### ISSUE TITLE
C1001 internal compiler error in VS2017

### ISSUE THREAD

**Issue by w1th0utnam3** [skypjack/entt#1]
For Visual Studio 2017 (compiler version `Microsoft (R) C/C++ Optimizing Compiler Version 19.10.25019 for x64`), the uniform initialization of the `pool` tuple in the `ComponentPool` constructor:
```
explicit ComponentPool(size_type dim = 4098) noexcept
    : pools{Pool<Component>{dim}, Pool<Components>{dim}...}
{
    assert(!(dim < 0));
}
```
results in the internal compiler error
> 1>main.cpp(12): fatal error C1001: An internal error has occurred in the compiler. 
> 1>(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\yyaction.cpp', line 7249) 
> 1> To work around this problem, try simplifying or changing the program near the locations listed above. 

A temporary workaround is to replace the uniform initialization with a standard initialization:
```
: pools(Pool<Component>{dim}, Pool<Components>{dim}...)
```
The line can be found [here](https://github.com/skypjack/entt/blob/7c0540fb9cdffb87ac6bd619eac57591f19e6027/src/component_pool.hpp#L128). I reported it as a compiler bug in the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/content/problem/60198/c1001-when-performing-uniform-initialization-with.html).

**Comment by skypjack** [comment]
Unfortunately it's an issue of VS compiler. I cannot do much for that. If you find a workaround that works on VS, I'd be glad to integrate it. I've not a copy of Windows on which to test it.

**Comment by w1th0utnam3** [comment]
Thanks you for your reply. As I mentioned in the last lines of the initial post, using
`: pools(Pool<Component>{dim}, Pool<Components>{dim}...)`
instead of
`: pools{Pool<Component>{dim}, Pool<Components>{dim}...}`
does the trick for VS2017, i.e. not using the uniform initialization syntax for the tuple.

**Comment by skypjack** [comment]
Yeah, I got it. Feel free to put it in a PR. Anyway, I'd like to have a switch like `#ifdef WIN32/#endif` where `WIN32` should be exported from cmake.

**Comment by skypjack** [comment]
Ok, I pushed on branch appveyor and [it works](https://ci.appveyor.com/project/skypjack/entt).
If you can confirm it, I'll merge the branch on master. Do not forget to build by using cmake, for it exports the expected variable `WIN32`.
Thank you. I'm looking forward for your feedback.

**Comment by w1th0utnam3** [comment]
Are you sure that you only want to enable this when cmake ran? As the registry, etc. is header only I didn't run it and instead directly included the headers.
Alternatives or extensions to your solution would be the macros `_MSC_VER` for the compiler version and `_WIN32` and `_WIN64` depending on the target [defined by the Microsoft compiler](https://msdn.microsoft.com/en-us/library/b0084kay.aspx).

**Comment by skypjack** [comment]
Actually I think cmake sets it up also when you run it through cygwin. Good point. `_MSC_VER` is more appropriate. Can you create a PR for that? Otherwise I'll update it in the afternoon.

**Comment by w1th0utnam3** [comment]
Makes sense, using `_MSC_VER` it's later possible to restrict this fix to older compiler versions when the bug is fixed. I could write a PR but unfortunately I'm not able do this before afternoon either.

________________________________
Von: Michele Caini <notifications@github.com>
Gesendet: 23.05.2017 8:27 vorm.
An: skypjack/entt
Cc: Fabian Löschner; Author
Betreff: Re: [skypjack/entt] C1001 internal compiler error in VS2017 (#1)


Actually I think cmake sets it up also when you run it through cygwin. Good point. _MSC_VER is more appropriate. Can you create a PR for that? Otherwise I'll update it in the afternoon.

**Comment by skypjack** [comment]
Found the time to updated it and it works just fine on appveyor as expected.
If you can confirm it your side, I'll merge everything on master and close the issue.
Thank you very much.

**Comment by w1th0utnam3** [comment]
Cool. Yes, it is working now.

**Comment by skypjack** [comment]
Upstream. Thank you.
