### ISSUE TITLE
Testing equality of meta_handle and meta_data structs

### ISSUE THREAD

**Issue by jdswebb** [skypjack/entt#1002]
I'm trying to write an undo/redo command for meta properties and I have the following data for doing this in a struct:

```
entt::meta_any new_value;
entt::meta_any old_value;
entt::meta_data property;
entt::meta_handle instance;
```

I want to be able to merge sequential commands operating on the same property and object and so find myself needing to compare the meta_data and meta_handle types.

I've included this background in case it seems like a flawed approach in general. If not, would it be correct to implement `operator==` for entt::meta_data returning true if the context and node ptr are equal? And likewise for entt::meta_handle returning true if the contained entt::meta_any is equal? 

Thanks

**Comment by skypjack** [comment]
It makes sense and seems feasible, yeah.
As for the `meta_handle`, I think it works already as `*h1 == *h2` (this forces a check between the underlying `meta_any` objects).

**Comment by jdswebb** [comment]
Thanks - I added it in to test but found another block for getting this working.

I can't see a way of setting a property with `meta_any`, but `meta_data` uses `meta_any` internally to call `meta_data_node::set`, so I think I can just add that in trivially too unless there's a reason not to?

**Comment by skypjack** [comment]
What do you mean with _setting a property with `meta_any`_? Property as in `meta_prop` or as in `meta_data`? 🤔

**Comment by jdswebb** [comment]
Sorry - property as in `meta_data`.

**Comment by skypjack** [comment]
🤔 it should work as-is already, `meta_any` has the following constructors:
```cpp
meta_any(const meta_ctx &area, const meta_any &other);
meta_any(const meta_ctx &area, meta_any &&other);
```
Therefore, `meta_any{*ctx, std::forward<Type>(value)}` is _ok-ish_ here.
Probably your type isn't copyable and you need an `any.as_ref()` at the call site instead?

**Comment by jdswebb** [comment]
You're right - it was showing up as an intellisense error for who knows what reason but compiles just fine!

**Comment by jdswebb** [comment]
Now that I've gotten a bit more familiar with the meta types, it seems to make more sense for my command struct to store a `meta_any` for the instance rather than a `meta_handle`. So the operator== is not needed any more from my point of view for that. Maybe it's nice to have anyway though to avoid potentially having to write  `a->operator*() == b->operator*()` to compare the underlying `meta_any` as you suggested before.
