### ISSUE TITLE
Serialize and Deserialize using reflection

### ISSUE THREAD

**Issue by TheExeQ** [skypjack/entt#1003]
Hello im trying to create a network system to sync my components between server and client. To do this im thinking that i could use the reflection system of entt to know which component and member to modify. 

After googling and asking chatgpt a lot for a solution i can't seem to find one that gets the result im looking for. I'd imagine that this would be the same if i wanted to save/load the data from a file, from the code snippet below is there a way to get/set the data?
```cpp
entt::entity entity = registry.create();
std::string component_class_name = "my_type";
std::string component_member_name = "value";
std::string component_member_type = "float";
float component_member_data = 21.4f;
```

I've tried using a bunch of different ways but all of them require me to use template of the type at some point it seems like which i can't really do since i need it to be runtime. The code below is as far as i've been able get before im requied to use compile time stuff.
```cpp
entt::meta<my_type>()
	.type(entt::hashed_string("my_type"))
	.data<&my_type::value>(entt::hashed_string("value"));

auto type = entt::resolve(entt::hashed_string("my_type"));
auto data = type.data(entt::hashed_string("value"));
```

Is there no way to set the data of my_type on entity using the 'type' and 'data' variables above? ChatGPT recommended something like this multiple times but there doesn't seem to exist something like this so im not sure where its getting that from but anyway, is there a way to do something like it?
```cpp
auto component = registry.get(type, entity);
data.set(component, component_member_data);
```

**Comment by skypjack** [comment]
You can get the storage from the registry using the component id (see `.storage(id)`), then an opaque pointer (as in `void *`) using the `.value(entt)` function. Then, since you know the component id, you can retrieve the meta type using `resolve(id)` and invoke the `.from_void` function to get a `meta_any` that wraps your component and that you can pass as an argument to your setter. Finally, `data.set(...)` is the way to go. 👍

**Comment by TheExeQ** [comment]
Do you mean something like this? because storage returns a ``entt::sparse_set*`` where ``.value()`` doesn't seem to exist :/
```cpp
    auto storage = registry.storage(componentId);
    
    void* componentPtr = storage.value(entity);
    const auto& metaType = entt::resolve(componentId);
    
    auto componentAny = metaType.from_void(componentPtr);
    componentAny.set(newValue);
```

**Comment by skypjack** [comment]
Ah, sorry, it's called `get` in the last version maybe? I changed it to `value` to avoid name clashing with derived classes.

**Comment by TheExeQ** [comment]
Yeah that was it, now i got it to work thanks a lot! :D
