### ISSUE TITLE
Entity id de/serialize

### ISSUE THREAD

**Issue by immerhart** [skypjack/entt#1006]
How can an entity id be de/serialized in order to send it over network?
I found `entt::to_integral`, which seems to convert the `entt::entity` to the underlying type (guess uint64 is the default).
What would be the counterpart, which converts the uint64 back to a `entt::entity`, so it can be get over the registry again?

Background: One node has the registry with all it's entities, it sends a network message (containing the `entt::entity`) to another node and this node would respond with the same entt::entity again, on receive of the response, the entt::entity should be get from the registry again.
It seems like there is some version encoded in the entt::entity as well, so I'm not sure if the to_integral would be enough and how to convert the uint64 back to the corresponding entity.

**Comment by skypjack** [comment]
`entt::entity` is just an enum class. `entt::to_integral` is literally a static cast to its underlying type (which is an `std::uint32_t` by default btw). To recreate an identifier from this value, you can use it as `entt::entity entity{value};` and that's it. 🙂

**Comment by immerhart** [comment]
Oh, sounds easy, will give it a try, thanks for the quick response! :)

**Comment by immerhart** [comment]
> Oh, sounds easy, will give it a try, thanks for the quick response! :)

It seems to work =)
