### ISSUE TITLE
Copy the entity and add it to the new registry

### ISSUE THREAD

**Issue by CleanCodeGames** [skypjack/entt#1008]
I have a basic registry containing entities with a set of components that I want to place in the game area.
How do I copy an entity and put it in the second registry with a new unique identifier? There used to be `clone()` and `visit()` methods, but now they are gone.

**Comment by CleanCodeGames** [comment]
Thanks! I've made some small changes and it works.
`void copy()
{
    entt::registry src;
    entt::basic_registry<entt::id_type> dst;

    static_cast<void>(dst.storage<int>());
    static_cast<void>(dst.storage<char>());

    const auto entity = src.create();
    const auto copy = dst.create();

    src.emplace<int>(entity, 42);
    src.emplace<char>(entity, 'c');

    for (auto [id, storage] : src.storage())
    {
        if (auto* other = dst.storage(id); other && storage.contains(entity))
        {
            other->push(copy, storage.value(entity));
        }
    }

    if (dst.all_of<int, char>(copy)) 
    {
        cout << dst.view<int>().get<int>(copy) << endl;
        cout << dst.view<char>().get<char>(copy) << endl;
    }
}

int main()
{
    copy();
    return 0;
}`

---
`output: 42 c`

**Comment by skypjack** [comment]
Thanks @Green-Sky 🙏❤️
