### ISSUE TITLE
clang basic_snapshot_loader deduction guide

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#1010]
Hi,

I recently got my code base working with clang again and  I found a warning that only happens when using clang:

```
/home/benjaminadamson/projects/rrogue/source/game/save.cxx:186:3: warning: 'basic_snapshot_loader' may not intend to support class template argument deduction [-Wctad-maybe-unsupported]
  entt::basic_snapshot_loader loader{registry};
  ^
/home/benjaminadamson/projects/rrogue/source/external/entt/entity/snapshot.hpp:159:7: note: add a deduction guide to suppress this warning
class basic_snapshot_loader {
      ^
1 warning generated.
[3/3] Linking CXX executable bin/main
```

To fix it I added my own deduction guide:
![entt deduction guide](https://user-images.githubusercontent.com/1087837/236276219-569707bd-75de-48ac-af61-b306b312a040.png)

I also managed to fix it by adding `Wno-ctad-maybe-unsupported` for my clang compilations.

I wanted to bring this issue to your attention (if you weren't already aware of it) and see if you thought any changes to entt should be warranted, or if your happy with the status quo.

Thanks so much for your time!

**Comment by bjadamson** [comment]
It seems the issue is complicated in general, I've been doing some more reading on the subject and wanted to share these links in case you were unaware as well:
https://quuxplusone.github.io/blog/2022/10/07/wctad-maybe-unsupported/

**Comment by skypjack** [comment]
Hi, thanks for pointing this out. Just a couple of questions: What version of EnTT are you using in this case? Are you able to pack a small reproducible example? I gave it a couple of tries and failed. I'm probably missing something obvious here. 🤔

**Comment by skypjack** [comment]
Ping.

**Comment by skypjack** [comment]
Closed as starving. Feel free to continue the discussion here if you have more details. Thanks.
