### ISSUE TITLE
entt::organizer::vertex::prepare does not create the required component pools

### ISSUE THREAD

**Issue by DonutVikingChap** [skypjack/entt#1013]
The documentation for entt::organizer mentions this:

> Since the creation of pools and resources within the registry isn't necessarily thread safe, each vertex also offers a `prepare` function which is used to setup a registry for execution with the created graph

However, the current implementation of `prepare` only successfully creates missing context variables, and does not create the component pools required by any "view" parameters of the user-provided systems. Here is a minimal example that demonstrates the bug:
```cpp
#include <entt/entt.hpp>
#include <iostream>

struct test_component {};

void test_system(entt::view<entt::get_t<test_component>> view) {
    (void)view;
}

int main() {
    entt::organizer organizer{};
    organizer.emplace<test_system>();

    entt::registry registry{};
    for (const entt::organizer::vertex& node : organizer.graph()) {
        node.prepare(registry);
    }

    const auto& s = registry.storage();
    auto it = s.begin();
    const auto end = s.end();
    ++it; // Skip "shortcut" storage.
    if (it != end) {
        std::cout << "good\n";
    } else {
        std::cout << "bad\n";
    }
}
```
This code currently prints "bad", which indicates that the registry contains no component pools except for the initial "shortcut" pool of type `entity_type`, despite `test_system` requiring `test_component`. If the `prepare` loop is replaced with simply `(void)registry.view<test_component>();`, then the program prints "good" as expected.

After digging into the code, I believe the main cause of the bug is in the `extract` function on line 129 of `organizer.hpp`: https://github.com/skypjack/entt/blob/master/src/entt/entity/organizer.hpp#L129
The intent here seems to be that the temporary `as_view` object should be implicitly converted to the concrete view type in order to invoke its internal `dispatch` method which is what actually constructs the view (and, consequently, its required pools): https://github.com/skypjack/entt/blob/master/src/entt/entity/helper.hpp#L48
Unfortunately, this conversion only happens when the actual callback function is called using `std::apply` with the result of `to_args` at https://github.com/skypjack/entt/blob/master/src/entt/entity/organizer.hpp#L300, and not when the result of `to_args` is discarded, which is what `prepare` does: https://github.com/skypjack/entt/blob/master/src/entt/entity/organizer.hpp#L310

A possible fix could be to explicitly construct the concrete view type inside of `extract` like this:
```cpp
return Type{as_view{reg}};
```

**Comment by skypjack** [comment]
Ah. Interesting. 🤔

**Comment by skypjack** [comment]
Actually, the test only checks context variables 🤦‍♂️ definitely my fault. Thanks for pointing this out. 🙏

**Comment by skypjack** [comment]
Apparently, all we need to do is to update the `extract` function as:
```cpp
} else if constexpr(internal::is_view_v<Type>) {
    return static_cast<Type>(as_view{reg});
}
```
Can you confirm it before pushing this change upstream? Thank you a lot. 👍
