### ISSUE TITLE
process/scheduler missing functions?

### ISSUE THREAD

**Issue by immerhart** [skypjack/entt#1017]
Hey, I had a look at the scheduler and process system and have a couple of questions:

1. Is it possible to get a feedback from the scheduler about the exit status?
1.1. e.g. if any of the processes fails, someone could implement a generic cleanup or whatever
1.2. I did it for e.g. fail, by coping the scheduler code and implemented it over the emitter, so you could connect to the fail signal
2. How can you get a reference to an instantiated process instance?
2.1. This is sometimes needed to do some bookkeeping.
2.2. At the moment I'm passing a pointer over the ctor of the process and in the ctor I'm assigning `this` (lethal XD)
3. Would it be possible to have something like: https://taskflow.github.io/taskflow/ConditionalTasking.html
3.1. This mechanic is really useful, if someone tries to build more complex flows
3.2. I found this https://github.com/skypjack/entt/wiki/Crash-Course:-graph, but I didn't understand how to use it, to be honest + I didn't find any link to the process/scheduler here
4. Is it possible to make a loop?
4.1. e.g. a process fails and the scheduler starts again from a specific process.

Thanks.

**Comment by skypjack** [comment]
> Is it possible to get a feedback from the scheduler about the exit status?

It's possible to know in which state a process is or is landing, then react accordingly.

> 1.1. e.g. if any of the processes fails, someone could implement a generic cleanup or whatever

You can do this in the process itself by implementing `failed`.

> How can you get a reference to an instantiated process instance?

You can't. Probably the continuation can return it though. No idea why you're assigning `this` btw nor what problem it's meant to solve, so I can't really help here probably.

> Would it be possible to have something like: https://taskflow.github.io/taskflow/ConditionalTasking.html

So, just a conditional continuation? Like _yeah, I'm done but please ignore my children_?

**Comment by immerhart** [comment]
> It's possible to know in which state a process is or is landing, then react accordingly.

How? Do you mean over the process entry points?
It would be nice to have some kind of final process, which is executed regardless if all the processes in the chain were successful or not. This handler would also get the exit code to act accordingly.

> You can do this in the process itself by implementing `failed`.

see previous comment (would be nice if someone wouldn't have to implement a generic logic in each and every process, even if the code would be the same for all of them).

> You can't. Probably the continuation can return it though. No idea why you're assigning `this` btw nor what problem it's meant to solve, so I can't really help here probably.

Would be good if that would be accessible... That's what I meant and how I did it:

```cpp
struct FailSignalingScheduler : entt::process<FailSignalingScheduler, tasks_delta_type>
{
    FailSignalingScheduler(FailSignalingScheduler** ppSched)
    {
        if(ppSched)
            *ppSched = this;
    }
}


FailSignalingScheduler* pSched;
tasks.attach<FailSignalingScheduler>(&pSched);
doStuffWith(pSched);
```

> So, just a conditional continuation? Like _yeah, I'm done but please ignore my children_?

I mean some mechanic to control the process flow. They do it over a return code which tells the scheduler which process to call next (if I understood it correct), further down, they also emulate a [switch](https://taskflow.github.io/taskflow/ConditionalTasking.html#ImplementSwitchControlFlow) behavior.

Background: I would like to use the scheduler/process to handle network requests in a distributed system. 
If a new request is received, multiple processes with multiple steps are scheduled. If the above features are supported, this logic could be easily used:
event1 -> some condition true -> do some thing -> do more -> other condition -> whatever
event1 -> some condition false -> do other thing -> restart
if any process fails, either send error back or retry operation (based on a condition)

**Comment by skypjack** [comment]
> How? Do you mean over the process entry points?

Yeah, I mean if using the `failed()` or `aborted()` functions and so on.

> It would be nice to have some kind of final process, which is executed regardless if all the processes in the chain were successful or not.

Technically speaking, it's easy to implement on top of what you've already.
Just share a common context across all processes and trigger it when the counter is 0.

> see previous comment (would be nice if someone wouldn't have to implement a generic logic in each and every process, even if the code would be the same for all of them).

Well, C++ supports inheritance and therefore common base classes to share logic. You don't have to reimplement it again and again. I strongly suspect that I need more context to understand your issue because so far it really sounds as an xy-problem.

> Would be good if that would be accessible... That's what I meant and how I did it:

I see, although you don't have to do it either. If your type is movable, just create it in the user space, do your stuff with it, then pass-move it (as in `std::move`) to `attach` and you're done. No need to do tricky things with a self pointer.

> I mean some mechanic to control the process flow.

Sounds interesting but it's definitely something to implement. It's not supported yet. I'm sorry.

**Comment by skypjack** [comment]
Usually, things go the other way around 🙂 can you provide a working example to reproduce your error, so that I can tell you what's wrong?
