### ISSUE TITLE
clone a registry, or at least a subset of components

### ISSUE THREAD

**Issue by mgiacal** [skypjack/entt#1020]
Hey, I have an use case where I need to multi buffer a `registry`, or at least the entities and most of the components. What would be the best way for copy/cloning a `registry`?

I couldn't manage to find a way to do it, based on previous issues and discussions, the api seems to have changed quite a bit.

Thanks.

**Comment by skypjack** [comment]
Do you want to do it with different registries or within the same registry? Because you can also multi-buffer in-place without having to restort to an external registry, as in `.storage<T>()` and `storage<T>("other"_hs)`.

**Comment by mgiacal** [comment]
> Do you want to do it with different registries or within the same registry? 
Different registries, I have a use case where I need to keep copies and be able to rollback to some older state.

**Comment by skypjack** [comment]
Well, you've a couple of possibilities here. If you want to copy everything at once, the best approach would be using meta or an erased function that you _bind_ to the given component type.
Do you happen to use meta already? Otherwise I can provide an example without it. Let me know. 👍

**Comment by mgiacal** [comment]
> Do you happen to use meta already? Otherwise I can provide an example without it. Let me know. 👍

I have no idea yet :) Yes please, few examples on different approaches would help me, thanks!

**Comment by skypjack** [comment]
Ok, so, if you want to only copy some types and know them, it's as easy as:
```cpp
auto &storage = from.storage<T>();
to.insert<T>(src.entt::sparse_set::begin(), src.entt::sparse_set::end(), src.begin());
```
Where `from` and `to` are the two registries. If you want to use named pools, just use the storage directly in all cases:
```cpp
auto &src = from.storage<T>("name"_hs);
to.storage<T>("name"_hs).insert(src.entt::sparse_set::begin(), src.entt::sparse_set::end(), src.begin());
```
Otherwise, you can do it blindly in a couple of ways. The first option is with meta, that is, a reflection system.
You can register the meta type on your own or use a storage mixin to do that on creation. Then you can use the meta function to do the copy.
Something along this line should (almost) work already:
```cpp
template<typename Type>
void copy(entt::sparse_set& base, entt::registry &to) {
    auto &src = static_cast<entt::storage_for_t<Type> &>(base);
    to.insert<Type>(src.entt::sparse_set::begin(), src.entt::sparse_set::end(), src.begin());
}

void register_meta() {
    using namespace entt::literals;
    entt::meta<Type>().func<&copy<Type>>("copy"_hs);
    // ...
}

void copy_all(entt::registry &from, entt::registry &to) {
    for (auto [id, storage] : from.storage()) {
        using namespace entt::literals;
        entt::resolve(storage.type()).invoke("copy"_hs, {}, entt::forward_as_meta(storage), entt::forward_as_meta(to));
    }
}
```
Finally, you can obtain something similar without meta too.
Just create a map of type ids and erased functions (like the `copy` function above, it decays to `void(*)(entt::sparse_set&, entt::registry &)` and `Type` disappears, you know), then use it as needed.

I hope it helped. Let me know if you have any questions. 👍

**Comment by skypjack** [comment]
I assume this was solved? Let me know if you have any other questions. I'll close the issue in a few days otherwise. Thanks.

**Comment by mgiacal** [comment]
> I assume this was solved? Let me know if you have any other questions. I'll close the issue in a few days otherwise. Thanks.

hey, sorry for the late response, and thanks for the explanation. It took me a while to test the suggested methods, specially to make sure also entities are copied. I ended up with something like that:

```
template <typename T>
static void copy_storage(entt::registry& dst, entt::registry& src) {
    auto& storage = src.storage<T>();
    dst.insert<T>(storage.entt::sparse_set::begin(), storage.entt::sparse_set::end(), storage.begin());
}

to.assign(from.storage<Entity>().cbegin(), from.storage<Entity>().cend(), from.storage<Entity>().size());
copy_storage<Type1>(to, from);
copy_storage<Type2>(to, from);
[...]
```

If you don't see any problems with that, then I would say it is solved :) thanks again!

**Comment by skypjack** [comment]
Oh, I see. With version 3.12, entities have their own storage, sorry. Forgot to mention it and the answer happened in the middle of the release. 😅
