### ISSUE TITLE
Friend private constructor for serializable type -- broke for me after updating to latest code

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#1021]
Hi, I just upgraded to the latest version of the code and serialization for a type I had previously worked stopped working after I upgraded. It's a Strong ID type, with private default constructor. Previously I was giving friend access to snapshot loader so that I could load these from a file, but nobody outside of zpp and entt had access to this private constructor. 

```C++
#pragma once
#include <cstdint>

#include <external/entt_fwd.hpp>
#include <external/zpp_full.hpp>

template <typename T, typename U=uint32_t>
class StrongId final
{
  U value_;

  friend zpp::bits::access;
  friend entt::snapshot_loader;
  using serialize = zpp::bits::members<1>;

  /// Private constructor
  StrongId(void) noexcept = default;

public:
  using type = T;
  using underlying_type = U;

public:
  explicit constexpr StrongId(U const value) noexcept
    : value_{value}
  {}

public:
  U const& underlying_value(void) const noexcept { return value_; }

public:
  bool operator==(StrongId<T, U> const&) const noexcept = default;
};

struct DUMMY;
static_assert(sizeof(StrongId<DUMMY>::underlying_type) == sizeof(StrongId<DUMMY>), "StrongId must be same size as underlying type");

/// ....
struct PassageNumber_Tag;
using PassageNumber = StrongId<PassageNumber_Tag>;
```

With the latest code, I hit a static assertion about my value not being `is_constructible`. It's debatable if my implementation of a strong ID type is good, but I was curious if you have any suggestions for allowing my StrongID type to pass the static assert if it's friends with the entity loader.

Thanks!

> /home/badamson/projects/rrogue/source/external/entt/container/../core/memory.hpp:185:17: error: static assertion failed due to requirement 'std::is_constructible_v<core::StrongId<PassageNumber_Tag, unsigned int>, const std::allocator<core::StrongId<PassageNumber_Tag, unsigned int>> &>': Ill-formed request
>                 static_assert(std::is_constructible_v<Type, Params..., const Allocator &>, "Ill-formed request");
>

**Comment by skypjack** [comment]
Hi, what do you mean with _the latest version_? Is it last tag (v3.11) or the last commit on `master`?

**Comment by bjadamson** [comment]
Last commit on master, I just downloaded it this morning

**Comment by skypjack** [comment]
Can I ask you what's the call that causes the problem? I'd like to reproduce it but I don't fully get how to do this yet. Sorry.

**Comment by bjadamson** [comment]
Here's the simplest program that can demonstrate the issue:
https://gist.github.com/bjadamson/f15e3c7524e1ab125572ecfff3656b49

If you make the default constructor private, [it fails to compile with the static assertion I mentioned above](https://gist.github.com/bjadamson/879327553d1a6f6889cd1eef6cca14bb). If you make the default constructor public, it succeeds. Previously the friend statements in the class definition were sufficient to grant zpp and entt special access to the private constructors. Now with the static assert, it doesn't work anymore.



Please note the includes at the top are just wrappers I had locally for entt and zpp_bits respectively:
https://github.com/eyalz800/zpp_bits/blob/main/zpp_bits.h

**Comment by skypjack** [comment]
Oh, I think I see the point now.
Briefly: before, the snapshot default-created an element to fill and then to pass to the `emplace` function. However, it works the other way around now: it default creates the element directly into the registry, then it fills it to avoid copies/moves/whatever.
So, technically speaking, I think making the storage rather than the snapshot loader friend is enough to solve your issue? 🤔 
In any case, someone also pointed out that the new approach doesn't fit well with `on_construct` listeners. I'm wondering if it's worth to flip back the way it works and sacrifice a few cpu cycles for more functionalities.

**Comment by notskm** [comment]
> I'm wondering if it's worth to flip back the way it works and sacrifice a few cpu cycles for more functionalities.

3.12 seems to fix a -Wnull-dereference warning on gcc when compiling with -O3, so reverting to the way 3.11.1 did things may reintroduce the warning. I can open an issue for this if you'd like.

**Comment by notskm** [comment]
> @notskm really? Do you know what's the cause? I never hit this warning so far.

I was using cereal with `entt::snapshot_loader` to load a `std::vector`. I had `-Wnull-dereference` enabled on gcc 12. It specifically happens under release mode in CMake and seems to be related to `-O3`. I imagine a check is being optimized out. Here's a minimal example project:
[example.zip](https://github.com/skypjack/entt/files/11768257/example.zip)

I traced the issue down to line 36479 of entt 3.11.1's single include, provided in the example.

I was about to open an issue, but 3.12.0 released like 20 minutes before I got to it and seems to have eliminated the warning.

**Comment by notskm** [comment]
Yeah, I can do that no problem. Just let me know when and point me to a commit.

**Comment by skypjack** [comment]
Cool, thank you very much @notskm you can find commit c1f6b11f7d30464509d84637ca01ed2d5ec7f775 on branch v3.12.x (I just pushed it). I'm looking forward to your feedback. Really appreciated. 🙏

**Comment by notskm** [comment]
@skypjack I cannot reproduce the warning on https://github.com/skypjack/entt/commit/c1f6b11f7d30464509d84637ca01ed2d5ec7f775, so it seems good to go.

**Comment by skypjack** [comment]
Should be bixed with tag `v3.12.1` @bjadamson can I ask you to give it a try, please?
Thank you very much. I'm looking forward to your feedback.
