### ISSUE TITLE
single include header file is outdated (release v3.12.0)

### ISSUE THREAD

**Issue by micb25** [skypjack/entt#1024]
Hey, 

first of all: thank you very much for your great work! I just realized that the published release **v3.12.0** contains an outdated single-include header file (`single_include/entt/entt.hpp`). This also affects the current `master` branch. The single header file reports:

```
#define ENTT_VERSION_MAJOR 3
#define ENTT_VERSION_MINOR 11
#define ENTT_VERSION_PATCH 0
```

Strangely, this is not the previous release **v3.11.1**, but the one before that.

Best regards,
Michael

**Comment by skypjack** [comment]
Oh, yeah, I never remember to update it. 😅 
I'm about to create a v3.12.1 to get backward compatibility with the snapshot class. I'll fix the single include file there too. 👍 
Thanks for pointing this out.

**Comment by skypjack** [comment]
Updated with the last tag (`v3.12.1`) and on the `wip` branch (soon `master`).
