### ISSUE TITLE
entt crashed on Windows 10 when turning on "/O2" or "/Ox" in VS2017

### ISSUE THREAD

**Issue by rockingdice** [skypjack/entt#1025]
Hi, I met a crash situation on Windows 10 using visual studio 2017. My project is working fine in debug mode. When I try to run in release mode, it crashed on the first usage of ```entt::registry```.

After some tests, I've found it's related to the speed optimization:"/O2" or "/Ox". If this option is turned on, even in debug mode the app will crash. 

I made a repro for you:

[cow3-2.zip](https://github.com/skypjack/entt/files/11811544/cow3-2.zip)

You can open the .sln from ```build/build-win32``` folder or generate a new project using cmake and run in debug/release mode to check the crash issue.

**Comment by skypjack** [comment]
Your _repro_ doesn't even compile for me. Neither the cmake version nor the vs solution.
In any case, I see that this is what it contains at the end of the day, literally:
```cpp
entt::registry reg;
auto ent = reg.create();
reg.emplace<test_moving>(ent);
reg.emplace<test_casting>(ent);
```
Well, I'm... I mean, pretty sure it works.

If you can pack a proper repro (like, a single cpp file), I'm more than willing to look into it.
If not, I'm sorry but this issue is somewhat invalid as-is because the error isn't reproducible and the provided code doesn't really point to any reason at the moment.

**Comment by rockingdice** [comment]
I'll check the repro, can you provide any error logs that fail the compilation? 

After some more debugs, I found if I turned off the optimization options in release mode, it'll lead to memory overflow here:
```
    virtual basic_iterator try_emplace(const Entity entt, const bool force_back, const void * = nullptr) {
        ENTT_ASSERT(!contains(entt), "Set already contains entity");

        if(auto &elem = assure_at_least(entt); free_list == null || force_back) {
            packed.push_back(entt);
            elem = entity_traits::combine(static_cast<typename entity_traits::entity_type>(packed.size() - 1u), entity_traits::to_integral(entt));
            return begin();
        } else {
            const auto pos = static_cast<size_type>(entity_traits::to_entity(free_list));
            elem = entity_traits::combine(entity_traits::to_integral(free_list), entity_traits::to_integral(entt));
            free_list = std::exchange(packed[pos], entt);                 <<<<<<<<<<<this line
            return --(end() - pos);
        }
    }
```
while the ```packed.size()``` is zero, it's still looking for the element at ```pos=0```.

And this only happens after it executes rehash:
```
    void rehash_if_required() {
        if(size() > (bucket_count() * max_load_factor())) {
            rehash(bucket_count() * 2u);                                <<<<<<after this line
        }
    }
```

The bucket is 8 and it wants to expand to 16. Before the rehash, it succeeds in emplacing several components on the same entity.
After the rehash, it'll go into the ```free_list = std::exchange(packed[pos], entt);``` line with the problem I mentioned above, and after the overflow, the program crashes randomly due to this problem.

Could you please share some insights/guesses that might lead to this issue? 
The project is working on my Mac both in debug and release mode anyway, so I think it might be related to different compilers/compile flags on different machines, but still have no clues...

**Comment by rockingdice** [comment]
I tested the repro on another pc, it's my fault to provide the generated projects.

The project needs to be re-generated via CMake: 
```
cd path/to/the/cow3-2/build/build-win32
cmake ../.. -GVisual Studio 15 2017 -Awin32
```
Then you should get a project that matches your machine's environment.
Open the .sln under the build-win32 folder, and right-click the target ```cow3-test``` to make it the launched one, switch to release mode and run. 
You should get a crash as expected.

**Comment by rockingdice** [comment]
Does entt support 32-bit Windows platform?

**Comment by skypjack** [comment]
Yeah. From what I see it's specifically an issue of the toolset v141. Everything works just fine with v142 instead and on other platforms. Are you experiencing something different?

**Comment by rockingdice** [comment]
@skypjack I don't know if my project supports v142, I'll try tomorrow, thanks!

**Comment by rockingdice** [comment]
@skypjack I've managed to upgrade my project to support v142 toolset, and now it works like a charm. I'll close this issue for now. If someone looks a way to upgrade cocos2d-x to support v142 toolset, you can try https://github.com/FlyingdutchmanC/Cocos2d-x_WIN64
