### ISSUE TITLE
Debug build warning, basic_snapshot_loader constructor

### ISSUE THREAD

**Issue by nmalg** [skypjack/entt#1027]
In debug builds, `ENTT_ASSERT(reg->empty(), "Registry must be empty");` generates warning:

> entt\entity\snapshot.hpp(214,9): warning C4996: entt::basic_registry<...>::empty': use .storage<Entity>().in_use() instead

**Comment by skypjack** [comment]
Available both on `v3.12.x` and `wip`. Soon on `master`. 👍

**Comment by skypjack** [comment]
Released as `v3.12.2`. 👍
