### ISSUE TITLE
Performance issue with basic_registry::alive()

### ISSUE THREAD

**Issue by akbyrd** [skypjack/entt#1042]
`basic_registry::alive()` (and by extension `basic_registry::empty()`) is currently a performance trap. It walks a linked list to determine its size and that linked list can be arbitrarily large. On my current project we have some development tools and debug checks that need to know how many entities exist. Unfortunately the current implementation makes this infeasible. We stream parts of the world in/out around the player and that means we can unload a large swath of entities in a short period of time, leading to a large free list for a while.

Would it be possible to implement a constant time version of this function?

**Comment by akbyrd** [comment]
As a side note, I'm not sure if the assertion in `generate_identifier` is behaving as desired or not. It appears to check that the entity is less than `reserved`, which is 0xFFFFFFFF. But I believe we need to ensure it's less than `entity_mask`.

**Comment by akbyrd** [comment]
I looked at the single include version when checking the behavior on the latest version (currently using a slightly older one). I didn't realize that file was out of date, this issue is likely moot.

**Comment by skypjack** [comment]
What version of EnTT are you using?
The last one has a constant time empty and a linear (in N number of entities) `each`.
It also return the number of deleted entities in constant time if needed.
Dunno how you can help here other than suggesting to upgrade maybe?

**Comment by akbyrd** [comment]
We're on 3.9.0. Since these issues are fixed in the latest version we'll update.
