### ISSUE TITLE
Clang warning: possible misuse of comma operator here [-Wcomma]

### ISSUE THREAD

**Issue by iK4tsu** [skypjack/entt#1044]
This line issues a clang warning when compiling with -Wcomma: https://github.com/skypjack/entt/blob/master/src/entt/meta/meta.hpp#L1803C32-L1803C32

```cpp
meta_iterator operator++(int) noexcept {
    meta_iterator orig = *this;
    return ++(*this), orig;
}
```

I'm assuming this is fixed by replacing the increment with `vtable(operation::incr, handle, nullptr);` or similar.

**Comment by skypjack** [comment]
What version of clang is it? What version of `EnTT`? What flags are you using?
The library is widely tested on the CI and I never hit this warning to be honest.

**Comment by iK4tsu** [comment]
I'm using the most recent version and clang 16 with C++20. I did try to reproduce this in compiler explorer with no luck. I'm also using the single include file. For the flags, we do use `-Weverything` without some stuff:
```
-Werror -Weverything -Wno-abstract-vbase-init -Wno-c++20-compat -Wno-c++98-compat-pedantic -Wno-covered-switch-default -Wno-ctad-maybe-unsupported -Wno-date-time -Wno-deprecated-copy-with-dtor -Wno-deprecated-copy-with-user-provided-dtor -Wno-disabled-macro-expansion -Wno-double-promotion -Wno-exit-time-destructors -Wno-extra-semi-stmt -Wno-float-conversion -Wno-float-equal -Wno-global-constructors -Wno-gnu-line-marker -Wno-implicit-int-conversion -Wno-implicit-int-float-conversion -Wno-invalid-noreturn -Wno-language-extension-token -Wno-missing-noreturn -Wno-missing-prototypes -Wno-padded -Wno-parentheses -Wno-range-loop-bind-reference -Wno-reserved-identifier -Wno-reserved-macro-identifier -Wno-shadow-all -Wno-shorten-64-to-32 -Wno-sign-compare -Wno-sign-conversion -Wno-switch-enum -Wno-undef -Wno-undefined-func-template -Wno-undefined-reinterpret-cast -Wno-unused-template -Wno-unsafe-buffer-usage -Wno-weak-template-vtables -Wno-weak-vtables
```

**Comment by skypjack** [comment]
What I don't get is why it returns this error while all other uses of the comma operator are fine.
I mean, I use this exact technique with **all** iterators, literally. Do you get a warning only in this case?

**Comment by iK4tsu** [comment]
I do hit other `-Wcomma` warnings, as well as some other stuff. Because we're using warnings as errors, I'm assuming not every warning is being reported, it stops with just a few warnings. Since I wasn't the one actually utilizing the lib, I was a bit short on the context. In the meantime, I compiled the project and these were the warnings emitted:

![Screenshot from 2023-07-31 19-59-41](https://github.com/skypjack/entt/assets/32413766/9ca2bd4c-37f2-47e4-8f45-2b3184017ea5)

So, there are also `-Wdocumentation` warnings in the mix. But probably these aren't the only ones. It just happens to stop compiling at this point.

These are all simple to fix though, I wouldn't mind submitting a PR if you agree it should be fixed.

**Comment by skypjack** [comment]
What version of EnTT is it? I have `-Wdocumentation` enabled and I can't find these errors anywhere.
Before submitting a PR, you should probably update to the latest version at least.

**Comment by iK4tsu** [comment]
> What version of EnTT is it?

We're using the single_include file (from master) because it was easier to integrate with our project. I was under the assumption that the file was updated to the latest version, but looking at the commit I was wrong. It matches the date from `v3.11.0` release (and taking a quick look inside the file it is indeed v3.11.0).  So, it is an outdated version. Looking at some of these documentation issues in the most recent version, it seems they have been fixed, such as:

https://github.com/skypjack/entt/blob/cb974bf5671c757cbce2e0248787bad616b06bf9/src/entt/core/memory.hpp#L107-L112

**Comment by iK4tsu** [comment]
Yup, I've tried with the single_include file from `v3.12.2` and I had no documentation warnings.

**Comment by iK4tsu** [comment]
Btw, for a quick patch in `3.12.2` should we do

```cpp
meta_iterator operator++(int) noexcept {
      meta_iterator orig = *this;
      vtable(operation::incr, handle, nullptr);
      return orig;
  }
```

The fix in `wip` https://github.com/skypjack/entt/commit/d08a07044cd2eb9f0e38952dde573a745f083c0d is not applicable since the signature is different, so I'd like to confirm what the equivalent in `3.12.2` is.

**Comment by skypjack** [comment]
Technically speaking, it's not a bug nor a blocking issue. I don't cut releases in this cases. However, I'm not opposed to doing it if you need it.
Note that you can regenerate the single include file on your own if that's what you need though. See the scripts dir. 👍

**Comment by iK4tsu** [comment]
Ok, for the time being, we can just do the patch locally. Thank you for your help with this :slightly_smiling_face:

**Comment by skypjack** [comment]
You're welcome. Thanks for pointing this out. 👍
