### ISSUE TITLE
Checking how much memory is currently in use

### ISSUE THREAD

**Issue by buttception** [skypjack/entt#1049]
1) Is there a way to check how much memory is currently in use by entt?
2) Can I provide a custom allocator to entt?

**Comment by skypjack** [comment]
You can provide a custom allocator (almost all classes are allocator-aware, just look at their definition).
Then, yes, you can track memory consumption with your allocator or a debug-only decorator for it.

**Comment by buttception** [comment]
Thanks a lot!
