### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#105]
Hi all,

I just realized that we need a logo for `EnTT`. :-)  
Because the library is made out of the ideas of its users, it would be great if the same happens also for the logo!!  
Someone wants to suggest something or make a contribution directly with an image?
It would be really appreciated!!

Thank you very much for your help!!

**Comment by Kerndog73** [comment]
Since this is a library that is primarily used for the creation of games, I think some pixel art is in order.

**Comment by ArnCarveris** [comment]
@Kerndog73 Agree. 

Example of minimalist logo of: [raylib](https://github.com/raysan5/raylib/blob/master/logo/raylib_256x256.png)

**Comment by Kerndog73** [comment]
This is why I'm a programmer and not an artist!

![entt_512](https://user-images.githubusercontent.com/10371177/41899836-924e6594-796c-11e8-8d94-cab400f49c2a.png)

The idea was there are three circles. A circle for _entities_, a circle for _components_ and a circle for _systems_. Where the three circles overlap, we have EnTT, which joins the three concepts together. A good logo needs a little bit of symbolism but the bright colors are a bit over-the-top and it kind of looks like EnTT is a graphics library or something.

Maybe this will inspire a real artist to have a crack!

**Comment by skypjack** [comment]
@Kerndog73 Really, really appreciated!! Come on guys, make your proposal!! :-)

**Comment by ArnCarveris** [comment]
@skypjack It's okay? 
![image](https://user-images.githubusercontent.com/783361/41903085-b47d7b8e-793d-11e8-95d7-49c30b651a54.png)

**Comment by skypjack** [comment]
@ArnCarveris It could be ok, of course. Actually, both your images could work.. Let's see if others want to participate before to decide!! ;-)

**Comment by mario-deluna** [comment]
Maybe something more simple:

![entt0](https://user-images.githubusercontent.com/956212/41903352-f1cfebf0-7935-11e8-80da-c0950fe64ba7.png)

A Penrose triangle:

![entt3](https://user-images.githubusercontent.com/956212/41903416-2200ba7a-7936-11e8-822a-158294bcab7a.png)

Ant as a foundation for your game:

![entt](https://user-images.githubusercontent.com/956212/41903528-79072d7c-7936-11e8-8dcd-0c10c039737c.png)

Multiple components working with each other 

![entt1](https://user-images.githubusercontent.com/956212/41903565-8b85693c-7936-11e8-91b9-6ff8e943b06d.png)

Its a circle there is no meaning here:

![entt2](https://user-images.githubusercontent.com/956212/41903583-94fa0ff4-7936-11e8-859c-2ee90ba097b4.png)

**Comment by ArnCarveris** [comment]
@mario-deluna Vote for **A Penrose triangle**

**Comment by skypjack** [comment]
@mario-deluna I really, really love the one with the circle, even if it has no meaning. Thank you very much for these amazing images!!

**Comment by m-waka** [comment]
I'm also no artist. But tried to mix my favourite ideas from @mario-deluna, @ArnCarveris  and @Kerndog73  up a little bit with inkscape:
![entt_proposal](https://user-images.githubusercontent.com/20254682/41965853-eb96607a-79fd-11e8-97a2-9d6989dd56fb.png)
![entt_proposal_bw](https://user-images.githubusercontent.com/20254682/41965863-f2db4efe-79fd-11e8-8673-0dd195192246.png)
The circles as the entity in the center and the Components surrounding it loosely:
![entt_proposal2](https://user-images.githubusercontent.com/20254682/41965877-fba54b70-79fd-11e8-9df1-009be2a893b0.png)
![entt_proposal2_bw](https://user-images.githubusercontent.com/20254682/41965907-0d363f16-79fe-11e8-88dc-0373596be83c.png)
But I think this should probably better be done by an artist. :smile:

**Comment by eliacoan** [comment]
Mixed something already in here ;-)
![entt](https://user-images.githubusercontent.com/29502665/41966271-fb831ce8-79fe-11e8-8a2a-32228a49ed60.png)

**Comment by eliacoan** [comment]
Another take, seeing you like the circle ide
![entt_2](https://user-images.githubusercontent.com/29502665/41967057-02e7c874-7a01-11e8-978a-1a2e8ee2a97d.png)
a!

**Comment by eliacoan** [comment]
Last one, sorry for the flooding, hope you'll find your logo! 😄 
![entt_3](https://user-images.githubusercontent.com/29502665/41968417-ab353ae0-7a04-11e8-8569-0dc6fa64783e.png)

**Comment by skypjack** [comment]
@eliacoan Flooding?? Absolutely!! You're welcome and thank you, really thank you for participating!!
Feel free to flood if you have something else to propose, I'll keep the issue open for another couple of days probably. :+1:

**Comment by m-waka** [comment]
Just a small variation:
![entt_proposal3](https://user-images.githubusercontent.com/20254682/41970554-883869ac-7a0b-11e8-8146-8a9c37567261.png)
![entt_proposal3_bw](https://user-images.githubusercontent.com/20254682/41970563-8c92c592-7a0b-11e8-9267-9eb8c94059e6.png)

**Comment by skypjack** [comment]
@m-waka I know I'm asking much to you, but I think it would be great also something along your line with the E on the left, three circles on the right in a column with the letters N, T, T within them, everything within the external frame. What about?

**Comment by m-waka** [comment]
Ok, this is how I interpret yaour description:
![entt_proposal5](https://user-images.githubusercontent.com/20254682/42026272-f63a7880-7ac6-11e8-852a-8881445f1e77.png)
![entt_proposal5_bw](https://user-images.githubusercontent.com/20254682/42026278-fafcdeb2-7ac6-11e8-9a8a-9886c08347c5.png)
But I like this a bit more:
![entt_proposal4](https://user-images.githubusercontent.com/20254682/42026301-0de2fdc2-7ac7-11e8-953b-cc682c319e7b.png)
![entt_proposal4_bw](https://user-images.githubusercontent.com/20254682/42026303-1238c050-7ac7-11e8-941e-a14005be6f78.png)

**Comment by richardbmx** [comment]
Hello my name is Richard I am a graphic designer and I like to make open source contributions, I see that you are looking for a logo for your app, I would like to present my proposal and if you like I send all the files you need to use it.

Inspired by the current logo of the three circles I have given a more modern and current form which incorporates the letters ENTT and the three circles without closing in its entirety using the three colors of the original logo.

![logo87](https://user-images.githubusercontent.com/35604837/42126932-b9dda766-7c5d-11e8-86a6-e57c8f28515f.png)

If you want any change or other variation of the logo do not hesitate to ask

Regards..

**Comment by dbacchet** [comment]
@richardbmx they look great! I particularly like the first and the forth (same logo with color and solid black).

**Comment by richardbmx** [comment]
@dbacchet  Good thing you really like it is the same logo but in different variations that guarantees that the logo is functional

**Comment by skypjack** [comment]
@richardbmx Thank you for participating!! Your proposal looks great.  
I'm from mobile now, so I'll look at them better when I'm back home. BTW I like them.  

I think the next step will be to pick up the best proposals, make some small changes and ask to users to vote.

**Comment by skypjack** [comment]
Time to recap. These are my favorites:

1. I like [this](https://user-images.githubusercontent.com/956212/41903583-94fa0ff4-7936-11e8-859c-2ee90ba097b4.png) one by @mario-deluna for no particular reason, I just like it.

2. I like the _three circles_ of @m-waka, in particular [this one](https://user-images.githubusercontent.com/20254682/41965907-0d363f16-79fe-11e8-88dc-0373596be83c.png) and [this one](https://user-images.githubusercontent.com/20254682/42026303-1238c050-7ac7-11e8-941e-a14005be6f78.png) (I like much the one with circles having different sizes, but we can adjust it later). Three circles like the three parts of the whole: entity, component and system. It makes sense after all.

3. I like [the first and the fourth](https://user-images.githubusercontent.com/35604837/42126977-bd6d2ec8-7c5e-11e8-9f14-a6b23b93df72.png) from @richardbmx (as mentioned also by others). The former as the _three parts concept_ mentioned above, the latter is good and it's enough for me.

I want to ask to the authors if they can release their images under a license that allow me as owner of the project to use the logo for any purpose in future.  
Otherwise, let me know and I'll remove your proposal from the list above.

Then, well... let's vote!! I wrote `EnTT`, but it wouldn't have reached this point without you, so it's right to involve users in giving it a shape!! :blush: 

I'd say to vote with the _reaction_ icons:
* :+1: for the proposal made by @mario-deluna 
* :laughing: for the proposal made by @m-waka 
* :heart: for the proposal made by @richardbmx 

Once voted, let's see if I wake up tomorrow still democratic or not!! :joy:

**Comment by loudedtwist** [comment]
😆

**Comment by skypjack** [comment]
@loudedtwist Please, use the _reaction button_ directly on my comment above (the one with an emoji top right near to the ellipsis), so as to collect all the votes together. Thank you.

**Comment by loudedtwist** [comment]
oh, sorry, sure = )

**Comment by richardbmx** [comment]
Hello happy day all my designs are under license, you can use it wherever and however you want 

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="License of Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is under <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons license Attribution-ShareAlike 4.0 International</a>.

**Comment by richardbmx** [comment]
@skypjack  Ready send you an email greetings ...

**Comment by richardbmx** [comment]
All File

[Google Drive](https://drive.google.com/open?id=1XfJseugodAOUEXGkFEAgYDhRuh8-Pqzg)

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/"><img alt="License of Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><br />This work is under <a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons license Attribution-ShareAlike 4.0 International</a>.

**Comment by skypjack** [comment]
@richardbmx I'm working on this. Soon the logo will be online. Thank you very much.

**Comment by richardbmx** [comment]
@skypjack  Excellent I am glad to know that you will use my proposal

**Comment by skypjack** [comment]
Well, this is democracy. Right? :-)

**Comment by richardbmx** [comment]
looool... so is

**Comment by skypjack** [comment]
[Here](https://github.com/skypjack/entt/tree/logo) it is. Mention: _Logo Copyright (c) 2018 Richard Caseres_. Is it fine for you?

**Comment by richardbmx** [comment]
@skypjack for me this perfect thank you very much for using my work

**Comment by skypjack** [comment]
You're welcome. It looks fine. I think I'll merge it on `master` tomorrow. Thank you very much.

**Comment by skypjack** [comment]
On `master`. Thank you again @richardbmx for your proposal.
