### ISSUE TITLE
`entt::registry::empty()` is deprecated, but (...) has no member named `in_use()`

### ISSUE THREAD

**Issue by colleen05** [skypjack/entt#1051]
Hi,
I have the following code:
```c
if(registry.empty()) {
    consoleLog.push_back({0, "No entities in scene."});
    return;
}
```
My compiler tells me:
```
warning: 'empty' is deprecated: use .storage<Entity>().in_use() instead
```
So I change the code to this:
```c
if(!registry.storage().in_use()) {
    consoleLog.push_back({0, "No entities in scene."});
    return;
}
```
Now, my compiler tells me this:
```
error: no member named 'in_use' in 'entt::iterable_adaptor<entt::internal::registry_storage_iterator<entt::internal::dense_map_iterator<__gnu_cxx::__normal_iterator<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>> *, std::vector<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>>>>'
```

What's going on? I'm using `single_include/entt/entt.hpp` with version v3.12.2.

**Comment by colleen05** [comment]
Just to add, I'm completely new to EnTT, and I'm _not_ trying to use the issues page as a support forum. I may be making a mistake that would be obvious to people familiar with the library.

I still feel like being warned about deprecation, suggested to use a different function, and then finding out that function doesn't actually exist, is a bit odd. Could this be an issue with the single-include header?

**Comment by skypjack** [comment]
> I still feel like being warned about deprecation, suggested to use a different function, and then finding out that function doesn't actually exist, is a bit odd

I mean, the warning says `storage<Entity>().in_use()` and you did `storage().in_use()`.
I find being notified of a change with a description of what to do, doing a different thing and then being surprised why it doesn't work is just as weird.
Probably that function exists on the *right* storage though:
```cpp
if(registry.storage<entt::entity>().in_use() == 0u) {
    // no entities currently in use here
}
```

**Comment by colleen05** [comment]
Thanks for pointing this out to me!
I failed to read the documentation last night, and I misunderstood the use of the function.

I do have an additional question:
Why does it want me to specify type _Entity_, when there's just one entity type (essentially a uint32)? Can registries store more than just entities? Or is there some non-purely-ECS thing you can do like, for example, creating an entity class that contains the uint32 EnTT needs, but also storing a name string for in-game referencing?

**Comment by skypjack** [comment]
Well, yeah, the entity type is customizable as everything else in EnTT. You can have 64b entities or use a custom class if you like.
That being said, `storage()` has a different purpose and `storage<T>()` wants a `T`. Since you're asking for the entity storage... 🤷‍♂️
