### ISSUE TITLE
connect construct/destroy listeners that accept entity ids and component references

### ISSUE THREAD

**Issue by davidc538** [skypjack/entt#1059]
```cpp
#include <entt/entt.hpp>

struct TestType {
};

void FreeFunc(entt::entity id, entt::registry& registry, TestType& t) {
}

int main(int argc, char** argv) {
    entt::registry registry;
    registry.on_construct<TestType>().connect<&FreeFunc>();
}
```

I'd like my listener function to accept this info about the new component being created but cannot figure out how to do this. Is it supported by entt? I found this signature at the link below but cannot get this to compile.

https://github.com/skypjack/entt/issues/385

**Comment by davidc538** [comment]
Sorry, shortly after posting I figured out how to do this...

```cpp
struct TestType {
};

void FreeFunc(entt::registry& registry, entt::entity id) {
}

int main(int argc, char** argv) {
    entt::registry registry;
    registry.on_construct<TestType>().connect<&FreeFunc>();
}
```

is there a way to do this with a reference to the newly created component in the function signature?

**Comment by davidc538** [comment]
I'm unable to find an example in the doc, could you provide an example?

**Comment by skypjack** [comment]
Well, yeah, [here](https://github.com/skypjack/entt/blob/717897052477515260bde3fd21fe987662666621/test/example/signal_less.cpp) you have a couple of specializations that enable or disable signal support for the different components.
In you case, you can implement your own mixin and just enable it for all types as:
```cpp
template<typename Type, typename Entity>
struct entt::storage_type<Type, Entity> {
    using type = my_own_mixin<basic_storage<Type, Entity>>;
};
```

**Comment by davidc538** [comment]
are these examples up to date? i think `sigh_mixin` has been replaced by `sigh_storage_mixin` ?

**Comment by skypjack** [comment]
Quite the opposite actually 🙂 it's `sigh_mixin` since the end of the last year or so.

**Comment by davidc538** [comment]
hmm, well i don't have a `entt/entity/mixin.hpp`, could the package be broken in vcpkg?
```
% ls ~/C/vcpkg/installed/x64-linux/include/entt/entity 
component.hpp  entity.hpp  fwd.hpp  group.hpp  handle.hpp  helper.hpp  observer.hpp  organizer.hpp  registry.hpp  runtime_view.hpp  snapshot.hpp  sparse_set.hpp  storage.hpp  storage_mixin.hpp  view.hpp
```

**Comment by davidc538** [comment]
ahh yes, my repo was horribly out of date.

```cpp
struct Test {
};

template<typename Storage>
struct MyMixin : entt::sigh_mixin<Storage> {
};

template<typename Entity>
struct entt::storage_type<Test, Entity> {
	using type = MyMixin<entt::basic_storage<Test, Entity>>;
};
```
i still don't understand how to customize the callback signature though? i can see that the `sigh_mixin` class has `sigh_type`  which gets instantiated as `construction` and `destruction` but even the `publish` methods don't accept the component?

**Comment by skypjack** [comment]
It's not like this:
```cpp
template<typename Storage>
struct MyMixin : entt::sigh_mixin<Storage> {
};
```
You must implement your own mixin. That is, you can just copy the sigh mixin and change the relevant parts.
For example, add a type parameter to the signal type and pass the component to the callback in the `emplace` function.
All other functions such as move operators, constructors and so on are more or less identical instead.
That being said, again, I'd start with getting the component from the registry and only implement my own mixin later on if needed. Not sure why you are ignoring this option to be honest. 🤔

**Comment by davidc538** [comment]
I apologize for being stubborn, I just really like to explore my options. Thank you for your assistance :+1:

**Comment by skypjack** [comment]
No worries at all. You aren't stubborn, don't get me wrong.
What I mean is that using the current mixin is a good compromise because it already takes care of empty types, stable types and so on.
However, copying it and modifying the signal type is also a perfectly valid solution. I can assist you if you want to give it a try. Not a big deal. 👍

**Comment by davidc538** [comment]
Thanks, but could I get you to look at line 40 in [this example](https://pastebin.com/YqAgARws)? uncommenting it causes compile errors in both clang and gcc with regards to the on_construct function missing.

**Comment by skypjack** [comment]
Single type groups are not allowed. I mean, there is nothing to group in a tightly packed pool. 🙂

**Comment by davidc538** [comment]
adding a second type doesn't fix the compile problem. can you have a look [here?](https://pastebin.com/UY6F0vpK)

**Comment by skypjack** [comment]
Oh, wait, my fault. You disable signals. Groups use them actually. It won't compile any time soon if you disable signals. Sorry.
