### ISSUE TITLE
Ivalid code example in the docu

### ISSUE THREAD

**Issue by Green-Sky** [skypjack/entt#1061]
the docu uses `.use<type>()` inline and "uses its return value", which does not exists anymore (`void`)

```c++
for(auto entity : registry.view<position, velocity>().use<position>()) {
    // ...
}
```
https://github.com/skypjack/entt/blob/master/docs/md/entity.md?plain=1#L1820

why does `.use<>()` not just return a ref to self? :thinking:  i had to change ever use of `use` i had to something like:
```c++
auto view = reg.view<type1,type2>();
view.use<type2>();
...
```

**Comment by skypjack** [comment]
Oh. I guess I missed the opportunity. 😅 
The previous version returned a completely different view and I wanted to make it clear that this is no longer the case.
However, returning a reference would have been just as good. Fair enough.
Thanks for pointing out the issue in the doc. 🙏
