### ISSUE TITLE
Outdated usage of the `basic_view::use` function in the docs

### ISSUE THREAD

**Issue by keiwando** [skypjack/entt#1066]
The v3.12.0 release changes the `basic_view::use` function to have a `void` return type and modify the view in place, as mentioned in the changelog:

> basic_view<...>::use<T>() is a self-contained, non-const function that changes the view in-place

But this line in the docs still shows the old usage, which now doesn't compile anymore:
https://github.com/skypjack/entt/blob/717897052477515260bde3fd21fe987662666621/docs/md/entity.md?plain=1#L1820

**Comment by skypjack** [comment]
Isn't this one a dup of #1061 ?

**Comment by keiwando** [comment]
Totally is, not sure how I missed that. Sorry!

**Comment by skypjack** [comment]
Not a problem. Thanks for pointing this out! 👍
