### ISSUE TITLE
Get variable from meta_any by reference instead of copy?

### ISSUE THREAD

**Issue by meinukey** [skypjack/entt#1074]
I'm using entt::meta to automatically serialize data in user-created types. For structs and classes, I'm doing the following for each member:

```
entt::meta_any value = instance.get(child->GetPropId());
child->Deserialize(stream, value);
instance.set(child->GetPropId(), value);
````

Where `instance` is a `meta_any` containing the structure object and `child` is a node object that I use for serialization and, in this case, represents a variable inside the struct referenced by `instance`.
As far as I understand, `value` is a copy of the variable and not a reference. This is not scaling too well on things like large arrays in terms of performance and I haven't measured it yet, but I suspect one of the bottlenecks is this piece of code. Is there a way to get a member variable by ref instead of by copy?

**Comment by skypjack** [comment]
Yeah, sure, it's all about using `entt::as_ref_t` when registering it with the factory.
You can find the details in the doc and many examples in the test suite but feel free to reach out for a quick and dirty example if you can't get it to work.

**Comment by meinukey** [comment]
Thank you so much, that worked a treat!
