### ISSUE TITLE
runtime_view assertion failed on windows (invalid comparator)

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#108]
Hello, 

I'm sorry the implementation seem's to be broken only on windows:

<img width="1646" alt="capture d ecran 2018-07-01 a 23 32 52" src="https://user-images.githubusercontent.com/21139416/42139088-73d27d2a-7d87-11e8-9cf3-69d0ddc7a203.png">
<img width="1680" alt="capture d ecran 2018-07-01 a 23 33 40" src="https://user-images.githubusercontent.com/21139416/42139089-741223a8-7d87-11e8-9f1d-8f84ed6452e8.png">
<img width="1674" alt="capture d ecran 2018-07-01 a 23 33 58" src="https://user-images.githubusercontent.com/21139416/42139090-742b0e7c-7d87-11e8-80e2-f4bdcb17f2b8.png">
<img width="1336" alt="capture d ecran 2018-07-01 a 23 34 16" src="https://user-images.githubusercontent.com/21139416/42139091-74413c4c-7d87-11e8-8d9c-e23daa24ed4a.png">

solution:
https://stackoverflow.com/questions/45966807/%D0%A1-invalid-comparator-assert
https://stackoverflow.com/questions/979759/operator-and-strict-weak-ordering

This compiler is a bananana

Tell me when you will have a possible patch i will modify the library directly on windows to test it !

**Comment by skypjack** [comment]
The best part is that appveyor works as a charm. :1st_place_medal: 
I think I'll fix it tomorrow, even though I'm not sure about it.

**Comment by Milerius** [comment]
You are so lucky xD, i will try on my computer your solutions if you want, i don't know what is the problem exactly but is probably the operator< which is mixed with other operators, to hard for msvc to parse and understand xD

**Comment by Milerius** [comment]
<img width="793" alt="capture d ecran 2018-07-01 a 23 47 27" src="https://user-images.githubusercontent.com/21139416/42139188-238d2566-7d89-11e8-900e-899062e7c1f3.png">

this is the result from my ci, (im using jenkins with ctest) (if you are using googletest and just ./test it's will not complain)

**Comment by skypjack** [comment]
No, it's my fault probably. Not sure the comparator respects the strict weak ordering actually. I forgot the constraint, this isn't the first time, shame on me!

**Comment by skypjack** [comment]
I'm from mobile and it's midnight here, so... Btw, something like this probably could work:
```
    RuntimeView(pattern_type others) ENTT_NOEXCEPT
        : pools{std::move(others)}
    {
        auto it = std::find_if(pools.begin(), pools.end(), [](const auto *view) { return view == nullptr; });
        
        if(it == pools.end()) {
            it = std::min_element(pools.begin(), pools.end(), [](const auto *lhs, const auto *rhs) {
                return lhs->size() < rhs->size();
            });
        }
 
        // brings the best candidate (if any) on front of the vector
        std::rotate(pools.begin(), it, pools.end());
    }
```
I'll wrap my mind around the issue tomorrow morning otherwise.

**Comment by Milerius** [comment]
my test pass with this snippet ! 

Thank's you !

Will wait for tommorow for a possible merge + mini tag 2.7.1

**Comment by skypjack** [comment]
Wow, I did it? One shot, one kill!! Come on!!  
Yeah, tomorrow I'll cut a new release for sure.  
Thanks for pointing out the error.

**Comment by Milerius** [comment]
Yeah, i'm surprised that's other compiler doesn't complain about this error.

**Comment by skypjack** [comment]
You shouldn't be surprised. The standard doesn't mandate for an error. It's undefined behavior if the compare function doesn't respect the constraints.  
This time Microsoft helped us by detecting it even though it wasn't mandatory.

May I ask you to try this one?
```
    RuntimeView(pattern_type others) ENTT_NOEXCEPT
        : pools{std::move(others)}
    {
        const auto it = std::min_element(pools.begin(), pools.end(), [](const auto *lhs, const auto *rhs) {
            return (!lhs && rhs) || (lhs && rhs && lhs->size() < rhs->size());
        });
 
        // brings the best candidate (if any) on front of the vector
        std::rotate(pools.begin(), it, pools.end());
    }
```
Not sure it works (I'm writing it on the bus while going to work), but it's a slightly faster alternative to the _midnight snippet_. 

Thank you.

**Comment by Milerius** [comment]
it's also work with the new snippet ! congratulation

**Comment by skypjack** [comment]
Upstream. Thank you for your help.
