### ISSUE TITLE
Is there a way to retrieve a view with at least one of the specified components?

### ISSUE THREAD

**Issue by kewyj** [skypjack/entt#1084]
I am looking through the crash course, and the one thing I found closest to what I need is a view pack. Would this work?
Also curious about how EnTT works with components with inheritance. Would `registry.view<base>();` yield all entities containing base/derived components?

**Comment by skypjack** [comment]
> Is there a way to retrieve a view with at least one of the specified components?

What does it mean _a view with at least one of the specified components_? As if it were an _or_ rather than an _and_?

> Would registry.view<base>(); yield all entities containing base/derived components?

Definitely no. Stop thinking in terms of hierarchies when it comes to using an ECS model.

**Comment by kewyj** [comment]
> As if it were an or rather than an and?
Yes exactly that!

**Comment by skypjack** [comment]
Then no, I'm sorry. Views return only the entities that have all the elements.
If you want those that have at least one of components and you want them only once, probably the best is to iterate multiple views separately and put the entities in a set.
However, this really, really, **really** smells of an XY-problem. Something like _I have states idle and jump and I want to find the entities that have a state, no matter what_. Just rethink your design. You don't need an _or-like_ view here. You just need to refactor your component types and probably a more ECS-y thinking. 👍

**Comment by kewyj** [comment]
Hmm, ok! I'll try to rethink my approach. Thanks so much!
