### ISSUE TITLE
Possible reasons for crashing at "slot not available"?

### ISSUE THREAD

**Issue by kewyj** [skypjack/entt#1086]
Hello, may I know what are the possible reasons for crashes at "slot not available"? 

Call stack is something like:
destroy(e1)
entity e2 = to_integral(create entity)
add/replace_component(e2, component) (crash)

Would appreciate any and all advice! Thanks in advance!!

**Comment by skypjack** [comment]
Callstack isn't that one, definitely. You get this error when you try to assign a component to an entity that has it already.

**Comment by kewyj** [comment]
Even when using `emplace_or_replace` though?

**Comment by skypjack** [comment]
No, `emplace_or_replace` doesn't incurr in this error because it performs the check for you under the hood.

**Comment by kewyj** [comment]
Hmmm, is there any other possible reasons for crashing at `emplace_or_replace`? 😅

**Comment by skypjack** [comment]
If you've a small, reproducible example, I can look into it to help.
Otherwise 🤷‍♂️ the reason for the error is the one above. It can be a mistake on a single threaded application or a concurrent access but I can't tell since I don't know what the real code does. I'm sorry.
