### ISSUE TITLE
Incorrect void type check in registry's assure function

### ISSUE THREAD

**Issue by ZeroMemes** [skypjack/entt#1088]
The changes made in commit https://github.com/skypjack/entt/commit/d5613e8c6576b98c4fa2998434a1e8b535a3bdb1 seem to be a typo. Referencing the other "use is_void_v as needed" commits, the correct substitution should be `std::is_void_v<Type>`.

**Comment by skypjack** [comment]
Shame on me. Good catch! Thanks. 👍
