### ISSUE TITLE
Use Travis-CI to update packages

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#109]
A few days ago, I learnt about continuous integration and setup travis with [one of my projects](https://github.com/Kerndog73/STELA) for the first time. CI is awesome! Test driven development is awesome! Why wasn't I doing this before?!

Anyway, I was thinking. Someone has to run a script or two when a new version of EnTT is released. I thought that maybe travis could do it. So I did a little research, and found this:

```yaml
deploy:
  provider: script
  script: bash update_packages.bash $TRAVIS_TAG
  on:
    tags: true
```

This will invoke `update_packages.bash` when a new tag is created. `update_packages.bash` could update packages for homebrew, vcpkg and any other package managers that might be supported in future like conan, spack, hunter, buckaroo, cget. The only change that will be required for the homebrew `update.bash` will be to clone instead of pull. I removed the section that does `brew audit` because it just produces annoying, nitpicky error messages.

This is just an idea and it might not be necessary but I wanted to see what you think.

This will avoid a repetition of the v2.7.0 incident. You ran the script, then I ran the script and created a merge commit. Dear oh dear 😅. That was my fault (sorry) but having Travis do the updating will mean that nobody has to worry about it ever again.

**Comment by Milerius** [comment]
I'm totaly agree !

**Comment by skypjack** [comment]
If we can bind a script only to tags, why not?  
Does the `tags: true` part serve this purpose?

**Comment by Kerndog73** [comment]
@skypjack yep. https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A

**Comment by skypjack** [comment]
So, why did you open an issue instead of submitting a PR? :-)

**Comment by Kerndog73** [comment]
Uuuuuuuuuum. Not sure actually. 😅

**Comment by Kerndog73** [comment]
Maybe I'll do that now

**Comment by skypjack** [comment]
:joy: I was joking, don't worry. However, if you can do it, it would be great!! Let me know. Otherwise I'll put a note in the TODO list for the next release.

**Comment by Kerndog73** [comment]
I might as well. I have time.
