### ISSUE TITLE
basic_sparse_set - assure_at_least Assertion `elem == null' failed.

### ISSUE THREAD

**Issue by am-software-solutions** [skypjack/entt#1095]
Hello,

how can this assertion happen?

The call looks like:
`reg.emplace_or_replace<Component>(entity, SOME_STATIC_STRING);`
Which leads to the assert on:
![image](https://github.com/skypjack/entt/assets/132895406/1dc833f3-0638-4f9c-91ed-01d4b0bdd017)

The component to add looks like:
```cpp
struct Component
{
    QString str;
};
```
A check with `reg.valid` on the entity did not return any error (and a couple of time the call works without causing the assert).
Not sure what else to check, as far as I can tell, the entity was also not deleted...

entt version:
```
#define ENTT_VERSION_MAJOR 3
#define ENTT_VERSION_MINOR 11
#define ENTT_VERSION_PATCH 0
```
Thanks in advance.

**Comment by skypjack** [comment]
Do you have a repro? At first glance, it looks like you're assigning the same component to the same entity twice.

**Comment by am-software-solutions** [comment]
Unfortunately not, but would that cause any problems? I thought `emplace_or_replace` would ignore the case when there is a component already present...

**Comment by am-software-solutions** [comment]
```cpp
        if(!reg.try_get<Component>(ent))
        {
            reg.emplace_or_replace<int>(ent, 123);
            reg.emplace_or_replace<Component>(ent, SOME_STATIC_STRING);
        }
```
ok, really strange, that crashes still on the Component emplace call, so now I'm out of ideas...

**Comment by skypjack** [comment]
It can be anything. A multi-threading issue, a call on a moved-from registry, whatever. I can't help much without a repro, really.

**Comment by am-software-solutions** [comment]
Hmm, I already checked that, only one thread calls the code and there is no move done (singleton registry)...
Is there any reason why the assert is not in this code:
https://github.com/skypjack/entt/blob/f2c417435c021b6bd2e426ffd9d1fc116b804146/src/entt/entity/sparse_set.hpp#L189
But in here:
https://raw.githubusercontent.com/skypjack/entt/f2c417435c021b6bd2e426ffd9d1fc116b804146/single_include/entt/entt.hpp
Without knowing the internal structure in detail, its hard to understand what this assert is causing, to me the code looks like the assert should actually not happen. Can maybe someone explain in what condition this assert is hit?
I guess that would help to check if/how the calling code messes something up.

**Comment by skypjack** [comment]
The assert tells you that the slot is already taken. It means that the set already contains the entity. That's all.
The component type doesn't really matter too, it would be the same for a `storage<void>` type.
Without a repro it's nearly impossible to tell why you're hitting this though. I'm sorry. You're the only one that can debug it.
I agree that the assert should not happen. It's there to _save_ all users (including me) from their own mistakes. 🙂

**Comment by Innokentiy-Alaytsev** [comment]
Are shared libraries involved?

**Comment by am-software-solutions** [comment]
> The assert tells you that the slot is already taken. It means that the set already contains the entity. That's all. The component type doesn't really matter too, it would be the same for a `storage<void>` type. Without a repro it's nearly impossible to tell why you're hitting this though. I'm sorry. You're the only one that can debug it. I agree that the assert should not happen. It's there to _save_ all users (including me) from their own mistakes. 🙂

Hmm, strange that this (entity already in the set) matters on a call of emplace_or_replace (-> if so, do a replace?), but there will be reasons I guess XD

> Are shared libraries involved?

Yes.
Maybe smth leaks into the registry, that the is the last thing I can think of.
Thanks.

**Comment by Innokentiy-Alaytsev** [comment]
Try looking into EnTT documentation about working with shared libraries. If you don't do things properly, then each shared library will have it's own set of identifiers for components and stuff.

**Comment by am-software-solutions** [comment]
> Try looking into EnTT documentation about working with shared libraries. If you don't do things properly, then each shared library will have it's own set of identifiers for components and stuff.

Thanks for pointing it out, do you mean in the wiki? Could you please provide a link to what you are referring to?

**Comment by Innokentiy-Alaytsev** [comment]
https://github.com/skypjack/entt/wiki/Push-EnTT-across-boundaries

**Comment by hfn92** [comment]
Just FYI, I had the exact same assertion when emplacing a component after previously accessing the same type of component from a deleted entity (Which of course is wrong).

Something like this
```cpp
reg.emplace<Transform>(e, {});
reg.destroy(e);
reg.get<Transform>(e); // bad

// ...

auto e2 = reg.create();
reg.get<Transform>(e2); // triggers assert
```

**Comment by am-software-solutions** [comment]
N1. That looks like the issue 👍🏻😀

**Comment by am-software-solutions** [comment]
> Just FYI, I had the exact same assertion when emplacing a component after previously accessing the same type of component from a deleted entity (Which of course is wrong).
> 
> Something like this
> 
> ```c++
> reg.emplace<Transform>(e, {});
> reg.destroy(e);
> reg.get_or_emplace<Transform>(e); // bad
> 
> // ...
> 
> auto e2 = reg.create();
> reg.get_or_emplace<Transform>(e2); // triggers assert
> ```

N1. That looks like the issue 👍🏻😀

**Comment by skypjack** [comment]
Wait a moment. In this case, EnTT should throw an assert to you. Did you disable them?

**Comment by hfn92** [comment]
> Wait a moment. In this case, EnTT should throw an assert to you. Did you disable them?

No I did not. I was confused about that as well.

**Comment by skypjack** [comment]
Oh, I see. The set doesn't contain the entity and therefore you can emplace the element.
However, the second emplace finds the slot occupied and triggers an error. Makes sense.
In theory, I can add a `valid(entt)` check within the `get_or_emplace` function but nothing prevents you from accessing the storage as in `.storage<int>()` and getting around the check if you like.

**Comment by hfn92** [comment]
Well an assertion at the point of error would have saved me some time in this case. I think it's worth adding even if doesn't work when accessing the storage directly.

**Comment by am-software-solutions** [comment]
It's your baby :), you can judge best, but asserting asap sounds good to me.

**Comment by skypjack** [comment]
Mmm, ok, let's reopen the issue as feature request then. We can add the checks back in place with the next release. 👍

**Comment by skypjack** [comment]
Checks available on the `wip` branch (with non-regression tests too).
They'll be part of the next release. Thanks for pointing this out. 👍
