### ISSUE TITLE
error: "use of overloaded operator '!=' is ambiguous" for `dense_map`-iterator?

### ISSUE THREAD

**Issue by RedCookieLP** [skypjack/entt#1102]
So I'm trying to use `entt` and copied the single-include header of version 3.12.2 into my project's directory.
For some reason, if I try to compile my code with `entt` (using clang 15.0.7 on WSL2, also tried with clang 14.0.0) I get the following error:
```bash
[project's path]/inc/ECS/entt.hpp:37953:24: error: use of overloaded operator '!=' is ambiguous (with operand types 'entt::dense_map<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>, entt::identity>::iterator' (aka 'dense_map_iterator<__normal_iterator<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>> *, std::vector<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>>') and 'entt::dense_map<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>, entt::identity>::iterator')
        for(auto &&curr: pools) {
                       ^
[project's path]/inc/ECS/entt.hpp:38003:9: note: in instantiation of member function 'entt::basic_registry<>::rebind' requested here
        rebind();
        ^
[project's path]/inc/Log/Log.h:16:45: note: in instantiation of member function 'entt::basic_registry<>::basic_registry' requested here
                : m_filePath(filePath), m_logEntries({}), m_container({})
                                                          ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/stl_relops.h:87:7: note: candidate function [with _Tp = entt::internal::dense_map_iterator<__gnu_cxx::__normal_iterator<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>> *, std::vector<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>>]
      operator!=(const _Tp& __x, const _Tp& __y)
      ^
[project's path]/inc/ECS/entt.hpp:3167:30: note: candidate function [with Lhs = __gnu_cxx::__normal_iterator<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>> *, std::vector<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>, Rhs = __gnu_cxx::__normal_iterator<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>> *, std::vector<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>]
[[nodiscard]] constexpr bool operator!=(const dense_map_iterator<Lhs> &lhs, const dense_map_iterator<Rhs> &rhs) noexcept {
                             ^
[project's path]/inc/ECS/entt.hpp:37953:26: note: in implicit call to 'operator!=' for iterator of type 'entt::basic_registry<>::pool_container_type' (aka 'dense_map<unsigned int, shared_ptr<basic_sparse_set<entt::entity, std::allocator<entt::entity>>>, entt::identity, equal_to<unsigned int>, allocator<std::pair<const unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>')
        for(auto &&curr: pools) {
                         ^~~~~
[project's path]/inc/ECS/entt.hpp:3493:28: note: selected 'begin' function with iterator type 'entt::dense_map<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>, entt::identity>::iterator' (aka 'dense_map_iterator<__normal_iterator<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>> *, std::vector<entt::internal::dense_map_node<unsigned int, std::shared_ptr<entt::basic_sparse_set<>>>>>>')
    [[nodiscard]] iterator begin() noexcept {
                           ^
1 error generated.
```

The file with the `Log`-class where the registry gets initiated looks like this:
```c++
// Log.h
#ifndef LOG_H
#define LOG_H

#include <Log/LogEntry.h>
#include <jsoncpp/json.h>
#include <vector>
#include <memory>
#include <regex>

class FileParser;
class Log
{
	friend class FileParser;
public:
	Log(const std::string& filePath = "")
		: m_filePath(filePath), m_logEntries({}), m_container({})
	{}
	~Log() { m_container.clear(); }
public:
	std::weak_ptr<LogEntry> createLogEntry();
	void deleteLogEntry(const std::weak_ptr<LogEntry>& toDelete);
	const std::vector<std::shared_ptr<LogEntry>>& getEntries() const { return m_logEntries; }
	const std::string& getFilePath() const { return m_filePath; }
	Json::Value toJSON() const;
	void setFilePath(const std::string& newFilePath) { m_filePath = newFilePath; }
private:
	std::string m_filePath;
	std::vector<std::shared_ptr<LogEntry>> m_logEntries;
	entt::registry m_container;
};

#endif
```

Is this a bug or did I mess something up?

**Comment by RedCookieLP** [comment]
(It'd be probably a good idea if I'd share the compiler-arguments for above too...)

`-Wall -Wextra -std=c++17 -O2 -m64`
The error-message from above is generated by clang-14

**Comment by skypjack** [comment]
Clang 14 is tested [here](https://github.com/skypjack/entt/actions/runs/7445568656/job/20254056003) on the CI and there are no errors.
Have you already tried the upstream version? To be honest, I cannot reproduce the issue yet. 🤔

**Comment by RedCookieLP** [comment]
I can try the version from the `master`-branch, hopefully this will solve it...

**Comment by RedCookieLP** [comment]
Wait, isn't that dated the same as the release? If so, then that'd be useless...
Ok, I'll just try the experimental

**Comment by RedCookieLP** [comment]
Nope, same error :/

**Comment by RedCookieLP** [comment]
I've just wrote a super simple example and with that it compiles fine... what's groing wrong in my project?...

**Comment by Innokentiy-Alaytsev** [comment]
Is there a chance that you have a template `operator!=` that accepts two arguments of any type anywhere in the code?

**Comment by RedCookieLP** [comment]
Not in my code, but JSONCpp has one. But that won't probably be it since it's specialized for two `const Json::SecuteAllocator<T>`-objects.
In that simple example I've also tested it with JSONCpp, working fine...

**Comment by skypjack** [comment]
You should try to use `master`. However, getting `entt.hpp` from there isn't enough because it's only generated for new releases.
Therefore, you can either use the files under `src/entt` or regenerate the `entt.hpp` file locally for your tests.
In both cases and without a proper repro, I'm tempted to mark the issue as invalid for the time being.

**Comment by RedCookieLP** [comment]
I've just tried it with the `src`-files, no difference, still just that one error. I don't get how or why this happens and have no idea what else to test...

So I'll either have to search further, trying all random stuff... or search for something else.

**Comment by RedCookieLP** [comment]
To add all files I did the following (telling you, so you can tell if I did something wrong):

- Copied all files from inside of `entt-3.12.2/src/entt` to my project's `inc/ECS/entt/`-directory
- Added `-I"inc/ECS/entt/"` to my compiler arguments.
- Changed `#include <ECS/entt.hpp>` to `#include <ECS/entt/entity/registry.hpp>` (since I'm only interested in the ECS-part...)

**Comment by Innokentiy-Alaytsev** [comment]
Did you try commenting out the `depse_map::iterator::operator!=()`? This could show you the other operator definition that makes the whole thing ambiguous.

**Comment by RedCookieLP** [comment]
Not yet, I can give it a shot...

**Comment by RedCookieLP** [comment]
First: That breaks everything even further
Second: It just shows me a bunch of STL-iterators which don't match

**Comment by Innokentiy-Alaytsev** [comment]
My bad, the error message tells us the alternative: [`std::rel_ops::operator!=`](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/libstdc++/api/a01362.html#a90a8bcb2378458899b902c6eb8834bd2) from [`stl_relops.h`](https://gcc.gnu.org/onlinedocs/gcc-4.8.5/libstdc++/api/a01258.html).

**Comment by RedCookieLP** [comment]
I think I've found the issue: It was a `using namepsace std::relops` in one of my headers to make comparing `Date`-objects simpler...

Guess I'll have to find another way to do that, but at least `entt`'s not complaining anymore!

**Comment by Innokentiy-Alaytsev** [comment]
A general recommendation is to avoid `using namespace` at global scope in headers or inside namespaces in headers. And I was initially right. And it was not EnTT complaining, but the compiler telling you there's an error.

**Comment by RedCookieLP** [comment]
Yeah, you're right. Of course it was the compiler, but it was complaining about multiple matches because of `entt` and rel_ops having definitions for that operator.

User-error by me and with that I'll close this issue
