### ISSUE TITLE
3.13.0 installs include/BUILD.bazel

### ISSUE THREAD

**Issue by yurivict** [skypjack/entt#1104]
Could you please remove it?

**Comment by skypjack** [comment]
Out of curiosity, was it there in the previous version? I don't think anything has changed in the meantime but I could be wrong. 🤔

**Comment by yurivict** [comment]
No, it wasn't there in 3.12.2

**Comment by skypjack** [comment]
I think this is eligible for the next patch version. Can you test a patch when it's upstream and before adding it to the new release?
Just to confirm that it works as expected. I think I can push it on Monday (mostly because I'm out until then 😅).

**Comment by zaucy** [comment]
Sorry this was introduced by me during bzlmod support. I don't use cmake much these days 😅 

Here's a patch https://github.com/skypjack/entt/pull/1107

**Comment by skypjack** [comment]
No worries at all @zaucy and thanks for your help! 🙂

**Comment by skypjack** [comment]
Fix available on branches `wip` and `v3.13.x` (next patch release for version 3.13).
Let me know if it doesn't work for you. Thanks. 👍

**Comment by skypjack** [comment]
Fixed with version 3.13.1, thanks for pointing this out.

**Comment by skypjack** [comment]
@zaucy before trying to fix it on my own, I think it's worth to ping you 🙂 bazel is complaining since a while ago, see [here](https://github.com/skypjack/entt/actions/runs/8263302869/job/22604411219) for an example. Is it an easy fix? Any suggestions?
Thanks in advance for your help. 🙏

**Comment by zaucy** [comment]
@skypjack done! it's here https://github.com/skypjack/entt/pull/1124

**Comment by skypjack** [comment]
Oh, wow @zaucy thank you very much!! ❤️
