### ISSUE TITLE
entt::registry has no member empty and each wtf

### ISSUE THREAD

**Issue by RodrigoBrombatti** [skypjack/entt#1105]
What Im doing wrong?
A project that I used this two methods just dont have it anymore
Looks like my project is joking me
Everything is working perfectly, just Each and Empty I cant acess from entt::registry
wtf
The include (single_include) is correct, Im using entt alot in my project

![Screenshot 2024-01-18 104215](https://github.com/skypjack/entt/assets/5924448/41b397d3-8218-4004-ab52-c0be34a1858f)
![Screenshot 2024-01-18 104533](https://github.com/skypjack/entt/assets/5924448/922c28ee-7826-4835-9c71-6ce426d7173a)

**Comment by Innokentiy-Alaytsev** [comment]
Is it a build error or an IntelliSense error?

**Comment by skypjack** [comment]
Entites were moved on their own storage a while ago and are no accessible using views as any other elements in the registry:
```cpp
auto view = registry.view<entt::entity>();
const bool empty = view.empty();
for(const auto entity: view) { /* ... */ }
```

**Comment by RodrigoBrombatti** [comment]
> Entites were moved on their own storage a while ago and are no accessible using views as any other elements in the registry:
> 
> ```c++
> auto view = registry.view<entt::entity>();
> const bool empty = view.empty();
> for(const auto entity: view) { /* ... */ }
> ```

![Screenshot 2024-01-19 122122](https://github.com/skypjack/entt/assets/5924448/39e61a18-2a68-47cd-8bc4-6b3ee604fb6e)
![Screenshot 2024-01-19 122128](https://github.com/skypjack/entt/assets/5924448/c7e760df-b127-4ffa-aa6a-b80c30a71c93)

**Comment by RodrigoBrombatti** [comment]
@skypjack empty for me don't exists

**Comment by RodrigoBrombatti** [comment]
@skypjack I changed to v3.8,x and worked

**Comment by skypjack** [comment]
Yeah, sorry, it's `size_hint` or even `view.storage().free_list() == 0u` if you want to be 100% sure.

**Comment by skypjack** [comment]
I assume this was solved. Let me know if this isn't the case. Thanks.
