### ISSUE TITLE
Combine snapshot and meta features

### ISSUE THREAD

**Issue by bookmagnus** [skypjack/entt#1110]
Hey
I just started using the library and I love it. I have not fully understood how to use the meta feature but in below code I am trying to serialize components with the help of the meta information. There must be a better way to do what I am trying to do inside the Archive class below. Can you please help me understand how to achive the same thing but without having to compare strings?

`

	struct SomeStruct
	{
		float x = 0.f;
		float y = 0.f;
		float z = 0.f;
		bool b = false;
		uint8_t u8 = 0;
		uint16_t u16 = 0;

		SomeStruct(float in_x, float in_y, float in_z, bool in_b, uint8_t in_u8, uint16_t in_u16)
			: x(in_x), y(in_y), z(in_z), b(in_b), u8(in_u8), u16(in_u16)
		{
		}
	};

	template<typename T>
	class BitPacker
	{
	public:
		BitPacker(T& storage)
		{}

		template<typename T>
		void serialize(T value) 
		{}
	};

	template<typename T>
	class Archive
	{
	public:
		Archive(T& storage)
			: m_bitPacker(storage)
		{}

		void operator()(std::underlying_type_t<entt::entity> size) 
		{}

		void operator()(entt::entity entity) 
		{}

		template<typename T>
		void operator() (const T& component)
		{
			entt::meta_any any(component);

			for (auto&& key_value : any.type().data())
			{
				auto member = key_value.second.get(component);
				auto type = member.type();

				if (type.info().name() == "bool")
				{
					std::cout << "bool value " << member.cast<bool>() << std::endl;
					m_bitPacker.serialize(member.cast<bool>());
					continue;
				}

				if (type.info().name() == "unsigned char")
				{
					std::cout << "uint8_t value " << member.cast<uint8_t>() << std::endl;
					m_bitPacker.serialize(member.cast<uint8_t>());
					continue;
				}

				if (type.info().name() == "unsigned short")
				{
					std::cout << "uint16_t value " << member.cast<uint16_t>() << std::endl;
					m_bitPacker.serialize(member.cast<uint16_t>());
					continue;
				}

				if (type.info().name() == "float")
				{
					std::cout << "float value " << member.cast<float>() << std::endl;
					m_bitPacker.serialize(member.cast<float>());
					continue;
				}
			}
		}

	private:
		BitPacker<T> m_bitPacker;
	};

	int main()
	{
		using namespace entt::literals;
	
		entt::meta<SomeStruct>()
			.type(entt::type_hash<SomeStruct>::value())
			.data<&SomeStruct::x>("x"_hs)
			.data<&SomeStruct::y>("y"_hs)
			.data<&SomeStruct::y>("z"_hs)
			.data<&SomeStruct::b>("b"_hs)
			.data<&SomeStruct::u8>("u8"_hs)
			.data<&SomeStruct::u16>("u16"_hs);

		entt::registry registry;
		auto entity1 = registry.create();
		registry.emplace<SomeStruct>(entity1, 0.f, 0.f, 0.f, false, 0, 0);

		auto entity2 = registry.create();
		registry.emplace<SomeStruct>(entity2, 10.f, 10.f, 10.f, true, 10, 1222);

		std::stringstream stream;
		Archive<std::stringstream> archive(stream);
	
		entt::snapshot{ registry }
			//.get<entt::entity>(archive)
			.get<SomeStruct>(archive);

		return 0;
	}

`

**Comment by skypjack** [comment]
> Can you please help me understand how to achive the same thing but without having to compare strings?

Do you mean here? `type.info().name() == "bool"`.
You can use the compile time hash for that, as in `type.info().hash() == entt::type_id<Type>().hash()`.

Also note that you're copying the object here: `entt::meta_any any(component);`.
However, `meta_any` also supports creating references to elements: `entt::meta_any any = entt::forward_as_meta(component);`.
That said, you don't have to wrap the element in an `meta_any` object at all. Just use the meta type directly:
```cpp
for (auto&& key_value : entt::resolve<Type>().data()) {
    ...
}
```

**Comment by bookmagnus** [comment]
Great thanks for the help.
