### ISSUE TITLE
What is a "valid entity type"? (Question)

### ISSUE THREAD

**Issue by Batres3** [skypjack/entt#1111]
According to the documentation: "User defined identifiers are allowed as enum classes and class types that define an entity_type member of type `std::uint32_t` or `std::uint64_t`."

I'm quite a beginner when it comes to C++ so I don't really understand what this means. In the faq the example given is:
```
enum class entity: std::uint32_t {};
```
What would a valid example look like for a custom entity that is not an enum class, but a regular class?

I'm trying to make it work with the following class:
```
class UUID
{
public:
	using entity_type = uint64_t;
	static constexpr uint64_t null = 0;
	UUID();
	UUID(uint64_t id);
	UUID(const UUID&) = default;

	constexpr operator entity_type() const noexcept { return m_UUID; }
private:
	entity_type m_UUID;
};
```

This is obviously not correct since it raises the error
```
error C2127: 'value': illegal initialization of 'constexpr' entity with a non-constant expression
```
But I don't understand what has to be constant here. Sorry if this has been asked before but I couldn't quite find it.

**Comment by skypjack** [comment]
Is [this](https://github.com/skypjack/entt/blob/master/test/example/custom_identifier.cpp#L6) what you are looking for?

**Comment by Batres3** [comment]
That's exactly it, thank you and sorry for the late response.
