### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#112]
Some repositories write about what was changed/added/depreciated/removed since the last release.

[Example](https://github.com/beetbox/beets/releases)

It doesn't have to be that detailed. It could just be a paragraph summary.

I think users (and potential users) will appreciate a releases page with more than just a version number.

**Comment by skypjack** [comment]
Are you asking to fill the gap also for the old releases? Because it's a great amount of work actually...

**Comment by Kerndog73** [comment]
No, no, no! There's no need for that

**Comment by skypjack** [comment]
How do they do it? I mean, I thought a Changelog file was enough, but your link is something... _different_.

**Comment by Kerndog73** [comment]
https://help.github.com/articles/creating-releases/

**Comment by skypjack** [comment]
You just made me feel so stupid... :sob:

**Comment by skypjack** [comment]
Added a [note](https://github.com/skypjack/entt/releases/tag/v2.7.1) for `EnTT` v2.7.1, that is the last version.  
I don't think I'll never fill the release notes for the old versions, but I'm willing to collaborate if anyone wants to help me to do it.  
I'll do my best for the next releases instead. Ping me if I forgot to write the release note. :smile:
