### ISSUE TITLE
Is it possible to use entt::nth_argument_t with lambdas that capture?

### ISSUE THREAD

**Issue by eliasdaler** [skypjack/entt#1127]
Hello.
I managed to get `nth_argument_t` working with non-capturing lambdas like this:

```cpp
struct MovementComponent {};

registerDisplayer("Movement", [](entt::const_handle e, const MovementComponent& mc) {
   ....
});

template<typename F>
void registerDisplayer(const std::string& componentName, F f)
{
    using DisplayerFuncType = std::remove_pointer_t<decltype(+std::declval<F>())>;
    using ComponentType = std::remove_cvref_t<entt::nth_argument_t<1u, DisplayerFuncType>>; 
    // ^ ComponentType == MovementComponent
   ...
}
```

However, this approach doesn't work with lambdas that capture state. Is it possible with some C++ template magic, perhaps?

Basically, I want to be able to do this:

```cpp
auto f = [someCapture](entt::const_handle e, const MovementComponent& mc) { ... };
static_assert(std::is_same_v<GetSecondArgType(f), const MovementComponent&>)
```

**Comment by manpat** [comment]
@skypjack do you welcome contributions, or do you already have a solution ready? this seems like something i could feasibly look at

**Comment by skypjack** [comment]
I welcome contributions but I've done this one locally already. I only need to port it from a fork to the main project.
If you're looking for tasks, I can drop some ideas in chat though. :)

**Comment by skypjack** [comment]
Fix available on the `wip` branch (upcoming `master`).

**Comment by eliasdaler** [comment]
Can confirm that it works for me. Thanks a lot. :)

**Comment by manpat** [comment]
@skypjack no worries :)
was just In The Neighborhood and this just seemed like a nice small task i could snipe :^)
