### ISSUE TITLE
Question it is posible to use Entt with lightweight wrapper class as a entt::entity

### ISSUE THREAD

**Issue by cNori** [skypjack/entt#1128]
so i was wondering if is possible to somehow use a lightweight wrapper as a ID

somfing like 
```c++
class MyEntity
{
MyEntity(entt::entity Handle)
{
EnTTHandle = Handle;
}
operator entt::entity() { return EnTTHandle; } 

protected:
entt::entity EnTTHandle;
MyEntity* Parent;
WorldChunk* Chunk;
};
```

**Comment by Domiran** [comment]
I do something vaguely similar, except the only thing stored in said class is the entity id. The class acts as just convenient entity-first object-oriented access, without exposing everything to the location of the registry.

With proper handling, this becomes a way to make entities "const" across different objects.

**Comment by skypjack** [comment]
Yes, it is. [Here](https://github.com/skypjack/entt/blob/master/test/example/custom_identifier.cpp#L6) you can find an example of a custom identifier. EnTT is highly customizable and the entity type is one of the things you can redefine as you like. 👍 
You still have to initialize `parent` and `chunk` manually in your systems or with a storage mixin for the entity storage though. The registry doesn't know how to setup them.
