### ISSUE TITLE
Components with overriden new operator.

### ISSUE THREAD

**Issue by jdumas** [skypjack/entt#1131]
Hi. I'm trying to use EnTT with [JoltPhysics](https://github.com/jrouwe/JoltPhysics). Jolt by default overrides its [new/delete](https://github.com/jrouwe/JoltPhysics/blob/f5ab4fd526fe1e03a408a5ead3ee396263d8a1d3/Jolt/Core/Memory.h#L29-L37) operators, which causes compilation issues with EnTT's usage of placement new operator here:

https://github.com/skypjack/entt/blob/fedcb920ce0068c35ffbc66fd4e84864e6ef71ef/src/entt/core/memory.hpp#L278

As proposed in [this discussion](https://github.com/jrouwe/JoltPhysics/discussions/986), the solution would be to replace `new(value)` with `::new(value)` in EnTT's codebase.

**Comment by skypjack** [comment]
Have you tried it already in your project? Can you confirm that it works as expected?

**Comment by jdumas** [comment]
Yes! But if there are other places where EnTT is using a placement new, those may also need to be updated. Happy to work on a MWE without Jolt if you think that's useful.

**Comment by jdumas** [comment]
Sure. As I said I was planning to provide a MWE _without_ Jolt. So here it is:

```c++
#include <entt/entt.hpp>

#include <stdlib.h>
#include <cstdlib>

namespace MyLib {

void* Allocate(size_t inSize)
{
    return malloc(inSize);
}

void Free(void* inBlock)
{
    free(inBlock);
}

void* AlignedAllocate(size_t inSize, size_t inAlignment)
{
#if defined(_WIN32)
    return _aligned_malloc(inSize, inAlignment);
#else
    void* block = nullptr;
    posix_memalign(&block, inAlignment, inSize);
    return block;
#endif
}

void AlignedFree(void* inBlock)
{
#if defined(_WIN32)
    _aligned_free(inBlock);
#else
    free(inBlock);
#endif
}

class Foo
{
public:
    Foo(int x_)
        : x(x_)
    {}

public:
    void* operator new(size_t inCount) { return MyLib::Allocate(inCount); }
    void operator delete(void* inPointer) noexcept { MyLib::Free(inPointer); }
    void* operator new[](size_t inCount) { return MyLib::Allocate(inCount); }
    void operator delete[](void* inPointer) noexcept { MyLib::Free(inPointer); }
    void* operator new(size_t inCount, std::align_val_t inAlignment)
    {
        return MyLib::AlignedAllocate(inCount, static_cast<size_t>(inAlignment));
    }
    void operator delete(void* inPointer, [[maybe_unused]] std::align_val_t inAlignment) noexcept
    {
        MyLib::AlignedFree(inPointer);
    }
    void* operator new[](size_t inCount, std::align_val_t inAlignment)
    {
        return MyLib::AlignedAllocate(inCount, static_cast<size_t>(inAlignment));
    }
    void operator delete[](void* inPointer, [[maybe_unused]] std::align_val_t inAlignment) noexcept
    {
        MyLib::AlignedFree(inPointer);
    }

protected:
    int x;
};

} // namespace MyLib

int main(void)
{
    entt::registry r;
    auto e = r.create();
    r.emplace<MyLib::Foo>(e, 42); // <-- doesn't compile
    return 0;
}
```

**Comment by skypjack** [comment]
> As I said I was planning to provide a MWE without Jolt

You're right and I read it wrong. 😅 
Thanks for the example, I'll use it as the basis for a non-regression test. 👍

**Comment by jdumas** [comment]
All good, thanks for looking into it!
