### ISSUE TITLE
entt build error: unused type alias 'common_type'

### ISSUE THREAD

**Issue by beekayer** [skypjack/entt#1136]
Just updated entt submodule for my project (I've been using entt since 2022) and got this:

Compiler Error:
entt/entity/snapshot.hpp:90:23: error: unused type alias 'common_type' [-Werror,-Wunused-local-typedef]
                using common_type = typename registry_type::common_type;

Compiler:
Apple clang version 15.0.0 (clang-1500.1.0.2.5)
Target: x86_64-apple-darwin22.6.0
Thread model: posix

top level project CMake (just showing I'm compiling for C++20):
add_definitions(-Wall -Wextra -Werror -DEIGEN_MPL2_ONLY)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++20")

**Comment by skypjack** [comment]
> Just updated entt submodule for my project

Just to be clear, updated to...? `master`? Last stable version/patch version? `wip`?
I'm about to create a new patch version. I can include a quick fix eventually. 👍

**Comment by beekayer** [comment]
This is my submodule update from remote I did this morning.

From git submodule update --remote
From https://github.com/skypjack/entt
   f2c41743..fedcb920  experimental -> origin/experimental
   7cf7699b..9a9e9e0b  gh-pages     -> origin/gh-pages
   f2c41743..df87206c  master       -> origin/master
 * [new branch]        v3.13.x      -> origin/v3.13.x
   5ea8f038..b9f9cb48  wip          -> origin/wip
 * [new tag]           v3.13.0      -> v3.13.0
 * [new tag]           v3.13.1      -> v3.13.1
Submodule path 'entt': checked out 'df87206c940706ed6d06e9e4763628bed075a9cc'
remote: Enumerating objects: 330, done.
remote: Counting objects: 100% (330/330), done.
remote: Compressing objects: 100% (180/180), done.
remote: Total 330 (delta 202), reused 198 (delta 130), pack-reused 0
Receiving objects: 100% (330/330), 479.12 KiB | 7.98 MiB/s, done.
Resolving deltas: 100% (202/202), completed with 11 local objects.

**Comment by skypjack** [comment]
I guess you're using `master`. Commit 4da502f from `wip` suppresses the warning already. Soon upstream. 👍

**Comment by beekayer** [comment]
I have to throw this out while I have you, love your library mate.  Good stuff. Using it to glue ImGui & Lua

**Comment by skypjack** [comment]
Thanks for the kind words ❤️ I've just created version 3.13.2 that also contains a fix for your issue.
Moreover, I'm starting work on the next _big one_. I hope it will make you love the library even more! 🙂

**Comment by beekayer** [comment]
Looking forward to it.. I saw your long thread on relationships a while back, I've long suspected you might do something with that - just speculation. :)  Either way, I'm sure it will be great. You're one hell of a C++ programmer.

**Comment by beekayer** [comment]
I see master wasn't updated with fix.  I see the fix in WIP and see it made it into 3.13.x.  I assume I shouldn't be using master branch in my production and use specific released versions?

**Comment by beekayer** [comment]
In stead of taking whatever master is, do you recommend I just keep up with your latest version in my .gitmodules? e.g.
[submodule "entt"]
	path = entt
	url = https://github.com/skypjack/entt.git
	branch = v3.13.x

**Comment by skypjack** [comment]
Yeah, I strongly suggest using stable releases if possible. As for the other branches, this is how it works in general:

* `wip` is the dev branch and it can contain bugs or even result in compilation errors
* `master` is the upcoming release, stuff tested and proved to work on an outstanding amount of platforms already

You don't see the fix on `master` yet because it's after a bunch of commits that I haven't tested properly. I cherry-picked it for the release instead and tested it in isolation. 👍
