### ISSUE TITLE
assert on destroy (inside of release function) non-orphan entity

### ISSUE THREAD

**Issue by immerhart** [skypjack/entt#1138]
I'm hitting an assert, which I don't understand why it's happening and after debugging for a long time, I'm reaching out for help now...
![image](https://github.com/skypjack/entt/assets/7241591/c73fc1e9-6c5e-4e69-b25a-1f4dbbaaf7f1)
Now, I'm not calling this function directly, I'm just using the `destroy(entity)` function (which calls the `release` function at some point).
I'm assuming it means that the entity that should be destroyed is not destroyed yet?!
What could cause that? It must be tied to a previous destroy/recycling (first time destroy works fine), as the entity version is >= 2.
Destroying the entity multiple times can't be it, as the assert (invalid identifier one line above) is not triggering and I checked that very often.
Running on a single thread and single registry here.
Probably looking at the wrong place...

**Comment by skypjack** [comment]
I cannot say what's happening without a repro. However, do you have listeners on components? As an example, a listener that gets triggered when a component is erased.

**Comment by immerhart** [comment]
Thanks for the idea, but no :/
We use entt::dispatcher for some event stuff, but nothing related to entity deletion, as far as I can tell.
The code can't be shared unfortunately...

**Comment by immerhart** [comment]
![image](https://github.com/skypjack/entt/assets/7241591/631134e5-f339-4a66-9b04-4b8edf911ad3)
good enough XD

**Comment by skypjack** [comment]
> good enough XD

It is not. You're probably hiding an UB with this guard.

**Comment by skypjack** [comment]
Well, let me know if I can help hands-on with the code then. I'm more than willing in case. 🙂👍

**Comment by immerhart** [comment]
Thank you very much for the offer, much appreciated!
But we actually found the issue this evening (still not sure why it caused the assert, though; but after the fix we aren't facing the crash anymore). 
It's actually quite embarrassing (even more, because it was me refactoring this, but sometimes stuff just goes wrong XD). In one class we had an uninitialized entt::entity member variable. At some event trigger, the class was assigning a component to that entity over emplace_or_replace, which works just fine (maybe that should assert already?).
And somehow this leads to the assert mentioned at the top, no clue why, but the error was ofc adding the component to an uninitialized entt::entity, which maybe messes up some internal state...

**Comment by skypjack** [comment]
> maybe that should assert already?

I think the upstream version already contains these asserts for the next release. Someone popped up with the exact same request less than a month ago. 🙂
