### ISSUE TITLE
bazel version and compatibility number out of sync

### ISSUE THREAD

**Issue by zaucy** [skypjack/entt#1141]
The current release process doesn't increment the version ~~or compatibility level~~ in the `MODULE.bazel` file. I've recently [submitted EnTT to the BCR](https://github.com/bazelbuild/bazel-central-registry/pull/1904) and had to patch it in (so no worries there.)

I'm creating this issue for visibility sake, but I plan on creating a PR to fix this myself in the coming weeks.

**edit:**

https://github.com/bazelbuild/bazel-central-registry/pull/1904#discussion_r1583814621

The current advice is to avoid `compatibility_level` altogether so it would probably be best to omit it for now until EnTT introduces some major breaking changes.

**Comment by skypjack** [comment]
@zaucy can I close this issue?

**Comment by zaucy** [comment]
thanks for the reminder! with https://github.com/skypjack/entt/pull/1147 it can be.

**Comment by zaucy** [comment]
although the version number is still not automatically updated. Is there a release script I could update?

**Comment by skypjack** [comment]
I usually update `version.h`, then I read it from cmake.

**Comment by skypjack** [comment]
Closed with #1147 afaik. 🙂
