### ISSUE TITLE
Try it: Face Smash

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#115]
Sooner or later I'll publish the source code online in its own repo, but I cannot do it today ( @morbo84 will hurt me otherwise ). I'm sorry.

By the way, today is the **World Emoji Day**.
We decided to celebrate it with our first game built entirely on top of `EnTT`: **Face Smash**.  
A game where you can use your facial expressions to smash emojis on screen.

[Check it out on Android store](https://play.google.com/store/apps/details?id=com.gamee.facesmash).  
iOS version is coming soon.

---

Lighting issue to make you know `EnTT` is also on the Android Store finally.

**Comment by ArnCarveris** [comment]
@skypjack iOS is planned?

**Comment by loudedtwist** [comment]
hey, that is really cool, i will try definitely it out. Was it difficult to compile it for Android ? Do you have a tutorial how to start my game that uses Entt on Android ?

**Comment by skypjack** [comment]
@loudedtwist  
Face Smash is written entirely with SDL2 on top of EnTT. SDL2 comes with a pre-built Android package and a java class you can extend to add more functionalities. It works just fine on Android as it is.  
We added functionalities for the camera, ads, billing, muxing and so on. You can find a lot of tutorial on the web for this stuff actually.

**Comment by vblanco20-1** [comment]
@skypjack . Will you write about that? I think some article explaining how you used the EnTT library for a "real" project would be a nice thing to read.

**Comment by skypjack** [comment]
@vblanco20-1 
I'm thinking for a while of creating a series of articles about several arguments actually: game development with `EnTT`, internals of `EnTT` (and therefore a sort of _how to develop a high performance ECS_), design patterns meet ECS and so on.  
My idea was to create an account on patreon.com or something like that, release the articles once a week or once every two weeks and then publish them in the public domain six months later.  
Why am I waiting for? Well, I'm not that sure I'll reach such an user base, so... :sob:  
Btw, sooner or later I'll do it. I count on your support, guys!! :smile:
