### ISSUE TITLE
Iterating over all entities

### ISSUE THREAD

**Issue by KiviTK** [skypjack/entt#1150]
For some housekeeping tasks in a game after a level is complete I wish to iterate over all entities in a registry and delete every entity that does not have the persistence compontnt.

`registry::each` would be the function that I wanted to use since that ahs been widely noted as the function for this exact task but it appears that in version `3.13.2` this function is no longer available on the registry.
What replaced this functionality or how do I createh the desired behavior with this version of the library?

```
---\sources\GameplayScreen.cpp(208): error C2039: 'each': is not a member of 'entt::basic_registry<entt::entity,std::allocator<Entity>>'
        with
        [
            Entity=entt::entity
        ]
```

**Comment by skypjack** [comment]
Something along this line: `for(auto entity: registry.view<entt::entity>(entt::exclude<T>)) { ... }`.
Entities have their own (fully customizable) storage now, as it happens with the components.
This means that they work with views, they support signals and mixins, and so on. 👍

**Comment by KiviTK** [comment]
I see, makes complete sense, I was jus tlooking for each so I didnt figure this on my own. Thanks a lot for the quick reply.
