### ISSUE TITLE
Is basic_collector::update supposed to support a list of component types?

### ISSUE THREAD

**Issue by Net5F** [skypjack/entt#1154]
When I try to do the following:
```
entt::observer obs = entt::collector.update<Foo, Bar>();
```
it fails to compile. The single component case compiles just fine, and using `group` instead of `update` works just fine.
```
entt::observer obs = entt::collector.update<Foo>();
entt::observer obs2 = entt::collector.group<Foo, Bar>();
```
The difference seems to be [here](https://github.com/skypjack/entt/blob/1ddc887ac43f6ba0ae5d39c14ec08ef7fcb0b435/src/entt/entity/observer.hpp#L56) in `basic_collector::update`. Unlike the `NoneOf` and `AllOf` template parameters in `group`, `AnyOf` in `update` isn't a parameter pack and thus doesn't get unfolded:
```
    template<typename... AllOf, typename... NoneOf>
    static constexpr auto group(exclude_t<NoneOf...> = exclude_t{}) noexcept {
        return basic_collector<matcher<type_list<>, type_list<>, type_list<NoneOf...>, AllOf...>>{};
    }

    template<typename AnyOf>
    static constexpr auto update() noexcept {
        return basic_collector<matcher<type_list<>, type_list<>, AnyOf>>{};
    }
```

It seems like a bug since the docs make it sound like the behavior should be "if any of the (potentially multiple) components are updated", but I figured I should confirm before submitting a PR.

**Comment by skypjack** [comment]
You can use multiple `update<T>` calls for that. Does it fail to compile too?

**Comment by Net5F** [comment]
That compiles, thanks!
