### ISSUE TITLE
entt.wiki has filenames with : in them, which probably causes problems with Git on Windows

### ISSUE THREAD

**Issue by kraybit** [skypjack/entt#1157]
Cloning the `entt.wiki` project causes problems with **Git `2.45.2.windows.1` on Windows**.

Here's a shell session showing the issue:

```
$ git clone https://github.com/skypjack/entt.wiki.git entt_wiki

Cloning into 'entt_wiki'...
remote: Enumerating objects: 1374, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 1374 (delta 0), reused 0 (delta 0), pack-reused 1371
Receiving objects: 100% (1374/1374), 578.79 KiB | 7.52 MiB/s, done.
Resolving deltas: 100% (913/913), done.
error: invalid path 'Crash-Course:-configuration.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

$ cd entt_wiki
$ git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
        deleted:    Crash-Course:-configuration.md
        deleted:    Crash-Course:-containers.md
        deleted:    Crash-Course:-cooperative-scheduler.md
        deleted:    Crash-Course:-core-functionalities.md
        deleted:    Crash-Course:-entity-component-system.md
        deleted:    Crash-Course:-events,-signals-and-everything-in-between.md
        deleted:    Crash-Course:-graph.md
        deleted:    Crash-Course:-poly.md
        deleted:    Crash-Course:-resource-management.md
        deleted:    Crash-Course:-runtime-reflection-system.md
        deleted:    Crash-Course:-service-locator.md
        deleted:    EnTT-and-Unreal-Engine.md
        deleted:    EnTT-in-Action.md
        deleted:    Frequently-Asked-Questions.md
        deleted:    Home.md
        deleted:    Push-EnTT-across-boundaries.md
        deleted:    Similar-projects.md
        deleted:    _Footer.md


$ _
```

Issuing `git restore --source=HEAD :/` just repeats the problem.

I can't say that I know, but perhaps this problem is caused by colons `:` in some of the filenames?

I've read on the Internet ([StackOverflow #63727594](https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows)) that this can perhaps be worked around by flipping some magical NTFS-setting in git. I haven't tried it. My hope is this issue report will have a similar but more wide-spread effect : )

Cheers!
Kind regards
/kraybit

**Comment by skypjack** [comment]
I didn't even know cloning the wiki was possible 😅 why are you doing it btw? All wiki files are in the main project too.

**Comment by kraybit** [comment]
Yeahno, the `entt.wiki` repos isn't "available", as far as I can see, but I found this little button in the lower right corner:

![image](https://github.com/user-attachments/assets/cb0702b7-dd6e-448d-b198-242629aacd7e)


Perhaps this could be seen as a Github bug, really?

Either way, the reason I tried to clone it was twofold:
1. In case I'd like to make a PR. But I understand/respect that's not supported.
2. Just nice to have locally (Think in case of no Internet connection)

Hm, to be honest, as far as I'm concerned, you can close this -- it's a non-issue. Sorry for taking up time.

Cheers!
Kind regards
/kraybit

**Comment by skypjack** [comment]
The wiki is in the main project because the same doc is also used for doxygen. So, it's not _the wiki_, technically speaking. It's _also the wiki_ 🙂 if you get what I mean.  Btw I never realized GH wikis can be forked, really. TIL something I didn't expect. 😅 
That said, don't worry. I'll be away for a few days in August, so I can't look into it right away. However, feel free to leave the issue open and I'll take a quick look at it when I'm back. If it can be fixed, well, why not then. I'll close the issue if it gets too complicated otherwise. 🤷‍♂️

**Comment by skypjack** [comment]
> I can't say that I know, but perhaps this problem is caused by colons : in some of the filenames?

Sorry for the late reply. You were right! Removed the colons and managed to clone it properly.
A double check would be appreciated though. Also, thanks for pointing this out! 🙏
