### ISSUE TITLE
registry.valid() causing an exception instead of returning false

### ISSUE THREAD

**Issue by calvinmullan** [skypjack/entt#1161]
In my program, I'm trying to verify if an entity is valid, and I know that it is invalid. When I call registry.valid() on the entity however, occasionally it causes an exception (seemingly at random). This is after the registry containing the entity has been cleared, and I'm expecting it to return false when I call valid(). 
the exception happens in the final line in the following statement:

[[nodiscard]] auto sparse_ptr(const Entity entt) const {
    const auto pos = static_cast<size_type>(traits_type::to_entity(entt));
    const auto page = pos / traits_type::page_size;
    return (page < sparse.size() && sparse[page]) ? (sparse[page] + fast_mod(pos, traits_type::page_size)) : nullptr;
}

(the exception is: Exception thrown at 0x00007FF62F36BD1D in Editor.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.)

I was not aware that this function should ever throw an exception, so I believe this is a bug.

**Comment by calvinmullan** [comment]
To update, I am using a different strategy to band aid fix this, so I am not too fussed if this can't be solved.

**Comment by skypjack** [comment]
Do you have a repro? It looks like a call on a moved-from registry to be honest.

**Comment by calvinmullan** [comment]
Ahh, yes I believe the registry got deleted, so that may be the cause?

**Comment by skypjack** [comment]
I mean, if you invoke `valid` on a deleted or moved-from registry, then yes, this is definitely a problem.
In general, a moved-from object in C++ is in a safe but unspecified state. It means that you can drop it without worrying but that you shouldn't use it anymore.

**Comment by skypjack** [comment]
I'm closing this issue as there is nothing to fix or change here if the error was due to using a moved-from object.
