### ISSUE TITLE
Feature request: Make 'entt::null' available in <entt/entity/fwd.hpp>

### ISSUE THREAD

**Issue by kraybit** [skypjack/entt#1170]
```cpp
#include <entt/entity/fwd.hpp>

struct Thing
{
	entt::entity target { entt::null }; // ERROR : Can not resolve symbol 'null'
};
```

Would be nice if this worked.
Cheers!
Kind regards /kraybit

PS. Or I'm doing this wrong, of course. Then please enlighten me : )

**Comment by skypjack** [comment]
You should include `entity.hpp` for that, which is another small and self-contained file that contains only entity related stuff.
The problem with including `entt::null` into `fwd.hpp` is that it needs the `entt::null_t` type, which is out of scope for a forward file.
