### ISSUE TITLE
.clang-tidy typo

### ISSUE THREAD

**Issue by NicksWorld** [skypjack/entt#1178]
`.clang-tidy` contains a typo which causes the readability suite of tests to remain disabled. Changing this line to read `readability-*` will enable these lints. A quick test with clang-tidy enabled emits a number of new warnings. 

https://github.com/skypjack/entt/blob/a5ce90b268e2eac089b22b6b97ea97a8b15aedc1/.clang-tidy#L18

The lints include a number of warnings on items that may be deemed unnecessary such as requiring the integer suffixes to be uppercase, which may warrant being disabled as well.

**Comment by skypjack** [comment]
🤦‍♂️ thanks for pointing this out. 👍
