### ISSUE TITLE
Make a Discord Server or a Gitter Chat?

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#118]
This would be awesome for the EnTT community which grow's up !

**Comment by Alan-FGR** [comment]
Gitter! :laughing:

**Comment by skypjack** [comment]
I just saw that `EnTT` isn't available as a name on Gitter. Suggestions? :smile: 
I was thinking about `entt_ecs` or `entt_cpp` or whatever.

**Comment by Milerius** [comment]
EnTT is more than an ECS ! entt_framework <3 ?

**Comment by skypjack** [comment]
It could be also `entt_cpp`... who know if in future someone decides to join me and develop a version with JS or C# or whatever?

**Comment by Kerndog73** [comment]
If only we could discuss the name for the Gitter channel on the Gitter channel before creating it, but then we’d have a pesky deadlock to worry about.

**Comment by Alan-FGR** [comment]
> I just saw that EnTT isn't available as a name on Gitter. Suggestions?

@skypjack well, I just created a room with that name to test and had no problems :confused:

**Comment by skypjack** [comment]
@Alan-FGR GitterLoggerBot? O.o

**Comment by Alan-FGR** [comment]
Yeah, in my darkest hours :trollface:... anyway, I don't see why you wouldn't be able to create EnTT/EnTT

**Comment by skypjack** [comment]
[Here](https://gitter.im/skypjack/entt) it is. Thank you guys. See you soon.

**Comment by ArnCarveris** [comment]
@skypjack Put link into `README` file.

**Comment by iderik** [comment]
You can connect to Gitter with a irc client, check this out: https://irc.gitter.im/
