### ISSUE TITLE
Runtime Eror with groups

### ISSUE THREAD

**Issue by MineStorm999** [skypjack/entt#1181]
I get this runtime error: 
```Assertion failed: ((std::all_of(groups.cbegin(), groups.cend(), [](const auto &data) { return !(data.second->owned(type_id<Owned>().hash()) || ...); })) && ("Conflicting groups")), file ...file/path/to/source...\entt\entity/registry.hpp, line 1105```

code:
```EntityManager::GetWorld().group<MeshInstance>(entt::get<Transform>).size()```
EntityManager::GetWorld() basically returns the registry

**Comment by MineStorm999** [comment]
Ok is it the same with Views?

**Comment by skypjack** [comment]
No, they don't _own_ anything.

**Comment by MineStorm999** [comment]
Thanks a lot
