### ISSUE TITLE
Multiple components same type

### ISSUE THREAD

**Issue by 1vanK** [skypjack/entt#1185]
Let's say you described a component - a laser cannon. The cannon can be mounted on a tank, or on a building. The tank can get hit, and the tracks will stop moving, but the cannon will continue to fire, or the turret with the cannon can be detached, and the cannon can similarly continue to fire.

But in EnTT, you simply can't add multiple components of the same type to one entity.

What do you do when you have an airplane with several laser cannons? In other words, you can't easily make it so that one cannon gets detached, falls to the ground, while the other laser cannons continue to fire.

Okay, I create a weapons component that holds an array of entities, each of which is a laser cannon. But I need to move the cannons not separately, but together with the airplane. And now I have to store the entity of the parent object (the airplane) in each cannon. In short, it becomes a mess.

**Comment by skypjack** [comment]
> But in EnTT, you simply can't add multiple components of the same type to one entity.

You can have multiple components of the same type already:
```cpp
registry.storage<cannon_type>("left_cannon"_hs).emplace(entity);
registry.storage<cannon_type>("right_cannon"_hs).emplace(entity);
```
See [here](https://github.com/skypjack/entt/wiki/Entity-Component-System#meet-the-runtime) for more details.
If you have any further questions once you have read the documentation too, then I am here. Moreover:

> I create a weapons component that holds an array of entities, each of which is a laser cannon

You can also create a component with a fixed-size array of cold elements and a counter of in-use ones.
There is no need to use cannons to kill mosquitoes sometimes. It really depends on the user case.

**Comment by 1vanK** [comment]
I used chat GPT which said that in entt this is impossible to have multiple components of the same type xD

Thanks!

**Comment by 1vanK** [comment]
I use chat GPT when I'm learning the basics of something new, it's useless for more professional stuff xD

**Comment by Innokentiy-Alaytsev** [comment]
It's dangerous for learning, because you can't distinguish correct information from incorrect information. Anyway, there is a better neuronal network for learning things. Everyone have it.

**Comment by 1vanK** [comment]
Can [this](https://github.com/dviglo2d-learn/mini_games/tree/main/letalka) be added to <https://github.com/skypjack/entt/wiki/EnTT-in-Action>?

**Comment by skypjack** [comment]
Sure thing. Can you provide name, link and a short description in English? Similar to what you see for the other games. Thanks. 👍

**Comment by 1vanK** [comment]
Well, I don't know how to describe it. It's a small demo for [engine](https://github.com/dviglo2d/dviglo2d). Ships fly out onto the screen, the player shoots at them and gets points for it.

Something like Tyrian https://www.youtube.com/watch?v=w4XOBfOcYgE

It's called "Letalka"

**Comment by skypjack** [comment]
Got it. Adding it to the wiki. 👍

**Comment by 1vanK** [comment]
Thank!

**Comment by 1vanK** [comment]
"Letalka" moved to https://github.com/dviglo2d/dviglo2d/tree/main/games/letalka

**Comment by skypjack** [comment]
Fixed it and updated the wiki. Thanks for the heads-up. 👍
