### ISSUE TITLE
Proposal - Fictional type support

### ISSUE THREAD

**Issue by GuusKemperman** [skypjack/entt#1186]
# Abstract

I propose entt provides support for fictional types inside entt::registry, based on [a discussion that was held a few weeks ago on discord.](https://discord.com/channels/707607951396962417/800747394521890867/1285229637169057803)

# Fictional types?

Also known as 'runtime' types, or 'virtual' types. They are types that have no C++ equivalent, they might exist as part of a different scripting language, or they might be loaded as an asset from a file.

# Motivation

Currently, entt::registry can only store types that have a C++ equivalent. This makes it difficult to implement scripting support if your type has no C++ equivalent. This proposal offers a solution to improve scripting support in entt::registry.

There are runtime reflection systems that support fictional types. The data-layout of a fictional type is stored as an asset on file. This type can work very similarly to a C++ type, by mallocing the total size and accessing the fields based type and offset. 

For example the default constructor could look like this:

```cpp
// Iterate over fields of toType and default construct them based on their offset
for (const MetaField& field : fictionalType)
{
        const MetaType& memberType = field.GetType();

const uintptr memberOffset = field.GetOffset();
    void* memberAddress = reinterpret_cast<void*>(addrAsInt + memberOffset);
memberType.ConstructAt(memberAddress);
  }
```

You have a type that you can feed to your script interpreter, the size of this type is known at runtime, and there are functions available to construct, copy, move and destruct it. The only problem? You can't place it in an entt::registry. 

**Solution**

The idea is to use the abstract interfaces currently in place, and create implementations that can work with full type erasure. There are abstract baseclasses such as entt::sparse_set, and derived classes that override the functions that require the full type, such as entt::storage<Transform>. The storage knows how to construct, copy, move, and destruct the type. To support fictional types, you need to add another derived class, such as entt::fictional_storage that has the required function pointers for constructing, copying, moving and destructing. [This is exactly what we did in Coral Engine](https://github.com/GuusKemperman/CoralEngine/blob/39a86d7ff667518a458fa276a4fa1fa8066d8de5/Source/World/Registry.cpp#L25)

One way to add this functionality to entt is by exposing an overload for the add_fictional_storage function that requires the user to provide callbacks for constructing, copying, moving and destructing their type.

```cpp
template<typename UserDataT>
entt::sparse_set* storage(
        id_type type_hash,
        std::string fictional_name,
        uint32 type_size,
        UserDataT&& user_data
        void(*default_constructor)(const UserDataT&, void* address), 
        void(*move_constructor)(const UserDataT&, void* address, void* original),
        void(*move_assign)(const UserDataT&, void* src_address, void* dst_address),
        void(*destructor)(const UserDataT&, void* address, void* original));
```

UserData would contain the necessary type information, for example a runtime reflection representation of their fictional type. The userdata would be stored inside the storage, and passed along to the callbacks. This way it only needs to be stored once. I'd love to get feedback on the API for this function.

Entt could then be integrated with runtime reflection systems that support fictional types.

```cpp
void construct(const Type& type, void* address) { type.ConstructAt(address); } 
void move_construct(const Type& type, void* address, void* original) { type.MoveConstructAt(address, original); } 
void move_assign(const Type& type, void* address, void* original) { type.MoveAssign(address, original); } 
void destruct(const Type& type, void* address) { type.DestructAt(address); } 

void load_script(std::string_view filename)
{
  Type type = load_type_from_file(filename);
  
  reg.add_fictional(type.get_hash(), type.get_name(), type.get_size_in_bytes(), type, &construct, &move_construct, &move_assign, &destruct);
}
```
# What about entt::meta?

In the future I'd like to add support to entt::meta for fictional types as well, but the scope of that change is significantly larger. Better to start small!

# Impact

The API would not grow significantly; only two more functions would be added. Internally, there would be another class added that derives from entt::sparse_set with similar functionality as is currently in entt::storage. Most of the 'common' functionality between storages has been moved to the baseclass entt::sparse_set, keeping code repetition at a minimum. 

Having to register the types beforehand conflicts with entt's current design of not having to 'announce' component types beforehand. I don't see a way around it in this scenario, and seeing as this functionality is completely opt-in, for a relatively specific usecase, I think it's perfectly acceptable. [The user can also use wrapper functions to recreate the 'lazy' initialization.](https://github.com/GuusKemperman/CoralEngine/blob/d161615e6f458284ce9c47d7cc2bfcce8dab8345/Source/World/Registry.cpp#L402)

# Implementation experience

I have implemented this exact proposal before for Coral Engine. I had [modified entt::registry to expose a function that allowed me to add my custom storage class to the map of pools](https://github.com/GuusKemperman/CoralEngine/blob/d161615e6f458284ce9c47d7cc2bfcce8dab8345/External/entt/entity/registry.hpp#L1350C5-L1350C31), and I had ofcourse implemented [a custom storage class](https://github.com/GuusKemperman/CoralEngine/blob/39a86d7ff667518a458fa276a4fa1fa8066d8de5/Source/World/Registry.cpp#L25). 

# Conclusion

This relatively small change opens up a lot of possibilities, it is fully opt-in and proved incredibly helpful during the development of Coral Engine. It opens up future possibilities of expanding entt::meta for better scripting support. I'd love to hear your thoughts on this proposal, including anything I've missed and anything I could change to be more consistent with entt's design

**Comment by GuusKemperman** [comment]
I realized a few days after opening this issue that there is a 'simpler' solution.

You can use whichever type you use as an 'any', e.g., entt::any or std::any. If your runtime reflection library supports fictional types, entt::registry already supports fictional types!

```cpp
for (const Script& script : GetAllAssets<Script>())
{
  MetaType type = ReflectTypeFromScript(script );
  registry.storage<MetaAny>(type.Hash());
}
```
With this approach each individual MetaAny stored inside the storage 'own' an instance of a fictional type that is stored on the heap. While my proposal would be a big optimization as you would have a lot fewer heap allocations, I personally don't consider the tradeoff of increasing entt's size worth it if there is an existing, simpler solution.

*Instead*. I will propose to add support for fictional types to entt::meta, I don't have much time today, but tomorrow I'll look into it and write a proposal for adding fictional type support to entt::meta. I'll either re-open this issue or open another one.

**Comment by skypjack** [comment]
I've been looking at the fictional type for meta. I think a factory for the `void` type might be the right fit for that. It needs some fixes, but I'm more than willing to give it a try. Any other ideas in the meantime?

**Comment by GuusKemperman** [comment]
Hi! My apologies for the delay, I started working on the implementation and got side-tracked by life :)

I agree with the idea for using a void type, made a specialization for the factory for entt::fictional_t. I'm picturing the API to look something like this:

```cpp
    entt::meta<entt::fictional_t>("myScript")
        .data<int>("Health"_hs)
        .data(entt::resolve<float>(), "Speed"_hs)
        .data(+[](entt::any member, const entt::data_context& context)
            {
                script_interpreter(context.data.prop("getter"_hs));
            })
        // Argument count and types can be deduced
        .func("PartiallyDynamicFunc", +[](int num, float otherNum, const entt::func_context& context)
            {
                return context.func.prop("script"_hs).value().cast<script>().invoke(num, otherNum);
            })
        // When we want to support fictional types as arguments, how do we specify that?
        // We could have a low-level way of registering functions?
        .func("MyDynamicFunc", 
            3, // arity
            +[](std::size_t argNum, const entt::func_context& context) -> entt::meta_type // argument getter
            {
                return context.func.prop("script"_hs).value().cast<script>().arg(argNum);
            },
            +[](const entt::func_context& context) -> entt::meta_type // Return type getter
            {
                return context.func.prop("script"_hs).value().cast<script>().ret();
            }
            +[](entt::meta_handle instance, entt::meta_any* const args, const entt::func_context& context) -> entt::meta_any // Invoker
            {
                return context.func.prop("script"_hs).value().cast<script>().invoke(std::move(instance), args);
            })
```

The type 'alias' needs to be provided to the constructor, as the meta_type internally needs to be constructed with a unique type_id right of the bat. One potential problem related to the type_info is that type_info is usually stored as a pointer, and in it there is a type_alias that is a non-owning string_view. This data does need to be stored somewhere, but I'm not sure what the best place for this is. Maybe the type_info in meta_type_node could be stored by value, and the user themselves is responsible for managing the lifetime of their string? Not very good practice, but it is more in line with entt's pay-for-what-you-use vision. The type_info could also be stored as a property in the type_descriptor, this would come at no cost to users who do not use fictional types, but it's also unintuitive for the user if there are properties present they didn't register... Something to think about!

The .data function is pretty straight-forward, but internally I'm not sure yet how it will work. We could keep track of the current size of the type. If the user registers an 'int' we increment the size by sizeof(int) (or more if needed for alignment), and add a setter/getter pair for an integer at the offset of old-size of the type. Maybe we should also support a .padding function, that just increments the size? That way you can manually adjust the layout of the type if need be. 

The user can also register custom functions, in order to avoid capturing any arguments there'd be an option to use entt::data_context or entt::func_context as a last argument. 

One idea that I've been thinking about for a while is how to handle constructors. For Coral Engine we had a default constructor that would allocate enough size to construct all the data members, and then default construct the data members in place. This constructor would be registered **after** all the data members, since if some data members could not be default-constructed, you cannot have an implicitly generated default constructor. I think the same idea would work for entt::meta_factory<void>; the user has to explicitly add default/copy/move constructors and a destructor.

```cpp
        .ctor<>()
        .ctor( // Custom copy constructor
            1, // arity
            +[](std::size_t argNum, const entt::func_context& context) -> entt::meta_type // argument getter
            {
                return context.outer.type;
            },
            +[](entt::meta_handle instance, entt::meta_any* const args, const entt::func_context& context)
            {
                entt::fictional::copy_copyable_members(instance, args[0]);

                // Do some custom logic here
            })
        .dtor();
 ```

What do you think?

**Comment by skypjack** [comment]
Sorry for the late reply. I decided to close a few things on the meta side so that I can work on this one now without unwanted stuff all around. 🙂 
So, my first question is: why `entt::fictional_t`? I mean, why not `entt::meta<void>`? If we don't want a C++ type there, `void` looks much better and captures the intent. 
Does it make sense? I think it's also easier to do like this. A bunch of `std::is_void_v<Type>` should get the job done for the large part.

**Comment by GuusKemperman** [comment]
No worries! 

I don't feel too strongly when choosing between ```void``` or ```entt::fictional_t```

I have a *slight* preference for ```entt::fictional```. Using ```void``` is a bit less clear, as the same keyword then means different things in different contexts.; ```void``` is used frequently as part of a function signatures and ```void``` pointers, while ```entt::fictional_t``` would *only* be used for fictional types. It's also a bit easier to document by adding a comment above the struct, and easier to google. But again I don't feel strongly about the matter, ```entt::meta<void>``` is shorter, and ```void``` represents something 'typeless', and that's exactly what we're going for here.

I think it mostly comes down to preference and what is more in line with entt's design, for which I'll trust your expertise 🙂

**Comment by skypjack** [comment]
I think the point is that the factory argument is also the meta function or meta data argument in general.
That is, the element on which data members are looked up and the `this` of the functions. Even when you bind a free function, the factory type is the first element in the list of arguments (if you like ofc).
Therefore, using an `entt::whatever` makes me feel like I can attach a `void f(entt::whatever &ref, other_args...)` function to it. However, this isn't the case. In this regard, I think `void` captures better what's going to happen. There is no type, that's it. 🤷‍♂️ 

That said, yesterday I tried to implement it and figured out that some functions don't make much sense with this factory.
For example, `conv` is pointless as well as `ctor` or `dtor` because we're typeless here. At the end of the day, in this kind of scenario I see a purpose only for `data` and `func`. Does it make sense to you?

**Comment by GuusKemperman** [comment]
Ahh that's a very good point, ```void``` definitely works better than.

I'm not sure what you mean with ```ctor``` and ```dtor``` being pointless, could you elaborate? I don't think ```conv``` is very useful,  but I think having custom constructors & destructors are needed for hooking up ```entt::meta``` to whichever scripting tool you're using.

It'd for example be really useful to be able to specify the default value of data members, especially since not all data members are default constructible. The user could provide a callback using ``ctor``` and ```dtor```, the callbacks take either an ```void*``` (or some form of meta_handle), and the user could use the data members offset to construct them in place with whatever value they like.

But more importantly, some scripting frameworks don't have a sequential C-like layout for the scripting types; they have different 'wrappers' around instances of the script types, such as ```sol::table``` for Lua. Instead of the user constructing the data members in the ctor/dtor, the user could construct/destruct a ```sol::table``` at the provided address.

I'm going away for a week today so it might take some time for me to respond, but let me know what you think or if I missed something

**Comment by skypjack** [comment]
Looking into this one. To start with, I think we need to change the way the context works, because it stores meta types in a map where the index is the type id. This makes it impossible to construct multiple meta types for the same C++ type, even with `void`. 🤔
