### ISSUE TITLE
Emitter.on(...) result is not homogenous, so can't store in container.

### ISSUE THREAD

**Issue by gamagan** [skypjack/entt#119]
https://github.com/skypjack/entt#event-emitter

I'm trying to implement a generic solution where a listener is automatically removed from emitter object, using Emitter.erase(...), when the listener goes out of scope. The Emitter.on(...) function returns a connection object that is templatized based on the event type. This makes it impossible to store different connection objects in a container.

Specifically, in my case, I'm trying to have a 'System' base class keep a list of connection objects for which derrive classes subscribe. Then, in the destructor of the base System class, I'm trying to disconnect the events from the emitter. But, because I can't store the connection objects, I can't do it.

Is there a way to get around this limitation?

**Comment by skypjack** [comment]
Something like (remember that connections are copyable)?
```
std::vector<std::functional<void()>> vec;
vec.emplace_back([conn, this]() { emitter.erase(conn); });
```
On destruction, you can run all the functions and disconnect everything.

**Comment by gamagan** [comment]
Hehe, I actually just implemented that exact thing.
I ran into another problem: you can't call erase twice on the same conn object. So, if the subscriber erases its connection then the auto disconnect will crash, because it was already disconnected. I'll see how I can get around this other particular issue.

Thanks, man.

**Comment by skypjack** [comment]
>you can't call erase twice on the same conn object

Yeah, more or less for the same reasons mentioned above: connections are aliases for lists' iterators. You cannot erase twice the same iterators and therefore you cannot do that for a connection.

Just a note: I've never used emitters with systems. Take a look at the other signalling stuff.
