### ISSUE TITLE
compiler error GCC 11.4.0 in sparse_set.hpp

### ISSUE THREAD

**Issue by beekayer** [skypjack/entt#1194]
On:
gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

With entt checkout:
Using v3.14.0

Compiler Error:
/entt/entity/sparse_set.hpp: In member function ‘auto entt::basic_sparse_set<Entity, <template-parameter-1-2> >::policy_to_head() const’:
/entt/src/entt/entity/sparse_set.hpp:168:50: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  168 |         return static_cast<size_type>(max_size * static_cast<decltype(max_size)>(mode != deletion_policy::swap_only));
      |                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by beekayer** [comment]
Sorry, not  a compiler error per se, it's a warning and I build project with -Werror so I have to make an exception for entt and now project spews up that warning.  You know what I mean.

**Comment by 1vanK** [comment]
![Image](https://github.com/user-attachments/assets/24480668-8708-4df6-9725-7326ac12f4ec)

**Comment by 1vanK** [comment]
This works (double brackets)

![Image](https://github.com/user-attachments/assets/cd83a832-d47c-48df-92ef-9f55562b1b33)

**Comment by skypjack** [comment]
I think an `std::remove_const_t` works as well there? Have you tried it @1vanK ?

**Comment by 1vanK** [comment]
yes

![Image](https://github.com/user-attachments/assets/a1aa423d-524a-4175-bfd6-05f0369b290d)
