### ISSUE TITLE
The program crashes when nothing abnormal happens

### ISSUE THREAD

**Issue by cyrant** [skypjack/entt#12]
'The program has unexpectedly finished' with this minimal code:
```
int main (void) {
  struct Pos { float x, y; };
  auto registry = entt::DefaultRegistry<Pos>{};
  auto entity = registry.create<Pos>();
  return 0;
}
```
And no, with this addition of code to the end:
```
#ifndef NDEBUG
  registry.reset();
#endif
```
It seems to me that this confusing behavior, depending on the NDEBUG definition, looks bad, as well as this part of the code:
```
~SparseSet() noexcept {
  assert(empty());
}
```

**Comment by skypjack** [comment]
In production environment I usually want to be sure that all the entities have been correctly deleted, thus all resources have been correctly released.  
That's why there is an assert in debug mode to force a call to `reset` at the end of the process.

It works as expected, this is not a bug, I'm sorry.

**Comment by cyrant** [comment]
But you do not get what you want. Look at your code:
```
~SparseSet() noexcept {
  assert(empty());
}
bool empty() const noexcept {
  return direct.empty();
}
std::vector<index_type> direct;
```
[From the standart:](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4687.pdf#section.15.4)
> 9. After executing the body of the destructor and destroying any automatic objects allocated within the body, a destructor for class X calls the destructors for X’s direct non-variant non-static data members, the destructors for X’s non-virtual direct base classes and, if X is the type of the most derived class (15.6.2), its destructor calls the destructors for X’s virtual base classes. ...

So, _direct_'s (object of std::vector class) destructor will be guaranteed to be called. Checking _direct.empty()_ is not needed.
Moreover, according to the standard, this check is not correct. Since the destructors of class members (_direct.std::vector::~vector()_) will be called after execution of _~SparseSet()_ body. That's why you always (without NDEBUG definition) get an abnormal program termination, even if nothing wrong has happened.

**Comment by skypjack** [comment]
Actually no, if you call `registry.reset();` (that is the recommended way) everything works just fine.  
I can partially agree on the fact that components would be destroyed in any case, but I'm reworking the ECS to use raw storage (aka `char`s), thus it won't apply anymore.  
That being said, I don't see the problem of invoking `reset` before to destroy the ECS yet, I'm sorry. What's the real problem you are experiencing?

**Comment by cyrant** [comment]
Why not just add _registry.reset()_ (maybe with _#ifndef NDEBUG ... #endif_) to _~SparseSet()_ instead of assertion?
The problem is that the program terminates incorrectly when it should.

**Comment by skypjack** [comment]
Mainly because the `reset` can throw (it depends on the components' types and we have no control over them) and to check that components have been properly destroyed is easier, faster and safer. Moreover because I want to be sure I've destroyed all the components on purpose when I destroy the registry. I don't want it to hide issues around by cleaning up my data.  
Again, I don't see the problem with calling `reset` before to discard the registry yet, if any.

**Comment by cyrant** [comment]
Direct calling of `reset` is unobvious. And it breaks RAII idiom.

**Comment by skypjack** [comment]
Actually RAII idiom is something slightly different from what you got if you find this breaks it. And _unobvious_ is something undocumented, that isn't the case for the requirement of calling `reset`.  
I'm sorry but you can have the cake and eat it with `EnTT`, at least with version 1.x (the current master). Version 2.x on which I'm working on right now won't have that assert probably, so stay tuned if you are interested.

**Comment by cyrant** [comment]
The STL, a good example of idiomatic C++, never requires me to call smth like `reset()` (release? clear? free?) directly to not abort my program. Because of ([thanks to Wikipedia](https://en.wikipedia.org/wiki/Resource_acquisition_is_initialization)):
> .. resource deallocation is done during object destruction, by the destructor. Thus the resource is guaranteed to be held between when initialization finishes and finalization starts, and to be held only when the object is alive.

That's why I described this requirement as _unobvious_. I mean _unexpected_. I am sorry for my English. (It is far from my native language. Which is Russian.)

One more thing. As far as I understand, since C++11 no `erase()`, `clear()`, `pop_back()`, `pop_front()` function throws an exception, `SparseSet<Index>::reset`, `SparseSet<Index, Type>::reset`, etc may have `noexcept` specifier.

Anyway, thank you for your work. I feel the pulse of EnTT progress. Your library is very fast and it has must-have feature for me: it can sort components in memory. Good luck!

**Comment by skypjack** [comment]
Just a question.  
If I succeeded to remove the requirement of statically specifying components when users declare the registry, so that you can do this:
```
Registry registry;
auto entity = registry.create<Position>();
// ...
```
Do you think it could be a nice to have feature? I'm interested in the opinion from users.  
The price to pay is a potential performance hit when you create components, that's all. Performance should be unaffected.  
Moreover multicomponent views should reach the performance of single component views and still nothing to specify at compile-time time.

What about?

That's something I'm working on...

**Comment by cyrant** [comment]
I do not see a big difference. In both cases, types of components must be known at compile time, right? But, if multicomponent views will really gain performance boost, it sounds good for my goals. Considering that I don't create dozens of objects at each loop of the program's main cycle.

---
If the pool (sparse array) is used only within the library, then it does not matter who manages its contents. But for the registry, which is used as a public API, following the RAII idiom (including release of components without outside help) would not be superfluous. Compare this:
```
auto registry = std::make_shared<Registry>(); // it works like charm
```
With this:
```
std::shared_ptr<Registry> registry (new Registry(), [](Registry* r){ r->reset(); });
// thanks to lambda I don't need to use monstrous std::bind,
// anyway code looks weird and it has two memory allocations instead of one
```
Following the idiom in this case not only frees users from manual memory management, but also makes registry easier to use in C++ code.
But you're right, I do not understand why that `assert()` is needed. What's a reason to force users clear registry explicitly? Why not use registry's destructor? I'll try to figure it out the other day.

**Comment by skypjack** [comment]
Well, the biggest difference should be in terms of compilation time when you change the components list or a component definition. The registry is included in all the files that work with components, the single component affects only a few files. In large projects it means you have far less files to recompile.  
Other differences exist but have not that impact indeed.

**Comment by cyrant** [comment]
I prefer to avoid OOP in my code. Sort of:
```
// A.hpp: // potentially drawable component 
struct A {
  int[8] vertices;
};

// B.hpp: // potentially printable component 
struct B {
  char[256] string;
};

// E.hpp: // ECS with all components (can be a precompiled header)
#include "A.hpp"
#include "B.hpp"
#include "ecs.hpp" // entt or entityx/experimental/compile_time
using E = ECS<A,B>;

// D.hpp: // external rendering library
void draw (int[8]) { ... }
set_draw_state (int) { ... }

// ED.hpp: // rendering system
#include "E.hpp"
#include "D.hpp"
void draw (E const& es, int s) {
  set_draw_state(s);
  for (auto& i: es.view<B>()) { draw(e.vertices); }
}

// P.hpp: // external printing library
void print (char[256]) { ... }
void print_colored (char[256]) { ... }

// EP.hpp: // printing system
#include "E.hpp"
#include "P.hpp"
void print (E const& es) {
  for (auto& e: es.view<B>()) { print(e.string); }
}
void print_colored (E const& es) {
  for (auto& e: es.view<B>()) { print_colored(e.string); }
}
```
As you can see, there is no difference for me.

**Comment by skypjack** [comment]
Good. So, as long as performance aren't affected, you have no preferences. Thank you.  
See #13 for more details on upcoming changes if you want to discuss them or give your own suggestions.
