### ISSUE TITLE
Adding/Removing components during iterations can lead to crashes

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#120]
Changes made for #93 (probably) broke something internally and this feature (something I love actually) is no longer safe to use (at least until the bug is fixed).

**Comment by vblanco20-1** [comment]
I ran into this bug probably. I found it most common with persistent views, wich could get broken and eventually crash.

**Comment by skypjack** [comment]
@vblanco20-1 yeah, it affects all the views, if you add or remove components during iterations and it does reallocate under the hood, iterators are invalidated and you incur in crashes unfortunately.  
This is something I want to fix, because I find that feature a must have for a lot of reasons, so stay tuned.
