### ISSUE TITLE
SIGSEGV: Assertion `context.value.contains(info.hash())' failed.

### ISSUE THREAD

**Issue by sigmareaver** [skypjack/entt#1202]
```
ASM generation compiler returned: 0
Execution build compiler returned: 0
Program returned: 139
output.s: /opt/compiler-explorer/libs/entt/v3.12.2/src/entt/meta/factory.hpp:34: decltype(auto) entt::internal::owner(entt::meta_ctx&, const entt::type_info&): Assertion `context.value.contains(info.hash())' failed.
Program terminated with signal: SIGSEGV
Registering reflection for component: 9Transform
```

I was playing around on Compiler Explorer (see here: https://godbolt.org/z/jvrTTv4bb) and got this, but I'm not sure if I'm doing something wrong, or if this is a bug. Any assistance would be appreciated.

**Comment by sigmareaver** [comment]
I was using the code from the reflection wiki article that uses the `meta_factory` object initializer format:
`entt::meta_factory<Transform>{}.type("Transform"_hs)`
But I found that replacing this with:
`entt::meta<Transform>().type("Transform"_hs)`
resolved the segmentation fault.

**Comment by skypjack** [comment]
Indeed, you're right. The wiki contains the doc for the current `master`.
If you want to look at the documentation for the last stable version, you can see [here](https://github.com/skypjack/entt/tree/v3.14.0/docs/md) (repo tag) or [here](https://skypjack.github.io/entt/pages.html) (doxygen doc).

**Comment by sigmareaver** [comment]
I see that warning on the wiki home page now. My apologies for that. When you're skimming documentation for a specific purpose, it's easy to miss the little details. :sweat_smile:
