### ISSUE TITLE
warning C4307: '*': integral constant overflow

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#121]
This snippet from the docs
```
constexpr auto identifier = entt::ResourceCache<MyResource>::resource_type{ "my/resource/identifier" };
```
Compiled under VS2017 produces a warning
```
warning C4307: '*': integral constant overflow
```

**Comment by skypjack** [comment]
Cannot reproduce on appveyor with VS2017 - https://ci.appveyor.com/project/skypjack/entt

Can you suggest changes to reproduce it?

**Comment by huwpascoe** [comment]
I've isolated the class here:
https://godbolt.org/g/HnpC5E

The part that causes the warning seems to be `partial^str[0]`

**Comment by skypjack** [comment]
It looks like MSVC is the sole compiler to report this warning. Honestly, I don't even know why it's reporting the error, so... I'd safely ignore it. That is a fast hash function, it works _somehow_ anyway, for some definitions of _somehow_.  
I won't spend my time looking into the reasons of MSVC, I'm sorry. However, if you can come up with a working solution, I'd be glad to review the PR and discuss it.

**Comment by skypjack** [comment]
It looks like MSVC does a promotion of `partial` towards `char` and thus an overflow is possible when it combines the result with a `long`. Btw I was convinced the promotion was the other way around, that is how it's performed ie by clang (we can see it with `-Weverything`). As noted by others on gitter (feel free to join us), an explicit promotion to `long` makes the warning disappear.

**Comment by skypjack** [comment]
Ok, tested it. Despite the warning triggered by MSVC, the returned value is right. I made some automated tests and the hash function works as expected. So, well, I'd say it's not a bug. :smile: 
You can safely use the hashed string and ignore the message. Try to suppress the warning if it's annoying (ping me if you find a way to do it or drop a comment below, it will help other users in future), but be aware that under the hood everything works as expected.

---

Do not forget to star the project if you find it's worth it and you decided to use `EnTT`.  
Also, feel free to contact me or create a PR to add you project to the README file if you want.

**Comment by skypjack** [comment]
I invite you to join the gitter channel if you have any question about the library or if you want to meet other users. I'd be curious to know for what you're using `EnTT`.

**Comment by Milerius** [comment]
i have the same problem :/

**Comment by skypjack** [comment]
@Milerius the same solution doesn't work for you? It seems an idiosyncrasy of msvc, there isn't much to say about that.

**Comment by huwpascoe** [comment]
Workaround now in macro form!
```
#if defined(_MSC_VER)
	#define HS(x) \
		__pragma(warning(push)) \
		__pragma(warning(disable:4307)) \
		entt::hashed_string{ #x } \
		__pragma(warning(pop))
#else
	#define HS(x) entt::hashed_string{ #x }
#endif
```
Usage example:
```
constexpr auto identifier = HS("my/resource/identifier");
```

**Comment by skypjack** [comment]
Interesting. Do you mind if I put this in the FAQ?

**Comment by huwpascoe** [comment]
Go for it!
