### ISSUE TITLE
Disambiguate tag and component calls

### ISSUE THREAD

**Issue by eugeneko** [skypjack/entt#127]
There are two versions of `Registry::get` -- `get()` for tags and `get(entity)` for components.
So, if entity parameter is missing, this error would be spotted only in runtime.
It is suggested to disambiguate these signatures so missing entity param would cause compiler error.
Maybe there are other places like this.

**Comment by Kerndog73** [comment]
Somewhat related...

```C++
constexpr tag_t tag {};
```

That way, you can type `entt::tag` instead of `entt::tag_t{}`.

**Comment by skypjack** [comment]
Good point. B
I'll use `tag_t` consistently to disambiguate.  
Out if my mind, also `has` suffers from the same problem and probably other member functions as well.

**Comment by skypjack** [comment]
@Kerndog73 Despite the fact that I like your proposal, it's not feasible because of `entt::break_t` and I prefer to use a _all or nothing_ policy. We should probably change the name of the tags used to dispatch the calls to something more meaningful.

**Comment by Kerndog73** [comment]
Maybe you could rename `break` to `cancel` but break really is the best word for the situation. Maybe you could intentionally misspell it and use`brake`. But it's probably best to just leave it. 😢

**Comment by skypjack** [comment]
I'm adding a new tag (`entt-v3`) to mark this kind of issues. All of them will be closed when `EnTT` v3 is released.  
This issue is tagged `entt-v3` mainly because it requires a breaking change to the API ( actually two if I consider also the request made by @Kerndog73 ).

**Comment by skypjack** [comment]
All changes have found their way in EnTT v3 somehow, as mentioned.  
In case of no feedback, I'm closing the issue in a couple of days.
