### ISSUE TITLE
lambda support for signalling

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#132]
This syntax especially
```
struct S {
    int capture;
    void bar(int, char) { /* ... */ }
};
S instance{ x };
signal.sink().connect<S, &S::bar>(&instance);
```
Would be very useful to support lambda syntax (c++ converts to the very same pattern internally, I think)
```
signal.sink().connect([x](int, char) { /* ... */ });
```

**Comment by Kerndog73** [comment]
The signal stuff is made to be fast. It’s designed to avoid allocations. If you want a lambda with state, you have to store the state somewhere. `std::function` will allocate space for that state but `entt::Delegate` will not. Supporting this feature would introduce allocations everywhere.

If your lambda is state-less then it can be cast to a function pointer. Unary plus operator can do that.

```C++
signal.sink().connect<+[] (int,char) {
  /* ... */
}>();
```

I’m not sure how you would go about `disconnect`ing that though.

**Comment by skypjack** [comment]
What @Kerndog73 said is more or less what I'd have said, but for the fact that lambdas cannot be used as template parameters in any case as far as I remember.

The fact is that `SigH` is all about template and it isn't in charge of the lifetime of the listeners. Supporting lambdas the way you're proposing requires a completely different design and some allocations around, more or less what `Emitter` offers.

If you want to create a signal class that accepts lambdas, probably `SigH` isn't what you're looking for, that's all. The idea behind this class is all the ways different from that.

**Comment by Kerndog73** [comment]
Oh, of course lambdas can’t be used as template parameters! Every lambda expression has a different type. Silly me! I should have compiled that.

**Comment by skypjack** [comment]
I'm closing the issue because it's invalid, something we cannot implement withing `SigH`, I'm sorry.  
Feel free to continue the discussion here if you have any proposal or suggestion. Thank you.

**Comment by Snektron** [comment]
I understand signals aren't in charge of the lifetime of the listener, however i don't think writing
```cpp
bool thing_happened = false;
auto listener = [&thing_happened]{
  thing_happened = true;
};
sink.connect<&decltype(listener)::operator()>(&listener);
```
is quite nice. A possible alternative would be to add an overload of `connect` that automatically deduces operator() of its parameter:
```cpp
template <typename Listener>
connection connect(Listener* listener) {
  connect<&Listener::operator()>(listener);
}```

This allows rewriting the first snippet as
```cpp
bool thing_happened = false;
auto listener = [&thing_happened]{
  thing_happened = true;
};
sink.connect(&listener);
```
which seems a lot nicer in my opinion.

**Comment by Kerndog73** [comment]
@Snektron I was thinking about this just the other day!

**Comment by skypjack** [comment]
@Snektron @Kerndog73 a lambda created on the stack and attached this way would result in a dangling pointer and therefore a crash.

**Comment by Snektron** [comment]
Wouldn't the same thing happen with a listener created on the stack?

**Comment by skypjack** [comment]
@Snektron indeed, of course. @Kerndog73 correctly commented the decisions behind `sigh` a while ago:

>The signal stuff is made to be fast. It’s designed to avoid allocations. If you want a lambda with state, you have to store the state somewhere. std::function will allocate space for that state but entt::Delegate will not. Supporting this feature would introduce allocations everywhere.

The fact is that the `delegate` class (and therefore `sigh`, that you can see as a multi-`delegate` class in a sense), doesn't allocate nor it has space to store aside lambdas or instances of any type. It gets the job done with just a couple of pointers and that's all. On the other side, fully supporting lambdas would require to design something similar to an `std::function` that **does** allocate instead in some cases and for obvious reasons. However, if what I need is an `std::function`, I can use it directly, it doesn't make much sense to design a drop-in replacement with no benefits at all and with the exact same API.
