### ISSUE TITLE
Registry::accommodate doesn't trigger events (it was: prototype creation ignores listeners)

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#133]
Not sure if this is intended behavior?
in the case of `registry.construction<Position>().connect<&MyFreeFunction>()`,
MyFreeFunction isn't called when a component is assigned via `prototype.create()`.

**Comment by Kerndog73** [comment]
I think that’s a bug. Registry::assign publishes to the construction sink but Registry::accomodate doesn’t. This is because accomodate doesn’t call assign. Also, the assign function that is created in Prototype::set uses accomodate when assign would suffice.

**Comment by Kerndog73** [comment]
Accomodate, assign and replace really should be closer together because scrolling between then all is super annoying on a phone!

**Comment by skypjack** [comment]
Good catch.  
This is a bug of `accommodate` that affects also the persistent views under certain circumstances.  
Thank you very much for pointing it out. Is it a problem if I change the title of the issue to match the actual bug?

**Comment by Kerndog73** [comment]
@skypjack Have you considered using `Registry::assign` [here](https://github.com/skypjack/entt/blob/13250887fa5ade9554b98bf11db9da5a6e0c9914/src/entt/entity/prototype.hpp#L143)?

**Comment by skypjack** [comment]
@Kerndog73 Yeah, you're right, using `assign` there would speed up the prototype and solve the issue for it. However, it won't resolve the underlying bug, that is the one that affects also other parts of the library.  
As an example, consider a persistent view for components `A` and `B`. You `assign` `A` to the entity `e0`, than you `accommodate` `B` for the same entity. The persistent view won't be notified and thus it won't track the entity. This is definitely a bug, a severe one actually.

**Comment by huwpascoe** [comment]
> Is it a problem if I change the title of the issue to match the actual bug?
Go for it! I figured the issue would be deeper than prototype

**Comment by skypjack** [comment]
Yeah, it's far deeper. Really a good catch. Thank you.  
I'm out of home for a few days. I'll push a fix upstream probably during the weekend and then I plan to cut a new minor release.

Please, leave open the issue so as to track changes.
