### ISSUE TITLE
Registering base class data members in Meta

### ISSUE THREAD

**Issue by morbo84** [skypjack/entt#137]
Currently, I'm not able to _register_ to the reflection system a public base class `B` member when registering a class `D` derived from `B`. In code:

    struct B { int i; };
    struct D : B {};

    entt::Meta::reflect<D>("D").data<int, &D::i>("i");

The problem here is that the member variable `i` belongs to the base class `B`, not to `D` directly.

How can I correctly reflect my class `D` and its inherited member `i`?

**Comment by skypjack** [comment]
Good point. Thank you. Tagged v3, it will be part of the next major release along with meta.

**Comment by skypjack** [comment]
Works as expected with the current implementation. See branch `meta`. Your snippet compiles and runs fine now.  
Feel free to reopen the issue if you find any other error. Thank you!!
