### ISSUE TITLE
using ->Set on a prototype causes program to crash.

### ISSUE THREAD

**Issue by SublimeCreations** [skypjack/entt#139]
When I call ->Set on a prototype I get an assertion failed crash for the reason "Vector sub script is out of range.

**Comment by Kerndog73** [comment]
Do you have a minimal, complete and verifiable example to reproduce the problem?

**Comment by skypjack** [comment]
Yeah, I agree with @Kerndog73 - we cannot figure out what's the error without a snippet to reproduce it. Prototypes are tested and therefore we must assume they work properly and the error is client side, until you can prove the opposite. I'm sorry.

I'll leave the issue open for a couple of days, so as to give you the time to integrate it.

**Comment by SublimeCreations** [comment]
Alright sorry for not leaving some code with the post, I was hoping that this was a well known gotcha i was running into. Alright so to give some background of what this code is doing. I have created a code generator that generates an amx script that is loaded at run time to create entity prototypes. 


First I have a cpp console application. Inside of that I call this

```
std::unique_ptr<entt::DefaultRegistry> registry = std::make_unique<entt::DefaultRegistry>();
EntityManager::Init(registry.get());

```

The entity manager class is inside of a static link library that I have created. 

```
#define MAX_COMPONENTS 4
static std::map<unsigned short, entt::DefaultPrototype*> protoTypes;
static entt::DefaultRegistry* registry;
static void(*p[MAX_COMPONENTS]) (unsigned short x);

static __forceinline void Init(entt::DefaultRegistry* _registry)
{
	registry = _registry;
		
	p[0] = AddNetActorToPrototype;
	p[1] = AddFacingAngleToPrototype;
	p[2] = AddPosition2DToPrototype;
	p[3] = AddPosition3DToPrototype;
	
}
```

The below code is called from the amx scripts.
```
//native CreateEntityPrototype(protoID);
	static __forceinline cell AMX_NATIVE_CALL n_create_entity_prototype(AMX *amx, const cell *params)
	{
		unsigned short idx = (unsigned short)params[1];
		std::unique_ptr<entt::DefaultPrototype>  pd = std::make_unique<entt::DefaultPrototype>(*registry);		
		protoTypes[idx] = std::move(pd.get());
		return 1;
	}
	

	
	//native AddComponentToProtoType(protoid,componentid);
	static __forceinline cell AMX_NATIVE_CALL n_add_component_to_protoType(AMX *amx, const cell *params)
	{
		
		auto componentID = (int)params[2];
		if ((componentID >= 0) && (componentID <= MAX_COMPONENTS))
		{
			(*p[componentID])(((unsigned short)params[1]));
		}
		return 1;
	}
```

Then when I get to this point is when the crash happens. 

```
	static __forceinline void AddPosition3DToPrototype(unsigned short protoID)
	{
		std::cout << protoID << std::endl;
		protoTypes[protoID]->set<Position3D>(0.0f,0.0f,0.0);
	}

```
Everything is working just fine until 

```
protoTypes[protoID]->set<Position3D>(0.0f,0.0f,0.0f);
``` 
is called.

Here are some screeshots of the error I get when the above code is found followed by a screenshot of where the callstack is taking me after the crash and the autos tab showing that some of the stuff is throwing "unable to read memory"

https://imgur.com/a/Ub9oFy4

**Comment by skypjack** [comment]
Unfortunately your code doesn't help to reproduce the error (at least my side).

Let's check the facts:

* `protoTypes` is a map
* The prototype uses a map internally
* The error is about an out of range on a vector

So, what happens at that line that could involve a vector?  
The constructor of `Position3D` is invoked.  
Can you paste the definition of that class?

**Comment by SublimeCreations** [comment]
Yeah sure here it is

```
struct Position3D
{
	float x;
	float y;
	float z;

	Position3D(float _x, float _y, float _z) : x(_x), y(_y), z(_z)
	{
		x = _x;
		y = _y;
		z = _z;
	}
};
```

**Comment by SublimeCreations** [comment]
I am not sure if this helps but I am using vs 2017(v141), and i am using ISO c++17 Standard

**Comment by skypjack** [comment]
Can you reproduce the error with a snippet? I cannot look into it this way and it's about a vector that doesn't exist. You know...

**Comment by OvermindDL1** [comment]
Providing a [SSCCE](http://sscce.org/) repo of the problem is always best!

**Comment by SublimeCreations** [comment]
I attempted to create a single snippet that replicates the error but was unsucessful. The below code works fine. 

I might just try to figure out another approach to what I am doing and try again unfortunately. 

```

struct Position3D
{
	float x;
	float y;
	float z;

	Position3D(float _x, float _y, float _z) : x(_x), y(_y), z(_z)
	{
		x = _x;
		y = _y;
		z = _z;
	}
};


#define MAX_COMPONENTS 1
static std::map<unsigned short, entt::DefaultPrototype*> protoTypes;
static entt::DefaultRegistry* registry;
static void(*p[MAX_COMPONENTS]) (unsigned short x);

void AddPosition3DToPrototype(unsigned short prototype)
{
	protoTypes[prototype]->set<Position3D>(0.0f, 0.0f, 0.0f);
}

int main()
{
	registry = new entt::DefaultRegistry();
	p[0] = AddPosition3DToPrototype;
	std::unique_ptr<entt::DefaultPrototype>  pd = std::make_unique<entt::DefaultPrototype>(*registry);
	protoTypes[0] = std::move(pd.get());


	auto componentID = 0;
	if ((componentID >= 0) && (componentID <= MAX_COMPONENTS))
	{
		(*p[componentID])(0);
	}
	while (true)
	{
		
	}

}
```

**Comment by SublimeCreations** [comment]
does this screenshot help? 
https://i.imgur.com/9KaS4wn.jpg

**Comment by SublimeCreations** [comment]
Have you taken a look at the screenshots i have posted? here?
https://i.imgur.com/9KaS4wn.jpg

The call stack shows that it is an entt vector that is causing the assertion.
https://i.imgur.com/61gO49k.jpg

See the highlight portion of the screenshot. It points to entt:Handlers in the debugger. and entt::handlers has a lot of unable to read memory values in it.

**Comment by SublimeCreations** [comment]
https://i.imgur.com/bKSE3kG.jpg

**Comment by skypjack** [comment]
`handlers` is a map:
```
std::unordered_map<component_type, component_handler> handlers;
```
I don't care if the underlying implementation uses vectors, I cannot control it.  
Just another question: are you using shared libraries in the example that crashes?

**Comment by SublimeCreations** [comment]
If by shared libraries you mean am I loading any dlls via loadlibrary then yes(I am on windows btw). however this error persists even if I disable them from being loaded.

```
	static void AddPosition3DToPrototype(unsigned short protoID)
	{
		std::cout << protoID << std::endl;
		protoTypes[protoID]->set<Position3D>(0.0f,0.0f,0.0f);
	}
```

When i call the above code 0 is printed to the console. Then when the ->set function is called the program crashes, putting this in the call stack as soon as it does. 

https://i.imgur.com/GXteEVu.jpg

I am not sure why there are so many values within the map is that normal? And I am also not sure why ->set is  accessing it at such a high index. I do not think this is anything within my code, I am not accessing the handlers map at all.

**Comment by OvermindDL1** [comment]
Sooo, about that [SSCCE](http://sscce.org/) repo of the issue?  :-)

**Comment by Kerndog73** [comment]
n_create_entity_prototype Stores a pointer to deallocated memory in protoTypes

**Comment by SublimeCreations** [comment]
> n_create_entity_prototype Stores a pointer to deallocated memory in protoTypes

Interestingy

**Comment by SublimeCreations** [comment]
> 
> 
> n_create_entity_prototype Stores a pointer to deallocated memory in protoTypes

Yeah you're correct, not sure how I missed that one or why the debugger was complaining about handlers. But thanks!

**Comment by Kerndog73** [comment]
Why are you storing pointers in protoTypes? Why not just store the objects?

**Comment by SublimeCreations** [comment]
Because when I tried doing it like this it was giving me "'entt::Prototype<unsigned int>::Prototype': no appropriate default constructor". That was just my attempt of fixing the error. I was getting.

```
	static std::map<unsigned short, entt::DefaultPrototype> protoTypes;
	//native CreateEntityPrototype(protoID);
	static __forceinline cell AMX_NATIVE_CALL n_create_entity_prototype(AMX *amx, const cell *params)
	{
		unsigned short idx = (unsigned short)params[1];
		entt::DefaultPrototype prototype{ *registry };
		protoTypes[idx] = std::move(prototype);
		return 1;
	}
```

**Comment by Kerndog73** [comment]
You’re default constructing a new object and then move assigning to it. Do this instead. 

protoTypes.emplace(idx, *registry)

**Comment by Kerndog73** [comment]
I’m sure you have good reasons for using global variables!

**Comment by SublimeCreations** [comment]
> 
> 
> I’m sure you have good reasons for using global variables!
n_create_entity_prototype is a function used within a scripting language that requires all functions to be marked as static. So in order to access those variables they also need to be static, but they're not being used outside of the entitymanager class.

**Comment by Kerndog73** [comment]
This compiles on my machine and I can't think of any reason why it shouldn't

```
#include <map>
#include <entt/entt.hpp>
void test() {
  std::map<unsigned short, entt::DefaultPrototype> map;
  unsigned short idx = 5;
  entt::DefaultRegistry regObj;
  entt::DefaultRegistry *regPtr = &regObj;
  // totally fine
  map.emplace(idx, *regPtr);
}
```

**Comment by SublimeCreations** [comment]
I am not sure off hand what I am using i recently reformatted my machine. My guess is whatever comes with the vs versoin 141 toolset. I will take a look when I am back at that computer.

Is anything bad going to happen with my fix? I simply added an empty default constructor to the prototype class.

**Comment by Kerndog73** [comment]
The only valid operations that can be performed on a default constructed prototype are assignment and destruction. Any other operations will result in crashes. A default constructed prototype is dangerous

**Comment by Kerndog73** [comment]
This works on GCC 5.1 and even GCC 4.8.1

```C++
map.emplace(idx, entt::DefaultPrototype{*regPtr});
```

No need to add a default constructor to `entt::DefaultPrototype`.
