### ISSUE TITLE
listeners in EnTT 2.5.0

### ISSUE THREAD

**Issue by dbacchet** [skypjack/entt#140]
Hi, this is not an issue but just a question.

I'm still using a decently old (considering the frequency at which you add new features) of EnTT; can you point me to a snippet of code that shows how to associate listeners/callbacks on component creation/destruction?
Is it possible at all in version 2.5.0? 
There are listeners in `registry.hpp`, but was not able to find references to them in the documentation or in the unit tests.

thanks!

**Comment by skypjack** [comment]
Hi @dbacchet !!

>Is it possible at all in version 2.5.0?

Unfortunately no, support for listeners has been introduced with version 2.6.0, I'm sorry.

>can you point me to a snippet of code that shows how to associate listeners/callbacks on component creation/destruction?

Do you still need this? I can provide you with an example if you decide to move to v2.6.0, it's not a problem.

**Comment by dbacchet** [comment]
I will try to move to 2.6 or the most recent then. A snippet would be very appreciated!
thanks!

**Comment by skypjack** [comment]
Sure, not a problem. Just let me know if you move to version 2.6/2.7.3 or to the `v3` branch, because API are different.

**Comment by dbacchet** [comment]
I’ll try with the latest stable 2.7.x to minimize changes for now.
Would you recommend to give v3 a try?

**Comment by skypjack** [comment]
`v3` is a porting of `v2.7.3` to C++17, it's stable enough and going to be the next major release. On the other side, you got it: moving to `v3` won't minimize the changes! :-)  
I'll merge on `v3` also the reflection system, probably by the end of the month. Then I'll create a `v3.0.0` if everything is ok. You can plan to move the next month if you prefer a smooth change.

**Comment by skypjack** [comment]
Btw have you already seen [this](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#observe-changes)? It's part of the crash course on the ecs stuff and it contains some details signals and listeners.

**Comment by dbacchet** [comment]
looks great thanks!

**Comment by skypjack** [comment]
You're welcome! :-)
If you need something else, let me know. Otherwise feel free to close the issue.

**Comment by dbacchet** [comment]
bumped to 2.7.3 and it works like a charm.

is there a way to have the same notifications also when an _entity_ is created/destroyed?

**Comment by skypjack** [comment]
I'm glad to know v2.7.3 works fine!!

>is there a way to have the same notifications also when an entity is created/destroyed?

Unfortunately no. I think I'll add it in future, because I see sometimes it can be useful.

**Comment by dbacchet** [comment]
ok, thanks. 
For the entity handlers, no pressure, it's easy enough to add that functionality on top of EnTT on my side.
Closing the issue.
