### ISSUE TITLE
Patreon

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#141]
Hi all,

I created this issue to make you know that **I opened a patreon account** to support this and other projects of mine.  
Long term plans for `EnTT` are known, but it would be great if I could also speed up the development, support  a C++14 version and port all the new features, create something new out of `EnTT` and put it in the public domain as well, and so on.

However, **I need your help** to do that.  
**I'm doing all of this in my free time** at the moment and it's hard to go straight to the goal in a short time sometimes.  
If you find you're interested in supporting me and the project you love, [here](https://www.patreon.com/bePatron?c=1772573) is a way to do that.

**Thank you** all in any case for the support shown so far.

**Comment by AquariusPower** [comment]
May be this is just my opinion but, if I were you, I would keep at least this issue opened forever!
Closed issues wont call the attention this one deserves, because this is something broader than any project itself, as this one means how well one can live in this non utopic world :)
