### ISSUE TITLE
EnTT-Pacman

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#142]
EnTT-Pacman is an example of how to make a game (in this case: Pacman) with EnTT. Reading the source might help beginners in understanding how to apply the ECS architecture to a game. I think this deserves a mention in the README of EnTT.

**Link:** https://github.com/Kerndog73/EnTT-Pacman
**Description:** An example of how to make Pacman with EnTT. Read the source and learn!

That last part “Read the source and learn!” might be a bit much. I’ll let you decide whether or not that part is included. 😉

**Comment by Kerndog73** [comment]
I believe that I have done that with Pacman. Changing the rendering backend would involve rewriting sys/render.cpp and modifying core/app.cpp to initialize the new rendering backend. Apart from that, the parameter types of a few functions will need to be tweaked but that's about it.

The code that does pathfinding has no idea how the entities are being rendered. I find that the ECS architecture makes separation of concerns really easy.

**Comment by AquariusPower** [comment]
could be
sys/render3D.cpp
sys/render2D.cpp
sys/renderTM.cpp
configurable thru core/app.cpp :)

so, such functions would be overridden and only available to 3D, 2D or TM,
I mean, the moment I start coding to 3D (as I will begin tests in TM), the idea, if possible, is to have not to change anything else other than create the code to let it render in 3D :)

but that all is a personal preference xD

**Comment by skypjack** [comment]
That's good!! I'm merging `meta` on `v3` during these days and then I'm porting everything on `master`.  
I'd add it directly after these changes if it's fine for you, even though this isn't using C++17.

**Comment by skypjack** [comment]
Ok, added to the [README](https://github.com/skypjack/entt/blob/v3/README.md) file of branch `v3`.  
I'm closing the issue right now and hopefully merging `v3` on `master` during the week. I've been a bit busy last week.
