### ISSUE TITLE
Do you plan to add physics and collisions?

### ISSUE THREAD

**Issue by MrKOTOKU** [skypjack/entt#144]
Hello
Do you plan to add physics and collisions?

In addition, we are looking for programmers in an indie game development project.
If "ECS" is your only project at the moment, then we could discuss the details of our project and the possibility of joining the project.
Thank's

**Comment by skypjack** [comment]
Hello,

Physics and collisions aren't really something that should belong to this project. Instead, they should be part of an engine based on `EnTT`, which isn't yet an open source project. I'm sorry.

---

As for your project, I think it's something we can definitely discuss via email. You find it in [my profile](https://github.com/skypjack), if interested.
