### ISSUE TITLE
recursive error

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#145]
This library is what's first introducing me to c++17. I had to install gcc-8 g++-8 and set CMAKE_CXX_COMPILER to gcc-8 in the cmakeList, but otherwise I don't think that should have been an issue...

```
[  3%] Built target gtest
[  7%] Built target gmock
[ 10%] Built target gmock_main
[ 14%] Built target gtest_main
[ 16%] Built target odr
[ 20%] Built target dispatcher
[ 23%] Built target delegate
[ 25%] Building CXX object test/CMakeFiles/scheduler.dir/entt/process/scheduler.cpp.o
In file included from /home/pgruenbacher/Code/cpp/ecs/entt/test/entt/process/scheduler.cpp:3:
/home/pgruenbacher/Code/cpp/ecs/entt/src/entt/process/scheduler.hpp: In instantiation of ‘entt::scheduler<Delta>::continuation entt::scheduler<Delta>::continuation::then(Args&& ...) [with Proc = succeeded_process; Args = {}; Delta = int]’:
/home/pgruenbacher/Code/cpp/ecs/entt/test/entt/process/scheduler.cpp:78:38:   required from here
/home/pgruenbacher/Code/cpp/ecs/entt/src/entt/process/scheduler.hpp:65:21: error: cannot convert ‘entt::scheduler<int>::continuation’ to ‘entt::scheduler<int>::process_handler*’ in assignment
             handler = scheduler::then<Proc>(handler, std::forward<Args>(args)...);

```
And then I get inititely recursive error.

![screenshot from 2018-10-27 16-46-39](https://user-images.githubusercontent.com/3332598/47609186-ee279d80-da07-11e8-8ce4-ddc97ed7d778.png)

**Comment by pgruenbacher** [comment]
and I am able to compile the library if I comment out handler = scheduler::then<Proc> line, and I think all tests will still pass except for the ./test/scheduler.

**Comment by skypjack** [comment]
:thinking: 
Travis uses GCC8 as well as me on my laptop and I've never had this problem actually.
Moreover, that class is almost the same in the C++14 version. It's odd indeed.
What's the exact version of the compiler? I mean, 8.x.y

**Comment by pgruenbacher** [comment]
this isn't a compiler issue that I can tell. I'm pretty sure you're supposed to be doing 
`handler = scheduler::then<Proc>(handler, std::forward<Args>(args)...).handler` in scheduler.hpp
this fixes the error, but now I just get the compiler building in some sort of infinite recursion...

g++-8 (Ubuntu 8.1.0-5ubuntu1~16.04) 8.1.0

**Comment by skypjack** [comment]
I think I didn't get you. You end up in an infinite recursion if you modify the code? What's the error if you try to compile it the way it's written?

**Comment by pgruenbacher** [comment]
I'm on the master branch. I get the original error above when compiling original code. it throws an error about scheduler::then<Proc> returning continuation instead of handler. 

I think the recursion has to do with the way the then function is structured. 

I'm going to test with g++-7

**Comment by skypjack** [comment]
It seems it gets confused by this line:
```
handler = scheduler::then<Proc>(handler, std::forward<Args>(args)...);
```
`scheduler::then` returns a `process_handler *` while `process_handler::then` returns a `continuation`. Not sure why your version of GCC calls `then` from the `continuation`.

**Comment by pgruenbacher** [comment]
lol g++-7 works for me just fine. It must have been doing an infinite continuation::then recursion with the newer compiler?

**Comment by skypjack** [comment]
nope, I'm compiling it with g++8 and travis does the same.  
If you can make a test, try to replace the first `then` function in the `continuation` class with this:
```
        template<typename Proc, typename... Args>
        continuation then(Args &&... args) {
            static_assert(std::is_base_of_v<process<Proc, Delta>, Proc>);

            if(handler) {
                auto proc = typename process_handler::instance_type{new Proc{std::forward<Args>(args)...}, &scheduler::deleter<Proc>};
                handler->next.reset(new process_handler{std::move(proc), &scheduler::update<Proc>, &scheduler::abort<Proc>, nullptr});
                handler = handler->next.get();
            }

            return *this;
        }
```
Then delete the static `then` member function in the outer class. It should work and it's probably something I should push anyway, because it doesn't make sense for that function to belong to the outer class.

**Comment by pgruenbacher** [comment]
![ezgif-6-c57423bfbe6e](https://user-images.githubusercontent.com/3332598/47609402-a99e0100-da0b-11e8-8149-2a78d18300ad.gif)

sure. I already made this gif so I'll show anyways.

**Comment by pgruenbacher** [comment]
your advice did the trick. it's compiling with g++-7 now.

**Comment by skypjack** [comment]
I was wrong about Travis anyway, it uses gcc7. If you can make the test, because I cannot reproduce the error on my laptop. I'm sorry.

**Comment by skypjack** [comment]
> your advice did the trick. it's compiling with g++-7 now.

Good, Does it compile also with g++8?

**Comment by pgruenbacher** [comment]
see edit yes.

**Comment by pgruenbacher** [comment]
and ./test/process works now too.
