### ISSUE TITLE
Call for comments: sort or performance

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#147]
I realized that there is probably room for further **optimizations in the multi components views**. However, if confirmed, it would require to **sacrifice all kind of sort functionalities**.

I'm not that sure it's worth it to be honest, therefore I'm creating this issue to know if **the possibility to sort pools is a must have feature** for the users of this library.  
I'm at the point in which a few cycles are maybe a good price to pay for more functionalities, but I'd like to know also what's your point of view.

Let's discuss it. I'll close the issue in a few days as usual.

**Comment by m-waka** [comment]
I'm sorting my entities which have a Renderable component by Position and Layer in a 2D isometric project in order to get the correct graphical overlapping of them right. It was the easiest way to achieve this. Perhaps there are alternatives?

Only slightly related: I am not quite sure yet how I can integrate EnTT with quadtree based algorithms which also imply some kind of sorting.

**Comment by ArnCarveris** [comment]
@skypjack What sacrifice?

**Comment by skypjack** [comment]
@m-waka 

>Perhaps there are alternatives?

Actually I'm doing the same in a couple of software of mine. The other way around is to keep a separated data structure you feel with entities and on which you infer an order.

>quadtree based algorithms which also imply some kind of sorting.

See above. There is nothing wrong in maintaining separated data structures aside the ECS to do what doesn't fit well with an ECS, after all.

@ArnCarveris 

All sort functionalities would be removed (see the registry class template).

**Comment by ArnCarveris** [comment]
@skypjack Uhh, I liked that :cry:

**Comment by skypjack** [comment]
Yeah, indeed it's a feature that usually an ECS doesn't offer and probably it's worth it to sacrifice a bit of performance for that in a library that is already amazingly fast. I'm from the party "features for performance" to some extents.

**Comment by danielytics** [comment]
Will removing the sort functionality mean that EnTT won't be able to keep components ordered with respect to each other for cache friendly iteration?

**Comment by skypjack** [comment]
@danielytics 

Well, yes, in a sense it's so, on the other side there is the optimization on multi component views that is in that direction. Therefore they should compensate somehow.  
However, as an example, the optimization will also prevent to use different memory pools for different types of components, that is something that could be useful.

I'm not sure it's worth it. It looks like I'm going to sacrifice flexibility for a few cycles.

**Comment by danielytics** [comment]
Based on what you said, it doesn't sound worth it. At least, paying a few cycles to allow for more flexibility seems like a worthy trade. EnTT is plenty fast anyway and while I would welcome even more performance, EnTT is not the bottleneck for me.

**Comment by vblanco20-1** [comment]
@skypjack  what is your planning for that new architecture? im doing some experiments to see if a unity-style block ECS could reach high speeds on my own. On the sorting part, i dont think sort is worth it, there are some places you could use it, but they are mostly for multithreading execution purposes, wich i think would be a more important feature (also, the sort you had wasnt a parallel sort wich is a lost opportunity)

**Comment by skypjack** [comment]
@vblanco20-1 yeah, it's not that easy to turn sorting functionality in a parallel sort actually, because of how a sparse set works. Probably one can achieve it, but I'm not sure it's worth it. Moreover, the underlying algorithm should be replaced for sure, mainly because now it's optimized for single thread execution and hardly we can make it parallel.

>im doing some experiments to see if a unity-style block ECS could reach high speeds on my own.

And the results are? I'm curious, feel free to involve me if you want. You know, these things are of interest for me.

>multithreading execution purposes, wich i think would be a more important feature

Well, iterators are all at least forward iterators, so `EnTT` can easily be used with parallel stuff. But you know it, we were discussing this point together if I remember right.  
Can I ask you what do you expect from `EnTT` along this line? Apart a job system I'm already working on in the free time, there is nothing in the TODO list on this point. Suggestions are welcome.

>im doing some experiments to see if a unity-style block ECS could reach high speeds on my own

Tbh I don't like much the approach based on archetypes and one can already simulate it to some extents with `EnTT` working on the barrier. At the moment I'm experimenting to see if I find a good way to speed up a bit multi component views. It would be great if I find something that doesn't affect other features, but it seems it's not possible.

Do you have any suggestion on this side? I'd be glad to listen to you, if you want to contribute.

**Comment by vblanco20-1** [comment]
@skypjack  my experimental thing is way too early to really have good data, but the performance of iteration on multi-component views is quite good on its unoptimized state. At the moment is slower than entt.

What i would expect is basically a bit better multithreading support. An ECS should have "parallel-for" as a first class feature (i think). With EnTT i ran into some scalability issues with the parallel fors, as there were copious amounts of false sharing (few cpus writing to the same cache line) wich slow up scaling a bit.

Ill keep experimenting with my archetype-block based approach and try to gather real data on how the different methods stick against each other, using my spaceship battle thingy as a benchmark.

**Comment by skypjack** [comment]
@vblanco20-1 

It would be great if you keep me informed and be back with the results. `EnTT` would benefit from them and we could try to work their way into the library instead of writing a new one. My two cents.

>With EnTT i ran into some scalability issues with the parallel fors, as there were copious amounts of false sharing (few cpus writing to the same cache line) wich slow up scaling a bit.

Just out of curiosity, do you have any idea about what could be the cause? It would help trying to figure out how to solve it. Thanks.

**Comment by vblanco20-1** [comment]
@skypjack  i dont know enough of the internals to know what exactly can cause it.

**Comment by skypjack** [comment]
@vblanco20-1 it makes sense. I'll keep watching your work and wait for your feedback and results to try to improve even more `EnTT`. Your help would be really appreciated, it seems to me you're way more skilled than me on this topic. :+1:

**Comment by skypjack** [comment]
@vblanco20-1 

>i dont know enough of the internals to know what exactly can cause it.

Ok, I thought at it and probably we can spot the root cause easily with a few questions:

* Are you experiencing same effect when iterating single components?

* More important, were you iterating multiple components with different orders in their pools?

If the answer to the second question is yes, well... this is the right issue in which to discuss this and proposed changes are in order to improve exactly that aspect.

**Comment by skypjack** [comment]
Time to close this issue. I think I'll end removing persistent views and introducing a slightly finer system to get even better performance on _hot groups_.  
Stay tuned. I'm working on this in the free time, but I'm still trying to figure out what's the best approach so as not to ruin performance on other features, with the goal of keeping intact all the already existing features. :+1:

**Comment by danielytics** [comment]
@skypjack will removing persistent views mean that there are no more views with  random access iterators? I was relying on that for use with TBB as it’s parallel_for doesn’t work on just forwaard iterators.

**Comment by danielytics** [comment]
I may replace my use of TBB with c++17 parallel for and cpp-taskflow for tasks, in which case, I don’t need random access iterators anymore. But maybe others also rely on it?
