### ISSUE TITLE
thread locking

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#148]
Without having fully researched this, I'm trying to plan ahead for how I implement some validation for how I organize my multi-threading. From an api standpoint, there's a couple ways...

```
{
auto lock = reg.lockWrite<ComponentA, ComponentB>();
viewPerformWriteOnComponents(reg);
// lock unlocks when exiting scope.
}

{
auto lock = reg.lockRead<ComponentB, ComponentC>();
viewPerformReadOperationOnComponents(reg);
// lock unlocks when exiting scope.
}
```

Where I'd imagine I can configure the lock class to throw an error when trying to read / write to a component. It'd have to iterate the lock count too so that I can three different views doing a read operation on the components and it being smart enough to wait till the last view is finished.

It's mainly intended so that I can visualize and debug the components I'm modifying / reading when I'm running different views on parallel threads.

I'm not sure how we'd also be able to change out the mutex / lock guard mechanisms...

Maybe it can tie into the process api?

**Comment by pgruenbacher** [comment]
and the main reason I'd imagine I'd want this implemented in the library is cause of the template magic with the Component Types.

maybe I supply the registry class with my custom Lock class that fits the api, and the registry automatically instantiates and calls that lock class for each component.
```

template<typename Component>
class LockInterface {
   counter lockRead();
   counter lockWrite();
}
```

but the library would do the automatic work of making this lock instance for each component pool type and calling the interface calls.

**Comment by Kerndog73** [comment]
I'm not a threading expert. I only learnt what a mutex was a few days ago. So maybe what I'm about to say is irrelevant!

Having multiple threads potentially reading and writing the same components sounds like a bad idea. I'm not even sure how that would work because the order of systems matters. You have to run system A before system B. If you have a bunch of threads all touching the same components it's gonna be a mess. You could end up with some systems sometimes running in the wrong order.

I think what you're trying to do should exist entirely outside of EnTT. 
 * You could use latches and barriers to run some systems in parallel and only run the next system when all parallel systems finish. 
 * You could use parallel for_each to run a system on multiple threads. [Others have done that quite successfully](http://victor.madtriangles.com/code%20experiment/2018/06/11/post-ecs-battle-huge.html).

**Comment by pgruenbacher** [comment]
yea what you describe is my intention. My intention isn't to do simultaneous read/write with lock guarding.

what I want to be able to do is something like this.
```
// parallel views section 1
thread A: viewABupdatder.updating<ComponentA, ComponentB> // A and B component pools locked for writing
threadB: viewCDupdater.updating<ComponentC, ComponentD> // C and D component pools locked for writing

// wait for section 1 threads to finish
// start section 2 threads (simultaneous reads on pool of components ok).
threadA: viewA.reading<ComponentA>
threadB: viewA.reading<ComponentA, ComponentD>
threadC: viewA.reading<ComponentA, Component C>
```

The thing is I just want to be able to do declare how I'm updating the components at a top-level. If i've got 50 different view functions operating on a registry, I'd like there to be something to help me catch when I"m trying to have a view write to A pool, while a different view is mistakenly reading from A pool at the same time. I don't intend to use this for synchronizing threads, but rather a way to throw early exceptions when a view is doing something unintented.

**Comment by Kerndog73** [comment]
I think you're looking a library like [Intel TBB](https://github.com/01org/tbb/blob/tbb_2019/README.md). There are other libraries like this. Basically, you declare a graph of tasks that you want executed and the library makes sure they all run in the right order and use threads where possible.

**Comment by pgruenbacher** [comment]
you're right, I just didn't realize thtat std::map where the key is a typename is actually feasible....

**Comment by Kerndog73** [comment]
It is feasible because that's how the guts of the registry work!

**Comment by pgruenbacher** [comment]
ah, i think the trick is to use the family::family_type as the key... and then just use component_family::type<Component>.

and then i just std::map<family::family_type, LockClass> to internally track.

even if what I described is wrong, I still get the gist of it. Each component pool should have a std::size_t identifier I can use...

thanks @Kerndog73

**Comment by Kerndog73** [comment]
@skypjack I'm glad to help! What does getting on board with the project entail? Shall we discuss this on gitter?

**Comment by skypjack** [comment]
Well, nothing in particular to be honest, but you're one of the most active users here and often you help me with Q/A on this project. Therefore I was guessing if you wanted to be involved somehow. That's all. :wink:

**Comment by pgruenbacher** [comment]
Here's an example wrapper I think...

```
template<typename... WriteComponent>
class LockWrite {
public:
    LockWrite() {
        std::cout << "LockWrite" << std::endl;
    }
    ~LockWrite() {
        std::cout << "ReleaseWrite" << std::endl;
    }
};

template<typename... WriteComponent>
class LockRead {
public:
    LockRead() {
        std::cout << "LockRead" << std::endl;
    }
    ~LockRead() {
        std::cout << "ReleaseRead" << std::endl;
    }
};


template<typename... ReadComponent>
class Read {
    template <typename... WriteComponent>
    class Write {
        LockWrite<WriteComponent...> _lockWrite;
        LockRead<ReadComponent...> _lockRead;
    public:
        Write(Registry& reg) :
        read(reg.view<ReadComponent...>()),
        write(reg.view<WriteComponent...>()) {

        }
        typedef entt::view<EntityType, ReadComponent...> ViewType;
        typedef entt::view<EntityType, WriteComponent...> WriteViewType;
        ViewType read;
        WriteViewType write;
    };
};

typedef Read<Player, Health>::Write<NearAgents, NearEnemies, NearFriends> AgentProximityQueryView;


AgentProximityQueryView agent_proximity_query_view(registry);
for (EntityType ent : ents) {
        const health = agent_proximity_query_view.read.get<Health>(ent);
}

```
At the moment I haven't come up with a way to enforce the read and write on the components themselves. But it'd be kinda cool to do something like 

```
AgentProximityQueryView(registry).each([](const auto& health, const auto& player, auto nearAgents, auto nearEnemies, auto nearFriends){}),
```

**Comment by skypjack** [comment]
I think it's easy to with a bit of template machinery. I'm not in front of my laptop right now, but I can try to help later if you need. :+1:

**Comment by pgruenbacher** [comment]
so I think instead if I want to get a combined each of both read and write views, I'll instead want to do some sort of iterator combining of the read and write views with the wrapper class. I'll hold off on that till later though.

**Comment by pgruenbacher** [comment]
yea I'm stuck on it. i'll come back to later.

**Comment by pgruenbacher** [comment]
OMG. It seems my actual issue is I was doing 

struct NearEntities {
    std::vector<NearEntity> entities;
};
typedef NearEntities NearAgents;
typedef NearEntities NearEnemies;
typedef NearEntities NearFriends;

And apparently ENTT doesn't like weak type definitions. which make sense since they'll get deduced to NearEntities type.... so I had to declare a struct for each one...

@skypjack it may be worth adding a unique type validation somewhere, or make a note about using strong typedef.

**Comment by skypjack** [comment]
Oh, well, aliases don't introduce different types actually. Btw we cannot know from the template system if you're passing the actual type or an alias, so I don't see how I can detect it.  
If you have any idea in mind, I'd be glad to discuss it. :+1:

**Comment by pgruenbacher** [comment]
@Kerndog73 https://github.com/skypjack/entt/issues/148#issuecomment-435505072 the main issue I was having was that I mistook c++'s typedef  to be strong instead of weak. 

but yea it looks like your TypeInList method would exactly do the trick of checking and enforcing a const for the read components. I'll try it out tomorrow. and yes I was just iterating over a list of entity types, it was a copy paste snippet from one of my test cases. 

meta programming is so headache-inducing.

**Comment by pgruenbacher** [comment]
![image](https://user-images.githubusercontent.com/3332598/47947840-d7e37b00-defa-11e8-8c32-ba5fca839893.png)

not bad. I'll have to validate correctness still but it's much faster with omp parallel. suspiciously fast...

the main trick is to make sure Registry or view is private()


        #pragma omp parallel private(registry)
        for (auto ent : registry.view<Position>()) {
            const Position& pos = registry.get<Position>(ent);
        }

**Comment by pgruenbacher** [comment]
nvm the registry was just being default contructed which led to near empty range...

**Comment by pgruenbacher** [comment]
I do get around a 10x speedup when i do schedule()
but it requires having to use a incrementing for loop instead of iterating.

                #pragma omp for schedule(static, 250)
                for (int i = 0; i < ents.size(); ++i) {
                    EntityType entity = ents[i];
                    AgentProximityQueryView query_view(reg);
                    AgentProximityQuery query(entity, query_view);
                    tree.agentQuery(&query);
                }

**Comment by skypjack** [comment]
I'm sorry, I'm out of home and my son got a fever. I'm not actively following this discussion.

If I can help, please, drop a message on gitter with a mention, so that I can find it later.

Thanks.

**Comment by vblanco20-1** [comment]
Dont use mutexes, they are not needed at all. I have a couple experiments (like http://victor.madtriangles.com/code%20experiment/2018/06/11/post-ecs-battle-huge.html ) which have a lot of multithreading without a single mutex. (the version in the blog just uses std::for_each parallel, so it doesnt run systems at once, but i have a newer version that uses Taskflow that does execute systems in parallel.

In an  ECS like this, you do not need locking . What you need is a way to know when 2 systems are safe to be executed at once. Parallel-fors are allways safe as long as you dont create/destroy entities or components. For the system parallelism, what ive done is to use a task library to schedule my simulation and execute it in parallel. Some systems that i know are safe to execute at once i do that.

My recomendation for those libraries is either "TaskFlow" or FiberTaskingLib.

Taskflow is a task-based library. In that one you need to have an "schedule" step that creates all the tasks (one per system, with a parallel-for or 2 inside it) and then you just execute the entire thing. Works like a charm, but you have those 2 steps that can be annoying. Its still great to have the possibility of creating the entire task graph as you want.

FiberTaskingLib is weirder due to the fibers, but the general point is that you can create an "async task" from anywhere and then wait on it (or not). So if you want to execute 2 systems at once, then you launch one task per each and then wait on them to continue execution. The tasks from the systems can then launch other tasks like a parallel for or parallel execution of subsystems. Very nice stuff, but given its fiber nature there are some weird things around it, so be careful.

With any of those, you can have a hugely complex simulation without any need for a single mutex.

You can implement your own scheduler for the tasks, or do it manually.

**Comment by pgruenbacher** [comment]
@vblanco20-1 that's the thing, I haven't implemented any mutexes yet. The Lock stuff I'm talking about earlier in this thread I intend to use outside of the parallel scope, but simply as a way to try to track which systems are updating which pool of vectors in parallel. I did get a speedup with my latest code, but I'll take a look at yours. I'll need to find a compiler that supports the execution parallel policy (intel) since apparently g++-8 doesn't support `std::for_each(std::execution_par` yet. I'm building a kd-tree on the positions of all the entities and then in paralllel i'm having each entity query the kd-tree to find nearby agents / enemies / friends and update their corresponding component. I'll have to see how my old simulation code was performing worse/better on 10,000 entities.

**Comment by vblanco20-1** [comment]
@pgruenbacher  if you just want it for safety, have you though of 1 atomic per component type? when a system is writing into it, you add +1, and whenever you want to read, you check if its 0 or not and assert. Lower complexity and its lockfree compared to a mutex.

**Comment by pgruenbacher** [comment]
yea that's my intent. A lot of the previous discussion was trying to set up a view wrapper that will automatically do the atomic lock per component based on read write declarations, as well as automatically enforce that when accessing from the component pool

@vblanco20-1 do you know which compiler you used for std::for_each(std::execution_par or was it just whatever comes shipped with Unreal?

**Comment by pgruenbacher** [comment]
nvm I can do __gnu_parallel::for_each...
but yea not any change in performance, it's the same as a naive pragma omp parlallel for shared(registry)

what really perturbs me is that I can pull up my 11,000+ demo of my original simulation code and get 17 fps with a very badly optimized opengl renderer too, but I'm getting like 5 fps performance on just doing the spatial query here all by itself.

**Comment by danielytics** [comment]
Just to throw in another alternative to Taskflow and FiberTaskingLib, Intel’s TBB also supports taskflow-like tasks. Taskflow claims to be faster/more efficient, but they don’t have any benchmarks or other proof for this claim. 

It may also be worth looking how Unity’s new ECS works: it’s updated serially but work can be farmed out to the job system. I’m not familiar enough with it to know how jobs can write back to components though. 

I’m personally doing something like this: I split my systems into two: read-only and read-write. The read-only ones always run in parallel with each other and the read-write ones are serial (or, at least, their parallelism is manually set using task dependencies).
