### ISSUE TITLE
Typo in Code Example

### ISSUE THREAD

**Issue by DJuego** [skypjack/entt#15]
Thank you for your efforts, @skypjack !! 
I admit that I have not yet used your library but I am excited about its evolution.

Meanwhile I suspect there are a typo in the sample:

Where...
    auto view = ecs.view<Position, Velocity>()
Shoud be:
    auto view = **registry**.view<Position, Velocity>()

DJuego

P.S:

I'm also interested in your event bus([eventpp](https://github.com/skypjack/eventpp)) but in that field you have ["competitors"](https://github.com/gelldur/EventBus).  ;-D

**Comment by skypjack** [comment]
Good catch. I'm fixing it upstream, thank you.

---

Just my two cents: ignore both `eventpp` and the other competitors for a while.  
I've already put in `EnTT` v2 a naked signal handler (see `sigh.hpp` for more details) and the next revision (v2.1.0) will be fully focused on signalling.

A brief list of what you'll have at your disposal:
* unmanaged signal handler (based on naked pointers)
* managed signal handler (based on smart pointers with auto disconnections on destruction)
* inheritable event emitter based on CRTP idiom (similar to the one in `uvw`, have a look at it to have a grasp of the idea), no predefined list of managed events required
* opaque delegate for free functions and member functions
* a more complex dispatcher that can be used directly within your main loop with immediate and queued events, no predefined list of managed events required
* general purpose bus that requires a predefined list of managed events (you can use it as a backbone bus within your modules)
* ... AOB ...

I suspect the `signal` module of `EnTT` will satisfy all of your requests indeed. :-)
Can you wait for a few weeks? I'm documenting them and my free time isn't that much.

I'm creating the `signal` branch soon. You can follow the work there step by step.

**Comment by skypjack** [comment]
Fixed upstream.

**Comment by DJuego** [comment]
Yes, yes! I can wait a few weeks. Certainly, a solution like that would be perfect. 
It's almost too good to be true!! 

*Thanks for your dedication, @skypjack !*

DJuego

**Comment by skypjack** [comment]
@DJuego I started pushing new stuff in `experimental`. It still lacks something, but hopefully we are along the line you were looking for. Any suggestion or request for feature is welcome, as usual!! ;-)

**Comment by skypjack** [comment]
@DJuego Signalling stuff is in `experimental` as announced.
Is it enough for your requirements? Let me know if you want to see a feature in `EnTT`.

**Comment by DJuego** [comment]
Thank you for your amazing work and your genuine interest in meeting the needs of your user base, @skypjack . The best thing than can happen to a library is to have a creator as enthusiastic as you. For this reason, i choose you. :-)

Concerning your questions, my only requirements are an elegant design (simple, clear and clean), high performance and good documentation. Sadly,  i have not experience with messaging pattern. So
I can not tell you anything more concrete, until I use it in a real project. However, i promise i will test it as soon as possible. And maybe help you debug it.  ;-P

I like the way you carry the project. I only ask that you do not sacrifice the design quality to meet needs too exotic or marginal. Think deeply.

Congrats for your enTT project, @skypjack!

DJuego
