### ISSUE TITLE
Possible undefined behavior in implementation

### ISSUE THREAD

**Issue by Gaspard--** [skypjack/entt#155]
Hello,

I was just going through the library and I stumbled upon this:
https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L119
Code copied below for convenience:
```cpp
    template<typename Component>
    inline const component_pool<Component> & pool() const ENTT_NOEXCEPT {
        assert(managed<Component>());
        return static_cast<const component_pool<Component> &>(*pools[component_family::type<Component>]);
    }

    template<typename Component>
    inline component_pool<Component> & pool() ENTT_NOEXCEPT {
        return const_cast<component_pool<Component> &>(std::as_const(*this).template pool<Component>());
}
```
If I'm not mistaken, this means that the non-const pool getter retrieves a `const` value and `const_cast`s it to a mutable reference, which is undefined behaviour if the returned value us then written (according to my reading of the standard). Quoting https://en.cppreference.com/w/cpp/language/const_cast:
> const_cast makes it possible to form a reference or pointer to non-const type that is actually referring to a const object or a reference or pointer to non-volatile type that is actually referring to a volatile object. Modifying a const object through a non-const access path and referring to a volatile object through a non-volatile glvalue results in undefined behavior. 

A simple fix would be reversing the pattern. Something like:

```cpp
    template<typename Component>
    inline component_pool<Component> & pool() ENTT_NOEXCEPT {
        assert(managed<Component>());
        return static_cast<component_pool<Component> &>(*pools[component_family::type<Component>]);
    }

    template<typename Component>
    inline const component_pool<Component> & pool() const ENTT_NOEXCEPT {
&>(*pools[component_family::type<Component>]);
        return std::as_const(std::const_cast<std::remove_const_t<decltype(*this)>>(*this).template pool<Component>());
    }
```
I didn't open a pull request because this didn't fit the description in the CONTRIBUTING.md. I hope this issue doesn't violate expected etiquette.

**Comment by skypjack** [comment]
I think you misunderstood the standard. Consider this (emphasis mine):

>**Modifying a const object** through a non-const access path [...] results in undefined behavior.

You're not modifying a const object here. The object isn't const in the pool. It's const only the reference you obtain from the const overload of `get` and from which you get rid of the const.

This is quite a common pattern in fact. See [this Q/A on SO](https://stackoverflow.com/q/123758/4987285) for further details.

**Comment by Gaspard--** [comment]
Ok thanks, I've been having this misconception for a long time O.o
I always wrote that pattern the other way because of that!

**Comment by skypjack** [comment]
You're welcome. :+1:
