### ISSUE TITLE
Is there a way to filter entities with internal data from component

### ISSUE THREAD

**Issue by L3nn0x** [skypjack/entt#158]
Hello,
is there a way to filter entities based on a predicate running over one or multiple components? Just like sorting, but for a filter instead.
I'd like to use it to represent an ownership model in the ECS (inventories to be exact).
A scene or space model could also work.

Thanks!

**Comment by Kerndog73** [comment]
```C++
std::vector<uint32_t> entities;
entities.reserve(reg.size());
auto view = reg.view<A, B>();
for (uint32_t e : view) {
  if (predicate(view.get<A>(e), view.get<B>(e))) {
    entities.push_back(e);
  }
}
```

**Comment by skypjack** [comment]
I think this is just a duplicate of #150 that adds a wider concept.  
To be clear, the final goal is to allow users to add custom filters on persistent views. This should solve also your problem. Right?  
If it's so, I'll close this as a _duplicate_. We can continue the discussion on the other issue. :+1:

**Comment by L3nn0x** [comment]
@Kerndog73 that was what I was thinking about, thanks!

I was thinking about spaces because I want to put the item from the inventory in the ECS proper, but iterating over all items to see if it's in your inventory or in the inventory of a NPC seems kind of wasted computation. I think I'll store the entities in a specific component for ease of access.

In any case that solves my problem, thanks.
