### ISSUE TITLE
[Feature request] Tags: Revenge

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#169]
More than once I've been asked to **reintroduce tags** in `v3`.  
However, the previous implementation had some design flaws and problems and I don't want to restore it.

The purpose of this issue is to **discuss common uses and requirements** (ie should tags be assigned to entities or not?), then **try to find an implementation that _works_** and makes sense.

I'd like also to understand if it's something that most of the users want back or not, so **please add at least a :+1: to the issue if you want to see tags also in `v3`** but you don't want to participate to the discussion.

Thanks.

**Comment by vblanco20-1** [comment]
Personal opinions from my own experiments and projects.
A "singleton component" is something ive allways used, a lot of times. I tended to use the tag feature before, but when it got deleted i just implemented my own.
My singleton implementation just consists of reserving one entity, and you have functions that mirror get, accumulate, and set, but have no entity. This methods will just affect the singleton entity.

The usage of singleton components is very common when you want "engine-wide" globals. I have a GameTimeComponent, wich holds pause state, delta time, and other similar values, and then i use it everywhere. I also use singleton components to store System related data, like an acceleration structure. This lets me have multiple different systems that affect the same acceleration structure, or query it to do physics.

I think a possible implementation is just to go with that singleton entity, as its barely a couple lines of code, and even lets you have multiple of the same "singleton", if you create a new entity and assign that component, as the singleton entity will still appear in Views.

**Comment by pgruenbacher** [comment]
I like the idea of singletons being tied to the registry mainly because a) if I have multiple registries for simultaneous simulations, i'd want multiple singletons for each and b) I like to think of the registry as the ultimate source of truth of data c) easier for system functions to access the singleton data if associated with the registry. allows for `perfromSimStep(Registry)` instead of `simStep(Registry, cameraSingleton, timeSingleton)`,

**Comment by skypjack** [comment]
Added a note the to the TODO list. Not sure I'll reintroduce them with `v3`, but I'll do my best to do it. :+1:
