### ISSUE TITLE
How to forward declare Registry and Entity

### ISSUE THREAD

**Issue by Josid88** [skypjack/entt#177]
Hi,

Could you please tell me how to forward declare Registry and Entity, I'm currently using an alias such as the pacman sample:

using Registry = entt::DefaultRegistry;
using Entity = Registry::entity_type;

**Comment by Kerndog73** [comment]
You can’t forward declare a type alias. Why do you need to do this?

**Comment by skypjack** [comment]
Confirmed. It's possible with `master`, but it is not with v2.7.3 and the C++14 branch in general.  
However, that version is in maintenance mode (put aside paid works). So, do not expect a change for this any time soon.  
I'm sorry. I've not enough bandwidth to keep alive two versions.

**Comment by Kerndog73** [comment]
@skypjack A forwarding header that just forward declared the whole library might improve compile times a little bit. Like iosfwd. Although EnTT isn’t a huge library so I don’t think it will make much difference.

**Comment by Kerndog73** [comment]
The view.hpp header forward declares the registry. But you can’t forward declare the defaulted template argument.

**Comment by skypjack** [comment]
Oh, I see what you mean, you would forward declare all the template classes. Risky but yes, it could work. Of course, the default template cannot be forward declared unfortunately.

**Comment by Josid88** [comment]
The thing is that I'm migrating my Java/Artemis-odb engine to entt(way more portable to other engines like unreal/urho/godot), I will create some bindings to call them from java as I'm using libgdx for rendering, and I really don't wan't to import all the includes because I'm compiling the jni bind.

Currently I'm using a forward declared wrapper in order to address this, so it's not a big deal.

By the way, thanks for answering so soon, and great job on entt.

**Comment by skypjack** [comment]
Thanks @Josid88 - I'm sorry you can't forward declare types with C++14 version.
Probably you can get it to some extents with the advice from @Kerndog73 btw.
Also, don't forget to star the project if you use it and like it.

**Comment by Kerndog73** [comment]
@skypjack I was thinking. Perhaps `entt::registry` could be declared in a similar way to `std::string`. Perhaps the default entity type could be available in the `entt` namespace too.

```C++
template <typename Entity>
class basic_registry;

using entity = uint32_t;
using registry = basic_registry<entity>;
```

This could be put in the forwarding header (along with all of the other forward declarations). Then `registry.hpp` would include the forwarding header to make `entt::entity` available. If the user requires a different entity identifier like `uint64_t`, there's nothing stopping them from writing their own type alias.

Defaults should have short names.

**Comment by skypjack** [comment]
@Kerndog73 sounds good indeed. Maybe it's worth it opening a dedicated issue and see what others say about it. What about?

**Comment by Kerndog73** [comment]
@skypjack I'll get right on it!

**Comment by Josid88** [comment]
@Kerndog73 I forwarded declared as you mention it worked for me on c++14 version. It reduced my compilation time in 20% approximately, thanks :+1:
