### ISSUE TITLE
Error in VS2015

### ISSUE THREAD

**Issue by galek** [skypjack/entt#18]
Hi, i have C2610 error in VS 2015 on this lines:
    /*! @brief Default copy assignment operator. @return This hashed string. */
    constexpr HashedString & operator=(const HashedString &) noexcept = default;
    /*! @brief Default move assignment operator. @return This hashed string. */
    constexpr HashedString & operator=(HashedString &&) noexcept = default;

In hashed_string.hpp.

Fix: comment constexpr for VS 2015(using define _MSC_VER>1900)

**Comment by skypjack** [comment]
Facts:

* A copy/move constructor/assignment operator doesn't make much sense for args aren't literals, I'd remove them all actually.

* MSVC 2015 doesn't fully support C++14, I suspect you'll encounter several problems unfortunately. Tests use MSVC 2017 and everything works fine with it.

Is it the sole error you encountered compiling tests?

**Comment by skypjack** [comment]
a727857 made it work with MSVC2017 as expected.
I cannot do much more for MSVC2015, for it's not a fully compliant C++14 compiler, I'm sorry.
Let me know if it works fine also for you. Otherwise, copy and paste the error and let's see what we can do to work around it, if possible.

**Comment by skypjack** [comment]
No reply and it works with MSVC 2017 as expected. The issue on hashed string is solved and `constexpr` isn't there anymore.
I'm closing the issue. Feel free to contact me if you need more help.
