### ISSUE TITLE
[bug] assertion failed at: registry.get<>(entity, component)

### ISSUE THREAD

**Issue by dBagrat** [skypjack/entt#185]
After latest update (master branch) I am experiencing "crash" at
`registry:
template<typename Component>
    Component & get(const entity_type entity, Component &&component)`
when component not exsist (in the pools) yet.
assertion failed here:
`assert(type<Component>() < pools.size() && pools[type<Component>()]);`
(line 131)

**Comment by Kerndog73** [comment]
Looks like there should be a call to `assure` instead of `pool`.

**Comment by skypjack** [comment]
Uhu, my fault. @Kerndog73 was right, I put a `pool<C>` in the wrong place with the last changes. Fixed.

**Comment by dBagrat** [comment]
> Uhu, my fault. @Kerndog73 was right, I put a `pool<C>` in the wrong place with the last changes. Fixed.
Thanks you! :)

**Comment by skypjack** [comment]
You're welcome. Thank you that pointed it out. I've also added a test to avoid the same error in future. :+1:
