### ISSUE TITLE
[Feature Request] Make the registry work across boundaries

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#186]
This is a follow up of #182 to discuss the problem in the title.  
To sum up: on Windows, inline variables aren't guaranteed to be unique between all the TUs and thus things could break when the registry is pushed across boundaries.

There are several solutions that could make it work when a single library is used with a main executable. However, most of them will still break in case of multiple libraries used together at once. Therefore I won't even mention these solutions.

So far, a widely accepted proposal (discussed on gitter) is based on _named components_. In other terms, components that will be pushed across boundaries must be assigned a compile-time name.  
This solution can be implemented in two different ways, each with its pros and cons:

1. Components inherit from a dedicated class template:
   ```cpp
   struct my_component: entt::shared<"my_name"_hs> { /* ... */ };
   // or even SHARED(my_component) { /* ... */ };
   // ...
   registry.do_something<my_component>(entity);
   ```
   A macro can be used to ease the definition, of course. In this case, whenever a shared component is detected, the registry searches it by name instead of by identifier. A secondary macro can be used to force the behavior only on libraries and rely on direct access through identifiers in the main executable.

2. The other way around doesn't affect component definitions, but require users to explicitly specify when to use a components in _shared mode_, that is by name. Something along this line:
   ```cpp
   struct my_component { /* ... */ };
   // ...
   registry.do_something<my_component>(entity); // direct access with numeric identifier
   registry.do_something<SHARED(my_component)>(entity); // work fine across boundaries
   ```
   This is a bit more verbose, but users have finer control and their components are _theirs_. Moreover, it's clear at the call site whether a component is used in shared mode or not.

I'm open to comment, critiques and suggestions. I won't to get rid of this limitations, because it's getting annoying, so let's discuss it and solve the problem once and forever.

---

**EDIT**

I tried to implement a first draft. Another possible approach is to rely on 1. and split components between shared and non-shared ones. In other terms, to have two vectors of pools. The drawback is that there are two vectors ofc. :smile:  
It would affect to an extent only those components that are pushed across boundaries.  
On the other side, this is trickier, it requires much boilerplate and it will be most probably harder to maintain.

A trivial approach instead, probably the easiest to implement and to maintain, is to have the whole registry as shared and non-shared.  
It means that internally the registry uses always a direct access or always a name based lookup. When users are dealing with dlls on Windows, it's enough to set up a macro and have components that inherit from `shared_t` to provide a _name_. In all the other cases, the lookup by name is disabled and everything works by direct access.  
Less granular, ofc, but it requires to change only one function at a first glance.

Comments?

---

**EDIT**

@ArnCarveris came up with a good idea that is a compromise between what we discusses so far, gets rid of inheritance and is safe as well.  
This edit to keep track of it (names can change in the final version):
```cpp
template<typename>
struct shared_traits;

template<>
struct shared_traits<my_component> {
    static constexpr auto value = "my_component"_hs;
};
```
A few macros will be provided to ease the definition of shared components. In particular:

* ```c++
   ENTT_SHARE(my_component);
   ```
   To use to turn an already existing type in a shared one.

* ```c++
   ENTT_SHARED_STRUCT(my_component) { /* ... */ };
   ENTT_SHARED_CLASS(my_component) { /* ... */ };
   ```
   To use to define directly a type as a shared class.

Feedback are welcome.

**Comment by ArnCarveris** [comment]
My vote for 2

**Comment by ArnCarveris** [comment]
@skypjack 

`registry.share<my_component>("my_name"_hs);`

**Comment by skypjack** [comment]
@ArnCarveris The problem is that this way you set a name for a component and that's fine, but you don't know when and why to use direct access or indirect one. I want to avoid to go by name if possible, when you're in the main executable.

**Comment by ArnCarveris** [comment]
@skypjack Ok when why at this point name `hashstring` is needed?

`registry.share<my_component>();` No??

**Comment by skypjack** [comment]
@ArnCarveris no, I want to use shared types with already existing member functions like `registry.get<SHARED(my_type)>(entity);`, but still I want direct access in the main executable as `registry<my_type>(entity);`.  
What should `registry.share<my_component>();` do instead? I don't get it. Just set a name for `my_component` to use later? This wouldn't solve the problem of using it only when needed, because you don't know what the user wants, when and why.

**Comment by ArnCarveris** [comment]
It will make `my_component` sharable from main executable to lib. 

What `SHARED` macro defines?

**Comment by skypjack** [comment]
The point isn't to make it _sharable_. The point is to know whether we must get a pool directly (as it happens now) or by name. For a given type, I can do both the thing and make it _sharable_ doesn't give me a clue on when to use direct access or not.

`SHARED` is a way to tell - _yo, registry, for this member function and for this specific call only, get the pool for `T` by name instead of by relying on direct access_.  
This way you can avoid searching by name within the main executable or on linux (eg by defining SHARED yourself as a no-op).

**Comment by vblanco20-1** [comment]
I think having it on the view is a huge mistake. Its far too easy to get wrong. 
Programmers have mistakes constantly, and every EnTT user will forget to type SHARED a few times, causing weird bugs or crashing in an assert. Even if the shared component way is slightly slower, i think its preferred just due to it being miles more safe to use.

**Comment by ArnCarveris** [comment]
@skypjack Is possible to avoid using macro?

**Comment by skypjack** [comment]
@ArnCarveris yeah, sure, macros will be only shortcut to ease the definition of components.  
You can do either:
```cpp
SHARED(my_component) { /* ... */ };
```
Or:
```cpp
struct my_component: entt::shared<"a_name"_hs> { /* ... */ };
```

**Comment by ArnCarveris** [comment]
@skypjack how `entt::shared` will be implemented?

**Comment by skypjack** [comment]
@ArnCarveris I don't know yet what's the final definition, probably something like this:
```cpp
template<typename hashed_string::hash_type HS>
struct shared_t { static constexpr auto value = HS; };
```

**Comment by ArnCarveris** [comment]
@skypjack I prefer to avoid force inherence, maybe this?:
```
template<typename Type, typename hashed_string::hash_type HS>
struct shared_t { using type = Type; static constexpr auto value = HS; };
```
```
using my_shared_component = entt::shared_t<my_component, "a_name"_hs>;
```
```
registry.view<my_shared_component>().each([](auto &&...) { /* ... */ });
```

This is possible?

**Comment by Kerndog73** [comment]
@ArnCarveris but then you have to worry about `my_shared_component` and `my_component`. It's possible to lookup the right pool and cast it to the right type using that approach but I don't like it. It's not polymorphic inheritance and the base is empty so I don't think of it has "real inheritance". If you really, really hate any kind of inheritance with a passion you could do this:

```C++
struct my_component {
  static constexpr hashed_string::hash_type entt_hash = "my_component"_hs;
};
```

but that's just more typing with no real benefit.

**Comment by ArnCarveris** [comment]
Hmm, agree.

```cpp
template<typename>
struct shared_traits;
```
```cpp
template<>
struct shared_traits<my_component>
{
    static constexpr hashed_string::hash_type value = "my_component"_hs;
};
```

I prefer do no modify `my_component` for making it shared.

**Comment by skypjack** [comment]
The fact is that it's risky to allow users to pass a component either as shared or as a plain type. In the second case, you don't have a name and you don't know it was shared, so the registry ends up creating two pools: one for the type when used _the standard way_ and one for the type when used as shared. It summons for subtle errors almost surely.

I'm not a fan of forcing classes to inherit from something, but also I don't want to spend my time trying to explain to new users that they are shooting in their feet because they did both `registry.view<my_shared_component>().each([](auto &&...) { /* ... */ });` and `registry.view<my_component>().each([](auto &&...) { /* ... */ });` in their code.

**Comment by ArnCarveris** [comment]
@skypjack I agree with this fact

**Comment by ArnCarveris** [comment]
For shared traits is acceptable to implement macro: 
```cpp
ENTT_SHARE_COMPONENT(my_component);
```

**Comment by Kerndog73** [comment]
Then you have to mention the component name twice. If `shared_t::value` was `private` and `shared_t` was friends with the `registry`, **you'd never even notice that `my_component` inherits `shared_t`** (unless you look at the code or use `std::is_base_of_v`). `shared_t` is empty and doesn't expose any interface to the user.

**Comment by skypjack** [comment]
>Hmm, but you could define `ENTT_SHARE_COMPONENT` so that it forward declares `my_component`, specializes `shared_traits`, then inserts `struct my_component`

It doesn't look bad actually and I thought the same @Kerndog73 - this would get rid of inheritance and we can still detect whether a type is shared or not in all cases (internal utility `is_shared_v` or similar). No ambiguities or risky uses.

**Comment by ArnCarveris** [comment]
```cpp
ENTT_SHARE(my_component);
```

```cpp
ENTT_SHARED_STRUCT(my_component) {
  // ...
};
ENTT_SHARED_CLASS(my_component) {
  // ...
};
```

**Comment by skypjack** [comment]
@ArnCarveris what is `ENTT_SHARE` for? I think the two below are more than enough. I don't want to provide a third _default version_ that is just unclear and misleading. My two cents.

**Comment by Kerndog73** [comment]
How about `ENTT_SHARE` which defines a `struct`. If the user wants a `class` they could do this:

```C++
ENTT_SHARE(my_component) {
private: // now it's a class!
  // ...
};
```

**Comment by ArnCarveris** [comment]
If those will work when  `ENTT_SHARE` will be not needed;
```cpp
struct my_struct_component {};
```
```cpp
class my_class_component {};
```
```cpp
ENTT_SHARED_STRUCT(my_struct_component);
ENTT_SHARED_CLASS(my_class_component);
```

**Comment by ArnCarveris** [comment]
Anyway there should work:
```cpp
ENTT_SHARE(my_component) {
  // ...
};
```
and
```cpp
ENTT_SHARE(my_component);
```

**Comment by skypjack** [comment]
Got the reasoning.

**Comment by skypjack** [comment]
@ArnCarveris @Kerndog73 I'm not that sure that _shared_ is the right term here.  
In fact, if I've a registry in the main executable and I want to push it across boundaries, all the components used within the library should have a name to avoid conflict with already existing identifiers. However, they could not be shared between the library and the main executable.  
Therefore the name is a bit misleading. Probably also the fact that one can mix shared and non-shared components to an extent can create confusion.

To make things easier to understand for users, maybe the best thing would be to make the whole registry _shared_. Something like `ENTT_SHARED` that forces components to have a name, all of them and that's all.

**Comment by ArnCarveris** [comment]
@skypjack Well, maybe user should define `ENTT_EXPORT` &`ENTT_IMPORT` macros?

**Comment by skypjack** [comment]
@ArnCarveris can you provide me with more details on their purposes?

**Comment by ArnCarveris** [comment]
@skypjack I mean this use case: https://www.gamedev.net/forums/topic/550895-dllimport--dllexport-with-libsdlls/

**Comment by ArnCarveris** [comment]
@skypjack hmm...
`ENTT_SHARE`:
```cpp
ENTT_API_INCLUDE(my_component);
```
`ENTT_SHARED_STRUCT`: 
```cpp
ENTT_API_STRUCT(my_component) { /* ... */ };
```
`ENTT_SHARED_CLASS`: 
```cpp
ENTT_API_CLASS(my_component) { /* ... */ };
```

**Comment by skypjack** [comment]
You made me think... could we just solve the problem with a `dllexport`? Why didn't I try it before to start?

**Comment by ArnCarveris** [comment]
@skypjack I mean is common practice to define `DLL_EXPORT`, `DLL_IMPORT` and `DLL_API` when dealing with shared libs...

**Comment by skypjack** [comment]
Yeah, I see, but I was wondering if using `dllexport`/`dllimport` would work on Windows without changes to `EnTT`.

**Comment by trashuj** [comment]
Issue happens also with static libs on windows, i dont think this would
solve anything.

**Comment by skypjack** [comment]
Right. Let's continue with what we agreed on so far. :+1:

**Comment by Green-Sky** [comment]
Just want to add, that "naming" components might benefit or impact serialization. It could make saving and loading not component-wise-equal snapshots easier.

**Comment by skypjack** [comment]
@Green-Sky that's true, but I don't plan to update also snapshot so as to use names tbh, mainly because I don't really need it at the moment. However, what you say can be applied archive side.  
These changes will allow to push across boundaries those classes that use families internally (registry, dispatcher, emitter) instead.

I'm open to PR or paid feature requests in case.

**Comment by skypjack** [comment]
I've still to test it, but branch `wip` contains a first draft to make a registry work across boundaries.  
`ENTT_ShaRED_TYPE` can be used to make a type exportable once defined. `ENTT_SHARED_STRUCT` and `ENTT_SHARED_CLASS` can be used to define the type itself and make it exportable at once.  
If you decide to test it, do not open new issues in case of problems. Please, just add a comment to this issue and let me know what's wrong.  
It will take a while to write a test suite for this feature. Moreover, there are other classes that deserve the same treatment (`dispatcher` and `emitter`). I don't know yet if I'll merge `wip` on `master` a class at a time or all at once when everything is done.

**Comment by skypjack** [comment]
Code coverage 100%. Macro reviewed. I've to write doc yet.  
The branch misses a test that pushes and uses a registry across boundaries, but I'm quite confident that everything works as expected. :+1:

**Comment by skypjack** [comment]
Up and running on branch `wip`. Doc updated (see `lib.md`).  
Roughly speaking, we have the `registry` working across boundaries. :heart_eyes: 
If no one comes out complaining about problems with the new implementation, I'll merge it on `master` during the week. :+1:

**Comment by skypjack** [comment]
Ready to go. Available on branch `experimental`.

**Comment by skypjack** [comment]
Upstream on `master`.
