### ISSUE TITLE
Wiki page for Dispatcher may be out of date?

### ISSUE THREAD

**Issue by unl1ght** [skypjack/entt#190]
The Wiki page "Crash Course: events, signals and everything in between" shows the dispatcher class being constructed without any template parameters. However, it seems that the dispatcher must be constructed with a templated value type that will be provided to connected callback functions (in addition to the event type itself). This also seems to be the way dispatcher is used in the entt test source code, where the day is constructed with int template argument and is used to trigger events of type "an_event".

Does this mean the Wiki page is out of date? Is there a way to use dispatcher where only the event struct is sent to connected functions without an additional data type (such as the int used in the test code)?

**Comment by Kerndog73** [comment]
> Does this mean the Wiki page is out of date?

@skypjack seems to keep on top of that pretty well so probably not

> Is there a way to use dispatcher where only the event struct is sent to connected functions without an additional data type (such as the int used in the test code)?

That's what the Wiki demonstrates. Although, I haven't tested it. I think you might need to do `entt::dispatcher<>` instead.

**Comment by skypjack** [comment]
Indeed it's outdated, my fault.  
However, it is due to a change that I plan to revert this week, because it's pointless.  
Please, leave the issue open. I'll close it as soon as I find the time to do that.  

Thanks.

**Comment by unl1ght** [comment]
Just want to say thank you for solving this issue so quickly <3
