### ISSUE TITLE
idiomatic way to do entity related events and entity id specific listeners.

### ISSUE THREAD

**Issue by Paolo-Oliverio** [skypjack/entt#198]
Is the use case of listening for events specifically related to an entity id and/or listen for an event that is intented to be called with  at least an entity id as payload so widely common and "generic" to justify a proper api or there is just a clear idiomatic way to do it with the provided api?
This because I us to work this way in other systems and I  still have to check if the api may support this elegantly or may require some additional feature or syntactic sugar.

**Comment by skypjack** [comment]
>Is the use case of listening for events specifically related to an entity id and/or listen for an event that is intented to be called with at least an entity id as payload so widely common and "generic" to justify a proper api or there is just a clear idiomatic way to do it with the provided api?

Signals on a per-entity basis aren't a good idea from my point of view. It would mean either to have thousands of signal handlers (one per entity) or to wrap all the listeners in a function that literally _add an `if`_ to filter events (and to ruin performance as a side effect).  
Similarly, application specific events (like the ones _with an entity as a payload_) should not find their ways into the registry for obvious reasons.

I see you need custom _things_ for your application and you want them to be part of the registry, but you should rather extend the latter if needed.

**Comment by Paolo-Oliverio** [comment]
Amazon Lumberyard has this concept of ebus channels I got used to and while I agree with you on paper I find them quite convenient in practice.Of course you get easily hundreds of handlers but in the end the profiler doesn't care so much. However it doesn't manage so many entities due to other factors so I cannot say how much extensive channel usage scales per se.

**Comment by skypjack** [comment]
How does it work? Do you register listeners on _entities_? I've never used Lumberyard, sorry.

**Comment by Paolo-Oliverio** [comment]
It is component entity indeed so you have component code signal and handle you listen on specific channels of template type mostly entity type. However on a further analysis I can map most of my workflow if not all to actual API and in most cases be more efficient too.

**Comment by skypjack** [comment]
I'm curious because I've never had the need of listening for specific entities. I can be interested in the couple `(component, entity)` either constructed or destroyed, that is what the registry makes available. However, I cannot figure out the use case for the entity only.
