### ISSUE TITLE
Requesting to add novuscore to the list of Entt in action

### ISSUE THREAD

**Issue by NixAJ** [skypjack/entt#204]
Greetings, I would like to propose that we add NovusCore to the list of projects using Entt in action.

**What is NovusCore**
NovusCore is an emulating project for World of Warcraft. We aim to support as many versions as we can, in an as flexible manner as possible, meaning that the aim to make it 'easier' to have multiple game builds supported by the same core.

Currently NovusCore is being written baseline for the Wrath of the Lich King 3.3.5a 12340 client build. This is to better enable us to design our architecture around the WoW Client. 

**The NovusCore Promise**
The project was made with the promise that we would always focus on reliability, redundancy, and performance over convenience. We achieve this through making use of experience, but also applying modern techniques and design patterns.

The end-goal is to provide a core capable of tackling all of the current limitations set by the cores available. Solving those issues are complicated, but we start by applying a proper foundation for our architecture to allow for better flow of information(data) and performance.

We are proud to say that we use Entt as a core part of our architecture.

Github Link
https://github.com/novuscore/NovusCore

**Comment by skypjack** [comment]
What's the right section? Games, engines/framework or even something new?

**Comment by NixAJ** [comment]
Possibly a new section?

NovusCore is essentially compiled and build into different server exes which all talk together, so its not an engine, not a standalone game and I wouldn't say a framework either.

Not sure what you would categorize it as, but potentially "Emulators"

**Comment by skypjack** [comment]
Fine for me. Let's see if somebody pops out with a better name, otherwise I'll use it. :+1:

**Comment by vblanco20-1** [comment]
@NixAJ  super interesting project. Whats the status of it?

**Comment by NixAJ** [comment]
@vblanco20-1 Current status is that we're working on the ground fundamentals, we can get ingame and have been able to see another player (With hardcoded packet sent with the guid), but it does work so we're currently working on structuring all of our worldserver code with entt in mind.
