### ISSUE TITLE
[doc] describe when references and iterators are invalidated

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#206]
Add a note in the doc to describe when and how iterators and references are invalidated, either during iterations or not.

**Comment by Kerndog73** [comment]
This seems to be [mentioned already](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#what-is-allowed-and-what-is-not)

**Comment by skypjack** [comment]
@Kerndog73 you're right, there is also an example about the references. I forgot it. Thanks.

**Comment by skypjack** [comment]
However I think I want to add a note about adding components of types that belong to groups where you're not iterating them in their group.  
This is completely safe and should be avoided as far as I can see, but I realized this yesterday around midnight and probably I should think better about it. :smile:
