### ISSUE TITLE
Error compiling example. ‘entt::registry’ is not a template

### ISSUE THREAD

**Issue by joaosausen** [skypjack/entt#209]
I just cloned entt and tried to compile the example on the README.
The command I used was 

`g++ main.cpp -o game -std=c++17 -Wall -I../entt/src/`

The error is:

```
main.cpp:14:13: error: ‘entt::registry’ {aka ‘entt::basic_registry<unsigned int>’} is not a template
 void update(entt::registry<> &registry) {
             ^~~~
main.cpp:25:31: error: ‘entt::registry’ {aka ‘entt::basic_registry<unsigned int>’} is not a template
 void update(std::uint64_t dt, entt::registry<> &registry) {
```

**Comment by skypjack** [comment]
Oh, thanks. It's due to some recent changes, I forgot to update the README file.  
It's enough to remove the `<>` at a first glance, but I'm from mobile now. I'll update the example as soon as I turn on my laptop.

**Comment by joaosausen** [comment]
I removed the <> and I can confirm it works. Thanks @skypjack

**Comment by skypjack** [comment]
Thank you for point it out. Please keep the issue open so that I won't forget to update it. :+1:
