### ISSUE TITLE
Article about EnTT

### ISSUE THREAD

**Issue by Leinnan** [skypjack/entt#210]
Article about creating example project using SFML 2.5 and EnTT using modern C++, Conan and CMake. 
https://leinnan.github.io/blog/conan-adventuressfml-and-entt-in-c.html

**Comment by skypjack** [comment]
That's good. Can I put it in the wiki? Not sure that was the request.

**Comment by Leinnan** [comment]
Feel free to do it if You want ;)
I wanted to add documentation label but failed to do so. :D Maybe because I don't use github a lot
