### ISSUE TITLE
"error C2066: cast to function type is illegal" on VS 2017

### ISSUE THREAD

**Issue by DoerriesT** [skypjack/entt#212]
https://github.com/skypjack/entt/blob/3beac98499187a192c5f576ad07b33b8bf7b58e5/src/entt/entity/registry.hpp#L156 and https://github.com/skypjack/entt/blob/3beac98499187a192c5f576ad07b33b8bf7b58e5/src/entt/entity/registry.hpp#L165 cause a compilation error (error C2066: cast to function type is illegal) on Visual Studio 2017 Version 15.9.10 and with /permissive- enabled. This error seems to be caused by a bug in MSVC, which is supposedly internally fixed and pending release. https://developercommunity.visualstudio.com/content/problem/220267/using-is-broken-regression-in-1570-p2.html . I "fixed" the error by directly specifiying the type instead of using the alias.

**Comment by skypjack** [comment]
How long will it take to release a version of msvc with the fix required to accept valid code?  
I don't like much to change the code of the library to work around idiosyncrasies of a tool. However, if the plan is to release msvc by June or so, I'll make a change to the upstream to support it in the meantime.  
Any clue from them?

**Comment by DoerriesT** [comment]
I don't have any concrete information about when it will be released, but I was told that the fix is likely going to be released with Visual Studio 2019. Since I got this info second hand, I don't know for sure when or how it will be released, but somehow I suspect that it's not going to be soon.

**Comment by skypjack** [comment]
That's good, I'll get rid of aliases then.

**Comment by skypjack** [comment]
Pushed the change on branch `experimental`. Can you confirm it` works fine before I merge on `master`?
