### ISSUE TITLE
Resource cache wiki is out of date

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#213]
There seem to be a few inconsistencies between the code and the wiki.

> Where `resource_type` is an alias for `entt::hashed_string`. Therefore, resource identifiers are created explicitly as in the following example:

[The code says otherwise](https://github.com/skypjack/entt/blob/a5f48f8af8f5a65bd77393f6c3eed44c304cad1f/src/entt/resource/cache.hpp#L37). `resource_type` is defined as `entt::hashed_string::hash_type` (aka `uint32_t`). This means that `_hs` is missing from the examples that follow.

> The declaration is similar to the one of load but for the fact that it doesn't return a boolean value. Instead, it returns a (possibly invalid) handle for the resource:
> ```C++
> auto handle = cache.temp<my_loader>("another/identifier", 42);
> ```

That seems to suggest that `temp` takes a `resource_type` as a first argument [but it doesn't](https://github.com/skypjack/entt/blob/a5f48f8af8f5a65bd77393f6c3eed44c304cad1f/src/entt/resource/cache.hpp#L143).

I suggest renaming `resource_type` to `resource_id` because I expect `entt::resource_cache<QImage>::resource_type` to be `QImage` and not `uint32_t`.

---

This might be more appropriate in a separate issue but I think a `lazy_load` function would be pretty handy. It would be similar to `load` except that it returns the resource handle (that may or may not have just been loaded) instead of a `bool`. We can save a call to `unordered_map::find` by doing it this way instead of having the user call `load` and then `handle`.

**Comment by skypjack** [comment]
Interesting. Something like - _give me handles as if resources existed, so by creatine placeholders, I'll load them when it makes sense to me_.  
Actually it looks like a more polished API.

**Comment by Kerndog73** [comment]
That's not exactly what I had in mind. I was thinking this:

```C++
template <typename... Args>
resource_handle<Resource> lazy_load(resource_type id, Args &&... args) {
  load(id);
  return handle(id);
} 
```

**Comment by skypjack** [comment]
Doc should be updated now (still to port it on the wiki). See the commit above.  
I prefer not to change `resource_type` to `resource_id`. After all, eg `entity_type` is an `std::uint32_t` and it makes perfectly sense to me. I'd rather blame the `resource_` part and not the `_type` part: probably `identifier_type` would be a better choice.

**Comment by skypjack** [comment]
Updated `load` and `reload`. Good point, thanks for the suggestion. :+1: 
Let me know if you see any other flaw in that part.

**Comment by Kerndog73** [comment]
Looks good to me. The new signature for `load` makes way more sense.
