### ISSUE TITLE
Entity Component System documentation outdated.

### ISSUE THREAD

**Issue by unl1ght** [skypjack/entt#216]
Howdy pard'ner,

I recently updated to the latest entt version which has broken my program. Specifically with intialisation of the entt::registry<uint64_t>, it appears that the registry no longer accepts a template for the underlying entity type as per the following error message.

![image](https://user-images.githubusercontent.com/7434573/55451380-32a01080-561a-11e9-95a2-a989e2238bef.png)

I checked the documentation to see what the process is for setting the entity type, but it does not appear to be updated under "Vademecum":

https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#vademecum

**Comment by Kerndog73** [comment]
Well spotted!

As the error message shows, `entt::basic_registry<uint64_t>` is what you want. However, the default 32-bit identifier (used by the alias `entt::registry`) is enough for 2^20 (1,048,576). I'm curious as to what you're doing with over a million entities!

**Comment by skypjack** [comment]
Good point @unl1ght I missed that part. Thanks for pointing it out.

@Kerndog73 You're right. However I always re-read the doc to find inconsistencies when I do this kind of changes.  
Unfortunately sometimes I fail to spot all the errors. `EnTT` is getting bigger and it's well documented. This is ironically both a pro and a con, because my free time isn't that much and re-reading everything is really time consuming.

**Comment by Kerndog73** [comment]
@skypjack I _might_ be able to find the time to do it. If I find anything I’ll gather it all into an issue or maybe even a PR if I have the time.

**Comment by skypjack** [comment]
Well, it goes without saying that any help is appreciated. :wink:

**Comment by unl1ght** [comment]
Thanks guys, I will switch over to basic_registry.

@Kerndog73 I'm not using basic_registry<uint64_t> in practice, only to demonstrate the issue. Maybe one day I will have an exciting enough project to warrant > 2^20 entities ;)

**Comment by skypjack** [comment]
>Maybe one day I will have an exciting enough project

What's the project in which you're currently using `EnTT` instead?  
There is a [dedicate section](https://github.com/skypjack/entt/wiki/EnTT-in-Action) for the projects that are using `EnTT` if you feel like to put a link or a mention of your own.

---

Please, keep open the issue until I fix the doc. It will help me not to forget it.
