### ISSUE TITLE
should empty components be serialized by snapshots?

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#219]
More discussion than issue. I have an empty component tag being serialized by the snapshot, it's going to be an empty {} json object.

so something like this: "empty_tags": [numids, id, {}, id2, {}]

it may make more sense to only serialize the component if `constexpr(!std::is_empty_v<Component>)`

so that it ultimately does something like this for empty tag components...
"empty_tags": [numids, id, id2]

**Comment by pgruenbacher** [comment]
see https://github.com/skypjack/entt/pull/220

**Comment by skypjack** [comment]
Do you mean not to emit the component when it's empty? It makes sense actually. The archive could already discard it, but an opaque archive that doesn't care about the types would benefit from this and there is no need to emit the component in this case. I agree.

**Comment by pgruenbacher** [comment]
yea I wasn't sure how to tell cereal to "discard" it, cause an empty serialize implementation for the empty component still led to "{}". I like the idea of the archiver not having to worry about the empty tag components.

**Comment by skypjack** [comment]
Indeed. I cannot work on it right now, but I'll definitely review and merge the PR soon. Thanks. :+1:

**Comment by skypjack** [comment]
I've merged your PR on `experimental` and reworked it a bit.  
If it works fine, I'll merge it upstream the next time I turn on my laptop.  
Let me know. Thank you again for pointing it out.
