### ISSUE TITLE
Call for comments: runtime components support

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#23]
Currently, being `EnTT` based exclusively on templates, there isn't the possibility to define components at runtime.  
The main purpose would be for scripting and plugins, but who knows what other uses are out there.  
See [this](https://forum.freegamedev.net/viewtopic.php?t=7661&p=74779) as an example.

I've thought to the problem and I'm ready to develop a solution that fits well with the API of `EnTT`.  
That being said, I would like also to know what are the use cases for such a feature, if any. I don't want to miss something during the development.

I'll leave the issue opened until the code is available on `master`.  
Feel free to comment whenever you want, give suggestions and make request for related features.

**Comment by mattcontinisio** [comment]
As you said, I think this would be really nice to have for scripting and plugins. This would also be nice to have for the event bus as well, if possible.

**Comment by dbacchet** [comment]
one big use case I have is supporting cross-language plugins. We expose some of the functionality of our simulation system through python, and having the possibility to define components and/or plugins in python and make the ECS aware of those would be great.

If I have to trade this with a clean API though, I would always choose a clean and minimal API!
One of the big advantage of EnTT imho is that is small enough that can be very well understood and customized. It's a fantastic building block and I would keep it like that.
Not a big fan of huge, entangled frameworks (did somebody say boost?!?) :)

**Comment by skypjack** [comment]
@mattcontinisio
Actually I didn't consider the signal stuff in this issue. However it makes sense to extend it to the bus and probably to the dispatcher.  
I'm not sure it fits well in those classes, but I'll have a go and I'll give you a feedback as soon as possible.

**Comment by skypjack** [comment]
@dbacchet 
Your use case is more or less the reason for which I'm proposing this feature.  
The API will be minimal and hopefully clean as usual. Something like the member functions you already have, with an extra parameter to dispatch the call to the right subsystem (either compile-time or runtime).  
Probably I'll add a dedicated view for those cases where you want to use runtime components.  
That's all. What about?

**Comment by DJuego** [comment]
_If I have to trade this with a clean API though, I would always choose a clean and minimal API!_ ( @dbacchet )

I completely agree! High performance, clean and minimal are The Keys (IMHO). 'Elegant' too, probably. 

DJuego

**Comment by skypjack** [comment]
@DJuego @dbacchet
You know, I'm always open to suggestions and requests. ;-)
That's also the reason for which I create _call for comments_ issues before to add new features. Your feedbacks are invaluable.

**Comment by skypjack** [comment]
A possible API can be the following one:
```
// type for numeric identifiers of custom runtime components
using runtime_type = std::uint8_t;

// it prepares a dedicated pool bound to the given C++ component and returns its identifier
// note: the same component (ie LuaRuntimeComponent) can be used to create more than one pool
template<typename Component>
runtime_type custom();

// it returns the number of component in the given runtime pool
size_type size(runtime_type) const noexcept;

// well, you know... :-)
bool empty(runtime_type) const noexcept;

// it assigns an instance of the given C++ type (ie LuaRuntimeComponent) to the entity in a given runtime pool
template<typename Component>
Component & assign(runtime_type, entity_type, Component &&);

// it removes the given runtime component from an entity
void remove(runtime_type, entity_type);

// well, you know... :-)
bool has(runtime_type, entity_type) const noexcept;

// ... and so on, I'm pretty sure you got the way

template<typename Component>
const Component & get(runtime_type, entity_type) const noexcept;

template<typename Component>
Component & get(runtime_type, entity_type) noexcept;

template<typename Component>
Component & accomodate(runtime_type, entity_type, Component &&);

// not that sure it makes much sense and not that sure it's feasible as well
template<typename Component, typename Compare>
void sort(runtime_type, Compare);

// not that sure it makes much sense and not that sure it's feasible as well
template<typename Component>
void sort(runtime_type, runtime_type);

void reset(runtime_type, entity_type);

void reset(runtime_type);

// it creates a runtime view for a runtime component (ie LuaRuntimeComponent)
// Component is the underlying type the view will return by means of the get member function
template<typename Component>
RuntimeView<Component> runtime(runtime_type);

// it creates a runtime view for a bunch of runtime components (ie LuaRuntimeComponent)
// Component is the underlying type the view will return by means of the get member function
template<typename Component>
RuntimeView<Component> runtime(std::vector<runtime_type>);
```

Feedback are welcome.
@dbacchet for you are already dealing with plugins, probably you can figure out if it could work or not for you and what are the weaknesses.

**Comment by skypjack** [comment]
Nevermind. `EnTT` was almost there to support runtime components and mods in general.  
I added a couple of functions to the registry and I'm developing an example to show how to do that.  
Unfortunately it will take a while because I'm doing it in my free time. However I feel like I'm on the right path.

**Comment by DJuego** [comment]
Fantastic-fantastic news!, @skypjack! In fact the best  possible news. This Christmas i want to study your work! I am really anxious to look for some application that I can do with this very promising resource.

DJuego

**Comment by skypjack** [comment]
The best part is that even mixing runtime and compile-time components in a kind of runtime view seems possible with the approach I've in mind.
I'm pretty excited actually. I really hope to be right, it would be great!!

**Comment by skypjack** [comment]
Update: the example uses duktape and is pretty minimal. It's not production ready, of course but it shows how compile-time and runtime components can be mixed together. I'm actively working on it. It will take still a few days to finish and publish everything for I've been a bit busy the last weeks.

**Comment by skypjack** [comment]
[Here](https://github.com/skypjack/entt/blob/master/test/mod/mod.cpp) it is.
I have still to update the documentation before to close the issue, but the example is upstream at least.

**Comment by DJuego** [comment]
Surely the current master is a transition period. However...
I'll warn you about it ;-P.

When i try to build the Code Example in README I get:

```
1>------ Build started: Project: entt_msvc2017, Configuration: Debug x64 ------
1>main.cpp
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\sparse_set.hpp(323): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\sparse_set.hpp(319): note: while compiling class template member function 'void entt::SparseSet<Entity>::respect(const entt::SparseSet<Entity> &) noexcept'
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\view.hpp(308): note: see reference to class template instantiation 'entt::SparseSet<Entity>' being compiled
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\src\main.cpp(16): note: see reference to class template instantiation 'entt::View<Entity,Position,Velocity>' being compiled
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\sparse_set.hpp(579): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\sparse_set.hpp(575): note: while compiling class template member function 'void entt::SparseSet<Entity,Velocity>::respect(const entt::SparseSet<Entity> &) noexcept'
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\view.hpp(316): note: see reference to class template instantiation 'entt::SparseSet<Entity,Velocity>' being compiled
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\view.hpp(312): note: while compiling class template member function 'bool entt::View<Entity,Position,Velocity>::Iterator::valid(void) noexcept const'
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\view.hpp(334): note: see reference to function template instantiation 'bool entt::View<Entity,Position,Velocity>::Iterator::valid(void) noexcept const' being compiled
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\src\main.cpp(18): note: see reference to class template instantiation 'entt::View<Entity,Position,Velocity>::Iterator' being compiled
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\inc\entt\src\entt\entity\view.hpp(502): error C2912: explicit specialization 'auto entt::View<Entity,Position,Velocity>::each::<lambda_30d3ba60f636de4df39768117cde981d>::operator ()(unknown-type,const Position &,const Velocity &) const' is not a specialization of a function template
1>        with
1>        [
1>            Entity=uint32_t
1>        ]
1>p:\mis-proyectos\personal\entt\src\main.cpp(38): note: see reference to function template instantiation 'void entt::View<Entity,Position,Velocity>::each<update::<lambda_1dc0a093c6c8dc4364f4ed1888795fb7>>(Func)' being compiled
1>        with
1>        [
1>            Entity=uint32_t,
1>            Func=update::<lambda_1dc0a093c6c8dc4364f4ed1888795fb7>
1>        ]
1>p:\mis-proyectos\personal\entt\src\main.cpp(31): note: see reference to function template instantiation 'void entt::View<Entity,Position,Velocity>::each<update::<lambda_1dc0a093c6c8dc4364f4ed1888795fb7>>(Func)' being compiled
1>        with
1>        [
1>            Entity=uint32_t,
1>            Func=update::<lambda_1dc0a093c6c8dc4364f4ed1888795fb7>
1>        ]
1>Done building project "entt_msvc2017.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
DJuego

P.S: Sorry for this :-)

**Comment by skypjack** [comment]
I know, appveyor just gave me a warning. I'm solving it as soon as possible, don't worry. ;-)
Thank you.

**Comment by skypjack** [comment]
@DJuego It should work now. Let me know, please.

**Comment by DJuego** [comment]
The thing builds now, @skypjack. 👍 

DJuego

**Comment by samaursa** [comment]
Sorry to resurrect this @skypjack your link in the comment is broken:
![image](https://user-images.githubusercontent.com/817849/186035029-ba25ed99-ef74-4fe4-97bf-e3a36386bd87.png)

Is there support for adding runtime components in `entt`? Or was this just an example which we can see in [this commit](https://github.com/skypjack/entt/commit/292978daf087793ba2c43f5a5e33d47f925a2d2b) which incidentally was never merged to `master`...?

**Comment by skypjack** [comment]
Hi @samaursa sorry for the lag. I'm on vacation and have limited access to a stable connection. As for the runtime components, can you be more explicit about what you're trying to achieve?
`EnTT` supports named pools now and therefore multiple pools for the same type `T` that you can create at runtime ie from a scripting system. However, it's hard to say if this is what you're looking for or if you're facing a different challenge.

**Comment by samaursa** [comment]
@skypjack No problem!

I have two problems:
- We have a component that will be specialised a few hundred times. Let's say that number of 300 different types of these components. Most of them will be instanced a few hundred times (i.e. 300 types, a few thousands instances). The interface will remain the same, only the logic and data will change (i.e. the size of `T` will change). Obviously, we could make the base component polymorphic but then that opens up a plethora of issues. So we are _not_ opting to go polymorphic. Worst case, we are willing to author code generation that spits out something like this:
```
registry.view<T>...
registry.view<T1>...
registry.view<T2>...
```
Ideally, we have runtime views where the only cost is the initial indirections to get the pool but then we do not pay for any other indirection while going over all components of one of the above types.

- The second problem is that we would like to create components at runtime i.e. create components in script that are then iterated over by a system (which is also in scripts). Ideally the runtime components would also be in a entt pool and the runtime view similar to what I explained in the point above.

**Comment by skypjack** [comment]
> a component that will be specialised a few hundred times

These are a few hundred different types in C++. How does it differ from using different types that aren't specialziations of the same class template? I think I'm missing something here. 🤔 

> create components in script that are then iterated over by a system

You know, C++ is a strongly typed language. Therefore, under the hood you're going to map these _runtime types_ to an actual C++ type. Let's say a map of accessors, mostly similar to what js engines do for example. We can call this type `T` 🙂 then everything boils down to creating multiple pools of type `T` and iterating them. Is it what you're looking for?

**Comment by samaursa** [comment]
(sorry for the delay in reply)

> These are a few hundred different types in C++. How does it differ from using different types that aren't specialziations of the same class template? I think I'm missing something here

Currently we have Systems that are registered to a 'world' which are then ticked. Because there are a few hundred and it's possible that quite a few of those systems have no components that are 'dirty' (i.e. they don't need to be ticked), we are ticking over a lot of systems needlessly (e.g. 100 out of 300 systems Tick only to find out they don't have to Tick any components). We can probably optimize that by adding removing systems (or treating Systems as components in an Entity and adding/removing them)

Thinking more about the problem and my original question, because the logic is different, I still require a different system for each type. I don't see a way around that.

> You know, C++ is a strongly typed language. Therefore, under the hood you're going to map these runtime types to an actual C++ type. Let's say a map of accessors, mostly similar to what js engines do for example. We can call this type T 🙂 then everything boils down to creating multiple pools of type T and iterating them. Is it what you're looking for?

Yes, that's exactly what I am looking for.

**Comment by skypjack** [comment]
> We can probably optimize that by adding removing systems

I'd rather measure to find that it's probably not necessary. This boils down to an iterator comparison probably. Isn't it?

> Yes, that's exactly what I am looking for.

`EnTT` made all storage available since a while ago and you can also assign them an identifier. That is, you can have multiple storage of the same type as long as you give them different (runtime) _names_:

```cpp
auto &&storage = registry.storage<T>(identifier);
storage.emplace(entity, value1, value2, value3);
storage.erase(entity); // yeah, they offer an interface similar to that of the registry

for(auto entt: entt::view{storage}) { ... }
```

Where `identifier` is a numeric value. If you have a runtime name, it can be an `entt::hashed_string::value(str)` for example.
Actually, nothing prevents you from having an externally managed storage that you mix with a view from a registry if you like:

```cpp
for(auto entt: entt::view{my_externally_managed_storage} | registry.view<T, U>()) { ... }
```

It also works if you want to just _track_ entities for example, since `entt::storage<void>` is a thing.
Does it address your needs? I'm thinking aloud while trying to help, feel free to drop more details or questions if needed.

**Comment by mingxxming** [comment]
my solution is precreate enough component  and write base component and system in c++  .. save data by type_id in my js or lua script. trigger script system by c++ runtime_view

**Comment by samaursa** [comment]
Thanks @skypjack, I think the runtime identifiers with storage would resolve some of our issues

> It also works if you want to just _track_ entities for example, since `entt::storage<void>` is a thing.

Sorry, just for my understanding could you explain the use case of being able to track entities?

**Comment by skypjack** [comment]
For example, you want to keep track of the entities for which _something happened_ (this really depends on the game logic), then combine them with a view. If you put the entities in a vector, you've to manually unroll the vector and the view somehow. On the other hand, if you've them in a storage class, you can do something like this:
```cpp
// entity only
for(auto entt: entt::view{my_storage} | registry.view<T, U>()) { ... }

// entity and components
for(auto [entt, t, u]: (entt::view{my_storage} | registry.view<T, U>()).each()) { ... }
```
Mostly convenience and qol feature, nothing special. 🙂

**Comment by AlpyneDreams** [comment]
Is there perhaps a way for registries to have storages for types that have a fixed size only known at runtime (i.e. based on autogenerated RTTI, for example)? With `registry.storage<T>(typeHash)` I can create storages with a statically known size (`sizeof(T)`, T could be `std::aligned_storage<N>` or `void` for example), but is a dynamic fixed size possible? Maybe some kind of custom allocator?

**Comment by samaursa** [comment]
@AlpyneDreams I am curious about that as well

@skypjack my previous questions/thoughts and your answers lead me to exactly what @AlpyneDreams is asking about. I would like to allocate component storage at runtime (with a fixed runtime size) where at compile time it's a `void*`. Then, I would like to be able to iterate over the component pool, also at runtime (where I will know the size of the type).

**Comment by skypjack** [comment]
If I get it correctly @samaursa all you need is to create one or more `storage<void *>`, which is of course possible already.
If you can be more specific about what problems you're having, I can try to help you better. Otherwise it's a little hard for me to understand what's blocking you.
Thanks. 👍

**Comment by skypjack** [comment]
Well, if you don't know the size **and** are not willing to pre-define fixed-size containers for your _runtime types_, all you can do is to allocate buffers one at a time when needed. 🤷‍♂️ 
The other option (that preserves contiguity or sort of) is to use fixed-size containers like storage of `std::byte[64]` or `std::byte[128]` and so on, then pick the _right_ one at runtime according with the size of your _runtime type_ and construct in-place your object into the buffer.
Consider that C++ is a strongly typed language and therefore it doesn't offer the possibility of defining _runtime types_. At the moment, I'm kinda guessing what you you're trying to achieve and thinking aloud to give you some hint if possible.

**Comment by samaursa** [comment]
As @AlpyneDreams said, as long as the `storage<void*>` is for the runtime type and _not_ for a pointer to the runtime type, then `storage<void*>` is what I am looking for.

Suppose at runtime, I have a new type (again, at runtime) with a size of `8 bytes` which is my runtime component. Further, suppose that I have 5 of the runtime components. I am hoping that entt's storage will allocate in-place storage of `8 * 5 bytes` (at least, could be more) for the runtime types and the runtime `view` returns a `void*` to each element such that `element[1]`'s address is `element[0] + 8`. The `void*` is then casted to the appropriate runtime type of `8 bytes` so that the runtime script can reason about the component data.

If that is indeed possible with `entt`, it would be great if you can point to an example to help me get started.

**Comment by skypjack** [comment]
As I said, C++ is a strongly typed language. You can't pass a runtime type to the type system of this kind of languages.
Therefore, you've a couple of options here. A `storage<void *>`-like storage that only contains pointers to dynamically allocated objects. Otherwise, something similar to a `storage<char[N]>` storage (for different `N`s ofc, you can pick the right one at runtime according with a runtime size in this case) that owns and returns tightly packed _buffers_ where you can construct your types. From what I read, the latter is closer to what you're trying to achieve?

**Comment by hls333555** [comment]
> As I said, C++ is a strongly typed language. You can't pass a runtime type to the type system of this kind of languages. Therefore, you've a couple of options here. A `storage<void *>`-like storage that only contains pointers to dynamically allocated objects. Otherwise, something similar to a `storage<char[N]>` storage (for different `N`s ofc, you can pick the right one at runtime according with a runtime size in this case) that owns and returns tightly packed _buffers_ where you can construct your types. From what I read, the latter is closer to what you're trying to achieve?

If I want to use `storage<void*>` and I know the size to dynamically allocate, how should I write code to register that pool? Could you please provide an example? Thanks a lot!

**Comment by skypjack** [comment]
Are all elements in the pool of the same size? Or do you want to allocate different buffers with different sizes for the same storage?

**Comment by hls333555** [comment]
> Are all elements in the pool of the same size? Or do you want to allocate different buffers with different sizes for the same storage?

If I understand correctly, `storage<void*>` represents a pool for certain component, so in this case, all elements in the pool have the same size due to being the same component, so could I have difference storage<void*> to represent different components?

**Comment by skypjack** [comment]
Yeah, sort of. Although I don't get why you want a `void *` component.
I mean, why not a bunch of storage types for different _sizes_, such as `storage<char[16]>`, `storage<char[32]>`, `storage<char[64]>`, and so on?
A `storage<void *>` makes me think more of a dynamic allocation, something you can achieve already with a `storage<std::unique_ptr<void, void(void *)>>` or similar.
A `storage<char[N]>` makes me think of placement new instead and therefore a more tightly packed storage.

**Comment by skypjack** [comment]
Oh, no, you can always create _named_ pools and have more storage instances of the same type. As in:
```cpp
auto position_storage = registry.storage<char[16]>("position"_hs);
auto position_storage = registry.storage<char[16]>("velocity"_hs);
```
