### ISSUE TITLE
wiki: Crash Course ECS: small additions

### ISSUE THREAD

**Issue by The5-1** [skypjack/entt#232]
I'd use this issue to gather small additions to the wiki.

Single component view´s getter does not require template parameters.
```
		auto viewPos = registry.view<Position>();
		auto pos& = viewPos.get(entity);

		auto viewVel = registry.view<const Velocity>();
		const auto& vel = viewVel.get(entity);
```

**Comment by skypjack** [comment]
Yeah. This isn't the first time someone asks for it. It's worth adding a note to the wiki.  
I'll do it as soon as I'm back home. Thanks.
