### ISSUE TITLE
resource_cache move ctor

### ISSUE THREAD

**Issue by NullBy7e** [skypjack/entt#233]
Hey,

With the latest src of entt (master) I'm getting an error in resource/cache.hpp on line 39 related to the default move constructor that's defined there:

`resource_cache(resource_cache &&) ENTT_NOEXCEPT = default;`

```
`1>entt/resource/cache.hpp(39): error : exception specification of explicitly defaulted move constructor does not match the calculated one
1>./managers/texture_manager.hpp(47): note: in instantiation of template class 'entt::resource_cache<sf::Texture>' requested here`
```

This is the line in texture_manager.hpp:
```
using texture_cache = entt::resource_cache<sf::Texture>;
texture_cache textures;
```

The issue no longer appears when I comment out the move ctor but I'm sure that it's there for a reason?

I'm compilling my project on x64 with CLANG/LLVM.

**Comment by skypjack** [comment]
Uhm... Have you exceptions turned on? Try to remove the `ENTT_NOEXCEPT` part only and let me know what happens, please.

**Comment by NullBy7e** [comment]
> Uhm... Have you exceptions turned on? Try to remove the `ENTT_NOEXCEPT` part only and let me know what happens, please.

Removed `ENTT_NOEXCEPT` and it compiles succesfully.

**Comment by NullBy7e** [comment]
Seems to be related to CLANG, it compiles with `ENTT_NOEXCEPT` using MSVC (Visual Studio 2017 (v141) toolset)

**Comment by skypjack** [comment]
What version of clang?

**Comment by NullBy7e** [comment]
> What version of clang?

Version 8.0.0 of LLVM which, I think, is clang 3.5.

**Comment by skypjack** [comment]
I think clang is right in this case. The exception specification from the `std::unordered_map` is incompatible with that of the cache actually.  
Good point. :+1:

**Comment by NullBy7e** [comment]
> I think clang is right in this case. The exception specification from the `std::unordered_map` is incompatible with that of the cache actually.
> Good point. 👍

Is that something that you can address by changing the code or should I just keep the NOEXCEPT commented out?

**Comment by ColinH** [comment]
The problem is that the cache marks its move-c'tor as `noexcept`. Its a problem because it invokes the move-c'tor from `std::unordered_map` which is however _not_ marked `noexcept`. The compiler is complaining about this discrepancy (don't want to call a non-`noexcept-`marked, i.e. potentially throwing, function from a `noexcept`-marked one). Once the cache's move-c'tor is no longer `noexcept` the warning or error should go away, so just a small change to EnTT.

**Comment by skypjack** [comment]
Yep, confirmed, a change to `EnTT` is required.  
You've to wait until I'm back home, then I'll do it directly upstream.

**Comment by NullBy7e** [comment]
Great! No rush, I've adjusted it locally in the src for the time being.

Outlook voor Android downloaden<https://aka.ms/ghei36>

________________________________
