### ISSUE TITLE
Sparse set vs. sparse map?

### ISSUE THREAD

**Issue by ColinH** [skypjack/entt#234]
Do I understand correctly that the `sparse_set` with two template parameters is a map from entities to something? Might it be suitable to rename the `sparse_set` with two template parameters to `sparse_map`?

**Comment by skypjack** [comment]
Historically, `EnTT` has a heavily modified version of a sparse set that doesn't fit well with the _canonical_ definition.  
In a sense, also the basic sparse set is a map (from the entity to the position) and the whole lib relies on this assumption. The derived class just extends the concept and maps an entity to a position plus an instance of a component (that occupies exactly the same position).

Is _map_ more appropriate a name? I don't know, the underlying logic is that of the sparse sets, targeted to the specific problem.  
I prefer to stick with a name that remembers me of its origin to be honest. Moreover it's an implementation detail with which users has almost no contacts, so I don't see big problems here.

---

As a side question, are you studying in details how EnTT works? :-)  
I see you pretty active here. If you have questions and want quick replies, you can also join the gitter channel. :+1:

**Comment by ColinH** [comment]
Yes, I'm looking at EnTT in-depth to understand exactly how it works :-)  I'll post small questions like this in gitter from now on.

**Comment by skypjack** [comment]
Not a problem. For me it's fine either here or in the gitter channel. I'm glad to know someone is looking into it btw. :wink:

**Comment by ColinH** [comment]
PS: Independent of the precise semantics of the `sparse_set` it seems to me that the relationship between `entt::sparse_set< Entity >` and `entt::sparse_set< Entity, Type >` is the same as between `std::(unordered_)set< Entity >` and `std::(unordered_)map< Entity, Type >` which made me suggest the name change...

**Comment by skypjack** [comment]
To be honest it's likely that I'll change these names soon.  
Before to leave I was working on this part to push sparse sets to a level where they could allow me to easily support shared components and to get rid of the _single instance_ currently stored in case of empty types.  
So stay tuned because this stuff is going to change soon. :+1:

**Comment by ColinH** [comment]
> In a sense, also the basic sparse set used as a base class is a map (from the entity to the position)

It took me a moment to see this in the code because `reverse` stores instances of `entity_type`, which leads one to assume that `reverse` contains Entities, rather than indices into `direct`.
