### ISSUE TITLE
Polymorphic components?

### ISSUE THREAD

**Issue by SoraKatadzuma** [skypjack/entt#239]
Is there a way to have polymorphic components, where a component can do something like:
```cpp
struct behaviour {
  virtual void print() {}
};

struct printer: public behaviour {
  void print() override {
    // Perform print action.
  }
};

// Later...
entt::registry registrar;
entt::entity e0 = registrar.create();
registrar.assign<printer>(e0);

// Even later...
registrar.view<behaviour>().each([](auto& component) {
  component.print();
});
```

I've tried this and it didn't work, and after reading the docs I'm not sure what the correct way to do this would be. I could use a bit of guidance to making this work. And I believe I understand why it doesn't work but I'd appreciate it if you could also explain why it doesn't.

**Comment by Kerndog73** [comment]
You could use `std::unique_ptr<behaviour>`.

**Comment by SoraKatadzuma** [comment]
I see, yes the `unique_ptr` approach worked nicely. I need polymorphism as described in my issue, because I plan to do scripting similar to Unity, where I need virtual functions that which can be overridden. But I thank you for your help 👍

**Comment by skypjack** [comment]
You can also use a single component and rely on type erasure techniques by mixing non-capturing lambdas and pointers to functions. More or less on the line of the _OOP in C_ book.  
This way you've **only** `behavior` as a component but different `print`s for different instances.

**Comment by SoraKatadzuma** [comment]
Mkay, I'll take that into consideration. It'll probably be an optimization later if it works into my design.
Thank you again for your help 😄

**Comment by skypjack** [comment]
You're welcome. Please, close the issue if you received a proper answer. :+1:  
Also, I invite you to join the gitter channel if you have other questions. There are smart people there that can help you.

**Comment by SoraKatadzuma** [comment]
Ah that'd be great!
