### ISSUE TITLE
Retrieve all active entities from the registry

### ISSUE THREAD

**Issue by mario-deluna** [skypjack/entt#24]
Correct me if im wrong, `std::vector<entity_type> available` and `std::vector<entity_type> entities`
are both private properties and there seems to be no class method in the registry to simply retrieve all active entities. 

I would really love to see a way to iterate over all entities. 

```
for(auto entity : registry.all())
{
    // something 
}
```

**Comment by skypjack** [comment]
The way you suggested requires the registry to expose `begin` and `end` member functions and it's a bit misleading from my point of view.  
However, [there exists something similar](https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L906):

```
registry.each([](auto entity) {
    // ...
});
```
It returns all the entities ever created.
Does it work for you?

Active entities (I think you mean `entities - available`) are expensive to find.  
It's faster usually to iterate all existing entities and filter out the ones you don't want.

**Comment by mario-deluna** [comment]
`each` works out perfectly. 

Thank you very much.

**Comment by skypjack** [comment]
Side note. I've updated `each` so that it returns only entities that are still in use. No longer destroyed ones, users should not be able to access them for several reasons.  
In general, `each` probably adheres strictly to your requirements now.
