### ISSUE TITLE
try_remove api method

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#244]
it's a bit trivial to implement in the user code, but it does reduce user code complexity when destroying optional tags and such without having to worry about wrapping with a "has" method.

```    
    template<typename Component>
    bool try_remove(const entity_type entity) {
        ENTT_ASSERT(valid(entity));
        if (has<Component>(ent)) {
            pool<Component>()->destroy(entity);
            return true;
        }
        return false;
    }
```

**Comment by skypjack** [comment]
[`reset<T>(entity)`](https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L1083) serves the same purpose.  
What's wrong with it?

**Comment by trashuj** [comment]
I like try_remove, it"s more consistent with the rest and easy to remember.
I +1 this

**Comment by pgruenbacher** [comment]
oh hm yea good point... I'll just use reset<T>(entity) which from a naming perspective does fine.
