### ISSUE TITLE
[MacOs] Compilation fail due to random <U+FEFF>

### ISSUE THREAD

**Issue by mhammerc** [skypjack/entt#247]
Hello! Using the single-header file, on line 994, there is a random `<U+FEFF>`. It makes compilation fail on latest MacOs as following:

https://github.com/skypjack/entt/blob/d4a64e93e03300a2b20a7fb9d11fae2f9290cc49/single_include/entt/entt.hpp#L994

```
/Users/mhammerc/Dev/deadlife/LE/misc/entt/entt.hpp:994:1: error: unknown type name '﻿'
<U+FEFF>#ifndef ENTT_ENTITY_REGISTRY_HPP
^
/Users/mhammerc/Dev/deadlife/LE/misc/entt/entt.hpp:994:4: error: expected unqualified-id
<U+FEFF>#ifndef ENTT_ENTITY_REGISTRY_HPP
        ^
/Users/mhammerc/Dev/deadlife/LE/misc/entt/entt.hpp:8080:2: error: #endif without #if
#endif // ENTT_ENTITY_ACTOR_HPP
 ^
/Users/mhammerc/Dev/deadlife/LE/misc/entt/entt.hpp:11521:9: warning: missing field 'base' initializer [-Wmissing-field-initializers]
        };
        ^
/Users/mhammerc/Dev/deadlife/LE/misc/entt/entt.hpp:9651:43: note: in instantiation of member function 'entt::internal::meta_node<unsigned long>::resolve' requested here
        node = internal::meta_info<Type>::resolve();
                                          ^
/Users/mhammerc/Dev/deadlife/LE/misc/entt/entt.hpp:10550:34: note: in instantiation of function template specialization 'entt::meta_any::meta_any<unsigned long &, void>' requested here
        return node->get(handle, index);
```

The whole compilation error isn't interesting, only the first error. Removing that random character fix the problem straight away!

**Comment by mhammerc** [comment]
Would be glad to make a PR for a quick fix, but you may be using tools to generate these files automatically. Note this is the latest `3.0.0` downloaded from Github releases, but it's the same on the latest file as shown above.

**Comment by skypjack** [comment]
Uhm... Actually I forgot to update it for the `v3`. Can you try to re-generate the file with [this script](https://github.com/skypjack/entt/blob/master/scripts/amalgamate.py) on your workstation to see if it works before I push the new one? I don't know from where that character popped out to be honest.

**Comment by Milerius** [comment]
Hey actually I think that we need to regenerate and strip that character manually, firstly I was thinking that was a bug from my computer when I see this character

**Comment by Milerius** [comment]
@mhammerc if you are from 42 or Epitech from France I'm reachable by mail: rmscastle@gmail.com for any question about this specific file.

**Comment by mhammerc** [comment]
I did not succeed to run Amalgate, because of this error :

```
Creating amalgamation:
 - processing "src/entt/entt.hpp"
Traceback (most recent call last):
  File "scripts/amalgamate.py", line 299, in <module>
    main()
  File "scripts/amalgamate.py", line 295, in main
    amalgamation.generate()
  File "scripts/amalgamate.py", line 94, in generate
    t = TranslationUnit(file_path, self, True)
  File "scripts/amalgamate.py", line 267, in __init__
    self._process()
  File "scripts/amalgamate.py", line 252, in _process
    self._process_includes()
  File "scripts/amalgamate.py", line 240, in _process_includes
    t = TranslationUnit(found_included_path, self.amalgamation, False)
  File "scripts/amalgamate.py", line 267, in __init__
    self._process()
  File "scripts/amalgamate.py", line 251, in _process
    self._process_pragma_once()
  File "scripts/amalgamate.py", line 203, in _process_pragma_once
    tmp_content += self.content[prev_end:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1318: ordinal not in range(128)
```

But I looked at `registry.hpp` file, and it seems the faulty character is there, even if we can not see it on Github (on both latest release 3.0.0 and master).

https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp

<img width="360" alt="image" src="https://user-images.githubusercontent.com/5982507/58111913-aca04f00-7bf2-11e9-95e9-3d5c364ec98e.png">

@Milerius Thanks! Why if I am from 42 and Epitech? (From 42 actually!)

**Comment by Milerius** [comment]
@skypjack seems like a spurious character

**Comment by mhammerc** [comment]
(just edited my previous comment)

**Comment by mhammerc** [comment]
It is actually a BOM character:

https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by Milerius** [comment]
Can you make a pull request and remove it ?

**Comment by skypjack** [comment]
Yeah, it would be great if you can pack a PR where you remove the character and generate the file.  
Otherwise I can do that as soon as I turn on my laptop.

**Comment by mhammerc** [comment]
Pull request created #248!

**Comment by skypjack** [comment]
Thank you very much. Really appreciated. :+1: :heart:
