### ISSUE TITLE
Dereferencing causes data corruption

### ISSUE THREAD

**Issue by mario-deluna** [skypjack/entt#25]
Hello there, this issue/bug might be completely my fault due to my lack of c++ knowledge so please excuse if that is the case.

I've started to run into an issue where sometimes entities in my case bullets where spawned at the wrong position. after digging into the issue I found that my player's transformation component (position, size, rotation) was sometimes, but not always, zero. 

I've built the following script to reproduce the issue:

```cpp
#include <glm/glm.hpp>

#include <entt/entity/registry.hpp>

using Entity = entt::DefaultRegistry::entity_type;

struct Transform {
    glm::vec3 origin;
    glm::vec3 size;
    glm::vec3 rotation;
    
    Transform(float x, float y, float width, float height, float angle = 0.0f) :
        origin(x, y, 0.0f), size(width, height, 0.0f), rotation(0.0f, 0.0f, angle)
    {}
};

struct Velocity {
    float x,y,z,w;
    
    Velocity(float x, float y, float z, float w) :
    x(x), y(y), z(z), w(w) {}
};

void update(entt::DefaultRegistry &registry, Entity main)
{
    auto &main_transform = registry.get<Transform>(main);
    
    auto child = registry.create();
    
    registry.assign<Transform>(child, 20.0f, 20.0f, 10.0f, 10.0f);
    registry.assign<Velocity>(child, 0.0f,  0.0f,  0.0f,  0.0f);
    
    if (main_transform.origin.x == 0.0f)
    {
        throw "Main tranform should still be 50.0";
    }
}

int main() {
    
    entt::DefaultRegistry registry;
    
    // create a main entity (player or whatever)
    Entity main = registry.create();
    registry.assign<Transform>(main, 50.0f, 50.0f, 100.0f, 100.0f);
    registry.assign<Velocity>(main, 0.0f,  0.0f,  0.0f,  0.0f);
    
    while(1) {
        update(registry, main);
    }
}
```

As you can see the transformation of the main entity gets at least for my understanding never modified. So the condition `if (main_transform.origin.x == 0.0f)` in the update method should never be reached, but it does. 

As soon as I don't dereference the main transform:
```
 auto main_transform = registry.get<Transform>(main);
```

The issue disappears.

Thanks in advance and merry christmas  :)

**Comment by skypjack** [comment]
What you are doing is more or less equivalent to this:
```
std::vector<int> vec;
vec.push_back(42);
auto &first = vec[0];
vec.push_back(3);
```
C++ doesn't guarantee that `first` is still valid after the second `push_back`. Roughly speaking, `vec` can reallocate internally and all the references are invalidated in this case.  
A call to `assign` does almost the same and has the same drawbacks.

`EnTT` gives guarantees when you work with iterators (it's better explained in the documentation). It's a kind of magic on how they access the internal data structures.  
The sole way to work around this would be to use paginated storage. It means a slightly change in the API and performance a bit ruined.  
I'm not that sure it's worth it.

As a rule of thumb, you shouldn't keep references to components around in any case.  
Accessing a component is usually fast enough and iterating entities is amazingly fast.  
Just _get_ the component when you need it.

**Comment by mario-deluna** [comment]
> As a rule of thumb, you shouldn't keep references to components around in any case.
Accessing a component is usually fast enough and iterating entities is amazingly fast.
Just get the component when you need it.

Im not 100% sure I understand, the `Transform` component reference is newly retrieved on every update and not stored. Only the the identifier to the main entity is stored. 

How would you structure this simple example? Im currently not seeing through how I could do this differently.

**Comment by skypjack** [comment]
And Merry Christmas, sorry!! :-)

I'm trying also to write down a few notes about `signal` to share with you.
Give me more time, for I'm out of home for a few days.

**Comment by mario-deluna** [comment]
Ah wait ok if I get it right the problem is that I call assign after I retrieved the reference right?

**Comment by skypjack** [comment]
The problem is that you are getting it before to assign the same component to another entity.  
I'm from mobile and I cannot try it. However it should work fine if you move the `get<Transform>` somewhere after the `assign<Transform>` within `update`.

**Comment by skypjack** [comment]
>Ah wait ok if I get it right the problem is that I call assign after I retrieved the reference right?

Exactly. Internally `EnTT` uses vectors and it undergoes their rules.  
See the example in my first answer.

**Comment by mario-deluna** [comment]
Great! Works perfectly. 

Thank you very much for your support! :)

**Comment by skypjack** [comment]
You are welcome. :-)
