### ISSUE TITLE
SceneGraph discussion

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#253]
I'm making this an issue since there's still no examples online that I've seen of 
EnTT scene graph implementation with parent-child transform dependencies and it'd be good to have a thread to refer to.

@vblanco20-1 i could use your input on this cause you keep mentioning how you've done it in gitter but gitter is awful for archive searching.

**Comment by pgruenbacher** [comment]
here's what I'm thinking

entities can have a single struct `Child { EntityType childId; } ` component.
any other entities that are children to the parent entity will get `Sibling { EntityType siblingId; }`

any transform changes would get a `TransformActive` tag added to the component.

no need to sort, just group all active components and step through parent->child->sibling->sibling etc...

**Comment by pgruenbacher** [comment]
though personally I still haven't found scene graph useful for anything other than for level organization so if I do implement it for bsf it's just gonna be hopefully kept simple.

**Comment by pgruenbacher** [comment]
i'm also thinking to not even worry about relative transforms. Just keep absolute transform component for each entity, and if wanting to edit the transform relative to the parent, just calculate the relative transform by using Inverse(childChild) * parentTransform. This may cause issues when tracking rotational changes though...

**Comment by vblanco20-1** [comment]
You need Parent, Child, Next Sibling, and Prev Sibling. All of the 4 at once. This could be on a SceneNode component, as i showed in the gitter. You need both siblings so you can attach and detach at O(1). With only forward sibling, detaching parent is a lot harder. Once you have that, a lot of "helper" functions can be implemented, such as IterateParents, IterateChildren, FindComponentinParent, etc

**Comment by skypjack** [comment]
What about moving the issue [here](https://github.com/skypjack/skypjack.github.io) instead?  
I was to write a new post about a different topic, but I could _explore_ this topic with some examples made with `EnTT`.

**Comment by pgruenbacher** [comment]
hm yea go ahead. I'll close this.

**Comment by skypjack** [comment]
I've just realized I cannot open issues to forks. :smile:  
I'm reopening this, so that I won't forget to write about it. I think I'll do it soon btw. :+1:

**Comment by skypjack** [comment]
I'm closing this issue because the first of two posts is ready.  
I've to review it to correct all the typos but I think I'll publish it during the next week. Shortly after it, I'll also publish a second post to go a bit deeper into the topic.  
Both the posts use `EnTT` to offer some examples for real world cases. I hope you'll like it. :wink:

**Comment by rockingdice** [comment]
@skypjack could you please share a link to the posts that you mentioned? I cannot find it :(

**Comment by skypjack** [comment]
ECS back and forth series [here](https://skypjack.github.io/) @rockingdice  👍

**Comment by eladm-ultrawis** [comment]
@skypjack forgive my lack of knowledge. I read your articles and trying to come up with proper scene graph implementation. I fail to understand why do transform objects have to be sorted such that parents appear before their children? I mean as far as I can tell, once I update a node, I must update all its descendants recursively. so what is the point in sorting?

Thanks.

**Comment by skypjack** [comment]
@eladm-ultrawis I don't remember all details of the article but I guess that it's because this way you have the parent already updated when you reach its children during iteration?
