### ISSUE TITLE
What is the "output_archive" in the doc?

### ISSUE THREAD

**Issue by linonetwo** [skypjack/entt#254]
In https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#snapshot-complete-vs-continuous there is an undefined "output_archive" type, what is it?

How to log the current state into stdout or a file?

**Comment by skypjack** [comment]
The `output_archive` can be of any type. The documentation contains also [the constraints](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#archives) for it.  
[Here](https://github.com/skypjack/entt/blob/master/test/snapshot/snapshot.cpp) is an example of use with `cereal` C++ instead. You can easily write the json it produces on a file or whatever.

Let me know if something is unclear.
