### ISSUE TITLE
Strong types for entity_type

### ISSUE THREAD

**Issue by FabienPean** [skypjack/entt#256]
Since the idea seemed to gain traction on gitter recently, I decided to open an issue since I was interested by this topic for a while.

Currently, the registry in entt is suited to work only with plain integer types as entity type. 

However, in the case where several registries are in use, the problem of passing an entity id on the wrong registry may become frequent as the usual typedef facility does not generate new types.

By enabling strong id types as entity types, the error would be caught directly in an IDE or at compile-time.

**Comment by skypjack** [comment]
>However, in the case where several registries are in use, the problem of passing an entity id on the wrong registry may become frequent as the usual typedef facility does not generate new types.
>
>By enabling strong id types as entity types, the error would be caught directly in an IDE or at compile-time.

This is true only if the underlying type is different, eg `uint32_t` for a registry and `uint16_t` for the other. Otherwise the strong type is the same for the two registries and you can still mix identifiers.  
Is this clear? I don't want to create false expectations.

**Comment by FabienPean** [comment]
I am not sure I understood. Here is a snippet of what I had in mind:

```cpp
#include<cstdint>
struct EntityX 
{
    explicit EntityX (std::uint64_t v) : x{v} {}
    std::uint64_t x;
};
struct EntityY
{
    explicit EntityY(std::uint64_t v) : x{v} {}
    std::uint64_t x;
};
template<typename T>
struct Registry {
    void get(T&& t) {}
};

using Reg1 = Registry<EntityX>;

int main() {
    Reg1 reg1;
    reg1.get(15UL);       //FAIL
    reg1.get(EntityX{2});
    reg1.get(EntityY{0});//FAIL
}
```

**Comment by skypjack** [comment]
Oh, ok, I didn't get you want to pass the strong type as template parameter directly to the registry. Sorry. It makes much more sense actually. Good point. :+1:

**Comment by FabienPean** [comment]
Isn't it doable as an opt-in feature? Like, by default keeping the specialization for std::uint64_t, and when a strong type is passed the user would need to provide the entt_traits<EntityX>.

**Comment by skypjack** [comment]
Not sure about it.

As an example, the sparse sets work with plain integers (entities) right now and it doesn't make sense to use strong types down there. However, unless the strong type as a conversion operator to the underlying type (that defeats a bit the purpose of being a strong type), the registry **must** know when it's working with a plain integer or a strong type so as to be able to extract the value to use.  
The other way around is to put an `if constexpr`'ed function to invoke each and every time we want the _value_. Unfortunately, this isn't enough yet. The views sometimes _compare_ the identifiers or work with them, therefore they must know with what they are working as well. And so on...

I don't know what's the effort required to turn identifiers to strong types to be honest. At a first glance, it's bigger than what it seems.

**Comment by skypjack** [comment]
Uhm... Probably with an explicit conversion operator and a comparison operator, the change won't be neither that breaking nor that big to do. I must experiment with it.  
Not sure if an explicit conversion operator is something meaningful at all for a boxed type btw, it looks tricky to me and it probably defeats the purpose.

**Comment by Kerndog73** [comment]
Could use an `enum` (similar to the way `std::byte` is defined). 

```C++
enum class EntityX : uint64_t {};
enum class EntityY : uint64_t {};
```

Conversion and comparison operators come for free. Also have `std::underlying_type_t` and `std::is_enum_v` if needed.

**Comment by skypjack** [comment]
This is interesting actually @Kerndog73 - what about @FabienPean ?

**Comment by FabienPean** [comment]
Nice, I did not know one could use an enum class this way. That seems to fit right 👍

**Comment by vblanco20-1** [comment]
The Enum thing would be good trickery. That would definitely work. The main goal is just to tag different registries with different types so if you use the wrong entityID then it wont compile.

**Comment by skypjack** [comment]
The only ugly thing with this is that `data` will return then an `enum class EntityX *`, that is a bit ugly.  
Btw being identifiers opaque handlers from the point of view of the user, it shouldn't be a problem at all.

**Comment by pgruenbacher** [comment]
@FabienPean the other thing to consider is to only really use one registry. I had once split out my code into multiple registries but since then I've merged all the logic into one registry because it keeps the api logic much simpler.

**Comment by FabienPean** [comment]
For sure using only one registry would simplify things and could be preferred in some scenarii, however this is overly restrictive as a general recommendation. I posted the issue since some people on gitter (e.g. @skypjack @vblanco20-1) were noticing benefits in using multiple registries.

**Comment by pgruenbacher** [comment]
for my benefit what were those benefits again? Encapsulation or perf. reasons?

**Comment by vblanco20-1** [comment]
> for my benefit what were those benefits again? Encapsulation or perf. reasons?

@pgruenbacher  both of them. You know Entt Groups are quite amazing for perf, but are heavily limited. A possibility is to have one registry for a specific subsystem and you have everything grouped in that one, getting all the gains.

**Comment by pgruenbacher** [comment]
oh so like level 1 / level 2 or region 1 / region 2. Ok well that's fine and makes sense. I had originally done like NavigationRegistry, AgentRegistry, ObstacleRegistry but I don't think there were any gains from that other than encapsulation.

**Comment by ArnCarveris** [comment]
`using RegistryX = entt::basic_registry<entt::entity, struct tag_x_t>;`
`using RegistryY= entt::basic_registry<entt::entity, struct tag_y_t>;`
`using EntityX = RegistryX::entity_type;`
`using EntityY = RegistryY::entity_type;`

@skypjack, no?

**Comment by skypjack** [comment]
@ArnCarveris they are still convertible to each other, I think it's as error prone as it is today. Am I wrong?

**Comment by ArnCarveris** [comment]
```cpp
template<typename Entity, typename... Tags>
struct entity_handle
{
  using registry_type =  entt::basic_registry<Entity, Tags...>;

  Entity id{};
};
```

@skypjack, no?

**Comment by ArnCarveris** [comment]
In https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L43:
```cpp
template<typename Entity, typename... Tags>
class basic_registry {
    using context_family = family<struct internal_registry_context_family, Tags...>;
    using component_family = family<struct internal_registry_component_family, Tags...>;
```

@skypjack, no?

**Comment by skypjack** [comment]
@ArnCarveris this addresses another aspect, but I'm not that sure it's the best thing to do.  
If it was allowed, type `T` won't have anymore the same identifier between different registries.  
Why is it a benefit from your point of view?

**Comment by OvermindDL1** [comment]
I would love being able to tag the types!  Would keep from mixing up my game and GUI entities for example.

**Comment by skypjack** [comment]
@OvermindDL1 Indeed, I agree that this would be useful.  
I liked in particular the proposal of @Kerndog73 to use something on the line of `std::byte`, that is like `enum class gui_entity: std::uint64_t {};`.  
What do you think about? Any comment or good argument against it?

**Comment by OvermindDL1** [comment]
I'm used to using template tags just because of the 'ol days, but whatever works to catch my own mistakes I'm for.  ^.^

**Comment by ArnCarveris** [comment]
> @ArnCarveris this addresses another aspect, but I'm not that sure it's the best thing to do.
> If it was allowed, type `T` won't have anymore the same identifier between different registries.
> Why is it a benefit from your point of view?

@skypjack any downside of that?

**Comment by skypjack** [comment]
@ArnCarveris good question. I don't see neither benefits nor drawbacks at a first glance. :smile:

**Comment by ArnCarveris** [comment]
```cpp
template<typename Entity>
class basic_registry {
    using context_family = family<struct internal_registry_context_family, Entity>;
    using component_family = family<struct internal_registry_component_family, Entity>;
```

and like @Kerndog73 said:
```cpp
enum class EntityX : uint64_t {};
enum class EntityY : uint64_t {};
```

The is only one benefit:
`regX.type<CompAForX>() - 1`
`regX.type<CompBForX>() - 2`
`regY.type<CompAForY>() - 1`
`regY.type<CompBForY>() - 2`

But currenly we will get this:
`regX.type<CompAForX>() - 1`
`regX.type<CompBForX>() - 2`
`regY.type<CompAForY>() - 3`
`regY.type<CompBForY>() - 4`

As you see it saves some space.

@skypjack any drawback of this?

**Comment by ArnCarveris** [comment]
As a side effect, it gives control of type ids.

**Comment by ArnCarveris** [comment]
So entity and type ids are totally incompatible, for me, it also one more benefit so we can add some guards to prevent users from mixing.

**Comment by skypjack** [comment]
Being entity identifiers stored in contiguous arrays within the pools, I think `enum class`es are a good way to go according to the reasons explained [here](https://stackoverflow.com/a/44508267/4987285). So thanks for pointing it out @Kerndog73 . :+1:

**Comment by skypjack** [comment]
If someone has the time and is willing to review this, `entt::entity` from branch `wip` is finally an enum class.  
I've added also the macro `ENTT_ENTITY_TYPE` to simplify the definition of new types of identifiers. It creates the enum class as well as a `to_integer` function to use to cast an identifier to its underlying type. You can use it as:
```
ENTT_ENTITY_TYPE(my_entity, std::uint32_t)
```
I've yet to update the documentation, so feel free to use this thread for any question. I'll merge everything on `master` most likely during the week, unless something terribly wrong pops out in the meantime.

**Comment by Kerndog73** [comment]
@skypjack You define `traits_type` as `entt_traits<std::underlying_type_t<Entity>>`. This breaks existing code that uses `basic_registry` (instead of `registry`). I'm not sure how I feel about this. Should plain integers continue to be valid entity types?

I don't really like the `ENTT_ENTITY_TYPE` macro. The `to_integer` function could be a template (note that using `std::underlying_type_t` for SFINAE is [UB until C++20](https://en.cppreference.com/w/cpp/types/underlying_type) so you'll have to use `std::is_enum_v` if you decide to go down that route). Defining the enum without the macro is shorter and IMHO cleaner. 

You might want add a `static_assert` before the definition of `traits_type` to deal with the aforementioned UB. It's UB whether whether we get a compilation error when an enum isn't used.

An alternative implementation could be to specialize `entt_traits` for enums and define `to_integer` there. That way, plain integers continue to be valid, the library doesn't assume the use of enums everywhere and the user could specialize `entt_traits` for their own strong integer type (though I'm not sure why you would want to do that).

Now that I've thought about it some more, I think forcing the use of enums isn't such a bad thing so specializing `entt_traits` for enums might not be the way to go. Sure, it's a breaking change but it's not breaking much and the fix is minimal.

**Comment by skypjack** [comment]
@Kerndog73 

I wouldn't care much of the fact that it's a breaking change tbh. It's easy to _solve_ and consistency is to prefer over a special case just because of backward compatibility.

The _problem_ of a general purpose `to_integer` that works with all the enum classes is exactly that it works with all the enum classes, while I'd prefer to limit it to the types that are actually introduced for entity identifiers.  
Kind of `std::to_integer` that works only with `std::byte`.

**Comment by Kerndog73** [comment]
@skypjack 

`std::to_integer` is a public interface. Converting an entity to an integer is an implementation detail. `to_integer` should only ever be used internally. Could you give a specific example of when a limited `to_integer` would be better than a generic `to_integer`? I can think of one unlikely case:

```C++
ENTT_ENTITY_TYPE(GuiEntity, uint32_t);

enum class Dir {
  up, right, down, left
};

entt::basic_registry<GuiEntity> gui; // ok
entt::basic_registry<Dir> dir; // oopsie! No matching call for to_integer
```

I don't see how that could ever happen since the user would probably create a type alias right after the definition of the entity. I still think that defining the enum directly is cleaner but I won't hold a grudge!  😉

**Comment by skypjack** [comment]
Ahahahah... No, well, you know, I like to discuss things and often I followed the advices from people like you.  
To be honest I don't think `to_integer` is merely an implementation detail. As an example, if you develop your own serialization system, it could be useful to convert entities to integers somehow.

**Comment by Kerndog73** [comment]
@skypjack I hadn’t thought about serialisation. It’s fine the way it is. Keep the macro.
