### ISSUE TITLE
VS2019 cannot compile correctly this simple snippet

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#257]
```
#include <entt/entt.hpp>

struct vec3 {
    float x;
    float y;
    float z;

    vec3(float x, float y, float z) :x(x), y(y), z(z) {};
};

struct Position {
    vec3 pos;
};

int main(int argc, char* args[]) {

    entt::registry reg;
    auto e = reg.create();
    reg.assign<Position>(e, vec3(1, 2, 3));


    return 0;
}
```
Env: win64 msvc from VS 2019. Error excerpt:

>delegate.hpp(118,1): error C2593:  'operator +' is ambiguous
delegate.hpp(118,1): message :  could be 'built-in C++ operator+(entt::delegate<void (entt::basic_registry<entt::entity> &,Entity)>::connect::<lambda_1>::<lambda_typedef_cdecl>)'

---

Thanks to @The5-1 for pointing this out on gitter.

**Comment by The5-1** [comment]
Happenes in VS Community 2019 using `platform toolset VS 2019 v142`.
Compiles just fine when switching back to `platform toolset VS 2017 v141`.

**Comment by skypjack** [comment]
Can you try to remove the `+` in front of the lambdas at lines 110 and 121 (file `delegate.hpp`), then recompile your snippet?  
If I remember it right, this isn't the first time that forcing explicitly a conversion for a lambda makes VS to complain.

**Comment by The5-1** [comment]
Indeed, removing the `+` makes it compile even for VS 2019.

**Comment by The5-1** [comment]
MS may have the issue fixed in the next release:
https://developercommunity.visualstudio.com/content/problem/566686/conversion-of-lambda-to-function-pointer-via-opera.html

**Comment by skypjack** [comment]
Well, we can still remove the `+` as a workaround in the meantime. It's not strictly necessary.

**Comment by skypjack** [comment]
@The5-1 branch `wip` should work fine for you. Can you confirm it?

**Comment by The5-1** [comment]
Confirmed, `wip` now works fine under VS 2019.
