### ISSUE TITLE
partition functionality

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#262]
related to https://github.com/GameFoundry/bsf/issues/339 in that it would be useful to replicate http://www.cplusplus.com/reference/algorithm/partition/ api logic. Specifically in the light rendering portion of bsf in which the directional lights are partitioned away. https://github.com/GameFoundry/bsf/blob/b36bf34e23b0c53d4be471dc25865ebb7d044d83/Source/Plugins/bsfRenderBeast/BsRendererLight.cpp#L223

**Comment by pgruenbacher** [comment]
like this?

```
    template<typename Compare>
    size_type partition(Compare compare) {
        size_type num = 0;
        int first = -1;
        auto size = instances.size();
        for (size_type i = 0; i < size; ++i) {
            if(compare(instances[i])) {
                first = i;
                break;
            } else
                ++num;
            }

        if (first != -1) {
            for(size_type i = first + 1; i < size; ++i) {
                if(!compare(instances[i])) {
                    std::swap(instances[i], instances[first]);
                    underlying_type::swap(i, first);
                    ++num;
                }
            }
        }

        return num;
    }
```

are we worried appending utility functions like this increasing compile time?

**Comment by skypjack** [comment]
Do you mean to partition the elements in a pool?  
Doesn't using a component for that work? This is quite common with an ECS.

**Comment by pgruenbacher** [comment]
oh you mean just a tag component and using a group to ensure that the instance data is partitioned correctly? Yes it could work that way actually.... 
your post is a good example of  this https://skypjack.github.io/2019-04-12-entt-tips-and-tricks-part-1/ so that's the better way of doing this.
