### ISSUE TITLE
Iterator for resource_cache

### ISSUE THREAD

**Issue by The5-1** [skypjack/entt#275]
It is currently not possible to iterate all resources of a resource_cache.
A usecase would be to iterate your shader asset cache and call a reload() function on all of them.

**Comment by skypjack** [comment]
May I ask you how do you envision it from the point of view of the user?

**Comment by The5-1** [comment]
I intended to use it like so:
```Cpp
for(Shader s: shaderCache){
   s->reload(); 
}```

Or, since we already have `.size()`:

```Cpp
for (int i = 0; i < shaderCache.size(); i++) {
    shaderCache.at(i)->reload();
}```

**Comment by The5-1** [comment]
added PR #276

**Comment by skypjack** [comment]
It's not a matter of being simpler, the fact is that without the `each` member function we should declare custom iterators to use with `begin`/`end`. This way instead we have less code to maintain. Probably this is the whole point of his suggestion. Does it make sense?

**Comment by The5-1** [comment]
I'm always in favor of KISS ;)
