### ISSUE TITLE
single header has weird character in 3.0.0 release

### ISSUE THREAD

**Issue by markand** [skypjack/entt#280]
Hello,

I don't know if something messed up the creation of the amalgamation but when downloading the 3.0.0 release and trying to compile a file that includes the single_include/entt/entt.hpp we have this error:

```
./entt-3.0.0/single_include/entt/entt.hpp:994:1: error: stray '\357' in program
 [m▒▒#ifndef ENTT_ENTITY_REGISTRY_HPP
```

And looking with vim I have the following strange character:

```
  993 // #include "registry.hpp"
  994 <feff>#ifndef ENTT_ENTITY_REGISTRY_HPP
  995 #define ENTT_ENTITY_REGISTRY_HPP
```

**Comment by Milerius** [comment]
I'm sure this one was fixed. @skypjack  ?

**Comment by Kerndog73** [comment]
It was fixed. See #247

**Comment by skypjack** [comment]
Indeed, this is a duplicate. You can either close this issue and use `master` or wait for v3.1 and leave this open if you prefer. In the latter case, I'll close the issue as soon as v3.1 is out.

**Comment by skypjack** [comment]
No feedback, good feedback. I'm closing the issue because it's already solved on `master` since a couple of months ago. Let me know if you've any other doubt. Thanks.

**Comment by markand** [comment]
Sorry for the noise. I should have checked master before asking but anyway don't you think it should be better to release at least a version 3.0.1 which contains the fixed file?
