### ISSUE TITLE
Signals with reference payload

### ISSUE THREAD

**Issue by BrodyHiggerson** [skypjack/entt#289]
This is an example of a situation I was in (obviously made more project-agnostic for this example) - I wanted to react to the construction of a component but perform modifications using some other object. In this situation, I couldn't use a member function on the object for API design reasons, but still needed an instance of that object in the callback.

Because I knew it couldn't be nullptr in this situation, I wanted to pass the payload by reference, but could not.
```
struct AComponent
{
	int32_t someData;
}

class SomeClass
{
	
}

// We know 'object' can't be null, but passing by pointer doesn't communicate this
void OnACreated(SomeClass* object, entt::registry& registry, auto entity, AComponent& component)
{
	
}

void InitHooks(entt::registry& registry, SomeClass& object);
{
	registry.on_construct<AComponent>().connect<&OnACreated>(&object);
}
```

**Comment by skypjack** [comment]
I think the instance (or value) should be passed both to the `connect` and to the callback by reference.  
In no case a null pointer makes sense.

This is a slightly breaking change but a _sane_ one from my point of view. :+1:

**Comment by skypjack** [comment]
On `wip`. If everything works fine, I'll merge it directly on `master`.
I updated also the `connect` and `disconnect` functions, so that they work with references as well.
