### ISSUE TITLE
VS2017 parsing issue

### ISSUE THREAD

**Issue by mario-deluna** [skypjack/entt#29]
Today is a busy day, I kind of feel sorry opening another issue.

I'm also running into an Issue with VS2017, until know I've been building with gcc and XCode. I've spent the last few days fixing issues to be able to run my application on WIndows. The last issue I was not able to resolve looks like a parsing issue in the `view.hpp`.

It's weird because I can see that the `entt` tests run successfully on the CI Service with VS.

It seems to be only one line VS struggles with inside the `reset` method.
```cpp
void reset() {
    using accumulator_type = size_type[];
    auto probe = [this](auto sz, auto &pool) { return pool.size() < sz ? (view = &pool, pool.size()) : sz; };
    size_type sz = std::max({ std::get<pool_type<Component> &>(pools).size()... }) + std::size_t{1};  // This line here.
    accumulator_type accumulator = { sz, (sz = probe(sz, std::get<pool_type<Component> &>(pools)))... };
        (void)accumulator;
}
````

This is line 517:
```cpp
size_type sz = std::max({ std::get<pool_type<Component> &>(pools).size()... }) + std::size_t{1};
```

Here is the error output:
```
/src\entt\entity\view.hpp(517): error C2062: type 'unknown-type' unexpected
/src\entt\entity\view.hpp(517): error C2143: syntax error: missing ';' before '{'
/src\entt\entity\view.hpp(517): error C2143: syntax error: missing ')' before ';'
/src\entt\entity\view.hpp(517): error C3520: 'Component': parameter pack must be expanded in this context
/src\entt\entity\view.hpp(517): error C2228: left of '.size' must have class/struct/union
/src\entt\entity\view.hpp(517): error C2143: syntax error: missing ';' before '...'
/src\entt\entity\view.hpp(517): error C2059: syntax error: '...'
/src\entt\entity\view.hpp(517): error C2059: syntax error: ')'
/src\entt\entity\view.hpp(517): error C2059: syntax error: '>'
/src\entt\entity\view.hpp(517): error C2143: syntax error: missing ';' before '{'
/src\entt\entity\view.hpp(517): error C3520: 'Component': parameter pack must be expanded in this context
/src\entt\entity\view.hpp(517): error C2228: left of '.size' must have class/struct/union
/src\entt\entity\view.hpp(517): error C2059: syntax error: '...'
/src\entt\entity\view.hpp(517): error C2059: syntax error: ')'
/src\entt\entity\view.hpp(517): error C2059: syntax error: ':'
/src\entt\entity\view.hpp(517): error C2143: syntax error: missing ';' before '{'
/src\entt\entity\view.hpp(517): error C2143: syntax error: missing ';' before '}'
```

Thanks in Advance.
PS: I love the signal stuff, I've been able to implement it :)

**Comment by skypjack** [comment]
Did you see #26?  
It seems that VS2017 gets in trouble if you turn on the Conformance mode. Is this the case?  
I'm asking just to eliminate an option.

**Comment by mario-deluna** [comment]
I don't use VS very often, that option seems to be missing, or am I missing something?

![properties](https://user-images.githubusercontent.com/956212/34584655-e81900e0-f19c-11e7-8407-2bb7c3f697cb.png)

**Comment by skypjack** [comment]
I don't use VS at all!! :-D
@Djuego can you help us?

**Comment by skypjack** [comment]
@mario-deluna Meanwhile, can you create a minimal example to reproduce the error?
This way I can add it to the test suite and have a try with appveyor.
Unless I don't know how to help you, for unfortunately I don't know how to reproduce the error so far.

**Comment by mario-deluna** [comment]
Hmm, I was able to run the tests with VS2017. So I guess the issue has to be related to how I generate the `.sln` file with cmake, or I messed something up in the code. It runs completely fine on mac. 

I will continue digging into this and keep you updated I have this is somehow related to entt in the end.

**Comment by skypjack** [comment]
Ok, good, thank you.
Please, keep updated the issue. I'm closing it in a week in case of no feedbacks from you.
Can it work for you?

**Comment by mario-deluna** [comment]
I just solved it, but i honestly don't understand it. at all... 

Somehow changing the order of the header file includes in SpriteDrawer solved the issue for me. I really don't get it. They are currently not connected at all... I guess I need some sleep.

Thanks. :)
