### ISSUE TITLE
Compiler specific undefined behavior with anonymous namespaces

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#292]
Using components and delegates in anonymous namespace across translation units results in undefined behavior. But only in LLVM and only with certain compiler flags. And only declared in anonymous namespaces, declaring with the static keyword still works.

(This bug has taken 3 days to catch. It may seem obvious but, having tested it in every compiler up to then there's no reason to suspect it and of course when it's time to test a release build for my target platform (android) the app crashes in an untraceable way, multiply that with needing to reupload a new apk each time and development hell ensues.)

Contrived example:

a.cpp:
```
namespace {
    struct MyItem{ std::string value; };
}
void add_item(entity e, std::string const& v) { registry.assign<MyItem>(e, v); }
std::string const& check_item(entity e) { return registry.get<MyItem>(e).value; }
```
b.cpp:
```
auto const e { registry.create() };
add_item(e, "hello");
std::cout << check_item(e) << "\n";
```

The above will work in all builds and compilers, until it doesn't. So, never do this!

**Comment by skypjack** [comment]
I'm not sure I get what you expect from me.  
Is there a fix for this or are you asking me to put a note somewhere in the doc?

**Comment by huwpascoe** [comment]
Don't know. I guess this is is a wiki footnote thing unless there are some magical template traits that can prevent it? I know it's an invalid issue but, just figured it should be known!

**Comment by skypjack** [comment]
Uhm... Wait, if I appeared rude, I didn't want to do so. Sorry.  
I was trying to figure out if you were also aware of a workaround to avoid it or if a note somewhere would have helped other users.  
I've never hit this problem, so I don't even know what are the side effects. :)

**Comment by huwpascoe** [comment]
I didn't think of your response as rude. : ) Hmm..I guess the only way to put it is information was lost. registry.get<T> returns a component, but it contains garbage data instead of what was assigned. It's such a weird state, I wonder if it could count as a compiler bug!
