### ISSUE TITLE
Signal connections lost

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#295]
[Possibly related to #292]
Started randomly occuring in MSVC after an update today, signals lose connection to callbacks. In this latest case, the build was broken simply by adding an empty *.cpp file!

By lots of modifications and output logging I've managed to find *something*. Consider the following:
```
dispatch.sink<events::EVENT_A>().connect<&MyClass::handle_EVENT_A>(*this);
dispatch.sink<events::EVENT_B>().connect<&MyClass::handle_EVENT_B>(*this);
dispatch.sink<events::EVENT_C>().connect<&MyClass::handle_EVENT_C>(*this);
dispatch.sink<events::EVENT_D>().connect<&MyClass::handle_EVENT_D>(*this);
...
dispatch.enqueue<events::EVENT_A>(...);
```

Here is what I've been able to gather. A sigh<T> is instanced when it's first called, and following calls are addressed to the same instance. When working as expected, each EVENT_* gets it's own instance with unique memory address. But then I add a blank *.cpp to the project and rebuild. The behavior is very different:

sigh<EVENT_A> is instanced at location 18f8d239e58, and connected to a method. But then EVENT_B replaces it. Then EVENT_C, and finally EVENT_H now takes on the identity of 18f8d239e58.

Finally at the end when EVENT_A is enqued, the original address is forgotten and a new sigh for EVENT_A is instanced at 18f90876b58 and published, but with nothing connected the events are lost.

```
NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_A const & __ptr64)>>(18f8d239e58)
CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_A const & __ptr64)> * __ptr64>(18f8d239e58) TO void (__cdecl MyClass::*)(struct events::EVENT_A const & __ptr64) __ptr64

CONNECT sigh<class entt::sigh<void __cdecl(class events::EVENT_B const & __ptr64)> * __ptr64>(18f8d239e58) TO void (__cdecl MyClass::*)(class events::EVENT_B const & __ptr64) __ptr64

CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_C const & __ptr64)> * __ptr64>(18f8d239e58) TO void (__cdecl MyClass::*)(struct events::EVENT_C const & __ptr64) __ptr64

NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_D const & __ptr64)>>(18f8d2481f8)
CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_D const & __ptr64)> * __ptr64>(18f8d2481f8) TO void (__cdecl MyClass::*)(struct events::EVENT_D const & __ptr64) __ptr64

NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_E const & __ptr64)>>(18f8d245e98)
CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_E const & __ptr64)> * __ptr64>(18f8d245e98) TO void (__cdecl MyClass::*)(struct events::EVENT_E const & __ptr64) __ptr64

NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_F const & __ptr64)>>(18f8d23ac88)
CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_F const & __ptr64)> * __ptr64>(18f8d23ac88) TO void (__cdecl MyClass::*)(struct events::EVENT_F const & __ptr64) __ptr64

NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_G const & __ptr64)>>(18f8d263d08)
CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_G const & __ptr64)> * __ptr64>(18f8d263d08) TO void (__cdecl MyClass::*)(struct events::EVENT_G const & __ptr64) __ptr64

CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_H const & __ptr64)> * __ptr64>(18f8d239e58) TO void (__cdecl MyClass::*)(struct events::EVENT_H const & __ptr64) __ptr64

NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_J const & __ptr64)>>(18f908784c8)
CONNECT sigh<class entt::sigh<void __cdecl(struct events::EVENT_J const & __ptr64)> * __ptr64>(18f908784c8) TO void (__cdecl MyClass::*)(struct events::EVENT_J const & __ptr64) __ptr64

NEW sigh<class entt::sink<void __cdecl(struct events::EVENT_A const & __ptr64)>>(18f90876b58)
ENQUEUE class entt::sigh<void __cdecl(struct events::EVENT_A const & __ptr64)>>(18f90876b58)
```
I don't have the ability to reproduce the problem on an empty project yet, so unfortunately I currently don't have any code I can share.

**Comment by skypjack** [comment]
>Started randomly occuring in MSVC after an update today

Are you using VS2019?

**Comment by huwpascoe** [comment]
VS2019, source is directly in project

**Comment by skypjack** [comment]
Ok. I guess VS2019, platform Win64, right?

**Comment by huwpascoe** [comment]
I'm not sure how but it's working again, I can't reproduce it. Maybe it was a build cache thing?!

**Comment by skypjack** [comment]
It's hard to say, but it seems there is a new issue with VS2019 - see #291 for more details.  
I can't do much for that but I found a workaround at least and used it also in the tests.

**Comment by huwpascoe** [comment]
Well it seems to be behaving now, whatever VS's problem was.

**Comment by skypjack** [comment]
I'm glad you solved it at least. :-)
