### ISSUE TITLE
create actor from existing id

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#296]
it'd be nice to be able to make actors from an existing id and reg.
i find actors more useful when using stomp now cause tracking two different registries can mess up the function signatures in some places.

    explicit basic_actor(registry_type &ref, entity_type id)
        : reg{&ref}, entt{id}
    {}

**Comment by skypjack** [comment]
What does it mean that it can _mess up the function signatures_?

**Comment by pgruenbacher** [comment]
eh ignore that phrase. i think just being able to make actors from existing id is good enough reason.
