### ISSUE TITLE
VS2017 15.5.3 compilation error when using views (C++17)

### ISSUE THREAD

**Issue by reworks** [skypjack/entt#30]
Getting a compilation error when using views with entt (commit 9761b6e) in sparse_set.hpp

Error	C2664	'void std::swap(std::exception_ptr &,std::exception_ptr &) noexcept': cannot convert argument 1 from '<COMPONENT_NAME>' to 'std::exception_ptr &' at sparse_set.hpp line 621
with <COMPONENT_NAME> the name of a component class.

entt::Entity is just
`using Entity = std::uint32_t`
one line above
`using DefaultRegistry = Registry<std::uint32_t>;`
in registery.hpp
(unless this is source of issue?)

Full output: https://pastebin.com/ViUaP9u3

**Comment by skypjack** [comment]
It's not that easy to investigate an issue that involves your components and for which I don't have a minimal example to reproduce the error.

Can you provide it?
Otherwise I must consider it a client error.

The way you wrote it, the issue is invalid and I'm closing it in a few hours.
I'm sorry.

**Comment by skypjack** [comment]
Honestly, look at this:

> error C2664: 'void std::swap(std::exception_ptr &,std::exception_ptr &) noexcept': cannot convert argument 1 from 're::TransformComponent' to 'std::exception_ptr &'

I'm not that sure why it's trying to use  `std::swap(std::exception_ptr &,std::exception_ptr &)` instead of `std::swap(TransformComponent &, TransformComponent &)`...
Have you tried to compile your code with GCC or clang too?

**Comment by skypjack** [comment]
Got it. Look here: http://en.cppreference.com/w/cpp/algorithm/swap

From the error, we see that you are trying to use the `noexcept` version of `std::swap`:

>template< class T >
void swap( T& a, T& b ) noexcept(/* ... */);

The link above says that since C++17:

>This overload does not participate in overload resolution unless std::is_move_constructible_v<T> && std::is_move_assignable_v<T> is true

Is your `TransformComponent` move assignable and move constructible?
I'm tempted to say no. Can you paste here its definition?
It looks definitely an error in your code after all.

**Comment by reworks** [comment]
Woops. I fixed it. Thanks for the help.

Sorry for the bother.

**Comment by skypjack** [comment]
You're welcome.
