### ISSUE TITLE
meta_any objects holding a value cannot be modified by meta functions

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#301]
```
#include <entt/meta/meta.hpp>
#include <entt/entt.hpp>

struct blah {
    int value{0};
};

blah create_blah() { return blah{}; }

void modify_blah(blah &blah_reference) { blah_reference.value = 10; }

auto blah_factory = entt::reflect<blah>("blah"_hs).ctor<&create_blah>().func<&modify_blah>("modify_blah"_hs);

int main() {
    auto blah_meta_type = entt::resolve("blah"_hs);
    auto new_blah = blah_meta_type.ctor().invoke();
    auto modify_blah_meta_func = blah_meta_type.func("modify_blah"_hs);
    modify_blah_meta_func.invoke({}, new_blah);
    assert(new_blah.cast<blah>().value == 10);
    return 0;
}
```

Request is to make this assertion pass.

Another possibility to make this pass would be allowing the following:
```
#include <entt/meta/meta.hpp>
#include <entt/entt.hpp>

struct blah {
    int value{0};
};

blah create_blah(){ return blah{}; }

void modify_blah(blah *blah_pointer) { blah_pointer->value = 10; }

auto blah_factory = entt::reflect<blah>("blah"_hs).ctor<&create_blah>().func<&modify_blah>("modify_blah"_hs);

int main() {
    auto blah_meta_type = entt::resolve("blah"_hs);
    auto new_blah = blah_meta_type.ctor().invoke();
    auto modify_blah_meta_func = blah_meta_type.func("modify_blah"_hs);
    modify_blah_meta_func.invoke(new_blah);
    assert(new_blah.cast<blah>().value == 10);
    return 0;
}
```
That is, static functions taking a pointer to the type underlying the meta type are treated as methods by the meta system.

**Comment by skypjack** [comment]
This would be straightforward if `meta_handle` allowed to cast or convert the underlying instance.  
In this case, we could construct handles for actual objects and concert `meta_any`s to `meta_handle`s at the call site. It won't make a copy of the value and therefore the _original_ instance would be brought around till the `invoke`.

**Comment by skypjack** [comment]
I've probably found a smart way to do this without having to modify the whole codebase.  
With a few changes to the `meta_any` and `meta_handle` classes so as to enforce aliasing on the input values, this should come almost for free.
I've already wrote the necessary code but I've still to test it. If everything works as expected, it will land on `master` during the week. :+1:

**Comment by skypjack** [comment]
Branch `wip` contains what is needed to support this. May I ask you to verify that it works as expected?

**Comment by Lawrencemm** [comment]
:+1: :+1: Thanks!
