### ISSUE TITLE
Warning using Visual Studio 2017 "hides class member"

### ISSUE THREAD

**Issue by roig** [skypjack/entt#306]
https://github.com/skypjack/entt/blob/0e07482e26b28f6f9d4dc275adf4c1c610b4f16a/src/entt/entity/registry.hpp#L559

Hello!
`auto e = registry.create();`
When I use the above function I always get the warning:
`warning C4458: declaration of 'entities' hides class member`

Maybe the variable name should be changed to avoid it.

**Comment by skypjack** [comment]
Thanks for reporting this. I'll change it to avoid annoying warnings.
