### ISSUE TITLE
would be ideal if other registry argument was const reference. 

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#308]
https://github.com/skypjack/entt/blob/454f072f13e263aed7bb4660aa8ef6211d84cfff/src/entt/entity/registry.hpp#L1629

idk if that's an issue if source registry == destination registry. maybe not, just separate const-type references to the same registry seems fine.

**Comment by skypjack** [comment]
It makes perfectly sense actually. There is no reason apparently for which it shouldn't be const. I'll try it. :+1:

**Comment by pgruenbacher** [comment]
Thanks
