### ISSUE TITLE
[Request] Retrieve multiple components at once from entity.

### ISSUE THREAD

**Issue by reworks** [skypjack/entt#31]
Hi,
I was wondering if a method like 
`registery.get<ComponentA, ComponentB>(entity);`
could be implemented?

The idea being you can retrieve a set of components from an entity instead of just one.
Something like:

```
template<typename ... Components>
std::tuple<Components...> get(std::uint32_t entity)
{
    return std::make_tuple<Components...>(/*get entity components*/);
}
```

Unless this can be done already with views? But I didn't see a way to get a view of only one entity.

**Comment by skypjack** [comment]
It can be implemented, but it won't be in the registry.
The policy so far has been _less is better_.
Moreover the prototype is far from the API of the rest of the library and we should find at least something more adherent.

You can implement it as an external method with something like this:

```
template<typename... T>
auto multi(entt::Registry &reg, entt::Registry::entity_type entity) {
	return std::make_tuple(reg.get<T>(entity)...);
}
```

Or as an extension of the registry itself, something like this:

```
struct MyRegistry: entt::Registry {
	template<typename... T>
    auto multi(entt::Registry::entity_type entity) {
    	return std::make_tuple(Registry::get<T>(entity)...);
    }
};
```

Let's see for 24h if it's a common request and it's worth putting something similar in the registry. Otherwise I'm closing the issue in a day.

**Comment by skypjack** [comment]
Note also that, as a rule of thumb, if we add something similar to the registry, views should be updated as well for consistency.
`EnTT` has a strictly defined API on which I spent a lot of time and I don't want to break it any time soon if possible.

**Comment by reworks** [comment]
The prototype was more pseudocode than actual implementation. I didn't want to make a request without at least putting down something.

I'm still a bit new to variadic arguments and I didn't realise you could call functions like that.

On one hand, having it in the library would save users from having to inherit and create their own registry. 
On the other, if your inheriting the registry anyway, it doesn't really matter, and I can see where your coming from when you say less is better, especially if it would affect other parts of the codebase. It would be simpler for the user's to implement themselves.

My understanding of the way views are meant to be used is that they are for iterating over groups of entities, and can already access multiple components. So there is no need for an entity to return multiple components in that situation.

**Comment by skypjack** [comment]
Actually views return you all the components at once (`each`) or one at the time (`get`). There is no way to get only part of the components, even though the need arises.

**Comment by skypjack** [comment]
See 6040f8f for more details. Hope it works fine for you.
