### ISSUE TITLE
Expose size() member for View class?

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#32]
Hello, I just started to use this library and have a simple question. I would like to assert at runtime there is only one entity in my registry with a certain component. To do this, I would like to write the following statement
`assert(1 == view.size());`

At this point I found there is no size() member on a View.  It has a [size type](https://github.com/skypjack/entt/blob/master/src/entt/entity/view.hpp#L414), but no member function for counting the number of entities.

I noticed that PersistentView has a [size member](https://github.com/skypjack/entt/blob/master/src/entt/entity/view.hpp#L91-L93).

My intuitive understanding is, the semantics of a "size" member function for a "view" would be the number of entities in the view with all the components. My question, is there a semantic reason for not having a size() member function on View?

If it's a performance reason, would a different function (ie: count) providing these semantics be palatable?

**Comment by skypjack** [comment]
>I would like to assert at runtime there is only one entity in my registry with a certain component.

For a single component, `size` is available both on views and on the registry.  
In other terms, these are both valid:

    registry.view<Component>().size()
    registry.size<Component>()

>My question, is there a semantic reason for not having a size() member function on View?

`size` is available only for single component standard views and persistent views actually.
On the other side, it's not available on multi component standard views.

The only way to know how many entities are in a multi component standard view is to iterate it.  
Imagine it as if it had a set of candidates for each component. How would you test if an entity has all the components? Intersection. However it is expensive to do that if it contains 10k entities and usually there is no need to do that.

**Comment by skypjack** [comment]
Just a side note.
If you want to assert it on a multi component standard view, I'd suggest either to put a snippet that count the entities in a separate function and use it or to introduce a new component to tag your entities and thus solve the problem somehow differently.
Honestly I never had such an issue using `EnTT`, so probably you can rethink a bit your design to work around it?

**Comment by skypjack** [comment]
Update: soon I'll push a `size` member function for multi component standard views.  
It doesn't return the exact number of entities the view is going to return. Instead, it will give you an estimation that is equal or greater than the actual number (it cannot be lower in any case).
