### ISSUE TITLE
Add an alias name for EnTT in CMake

### ISSUE THREAD

**Issue by carlfindahl** [skypjack/entt#321]
I propose that you add a target alias for EnTT in CMake as to follow the convention of many other major libraries. Something like:

```cmake
add_library(EnTT INTERFACE)
add_library(EnTT::EnTT ALIAS EnTT)
```

This has numerous benefits according to the book `Professional CMake 2nd Edition by Craig Scott`. Some of which I'll quote here to back up why I think this would be beneficial:

**Quote from page 143:**
> Another` important aspect of names having a double-colon (::) is that CMake will always treat them as the name of an alias or imported target. Any attempt to use such a name for a different target type will result in an error.

Basically, without the alias name linking for `EnTT` in CMake without actually having the target available will make GCC attempt to use `-lEnTT` which can cause compile errors instead of generation time errors with CMake, that make it more clear something is wrong.

**Quote from page 144:**
> It is therefore more robust to link to namespaced names where they are available. Projects are strongly encouraged to define namespaced aliases at least for all targets that are intended to be installed/packaged. Such namespaced aliases can even be used within the project itself, not just other projects consuming it as a pre-built package or child project.

I'm not sure if including the quotes is allowed, but I do find them helpful to explain my point, and I will gladly remove them if it is inappropriate.

**Comment by skypjack** [comment]
Have you tried it already? Does the change you're proposing work as expected?

**Comment by carlfindahl** [comment]
It is not enough alone. It must also be added to the export target around line 120 in the `CMakeLists.txt` (added the NAMESPACE part):

```cmake
install(
    EXPORT EnTTTargets
    FILE EnTTTargets.cmake
    DESTINATION ${CUSTOM_INSTALL_CONFIGDIR}
    NAMESPACE EnTT::
)
```
I just did a quick test with those two changes and that seems to work as intended.

**Comment by skypjack** [comment]
May I ask you to make a PR when you think you have something that works?
I've not a project on which to test it right now and I'm a bit short in time to pack one.

**Comment by carlfindahl** [comment]
@skypjack Yes, I'll try the changes in a project and test that it works with `find_package` and `add_subdirectory`.

**Comment by skypjack** [comment]
Thank you very much! Really appreciated.
I'll keep the issue open for a week or so, let me know if you try it and feel free to make the PR when you're ready. :+1:

**Comment by carlfindahl** [comment]
Tested it now with `find_package` after making the changes to current master and building + installing locally. Also tested in-source build with `add_subdirectory` and it works great in both cases. I think it will also be better suited for use with `FetchContent` now, but I can't test that quite yet. I'll be setting up a PR soon.
