### ISSUE TITLE
Cannot resolve meta types reflected in a shared library

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#324]
In my opinion the best approach to fix this problem would be to offer a class that can hold a set of reflected types, eg. `meta_type_set`.

The data that is currently only stored in inline variables could be members of this class.

Then the `reflect` and `resolve` functions could be methods of this class.

To maintain backwards compatibility, an inline global instance of this class could be declared, and the existing reflect/resolve functions kept which would delegate to this inline global instance.

With this class, one could expose functions in a shared library which add their types to an instance of a meta type set, and not have problems with shared static data.

**Comment by skypjack** [comment]
This boils down to the fact that meta doesn't work across boundaries. Do we agree on this?
When that problem is solved, even what you mention should disappear. Am I wrong?

**Comment by Lawrencemm** [comment]
I thought it was just reflection that didn't work, hence I've been more specific here.

**Comment by skypjack** [comment]
Oh, sorry, then no, it is not reflection. It works (I guess, I haven't tried this actually) on Linux and iOS/MacOS/Android/whatever while it doesn't work as expected on Windows because it treats inline variables in a fancy way unfortunately. That's the same reason for which `EnTT` has named components.

Do you mind if I change the title of the issue, so that we can use this to track the work on meta and DLLs?

**Comment by Lawrencemm** [comment]
You mean make this issue specific to Windows and DLLs or...? Is there something else about meta that doesn't work across boundaries or DLLs?

**Comment by skypjack** [comment]
I mean to make this issue specific to make meta work across boundaries. It's mainly a problem on Windows ofc, unless you use visibility hidden by default on the other systems. In this case, you can have similar problems but it's quite uncommon.

**Comment by Lawrencemm** [comment]
Right, so this object would just hold references to the inline variables.

You can go ahead and change title, though I still think this issue is actually about reflection not working rather than the whole meta system which has more to it like the meta_any class and such.

**Comment by skypjack** [comment]
Sure, but the fact is that you cannot resolve meta types reflected in a shared library because meta doesn't work across boundaries. This is why I'm saying it boils down to the same issue at the end of the day.

**Comment by skypjack** [comment]
I'm almost done with making the meta part work across boundaries. Then you'll be able to resolve types reflected in a shared library.
As usual, to push types across boundaries they must be named types. While this is enough for all the other classes, the meta part has also an additional step. We must set a _context_ on which to bind reflected types.
Out of my mind (this is the only part still under development), the API will be something like this (from the point of view of the main executable):
```
shared_library_set_meta_context(entt::meta_context());
shared_library_reflect();
```
Where in the shared library we have something like:
```
void shared_library_set_meta_context(entt::meta_ctx ctx) {
    entt::set_meta_context(ctx);
}

void shared_library_reflect() {
    entt::reflect<T>().and_bla_bla_bla();
    and_so_on();
}
```
Of course, this is only an example. You can arrange your functions and entry points the way you prefer.
Also, names from `EnTT` aren't guaranteed to be the ones used above but it will be something similar for sure.

As usual, this is needed only on Windows (where fancy things happen with inline variables and odr).
Does it sound like a reasonable solution for you? Do you have any suggestion?

**Comment by Lawrencemm** [comment]
Seems reasonable to me 👍

**Comment by skypjack** [comment]
I've still to write the documentation but all the tests are up-to-date.
If you want to give it a try or just a look, I'm open to feedback. :wink:

**Comment by Lawrencemm** [comment]
Just getting up to speed with the `deluge` of meta changes so I can test this :sweat_smile:

**Comment by skypjack** [comment]
:smile: yeah, you're right, I got the chance to _improve_ the whole part a bit. FWIW, these changes are meant to offer a better tool. :wink:

**Comment by Lawrencemm** [comment]
Yes, I'm sure I'll appreciate them when I inevitably need the changes, which is usually about five minutes after you implement them
