### ISSUE TITLE
Resource loader - function does not take 0 arguments.

### ISSUE THREAD

**Issue by tomsharratt** [skypjack/entt#33]
Having this error when trying to use the resource loader.

Thought it was my code to begin with but I took a copy of the example loader in comments:

```c
struct MyResource {};

struct MyLoader : entt::ResourceLoader<MyLoader, MyResource> {
	std::shared_ptr<MyResource> load(int) const {
		return std::make_shared<MyResource>();
	}
};
```

And I try and use it:

```c
entt::ResourceCache<MyResource> cache;
cache.load<MyLoader>("test");
```

I get the compile time error of `C2660 'MyLoader::load': function does not take 0 arguments`

**Comment by skypjack** [comment]
Do you mean the `doc` branch? It's a work in progress, it contains errors probably.
I would say that the example should be either:
```
std::shared_ptr<MyResource> load() const {
    return std::make_shared<MyResource>();
}
```
Or:
```
cache.load<MyLoader>("test", 0);
```
Does it solve your issue? If yes, I'm updating the documentation accordingly.

**Comment by skypjack** [comment]
Wait a moment. Resource loader isn't documented yet.  
Where did you get the example code?

**Comment by tomsharratt** [comment]
Example I found here: https://github.com/skypjack/entt/blob/master/src/entt/resource/loader.hpp#L22-L33

**Comment by tomsharratt** [comment]
On second thoughts, I think that example is fine, but doesn't show how to call it. I didn't realize I needed to provide an extra parameter when calling.

My bad. It isn't incorrect, just a bit confusing perhaps?

Once everything is documented thought that should be fine.

**Comment by skypjack** [comment]
Yeah, I got it. Well, I'm documenting everything on branch `doc`.
It will take a while for I'm a bit busy, but you'll find there full examples sooner or later.
Please, close the issue if it's solved.

**Comment by tomsharratt** [comment]
I do feel like the resource_id should be passed through to the loader though ([here](https://github.com/skypjack/entt/blob/master/src/entt/resource/cache.hpp#L101)).

**Comment by skypjack** [comment]
Actually I never had the need to access the resource identifier.
I mean, I'm using it with something like this in a project of mine:

    textureCache.load<AssetTextureLoader>("bt/empty", "png/gui/bt_empty.png", renderer);

From the point of view of the loader, the filename and the renderer are enough to load the resource.  
Then I can get it as `textureCache.handle("bt/empty")` and that's all.

I don't see how the identifier could help the loader, unless you want to use it to cache things directly within the loader somehow (but I wouldn't suggest it honestly).

Can you describe the use case where the requirement arises?

**Comment by tomsharratt** [comment]
I personally don't like the idea of having file paths hard-coded.

My example is a bit simplified but gives the general idea.

In my asset pipeline I have the ability to give resources names (e.g "bt/empty") and then it will add it to a 'manifest' file. For example: `43924=/path/to/asset/bt_empty.png` (assuming bt/empty is hashed to 43924).

This manifest is loaded at the start into a map so the loaders could quickly `find(id)` to get the file path.

This means where an assert is physically located does not matter to me, I just have to know what friendly-name to use. If I change the location of an asset, I don't have to update any code because moving it will update the manifest file.

**Comment by skypjack** [comment]
Interesting. A minimal example would help indeed and I'd be glad to try it too. :-)
Please, if you find the time to go a bit deeper and provide me with more details, it would be appreciated.
