### ISSUE TITLE
Cannot find -lEnTT

### ISSUE THREAD

**Issue by roepel** [skypjack/entt#332]
After I pulled from master, make fails at the linking stage with the message
`/usr/bin/ld: cannot find -lEnTT`
When I reset entt to the commit I have previously been working with, everything works fine.
The commit i have been working with was `454f072f13e263aed7bb4660aa8ef6211d84cfff`.
```
CMake Version 3.15.3
GNU Make Version 4.2.1
g++ Version Debian 9.2.1-8
on Debian bullseye/sid (testing)
```

**Comment by skypjack** [comment]
`EnTT` is neither a shared nor a static library, it's a header-only library. I don't think you should link to it at all to be honest.

**Comment by roepel** [comment]
I am using CMake and 'link' entt with target_link_libraries(... EnTT).
Has the CMake integration changed?

**Comment by skypjack** [comment]
Is your hash before #321 ?
Probably you just need the namespace part as `EnTT::EnTT` to make it work.

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

Check if the EnTT::EnTT imported target is available. If I'm not mistaken
there was some effort towards adding it.

ср, 9 окт. 2019 г., 20:15 Jan Hahlganß notifications@github.com:

**Comment by roepel** [comment]
> Check if the EnTT::EnTT imported target is available. If I'm not mistaken there was some effort towards adding it.

I used EnTT without the namespace and this was the problem indeed, thanks!
