### ISSUE TITLE
Question on approach/entity from component

### ISSUE THREAD

**Issue by jasmt-us-dev** [skypjack/entt#333]
I have a question as to approach - assume a component;
```
struct Position
{
int x;
int y;
int x;
}
```

Also assume that I wish to spatially interact with this component - that is "I want all components within Y distance from point (a,b,c)".  This I can derive, for the sake of this question, from a r*tree.

My question, what is the best way to interact with the entities associated with the resultant component set?  Perhaps I am missing a means to obtain the entity ID from the component - unless I store that within the component (which seems an incorrect approach).  What I would like to do is use a visitor callback to fire an event associated with the entity (which is associated with the component).

Thank you in advance!

**Comment by skypjack** [comment]
I'm not sure I get your problem but let's try to flip the problem on its head.

Assume you use a quadtree or something similar for you spatial queries.  
The quadtree **must** contain your entity identifiers, **not** your references or pointers to components because the latter aren't guaranteed to be stable (for optimization purposes).  

This way you don't have anymore the problem of getting the entity from a component because you're going the other way around. You get the components from their entities and you've always both of them at hand.

Does it make sense to you?

**Comment by jasmt-us-dev** [comment]
I had considered this upfront, but what swayed me away was not knowing the components pointer could change.  This would have reduced the overhead of the tree and was trying to approach it from there.  Good thing I asked ;)

The other concern I had was the need to reference the entity identifier for each operation within the tree - this I will have to spend a bit more time thinking about.

Thank you!

**Comment by skypjack** [comment]
I plan to introduce a few alternative pools in future, one for stable pointers to components. It's useful when you make `EnTT` work with other tools UE4 apparently. However, they aren't available out of the box yet (you can implement custom pools by specialization the `storage` class though).

If I were you, I'd store copies of entities in my tree. There is also a function in the registry to know if an entity identifier is still valid of if the entity has been recycled in the meantime (`registry::valid`).

>The other concern I had was the need to reference the entity identifier for each operation within the tree

I'm not sure what you mean with this. I also invite you to join the gitter channel if you want to talk with me and other devs about how to address your doubts. :+1:
See the badges in the README file for the links.

**Comment by skypjack** [comment]
I'm closing this as _question_. I hope you got a proper answer. Feel free to reopen the issue and add more comments if it's not the case. :+1:
