### ISSUE TITLE
Compilation error when trying to register function like f(non_copyable const&)

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#336]
Trying to register a function with a reference to an object of a non-copyable type results in compilation error.

A snippet to reproduce the problem ([Compiler Explorer](https://godbolt.org/z/sbbl8G)):
```c++
#include <single_include/entt/entt.hpp>
#include <cstdint>

struct non_copyable {
    non_copyable(non_copyable const&) = delete;
};

void f (non_copyable const& i) {
    (void)i;
}

struct T {};

int main() {
    entt::reflect<T>().func<&f>("f"_hs);
}
```

I expect `std::reference_wrapper` can solve the problem. The following code compiles just fine [Compiler Explorer](https://godbolt.org/z/m5KkNf)):
```c++
#include <single_include/entt/entt.hpp>
#include <cstdint>
#include <functional>

struct non_copyable {
    non_copyable(non_copyable const&) = delete;
};

void f (std::reference_wrapper<non_copyable const> i) {
    (void)i;
}

struct T {};

int main() {
    entt::reflect<T>().func<&f>("f"_hs);

    // ...
}
```

However, it may worth providing a simple reference wrapper it EnTT. First, for some types `std::reference_wrapper` may not work (for example, `rapidjson::GenericValue`). Second, `<functional>` is quite a huge header that may ruin compilation time for some people. An example of reference wrapper that works is [foonathan's `type_safe::object_ref`](https://github.com/foonathan/type_safe/blob/master/include/type_safe/reference.hpp#L42)

P.S. I'm mostly interested in the first point because I use RapidJSON.

**Comment by skypjack** [comment]
I was looking into this and want to add a note. This type isn't only non-copyable:
```
struct non_copyable {
    non_copyable(non_copyable const&) = delete;
};
```
It's also non-moveable. There is no chance it can work with `meta_any` but for the aliasing mode. In all the other cases, the constructor has no ways to acquire the object and it won't compile.

On the other side, this type should work to an extent (at least until someone tries to make a copy of the meta any, in this case everything should crash down abruptly and that's all - devilish):
```
struct non_copyable {
    non_copyable(non_copyable const&) = delete;
    non_copyable(non_copyable &&) = default;
};
```
The constructor can acquire temporaries this time. I'll look into it further during the next days. :+1:

**Comment by skypjack** [comment]
The more I look at the code to deal with this issue, the less I can decide what to do here.
Should we allow to construct `meta_any`s from a non-copyable type passed as an rvalue-reference? What should the `meta_any`instance do then when you try to copy-construct another instance? Just return an empty wrapper or trigger an assert and crash your software instead?
I'm not convinced yet...

**Comment by Innokentiy-Alaytsev** [comment]
I have very few suggestions:

 * If it's possible to know that the type is not copyable upon the `meta_any` construction then the value may be wrapped in `std::reference_wrapper`. However, this comes with the price of introducing lifetime management problems. This option is worth mentioning only for pointing at these problems.

 * Add notes to the documentation for the `meta_any` regarding the non-copyable types and suggest using `std::reference_wrapper` or any other kind of reference wrapper but warn about lifetime management.

The only way I see for supporting initialisation of `meta_any` with an rvalue reference to the non-copyable type is using `std::shared_ptr` for storing the actual value. This allows for copying the `meta_any` instance around without problems. However, it introduces a kind of implicit sharing and complicates the implementation of `meta_any`. I don't think it worth it. So I'd say "ban non-copyable types from `meta_any`".

**Comment by skypjack** [comment]
The current implementation of `meta_any` allows to work with non-copyable objects in the _aliasing mode_.
All we need is to update the `convert` function so as to return an empty, invalid instance when a copy is required (`if constexpr`-ed branch on `std::is_copy_constructible_v`).

**Comment by skypjack** [comment]
I've added a commit that makes `meta_any` accept non-copyable types. This, combined with the aliasing stuff and whatsoever, should solve also this problem.
