### ISSUE TITLE
Runtime hashed string?

### ISSUE THREAD

**Issue by tomsharratt** [skypjack/entt#34]
Would be useful to have a run-time hashed string constructor. I already have this requirement and currently just have a copy of the hash function used. Obviously, this is a maintenance risk if you were to ever change that hashing function.

EDIT: To clarify, I am aware that if I have a char array with a predetermined size e.g `char name[32]` I can construct a HashedString at run-time but It would be nice to have the option to pass a `std::string` for example.

**Comment by skypjack** [comment]
Doesn't it work by doing `HashedString hs{str.c_str()};`?

**Comment by tomsharratt** [comment]
Interesting, in my use it isn't working but when I try exactly what you suggest it does.

I have a function `entt::ResourceHandle<Resource> get(resource_id id)` resource_id is defined as `using resource_id = entt::HashedString;` but when I call the get function with `str.c_str()` it doesn't work. I get: `cannot convert argument 1 from const char * to entt::HashedString`

**Comment by skypjack** [comment]
Constructor from `const char *` is `explicit`. This helps to promote the `constexpr` constructor.
On the other side, implicit conversions from `const char *` to `HashedString` are not allowed.

All what you have to do to work around it is this:

    get(resource_id{str.c_str()});

**Comment by tomsharratt** [comment]
Yes it does, that is fine. Thank you.

**Comment by skypjack** [comment]
You're welcome. Hope you like `EnTT`.
