### ISSUE TITLE
Static reflection

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#342]
## Abstract

A static reflection is a tool that allows adding meta-information to types for using it at compile time for different purposes. One of the use cases is generating data for runtime reflection systems like the one in EnTT or RTTR. Another important use case is generating Lua bindings based on sol2 or similar system. The main advantage of the static reflection in these cases is that it allows defining a single source of truth and generating all the necessary code with the help of generic functions that work for any type.

## Introduction

The inspiration for this definition of static reflection and its use cases comes from the following code snippet by @Milerius:

```c++
template < typename TypeToRegister >
void register_type (const char* replace_name = nullptr) noexcept
{
    register_type_impl< TypeToRegister > (
        refl::reflect< TypeToRegister > ().members, replace_name);
}

template < typename TypeToRegister, typename... Members >
void register_type_impl (
    refl::type_list< Members... >, const char* replace_name = nullptr) noexcept
{
    std::string current_name = refl::reflect< TypeToRegister > ().name.str ();
    std::string final_name   = current_name;
    if (std::size_t found = current_name.find_last_of (':');
        found != std::string::npos)
    {
        //! Skip namespace
        final_name = current_name.substr (found + 1); //! LCOV_EXCL_LINE
    }

    auto apply_functor = [this](auto&& final_table) {
        try
        {
            std::apply (
                [this](auto&&... params) {
                    // static_assert((std::is_same_v<std::remove_cv_t<std::remove_reference_t<decltype(params)>>,
                    // std::nullptr_t> || ...), "system is flawed");
                    this->lua_state_->new_usertype< TypeToRegister > (
                        std::forward< decltype (params) > (params)...);
                },
                final_table);
        }
        catch (const std::exception& error)
        {
            std::cerr << error.what () << std::endl; //! LCOV_EXCL_LINE
        }
    };

    auto name_table =
        std::make_tuple (replace_name == nullptr ? final_name : replace_name);
    if constexpr (doom::meta::is_detected_v<
                      member_type_constructors_detector,
                      TypeToRegister >)
    {
        using ctor       = typename TypeToRegister::constructors;
        auto final_table = std::tuple_cat (
            name_table,
            std::make_tuple (ctor ()),
            std::make_tuple (Members::name.c_str (), Members::pointer)...);
        apply_functor (final_table);
    }
    else
    {
        auto final_table = std::tuple_cat (
            name_table,
            std::make_tuple (Members::name.c_str (), Members::pointer)...);
        apply_functor (final_table);
    }
}
```

The code above uses the meta-information generated with the help of [refl-cpp](https://github.com/veselink1/refl-cpp) library. The downsides of this library are:

 * it's a third-party library which means it cannot be included into the EnTT library;
 * it makes heavy use of macros for code-generation which makes it relatively hard to comprehend.

Thus, providing a static reflection system would be a great addition to the feature set of the EnTT library. The only technical requirement for it now is not to be a macro-monster.

Requirements:

 * ability to provide meta-information for any type without changing it's definition, not magic macros, inheritance or anything along this line;
 * no pre-build steps and external code generation;
 * allow users providing custom names for the reflected entities (types, functions, etc.) and a reasonable default name generation, whenever possible;
 * ability to query a list of meta-items of different categories (functions, data members, properties) with types, names (`const char*` or similar form)
   and values - required for using other template-based meta systems (EnTT, sol2);
 * ability to query meta-items by name or any other identifier.

## Proposed wording

There are several proposals for the static reflection syntax:

1. Chain-calls (@Innokentiy-Alaytsev, a rippoff of current EnTT version of runtime reflection)

   ```c++
   entt::reflect< T > ()
       .type< entt::name< "foobar"_hs > > ()
       .data<
           entt::target< &T::data >,
           entt::name< "data"_hs >,
           entt::properties<
               my_property,
               entt::property< "foo"_hs, 4 >,
               entt::property< "bar"_hs, 2 > >,
           entt::annotations< my_annotations > > ()
       .func<
           entt::target< &T::func >,
           entt::name< "func"_hs >,
           entt::properties< another_property > > ();
   ```

   The obvious problem with this approach is that it is a function call. It    should be tested whether this kind of code can be used to declare a type through `decltype` but it is not clear how exactly to use this approach.

2. Type lists templates (@Innokentiy-Alaytsev)

   ```c++
   entt::reflect<
       T,
       entt::type< entt::name< "foobar"_hs > >,
       entt::data<
           entt::target< &T::data >,
           entt::name< "data"_hs >,
           entt::properties<
               my_property,
               entt::property< "foo"_hs, 4 >,
               entt::property< "bar"_hs, 2 > >,
           entt::annotations< my_annotations > >,
       entt::func<
           entt::target< &T::func >,
           entt::name< "func"_hs >,
           entt::properties< another_property > > > ();
   ```

   This version shares the problems of being a function call with the vatiant 1. Another problem with this kind of approach is the impossibility of passing values of object types (that is `entt::hashed_string` in the example code) or string literals as template non-type parameters. This will be possible in C++20 but for now EnTT is C++17 library.

   It is most likely that the only way of overcoming this limitation of the language is using macros for generating some kind of class specialisation containing the desired value as `static constexpr` data member.

   There are cases where passing `entt::hashed_string` as template parameter work in EnTT, e.g. `entt::tag` type. The problem here is that in fact the `entt::hashed_string` value is implicitly converted into `entt::hashed_string::hash_type` so that the actual string is lost.

3. Macro-based reflection (by @skypjack)

   ```c++
   REFLECT(
       T,
       TYPE("foobar"_hs),
       DATA(...),
       FUNC(...)
   );

   struct Type {
       int foo;
       void bar() {}
   };

   void quux(const Type &) {}

   META(
       TYPE(Type, "Type")
       DATA(&Type::foo, "Foo")
       FUNC(&Type::bar, "Bar")
       FUNC(&quux)
   )
   ```

   @skypjack:

   > that resembles exactly the definition of refl too :smile: but for the fact that I'd make an abuse of `auto` under the hood to allow more things than what it does

   @Innokentiy-Alaytsev:

   > Would it be possible to unwrap the META macro smartly: at first have every meta-item be turned into a class specialisation and then have every meta-item be actually turned into something else that is the actual meta-data storage?

   This version is mostly intended for hiding the actual code that is most likely a bunch of specialisation. On the plus side, it may be possible to generate some additional code, e.g. specialisation in the global namespace, with this approach. However, it is important to keep those macros as simple as humanly possible.

4. Meta-descriptor reflection (@skypjack)

   ```c++
   template<typename>
   struct meta_type;

   template<>
   struct meta_type<T>: meta_descriptor_t<
       &type::a_member_function,
       &type::another_member_function,
       &type::a_data_member,
       &type::another_member,
       ...
   >;

   template<>
   struct meta_type<T>: meta_descriptor_t<
       func<"name"_hs, &type::a_member_function>, // ?
       &type::another_member_function,
       &type::a_data_member,
       &type::another_member,
       ...
   >;
   ```

   @skypjack:

   > where meta_descriptor_t is an alias that forward everything to a template based system that separates the arguments in lists and defines a compile-time object with a bunch of members like data, func and so on

   Meta-descriptor type specialisation shares the same problems as variant 2 as it needs no pass some object-type values as template parameters. Otherwise, it may have the API that resembles the variant 2 to some extent.

   It may be worth considering the implementation based on alias template: pass template arguments to an alias that unwraps them under the hood to form a proper specialisation of meta-descriptor type.

5. [Attachment through template specialisation](https://godbolt.org/z/RjZn170) (@Innokentiy-Alaytsev)

   ```c++
   struct type_w_p {};


   template<class T, class K>
   struct property{
       static bool constexpr owned = false;
   };


   #define PROPERTY(i_type, i_key, i_value) \
       template<> \
       struct property<i_type, entt::tag<entt::hashed_string{i_key}>> { \
           static bool constexpr owned = true; \
           static auto constexpr key = i_key; \
           static auto constexpr value = i_value; \
       };


   template<class T, class K>
   constexpr bool has_property () {
       return property<T, K>::owned;
   }


   PROPERTY (type_w_p, "test", 43);
   ```

   @Innokentiy-Alaytsev:

   > It is far too limited. The only way to query anything is to call it by name which undermines the whole idea of meta information. It is possible to make yet another specialisation to hold a list of properties, but it is cumbersome and error-prone since it is not possible (from what I can see) to check whether the list is correct or not.

   This version may be usable in certain cases but is most likely not suitable for solving the problem at hand due to lack of querying meta-items functionality.

6. [Static constexpr data structure](https://godbolt.org/z/KckWZG) (@Innokentiy-Alaytsev)

   ```c++
   struct Structure {
       int var;

       void f ()
       {
       }
   };


   template < class TKey, class TValue >
   struct meta_property {
       constexpr meta_property ()
           : key{}
           , val{} {};
       constexpr meta_property (TKey i_k, TValue i_v)
           : key{i_k}
           , val{i_v}
       {
       }

       TKey   key;
       TValue val;
   };


   template < class... TProp >
   struct meta_properties {
       template < std::size_t Ts = sizeof...(TProp) >
       constexpr meta_properties (std::enable_if_t< (Ts >= 0) >* a = nullptr)
           : props{}
       {
       }
       constexpr meta_properties (TProp&&... i_p)
           : props{i_p...}
       {
       }

       std::tuple< TProp... > props;
   };


   template < auto TSource, class TName, class TProperties = meta_properties<> >
   struct meta_item {
       constexpr meta_item (TName i_n, TProperties i_p)
           : name{i_n}
           , props{i_p}
       {
       }


       static auto constexpr src = TSource;

       TName       name;
       TProperties props;
   };


   template < class... TItem >
   struct meta_items {
       constexpr meta_items (TItem&&... i_v)
           : items{i_v...}
       {
       }

       std::tuple< TItem... > items;
   };


   /*
      Template parameters deduction stops working if any template parameter is
      provided, so using meta_item<&source>(name, properties) does not work.
      Another way round is using type parameter for source and saving the source as
      an ordinary member-variable.
   */
   template < auto TSource, class TName, class TProperties = meta_properties<> >
   constexpr auto make_meta_item (TName&& i_n, TProperties&& i_p = {})
   {
       return meta_item< TSource, TName, TProperties >{
           std::forward< TName > (i_n), std::forward< TProperties > (i_p)};
   }


   template < class T >
   struct meta_info {
   };


   template <>
   struct meta_info< Structure > {
       static auto constexpr variables =
           meta_items{make_meta_item< &Structure::var > ("var"_hs),
                      make_meta_item< &Structure::var > (
                          "var_alias"_hs,
                          meta_properties{meta_property{"foo"_hs, 4},
                                          meta_property{"bar"_hs, 2}})};

       static auto constexpr functions =
           meta_items{make_meta_item< &Structure::f > ("f"_hs)};
   };
   ```

   @Innokentiy-Alaytsev (applicable to most types of static reflection):

   > It is not possible to extend this meta-information thing because of C++ and compile-time. But in some rare cases, this kind of extension may be wanted. It could be possible to use inheritance for this: the meta-information type for the specific context may be inherited from the default meta-information type and have a distinct name. The default specialisation will just inherit the base without any changes. The user-defined implementation may shadow the base type members definitions with its own that are composed from the base class definition and new items.

   This version represents one of the ways the underlying compile-time data structure of some template-based reflection (variants 3, 4 and 7, something in the style of variant 2). Having to write this kind of data structure by hand is not desired.

7. Template type-list (@skypjack)

   ```c++
   struct Type {
       int foo;
       void bar() {}
   };

   void quux(const Type &) {}

   using type_meta = meta<
       Type,
       name("Type"),
       data<&Type::foo, name("Foo")>,
       func<&Type::bar, name("Bar")>,
       func<&Type::quux, name("Quux")>
   >;
   ```

   @skypjack:

   > here meta could rely on reordering for parameters and easily handle everything under the hood with a bit of template magic **BUT** there is a problem with the name. mainly because you're already in a context where you cannot push outside the name to define or specialize a class with the sole goal of carrying a `const char *`

8. [Cista](https://cista.rocks/) rippoff

   ```c++
   struct row {
     sql_col<
       int, name("id"),
       primary, not_null> user_id;
     sql_col<
       std::string, name("first"),
       not_null> first_name;
     sql_col<
       std::string, name("last"),
       not_null> last_name;
   } r;
   ```
   ([Full example](https://www.onlinegdb.com/BkEgNzpkN))

   The idea here is to use the same trick (involving macros) to drag string literals into the type definition.

9. Constexpr function chain (@skypjack):

   ```c++
   using t_meta_type = entt::meta<T>::type("Foo").data<&T::member>("Bar");
   // Or
   type("Foo", data<a_member>("bar").data<another_member>("quux"))
   ```

   @skypjack

   > Btw it's something like using this and so on - well, this can be constexpr (with a `decltype` and some `typename` here and there).
   > Then we can add syntactic sugar to get rid of the decltype and all the rest.
   > This can be fully compile-time time and it solves the problem with the names.

   @Innokentiy-Alaytsev

   > Even if those calls are all constexpr then they still return something so you can't use using the way you've done it. My thought was something like using `t_meta_type = decltype(entt::meta<T>::type("Foo").data<&T::member>("Bar"))`. Another option is turing it into static auto constexpr `t_meta_info = entt::meta<T>::type("Foo").data<&T::member>("Bar")`.

   @skypjack

   > Don't worry about the result, you can still define meta_type_t and hide the decltype to the user.
   > The important part is that this would be fully macro-less.

**Comment by yamashi** [comment]
Why not wait a bit and use http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0953r0.html ?

**Comment by skypjack** [comment]
@yamashi 

Unfortunately _a bit_ here means at least 2023 to see that draft enter the standard. Then we'll wait most likely until 2030 to see it widely used because C++20 is such a big revision that it will take way longer than we can imagine to land in the game industry.

**Comment by skypjack** [comment]
Since I put the feature in the backlog and nobody can work on it right now, I'd close the issue (I'm referencing it from the todo file though).
Usually I prefer not to keep issues open unless they are bugs or new features planned in the short term.
I'll reopen this one or even better a new issue with all the details when I find (or someone else finds) the time to tackle in the _static relfection_. I'd be interested in it actually but I've not a clear idea on how to implement this yet and so far everything boils down to something more or less identical to what other projects offer already.

Any thoughts?

**Comment by Innokentiy-Alaytsev** [comment]
Yup, close it. At least for now. It will stay here in any case so that some information on what has already been thought will remain available. I'd love to try to solve this, but I'm a bit overwhelmed with tasks that I don't know how to resolve(

**Comment by skypjack** [comment]
>At least for now.

Yup. This is the point. I want to keep it in the backlog and reopen a new issue with the _final_ solution when the time comes to implement it. :+1:

**Comment by Innokentiy-Alaytsev** [comment]
[Current proposal](https://gist.github.com/Innokentiy-Alaytsev/a797104a6221297909553413c43e4add). The formatting is done according to the style I use to make it simpler for me to write the code. If the proposal (in some future incarnation) will be approved, the style will be fixed tp match the EnTT's one.

The choice was made to use a `constexpr` data structure. As was mentioned in the issue description, using any kind of special type specialisation will not work due to inability to introspect the meta-information stored in this way without knowing all possible kinds of it. This approach may be suitable for type traits where the set of all traits is finite and defined beforehand. With reflection, there is no prior knowledge about what kind of information will be stored in the reflection system.

The implementation looks a bit overcomplicated due to presence of a bunch of special types for storing different kinds of meta-items: meta-member functions, meta-member variables, properties. This is done intentionally for making it possible to catch errors, i.e. to prevent adding a meta-member variable to a meta-member functions list.

The current implementation lacks constructors and destructors, as well as meta-annotations. I'll add those the moment I find time for it.

**Comment by skypjack** [comment]
That's good. Le'ts reopen this so as not to forget it. :+1: 
Thanks for the proposal. I'll do my best to look into it as soon as possible.

**Comment by skypjack** [comment]
I looked into the last proposal. It's by far more complex than what I expected and probably even more complex than what is needed but it contains some interesting ideas.
Please, don't delete it! I'll try to write a draft that borrows some concepts from your implementation.

**Comment by Innokentiy-Alaytsev** [comment]
If you have any questions about the motivation behind complexities - feel free to ask.

**Comment by skypjack** [comment]
This has been starving for a year apparently. Unfortunately, at the moment, I've no bandwidth nor the requirements for this.
I'm closing the issue. I'll reopen it in future if the need for static reflection arises or someone decides to contribute with a first draft. 🙂
