### ISSUE TITLE
warning about arguments to 'min' (becomes macro) on windows/vs2019

### ISSUE THREAD

**Issue by space222** [skypjack/entt#343]
warning is "view.hpp(229,21): warning C4003: not enough arguments for function-like macro invocation 'min' (compiling source file App.cpp)"

also on line 1400 of registry.hpp

Fixed either by putting parenthesis around the function (std::min)(arg1, arg2), or warning windows users to use the correct define (NOMINMAX) before windows.h.

**Comment by skypjack** [comment]
The FAQ [already contains](https://github.com/skypjack/entt/wiki/Frequently-Asked-Questions#warning-C4003-the-min-the-max-and-the-macro) a note about this.

**Comment by space222** [comment]
Thanks; I now realize last time I read the docs I was on Linux.

**Comment by skypjack** [comment]
:smile: You're welcome. I'm using `EnTT` on Linux too, so the `(`-`)` solution risks to be fragile because I cannot guarantee on it. I'm pretty sure I'll forget to add parentheses the next time I use `min` or `max`. :joy:
