### ISSUE TITLE
Property not found after the type is re-registered with meta

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#353]
## Steps to reproduce

1. Register a type with meta.
2. Attach a couple of properties to the registered item with distinct calls to `prop` or a single call to `props` member function. properties may be added to anything that can have properties attached to it - may be type or type's data or function.
3. Check if the first of the properties present. The check will succeed.
4. Unregister the type with a call to `entt::meta<Type>().reset()`.
5. Repeat steps 1-3.

## Expected behaviour

The queried property is present so the check for its existence passes.

## Actual behaviour

The first property added will be missing.

## Example code

```c++
TEST_F(Meta, ReRegistrationAfterResetFailureSingular) {
    struct singular_prop_fail {};

    entt::meta<singular_prop_fail>()
        .type("singular_prop_fail"_hs)
        .prop("required_prop"_hs)
        .prop("any_property"_hs);

    ASSERT_TRUE(entt::resolve<singular_prop_fail>().prop("required_prop"_hs));
    ASSERT_TRUE(entt::resolve<singular_prop_fail>().prop("any_property"_hs));

    entt::meta<singular_prop_fail>().reset();

    entt::meta<singular_prop_fail>()
        .type("singular_prop_fail"_hs)
        .prop("required_prop"_hs)
        .prop("any_property"_hs);

    ASSERT_TRUE(entt::resolve<singular_prop_fail>().prop("required_prop"_hs));
    ASSERT_TRUE(entt::resolve<singular_prop_fail>().prop("any_property"_hs));

    entt::meta<singular_prop_fail>().reset();
}
```

**Comment by Innokentiy-Alaytsev** [comment]
Tests are in [PR](https://github.com/skypjack/entt/pull/354)

**Comment by skypjack** [comment]
Fixed upstream. Thanks for pointing this out. It was really hard to find.

**Comment by Innokentiy-Alaytsev** [comment]
Thanks for a quick fix!)
