### ISSUE TITLE
Are empty entities (entities without components) automatically removed from the registry?

### ISSUE THREAD

**Issue by vokama** [skypjack/entt#355]
Couldn't find information about this anywhere. When I remove the last component from the entity, is the entity itself removed? Is there some sort of garbage collector? Or do I have to remove the empty entity manually?

**Comment by trashuj** [comment]
You have to remove them manually.
The doc mentions "orphans" sometimes.

**Comment by skypjack** [comment]
>When I remove the last component from the entity, is the entity itself removed?

No, it is not.

>Is there some sort of garbage collector?

No but you can find orphans using `registry::orphan`.

>Or do I have to remove the empty entity manually?

If you don't want to recycle it, yes, you can/should delete it explicitly.

**Comment by vokama** [comment]
Great, thank you!

**Comment by skypjack** [comment]
You're welcome. I invite you to join the [gitter](https://gitter.im/skypjack/entt) channel if you've other questions. It's likely you'll get a faster answer from those present. :wink:
