### ISSUE TITLE
Same component ID for two structs in a specific case

### ISSUE THREAD

**Issue by Steki95** [skypjack/entt#357]
I found a weird bug. 
![image](https://user-images.githubusercontent.com/22352869/68518749-afb8f580-028d-11ea-890e-d0e440def323.png)

This occurs because the two components used ComponentA and ComponentB share the same component ID but only in this specific case.

Here is my code
main.cpp
```
#include "ComponentA.h"
#include "ComponentB.h"
#include "entt/entt.hpp"

void test(entt::registry& registry) {
	auto view = registry.view<ComponentA>();


	for (auto e : view) {
		view.get<ComponentA>(e);
		break;
	}
}

int main() {
	entt::registry registry;

	auto entity = registry.create();
	registry.assign<ComponentB>(entity);

	test(registry);
	return 0;
}
```

ComponentA.h
```
#pragma once

struct ComponentA {
	float val1, val2;
};
```

ComponentB.h
```
#pragma once

struct ComponentB {
	float val;
};
```

System.h
```
#pragma once
#include "entt/entity/registry.hpp"
#include "ComponentA.h"

void Update(entt::registry& manager) {
	auto view = manager.view<ComponentA>();
}
```

System.cpp
```
#include "System.h"
```

If anything changes, like for example System.cpp does not include System.h or ComponentB has two variables instead of one the bug does not show.

I got this Bug on Visual Studio 2017

**Comment by skypjack** [comment]
Are you working across boundaries?

**Comment by Steki95** [comment]
Not that i know of. All the files used are put in the project folder and as you can the code used does not access anything other than the files in the project folder. In theory if create a empty project, create the same files and compile is should also crash. If not then the problem is most likely with my system.

**Comment by skypjack** [comment]
>Not that i know of.

Ok, sorry, I was in a rush and I couldn't drop down more than that comment.
What I meant is if you're using shared or static libraries in your application and therefore you pass the registry from the main executable to those libraries.

>This occurs because the two components used ComponentA and ComponentB share the same component ID

In general, components don't share the same id. This is sequentially generated on the fly and we can rely on the fact that _it works_, otherwise the whole library would be unusable (and it is not, ofc).
In case of shared/static libraries on Windows though, you've to use named components to work around an idiosyncrasy of the system. That's why I'm asking.

**Comment by Steki95** [comment]
To make sure that i accidentally didn't have some includes or libraries linked i created a new empty C++ project. Download the repository as zip and copied entt-master/src/entt in the project. After that i created each file in the same order as listed above and copied the given code. Went into project options and set language standard to c++17. The same problem occurred after compiling and running the program.

**Comment by skypjack** [comment]
I cannot reproduce it in any way. I've created the files in the order you mentioned and with the code you mentioned but that's perfectly normal code and it works as expected. There isn't much I can do here. It definitely doesn't look like a bug of this library, I'm sorry.

**Comment by Innokentiy-Alaytsev** [comment]
@Steki95 Could you provide a call stack for the assertion?

**Comment by Steki95** [comment]
I have installed the newest version of visual studio and now the bug has disappeared so it was a problem with my version of visual studio and not the library. Thanks for the help.

**Comment by skypjack** [comment]
You're welcome.
