### ISSUE TITLE
Who is using EnTT out there?

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#36]
If you are using `EnTT` in a real world project, I want to let you know that there exists a [dedicate section](https://github.com/skypjack/entt/wiki/EnTT-in-Action) in the wiki where I'd be glad to add a link for you.  
Feel free to add a comment to this issue or get in touch with me privately.

**Comment by UnoYakshi** [comment]
Making ECS plug-in for [Unreal Engine 4](https://www.unrealengine.com/en-US/blog). Here's the link to the [thread](https://forums.unrealengine.com/community/work-in-progress/1423789-entity-component-system-ecs-for-ue4). 
For the start, I've decided to use `EnTT` for the number of reasons:

- most of the popular ECS C++ implementations (like Artemis, EntityX, Anax) were updated 1-2 years ago, while EnTT still improves itself

- really nice set of features

- it could sound strange, but I see WIPness as an advantage; what I mean is community affect can in a way faster manner, and the creator is still eager to work on the project


Later on, I'm going to use this plug-in for my game projects (for now, mostly tactical FPSs).

**Comment by skypjack** [comment]
Awesome! Thank you for being the first on this thread and with such a good project.

Feel free to contact me whenever you want either on GitHub or by mail. Feedback, requests for new features, bug reports, PRs, whatever... everything is welcome! ;-)

Do you plan to make the project open source? Is there already a link?

**Comment by UnoYakshi** [comment]
@skypjack, I'm not sure if it will be open-source (still thinking), however, I want it to be available for any indie-developer.
For now it's in private repo, just have started to integrate.

And I must say I'm a new one in ECS, so I'll play with it firstly.

**Comment by skypjack** [comment]
Good. I am at your disposal if you need help, do not hesitate to contact me.

I'm not sure about the wording to use to mention your project in the readme. If you have any advice, please let me know.

**Comment by UnoYakshi** [comment]
@skypjack, I think something like _EnTT-UE4-integration plug-in_ will be sufficient.

**Comment by skypjack** [comment]
Well, it looks like people don't like to see their projects and names put in a readme file.  
It makes sense indeed. Nevermind.  
I'm closing the ticket.

**Comment by Wulfe813** [comment]
Well, I know this is closed and all... Anyways, I'm looking into using EnTT to rebuild Cataclysm: Dark Days Ahead with sane design. Not technically using it yet(still working out the mechanics while trying to cut through one of those Gordian Knots), but if we go ahead with it and start making progress, I'll drop you a link.

**Comment by skypjack** [comment]
Time to reopen this issue for a few days and see if someone else wants to add a project to [this list](https://github.com/skypjack/entt/wiki/EnTT-in-Action).  
To be honest I've been told of several projects during the last months, but unfortunately I cannot mention them unless authors pop out giving the rights to do it. :sob:

**Comment by L3nn0x** [comment]
I'm actually considering moving away from entityX and use entt. The major reason is that I need to be able to store entities in a component and it's a pain to do it in entityX (I'm using the compile time version). The fact that the project is maintained is also a good thing in my opinion.
I can't really say if I'll end up using it or not yet, but I like what I see so far!

**Comment by skypjack** [comment]
@L3nn0x I'm glad to know that. I moved away from `entityx` for several reasons (memory usage, features, no longer maintained, and so on) and I understand what you mean.  
Let me know if you'll ever decide to switch and feel free to ping me so that I can add your project to [the list](https://github.com/skypjack/entt/wiki/EnTT-in-Action). :+1:

**Comment by yamashi** [comment]
We are using entt heavily for the mods Skyrim Together and Fallout Together, both of them can be found at https://github.com/tiltedphoques/TiltedOnline

**Comment by skypjack** [comment]
Great @yamashi I'm glad to know it. Feel free to ping me if you ever need help with EnTT! 👍

**Comment by OverShifted** [comment]
I am also using EnTT in my little game engine; But I don't think it is considered "Real World".
Here it is: https://github.com/OverShifted/OverEngine

**Comment by skypjack** [comment]
@OverShifted can I ask you to create a new issue with the link to your project?
I'm out of home at the moment and I don't want to forget about this message, since the issue is closed.
Thanks! :)

**Comment by JohnMrziglod** [comment]
Hi @skypjack!
Thank you very much for this amazing tool! I decided to give it a try in my new project (after butchering around with OOP-heavy game classes for years) and I LOVE it. Everything is so much easier now.
Link to my project: https://store.steampowered.com/app/1670930/Black_Sun/

**Comment by skypjack** [comment]
Hi @JohnMrziglod thanks for the heads-up, it looks good!!
Do you mind if I add it to the list of showcases?

**Comment by JohnMrziglod** [comment]
Please, go ahead :)

**Comment by ajh123** [comment]
I'm using ENTT in my [game](https://github.com/ajh123-development/HistorySurvival), this is what I just need :) 👍

**Comment by skypjack** [comment]
Hi @ajh123 what kind of game is it? How far from being released?

**Comment by ajh123** [comment]
@skypjack it is not really ready for release yet, I will tell you and make a release in the got as well when it is ready

**Comment by skypjack** [comment]
@zaucy sure thing, I'm more than glad to add it. Do you want to suggest a description or can I proceed on my own?

**Comment by zaucy** [comment]
@skypjack I think something like this could describe it well enough.
> [Ecsact](): A language dedicated to describing ECS. An ecsact [runtime implementation](https://github.com/ecsact-dev/ecsact_rt_entt) is maintained by the Ecsact development team which heavily utilizes EnTT.

By all means, give it a description you'd prefer!

**Comment by skypjack** [comment]
Do you think that _engines and the like_ is appropriate as a section or _any other business_ is better? I don't really have a _lang_ section, sorry. 🙂

**Comment by zaucy** [comment]
I would lean more to engines and the like with an emphasis on "the like" haha

**Comment by MohitSethi99** [comment]
I am using EnTT in my game engine: https://github.com/MohitSethi99/ArcGameEngine

**Comment by skypjack** [comment]
Cool, thanks for pointing it out. 👍

**Comment by jwmcglynn** [comment]
Hey, would you please add my project to your list under "Engines and the like"?

* [Donner](https://github.com/jwmcglynn/donner): a modern SVG rendering engine in C++20 that uses `EnTT` for its data-model.

**Comment by GuusKemperman** [comment]
Hi, we are using EnTT in our game engine and I was wondering if it could be added to the list :)

https://github.com/GuusKemperman/CoralEngine

**Comment by skypjack** [comment]
Sure thing @GuusKemperman done. They're in the wiki now. 👍

**Comment by notchyves** [comment]
I'm using EnTT for Minecraft: Bedrock Edition modding. It makes it much easier when dealing with components, thanks for the amazing tool :D

**Comment by jamesl-github** [comment]
TheCherno has built (is building) a game engine in C++ and Vulkan and is using it 
https://www.youtube.com/watch?v=D4hz0wEB978

**Comment by skypjack** [comment]
Yeah, I know, it's already on the wiki 🙂 thanks for pointing it out.

**Comment by Ace-codes-swift** [comment]
hey! im making a game engine in c++ opengl using entt but i don't have a public github can i still be featured? its called **Omnix Engine**
