### ISSUE TITLE
Inconsistent noexcept specification

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#362]
There are several inconsistencies in `noexcept` specification of `entt:basic_registry` member functions:

* [`get() const`](https://github.com/skypjack/entt/blob/wip/src/entt/entity/registry.hpp#L751) is not marked as `noexcept` while [`get()`](https://github.com/skypjack/entt/blob/wip/src/entt/entity/registry.hpp#L763) is;

* [`get_or_assign`](https://github.com/skypjack/entt/blob/wip/src/entt/entity/registry.hpp#L798) is marked as `noexcept` while non of the `assign()` overloads are.

**Comment by Innokentiy-Alaytsev** [comment]
Why functions like `has` or `try_get` are no longer `noexcept`? They seem to not do things that may cause exception. Am I wrong?

**Comment by skypjack** [comment]
They don't but `assure` does. This is the price for having pools created _automagically_ rather than having you explicitly list them for creation.

**Comment by Innokentiy-Alaytsev** [comment]
So `assure` creates the pool under the hood and then checks if an entity has a component? Wouldn't it be possible to short-circuit the case where the pool for the queried component does not exist yet and just return `false` or `nullptr` from `has` and `try_get` respectively?

**Comment by skypjack** [comment]
Possible? Yes. Does it worth it? Imho no. It worked like that before, no benefits and a code a bit harder to maintain because you need two paths for the pools (_get-if-exists_ and _get-no-matter-what_).

**Comment by skypjack** [comment]
Consider that you're just delaying something (pool creation) you will do for sure sooner or later and this will complicate the code for no real benefits. I don't think noexcept-ness on the `get` is a game changing, even less if you consider that I always disable exceptions in general.

**Comment by Innokentiy-Alaytsev** [comment]
OK, just asking. I don't exactly understand the consequences (as in "what I get") of `noexcept`-ness so it's all about curiosity)
