### ISSUE TITLE
Incorrect code in docs

### ISSUE THREAD

**Issue by xissburg** [skypjack/entt#364]
In the **Views** section [here](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#views) the `&` should not be present, since the `entt::view::get` function in that case returns a `std::tuple` of references, by copy.

```cpp
// ... or multiple components at once
auto &[pos, vel] = view.get<position, velocity>(entity);
```

**Comment by skypjack** [comment]
Wiki updated. Thanks for pointing this out. :+1:
