### ISSUE TITLE
Sorting by empty type

### ISSUE THREAD

**Issue by KB9** [skypjack/entt#365]
I'm using empty tag components to differentiate two groups of entities with the same components. I'm attempting to sort entities of one type using the tag component, where I will use their other components to decide their sorting order, like so:

```cpp
struct Empty {};

registry.sort<Empty>([](const entt::entity a, const entt::entity b) {
  ...compare other components...
});
```

This generates the following error:

```
cannot convert 'cpool->entt::basic_registry<entt::entity>::pool_handler<Empty>::<anonymous>.entt::storage<entt::entity, Empty>::<anonymous>.entt::basic_storage<entt::entity, Empty, void>::begin()' (type 'entt::basic_storage<entt::entity, Empty, void>::iterator_type' {aka 'entt::basic_storage<entt::entity, Empty, void>::iterator'}) to type 'entt::sparse_set<entt::entity>::iterator_type' {aka 'entt::sparse_set<entt::entity>::iterator'}
```

Having read through the documentation on ETO, I'm confused as to why this happens. As I understand the docs, this shouldn't be a problem. From the docs:

> When an empty type is detected, it's not instantiated in any case. Therefore, only the entities to which it's assigned are made available. All the iterators as well as the get member functions of the registry, the views and the groups will return temporary objects. Similarly, some functions such as try_get or the raw access to the list of components aren't available for this kind of types.

Since I'm only reading the entities and no attempt is made to access the `Empty` component, why is this code not valid?

**Comment by Innokentiy-Alaytsev** [comment]
If I get the error and the `entt::storage::sort()` code correctly, then the function does not do what you expect it to do:
```c++
    template<typename Compare, typename Sort = std_sort, typename... Args>
    void sort(iterator_type first, iterator_type last, Compare compare, Sort algo = Sort{}, Args &&... args) {
        ENTT_ASSERT(!(last < first));
        ENTT_ASSERT(!(last > end()));

        const auto from = underlying_type::begin() + std::distance(begin(), first);
        const auto to = from + std::distance(first, last);

        const auto apply = [this](const auto lhs, const auto rhs) {
            std::swap(instances[underlying_type::index(lhs)], instances[underlying_type::index(rhs)]);
        };

        if constexpr(std::is_invocable_v<Compare, const object_type &, const object_type &>) {
            underlying_type::arrange(from, to, std::move(apply), [this, compare = std::move(compare)](const auto lhs, const auto rhs) {
                return compare(std::as_const(instances[underlying_type::index(lhs)]), std::as_const(instances[underlying_type::index(rhs)]));
            }, std::move(algo), std::forward<Args>(args)...);
        } else {
            underlying_type::arrange(from, to, std::move(apply), std::move(compare), std::move(algo), std::forward<Args>(args)...);
        }
    }
```
If I'm not too wrong then the comparison function if given instances of the component type and not the entities themselves.

**Comment by Innokentiy-Alaytsev** [comment]
@skypjack Will using a group solve the problem? The Doxygen documentation mentions a comparison function that accepts entities:
```     
     * @code{.cpp}
     * bool(std::tuple<Component &...>, std::tuple<Component &...>);
     * bool(const Component &..., const Component &...);
     * bool(const Entity, const Entity);
     * @endcode
```

**Comment by Innokentiy-Alaytsev** [comment]
```c++
auto group = registry.group<EmptyType>();

group.sort ([](const entt::entity a, const entt::entity b) {
  ...compare other components...
});
```

**Comment by KB9** [comment]
> ```c++
> auto group = registry.group<EmptyType>();
> 
> group.sort ([](const entt::entity a, const entt::entity b) {
>   ...compare other components...
> });
> ```

Unfortunately this does not compile either. The following assertion within the registry's `group` method is triggered:

```cpp
static_assert(sizeof...(Owned) + sizeof...(Get) + sizeof...(Exclude) > 1);
```

Calling `sort` on this group also generates a similar compile-time error to the one I mentioned originally.

**Comment by Innokentiy-Alaytsev** [comment]
Well, I didn't test the code - it was more of the idea I had.

**Comment by Innokentiy-Alaytsev** [comment]
@KB9 How do you plan to sort the entities? If you are going to use other components for comparison then you can add them to the group with `registry.group<EmptyComponent>(entt::get<Comp...>);`. It will prevent static assertion.

**Comment by skypjack** [comment]
I'm from mobile and I've to test it but I'm pretty sure you've found a bug from what I see in the log.
One of the rare corner cases not covered by a test yet. **Thanks** for pointing this out.

I'll look into it tomorrow probably, in the worst case on Wednesday (I'm a bit busy during these days). If that's what I think, it should be straightforward to solve.

What version of `EnTT` are you using? `master` or a tag?
This probably deserves a minor release.

@Innokentiy-Alaytsev maybe you're looking at the _wrong_ sort function? Be aware that `storage` has a specialization for empty types.

**Comment by KB9** [comment]
@skypjack Thanks for the reply and clearing this up. I'm using the latest release (v3.2.0).

**Comment by skypjack** [comment]
Bug confirmed. Fixed upstream on branch `wip`. I've also added a test for this case.
May I ask you to test the patch and confirm that it works as expected?

**Comment by KB9** [comment]
@skypjack Many thanks for the quick turnaround! Those changes have fixed things on my end.

Any idea when you'll release the latest version? I'm using the latest Conan package so it'd be easiest for me to simply update to a release where this is supported.

**Comment by Innokentiy-Alaytsev** [comment]
@skypjack I've been able to find only one version of the sort function for
storage (
https://github.com/skypjack/entt/blob/831f955b79a77455dadbf27de03d9bade92529c7/src/entt/entity/storage.hpp#L446).
Is it specialised somewhere else? Or is it overriden?

вт, 26 нояб. 2019 г., 3:35 Kavan Bickerstaff <notifications@github.com>:

**Comment by skypjack** [comment]
@KB9

I'll try to make a minor release this week, even though I'm a bit busy. Patches have a fast path on releases. 

@Innokentiy-Alaytsev 

That was the bug. The class specialization for empty types didn't have a `sort` function. Probably I thought that sorting a pool for empty types didn't make sense but it may help actually, especially if used in combination with groups or such.

**Comment by skypjack** [comment]
Created version v3.2.1 - conan package should be released automatically, let me know if you've problems.
