### ISSUE TITLE
Exclude a component from view

### ISSUE THREAD

**Issue by stwe** [skypjack/entt#366]
I want to exclude a component from the view. See the following code:

```cpp
#include "entt.hpp"

namespace component
{
    struct Position {};
    struct Moveable {};
    struct Renderable {};
}

int main()
{
    entt::registry registry;

    // single component view
    auto single = registry.view<component::Position>();

    // multi component view
    auto multi = registry.view<component::Position, component::Moveable>();

    // exclude
    auto view = registry.view<component::Position, component::Moveable>(entt::exclude<component::Renderable>); 
     // -->Error: None of the overloads accepts 1 argument

    for (auto entity : view) {}

    return 0;
}
```

But the exclude view does not accept the argument. What am I doing wrong? This is almost copy and paste from the readme.

**Comment by skypjack** [comment]
What version of `EnTT` are you using? The exclusion list is on `master`.

**Comment by stwe** [comment]
I tried that with the last release and master. I use the single include file and Visual Studio 2019.

**Comment by skypjack** [comment]
I strongly suspect I haven't updated the single include file. This could be your problem. :smile:

**Comment by skypjack** [comment]
Can you try the version from branch `wip`? I've updated it to v3.2.0, the last _stable_ release.

**Comment by stwe** [comment]
That was the problem. Thank you.

**Comment by skypjack** [comment]
That's good. I plan to create a minor release because of #365 so it will land `master` soon. :+1:
I'll close the issue when this happens.

**Comment by skypjack** [comment]
Updated upstream.
