### ISSUE TITLE
Proposal for registry::any<>

### ISSUE THREAD

**Issue by alanjfs** [skypjack/entt#371]
As mentioned [in chat](https://gitter.im/skypjack/entt?at=5df243cac6ce6027ebab1fd5), there might be an opportunity for the API to save a few characters from being typed, by introducing a `any` to the registry.

**Before**

```cpp
if (_registry.has<Selected>(entity) ||
    _registry.has<SelectedByParent>(entity) ||
    _registry.has<SelectedByChild>(entity))
{
  flags |= ImGuiTreeNodeFlags_Selected;
}
```

**After**

```cpp
if (_registry.any<Selected, SelectedByParent, SelectedByChild>(entity) {
  flags |= ImGuiTreeNodeFlags_Selected;
}
```

**Comment by skypjack** [comment]
What about the following instead?
```
registry.has<A, B>(entity, entt::any<C, D>);
```
That is: `entity` has both `A` and `B` and any of `C` and `D`.
This could make possible more complex queries like the one above.
Your case becomes:
```
registry.has<>(entity, entt::any<Selected, SelectedByParent, SelectedByChild>);
```

**Comment by alanjfs** [comment]
That could work, but I'm not a fan of how it reads.

1. registry, has.. what?
2. In this entity
3. Any of `<these>`
4. Do something

Now `.has<>` is noise, and the other `entt::` is more noise. You would have to have read it a few times to understand its meaning. As opposed to..

1. registry, any of these
2. Do something
 
Which isn't as clear as `registry.has<>` which is almost English, but closer. My picks would be, in this order:

1. `registry.any<A, B>(entity)`
1. `registry.has<A, B>(entity, entt::any)`

**Comment by skypjack** [comment]
Just to be sure, are you suggesting to implement both of them or just the first one from your list?

**Comment by alanjfs** [comment]
That's up to you, I meant either one or the other, with more preference to the first.

**Comment by skypjack** [comment]
I added `registry::any`, it was actually easier to read and to work with.
I'll push it upstream soon, most likely tomorrow since I'm out of home today. :+1:
