### ISSUE TITLE
Questionable noexcept specification

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#372]
Some functions are marked as `noexcept` but seem to have nested calls that may throw:

* [`dispatcher::sink()`](https://github.com/skypjack/entt/blob/lib/src/entt/signal/dispatcher.hpp#L117): `dispatcher::assure()` may throw on resize;

* [`dispatcher::discard()`](https://github.com/skypjack/entt/blob/lib/src/entt/signal/dispatcher.hpp#L188): `dispatcher::assure()` may throw on resize when the function is called with a non-empty `Event` template parameter pack;

* [`emitter::clear()`](https://github.com/skypjack/entt/blob/lib/src/entt/signal/emitter.hpp#L275): `mitter::assure()` may throw on resize;

* [`emitter::empty()`](https://github.com/skypjack/entt/blob/lib/src/entt/signal/emitter.hpp#L298): `mitter::assure()` may throw on resize.

**Comment by skypjack** [comment]
Good catch. Thank you for pointing these out. :+1:
