### ISSUE TITLE
Meta and constexpr problems

### ISSUE THREAD

**Issue by roig** [skypjack/entt#374]
Hello!

I have a type like this:

```   
struct Test {
        float &x() {return _data;}
        constexpr float x() const {return _data;}
        private:
        float _data;
    };
```

I only want to reflect the method float& x()  doing this but always I get an error:

```
    entt::meta<Test>().type("Test"_hs);
    entt::meta<Test>().func<&Test::x>("x"_hs);
```

```
 error C2672: 'entt::meta_factory<Endavant::Reflection::reflectTypes::Test>::func': no matching overloaded function found
 error C7513: 'Candidate': cannot deduce the type of the placeholder 
 error C2975: 'Candidate': invalid template argument for 'entt::meta_factory<Endavant::Reflection::reflectTypes::Test>::func', expected compile-time constant expression
```

If I comment the constexpr function in the Test, it works. Where is the problem exactly?
Thank you!

**Comment by skypjack** [comment]
At a first glance `&Test::x` is ambiguous. The compiler cannot know what overload you want.
The following should work instead:
```
entt::meta<Test>().func<entt::overload<float &()>(&Test::x)>("x"_hs);
```
`entt::overload` is just a _nicer_ alternative to a static cast. The goal is to _force_ the right type to disambiguate it.

**Comment by roig** [comment]
wow, entt::overload, thank you skypjack!
