### ISSUE TITLE
Update vcpkg port to 3.2.2

### ISSUE THREAD

**Issue by brempusz** [skypjack/entt#376]
FYI: I created 
https://github.com/microsoft/vcpkg/issues/9407
and 
https://github.com/microsoft/vcpkg/pull/9409
to upgrade vcpkg port from 3.1.1 to 3.2.2

**Comment by skypjack** [comment]
Thank you very much. Really appreciated! :+1:

**Comment by skypjack** [comment]
I'm closing the issue since I saw that your PR has been merged. Thank you again for your help.
