### ISSUE TITLE
EnTT in Action - add to list

### ISSUE THREAD

**Issue by stwe** [skypjack/entt#378]
I would be happy if you add my project to your "EnTT in Action" list. It is a small engine that I program in my spare time for learning purposes.

https://github.com/stwe/SgOgl

**Comment by skypjack** [comment]
Sure, I'm glad to do that! Thank you for pointing it out.
I'll add it as soon as possible upstream. What version of EnTT have you used? Just for reference.

Since you've used actively EnTT, may I ask you if you've any feedback or feature request that would have made your goal easier to accomplish?

**Comment by stwe** [comment]
Version: EnTT v3.2.1

Much would be easier for me if you had your own small and simple sample program. This should include the most important things (create entities -> add components -> create and use systems -> events). Other developers do it like this: https://github.com/SuperV1234/ecst/blob/master/CODE_SAMPLE.md

You currently have your wiki and programs from other developers. That's OK. But you have to find everything in different places. I also don't know if what others do is "best practice".
