### ISSUE TITLE
Program abort when using view.each in entt-3.2.2

### ISSUE THREAD

**Issue by SylEze** [skypjack/entt#379]
**Context**:
I have a Window system which iterates through all entities which have a Layer component, a Sprite component and a Transform2D component.

**Sprite component structure**:
```cpp
struct Sprite
{
        explicit Sprite(const TexturePtr& texture_ptr) :
            Sprite(texture_ptr, Maths::Rect2u { texture_ptr->GetSize() })
        {}
        
        explicit Sprite(TexturePtr texture_ptr, Maths::Rect2u texture_frame) :
            Texture(std::move(texture_ptr)), TextureFrame(texture_frame)
        {
            this->SfmlData.setTexture(this->Texture->SfmlData);
            this->SfmlData.setTextureRect(this->TextureFrame.To<int>().ToSfRect());
        }

        TexturePtr Texture;

        Maths::Rect2u TextureFrame;

        bool IsVisible { true };

        sf::Sprite SfmlData;
};
```

**Transform2D component structure**:
```cpp
struct Transform2D
{
        Transform2D() noexcept :
            Transform2D(Maths::Vec2f {}, Maths::Vec2f(1, 1), 0.0f, false)
        {}

        explicit Transform2D(Maths::Vec2f pos) noexcept :
            Transform2D(pos, Maths::Vec2f(1, 1), 0.0f, false)
        {}

        explicit Transform2D(Maths::Vec2f pos, Maths::Vec2f scale) noexcept :
            Transform2D(pos, scale, 0.0f, false)
        {}

        explicit Transform2D(Maths::Vec2f pos, Maths::Vec2f scale, float rotation) noexcept :
            Transform2D(pos, scale, rotation, false)
        {}

        explicit Transform2D(Maths::Vec2f pos, Maths::Vec2f scale, float rotation, bool centered) noexcept :
            Position(pos), Scale(scale), Rotation(rotation), IsCentered(centered)
        {}

        explicit Transform2D(Maths::Vec2f pos, Maths::Vec2f scale, float rotation, Maths::Vec2f origin) noexcept :
            Position(pos), Scale(scale), Rotation(rotation), Origin(origin), IsCentered(false)
        {}

        Maths::Vec2f Position;

        Maths::Vec2f Scale;

        float Rotation;

        Maths::Vec2f Origin;

        bool IsCentered;
};
```

**The window system**
```cpp
template <typename TLayer, typename TDrawable>
inline void Window::Draw()
{
    this->_entity_registry.view<TDrawable, Physics::Transform2D, TLayer>.each(
        [&](const auto, const auto& drawable, const auto&, const auto)
        {
            if (drawable.IsVisible)
            {
                this->_sfml_window.draw(drawable.SfmlData);
            }
        });
}
```

**Bug**:
When I assign at least 2 Sprite components to my entities, the program will abort when using `view<Sprite, Physics::Transform2D, Layer>.each()`

**What I found until now**:
When iterating, the first entity assigned to a Sprite does not have any issue.
But when it's the second entity's turn, the `drawable` parameter of my lambda is not correct.

**Debugger screens of the second entity's Sprite**:
Inside the lambda the drawable parameter does not seem valid:
<img width="1060" alt="Capture d’écran 2019-12-26 à 16 10 14" src="https://user-images.githubusercontent.com/14373103/71480654-8979f580-27fa-11ea-9466-19ce53dc4f59.png">

Inside view::get() the drawable value seems valid.
view::get() is called by view::traverse() which is called by view::each()
<img width="1001" alt="Capture d’écran 2019-12-26 à 16 11 00" src="https://user-images.githubusercontent.com/14373103/71480681-b928fd80-27fa-11ea-84d0-4a2d9a95e007.png">

**How I deal with the problem right now**:
To fix it, I have to change the first returning line of view::get()
From:
<img width="1190" alt="Capture d’écran 2019-12-26 à 16 15 14" src="https://user-images.githubusercontent.com/14373103/71480774-25a3fc80-27fb-11ea-919a-89037108c17b.png">
To:
<img width="1191" alt="Capture d’écran 2019-12-26 à 16 16 50" src="https://user-images.githubusercontent.com/14373103/71480781-2dfc3780-27fb-11ea-890a-d6bbff634d40.png">

The problem seems to come from the `return *it` inside view::get but I don't know why.

**Comment by Milerius** [comment]
:D

**Comment by SylEze** [comment]
And i forget to mention how I create entities and assign them components:
```cpp
int main()
{
    auto cursor_path = GetBinaryDirectoryPath() / "Resources" / "Cursor.png";
    auto cursor_frame = Rect2u { 0, 0, 10, 10 };

    auto tex = std::make_shared<Texture>(cursor_path);
    
    {
        auto et = this->_entity_registry.create();
        this->_entity_registry.assign<Sprite>(et, tex);
        this->_entity_registry.assign<Layer1>(et);
        this->_entity_registry.assign<Transform2D>(et, Vec2f { 400, 400 });
    }
    
    {
        auto et = this->_entity_registry.create();
        this->_entity_registry.assign<Sprite>(et, tex);
        this->_entity_registry.assign<Layer1>(et);
        this->_entity_registry.assign<Transform2D>(et, Vec2f { 250, 300 });
    }
}
```

**Comment by skypjack** [comment]
Is it possible to have a minimal example so as to reproduce the error?
From what I see, there is nothing wrong in what you're doing and it's pretty difficult to know where the error is from these snippets.

**Comment by skypjack** [comment]
I put the code you posted in a small program and everything works as expected.
It's unlikely this code is the same that gives you problems, since there are some wrong `this->` here and there and a few other things to fix to make it work.

It seems that you're invalidating the iterators/pools somehow during iterations but I've no clue of the reasons, so I don't know how to help you.
As it stands, the issue is _invalid_. Please, submit a code that can be used to reproduce the problem.

I'll leave the issue open for a week or so in order to give you the time to add more details.

**Comment by skypjack** [comment]
As a side note, using `cpool->get(entt)` rather than `*it` works fine because it doesn't use the underlying iterator and therefore it doesn't suffer from invalidation.
The drawback is that it's a loss of performance for no real benefit, since probably invalidating an iterator will cause problems anyway sooner or later and somewhere else.

I'd rather try to find the root cause of your problem. :+1:

**Comment by SylEze** [comment]
I found the problem coming from another area of my code. I was using:
```cpp
if (_registry.has<Comp>(et))
  _registry.assign<Comp>(et);
```
Instead of `_registry.replace`
As the documentation says, assigning an already assigned component is undefined behavior, maybe it was the reason why the iterators were invalid.

**Comment by skypjack** [comment]
That's good, I'm glad you found it. Thank you for investigating.
Afaik it should assert in debug though, doesn't it?

**Comment by SylEze** [comment]
I don't see any `ENTT_ASSERT` inside `view::traverse` method.

**Comment by skypjack** [comment]
>I don't see any ENTT_ASSERT inside view::traverse method.

No, I mean, it asserts if you assign a component to an entity that has it already.
`traverse` knows nothing about the error ofc, it makes perfectly sense. :wink: 

>And thank you for your amazing ECS !

Thank you for using it! Is it for an open-source project or a private one?

**Comment by SylEze** [comment]
Hmm it's weird, indeed it should assert.

Indeed, it's for a private project, I am working on a game engine (simply called DN4VRengine) with a really high level API which provides IO, 2D, physics, maths, lua, observable, reflection, serialization... procedures.

No graphics wrapper dependant stuff, you can choose the graphical wrapper you like (sfml, sdl...) without editing your code. I also encapsulated `entt::registry` . 😃 

I'm doing this to challenge myself and for the special game I want to create since years.

**Comment by skypjack** [comment]
It sounds interesting. Ping me if you need help and feel free to join the gitter channel if you want to talk with other users of this library. :wink:
