### ISSUE TITLE
Remove in-repo Conan support

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#380]
Conan is switching to a different model (see [this issue](https://github.com/conan-io/conan-center-index/issues/550) for further details) and therefore the in-repo stuff is no longer required.

**Comment by Lawrencemm** [comment]
Removing the recipe from EnTT repo will make it a bit cumbersome for me to test things eg. the experimental or other branches.

Having the recipe there allows me to add the repo as a part of a Conan workspace, without it I can't do that.

**Comment by skypjack** [comment]
Interesting. Isn't it possible with the new model they are setting up?
I thought they wanted to make it the _official way_ to do it in the long term.
Since they asked for feedback, maybe this one could help them to improve the whole thing.

**Comment by Minimonium** [comment]
Hi, thanks a lot for bringing up this use-case! I totally forgot about it. 

Small clarification, we change the official way of packaging for the **default** remote - the `conan-center`. It greatly simplifies the maintaining process and is much more reliable and secure for all the users. 

Discussion about the out-of-source recipes pros/cons is here: https://github.com/conan-io/conan-center-index/issues/22

I'll point this use case out and we'll see what can be done. For now, I'd suggest to post-pone the removal of the in-source recipe then albeit we have duplication and an additional maintaining cost.

**Comment by skypjack** [comment]
>Hi, thanks a lot for bringing up this use-case! I totally forgot about it.

You're welcome. Thank you for helping us with the corner cases. :wink: 

>For now, I'd suggest to post-pone the removal of the in-source recipe

Sure, this goes without saying. It's not a problem for me.
I opened the issue to `EnTT` so as to intercept comments like the one above. :wink:
Let us know if you have any news and thank you very much for being so kind.

**Comment by danimtb** [comment]
@Lawrencemm I don't think using the in-source Conan recipe (the one in this repo) to set up a Conan workspace would be a stopper. The recipe in conan-center-index repo could be a generic one prepared to bump versions just editing the *conandata.yml*. That will enable you to test experimental features or branches while in the development of the library.

Additionally, this reduces the maintenance of the library author's side, leaving the recipe maintenance to the Conan community. New versions can be added on-demand there and the recipe could evolve parallel to the library.

Of course, conan-center-index is still on Early Access Program and there are still some things to work on as @Minimonium said. But regarding the number of recipes already in and the number of PRs it is quickly becoming the way to contribute recipes and generate massive package configurations for the Conan users.

**Comment by skypjack** [comment]
@danimtb I'm not sure I get what you're saying. Does it mean that we can remove the in-source support and the CCI way will make possible to use `experimental` or any other branch anyway? Afaik it's not the case yet but you certainly know it better than me, so please let me know if I'm wrong. Thanks.

**Comment by danimtb** [comment]
@skypjack testing `experimental` branch will not be as straight forward as just changing branches as it is not possible (it is a centralized repo), but could be done with little manual work editing the *conandata.yml* file and adding the URL path of the experimental sources.

Anyway, to begin with this issue, I'd recommend removing first the Conan create and upload steps in CI (https://github.com/skypjack/entt/blob/master/.github/workflows/deploy.yml) and hkeep the conanfile.py meanwhile

**Comment by skypjack** [comment]
Fine for me and thanks for answering.
@Lawrencemm do you spot any issue with what @danimtb suggested?

**Comment by Lawrencemm** [comment]
No worries, in-repo recipe can just contain the information needed for editable mode.

**Comment by skypjack** [comment]
Good to know. So, I'll close this issue and stop publishing the package on my account. On the other side, I'll leave the in-repo recipe until required.
@Minimonium @danimtb thank you very much for the support. Please, let us know if you find a solution that makes possible to do everything from the CCI. As a side note, I've also another library published on Conan, `uvw`. Ping me if it's covered by CCI as well.

Thank you all for participating. :+1:
