### ISSUE TITLE
Update EnTT in Action wiki page

### ISSUE THREAD

**Issue by Czapa10** [skypjack/entt#384]
Hi! I'm currently working on game called PopHead and we're using EnTT.
Could you mention PopHead on EnTT in Action wiki page?
https://github.com/SPC-Some-Polish-Coders/PopHead/

**Comment by skypjack** [comment]
Thank you very much for pointing this out!
Of course, I'd be glad to ad it to the list. :+1:

**Comment by Czapa10** [comment]
Thanks
