### ISSUE TITLE
Sorting during registry::on_construct breaks registry::get_or_assign

### ISSUE THREAD

**Issue by alanjfs** [skypjack/entt#386]
A somewhat special case and the first time I had use both of them together like this, at which point I encountered this issue.

From [the chat](https://gitter.im/skypjack/entt?at=5e16e505a74ac853777b0300).

**Works**

```cpp
if (!Registry.has<A>(entity)) {
  Registry.assign<A>(entity, 1);
}

auto& a = Registry.get<A>(entity);
```

**Breaks**

```cpp
auto& a = Registry.get_or_assign<A>(entity, 1);
```

The key being that A is being sorted whenever one is constructed. If I don't sort, both works.
With the latter, the A I get back is from another entity then the one I asked for

**Comment by skypjack** [comment]
Fix available on `experimental`. I'll merge it on `master` soon. :+1: 
Please, don't close the issue. It will be closed automatically once merged.

**Comment by skypjack** [comment]
Actually, I think this issue is harder to solve than expected.
I need to write one more test to verify an intuition I had in the evening.
Probably, we cannot really pass the component in the callback and listeners should get it from the registry if needed. This is the only reliable way if you attached eg two listeners, one of which sorts the pool.

**Comment by skypjack** [comment]
This test is enough to reproduce the issue:
```
entt::registry registry;
registry.group<int, char>();
registry.on_construct<int>().connect<&listener::bump<int>>();

const auto entity = registry.create();
const auto other = registry.create();

registry.assign<int>(entity, 0);
registry.assign<char>(other, 'c');

ASSERT_EQ(registry.assign<int>(other, 0), 1);
```
Long story short, if you've something that _affects_ the order of a pool, you cannot rely on the reference returned during the construct or as an argument to a callback. We should **always** `get` it when needed  to avoid errors.

The solution is pretty easy: I won't pass anymore the component to the callbacks.
The error you pointed out is already fixed instead. Range assign will be soon too.
