### ISSUE TITLE
Add support for fetching all components attached to an entity

### ISSUE THREAD

**Issue by Tyyppi77** [skypjack/entt#390]
I propose adding a method of iterating over all components IDs that are currently attached to an entity. 

What I want to achieve is mapping the components to my custom reflection system, and that could be done by mapping & looking them up with runtime component IDs generated via `registry.type<Component>()`. In addition to the type ID, I would also need a pointer to the actual component type that I could then cast to the correct type based on the ID.

The resulting API could look something like the following:

    registry.components(entity, [](entt::component component_id, void *instance) { ... });

The naming of the method should probably be considered, maybe it should somehow clearly indicate that this is very "raw" data as it only feeds the caller void pointers.

**Comment by Tyyppi77** [comment]
Dunno if this should go to a separate issue, but actually a similar system for context variables would also be useful, `registry.all_ctx([](uint32_t type, void* ctxElementPtr){ });`. This would allow similar type visitation for context variables in the registry.

**Comment by skypjack** [comment]
No need for another issue. I'll expose functions for all erased types, whatever they refer to.

**Comment by ArekPiekarz** [comment]
It would also help with unit testing, for instance to check what components are assigned to entities after some system has run its update.

**Comment by skypjack** [comment]
Yes. I am extracting one problem at a time from the list and closing them.
It is a matter of time and this will be possible. Don't worry. :wink:

**Comment by Lawrencemm** [comment]
This is actually a really great idea that I just realised I need to decouple loading a map from loading the meta data needed by a map editor.

**Comment by Kerndog73** [comment]
Just had an idea to make the component ID a strong type that depends on the entity type (to avoid mixing component IDs from different registries).

```C++
namespace entt {

namespace internal {

// enum templates aren't a thing :-(
template <typename Entity>
struct basic_component {
  enum class type : ENTT_ID_TYPE {};
};

}

template <typename Entity>
using basic_component = typename internal::basic_component<Entity>::type;

using component = basic_component<entity>;

}
```

Perhaps I'm missing the reason why `entt::component` was removed?

Oh, I forgot about `to_integer`. Um, I didn't think that far ahead...

**Comment by skypjack** [comment]
@Kerndog73 Why shouldn't I mix component ids for components from different registries? A component type T is the same no matter what registry uses it. This is also pretty useful in fact. You can move instances between different containers without having to know their actual types this way.
`entt::component` was removed because I introduced `type_info`, that is a more reliable way to assign ids to types also across boundaries. I'm no longer using sequential ids and I got rid of the linear lookup step for named types.

**Comment by Lawrencemm** [comment]
So, if this feature is implemented, is it easy to get an `entt::meta_type` for each component, if such a meta type exists?

**Comment by skypjack** [comment]
@Lawrencemm definitely, yes. Probably we need a method to create a `meta_any` from a couple `void *` and `meta_type` though. This way, creating a bridge between the registry and the meta system becomes straightforward.

**Comment by Lawrencemm** [comment]
I think iterating over all the component types in the registry across all entities would also be useful.

**Comment by skypjack** [comment]
Uhm... what could be the use case @Lawrencemm ?

**Comment by Lawrencemm** [comment]
You can do a custom snapshot serialisation, except only the components that you have declared meta types for are serialised.

Each component meta type would have a func to delegate to which takes a registry and an output stream and writes the whole pool out.

**Comment by Innokentiy-Alaytsev** [comment]
Another possible use case is implementing editors. As long ass all component types have proper meta-API, it would be possible to write a single generic editor that looks into the meta-information and generates UI according to it. It's the feature I want for quite some time now and proposed something similar to this issue somewhere in September 2019. The way I put it back then differed from the current formulation, though.

Yet another use case is entity validation. Imagine that you have a special registry that has "schema entities". These entities are not used anywhere in the application for business logic. Their purpose is to validate if the deserialised entities have proper components assigned. This feature was mentioned by me somewhere in November 2019.

**Comment by skypjack** [comment]
I'm reopening this because we still miss a `visit` overload for context variables. :+1: @Tyyppi77
