### ISSUE TITLE
Proposal for registry.assign<A>(view)

### ISSUE THREAD

**Issue by alanjfs** [skypjack/entt#392]
On several occasions, I've found myself doing things like this.

```cpp
void on_click() {
    registry.view<Hovered>().each([](auto entity, const auto) {
        registry.assign<Selected>(entity);
    });
}
```

And intuitively tried calling..

```cpp
void on_click() {
    registry.assign<Selected>(registry.view<Hovered>())
}
```

Which would have been awesome. :) I can't spot any ambiguity either, seeing as the view would effectively contain a list of relevant entities (if any). And I think you're already able to assign to a range of entities from an `std::vector`?

Implementation wise, I haven't dove too deep before gathering feedback, but I would imagine it'd be an added overload to `assign`, to make it aware and in support of a `entt::basic_view`.

**Comment by skypjack** [comment]
The problem of making it _view-aware_ is that someone wants it also _group-aware_, then _vector-aware_, _list-aware_ and so on.
That's why the standard library isn't aware of containers in general and just works with a couple of iterators.
`EnTT` follows the same philosophy:
```
void on_click() {
    const auto hovered = registry.view<const Hovered>();
    registry.assign<Selected>(hovered.begin(), hovered.end());
}
```

>And I think you're already able to assign to a range of entities from an `std::vector`

Actually, you can assign from a range. It just happens that a vector is a range but also a list, a map, an unordered map and all others are range. You can use whatever you want with the solution above.

**Comment by alanjfs** [comment]
Fair enough, it doesn't really save characters or reading comprehension compared to a `.each` or for-loop so I'll probably stick with what I have but good to know about more options. 👍

**Comment by skypjack** [comment]
Consider that the range-`assign` is by far faster than N different `assign`s though.
If N is low it doesn't change much but if you're adding the component to 40k entities maybe it's worth it. :+1:

**Comment by alanjfs** [comment]
I still haven't figured out a usecase for range-assign. :S Every component I've assigned needs its own custom initialisation. But that's another conversation. Would love an example and/or usecase for it, however on the other hand assignments are far from a bottleneck currently so it isn't a priority.
