### ISSUE TITLE
Proposal for registry.first<X>()

### ISSUE THREAD

**Issue by alanjfs** [skypjack/entt#393]
I often find myself doing things like this.

```cpp
entt::entity hovered { entt::null };
for (auto entity : registry.view<Hovered>()) {
    hovered = entity;
    break;
};
```

Where there may be many things carrying this particular component, e.g. behind or infront of the cursor, and where you may have sorted them front to back and only want the front-most one. Another usecase is for selection, where the "first" gets special treatment like a different kind of draw call.

And was thinking that could be simplified to e.g.

```cpp
auto hovered = registry.first<Hovered>();
```

Along with, for symmetry..

```cpp
auto hovered = registry.last<Hovered>();
```

Thoughts?

**Comment by skypjack** [comment]
What if the pool is empty?

**Comment by alanjfs** [comment]
That's what I would expect, yes.

**Comment by Kerndog73** [comment]
Perhaps a better name would be `first_or_null`. I'd expect `first` to be similar to `std::vector::front` and assert when empty.

**Comment by alanjfs** [comment]
With that in mind, maybe even go with `registry.front<>()` and `registry.back<>()` and *do* assert?

**Comment by skypjack** [comment]
Well, it would be equivalent to the following:
```
const auto entity = *registry.view<T>().begin();
```
It returns the first entity and asserts in case the pool for `T` is empty.
This is the counterpart for last instead:
```
const auto entity = *(--registry.view<T>().end());
```

**Comment by alanjfs** [comment]
Sure, or the equivalent to my original example. :) The idea was to improve reading comprehension, not necessarily introduce a new feature.

**Comment by skypjack** [comment]
Yup. Btw I'd add `first` and `last` on views and groups rather than the registry. This would make them available also for multiple components for free.

Something like:
```
registry.view<T>().first();
```
Rather than:
```
registry.first<T>();
```
I see it's more verbose but also by far more flexible and general purpose.

What about?

**Comment by alanjfs** [comment]
Oo yes that's not bad. :)

Would it then make sense to return `entt::null` on an empty view?

**Comment by skypjack** [comment]
Sure, it makes sense. You would have to check if it's empty otherwise, so it's worth returning an entity anyway, then verify if it's the null entity. :+1:

**Comment by alanjfs** [comment]
Love it! ❤️

**Comment by skypjack** [comment]
I was experimenting with this feature and I realized that I would use it this way:
```
if(const auto entity = view.first(); entity != entt::null) {
    my_func(entity);
}
```
That is pretty much equivalent to this:
```
if(const auto it = view.begin(); it != view.end()) {
    my_func(*it);
}
```
`last` would be equivalent to this snippet instead:
```
if(const auto it = std::make_reverse_iterator(view.end()); it != std::make_reverse_iterator(view.begin())) {
    my_func(*it);
}
```
What's the problem of using the latter?
I'm not saying we can't introduce `first` and `last` but it seems to me they don't add much to the game. Am I wrong?

**Comment by Kerndog73** [comment]
Should views be able to return reverse iterators if only to make that last example more readable?

```C++
if(const auto it = view.rbegin(); it != view.rend()) {
    my_func(*it);
}
```

**Comment by skypjack** [comment]
This could be a good idea because it has also other advantages.
Iterating a view with reverse iterators is no longer _safe_ if you want to add/remove components on the fly but it's also faster if you don't want to do that.
Ironically, also a _reverse each_ could make sense. Much faster but unsafe if you want to add/remove elements. Since I don't do it 90% of the times, I'd benefit from this quite a lot.

**Comment by Kerndog73** [comment]
Oh right, because view iterators actually iterate backwards. I remember asking about this a while ago. I was sorting and then using `data` and I noticed that it was backwards.

**Comment by skypjack** [comment]
Yup. That's the cheapest way to allow adding/removing components during iterations without a staging area (merge) or a command queue (lazy ops), and so on.
If it's not enough, users can just implement a solution that fits their needs on top of these basic tools.

**Comment by alanjfs** [comment]
> I'm not saying we can't introduce first and last but it seems to me they don't add much to the game. Am I wrong?

Is the question which of these two to prefer?

**Option 1**

```cpp
auto hovered = registry.last<Hovered>();
```

**Option 2**

```cpp
entt::entity hovered { entt::null };
if(const auto it = std::make_reverse_iterator(view.end()); it != std::make_reverse_iterator(view.begin())) {
    hovered = *it;
}
```

Tough choice! xD

**Comment by Innokentiy-Alaytsev** [comment]
What about `with_first` and `with_last`?
```c++
registry.with_first<Component>([](entt::entity){
    // Do work
});
```
As you don't need to store anything it should be possible to allow any kind of callable here.

**Comment by Kerndog73** [comment]
@alanjfs At some point you need to check if `hovered` is null don't you? So it's really not that much shorter than using iterators because either way you need to check if the view is empty.

**Comment by skypjack** [comment]
Hi agree with @Kerndog73 to be honest. You're going to check the returned value anyway, don't you?

**Comment by alanjfs** [comment]
I can see how this kind of feature might seem like bloat if you aren't using it. Personally, and likely based on the way I'm using my components and systems, it's all over the place. So yeah, the forementioned snippets does work, it's what I do too. It just takes me a while each time reading it to figure out what it does and is supposed to do.

This, for example..

```cpp
select(registry.first<Hovered>());
remove(registry.view<Selected>());
undo(registry.last<Command>());
```

Turns into e.g.

```cpp
{
  auto view = registry.view<Hovered>();
  if(const auto it = view.begin(); it != view.end()) {
      select(*it);
  }
}
{
  auto view = registry.view<Command>();
  if(const auto it = view.begin(); it != view.end()) {
      remove(*it);
  }
}
{
  auto view = registry.view<Selected>();
  if(const auto it = std::make_reverse_iterator(view.end()); it != std::make_reverse_iterator(view.begin()))   {
      undo(*it);
  }
}
```

Readability and maintainability is hard to quantify, so I can't ask for more than I already have, and I can always write a wrapper function on my end. It's up to you!

**Comment by Kerndog73** [comment]
@alanjfs What I'm saying is that `select`, `remove` and `undo` need to check for null in the first example but not in the second example. You're not showing the full story.

**Comment by alanjfs** [comment]
> You're not showing the full story.

I suppose, but what those functions do internally isn't relevant to the issue I think. They would check for null. What matters (to me) is the readability prior to getting into that function, because the function itself is clear in what it does via its name. The `select` for example would happily accept `entt::null`, and simply deselect everything.

It's hard arguing for readability, I understand that. Here's where I stand, the rest is up to you. ❤️

**Comment by Kerndog73** [comment]
I think I just found another use for this feature. I found myself writing this:

```C++
gfx::Point player;
reg.view<Position, Player>().less([&](auto pos) {
  player = pos.p;
});
```

What would be clear is this:

```C++
const gfx::Point player = reg.get<Position>(reg.first<Player>()).p;
```

Although, what's even cleaner is this (so maybe this isn't such a good use-case after all):

```C++
const gfx::Point player = getPlayerPos(reg);
```
