### ISSUE TITLE
Use of entt::observer

### ISSUE THREAD

**Issue by alanjfs** [skypjack/entt#395]
I'd like to open up a conversation about the interface for observers. I find them essential for initialisation of data that involve external or system resources, like OpenGL or a physics engine, but that they are a little tedious to use and manage.

Here's a typical usage for me.

```cpp
// 1. In the header file of a System
entt::observer some_observer;

// 2. In the constructor of a System
some_observer.connect(registry, entt::collector.group<OpenGLMesh>());

// 3. In a `.reset()` of my System
some_observer.clear();  // Discard any pending events, we're starting fresh

// 4. Flush, in the update loop of the application
for (const auto entity : some_observer) handler_for_some_observer(entity);
some_observer.clear();
```

Which is 4 separate parts of my code to manage, only 2 of which are independent.

1. Register
2. Flush

With that in mind, I was thinking it could be reduced into something like..

```cpp
// 1. In the constructor of a system
registry.observer<OpenGLMesh>().connect(&handler_for_some_observer);

// 4. Flush
registry.observer<OpenGLMesh>().flush();
```

<br>

### Alternative

Maybe I am misusing the observer? Is there another mechanism to accomplish this? The `registry.on_construct` gets me half-way there, but where the observer wins is that I can defer handling of all queued events until a given point in my update loop. That's gold.

One alternative I was considering was to use system.

```cpp
// Somewhere in your code
registry.assign<InitCollider>(collider_entity);

// In your update loop..
registry.view<InitCollider>().each([](auto entity) {
    handler_for_some_observer(entity);
    registry.remove<InitCollider>(entity);
});
```

Which begs the question, why do observers exist?

**Comment by skypjack** [comment]
>Which begs the question, why do observers exist?

They exist to avoid this:
```
registry.assign<InitCollider>(collider_entity);
```
You can use them to setup complex _queries_ (the plan is to add also support for user defined queries like _position.x < 20_). Without them, you would have a bunch of `assign` spread in your codebase, that is something error-prone and annoying to maintain. Moreover, this `assign`s could be the result of some `if`s here and there where you test the conditions and this is yet another thing to keep in sync around the codebase.

Imho, the real _issue_ with observers is that they are an external tool.
You setup a query and they fill their own pool:
```
some_observer.connect(registry, entt::collector.group<OpenGLMesh>());
```
Then you've to iterate the observer, clear it and so on.
I think it would be better something like this:
```
entt::assign<InitTypeT>(registry).on(entt::collector.group<TypeT>());
```
This will create a pool for `InitTypeT` that you can use with your views, groups, whatever and you can `clear` at the right time directly from the registry.
After all, the observer is an _unnamed pool_. This makes it unusable in combination with the other components in a view. Just... give it a name, a type and you've all the benefits of a _standard_ component.
Does it make sense?

**Comment by alanjfs** [comment]
Makes sense. I like the idea of an `on`.

Having a think on syntax..

```cpp
registry.on<TypeT>().assign<InitTypeT>();
```

Where anything passed to `on` is the `entt::collector.replace<>`, with room for further filters in the constructor.

```cpp
registry.on<TypeT>(entt::collector.group<A, B, C>).assign<InitTypeT>();
```

Followed by, as you mentioned:

```cpp
// Somewhere in your loop
registry.view<InitTypeT>().each([]() { ... });
registry.reset<InitTypeT>();
```

That also seems useful for another common pattern I use for `on_construct`.

```cpp
void on_position_constructed(entt::registry& registry, entt::entity entity) {
  registry.assign<InitialPosition>(entity, registry.get<Position>(entity));
}
```

Which could then become..

```cpp
registry.on<Position>().assign<InitialPosition>();
```

Although it isn't clear how to pass the `Position` component into the argument list for `InitialPosition`, so perhaps not. And that's possibly another topic altogether.

I suppose, I don't quite see the advantage of `entt::on` or `registry.on` compared to assigning an `InitTypeT` during `on_construct`?

> Without them, you would have a bunch of assign spread in your codebase, that is something error-prone and annoying to maintain

This one is hard to envision. Things being hard to maintain is hard to exemplify, but if you can think of anything specific that could possibly help. I think I would rather have complex queries in the form of standard C++ in an `on_construct` than a customised EnTT syntax (i.e. a domain-specific language, basically).

**Comment by skypjack** [comment]
I'm closing this since the changes I described are already in the pipeline and the discussion is over from my point of view.
Thanks for pointing out this and for helping to better understand the problem. Stay tuned for the _new observer stuff_ that will land sooner or later on `master`. :wink:
