### ISSUE TITLE
Hashing in ENTT_ID_TYPE is not always evaluated as constexpr

### ISSUE THREAD

**Issue by dBagrat** [skypjack/entt#396]
On VS 2019 (Release) hashing function called every time.

https://github.com/skypjack/entt/blob/b3c568fb6fa46fecbaf77e3b23d5cca7426595de/src/entt/core/type_info.hpp#L60

To force "consteval", we can re-write as:
```cpp
constexpr auto id = entt::hashed_string{ENTT_PRETTY_FUNCTION};
return id;
```

**Comment by dBagrat** [comment]
OMG!
By trying it, I've got a 3-4x speed boost in some system-update loops where I have a couple of registry.get<> (instead of groups/views)

**Comment by skypjack** [comment]
WTF!? Why on the heart the compiler doesn't always evaluate it as `constexpr` when it's possible?

**Comment by skypjack** [comment]
Does `return entt::hashed_string::value{ENTT_PRETTY_FUNCTION};` work as expected instead?

**Comment by dBagrat** [comment]
> Does `return entt::hashed_string::value(ENTT_PRETTY_FUNCTION);` work as expected instead?
just tested, unfortunately no.
//It's pity that we don't have a `consteval` specifier in C++17 :)

**Comment by skypjack** [comment]
Nvm I'll make it explicitly `constexpr` as you suggested.
Who knows why it doesn't work otherwise, it's odd.
Indeed, `consteval` would work like a charm here.

**Comment by skypjack** [comment]
[This](https://github.com/skypjack/entt/commit/fc0432df8cf9e537d02eac37af239ae7f3038c79/checks?check_suite_id=419400852#step:3:97) is way it wasn't `constexpr`. :(

**Comment by Kerndog73** [comment]
@skypjack [Apparently](https://stackoverflow.com/questions/55850013/pretty-function-in-constant-expression) that was fixed in GCC 8

**Comment by skypjack** [comment]
Yup. I'm adding a macro to differentiate between `static` and `constexpr` when dealing with gcc. :+1:
