### ISSUE TITLE
Github Action for updating Homebrew formula

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#397]
I noticed that the homebrew formula hadn't been updated since 3.1.1 so I updated it myself. According to the [analytics](https://formulae.brew.sh/analytics/install-on-request/365d/) (that webpage is ridiculously huge), the formula has had a whopping 61 installs in the past 365 days! That's honestly more than I was expecting. I think these staggering numbers are enough reason to get this working.

We just need to download a file, hash it, and put the hash into a file on [another repo](https://github.com/skypjack/homebrew-entt). There's already a [script](https://github.com/skypjack/homebrew-entt/blob/master/update.bash) to do this but it will have to be modified to work as a Github Action. I had a look into this a few weeks ago and realised that it's not really that simple. I fell into a rabbit hole and gave up.

If I remember right, you need to [create an access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line) that gives the script write permissions, then make that a [secret](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets) so that the Action can use it but nobody can actually see it, then hand that over to git somehow. After that, it should be plain sailing.

**Comment by skypjack** [comment]
No idea about how to do that but I'll give it a try. :)

**Comment by skypjack** [comment]
Can I use the script _as-is_ during the deploy?
Do you think you can/know how to modify it otherwise?

**Comment by Kerndog73** [comment]
For the most part, it should remain the same apart from "logging in" to git using the personal access token. I'm not exactly sure how to do that though.

**Comment by skypjack** [comment]
I was looking into this.
It doesn't seem too difficult to set up but I want to share a thought on a fact that could break the whole thing. Let me know if I'm missing something.

Afaik to update the homebrew formula we need to download the latest zip from this repo, the one created for the last tag.
The workflow should start only when a tag is pushed.
In this case, I think (though I'm not sure) it's not guaranteed that the file is available when the workflow runs and therefore the latter could fail. If this happens, we have no chance to recover from the error but pushing another tag that could fail as well.

Does it makes sense or am I missing something here?

**Comment by Kerndog73** [comment]
That's a very good point that I hadn't thought of.

**Comment by Kerndog73** [comment]
I checked the docs and it should be fine. The [webhook payload](https://developer.github.com/v3/activity/events/types/#releaseevent) for when a release is published contains the URL of the ZIP. So if the action is triggered when the release is published...

```
on:
  release:
    types: [published]
```

...the ZIP will be available at that point.

**Comment by skypjack** [comment]
Oh, you beat me on time. I wrote the comment and went to sleep.
I wanted to check into the issue today morning but you did it first.
Thank you very much for helping! :+1: :heart:

**Comment by skypjack** [comment]
I'm to cut a new patch release because of #436 and it would be great if this entered it.
However, I've no idea on how I could test it without making an actual release. Any idea?

**Comment by skypjack** [comment]
NVM. Would you review the last commit on `experimental`?
It seems to work fine and could solve this issue.

**Comment by skypjack** [comment]
I think [it works as expected](https://github.com/skypjack/entt/runs/492457883?check_suite_focus=true) but a feedback would be appreciated.
If using `release`, `github.ref` correctly returns the tag. :+1:

**Comment by Kerndog73** [comment]
The commit message is `Update to refs/tags/v3.2.2` but that’s probably not worth making a fuss over. I didn’t spot any other issues. It looks good!

**Comment by skypjack** [comment]
Oh, well, who cared about the commit message, it's fine anyway. Isn't it?

**Comment by Kerndog73** [comment]
Yeah, you’re right. It doesn’t matter.
