### ISSUE TITLE
Signals with unordered arguments

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#399]
In [this comment](https://github.com/skypjack/entt/issues/385#issuecomment-573492337), I mentioned `connect_unordered`. I thought about it some more and came up with this:

```C++
constexpr size_t not_found = -1;
constexpr size_t ambiguous = -2;

template <size_t Size>
constexpr size_t find(const bool (&matches)[Size]) noexcept {
  size_t count = 0;
  size_t index = 0;
  for (size_t i = 0; i != Size; ++i) {
    if (matches[i]) {
      ++count;
      index = i;
    }
  }
  if (count == 0) {
    return not_found;
  } else if (count > 1) {
    return ambiguous;
  } else {
    return index;
  }
}

template <size_t Size>
constexpr bool unique(const size_t (&indicies)[Size]) noexcept {
  for (size_t i = 0; i != Size; ++i) {
    for (size_t j = i + 1; j != Size; ++j) {
      if (indicies[i] == indicies[j]) {
        return false;
      }
    }
  }
  return true;
}

template <typename SrcArg, typename... DstArgs>
struct index_of {
  static constexpr bool matches[] = {std::is_convertible_v<DstArgs, SrcArg>...};
  static constexpr size_t value = find(matches);
  static_assert(value != not_found, "Argument type not found in delegate signature");
  static_assert(value != ambiguous, "Argument type appears more than once in delegate signature");
};

template <typename... DstArgs>
struct find_order {
  template <typename Ret, typename... SrcArgs>
  static constexpr auto sequence(Ret(*)(SrcArgs...)) {
    constexpr size_t indicies[] = {index_of<SrcArgs, DstArgs...>::value...};
    static_assert(unique(indicies), "Argument type appears more than once in callable signature");
    return std::index_sequence<index_of<SrcArgs, DstArgs...>::value...>{};
  }
};
```

`find_order` is a drop-in alternative to `internal::index_sequence_for` that supports unordered arguments. I haven't tried to integrate this with `entt::delegate` yet but I assume it will be pretty straight forward. It doesn't quite solve #385 but it might be a cool feature anyway. Usage will look a bit like this:

```C++
struct A {};
struct B {};
struct C {};

void f1() {}
void f2(B, A) {}
void f3(A, B, C) {}
void f4(C) {}

int main() {
  entt::sigh<void(A, B, C)> signal;
  entt::sink sink{signal};
  sink.connect_unordered<&f1>();
  sink.connect_unordered<&f2>();
  sink.connect_unordered<&f3>();
  sink.connect_unordered<&f4>();
  signal.publish(A{}, B{}, C{});
}
```

Something that I've just realised is that we could check for an exact match first (`std::is_same_v`) and then fall back to implicit conversions (`std::is_convertible_v`). Similar to how the compiler does overload resolution. This would allow you to do something like this:

```C++
void f(const B &, B &) {}

int main() {
  entt::sigh<void(A, B &, const B &)> signal;
  entt::sink{signal}.connect_unordered<&f>();
}
```

I think this feature is pretty cool but is it useful? Do we need it?

**Comment by skypjack** [comment]
>I think this feature is pretty cool but is it useful? Do we need it?

To be honest, I don't think this is crucial for `EnTT` and I don't think I would use it as an user.
It makes the call site a bit confusing probably. Moreover, there is the problem that I could have two arguments of the same type in a function type. This makes the whole thing even more confusing.

**Comment by Kerndog73** [comment]
I don't really think this is confusing. If there's any ambiguity, you get a static_assert. Here's a more realistic example:

```C++
struct Component {};

void replace(Component &) {}

int main() {
  entt::registry reg;
  reg.on_replace<Component>().connect_unordered<&replace>();
}
```

It would solve #385 if the component was still passed to `on_construct` and `on_destroy` signals. It exists purely to save typing so it's certainly not crucial. There's not really much opportunity to use it with the registry signals so it would make the most sense for users of the signals library.

**Comment by skypjack** [comment]
>It would solve #385 if the component was still passed to on_construct and on_destroy signals.

Unfortunately, I realized that users can do literally **everything** in a callback, even sort a pool.
Imagine you've two callbacks and the first one sorts the pool. The reference would be no longer valid unless you `get` it from the pool before every invocation. However, in this case you are consuming cpu cycles also when the listeners isn't interested in the component (eg groups).
All in all, moving the `get` to the user space looked like the most promising compromise. :)

**Comment by Kerndog73** [comment]
@skypjack

> Btw, what if my function type has two parameters of the same type? This would fail, right?

Yeah, you'd get a static_assert.

**Comment by Kerndog73** [comment]
Yet another solution looking for a problem

**Comment by skypjack** [comment]
Why did you close this?

**Comment by Kerndog73** [comment]
@skypjack It just seems kind of pointless
