### ISSUE TITLE
512 constexpr recursive template limit on clang for big templates (id generation)

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#400]
AS discussed on gitter i open the issue here:

` /home/milerius/vcpkg/installed/x64-linux/include/entt/entity/../core/hashed_string.hpp:72:41: note: constexpr evaluation exceeded maximum depth of 512 calls`

`/home/milerius/vcpkg/installed/x64-linux/include/entt/entity/../core/type_info.hpp:60:24: fatal error: constexpr variable 'value' must be initialized by a constant expression
constexpr auto value = entt::hashed_string::value(ENTT_PRETTY_FUNCTION_CONSTEXPR)`

**Comment by Kerndog73** [comment]
I used [djb2](http://www.cse.yorku.ca/~oz/hash.html) for the same purpose [long ago](https://github.com/Kerndog73/Simpleton-Engine/blob/ab1905f805d1e1c951d96775d0d6646a3548b4ce/Simpleton/Utils/type%20name.hpp#L39-L47).

```C++
size_t djb2(const char *str) {
  size_t hash = 5381;
  while (char c = *str++) {
    hash = ((hash << 5) + hash) ^ c;
  }
  return hash;
}
```

**Comment by skypjack** [comment]
I think we can easily make fnv not recursive. I'll try it before to use a different algorithm. Nice to know that djb2 fits the purpose btw. Thanks for pointing this out. :+1:
