### ISSUE TITLE
Process struct of base class entt::process needs to have a ctor

### ISSUE THREAD

**Issue by tuncatunc** [skypjack/entt#401]
I'm following [cooperative scheduler crash course](https://github.com/skypjack/entt/wiki/Crash-Course:-cooperative-scheduler) to evaluate EnTT library 3.2.2

Needed to add the following ctor for it to compile.
```
my_process (const char*) { /* whatever you want to do with it... */ }
```

I suggest the wiki page to be updated.

[Related SO question](https://stackoverflow.com/questions/59802112/why-using-entt-process-fails-to-compile)

**Comment by Kerndog73** [comment]
The wiki says that `attach` forwards its arguments to the constructor of `my_process`.

> If the process inherits from the process class template, it's enough to indicate its type and submit all the parameters required to construct it to the attach member function:

**Comment by tuncatunc** [comment]
The minimal example has no constructor. 
```
struct my_process: entt::process<my_process, std::uint32_t> {
    using delta_type = std::uint32_t;

    void update(delta_type delta, void *) {
        remaining -= std::min(remaining, delta);

        // ...

        if(!remaining) {
            succeed();
        }
    }

private:
    delta_type remaining{1000u};
};
```
I was following the document and a bit confused. 
Adding following ctor to the struct my_process makes the document easier to follow for a newcomer like me.

```
my_process (const char*) { /* whatever you want to do with it... */ }
```

**Comment by skypjack** [comment]
Maybe an error in the documentation.
I'll look into it and let you know.
Thanks for pointing this out. :+1:
