### ISSUE TITLE
Allow user to configure behaviour in config.h by checking if the macros are already defined

### ISSUE THREAD

**Issue by Tyyppi77** [skypjack/entt#403]
Currently, it is not possible to provide EnTT a custom assertion macro due to the way it is implemented.  https://github.com/skypjack/entt/blob/f32f3ab895a59ee2207ccd03b4493a40bebc28d9/src/entt/config/config.h#L39-L44
The macro gets redefined even if it is already defined by the user.

In addition to `ENTT_ASSERT`, this same behaviour also applies to `ENTT_MAYBE_ATOMIC` and `ENTT_ENABLE_ETO`, all though I'm not sure if the last one falls into implementation details with `ENTT_PRETTY_FUNCTION`, and should be perhaps kept unconfigurable. I could perhaps see atomics getting redefined with platform specific implementations though.

**Comment by skypjack** [comment]
I'll probably remove `ENTT_ENABLE_ETO` and `ENTT_PRETTY_FUNCTION` shouldn't be redefined. The type info class is fully customizable already but this isn't the right way to do it.
Not sure about `ENTT_MAYBE_ATOMIC` though. If enabled, it forces using C++ atomics, that are the _preferred_ way to do it imho and already platform independent.

**Comment by Tyyppi77** [comment]
Yeah actually now that I think about it, since the library anyways has dependencies to the std library, depending on `std::atomic` seems very reasonable! So probably just changing `ENTT_ASSERT` is enough.
