### ISSUE TITLE
Segmentation fault entt::meta_any assignment to a class variable

### ISSUE THREAD

**Issue by avkudr** [skypjack/entt#404]
Hello!
I have a segmentation fault on ```entt::meta_any``` assignment operator (GCC compiler, did't try with others). Here is the example allowing to reproduce the problem. I am trying to assign a meta_any to a class variable...

```
struct B{
    B() {
        entt::meta<B>()
            .type("ClassB"_hs)
            .data<&B::value>("value"_hs);
    }
    int value = 5;
};

struct Dummy{
    entt::meta_any value;
};

int main()
{
    Dummy d;
    B b;
    auto data = entt::resolve<B>().data("value"_hs);
    d.value = data.get(b); // seg fault here

    return (d.value == b.value) ? 0 : 1;
}
```
Thanks in advance.

**Comment by skypjack** [comment]
The problem is that `meta_any` within `Dummy` isn't initialized. It should be:
```
struct Dummy{
    entt::meta_any value{};
};
```
That said, I can add initializers to intercept and prevent this kind of errors user side. :+1:

**Comment by skypjack** [comment]
Nvm. A bug of clang 6 makes it ugly to modify, so I'll let it be. Thanks for pointing this out anyway. :+1:

**Comment by Kerndog73** [comment]
@skypjack What's preventing you from doing the way it was done in 3.2.2? Does the clang bug affect that version too?

**Comment by skypjack** [comment]
@Kerndog73 
The default-ed constructor default initialize data members, so the current form is equivalent to the one in 3.2.2 **but** neither this one nor that one would _solve_ this problem.
In fact, using `entt::meta_any value{};` rather than `entt::meta_any value;` gets the default-ed path and everything is properly initialized as expected.

**Comment by Kerndog73** [comment]
I'm not able to reproduce this bug on 3.2.2 (since it has a default constructor that actually initializes the members). `meta_any() = default` is not equivalent to 3.2.2. I think using an explicitly defaulted default constructor is a real design flaw.

**Comment by skypjack** [comment]
Let's reopen this and make a try. :+1:

**Comment by Kerndog73** [comment]
I see no reason not to restore the constructor from 3.2.2:

```C++
meta_any() ENTT_NOEXCEPT
        : storage{},
          instance{nullptr},
          node{nullptr},
          destroy_fn{nullptr},
          copy_fn{nullptr},
          steal_fn{nullptr}
    {}
```

You could even shorten it a little by using `instance{}` instead of `instance{nullptr}`.
