### ISSUE TITLE
Using default constructible types shouldn't be a requirement

### ISSUE THREAD

**Issue by dBagrat** [skypjack/entt#405]
Unable to assign component that does not have a default constructor.

The problem occurs after the commit: https://github.com/skypjack/entt/commit/a984ce5bba06b8bb03b6ef610f4b2c14f3fae9e3

**Comment by skypjack** [comment]
Yup, confirmed on `master` only.
I'm rollbacking the changes and adding a test to avoid the same mistake in future.
Thanks for pointing this out. :+1:
