### ISSUE TITLE
empty components causing warning in registry::replace

### ISSUE THREAD

**Issue by RafeWoo** [skypjack/entt#407]
First of all, thanks for your great library. 
I'm currently playing around with it and enjoying myself so far.

I have hit a problem though. I just switched from #including the single header to individual headers. 
and the code stopped compiling due to this warning

    entt\entity\registry.hpp(123): warning C4172: returning address of local variable or temporary

The warning only occurs if I try to assign empty components like a tag to an entity.

The first thing I noticed was that the code in the basic_registry::pool_handler::replace function is different between the single_include and individual registry.hpp. In the single header there is a test for empty types. (Are there any plans to keep the single header in sync?)
It looks like in December 2019 the ETO check was removed quite intentionally but if I add it back in the code seems to work.
  
    template<typename... Args>
        decltype(auto) replace(basic_registry &owner, const Entity entt, Args &&... args) 
    {
    #ifdef USE_ETO_TEST
            if constexpr (ENTT_ENABLE_ETO(Component)) {
                ENTT_ASSERT((storage<Entity, Component>::has(entt)));
                update.publish( owner, entt, Component{});
                return Component{ std::forward<Args>(args)... };
            }
            else {
                Component component{ std::forward<Args>(args)... };
                update.publish(owner, entt, component);
                return (this->get(entt) = std::move(component));
            }
    #else
             Component component{std::forward<Args>(args)...};
             update.publish(owner, entt, component);
             return (this->get(entt) = std::move(component));
    #endif
    }

I'm using the latest master build.
I'm using VS2017 and compiling with warnings as errors.

What I think is happening is this:  On the last line, this->get() is returning by value for empty structs,  then the assignment operator is returning a reference to the local value which is being returned from the replace function as a whole triggering the warning.

Thank you again.

**Comment by skypjack** [comment]
Afaik it's an issue of VS2017 that has been solved in VS2019.
Actually, the function doesn't return a reference to a local variable. The warning is wrong.
I'd suggest either to update your VS or not to treat warnings as errors. However, if you know how to suppress it, please let me know and I can apply your changes to `master`.
Since I'm not working on Windows and even less with VS2017, I've some problems to experiment in this sense.

**Comment by RafeWoo** [comment]
Thanks for prompt response. I've added a pull request that fixes the warning by adding a replace method to the storage class.

I get the warning in vs2019 as well. I think it's a genuine warning although I don't see it as particularly dangerous to get a reference to an empty object.  Perhaps the compilers you're using do a better job of optimising away the assignment.

Thanks for your time.

**Comment by skypjack** [comment]
Oh, I see. I wanted to perfect forward the return type of the underlying `get` here but the assignment operator is the expression being evaluated by `decltype(auto)`.
So, the fix seems easy. Just splitting the whole thing in two parts should suppress the warning.
