### ISSUE TITLE
Wrong guard for attribute.h

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#410]
`attribute.h` uses `ENTT_LIB_ATTRIBUTE_H` rather than `ENTT_CORE_ATTRIBUTE_H`.
Thanks to @Kerndog73 for pointing this out. :+1:

**Comment by Kerndog73** [comment]
Would if make sense for `attribute.h` to be moved into the `config` directory? Also, is there any reason for using `.h` instead of `.hpp`? It seems a little odd but I don't use these headers so I don't care!

**Comment by skypjack** [comment]
I put it under `core` because _in theory_ it's something that can be reused and has nothing to do with configuration in general (even though this is arguable). It depends on the config though, like many other parts of the library.
`.h` vs `.hpp` is due to the fact that it contains only a bunch of macros, no functions nor classes. I usually use `.hpp` when the file contains a fully defined class template or some function templates. It's more a matter of tastes here.
