### ISSUE TITLE
Define a nice type alias for ENTT_ID_TYPE

### ISSUE THREAD

**Issue by Tyyppi77** [skypjack/entt#416]
With the new visitation API, `ENTT_ID_TYPE` can be used a lot more in userspace, so it would be nice to able to write for an example `std::vector<entt::id_type>` instead of `std::vector<ENTT_ID_TYPE>`. I propose adding a `using id_type = ENTT_ID_TYPE` (or something similarly named) to somewhere within EnTT.

**Comment by qiujiangkun** [comment]
I agree with you. With a prettier name codes will be much better

**Comment by skypjack** [comment]
Yup. This is an accepted request.
It's just a matter of finding the time to work on it since I've a few things with higher priority for my own projects in the pipeline.
This will enter `master` soon though, don't worry. :+1:
