### ISSUE TITLE
C4706 in meta.hpp

### ISSUE THREAD

**Issue by BrodyHiggerson** [skypjack/entt#420]
> entt\meta\meta.hpp(536): warning C4706: assignment within conditional expression

Build flags are:
/W4 
/WX (warnings as errors)
/std:c++latest
/permissive-

_Compiling using VS 2019 16.5.0 Preview 2.0_

Fixed locally by modifying convert() like so:

```
     /**
     * @brief Tries to convert an instance to a given type.
     * @tparam Type Type to which to convert the instance.
     * @return True if the conversion is possible, false otherwise.
     */
#pragma warning( push )
#pragma warning( disable : 4706 )
    template<typename Type>
    bool convert() {
        bool valid = (node && node->id == internal::meta_info<Type>::resolve()->id);

        if(!valid) {
            if(auto any = std::as_const(*this).convert<Type>(); (valid = static_cast<bool>(any))) {
                swap(any, *this);
            }
        }

        return valid;
    }
#pragma warning( pop )
```

**Comment by Kerndog73** [comment]
`/W4` and `/WX` is really not a good combo. It's like `-Weverything -Werror`.

**Comment by BrodyHiggerson** [comment]
All of my projects and dependencies pass under this combo - it's strict and I like it.

**Comment by skypjack** [comment]
That's the only warning treated as error in `EnTT` with this combo?

**Comment by BrodyHiggerson** [comment]
@skypjack the only one so far. I'm not including/using all features or headers just yet :) 

Anything widespread and intrusive to fix I can suppress at the whole-project level or in a fork if I really have to, but is not so desirable.

**Comment by BrodyHiggerson** [comment]
Actually, I am suppressing the following at the project level

C4201 // Nonstandard extension used: nameless struct/union
C4100 // Unreferenced formal parameter

I think it was a warning-heavy dependency like RakNet that forced me to use these. Not sure about EnTT.

**Comment by Innokentiy-Alaytsev** [comment]
I defined two macros (one pushes warning disabling pragma, the other pops it) to deal with warning noise in dependencies. I call the first macro before including the noisy dependency and the second macro after including. Not intrusive, does not require to change whole project warning settings, quite explicit that is something some people like.

**Comment by skypjack** [comment]
Upstream on `experimental`.
