### ISSUE TITLE
Error packaging entt, confusing paths for EnTTConfig.cmake

### ISSUE THREAD

**Issue by pmiddend** [skypjack/entt#421]
Hi! I was just going to package entt using the [Nix package manager](https://nixos.org/nix/). Usually, with cmake-based projects, there isn't much to do. Just specify the dependencies and everything else is automagical. With entt, there's something strange, however.

Installation fails because:

```
file INSTALL cannot find
  "/build/entt-3.2.2/build//nix/store/m35413in5rsdzwfpil6jwmgbv67igka7-entt-3.2.2/lib/cmake/entt/EnTTConfig.cmake":
  No such file or directory.
```

After some debugging, I found the following statement(s) in `CMakeLists.txt` to be the culprit:

```
configure_package_config_file(
    cmake/in/EnTTConfig.cmake.in
    ${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake
    INSTALL_DESTINATION ${CUSTOM_INSTALL_CONFIGDIR}
    PATH_VARS CMAKE_INSTALL_INCLUDEDIR
)
...
install(
    FILES
        ${EnTT_BINARY_DIR}/${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake
        ${EnTT_BINARY_DIR}/EnTTConfigVersion.cmake
    DESTINATION ${CUSTOM_INSTALL_CONFIGDIR}
)
```

Removing the line:

```
${EnTT_BINARY_DIR}/${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake
```

Makes entt build and install and I can use it then. I cannot (yet) tell you exactly what Nix does with respect to cmake. However, the code above looks a little fishy to me. Why is there a call to `configure_package_config_file` specifying `${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake` as the destination (and a corresponding `INSTALL_DESTINATION ${CUSTOM_INSTALL_CONFIGDIR}`), and then an explicit `install` for this file, but using `EnTT_BINARY_DIR`? This seems redundant. Is there a reason for doing it this way?

**Comment by skypjack** [comment]
I don't remember the details (this part was written long time ago) but afaik it's to allow installing `EnTT` in the build directory, then finding it directly from an outer project that includes the library.

**Comment by OvermindDL1** [comment]
The `<ProjectName>Config.cmake` file is the file that let's cmake know all the locations, build options, etc... of the built library, it definitely should be installed.  It would probably be better to say what error message nix is giving you instead of breaking installed cmake usage of this library.

**Comment by pmiddend** [comment]
@OvermindDL1 I absolutely agree that this file should be installed, and in fact, it is installed, even without the explicit `install` line. The confusing thing about this line isn't whether the file is supposed to be installed or not, it's the mention of `${EnTT_BINARY_DIR}` in the installation path. This is what trips Nix up (which seems to be fine with hundreds of other CMake-based projects).

**Comment by skypjack** [comment]
So, you suggestion is just to turn this:
```
install(
    FILES
        ${EnTT_BINARY_DIR}/${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake
        ${EnTT_BINARY_DIR}/EnTTConfigVersion.cmake
    DESTINATION ${CUSTOM_INSTALL_CONFIGDIR}
)
```
Into this:
```
install(
    FILES
        ${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake
        ${EnTT_BINARY_DIR}/EnTTConfigVersion.cmake
    DESTINATION ${CUSTOM_INSTALL_CONFIGDIR}
)
```
Did I get it right?

**Comment by pmiddend** [comment]
As I said in my original post, removing the line 
```
${EnTT_BINARY_DIR}/${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake
```
fixes the issue for me. The thing is, you're using the `INSTALL_DESTINATION` parameter for `CONFIGURE_PACKAGE_CONFIG_FILE`, which _already_ installs the `.cmake` file to `${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake` (as the name says). You might install it to _another_ destination using the `install` command, but specifying `${EnTT_BINARY_DIR}/${CUSTOM_INSTALL_CONFIGDIR}/EnTTConfig.cmake` apparently isn't portable.

**Comment by skypjack** [comment]
Let's see if @m-waka can help us.
If I remember right, that part is due to one of his PR. Maybe he can tell us why the `install` command has this form, what was the goal originally. :+1:
