### ISSUE TITLE
registry.replace examples wrong?

### ISSUE THREAD

**Issue by pmiddend** [skypjack/entt#422]
Reading the Wiki, it says that you can replace a component like this:

```
registry.replace<position>(entity, [](auto &pos) { pos.x = pos.y = 0.; });
```

This doesn't compile in my examples, though, and the code doesn't really indicate that `replace` takes a function. Is that old code, maybe?

**Comment by skypjack** [comment]
The wiki refers to `master` and I've pushed this change an hour ago or so.
Maybe a pull can solve the problem. [This](https://skypjack.github.io/entt/) is the documentation for the last stable release instead.

**Comment by pmiddend** [comment]
Ah, I see, so `replace` doesn't exist in that form yet, thanks!
