### ISSUE TITLE
Simplified loader syntax

### ISSUE THREAD

**Issue by sunbubble** [skypjack/entt#423]
Maybe you could provide a simplified resource loader wrapper in your examples for the trivial case:
```c++
template<typename Resource>
struct Loader : entt::loader<Loader<Resource>, Resource>
{
    auto load(Resource value) const { return std::make_shared<Resource>(std::move(value)); }
};
```

usage example:
```c++
cache.reload<Loader<SomeType>>(entt::hashed_string(path.c_str()), someValue);
```
Or does it not make sense to use it this way?

**Comment by skypjack** [comment]
Roughly speaking, you can use it this way but it doesn't make much sense since the loader isn't loading anything.
Here you're passing a resource from outside and the loader is just forwarding it as an output.
Do you see it?

**Comment by sunbubble** [comment]
Let me see whether I get your point. Fundamentally, the only difference from the wiki example is that you construct the resource in the load method (instead of moving it in. Thus, the user of the loader needs to know how to load the resource before passing it to the cache, adding one unnecessary step to the process.

So by templating the loader, while reducing the boilerplate, I'm offloading the code and responsibility of correctly loading the resource to the user, which in your mind should be encapsulated within the loader. Correct?

**Comment by skypjack** [comment]
Exactly. Imagine a loader for an `SDL_Texture`, you could define it as:
```
struct texture_loader: public entt::loader<texture_loader, texture> {
    std::shared_ptr<texture> load(SDL_Renderer *, const char *) const;
};
```
Where the first argument is the rendered used to create the texture and the second argument is the path of the resource.
Then you use this loader to load an SDL texture in the cache eg using SDL image **but** keep in mind that the same cache can also accept textures from a loader that generates them on the fly or  creates them as a combination of other textures and so on.
From the point of view of the user of the cache, who cares how a texture is created (or loaded) before to enter the cache itself? This is why things are decoupled this way.

Does it make sense now or I haven't found the right wording to explain it yet?

**Comment by sunbubble** [comment]
Makes perfect sense, thanks.

**Comment by skypjack** [comment]
You're welcome. Can I close the issue or are there other questions?

**Comment by sunbubble** [comment]
That would be all :)
