### ISSUE TITLE
use entt in many DLL applications

### ISSUE THREAD

**Issue by Logris** [skypjack/entt#426]
![Application](https://user-images.githubusercontent.com/11351972/75169974-7754fe80-573a-11ea-9876-db47cea3cf3c.png)

I made small edits that fixed this problem

```
namespace entt
{
extern ENGINE_API ENTT_MAYBE_ATOMIC(ENTT_ID_TYPE) g_id;
extern ENGINE_API std::map<std::uint32_t, ENTT_ID_TYPE> g_map_ids;

template <typename T>
uint32_t type_of()
{
    static const std::uint32_t id{ entt::hashed_string(__FUNCSIG__) };
    return id;
};

template<typename T>
ENTT_ID_TYPE get_type_id()
{
auto id = type_of<T>();
    if (auto it = g_map_ids.find(id); it != g_map_ids.end()) {
        return it->second;
    }
    auto [it, ok] = g_map_ids.insert({ id, ++g_id });
    return it->second;
}

template<typename T>
ENTT_ID_TYPE get_runtime_id()
{
    static const ENTT_ID_TYPE id = entt::get_type_id<T>();
    return id;
}
}
```

and in single_include/entt/entt.h
```
template<typename Entity>
class basic_registry {
........................
    template<typename Type, typename Family>
    static ENTT_ID_TYPE runtime_type() ENTT_NOEXCEPT {
        if constexpr(is_named_type_v<Type>) {
            return named_type_traits_v<Type>;
        } else {
            //return Family::template type<std::decay_t<Type>>;
            return get_runtime_id<std::decay_t<Type>>();
        }
    }

.......................
}
```

the function `entt::get_type_id()` 
will be called once for the type for each *.dll

**Comment by Innokentiy-Alaytsev** [comment]
What version of EnTT are you using? As of v3.3.0 it should be possible to make all this work out of the box: define `ENTT_API_IMPORT` when building the consumers of the libraries and `ENTT_DLL_EXPORT` for your libraries. However, I'm not sure how it will work in case of multiple libraries that you have. TO fix it you may try to redefine the `ENTT_API` to match you export macro at the project level, i.e. `-DENTT_API=ENGINE_API` or something similar.

**Comment by Innokentiy-Alaytsev** [comment]
A side note: the single header version may be out of date for v3.3.0 - check the normal version first.

**Comment by Logris** [comment]
I use v.3.3.0 - single header version

Innokentiy, you can communicate with you, for example, in whatsapp?

**Comment by skypjack** [comment]
It's unlikely that you're using v3.3.0 since things like `named_type_traits` or `runtime_type` are no longer there.
The latest release relies on the `type_info` class and the problem you're trying to solve is no longer there afaik.

From my point of view, this issue is invalid.

**Comment by Innokentiy-Alaytsev** [comment]
@skypjack The single-header version was not updated for the v3.3.0 release so all the named-types machinery is still there. I'm speaking about [the tagged version](https://github.com/skypjack/entt/blob/v3.3.0/single_include/entt/entt.hpp#L1220) - I know that you've added a GH Action for updating it.

**Comment by Innokentiy-Alaytsev** [comment]
@Logris I'll dare to go against the hierarchy and invite you to the (EnTT Gitter channel](https://gitter.im/skypjack/entt) where you can get more answers 😉

**Comment by skypjack** [comment]
I'm closing this as _invalid_. Let us know if you've any other problem with the latest version. Thanks.
