### ISSUE TITLE
Requirements of Output Archive Do NOT Match the Ducumentation

### ISSUE THREAD

**Issue by qiujiangkun** [skypjack/entt#431]
```cpp
    class json_archive {
        public:
            void operator()(entt::entt_traits<unsigned int>::entity_type ent) {
                std::cerr << ent << std::endl;
            }

            void operator()(entt::entity ent) {
                std::cerr << entt::to_integral(ent) << std::endl;

            }
            template <typename T>
            void operator()(entt::entity ent, const T &data) {
                std::cerr << entt::to_integral(ent) << std::endl;
            }
        };

```
I did several tests about the three functions.
1) The first function is used to indicate the size of a list (depending on which part of entities the user wants)
2) The second function tells each entt::entity
3) The third one saves all specified components alongside entt::entity

I followed strictly the document, which DID mention that I should save the size of list. However without the first function, I coundn't compile it at all. My compiler is GCC 9.2.0.

I think it's better to improve the document by adding more information like this:

https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#archives

```text
An output archive, the one used when creating a snapshot, must expose a function call operator with the following signature to store entities:
void operator()(entt::entt_traits<T>::entity_type ent);
entt::entt_traits<T>::entity_type is interchangable with ENTT_ID_TYPE, or just some integral types.
Note that all the member functions of the snapshot class make also an initial call to this endpoint to save the size of the set they are going to store.

void operator()(entt::entity);
Where entt::entity is the type of the entities used by the registry. 
In addition, an archive must accept a pair of entity and component for each type to be serialized. Therefore, given a type T, the archive must contain a function call operator with the following signature:

void operator()(entt::entity, const T &);
The output archive can freely decide how to serialize the data. The register is not affected at all by the decision.
```

**Comment by qiujiangkun** [comment]
So does input archive

**Comment by qiujiangkun** [comment]
Consider making base classes like iarchive and oarchive for user to inherit from, with pre-defined operator() functions.
Because of the templated arguments, this won't affect existing codes nor the interface.

**Comment by skypjack** [comment]
I'll update the documentation to make what you point out explicit. However:

>Consider making base classes like iarchive and oarchive for user to inherit from

To be honest, I think the snapshot part is to be deprecated rather than investing in it.
When I wrote that part, the API of the registry was smaller than what you see today. In particular, there weren't the range-* functions.
The snapshot is an utility but you can do much more by working directly with the registry nowadays. Therefore, an investment in that part doesn't seem a good choice.

**Comment by qiujiangkun** [comment]
I read relevant codes and basically now understand how snapshot works. However, when I was reading codes about runtime_view, it seems quite the opposite.
```txt
 * @warning
 * Lifetime of a view must overcome the one of the registry that generated it.
 * In any other case, attempting to use a view results in undefined behavior.
```
I think it's `Lifetime of a view cannot overcome the one of the registry that generated it.`

**Comment by skypjack** [comment]
>I think it's `Lifetime of a view cannot overcome the one of the registry that generated it.`

Yeah, good point. My fault. :smile: :+1:
