### ISSUE TITLE
[v3.3.0] Changed behaviour of meta-types resolution when working across boundaries

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#432]
As of version 3.3.0 the behaviour of meta-types resolution by type (i.e. `entt::resolve<T>()`) have changed - local meta-types definitions are prioritised now instead of global definitions as happened before. This change is intentional and aims at minimising of meta-context pollution by linked and dynamically loaded libraries.

An example of the project structure that allows reproducing the issue:
`lib.cpp` - a linked library (i.e. linked by the linker and not dynamically loaded via `dlopen()`):
```c++
#include <entt/core/attribute.h>
#include <entt/core/hashed_string.hpp>
#include <entt/meta/factory.hpp>
#include <entt/meta/meta.hpp>
#include "types.h"

ENTT_API void set_up(entt::meta_ctx ctx) {
    entt::meta_ctx::bind(ctx);

    entt::meta<std::int32_t> ()
        .alias (entt::type_info<std::int32_t>::id ())
        .ctor< std::int8_t > ()
        .ctor< std::uint8_t > ()
        .ctor< std::int16_t > ()
        .ctor< std::uint16_t > ()
        .conv< std::int64_t > ()
        .conv< float > ()
        .conv< double > ();
}

ENTT_API void tear_down() {
    entt::meta<std::int32_t> ().reset ();
}

ENTT_API entt::meta_any create_my_position () {
    auto const my_position_meta_type = entt::resolve ("my_position"_hs);

    if (!my_position_meta_type) {
        return {};
    }

    int ctr = 42;

    auto my_position_any = my_position_meta_type.construct ();

    my_position_meta_type.data ([&ctr, &my_position_any](auto const& i_meta_data) {
        auto const meta_data_type = i_meta_data.type ();

        if (auto const ctor_from_int = meta_data_type.ctor<int> ()) {
            i_meta_data.set (my_position_any, ctor_from_int.invoke (ctr++));
        }
    });

    return my_position_any;
}

ENTT_API bool my_position_f (entt::meta_any const& i_my_position) {
    return bool (i_my_position.type ().func ("f"_hs).arg (0).ctor<int>());
}
```

`main.cpp` - the executable linked against the library refined by the `lib.cpp`:
```c++
#include <gtest/gtest.h>
#include <entt/core/attribute.h>
#include <entt/meta/factory.hpp>
#include <entt/meta/meta.hpp>
#include "types.h"

ENTT_API void set_up(entt::meta_ctx);
ENTT_API void tear_down();

ENTT_API entt::meta_any create_my_position ();
ENTT_API bool my_position_f (entt::meta_any const& i_my_position);

struct my_position {
    int x;
    int y;

    void f (int) {};
};


TEST (ResolveFailure, Meta) {
    set_up (entt::meta_ctx{});

    entt::meta<my_position> ()
        .alias ("my_position"_hs)
        .ctor<> ()
        .data<&my_position::x> ("x"_hs)
        .data<&my_position::y> ("y"_hs)
        .func<&my_position::f> ("f"_hs);

    auto const my_position_any = create_my_position ();

    ASSERT_TRUE (my_position_any);

    EXPECT_EQ (my_position_any.type ().data ("x"_hs).get (*my_position_any).cast<int> (), 42);
    EXPECT_EQ (my_position_any.type ().data ("y"_hs).get (*my_position_any).cast<int> (), 43);

    EXPECT_TRUE (my_position_f (my_position_any));

    tear_down ();
}
```

Here the meta-types are resolved from the global context in case of resolution by name and from the local context in case of resolution by type. The resolution by type happens for constructors and other meta-function arguments.

One of the examples of the scenario above is an application-level base components library that registers basic meta-types and provides deserialisation functions.

A possible solution is allowing the user to control the context used for resolving meta-types, including meta-types of the nested meta-items (data, functions, constructors, conversion functions).

**Comment by Innokentiy-Alaytsev** [comment]
It should be noted that the default behaviour depends on the visibility settings. If the default visibility is `visible` then the meta-type resolution always looks up the global context for the linked libraries. If the default visibility is `hidden` then the meta-type resolution works as described above and prioritises the local context.

**Comment by skypjack** [comment]
>This change is intentional and aims at minimising of meta-context pollution [...] the meta-types are resolved from the global context in case of resolution by name and from the local context in case of resolution by type

Yup, this is exactly the purpose. A meta type is self contained and always refer to its context **but** you can search meta types from other contexts by name from the user side.

>A possible solution is allowing the user to control the context used for resolving meta-types, including meta-types of the nested meta-items (data, functions, constructors, conversion functions).

:thinking: How exactly? The only thing I can come up with right now is a traits based solution like:
```
template<typename, typename = std::void_t<>>
struct resolve_function { static auto constexpr value = &default_resolve_function; };
```
This is out of my mind, I don't expect it to be working code. It's just to give you an idea.
The aim is to provide a tool you can specialize on a per-type, per-traits and globally, so as to allow any level of granularity.

>It should be noted that the default behaviour depends on the visibility settings.

This isn't correct actually.
Visibility affects the way a linker works. When you use public visibility (either default visibility on linux or the `dllimport`/`dllexport` stuff on Windows), you don't have two contexts. Everything is bound at runtime and both the sides of a boundary refer to the same variables.
In other terms, it's as if you had a single bigger context by construction rather than two separate contexts. Therefore the way meta works is consistent in this case.

**Comment by Innokentiy-Alaytsev** [comment]
> ... Therefore the way meta works is consistent in this case.

I was not clear enough. I understand why `meta` works the way it does in this case. What I meant was that type resolution behaves differently when the same application is built on different platforms with the "standard" visibility settings for this planform. I.E. the same code will behave as if it has multiple contexts on Windows and one global context on Linux. This is not a problem or an error per se, but I think it worth mentioning this fact in documentation because such behaviour may be unexpected for the library end-user who just "uses the defaults".

**Comment by skypjack** [comment]
>I think it worth mentioning this fact in documentation

Yup. Actually on Windows the way to _simulate_ default visibility is by using `ENTT_STANDARD_CPP`. It disables the constexpr stuff and uses `dllimport`/`dllexport` instead.

I don't even know how to explain it to someone that doesn't know already how this stuff works! :smile:

**Comment by Innokentiy-Alaytsev** [comment]
I think I have a solution for this, the one you kinda mentioned. 

The main problem comes from primitive types or other types that are considered "basic" within the context of an application. For these types, it should be possible to define an inline function or a type list that is used on the side interested in those type for binding them locally without naming (i.e. for resolution by type). All the other types that are not primitive and are supposed to be resolved by name (for (de)serialisation and other purposes) are registered in the usual way with an `entt::meta_ctx` instance passed into a (possibly not inline) function defined by the library during its initialisation.

**Comment by skypjack** [comment]
Not sure I get what you mean.
How would you set these types? Can you provide an example of use user side?

**Comment by Innokentiy-Alaytsev** [comment]
**Disclaimer**: The code below is based on my understanding of how things work.

For the primitive and other "basic" within application types the following idea applies:
`library.hpp`:
```c++
inline void RegistedBasicMetaTypes () {
 entt::meta<int>(); // With all the required constructors and conversion stuff and no alias.
 entt::meta<char>(); // With all the required constructors and conversion stuff and no alias.
 entt::meta<float>(); // With all the required constructors and conversion stuff and no alias.
 entt::meta<double>(); // With all the required constructors and conversion stuff and no alias.
 entt::meta<std::string>(); // With all the required constructors and conversion stuff and no alias.
}

void RegisterLibraryMetaTypes(entt::meta_ctx meta_ctx);
```
`library.cpp`:
```c++
void RegisterLibraryMetaTypes(entt::meta_ctx meta_ctx) {
 RegisterBasicMetaTypes();

 entt::meta_ctx::bind (meta_ctx);

 entt::meta<PublicLibType1>().alias("PublicLibType1"_hs); // With all the required stuff.
 entt::meta<PublicLibType2>().alias("PublicLibType2"_hs); // With all the required stuff .

 entt::meta<SharedLibType>(); // With all the required stuff but no alias.
}
```
`app.cpp`
```c++
void main() {
 RegisterBasicMetaTypes();

 RegisterLibraryMetaTypes(entt::meta_ctx{});

 entt::meta<AppType1>().alias("AppType1"_hs); // With all the required stuff.
 entt::meta<AppType2>().alias("AppType1"_hs); // With all the required stuff .

 entt::meta<SharedLibType>(); // With all the required stuff but no alias.
}
```

If I understand the mechanics correctly, basic types will be registered in the local meta-context in both cases, so both library and application meta-types have access to the same definition of the basic types. At the same time, no meta-context pollution occurs, and each side can have its meta-definition of types. So `SharedLibType` can have different meta-definition on each side of the boundary.

**Comment by skypjack** [comment]
So, `app.cpp` incluse `library.hpp`? Did I get it correctly?

**Comment by Innokentiy-Alaytsev** [comment]
Yup. I just ignored all the includes) Will it work the way I expect?

**Comment by Innokentiy-Alaytsev** [comment]
I've checked the proposed solution and it does work. Of course, there are some complications in my case: due to how Catch2 works, I need to properly unbind types in each test that I do with an RAII tool. This applies to both basic types and other library-defined types so I can't use the same function in both cases. But it doesn't matter much - this issue is very resolvable with a type list and a function accepting it.

**Comment by skypjack** [comment]
So, what do you suggest for the issue?

**Comment by Innokentiy-Alaytsev** [comment]
I'll provide you with my solution later this day or tomorrow. It's a bit overcomplicated, which is quite unexpected, but it works fine, doesn't seem to break anything and seems to conform the overall idea of context isolation.

**Comment by Innokentiy-Alaytsev** [comment]
# Motivation

I want to be able to register and unregister meta-types within the local and
global context and be able to do it effectively (whatever it means). I expect
to need to register many types quite often due to the presence of unit-tests and
how Catch2 library is working. At the same time, I expect to have quite a lot of
meta-types defined in different header files. I want to be able to support
plugins in case I ever decide that I need them.

# Method

I've split the problem into several parts:
1. Definition of the meta-type information.
2. Registration of a single set of types.
3. Registration of multiple sets of types.
4. Unregistering meta-types.

## Definition of the meta-type information

I want to have meta-information as for a type to be defined as close to the type
definition as possible and to be able to access it from anywhere. This means
that I have to be able to define it in a header file without violating ODR.

The first approach I tried was similar to how named types worked: I had a
templated struct with a static function `Register()`, that was specialised for
every type I want to register with meta-system. The "Register()` function had a
default implementation, that registered a meta-type with a default alias and
without any meta-members. The downside of this approach was that the templated
class has to be specialised in the global namespace. This prevents bringing
meta-type definition as close as possible to the actual type definition.

While resolving this issue, I decided to change the approach. The new approach
is based on using a templated function, that is looked up through ADL and allows
control over the locality of meta-type registration. By default, the function
asserts that the type was not registered to prevent missing meta-type
definitions:

```c++
template < class TType, class TAliasMode >
void RegisterMetaType (meta::AnchorContainer< TType >, TAliasMode)
{
    static_assert (
        sizeof (TType) < 0,
        "Unregistered type: provide specialisation of the "
        "RegisterMetatype(asclepia::ecs::meta::AnchorContainer) function");
}
```

Here, the `TType` stands for the type for which the meta-type is registered and
`TAliasMode` stands for a tag-type controlling generation of an alias and thus
the locality of meta-type registration. The following tag-types are provided:

```c++
namespace meta {
    struct NoAlias {
    };

    struct WithAlias {
    };
```

`AnchorContainer` is a type-contained struct used for ADL lookup.

The user is free to define the function anywhere he wants, but I'm lazy so I
defined a macro for that:

```c++
#define ASCLEPIA_ECS_META_TYPE_REGISTRATION_IMPL(i_type, i_alias, ...)         \
    [[maybe_unused]] auto meta_factory = [] {                                  \
        if constexpr (::std::is_same_v<                                        \
                          TAliasMode,                                          \
                          ::asclepia::ecs::meta::WithAlias >)                  \
        {                                                                      \
            return ::entt::meta< i_type > ().alias (i_alias);                  \
        }                                                                      \
        else                                                                   \
        {                                                                      \
            return ::entt::meta< i_type > ();                                  \
        }                                                                      \
    }() __VA_ARGS__;                                                           \
                                                                               \
    static_assert (true)


#define ASCLEPIA_ECS_META_TYPE_REGISTRATION(i_type, i_alias, ...)              \
    template < class TAliasMode >                                              \
    void RegisterMetaType (                                                    \
        ::asclepia::ecs::meta::AnchorContainer< i_type >, TAliasMode)          \
    {                                                                          \
        ASCLEPIA_ECS_META_TYPE_REGISTRATION_IMPL (                             \
            i_type, i_alias, __VA_ARGS__);                                     \
    }                                                                          \
                                                                               \
    static_assert (true)


#define ASCLEPIA_ECS_META_TYPE_REGISTRATION_NS(                                \
    i_namespace, i_type, i_alias, ...)                                         \
    ASCLEPIA_ECS_NAMESPACE_OPEN                                                \
                                                                               \
    template < class TAliasMode >                                              \
    void RegisterMetaType (                                                    \
        ::asclepia::ecs::meta::AnchorContainer< i_namespace::i_type >)         \
    {                                                                          \
        using i_type = i_namespace::i_type;                                    \
                                                                               \
                                                                               \
        ASCLEPIA_ECS_META_TYPE_REGISTRATION_IMPL (                             \
            i_type, i_alias, __VA_ARGS__);                                     \
    }                                                                          \
                                                                               \
    ASCLEPIA_ECS_NAMESPACE_CLOSE                                               \
                                                                               \
    static_assert (true)
```

`ASCLEPIA_ECS_META_TYPE_REGISTRATION` allows registering meta-types for types
within the namespace where they were defined, while
`ASCLEPIA_ECS_META_TYPE_REGISTRATION_NS` allows registering meta-types outside
of the type's parent namespace. The latter is useful for reflecting types from
foreign namespaces over which the user has no control, e.g. `std`. The
meta-information registration function is put into the library namespace so that
it's found without relying on ADL. For obvious reasons, this macro should be
called from the global namespace.

The signatures of both macros are simular:

* `i_type` - the name of the type for which the meta-type is registered;

* `i_alias` - the user-provided alias for meta-type; no assumptions are made
  here to give the user maximum control;

* `...` - `entt::meta_factory` member function invocations starting with a dot.

`ASCLEPIA_ECS_META_TYPE_REGISTRATION_IMPL` implements the basic logic of
meta-type registration:

1. It creates a meta-factory based on alias generation tag passed to the
   `RegisterMetaType()` function.

2. Expands the variadic macro arguments containing `entt::meta_factory` member
   functions invocations for registering meta-members of the meta-type.

An example invocation:

```c++
namespace asclepia {
    namespace ecs {
        UTK_TYPE_SAFE_STRONG_CLASS_TYPEDEF (Scale, ::glm::vec3)

        ASCLEPIA_ECS_META_TYPE_REGISTRATION (
            Scale,
            HS ("Scale"),
            .ctor<> ()
                .ctor< Scale::value_type > ()
                .ctor< Scale::value_type, Scale::value_type, Scale::value_type > ()
                .data< &Scale::x > (HS ("x"))
                .data< &Scale::y > (HS ("y"))
                .data< &Scale::z > (HS ("z")));
    }
}
```

A set of helper macros is provided for registering meta-types for primitive
types:


```c++
#define ASCLEPIA_ECS_ADDITIONAL_CONSTRUCTORS(...) __VA_ARGS__
#define ASCLEPIA_ECS_ADDITIONAL_CONVERSIONS(...) __VA_ARGS__

#define ASCLEPIA_ECS_NO_ADDITIONAL_CONSTRUCTORS
#define ASCLEPIA_ECS_NO_ADDITIONAL_CONVERSIONS
```

An example invocation:
```c++
namespace asclepia {
    namespace ecs {
        ASCLEPIA_ECS_PRIMITIVE_META_TYPE_REGISTRATION (
            std::int32_t,
            ASCLEPIA_ECS_ADDITIONAL_CONSTRUCTORS (.ctor< std::int8_t > ()
                                                      .ctor< std::uint8_t > ()
                                                      .ctor< std::int16_t > ()
                                                      .ctor< std::uint16_t > ()),
            ASCLEPIA_ECS_ADDITIONAL_CONVERSIONS (.conv< std::int64_t > ()
                                                     .conv< float > ()
                                                     .conv< double > ()));
    }
}
```

## Registration of a single set of types

Registration of a single set of types is performed with a combination of the
following functions:

```c++
template < class... TTypeConfig >
auto RegisterMetaTypes (meta::BindingConfigList< TTypeConfig... >)
{
    (RegisterMetaType (
         meta::Anchor< meta::TargetType< TTypeConfig > >,
         meta::AliasConfig< TTypeConfig >{}),
     ...);

    return &UnregisterMetaTypes< meta::TargetType< TTypeConfig >... >;
}


template < class... TTypeConfig >
auto RegisterMetaTypes ()
{
    return RegisterMetaTypes (meta::BindingConfigs< TTypeConfig... >);
}
```

The first function accepts a specialised type-list while the second is a simple
variadic template function. The `TTypeConfig` is any type that has a
meta-interface of an `std::pair`. The `meta::BindingConfigsList` is defined as
following:

```c++
namespace meta {
    template < class TTypeConfig_ >
    using TargetType = typename TTypeConfig_::first_type;

    template < class TTypeConfig_ >
    using AliasConfig = typename TTypeConfig_::second_type;


    template < class... TTypeConfig >
    struct BindingConfigList : TypeList< TTypeConfig... > {
        static_assert (
            (!::std::disjunction_v<
                ::std::is_same< TargetType< TTypeConfig >, meta::NoAlias >...,
                ::std::
                    is_same< TargetType< TTypeConfig >, meta::WithAlias >... >),
            "Using alias presence control tags is not allowed");

        static_assert (
            (::std::disjunction_v<
                ::std::is_same< AliasConfig< TTypeConfig >, meta::NoAlias >...,
                ::std::is_same<
                    AliasConfig< TTypeConfig >,
                    meta::WithAlias >... >),
            "The second element of the pair must be one of meta::NoAlias or "
            "meta::WithAlias");
    };


    template < class... TTypeConfig >
    static auto constexpr BindingConfigs =
        BindingConfigList< TTypeConfig... >{};
} // namespace meta
```

I'm hell-bent on validation of things so I try to catch the uses that are
invalid with the static assertions.

The meaning of returning an address of the `UnregisterMetaTypes()` function will
be explained later.


## Registration of multiple sets of types

Listing the types every time is cumbersome and error-prone: the more types you
have the more chances you have to forget a type. Same goes for the number of
places where you want to register meta-types. In this case, type lists appear to
save the day:

```c++
namespace meta {
    using BasicMetaTypesList = BindingConfigList<
        ::std::pair< int8_t, NoAlias >,
        ::std::pair< uint8_t, NoAlias >,
        ::std::pair< int16_t, NoAlias >,
        ::std::pair< uint16_t, NoAlias >,
        ::std::pair< int32_t, NoAlias >,
        ::std::pair< uint32_t, NoAlias >,
        ::std::pair< int64_t, NoAlias >,
        ::std::pair< uint64_t, NoAlias >,
        ::std::pair< float, NoAlias >,
        ::std::pair< double, NoAlias >,
        ::std::pair< void*, NoAlias >,
        ::std::pair< void const*, NoAlias >,
        ::std::pair<::std::string, NoAlias >,
        ::std::pair<::std::string_view, NoAlias >,
        ::std::pair< char*, NoAlias >,
        ::std::pair< char const*, NoAlias >,
        ::std::pair<::entt::entity, NoAlias >,
        ::std::pair<::entt::registry*, NoAlias >,
        ::std::pair<::entt::registry const*, NoAlias > >;
}
```

Here, a type list of meta-type binding configurations is built. All of the types
are considered basic so no alias is registered for each of them. The contents of
the list are the same as template arguments used when calling the
`RegisterMetaTypes()` function.

The idea here is that every time you have a header file with meta-types
definitions, you can define a separate type-list that is short and simple. For
registering the meta-types from multiple lists a separate function is used:

```c++
template < class... TTypeConfigList >
auto RegisterMetaTypeList ()
{
    static_assert (
        (IsSameTypeList< meta::BindingConfigList > (Type< TTypeConfigList >) &&
         ...),
        "meta::BindingConfigList are required");

    return RegisterMetaTypes (
        TypeListConcatenation< meta::BindingConfigList, TTypeConfigList... >{});
}
```

The static assertion check that each type list is a specialisation of the
`meta::BindingConfigList` (I think there should be a cover of Judas Priest's
"Hell Bent on Leather" called "Hell Bent on Safety"):

```c++
template <
    template < class... >
    class TExpected,
    template < class... >
    class TActual,
    class... TTypes >
constexpr bool IsSameTypeList (TypeContainer< TActual< TTypes... > >)
{
    return ::std::is_same_v< TExpected< TTypes... >, TActual< TTypes... > >;
}


template < template < class... > class TExpected, class TActual >
constexpr bool IsSameTypeList (TypeContainer< TActual >)
{
    return false;
}
```

The type lists are concatenated and sent to the `RegisterMetaTypes()` function
from above:

```c++
template <
    template < class... >
    class TResultList,
    template < class... >
    class TSingleList,
    class... TType >
auto ConcatenateTypeLists (TSingleList< TType... >)
{
    return TResultList< TType... >{};
}


template <
    template < class... >
    class TResultList,
    template < class... >
    class TFirstList,
    template < class... >
    class TSecondList,
    class... TFirstType,
    class... TSecondType >
auto ConcatenateTypeLists (
    TFirstList< TFirstType... >, TSecondList< TSecondType... >)
{
    return TResultList< TFirstType..., TSecondType... >{};
}


template <
    template < class... >
    class TResultList,
    class TFirstList,
    class TSecondList,
    class... TOtherList >
auto ConcatenateTypeLists (TFirstList, TSecondList, TOtherList...)
{
    return ConcatenateTypeLists< TResultList > (
        ConcatenateTypeLists< TResultList > (TFirstList{}, TSecondList{}),
        ConcatenateTypeLists< TResultList > (TOtherList{}...));
}


template < template < class... > class TResultList, class... TTypeList >
using TypeListConcatenation =
    decltype (ConcatenateTypeLists< TResultList > (TTypeList{}...));
```

In fact, I have also a function for removing duplicates but "something went
wrong" the first time I tried to apply it here:

```c++
template <
    template < class... >
    class TTypeList,
    class TType,
    class... TDistinctType >
auto BuildDistinctTypeList (
    TTypeList<>, TTypeList< TDistinctType... > i_distinct_types)
{
    return i_distinct_types;
}


template <
    template < class... >
    class TTypeList,
    class TType,
    class... TTypes,
    class... TDistinctType >
auto BuildDistinctTypeList (
    TTypeList< TType, TTypes... >,
    TTypeList< TDistinctType... > i_distinct_types)
{
    using DistinctTypes = ::std::conditional_t<
        HasType< TType > (i_distinct_types),
        TTypeList< TDistinctType... >,
        TTypeList< TDistinctType..., TType > >;

    if constexpr (0 < sizeof...(TTypes))
    {
        return BuildDistinctTypeList (
            TTypeList< TTypes... >{}, DistinctTypes{});
    }
    else
    {
        return DistinctTypes{};
    }
}


template < template < class... > class TTypeList, class... TType >
auto RemoveDuplicates (TTypeList< TType... > i_type_list)
{
    if constexpr (0 < sizeof...(TType))
    {
        return BuildDistinctTypeList (i_type_list, TTypeList<>{});
    }
    else
    {
        return i_type_list;
    }
}


template < class TTypeList >
using DistinctTypeList = decltype (RemoveDuplicates (TTypeList{}));
```

The problem may have something to do with deferred template processing of MSVC
(from what I know, I may be wrong on that).

## Unregistering meta-types

With meta-types registration working, how does one unregister the types? The
manual unregistering is cumbersome and error-prone. So let's use RAII:

```c++
class ASCLEPIA_ECS_EXPORT MetaTypesBinding {
public:
    using UnbindMetaTypesFunction = void (*) ();
    using BindMetaTypesFunction   = UnbindMetaTypesFunction (*) ();

    MetaTypesBinding (BindMetaTypesFunction i_bind_meta_types)
        : bind_meta_types_{i_bind_meta_types}
        , unbind_meta_types_{i_bind_meta_types ()}
    {
    }

    MetaTypesBinding (MetaTypesBinding&& i_src)
        : bind_meta_types_{i_src.bind_meta_types_}
        , unbind_meta_types_{i_src.unbind_meta_types_}
    {
        i_src.bind_meta_types_   = nullptr;
        i_src.unbind_meta_types_ = nullptr;
    }

    MetaTypesBinding (MetaTypesBinding const&) = delete;

    ~MetaTypesBinding ()
    {
        Unbind ();
    }

    MetaTypesBinding& operator= (MetaTypesBinding const&) = delete;

    MetaTypesBinding& operator= (MetaTypesBinding&&) = delete;

    void Bind ()
    {
        if (bind_meta_types_)
        {
            bind_meta_types_ ();
        }
    }

    void Unbind ()
    {
        if (unbind_meta_types_)
        {
            unbind_meta_types_ ();
        }
    }

private:
    BindMetaTypesFunction   bind_meta_types_   = nullptr;
    UnbindMetaTypesFunction unbind_meta_types_ = nullptr;
};
```

The code is pretty straight-forward and explains why the meta-types registration
functions return a pointer to a `UnregisterMetaTypes()` function specialisation
for the registered types. The nice feature of this implementation is that the
RAII container is not templated so it's possible to store instances of it in an
array or any other homogenous data structure. This may come in handy when
working with plugins (or may not).

In my unit-tests, I often need to register a bunch of meta-types used only in
tests, that rely on the basic meta-types. I also want to have meta-types from
the library available in case I need any of them. So I use something similar to
the following snippet:

```c++
using TestMetaTypesList = asclepia::meta::BindingConfigList<
    ::std::pair< AnotherEntityComponent, asclepia::meta::WithAlias >,
    ::std::pair< AnotherChildEntity, asclepia::meta::WithAlias >,
    ::std::pair< AnotherParentLink, asclepia::meta::WithAlias >,
    ::std::pair< BaseIntIdentifier, asclepia::meta::WithAlias >,
    ::std::pair< BaseStringIdentifier, asclepia::meta::WithAlias >,
    ::std::pair< EntityComponent, asclepia::meta::WithAlias >,
    ::std::pair< TestChildEntity, asclepia::meta::WithAlias >,
    ::std::pair< IntIdentifier, asclepia::meta::WithAlias >,
    ::std::pair< Lvl_1, asclepia::meta::WithAlias >,
    ::std::pair< Lvl_2, asclepia::meta::WithAlias >,
    ::std::pair< Lvl_3, asclepia::meta::WithAlias >,
    ::std::pair< ObjectComponent, asclepia::meta::WithAlias >,
    ::std::pair< ParentLink, asclepia::meta::WithAlias >,
    ::std::pair< PrefabTag, asclepia::meta::WithAlias >,
    ::std::pair< StringIdentifier, asclepia::meta::WithAlias > >;

auto ecs_meta_binding =
    asclepia::RegisterMetaTypesInContext (i_meta_ctx);

auto test_meta_binding =
    asclepia::MetaTypesBinding{&asclepia::RegisterMetaTypeList<
        asclepia::meta::BasicMetaTypesList,
        TestMetaTypesList >};

// The rest of the test.
```
This works very well with Catch2 that relies on RAII instead of `SetUp()`- and
`TearDown()` style functions.

# Resume

So that's it, an overcomplicated system for doing a simple thing. Sorry for
wasting your time;)

**Comment by skypjack** [comment]
Sorry if I'm late. It took me a while to go through all this but there were actually a lot of information here. :smile: 

Overall it seems to me that there isn't something to _add_ to `EnTT` but I may be wrong.
My impression is that this is a good solution that can work in user space and is subject to customization.
If I used it, I'd change already some parts to adapt them to my requirements but I'd also maintain the same design probably.

What's unclear from the whole description instead is _why_ this solves the problem in the title.
I suspect it's due to the fact that you export the same definitions for some types on the local contexts of both sides. Am I right?

---

Something made me realize that we can improve the API of the meta module instead:

>The manual unregistering is cumbersome and error-prone.

I looked into the current implementation and actually there isn't a `reset` function on the meta type object or similar. It means that something like this isn't possible:

```
entt::resolve([](auto type) {
    if(respect_my_condition(type)) {
        type.reset();
    }
});
```

Where `respect_my_condition` could be as simply as checking if it's a locally defined type, no matter if it had been attached to a shared context (here a type property is enough to disambiguate).
This should also indecently simplify the last part of your solution. Am I wrong?

**Comment by skypjack** [comment]
>Something made me realize that we can improve the API of the meta module instead

I realized also why it's not there already. `meta_type` holds a const reference to the underlying node and cannot really modify it.

**Comment by Innokentiy-Alaytsev** [comment]
>Overall it seems to me that there isn't something to add to EnTT but I may be wrong.

You are right, there is nothing to add to EnTT. At least I can't think of anything right now. The user-side solution is fine. It may worth noting it somewhere in the documentation or a kind of "tips and tricks" kind of blog post or article.

>What's unclear from the whole description instead is why this solves the problem in the title.
I suspect it's due to the fact that you export the same definitions for some types on the local contexts of both sides. Am I right?

As we discussed earlier, local meta-types definitions are used for meta-function arguments. The described solution solves my issue not because I use the same definition on each side (which is a kind of an implementation detail of the library), but rather because I register proper meta-types definition on the application side. As a result, the required constructors and other meta-things are present when I try looking for them.

>I realized also why this is not there already. meta_type holds a const reference to the underlying node and cannot really modify it.
Probably we discussed this already and agreed on something like that people can still attach reset functions to meta types, so who cares.

Yup, it was discussed and the resolution was more or less the same. I'm not sure I have any valuable input on this question right now.

**Comment by skypjack** [comment]
Ok. I've added a note in the TODO list.
I don't consider adding a `meta_type::reset` function high priority but I can see how it may be useful in many cases. Probably I'll add it soon.

I'm also closing the issue since we have no idea of what to do in `EnTT` other than what I mentioned.
Feel free to reopen it in case you've something more to add here. Thank you. :heart:
