### ISSUE TITLE
What's the best way to bridge Lua and EnTT?

### ISSUE THREAD

**Issue by qiujiangkun** [skypjack/entt#435]
Now I'm working on my lua scipt system. I'll use it for AI and map scripting.
I have my own systems, which supports finding a certain system without knowing its exact location and supports tree-like structure of systems. By doing so, I can easily replace each system. In other words, I use entt::registry only for map, not for system manager.

For data, currently I have my own serialization lib, which will turn all the component data to json. Then I can convert json to table for the sake of lua, or implement a RESTful API. Lua can simply "get" and "post" infomation. Data conversion is of no problem.

How about the events? Lua script should be able to emit, receive events. I come up with the idea that I could wrap entt::dispatcher and use the same method of serialization and conversion. Once c++-end receives events from lua, it tries to deserialize them. If successfull, now events are native events and enter the event system, otherwise events are treated as json string to be sent back to lua script.

Is there a better way to treat events?

```cpp
class System
{
protected:
    std::vector<System *> subsystems;
    System *parent;

public:
    virtual void configure()
    {
    }
    virtual void unconfigure()
    {
    }
    virtual void update(float delta)
    {
    }
    void updateAll(float delta)
    {
        foreach ([=](System *sys) {
            sys->update(delta);
        });
    }
    System(System *parent = nullptr) : parent(parent)
    {
    }
    virtual void initialize()
    {
    }
    template <class T>
    T *findSystem(bool assertion=true)
    {
        System *root = this;
        while (root->parent != nullptr)
            root = root->parent;
        T *objective = nullptr;
        root->foreach ([&](System *sys) {
            T *casted = dynamic_cast<T *>(sys);
            if (casted != nullptr)
                objective = casted;
        });
        if(assertion)
            assert(objective != nullptr);
        return objective;
    }
    void foreach (std::function<void(System *)> func)
    {
        func(this);
        for (auto &&sub : subsystems)
        {
            sub->foreach (func);
        }
    }

    const std::vector<System *> &getSubSystems() const
    {
        return subsystems;
    }

    System *getParent() const
    {
        return parent;
    }
    virtual ~System()
    {
        for (auto &&i : subsystems)
        {
            delete i;
        }
    }
    // This will retrieve the ownership
    void addSubSystem(System *sub)
    {
        assert(sub->parent == nullptr);
        sub->parent = this;
        subsystems.push_back(sub);
        sub->configure();
    }
    // Will return the ownership
    bool removeSubSystem(System *sub)
    {
        assert(sub->parent != nullptr);
        for (size_t i = 0; i < subsystems.size(); i++)
        {
            if (subsystems[i] == sub)
            {
                subsystems.erase(subsystems.begin() + i);
                sub->unconfigure();
                sub->parent = nullptr;
                return true;
            }
        }
        return false;
    }
};
```

**Comment by skypjack** [comment]
This is very application specific. It's hard to say what's the right way to do things in your case.
I rarely use the dispatcher, I prefer plain instances of `sigh` but it's a matter of tastes.
To erase C++ types, I use meta and work almost everywhere without knowing the actual types for my objects.

I'm tempted to say that if it works for you, than your approach is fine.
I can't really invest much time on understanding and trying to improve the design of users' applications, I'm sorry. :)

**Comment by skypjack** [comment]
If I can give you an advice, I'd join the gitter channel for this. I can try to reply there when I've time to do that and there are also many other users that can share their experiences.
Afaik a couple of them integrated lua with `EnTT`. :wink:

**Comment by qiujiangkun** [comment]
> If I can give you an advice, I'd join the gitter channel for this. I can try to reply there when I've time to do that and there are also many other users that can share their experiences.
> Afaik a couple of them integrated lua with `EnTT`.

Thanks a lot. I never heard about it before but I found it fantastic.

**Comment by skypjack** [comment]
The link is on the README file. :wink: 
Let's continue the discussion on gitter then. :+1: 
This is best suited for that channel imho.

**Comment by Innokentiy-Alaytsev** [comment]
@qiujiangkun [Antara SDK](https://github.com/KomodoPlatform/antara-gaming-sdk) may be of interest for you.

**Comment by qiujiangkun** [comment]
> @qiujiangkun [Antara SDK](https://github.com/KomodoPlatform/antara-gaming-sdk) may be of interest to you.
Yes, it's almost what I've been doing these days.

**Comment by Milerius** [comment]
https://github.com/KomodoPlatform/antara-gaming-sdk/tree/master/modules/lua/antara/gaming/lua
