### ISSUE TITLE
Bring back registry replace by value

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#437]
It seems the ability to do `registry.replace<component_type>(entity, component_instance)` has been deprecated.

I don't think this is a good idea because the alternatives are more verbose and imo unnecessarily so:
```
registry.replace<component_type>(entity, [&](auto &instance){ instance = new_instance; });
```
```
registry.get<component_type>(entity) = new_instance;
registry.replace<component_type>(entity); // Haven't actually tried this one, read about it on gitter
```

I was trying to find the rationale for deprecating the by-value version, and I can't seem to find it. I'd be really curious to know why it was deprecated.

Also, I think the effect of having the extra overload (replace with lambda) on compile times should be investigated. If that's the case I'd vote for renaming the lambda-based version to `in_place_replace`.

I personally find that reading the library source code is actually harder when there are lots of overloads, if one signature is significantly different to another such as the two versions of `replace`, I believe it warrants its own method name.

**Comment by Kerndog73** [comment]
> I personally find that reading the library source code is actually harder when there are lots of overloads, if one signature is significantly different to another such as the two versions of `replace`, I believe it warrants its own method name.

Ditto for `assign`. [I mentioned this in another comment.](https://github.com/skypjack/entt/pull/433#issuecomment-593185750)

**Comment by skypjack** [comment]
`replace` and `get_and_replace`?

**Comment by Lawrencemm** [comment]
`in_place_replace`. It rhymes, and is cool.
