### ISSUE TITLE
Undefined behaviour in range-assign

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#438]
I was reading through the code stumbled upon range-assign at [642](https://github.com/skypjack/entt/blob/50ba8c6c396f69e31876e7e4a248f3a0a7b2a819/src/entt/entity/registry.hpp#L642) and [661](https://github.com/skypjack/entt/blob/50ba8c6c396f69e31876e7e4a248f3a0a7b2a819/src/entt/entity/registry.hpp#L661).
I was initially confused by the difference between these functions until I found the relevant [unit test](https://github.com/skypjack/entt/blob/50ba8c6c396f69e31876e7e4a248f3a0a7b2a819/test/entt/entity/registry.cpp#L1143-L1177). It seems easy to mess these functions up. For example:

```C++
#include <iostream>
#include <entt/entity/registry.hpp>

int main() {
  entt::registry reg;
  std::vector<entt::entity> vec {reg.create(), reg.create()};
  reg.assign<float>(vec.begin(), vec.end(), 3);
  std::cout << reg.get<float>(vec[0]) << '\n';
  std::cout << reg.get<float>(vec[1]) << '\n';
}
```

Can you guess what the output of this program is?

```
5
5
```

I don't really know how `3` is being turned into `5.0f`. If you try some different numbers you get some interesting output. Assigning `1` results in `3 0`.

Maybe that example is a bit contrived (I'm not really using the function as intended and primitive types are rarely used as components) but the fact that it's even possible to do this without any assertions or compiler errors is a hole in the API.

**Comment by skypjack** [comment]
I think I'll rename the _basic_ `assign` to `assign_from_args` and reintroduce a `replace_from_args` to address #437. This should help to disambiguate the two cases where the template parameter pack makes things _odd_.
what do you think about?

**Comment by skypjack** [comment]
I introduce new functions to disambiguate the calls you mentioned. In particular: `patch`, `emplace`, `insert` and `emplace_or_replace`.
Old functions are still there but have been deprecated (as in `[[deprecate("...")]]`). They will be removed in future.

Let me know if this is the expected result. Ambiguity on `assign` has been drastically reduced imho. Moreover, the migration is smooth this way, since `assign` has been most likely largely used so far by all users of `EnTT`. :+1:

**Comment by Kerndog73** [comment]
I updated my example (`assign` -> `insert`) and I still get the same result (`3` becomes `5.0f`). There is still ambiguity between the two overloads of `insert`. My example is probably too contrived to be worth addressing but I do like the new names.

**Comment by Kerndog73** [comment]
After seeing the latest change, I'm convinced that this issue has been thoroughly resolved. The API is much clearer and easier to understand. Simply renaming some functions has had a huge impact. This is really great! You can close this when the changes are merged.

**Comment by skypjack** [comment]
Yup. I agree. Good suggestions are good suggestions, no doubts about it. :wink:
