### ISSUE TITLE
entt::registry::stamp() function signature clarification

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [skypjack/entt#445]
[Currently](https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L1579), the `entt::registry::stamp()` function has the following signature:
```c++
void stamp(const entity_type dst, const basic_registry &other, const entity_type src, exclude_t<Exclude...> = {})
```

How about renaming the `other` to `src_reg`? I misread this signature and thought that it should be the destination registry. I know that the documentation comment right above it has the required information but It's somewhat easy to skip and the signature is not informative in this aspect. The same idea goes for all related functions inside the registry.

**Comment by skypjack** [comment]
Wait. What version of `EnTT` is this? `stamp` no longer exists upstream.

**Comment by Innokentiy-Alaytsev** [comment]
This is fair for `master` and `v3.3.0`

**Comment by skypjack** [comment]
I'm closing this since I'm not updating the documentation for older versions. I'm sorry.
On the other side, I'm working to reintroduce a `stamp`-like function on `master`, so most likely you won't need to refer to the old documentation soon. :wink:

**Comment by alanjfs** [comment]
Adding a note here from Discord, would love to see a return of stamp! ❤️
