### ISSUE TITLE
registry::on_replace documentation issue

### ISSUE THREAD

**Issue by lbakman** [skypjack/entt#452]
Hi, 

I am learning EnTT framework, and was experimenting with observing changes to the registry. 

I found a small documentation issue for the on_replace method in the registry. 
The documentation says:

> The function type for a listener is equivalent to:
> 
> void(registry<Entity> &, Entity, Component &);
> 
> Listeners are invoked **before** the component has been updated.

But the on_replace listener does not expect a Component reference and it seems to be called after the component is updated.

Am I missing something, or is the documentation incorrect?

Regards Lau Bakman

**Comment by skypjack** [comment]
This seems to be invalid. Where did you find the issue exactly?
Just to sum up:
* The wiki contains the documentation for the current `master`.
* The online documentation refers to the last stable tag instead.

My impression is that you're using `master` but referring to the online documentation. Is this the case?

**Comment by lbakman** [comment]
Hi,

Sorry I wasn't more specific. I am using 3.3.2, and the issue I am talking about is in entt/entity/registry.hpp, lines 1101 to 1107. It is in the API documentation of the on_replace call.

In master, is is in lines 1138 - 1144 and the method is nor on_update.

Regards Lau Bakman

**Comment by skypjack** [comment]
>Sorry I wasn't more specific

Nah, nothing to apologize for. Indeed thanks for reporting this! :wink: 
I've updated the wiki but I missed the inline documentation. Good catch. :+1:
