### ISSUE TITLE
Crash course on entt::meta is outdated

### ISSUE THREAD

**Issue by stefanofiorentino** [skypjack/entt#459]
At [this](https://github.com/skypjack/entt/wiki/Crash-Course:-runtime-reflection-system#names-and-identifiers) link the documentation is outdated (still use type instead of alias), let me know if I can help updating it.

**Comment by skypjack** [comment]
Apparently [I've updated the doc](https://github.com/skypjack/entt/commit/34f05fb8dcf9da6e960dc647756419c49432d7b4) but I didn't copied it in the wiki. Thanks for pointing this out. :+1: :heart:

**Comment by skypjack** [comment]
Updated. :+1:
