### ISSUE TITLE
exporting entt symbols in shared lybrary

### ISSUE THREAD

**Issue by avkudr** [skypjack/entt#464]
Hello,

I've encountered the following problem: if the `entt::meta` types that are resolved in a shared library, stay unresolved in the application (it is impossible to resolve by type).
By sharing the context, library types may be resolved in the application by name but not by type.

The problem is present only in Windows (I tested with vs2017 and vs2019). Everything is OK on linux and mac.

I've managed to solve the problem by replacing
```
template<typename... Type>
struct meta_node {
```
with
```
template<typename... Type>
struct ENTT_API meta_node {
```
in ```entt/single_include/entt/entt.hpp:11357```. I think this corresponds to ```meta.hpp:194```
add adding correct compile definitions:
```
target_compile_definitions (library PRIVATE ENTT_API_EXPORT)
target_compile_definitions (app PRIVATE ENTT_API_IMPORT)
```

However, to resolve by name a shared context is needed.

Thanks!

**Comment by skypjack** [comment]
>However, to resolve by name a shared context is needed.

Isn't enough to also add `ENTT_API` to the class specialization?

```
template<>
struct ENTT_API meta_node<> {
    // ...
};
```

**Comment by avkudr** [comment]
Yes, exactly!
However, it made me think. What if the client of the library wants to use `entt::meta` too. Wouldn't it be a problem that we already use `ENTT_API_IMPORT` definition ?

**Comment by skypjack** [comment]
Meta is sandboxed and every side of the boundary has its own context.
You can share a context across boundaries but all things are implicitly resolved on their original context anyway.

By using `ENTT_API_*` you're somehow instructing the runtime linker to _merge_ these contexts and everything behaves as if there is a single, global context.
Just don't do that if you want sandboxed ones. This is a trick that has its pros and cons.

**Comment by skypjack** [comment]
Btw thanks to your efforts I managed to reproduce the error you had.
I pushed upstream an updated test and the fix. Currently, only VS2017 is having problem to compiler this code but I'm confident that I'll find a workaround! :smile:

**Comment by avkudr** [comment]
Thanks for your help ;)

**Comment by avkudr** [comment]
A side note.
Let's say that I registered a type LibClass in my library and compiled it with ENTT_API_IMPORT.

Now, in the client code I can use the following and everything is OK:
`entt::resolve<LibClass>()`

However, if I want to resolve a new class, AppClass, I won't be able to do it:
```
// client_app.cpp
class AppClass{
  int v;
};

int main()
{
    entt::resolve<LibClass>(); // ok
    entt::meta<AppClass>().alias("AppClass"_hs); // won't link, unresolved symbol
}
```
As far as I understand it, the problem is that when we put `ENTT_API_*` in front of a template function, such as `template<typename... Type> struct meta_node`, it will generate only the instances that are actually present. That is why `meta_node<LibClass>` will be generated.

On the other side, `meta_node<AppClass>` is unresolved...

**Comment by Innokentiy-Alaytsev** [comment]
I confirm that this is a possible issue. I've stumbled upon it during my first attempts to resolve #432. But then I resolved my original issue and got carried away with other things: I didn't have either time or mood to do the right thing. Sorry me, please.

**Comment by skypjack** [comment]
@avkudr in this case either use the classical sandboxed approach and resolve meta types by name or instantiate explicitly the C++ types you don't use from where you export.
@Innokentiy-Alaytsev don't worry. :wink:
