### ISSUE TITLE
emplace does not exist on registry

### ISSUE THREAD

**Issue by kix-mcotton** [skypjack/entt#465]
I read through the docs and decided to try out a test run but noticed that registry.emplace<component>(entity, ...) doesn't exist?

**Comment by skypjack** [comment]
`emplace` is only available from `master` (where `assign` is deprecated). The wiki refers to it. The documentation for the last release is [here](https://skypjack.github.io/entt/) instead.
Maybe you're trying to use `emplace` with the last tag? In this case, the right name is `assign`.

**Comment by skypjack** [comment]
I assume this has been answered. I'm closing the issue. Feel free to reopen it if you still have doubts.

**Comment by kix-mcotton** [comment]
Yes this is answered now thank you. Sorry, I missed the part of the documentation mentioning the change.

**Comment by skypjack** [comment]
Not a problem. Thanks for asking! :+1: :wink:

**Comment by LiliumAtratum** [comment]
> `emplace` is only available from `master` (where `assign` is deprecated). The wiki refers to it. The documentation for the last release is [here](https://skypjack.github.io/entt/) instead.
> Maybe you're trying to use `emplace` with the last tag? In this case, the right name is `assign`.

I am completely new to entt. I am trying to adapt the example given in "Code Example" from the wiki and it does contain `emplace`. I don't know what "last tag" means. Using vcpkg to get entt, it is at version v3.3.2-057721244e I believe.

**Comment by skypjack** [comment]
@LiliumAtratum `vcpkg` contains now the last stable version (v3.4.0). Just update it and the example in the README should compile.

**Comment by LiliumAtratum** [comment]
Indeed it does. I forgot to update the ports repository. My apologies.

**Comment by skypjack** [comment]
Don't worry. You're welcome. :+1:

**Comment by DanielGarwart** [comment]
> 
> 
> @LiliumAtratum `vcpkg` contains now the last stable version (v3.4.0). Just update it and the example in the README should compile.

vcpkg search entt only lists entt v 3.3.2

**Comment by Kerndog73** [comment]
@DanielGarwart You might need to do a `git pull` in the vcpkg directory. The [EnTT portfile](https://github.com/microsoft/vcpkg/blob/34db0f946b36102cafd9c84f0cef26504a7ce3e8/ports/entt/portfile.cmake) is at v3.4.0

**Comment by DanielGarwart** [comment]
> 
> 
> @DanielGarwart You might need to do a `git pull` in the vcpkg directory. The [EnTT portfile](https://github.com/microsoft/vcpkg/blob/master/ports/entt/portfile.cmake) is at v3.4.0

Yup fixed it.
