### ISSUE TITLE
Compile error with groups inside templated function

### ISSUE THREAD

**Issue by Oipo** [skypjack/entt#466]
The following function

```
    struct a{}
    struct b{}
    template<bool c>
    void test(entt::registry &es) {
        auto pc_group = es.group<a>(entt::get<b>);
        for(auto entity : pc_group) {
            auto[ac, bc] = pc_group.get<a, b>(entity);
        }
    }
```

creates the following compile error on g++ 9.2.1 and g++ 10-rc1, using `-std=c++2a`:
```
p:31:54: error: expected primary-expression before ‘,’ token
   31 |             auto[ac, bc] = pc_group.get<a, b>(entity);
      |                                                      ^
```

**Comment by skypjack** [comment]
Both `a` and `b` are empty types and therefore they aren't instantiated.
Roughly speaking, you cannot `get` them since they don't exist.

If you want to disable the empty type optimization, set the `ENTT_NO_ETO` definition or just define it before using the registry.
[It compiles](https://godbolt.org/z/xSi_cS) and works as expected with C++20. :+1:

**Comment by Oipo** [comment]
Actually I encountered this with non-empty structs, but I see how you fixed it: you added the template keyword before the get function. Thanks!

**Comment by skypjack** [comment]
Oh, yeah, I forgot to mention it! Sorry. Nice to know it helped.

**Comment by Kerndog73** [comment]
@skypjack Do you know why the `template` keyword is required there? It seems like `decltype(pc_group)` is dependent on the template parameter of `test` somehow, even though it's never actually mentioned... Oh, Clang doesn't require the `template` keyword. Maybe this is a GCC bug?

**Comment by skypjack** [comment]
>Maybe this is a GCC bug?

@Kerndog73 Yeah, I tried this with clang first and it worked. Then I found that g++ cannot compile the snippet without the `template` keyword.
Afaik it's a bug, this isn't a dependent name, so I don't see why it requires a `template` there.
