### ISSUE TITLE
[C++20] operator tiebreaker changes cause warning

### ISSUE THREAD

**Issue by Oipo** [skypjack/entt#467]
[C++20 changes operator overload tiebreakers](https://stackoverflow.com/questions/60568088/breaking-change-in-c20-or-regression-in-clang-trunk-gcc-trunk-when-overloading), causing the equality operator for the `null` class to become recursive. GCC 10 generates the following error:

```
/home/oipo-unencrypted/Programming/IdleBossHunter/external/entt/src/entt/entity/entity.hpp:143:18: warning: in C++20 this comparison calls the current function recursively with reversed arguments
  143 |     return other == entity;
```

This line and the one on 149 probably need to be changed to `return other.operator==(entity);` and `return other.operator!=(entity);` respectively.

**Comment by Oipo** [comment]
[Godbolt](https://godbolt.org/z/w3wxMP) reproduces this error.

**Comment by skypjack** [comment]
Good catch. Thanks for pointing this out.
