### ISSUE TITLE
Conan version troubles

### ISSUE THREAD

**Issue by m4nuelst** [skypjack/entt#474]
Although the versions in the repo and in the conan center are same, there is a discrepancy. For example, in the last framework version from github we have new function emplace(..) of the entt::registry class which is not in the conan version, that is numbered the same.

**Comment by skypjack** [comment]
The assumption that the two versions are the same is wrong though.
Conan contains the last stable tag, that is, v3.2.2, while `emplace` is only available on `master`, that is, the upcoming release.
This explains why you don't see the function in the version available from the conan center. Why did you expect it?

**Comment by m4nuelst** [comment]
Sorry, I really opened the issue by mistake.
