### ISSUE TITLE
Emplace/view components with the same type BUT with different id in runtime.

### ISSUE THREAD

**Issue by roig** [skypjack/entt#475]
Let's say that I want to make an application that allows you to "define" differents component at runtime. How would you do it? 

What I ended doing to store my "dynamic runtime" components using entt was something like that (very simplified for example purposes):
```
struct RuntimeComponent {
        std::vector<entt::meta_any> variables;
};
```

This allows to setup that component with different variables at runtime. Problem is that I can't add them to the registry because each different RuntimeComponent instance will be in the same Id and we can't differentiate them in a view.

Is it possible to add the feature to emplace a component with the same type (RuntimeComponent) but with different id? Something like that:

```	
struct RuntimeComponent {
	std::vector<entt::meta_any> variables;
};

RuntimeComponent a;
// add vars to a meta_any vars...


RuntimeComponent b;
// add vars to b meta_any vars...

const id_type aId = 11111111;
const id_type bId = 22222222;
registry.runtime_emplace<RuntimeComponent>(entity, aId, a);
registry.runtime_emplace<RuntimeComponent>(entity, bId, b);
```

The idea is to use the same struct layout but with different ids to "dynamically create" new types of components to emplace in the registry.

For the views I think we have what we need:
```
entt::component types[] = { aId , bId };
auto view = registry.runtime_view(std::cbegin(types), std::cend(types));
```

**Comment by skypjack** [comment]
I think the main problem is the other way around. What if you tried to create a _standard_ view? What pool should it use in this case?
I don't see a _proper_ solution for that unfortunately.

My two cents on this problem. A couple of possible solutions:

* Custom pools. If we could specialize pool, users can define a sort of nested registry within a pool that is suitable for runtime purposes. In this case, the standard view would get the pool as-is and return whatever is the type it returns.

* User defined matcher for observers. If you could set a free function as a matcher for an observer, you would have literally all the entities split in their own sets through the observers and according to the runtime components they have.

**Comment by roig** [comment]
> I think the main problem is the other way around. What if you tried to create a _standard_ view? What pool should it use in this case?

As I see it, it should return the pool for the implicitly created RuntimeComponent id (using PrettyFunction) as you are using with others. And it will correctly not show the ones created using a custom id no?

What I'm thinking... is that probably having a more low level registry that works with ids and memory layouts (having the user to make the correct casts) and then having a higher level one that works like a facade to that low level registry generating a implicitly component type id and casting the pools to the type would be useful.

```
// base registry
base_registry.emplace<Component >(entity, explicitid)
// all functions receive/pass the id (never casting, this should be done in user side)

// higher level registry
// all functions receive/pass the Component type, (it will cast automatically the result of base_registry, so no casting in user side)

registry.emplace<Component >(entity) will use: base_registry.emplace<Component >(entity, type_id<Component>::id() (or whatever you are using there) )
```

Maybe having the user to manually specify the ids is not a bad idea at all

I know this is a bit offtopic but, and again correct me if I'm wrong, currently the id is generated using prettyfunction. This means that if I a serialize a component using this id and I change the code or the prettyfunction change the output I will have problems deserializing that component, am I right? (ofc I can use a custom id to serialize/deserialize but could be a problem if you don't know that implementation detail and use the id that entt is using)

> My two cents on this problem. A couple of possible solutions:
> 
>     Custom pools. If we could specialize pool, users can define a sort of nested registry within a pool that is suitable for runtime purposes. In this case, the standard view would get the pool as-is and return whatever is the type it returns.
> 
>     User defined matcher for observers. If you could set a free function as a matcher for an observer, you would have literally all the entities split in their own sets through the observers and according to the runtime components they have.
> 

Could you give us an example of those? 

Thank you

**Comment by skypjack** [comment]
>As I see it, it should return the pool for the implicitly created RuntimeComponent id (using PrettyFunction) as you are using with others. And it will correctly not show the ones created using a custom id no?

This can quickly become confusing for the final user imho. Moreover, it opens the door to a duplication of the API, so as to support both _built-in_ and user defined pools.

>having a more low level registry that works with ids and memory layouts (having the user to make the correct casts)

This is _another project_ in a sense, though it's somehow possible nowadays.
What if you could create a view from a bunch of sparse sets or storage classes?
In this case, you could easily create as many pools for the same type as you want and even mix them with views.
The best would be having a sort of _merging view_ that zips two views and make you iterate them as if they were a single view. In this case, you could combine your _runtime views_ with those generated by the registry.
Funny enough, it's quite easy to make this possible. `EnTT` is already _almost there_.

>Maybe having the user to manually specify the ids is not a bad idea at all

It would be annoying as heck in all those cases where you don't want/need to use runtime stuff. My two cents.

>currently the id is generated using prettyfunction

Yeah, even though it's fully customizable and this part is documented.
If you doubt the _stability_ of these ids, you can provide your own generator. It can be as simple as a registration step during the bootstrap of your application and this wouldn't be different from what other libraries do, that is, forcing the user to do that in all cases and no matter what.
The built-in generator is just convenient in the vast majority of cases but it's not a requirement.

>Could you give us an example of those?

Well, you can't (yet) mix sparse sets or different storage with a view (mainly because the view's constructor is private) but you can instantiate how many classes of these types you want and iterate them when needed.
This is already enough to solve your problem. We can introduce tools and feature to make it easy but still...

**Comment by roig** [comment]
Sounds perfect! But one more question.

Let's use a real example, let's say that I have an engine with X c++ defined components, Then I have lua bindings to set functions as systems and I want to create Y components in lua that can be viewed by entt in lua.

With your solution can we view X and Y components in the same view?

And how the runtime components would be added to entt using your proposed solution? 

We will have to create some C++ component that can hold inside "variables" or it will be more like passing just an id and a sizeofmem param (depending on the variables added in lua to that component) ?

Thank you

**Comment by skypjack** [comment]
No, you won't put them in the registry. That's all. Something like:
```
const auto entity = registry.create();
registry.assign<position>(entity);

// both these are instances of `entt::storage`
my_storage storage_1;
my_storage storage_2;

// do whatever you want in lua and fill storage_1 and storage_2

auto view = registry.view<position>();
view.zip_each([&](auto entity, auto &position) {
    // entity has position AND storage_1/storage2
}, storage_1, storage_2);
```
Don't care about the syntax, just guessing out of my mind but this could be a solution.
That is, you create and manage lua pools, even more than once for the same _type_, then you combine them with actual views generated by the registry to iterate entities that have all components.

Does it make sense?

**Comment by roig** [comment]
Yep, it makes sense! That would be awesome :dancers:

**Comment by skypjack** [comment]
The _custom path_ (a new feature of the upcoming release) will make this (and many other things) possible.
I'm closing the issue becuase it's technically done and already available upstream, even though the implementation isn't probably as obvious as it ought be.
I'm also adding a note to the todo list to add an example that will serve as bootstrap for future users. 👍
