### ISSUE TITLE
Proposal: Move from Gitter to Discord

### ISSUE THREAD

**Issue by NixAJ** [skypjack/entt#477]
**Introduction**
Hey there, I'm Nix and there is a good chance you don't know how I am. I work on a project called NovusCore and we currently use Entt and have done so since late 2018. I want to start this off by saying that I see Discord as a platform with more tools available for communicating compared to Gitter, however I'm not completely informed about Gitter's full potential.

**Proposal**
I propose that we move all communication from Gitter to Discord. Discord is a platform with a lot of tools available directly designed to make communication easy and simple, and Entt is a platform where having conversations about a specific topic could be very beneficial and as it stands now our only option is to do that through issues, but considering how issues mainly allows for "over time" conversations and not "real time" conversations as much degrades the quality of those conversations. I'm not sure I've made my argument as best as I can, but I hope the convenience of discord is something that have at least been highlighted.

**Outro**
I encourage a healthy conversation about moving over to Discord, I'm probably biased even if I don't personally feel that I am, and I'd like others to chip in on reasons why or why not we should make the move, and added on top of that I would like to hear if you feel I got something wrong in my explanation above.

**Comment by skypjack** [comment]
I'm not against creating a discord server dedicated to `EnTT`.
However, I'd also keep the gitter channel around, at least for a while.
It's extremely convenient for anyone who wants to ask a question without creating any account on a social network.

Let's see what others say on this though. :+1:

**Comment by roig** [comment]
The Discord desktop/mobile application is way better than gitter one imho.
Discord has more server management features, inner channels.. etc.. maybe those could be useful for entt project.
So for me is a big yes.

**Comment by Green-Sky** [comment]
I'm against Discord, since it is closed source, data collecting service, which requires a login to read (contrary to gitter), and has no reliable source of income. Except for when you count Investors money as income.

While on the matter, i already have a stomachache while using gitter...

Using Discord would exclude me and other "hardcode" open-sourcerers from coming by for a chat.
_We are going to be at discord here._

Read up more on a similar topic: https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

**Comment by NixAJ** [comment]
> I'm against Discord, since it is closed source, data collecting service, which requires a login to read (contrary to gitter), and has no reliable source of income. Except for when you count Investors money as income.
> 
> While on the matter, i already have a stomachache while using gitter...
> 
> Using Discord would exclude me and other "hardcode" open-sourcerers from coming by for a chat.
> _We are going to be at discord here._
> 
> Read up more on a similar topic: https://drewdevault.com/2015/11/01/Please-stop-using-slack.html

If the gitter is maintained for short interactions, then I'd assume there would be no change in how you operate and interact with the project as a whole.

**Comment by Green-Sky** [comment]
> If the gitter is maintained for short interactions, then I'd assume there would be no change in how you operate and interact with the project as a whole.

Sure.

**Comment by Qix-** [comment]
> and has no reliable source of income

This is patently inaccurate. They have Nitro and have had a shop for a while that they are planning to re-work and reopen at a later date.

---

+1 for Discord. Would happily join.

**Comment by roepel** [comment]
+1 for Discord from me. Nothing to add.

**Comment by Lawrencemm** [comment]
No need to choose one over the other, just open a discord and see what value it brings.

**Comment by skypjack** [comment]
Ok, let's create it. :+1: 
I won't close the gitter channel though, mainly because I think the two serve different purposes.

**Comment by skypjack** [comment]
Please, **don't close** the issue until I update also the README. Thanks. :heart:

**Comment by skypjack** [comment]
Added the badge to the readme file. Time to close this issue. Enjoy the new channel. :)
