### ISSUE TITLE
on_construct and on_destroy for context variables

### ISSUE THREAD

**Issue by Qix-** [skypjack/entt#480]
Is there a way to attach `on_construct` and `on_destroy` handlers for registry context variables?

**Comment by skypjack** [comment]
Actually no. What you would expect to receive in the callback exactly?
Just an empty notification that something has been added or deleted?

**Comment by Qix-** [comment]
Yeah that's what I'd expect....

... if it weren't for the fact that constructors/destructors were called. You're too fast for me @skypjack ;)

Existing functionality is fine, idk why I thought you didn't call the constructors. Sorry for the noise <3

**Comment by skypjack** [comment]
Don't worry. You're welcome. :wink:

**Comment by alexander-v** [comment]
Hello.
I'm interested in such kind of functionality.
For example, I'd like to store scene-wide physics settings (gravity etc) in a context variable and make my physics system observe changes in the context variable to push it to PhysX.
How can I observe changes in contexts without on_update signal?

**Comment by skypjack** [comment]
@alexander-v your context variable could for example inherit from `entt:emitter`, so that you can update and publish from that.
