### ISSUE TITLE
Return the number of components actually removed by remove_if

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#483]
Currently, `registry::remove_if` returns nothing.
It could help if it returned the number of elements actually removed.
For a single element, it turns out to be also a sort of true/false like value we can easily use in a guard.

**Comment by sunbubble** [comment]
You could also add range based `std::size_t registry::insert_missing<T>(begin, end)`, which would also return the number of inserted components.
On first glance this only works with empty struct components, but looks quite useful for tagging purposes.

**Comment by skypjack** [comment]
@sunbubble you can already do that by using a view with an exclude filter and then invoking the range assign. :+1:

**Comment by sunbubble** [comment]
> @sunbubble you can already do that by using a view with an exclude filter and then invoking the range assign. 👍

True, but I wonder if that's always practical. If for some reason you only have a `std::vector<entt::entity>` that you want to tag, generating a type-filtered view might not be most practical or efficient.

This course begs the questions whether you should ever want to have `std::vector<entt::entity>` in the first place. Would you consider this a big anti-pattern?

**Comment by sunbubble** [comment]
I've been trying to think of a better example, but it looks to be kind of a corner case, which could probably be refactored.

Thanks for the feedback 👍
