### ISSUE TITLE
How to write top-down looking code that's actually entt-efficient?

### ISSUE THREAD

**Issue by johelegp** [skypjack/entt#487]
With coroutines, it's possible to tame callback hell and be able to write top-down looking code that's actually asynchronous. Is it (yet) possible to do the same with entt code, tame loop hell, and be able to write top-down looking code that's actually entt-efficient?

**Comment by skypjack** [comment]
Well, you can loop over the view using its iterators and _yield_ when you think it's reasonable.
However, since the `each` internally is nothing more than a loop, you can _yield_ also from within the function you pass to it.
Not sure what you are looking for exactly though. `EnTT` doesn't perform async operations, so it doesn't make much sense for it to _stop and wait_. On the other hand, you can surely use coro with it and according with the application logic but this mostly depend on your software, not on the library.

**Comment by johelegp** [comment]
I read the wiki now. I actually meant something more like the following:
```C++
award({registry, {p1, p2, p3}}, 300_exp); // `pX` are `entt::entity`.

using player = entt::make_struct<position, attack, experience, /*...*/>;

award(player p, experience exp)
{
    p.exp += exp;
    update_level(p);
}
```
With the idea that the `award` call above actually executes:
```C++
registry.get<experience>(p1) += exp;
registry.get<experience>(p2) += exp;
registry.get<experience>(p3) += exp;
update_level(p1);
update_level(p2);
update_level(p3);
```

**Comment by Kerndog73** [comment]
I don't think I understand what you're looking for. Calling `registry.get` on an array of `entt::entity`s is not very efficient. You're probably better off using views or groups.

**Comment by johelegp** [comment]
Thank you. I replaced `registry` with `view` to not distract from the focus of making it look like operating on a single instance rather than an array.

**Comment by Kerndog73** [comment]
I still don't understand the problem you're trying to solve. Why is `entt::make_struct` necessary? Why can't you use views and groups directly?

**Comment by johelegp** [comment]
As I understand it, a reason to use ECS is performance. And that means operating on arrays of structs, where you would otherwise use structs of arrays. Since my intention is to be able to write code like the latter which actually translates to the former, it shouldn't be slower. As for understandability, I'd guess it'd be easier to understand. That said, the above is just pseudo-C++. I haven't proven I can make that work.

> I still don't understand the problem you're trying to solve.

That'd be writing naive looking code with the advantages of an ECS.

> Why is `entt::make_struct` necessary?

To express a logical entity that the components make up.

> Why can't you use views and groups directly?

I just want to explore if we can do better.

**Comment by Kerndog73** [comment]
> And that means operating on arrays of structs, where you would otherwise use structs of arrays.

I think you have that back to front. Arrays of structs are a little more natural and intuitive but structs of arrays are faster. EnTT uses SoA to store components. I see what you're trying to do now. You want an API that looks like AoS but is actually SoA under the hood. Still, I think using views and groups directly leads to faster and easier-to-understand code. Your example might look something like this:

```C++
struct level {
  int value;
};

struct experience {
  int value;
};

// when an entity gains XP, you do 
// reg.emplace<deserves_xp>(e, 300);
struct deserves_xp {
  int value;
};

void award(entt::registry &reg) {
  auto view = reg.view<level, experience, deserves_xp>();
  view.each([](auto &level, auto &xp, auto extra) {
    xp.value += extra.value;
    update_level(level, xp);
  });
  reg.clear<deserves_xp>();
}
```

**Comment by johelegp** [comment]
That's a valuable example. Thank you.

**Comment by skypjack** [comment]
I'm closing this issue as a question for which you received an answer.
If this isn't the case, feel free to reopen it and to provide details on what is missing.
Thank you.
