### ISSUE TITLE
Clarify constructor/destructor calls in documentation

### ISSUE THREAD

**Issue by Qix-** [skypjack/entt#488]
Currently it's not very clear when constructors/destructors are called for components in the ECS wiki text. Could this be clarified?

From my understanding (I could be wrong), component constructors are called before `on_construct` is ever emitted, and `on_destroy` is emitted before destructors are called. Is that correct/guaranteed?

**Comment by skypjack** [comment]
Not sure what I should clarify exactly. The documentation says that listeners are invoked after components have been assigned to entities. To assign a component to an entity, you've to construct it. So, yeah, constructors are necessarily invoked before any listener is invoked.
The same applies to destructors. Listeners are invoked before the component is removed and therefore before its destructor is invoked.
In both cases, the goal is to provide listeners with valid instances of components to use.

**Comment by Qix-** [comment]
Right, but are constructor/destructors invoked when components are replaced?

**Comment by skypjack** [comment]
>Right, but are constructor/destructors invoked when components are replaced?

Of course, before the listeners are invoked. The component is replaced with a new object created as a temporary, so you've a chain of constructor, move constructor, destructor of an object that is in an unspecified but safe state (well, if your objects give this guarantee as stated by the standard, of course).

>it's not completely unreasonable to assume the the constructors/destructors are not called at all for performance reasons

Indeed, it is not. However, in case I didn't invoke the constructor, all your objects would be in an invalid state and you couldn't use them after an `emplace`. Am I wrong?

>Could just be me, but I thought the construct/destroy callbacks were in lieu of the constructors and destructors since components could be re-used.

Oh, no. You can even pass the arguments to use with a constructor when you invoke `emplace`.
The scope of the listeners isn't this one. To be honest, in C++ it would be odd if I asked to users to attach listeners that perform the construction/destruction of objects.
These callbacks are meant to perform all other kinds of set up and tear down for components. For example, resource management and such. Also, you can attach the member functions of the registry to the listeners and therefore for example trigger an `emplace` of `T` when you `remove` a `U` from an entity.

**Comment by Qix-** [comment]
No, you're right. This was resolved in Discord and it was determined I simply need to pay closer attention.

Thanks @skypjack

**Comment by skypjack** [comment]
You're welcome. Can I close the issue or are there some changes you want to propose anyway? I didn't get it, sorry. :)

**Comment by Qix-** [comment]
No sorry, just hit the wrong button :) Thanks again!
