### ISSUE TITLE
update documentation on ordering guarantees of `raw<T>`

### ISSUE THREAD

**Issue by sunbubble** [skypjack/entt#489]
Currently the documentation of the `raw<T>` method says that there are no guarantees on the order of components, when in fact they are in reverse order as imposed by the `sort` method.

**Comment by codylico** [comment]
Implementation detail?

**Comment by skypjack** [comment]
@codylico It's (was?) an implementation detail but nowadays it's also guaranteed, so why not to leverage it if needed.
