### ISSUE TITLE
Add support for ENTT_DISABLE_TYPE_INDEX definition (or similar)

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#490]
Currently, suppressing index generation is possible with the following snippet:
```
template<typename Type>
struct entt::type_index<Type> {};
```
It would be useful if there were a macro definition that enforces this project wide.
Something as simple as the following is enough:
```
#ifdef ENTT_DISABLE_TYPE_INDEX 
template<typename Type>
struct entt::type_index<Type> {};
#endif
```
cc @Lawrencemm :+1:

**Comment by Lawrencemm** [comment]
OK, thinking about this overnight instead of sleeping, I've come to the conclusion it might be better for the macro to _enable_ type index. Why?

I think it sounds better to say `EnTT has an option to make registry faster when you do a monolithic build` than to say `EnTT is broken by default when using shared libraries, you have to add a compiler definition or you get undefined behaviour and segfaults` just my two cents.

**Comment by skypjack** [comment]
@Lawrencemm it's mainly a matter of backward compatibility nowadays. You can't just switch the default behavior and expect all users read the changelog and start passing the definition. This... won't happen, that's all. :smile:

**Comment by Innokentiy-Alaytsev** [comment]
It heavily depends on how users are using EnTT. If they are responsible, they are using CMake imported target that can provide the required definitions. If they are either not responsible or don't use CMake then it's their job to read changelog. Of course, breaking user code is not good, but I think it should be possible to introduce this change through some transition period, where for 1 version the users will get a warning about that the definition is required.

It's not like EnTT updates never broke something before)

**Comment by skypjack** [comment]
>It's not like EnTT updates never broke something before)

I don't remember it actually... :joy:

**Comment by Innokentiy-Alaytsev** [comment]
Ask the Antara SDK guy who got problems on several updates because his submodule or something was pointed to `master`. #432 is also about breaking changes BTW.

**Comment by Lawrencemm** [comment]
Type index off by default can't really break anyone, unless they have hard speed requirements, in which case they can ask for help or look at the change log.

I really think having a major use case broken by default is the wrong way to go, esp. In the name of not changing things, especially when the change has a very low probability of causing bad problems.
