### ISSUE TITLE
Wiki-page for events contains non-working example

### ISSUE THREAD

**Issue by Tyyppi77** [skypjack/entt#491]
The examples [here](https://github.com/skypjack/entt/wiki/Crash-Course:-events,-signals-and-everything-in-between#event-dispatcher) do not compile since `struct an_event` is missing a constructor. The docs should probably be updated to reflect this.

**Comment by skypjack** [comment]
I decided to make `enqueue` work fine with aggregates too instead of fixing the documentation. :+1:
