### ISSUE TITLE
Entity Hierarchies

### ISSUE THREAD

**Issue by maxattack** [skypjack/entt#494]
We studied [both](https://skypjack.github.io/2019-06-25-ecs-baf-part-4/) [articles](https://skypjack.github.io/2019-08-20-ecs-baf-part-4-insights/) on the topic of entity hierarchies, but determined for our needs to implement a flat depth-first sorted vector hierarchy with a parent-vector (where e.g. iterating over nested-children is just a contiguous range traversal, and doesn't involve linked lists).

```
entt::registry registry;
std::vector<entt::entity> hEntity;  // fast index -> entity lookup
std::vector<int32> hParent;         // -1 for roots

// for registering indices with entities
struct HierarchyComponent {
  int32 hIndex;                        
};

```

This solves our use-case, however I feel like we're double-bookkeeping to keep the registry and containers in sync (e.g. handling `on_destroy` cleanly). The reason for not keeping the parent-vector as an EnTT component is that there doesn't appear to be an easy way to implement insert/downshift or delete/upshift w/ index-fixup -- are there facilities in the library we've overlooked?

**Comment by skypjack** [comment]
Do you mean something like _insert before iterator/entity/whatever_, similar to what the standard library does with some of its containers?
Technically speaking, it's easy to implement. Maybe the cost is to take under consideration but it shouldn't be a problem if you know what you are doing.

**Comment by maxattack** [comment]
To to verify I'm understanding you correctly, your recommendation is to add analogues of `vector::insert`/`vector::erase` to `sparse_set` (not to be confused with `sparse_set::insert`/`sparse_set;:erase`, lol).

Looking at `sparse_set::emplace` as a reference, adding the entity/page looks straightforward, but how would we find/update all the entities associated with the downshifted components? I'm looking at `sparse_set::sort` for reference, but I don't really understand the loop that follows the sorting algo.

**Comment by maxattack** [comment]
Is the `Entity` that parameterizes `sparse_set` template the component-type or `entt::entity`?

**Comment by skypjack** [comment]
More than a recommendation, I'm asking if that's what you were asking for. :smile: 

>but how would we find/update all the entities associated with the downshifted components?

This is pretty easy. If you add or remove an element at position N, all subsequent entities are updated and their new positions, that is, the indexes in the vector are also the values to put in the sparse array. The index for the sparse array is the entity itself instead, this won't change.
Ignore the `sort` function, it's an highly optimized, allocation free process that has not much to share with inserting/removing at a specific position imho.

>Is the Entity that parameterizes sparse_set template the component-type or entt::entity?

It's the entity type, not necessarily `entt::entity` though. It depends on the entity type used to specialize the registry that contains the given pool.

---

I'm working during these days to make it possible to define custom pools.
At a first glance, they are probably a better fit for this functionality. Dunno.

**Comment by maxattack** [comment]
Cool, thanks :)
