### ISSUE TITLE
Add a non-template `connect` method to sink

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#495]
Hi, I need to connect to component signals through a meta type:

`meta_type.func("connect_on_destroy").invoke({}, registry, some_method, some_obj_instance);`

The problem is that the `connect` method takes the function to connect as a template argument, but meta functions cannot be templates. 

If `connect` could take an `entt::delegate` directly then I could instantiate a `delegate` and call a meta function with it like this: `meta_type.func("connect_on_destroy").invoke({}, registry, entt::delegate{&some_method, some_obj_instance});`.

**Comment by skypjack** [comment]
You can't pass the member as an argument to the delegate constructor though.
It still goes into the class as a template argument. Aren't you just moving around the problem this way?

**Comment by skypjack** [comment]
I looked into the code of the `delegate` class once more.
After the last reworking aimed at reducing compilation time, we could maybe attach non capturing lambdas to delegates and as long as their signature is `Ret(void *, Args...)`, where `void *` is the payload and can be null eventually.
Not sure about this since I'm looking at the code from mobile but it seems to me that it's feasible to an extent.

**Comment by Lawrencemm** [comment]
Moving the problem is precisely what I need. I need to call `connect` inside a meta function so that any object can connect to the signals for the underlying type.

To achieve this, I need to instantiate the delegate before passing to the meta function, so the meta function doesn't need to know the type of the thing that is trying to connect to the signal. That is all.

**Comment by skypjack** [comment]
I looked into this request. Ironically, the hardest part is returning a function-type less connection here.
I'm trying to figure out how to do that because at the moment this is somewhat blocking.

**Comment by Lawrencemm** [comment]
Not sure if this is in delegate, sink or sigh? The only connection object I'm aware of isn't templated.

**Comment by skypjack** [comment]
The one from `sigh`, yeah. The fact that it's not templated is a problem here.

**Comment by skypjack** [comment]
As discussed on Discord, to fully support it we must turn the connection in a _typed_ object. The other way around is to not return a connection when a delegate is passed to a sink, that is annoying to some degrees and makes the feature less useful overall.
In fact, we also agreed that the recent changes to the registry made this request somewhat _invalid_ and therefore we can close it.
Feel free to reopen the issue in case the problem persists or if you have good arguments to convince me of the opposite. 🙂
