### ISSUE TITLE
Can component be protobuf class?

### ISSUE THREAD

**Issue by valaxkong** [skypjack/entt#497]
[Protobuf](https://developers.google.com/protocol-buffers) generated class is not a pure struct and which has some methods in its definition.So i don't know if it is safe to use it as a component for an entity.
If I can not do this, do you have some suggestions for serialization my entities? It should be note than, I need to deserialization with python and c++14 is the allowed at most.
Thank you for your kindness!

**Comment by skypjack** [comment]
You can use any type as component as long as it's moveable. :+1:

**Comment by valaxkong** [comment]
@skypjack Great!
Additionally, Does it lead to performance degratation when component is not pure struct?

**Comment by skypjack** [comment]
It leads to performance degradation in the same measure in which it would do if you put these components in an `std::vector` and decided to iterate them linearly. That is, most likely not something you can easily measure.

**Comment by skypjack** [comment]
I'm closing this since I think it has been answered.
Feel free to reopen the issue if this isn't the case. :+1:
