### ISSUE TITLE
Meta: add support for indexable types (aka containers)

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#499]
Proposed API for registering the key type:
* `entt::meta<T>().indexable<KeyType, OptionalPolicyForReturnedValue>()` (it assumes that `operator[]` exists)
* `entt::meta<T>().indexable<KeyType, AccessMemberFunction,  OptionalPolicyForReturnedValue>()` (for when `operator[]` doesn't exist)

To be used like: `type.operator[](instance, index_as_meta_any);`.
It returns the associated value as a meta any.

This should work with all types of containers, like vectors and maps.

**Comment by Vennor** [comment]
It might be a separate issue but builtin support for iterators would help in cases where one doesn't know the keys but still wants to go through all the contained values in an efficient manner.
