### ISSUE TITLE
vcpkg

### ISSUE THREAD

**Issue by DavidHamburg** [skypjack/entt#50]
Hi @skypjack ,

thanks for your great library! I would like to use your library in one of our projects. To be able to use entt more easily I would like to publish it to the package manager [vcpkg](https://github.com/Microsoft/vcpkg) and maybe later to [arch user repository](https://aur.archlinux.org/).

Is that in your interest? 

https://github.com/DavidHamburg/vcpkg/commit/c14258a822043ee336b04f751a271534001f2598
https://github.com/DavidHamburg/aur-entt

**Comment by skypjack** [comment]
Hi @DavidHamburg ,

I'm glad you like my project.
Can I ask you in which type of project you want to use it?

>Is that in your interest?

As far as I can see, you already did all the work. I don't see any reason to say _no_. :-). 
Unfortunately I'm short in time to be able to maintain also the stuff you're going to publish. However, if you're willing to help with this, it would be great to see EnTT published for vcpkg and Arch!!

Thank you very much for your help so far!! Really appreciated.

**Comment by DavidHamburg** [comment]
> Can I ask you in what kind of project you want to use EnTT?

It's not the typical gaming context - we would like to use EnTT to develop a graphical 2D diagram editor.

> As far as I can see, you already did all the work. I don't see any reason to say no. :-).

Great :) I will make a pull request in the vcpkg repository and inform you when its published. You could mention it in the README if you like. It's a nice way for new users to get in touch with EnTT. 

> Unfortunately I'm short in time to be able to maintain also the stuff you're going to publish. However, if you're willing to help with this, it would be great to see EnTT published for vcpkg and Arch!!

Sure, I can update the packages when you release new versions.

**Comment by skypjack** [comment]
>It's not the typical gaming context - we would like to use EnTT to develop a graphical 2D diagram editor.

I got in touch with a lot of people that use `EnTT` out of the typical gaming context actually.  
It's pretty common and I'm glad you find it's the right tool for your task. Let me know if you publish the software online, I'd like to look at it. Also feel free to contact me if you need help with `EnTT`.

>You could mention it in the README if you like.

Absolutely!! I was going to ask you to ping me once published. It would be great. Of course, I'll give you all the credit for that too.

>Sure, I can update the packages when you release new versions.

Good. Welcome on board. Really appreciated.  
You can either leave this issue open to fill it with another comment when it's done or close it and open a PR or another issue to update the README. Probably the latter is the way to go, but feel free to do it the way you prefer.

Thank you again for your help.

**Comment by DavidHamburg** [comment]
Great, I will start another pull request with an updated README once the [PR in vcpkg](https://github.com/Microsoft/vcpkg/pull/2984) has been accepted.

**Comment by skypjack** [comment]
Hi,

Would you mind to update the package to v2.5.0?
Otherwise I can make the PR next week.

Thank you.

**Comment by DavidHamburg** [comment]
Hi,

Sorry, I haven't seen the updated version. Now I'm subscribed to the rss feed to get update notifications.

> Would you mind to update the package to v2.5.0?
Done, https://github.com/Microsoft/vcpkg/pull/3287

**Comment by skypjack** [comment]
Don't worry. I just noted that it was not up-to-date but I'm out of home, so I cannot do it.
Thank you very much for your help.

I'm also thinking of a way to automatize it, but I've not had enough time to work on it so far.

**Comment by skypjack** [comment]
I'm adding you to the contributors list (branch `experimental`). Thank you very much for your help so far.
