### ISSUE TITLE
Make registry context shareable

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#504]
Currently, a registry has its own private context.
It would be useful if multiple registries could share the same context instead.

**Comment by Innokentiy-Alaytsev** [comment]
I would say that having a special type for a context and an ability for setting the context for the registry would be a good extension. This would allow having the very single source of truth across all the registries of different types.

**Comment by skypjack** [comment]
Yeah, the idea is to make a base class that users can also extend if necessary.
Obviously, there will be a base implementation that also guarantees backward compatibility.

**Comment by Innokentiy-Alaytsev** [comment]
As a side note, making the registry inheritance-friendly may be nice as well. Currently, all the internals of the class are declared `private` which complicates doing interesting things.

**Comment by skypjack** [comment]
@Innokentiy-Alaytsev what kind of interesting things? You can already inherit from the registry. Making its internals protected exposes users to potential bugs.

**Comment by Innokentiy-Alaytsev** [comment]
I've been thinking about something like a registry facade that changes some small aspects of behaviour or adds some side effects to regular registry function calls. Obviously, this will depend on internals of the registry, but if someone needs something like that then they're prepared to work on compatibility with updated versions of EnTT. However, this may be not that useful, as the initial idea I had is somewhat conceptually wrong.

**Comment by skypjack** [comment]
I thought about this and it doesn't make much sense probably.
If one really wants to share something in the context, we can still set a pointer-like object and use it.
The problem is: if you share a whole context, you cannot have _private_ variables anymore. If you use the current model and share only a part of the context, you can have both shared and private data.
