### ISSUE TITLE
The documentation could benefit from an explanation of pools

### ISSUE THREAD

**Issue by s9w** [skypjack/entt#505]
I consider [the entity.md](https://github.com/skypjack/entt/blob/master/docs/md/entity.md) the main documentation. That document references 'pools' somewhat often - even in technical contexts where at least a cursory understanding would be required (eg for groups).

But as fas as I can tell that word is never explained. You can find things on pools in other places: That blog series has some info on it and there seems to have been an [implementation.md](https://github.com/skypjack/entt/blob/cdb35e053828e83e5fe8567a23e0786fb42a6f3c/docs/md/implementation.md) document at some time which did contain explanations on this and other stuff - but I can't find it in the main repo. A single sentence about pools being sparse sets with an external link would make this much less mysterious I think.

**Comment by skypjack** [comment]
Interesting. Yesterday I started to work to support custom pools.
This requires necessarily a dedicated section in the documentation. This part will also contain all the details about the _default pool_, that is, exactly what you're asking for.
Feel free to keep the issue open until I push everything upstream or to close it if you prefer. In both cases, the documentation about pools will enter the wiki soon. :+1:

**Comment by s9w** [comment]
Perfect, thanks
