### ISSUE TITLE
Inefficient use of std::make_unique

### ISSUE THREAD

**Issue by Kerndog73** [skypjack/entt#506]
There seems to be an inefficiency in [`sparse_set::assure`](https://github.com/skypjack/entt/blob/171463faf54f1f0862007c481ed907f80bc5d63b/src/entt/entity/sparse_set.hpp#L166-L170). `std::make_unique` will value initialize (zero initialize) the memory. Immediately after that, it's being filled with `entt::null`. Apparently, the compiler isn't smart enough to optimize away the zero init ([compiler explorer](https://godbolt.org/z/69pmiJ)). Notice that `c` contains a call to `memset` while `d` does not.

The solution is to default initialize using `new` directly or with `std::make_unique_for_overwrite` (formerly known as `std::make_unique_default_init`).

I haven't looked around for other instances of this.

**Comment by skypjack** [comment]
Good catch. So, what you suggest is to use `sparse[pos].reset(new entity_type[entt_per_page]);` instead, right?

**Comment by Kerndog73** [comment]
Yes, that’s what I’m suggesting.

**Comment by skypjack** [comment]
Upstream on `master`.
