### ISSUE TITLE
Question: view<> based on base class type

### ISSUE THREAD

**Issue by PerMalmberg** [skypjack/entt#509]
Hello,

Just getting to know entt, liking it so far :)

Is it possible to do something like this?

```C++
class A{};
class B : public A {};
class C : public A {};

reg.emplace<B>(id);
reg.emplace<C>(id);

reg.view<A>(id).each(...);
```

The above doesn't work, but is there a recommended way to accomplish the same thing?

**Comment by skypjack** [comment]
No, it's not supported. I'm sorry.
To be honest, inheritance based components are a little odd when you decide to move away from typical OOP. This doesn't mean that you shouldn't use inheritance in general. However, it's odd that it entered your component design.

Could it be an XY-problem? What are you trying to solve with this?

**Comment by PerMalmberg** [comment]
Specifically, I've got this:

```C++
class Geometry{};

template<FinalType, std::size_t VertexCount>
class Polygon : Geometry
{
protected:
std::array<Point<float>, VertexCount> vertices;
};

class Triangle : Polygon<Triangle, 3>{}
class Circle : Polygon<Circle, 16>{}
class Rect : Polygon<Circle, 4>{}
```
All the data and functionality is actually in the Polygon-class so the derived classes are really nothing but a name/type, but the inheritance obviously prevents their use in entt.

I can ofc first iterate Triangle, then Circle etc.
