### ISSUE TITLE
Added documentation with API reference

### ISSUE THREAD

**Issue by erez-o** [skypjack/entt#510]
Hi,

I've created a documentation with the content from the wiki and API reference, you can see an example at https://entt.docsforge.com/

Hope it's helpful for anyone using EnTT. The docs are built automatically every week so they should always be in sync with the code and wiki.

If there are any more tutorial pages you wish to add to the sidebar, or you wish to hide certain internal APIs from being displayed please let me know, everything is configurable.

Disclaimer - I'm the creator of docsforge

**Comment by SupinePandora43** [comment]
@erez-o thank you!
finally i can see example of using **entt**
