### ISSUE TITLE
Code snippet in the event dispatcher wiki entry is misleading

### ISSUE THREAD

**Issue by seanballais** [skypjack/entt#511]
I'm using EnTT's event dispatcher for my game, and I'm following the Wiki to learn how to use it properly. Basing my code that will use the dispatcher from this [wiki entry](https://github.com/skypjack/entt/wiki/Crash-Course:-events,-signals-and-everything-in-between#event-dispatcher), I wrote this snippet inside a class function:

```
while (SDL_PollEvent(&e) != 0) {
      switch (e.type) {
          case SDL_WINDOWEVENT:
              this->eventDispatcher.enqueue<corex::events::WindowEvent>(e);
              break;
     ...
```

`corex::events::WindowEvent` is defined as:

```
namespace corex::events
{
  struct WindowEvent { SDL_Event event; };
  ...
```

When I compile the code, the compiler (I use Clang 10) raises an error, saying that `corex::events::WindowEvent` has no matching constructor for initialization.
<details><summary>Click to see error log</summary>

```
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/ext/new_allocator.h:146:8: error: no matching constructor for initialization of 'corex::events::WindowEvent'
                            _Up(std::forward<_Args>(__args)...)))
                            ^   ~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/alloc_traits.h:483:24: note: in instantiation of exception specification for 'construct<corex::events::WindowEvent, SDL_Event &>' requested here
        noexcept(noexcept(__a.construct(__p, std::forward<_Args>(__args)...)))
                              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/vector.tcc:115:21: note: in instantiation of exception specification for 'construct<corex::events::WindowEvent, SDL_Event &>' requested here
            _Alloc_traits::construct(this->_M_impl, this->_M_impl._M_finish,
                           ^
/home/seanballais/.conan/data/entt/3.4.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/signal/dispatcher.hpp:69:20: note: in instantiation of function template specialization 'std::vector<corex::events::WindowEvent, std::allocator<corex::events::WindowEvent> >::emplace_back<SDL_Event &>' requested here
            events.emplace_back(std::forward<Args>(args)...);

/home/seanballais/.conan/data/entt/3.4.0/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include/entt/signal/dispatcher.hpp:167:25: note: in instantiation of function template specialization 'entt::dispatcher::pool_handler<corex::events::WindowEvent>::enqueue<SDL_Event &>' requested here
        assure<Event>().enqueue(std::forward<Args>(args)...);
                        ^
/home/seanballais/Code/Projects/boyet-game/corex/src/corex/systems/SysEventsDispatcher.cpp:20:39: note: in instantiation of function template specialization 'entt::dispatcher::enqueue<corex::events::WindowEvent, SDL_Event &>' requested here
                this->eventDispatcher.enqueue<corex::events::WindowEvent>(e);
                                      ^
/home/seanballais/Code/Projects/boyet-game/corex/src/corex/events/sys_events.hpp:8:10: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'SDL_Event' to 'const corex::events::WindowEvent' for 1st argument
  struct WindowEvent { SDL_Event event; };
         ^
/home/seanballais/Code/Projects/boyet-game/corex/src/corex/events/sys_events.hpp:8:10: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'SDL_Event' to 'corex::events::WindowEvent' for 1st argument
/home/seanballais/Code/Projects/boyet-game/corex/src/corex/events/sys_events.hpp:8:10: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
```

`</details>

I traced this back to the fact that the event dispatcher uses an `std::vector` to store events, and calls `emplace_back()` when queuing new events, which requires an explicit constructor. Unfortunately, the snippet in the aforementioned wiki shows this:

```
struct an_event { int value; };
struct another_event {};

dispatcher.enqueue<an_event>(42);
dispatcher.enqueue<another_event>();
```

This misled me to believe that I no longer need to define an explicit constructor for event `struct`s. I have learned from this and is going to work on a solution for my case, but I believe future readers may still stumble upon this problem. As such, I propose the following possible solutions:

* Add in a note in the wiki entry for event dispatchers stating that you still need to define an explicit constructor for event `struct`s. Or
* Modify the event `struct`s to include an explicit constructor. Or
* We can modify the event `struct`s to include an explicit constructor, but add in a note that the constructor will no longer be required starting with C++20, since [the behaviour of `emplace_back()` will be changed in the new version](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p0960r3.html).

What do you think? I'd like to know your thoughts on this.

**Comment by skypjack** [comment]
Hi, what version of `EnTT` are you using?
As far as I remember, we already discussed this in another issue and it should work on `master` (or `experimental`, I should check where I pushed the changes).
Could you give it a try?

**Comment by seanballais** [comment]
I'm using 3.4.0 via Conan. I'll try using the version from `experimental` later.

**Comment by skypjack** [comment]
I've checked, it's on `master`. See [this](https://github.com/skypjack/entt/commit/7db0f540bde5de9b6bb64508892eb24214c001cc) commit for further details.
Related issue is #491 and this is a duplicate of that one.

**Comment by seanballais** [comment]
Ah. Yes, this is a duplicate of #491. Thanks! Will there be a patch or minor release with the aforementioned commit included?

**Comment by skypjack** [comment]
Usually I cut a new minor release every couple of months if there is enough stuff to justify it. Unless there are critical bugs, of course. In this case, I cut patch releases more often.
So, yes, by the end of the month there should be one. I don't think this is critical to be honest, mainly because an easy workaround exists as you pointed out.

**Comment by seanballais** [comment]
I see. Thanks for the help! I'll close this issue now, since it has been resolved.
