### ISSUE TITLE
Support for exclude components in runtime_view

### ISSUE THREAD

**Issue by cholmquist** [skypjack/entt#512]
If one relies on runtime_view one currently can't use the exclude mechanism of the compile time equivalent.

Proposed API:
Add an overload to registry.runtime_view that accepts an exclude range.

Example:
entt::component types[] = { entt::type_info<position>::id()};
entt::component exclude[] = {entt::type_info<velocity>::id()};
auto view = registry.runtime_view(
  std::cbegin(types), std::cend(types)
  std::cbegin(exclude), std::cend(exclude));

**Comment by skypjack** [comment]
Good catch. This is interesting actually. :+1:

**Comment by mingxxming** [comment]
this feature has been removed ?

**Comment by skypjack** [comment]
I wouldn't say so. It's part of the `runtime_view`s API now. 👍

**Comment by mingxxming** [comment]
i am not find similar api. Actually i am confuesed with the new runtime_view.
can i still create a view with assign type_id array?
could you show me an example? Thanks~

**Comment by skypjack** [comment]
[This](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#runtime-views) is what you're looking for probably. See the `iterate` and `exclude` methods.

**Comment by mingxxming** [comment]
I can`t get type in my case due to calling from script(js or lua) but the type has precreated in c++ so all types has been compiled.

**Comment by mingxxming** [comment]
static uint32_t GetTypeId(int32_t id) {
	switch (id) {
		case 1	 :return entt::type_hash<COMPONENT_ID_1  >::value();
		case 2   :return entt::type_hash<COMPONENT_ID_2  >::value();
                ........
        }
}
I precreated all enough types in c++ some are tag only that used by script but some are not used in c++.

**Comment by skypjack** [comment]
You don't have to get the type. You already have the ids, right? Just pass them to `iterate` and `exclude` rather than to the constructor.
