### ISSUE TITLE
Compilation warning in Registry.hpp

### ISSUE THREAD

**Issue by Segel10** [skypjack/entt#514]
When compiling i'm getting the warning:

_Warning	C4100	'<func_0>': unreferenced formal parameter
registry.hpp	101_

From this function:
![image](https://user-images.githubusercontent.com/67321835/85402279-b31e9a00-b55b-11ea-9641-24445424bf36.png)

**Comment by skypjack** [comment]
What compiler? I don't even get what parameter is unreferenced since `owner` and `entt` are used in both cases and `func` is declared as _maybe unused_.

**Comment by Segel10** [comment]
I am compiling this from Visual studio 2017 with ISO C++17 Standard (/std:c++17) (Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27038 for x64).

I can track the warning to a part of my code where i am doing this:

```
template<class C>
struct EmptyTag{ };

emplace_or_replace<EmptyTag<C>>(ent);
```

Should i do any other way if i want to do this with an empty component?

**Comment by skypjack** [comment]
From what I see, it may be due to `C`. In any case, you don't have to give names to parameters that you're not going to use. By getting rid of unused names you should be able to suppress the warning.

**Comment by skypjack** [comment]
I'm closing this since it's not due to the code in `EnTT` apparently.
Feel free to reopen the issue if you have any evidence of the contrary.

Thanks.
