### ISSUE TITLE
Component that has member pointer resulting 0xfeeefeee

### ISSUE THREAD

**Issue by damarindra** [skypjack/entt#515]
So, I want to create a Transfrom component that has parent, which is I need to set it as pointer
```
class Transform{
public:
	Matrix matrix;
	Transform* parent;
}

int main(){
	entt::registry registry;
	auto entity = registry.create();
	auto& entity_tr = registry.emplace<Transform>(entity);
	// entity_tr.parent = NULL
	// at this point, still fine

	auto child = registry.create();
	auto &child_tr = registry.emplace<Transform>(child);
	// child_tr.parent = NULL
	// entity_tr.parent = 0xfeeefeee
	// now the problem show up.
}
```

So, the `entity_tr.parent` will have a value 0xfeeefeee which is `Used by Microsoft's HeapFree() to mark freed heap memory`. Am I doing it wrong?

Anyway, EnTT is awesome! thanks for creating this library.

**Comment by Kerndog73** [comment]
See [this comment](https://github.com/skypjack/entt/issues/25#issuecomment-353769453).

Component pointers aren't stable because under the hood they're stored in a `std::vector`. On the other hand, entity IDs are stable. Consider this:

```C++
entt::registry reg;
entt::entity entity1 = reg.create();
reg.destroy(entity1);
entt::entity entity2 = reg.create();

reg.emplace<int>(entity1); // assert
reg.emplace<int>(entity2); // fine
```

So if you want `Transform`s to reference their parents, you're better off storing the entity ID of the parent. For transforms that don't have parents, you can use `entt::null` (see [wiki](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#null-entity)).

```C++
struct Transform {
    Matrix matrix;
    entt::entity parent = entt::null;
};

int main() {
    entt::registry registry;
    entt::entity entity = registry.create();
    registry.emplace<Transform>(entity);

    entt::entity child = registry.create();
    auto &child_tr = registry.emplace<Transform>(child);
    child_tr.parent = entity;
}
```

You might also want to read [this blog post](https://skypjack.github.io/2019-06-25-ecs-baf-part-4/) about building hierarchies with EnTT.

**Comment by damarindra** [comment]
Thanks, that's all I need to know!

**Comment by 2047241149** [comment]
I found the same issue, Component pointers aren't stable...... add multi component and return component pointers in the same time, many pointers object become invalid!

**Comment by 2047241149** [comment]
meshActor = scene->CreateActor();
	meshActor1 = scene->CreateActor();
	MeshComponent& meshCpt = meshActor.AddComponent<MeshComponent>("Resource\\sphere.FBX");
	MeshComponent& meshCpt1 = meshActor1.AddComponent<MeshComponent>("Resource\\sphere.FBX");

**Comment by 2047241149** [comment]
I found the same issue, Component pointers aren't stable...... add multi component and return component pointers in the same time, many pointers object become invalid!

**Comment by 2047241149** [comment]
I found the same issue, Component pointers aren't stable...... add multi component and return component pointers in the same time, many pointers object become invalid!

meshActor = scene->CreateActor();
meshActor1 = scene->CreateActor();
MeshComponent& meshCpt = meshActor.AddComponent<MeshComponent>("Resource\\sphere.FBX");
MeshComponent& meshCpt1 = meshActor1.AddComponent<MeshComponent>("Resource\\sphere.FBX");

meshCpt  becomes invalid

**Comment by skypjack** [comment]
@2047241149 By default, elements in a pool are rearranged to keep it tightly packed. That is why references get invalidated.
However, `master` contains support for pointer stability. You've to enable it explicitly for one, several or all types (see the wiki for all details). Pointer stability has ofc its pros and cons, but it gives you what you're looking for in this case.
