### ISSUE TITLE
API to return size of `std::vector<ctx_variable> vars{};`

### ISSUE THREAD

**Issue by blockspacer** [skypjack/entt#519]
From `entt/entity/registry.hpp`:

```cpp
    /**
     * @brief Returns the number of entities created so far.
     * @return Number of entities created so far.
     */
    size_type size() const ENTT_NOEXCEPT {
        return entities.size();
    }
```

It may be useful to know size of:

```cpp
    std::vector<ctx_variable> vars{};
```

**Comment by skypjack** [comment]
What's the use case exactly? I must admit I've never had this need.

**Comment by blockspacer** [comment]
@skypjack 
I want to force API users to manually free all created resources via `unset` (in proper order)

```cpp
  /// \note allows to assume that all resources
  /// are manually freed in proper order
  CHECK(vars.empty())
    << "You must manually call `unset` before destruction."
    << "Remaining elements count:"
    << vars.size();
```

**Comment by skypjack** [comment]
Just curious: why do you want this? Context variables are properly destroyed by the registry, so it would be enough for the user to define a destructor that releases all acquired resources, if any.

**Comment by blockspacer** [comment]
@skypjack 
I need to destroy context variables in order different from initialization order (i want to control destruction order) and i want to validate that i manually freed all context variables in proper order (vars.empty()).

BTW: another use-case - profile `vars.size()` for debug purposes.

**Comment by blockspacer** [comment]
I want to print some debug information about stored data type in case of failed `vars.size()` check (or in case of thread-safety issues).

Cause type of |variable_data| is not configurable i decided to inherit from existing entt types to add some debug information and perform custom checks (thread-safety, `vars.size()`, etc.).

Now i have full control over stored `vars`.
