### ISSUE TITLE
Feature request: dispatcher - disconnect all, given a listener instance

### ISSUE THREAD

**Issue by andrew-r-king** [skypjack/entt#523]
I'm replacing an old event manager/dispatcher I had using entt::dispatcher, and was wondering if it would be possible to add a "disconnect_all" function, given the class instance instead of specifying event types manually. Here's my use case:

```c++
// some events
namespace Event {
    struct Foo {
        int value = 0;
    };
    struct Bar {
        int value = 0;
    };
}

// EventManager abstraction
template <typename EventStruct, class Listener>
constexpr void EventManager::attach(Listener* const inListener)
{
    // Known events (engine-related)
    auto sink = m_dispatcher.template sink<EventStruct>();
    if constexpr (std::is_same_v<EventStruct, Event::Foo>)
    {
        sink.template connect<&Listener::onFoo>(*inListener);
    }
    else if constexpr (std::is_same_v<EventStruct, Event::Bar>)
    {
        sink.template connect<&Listener::onBar>(*inListener);
    }
    else
    {
        assert(false && "Event type not valid. Use attach<Event, &MyClass::myMethod>(this) instead.");
    }
}

template <typename EventStruct, auto Handler, class Listener>
constexpr void EventManager::attach(Listener* const inListener)
{
    // Unknown event types w/ custom handlers
    auto sink = m_dispatcher.template sink<EventStruct>();
    sink.template connect<Handler>(*inListener);
}

template <class Listener, typename... Events>
constexpr void EventManager::detachAll(Listener* const inListener)
{
    // Instead of this, disconnect_all
    ((m_dispatcher.template sink<Events>().template disconnect(*inListener)), ...);
}

// attach/detach called inside of scenes
// onLoad
eventManager.attach<Event::Foo>(this);
eventManager.attach<Event::Bar>(this);
// (granted, these could be combined into one call, but ignore that for now--still a wip)

// onUnload
eventManager.detachAll<MyScene, Event::Foo, Event::Bar>(this); 
```

If possible, I would prefer to write:
```c++
template <class Listener>
constexpr void EventManager::detachAll(Listener* const inListener)
{
    m_dispatcher.disconnect_all(*inListener); // <---
}

// in scene, onUnload:
eventManager.detachAll(this);
```

In my original event manager, I did this by storing the listeners as void pointers and checking the addresses, so since entt:dispatcher requires a sink each time, I don't know if that's that even doable in the same way. Figured I would at least bring it up as it would give me peace of mind, and parity with what I had in my older, clunkier event manager class.

Thanks. Loving the flexibility of this library so far!

**Comment by skypjack** [comment]
Mmm... This is possible actually. Pretty easy to implement too.
It would be a good addition. Thanks. :+1:

**Comment by skypjack** [comment]
Can I ask you to test branch `experimental` and see if it works as expected?
The call is slightly different from what you suggested though: `m_dispatcher.disconnect(*inListener);`.

**Comment by andrew-r-king** [comment]
Trying it out now. Btw, I'm using some pretty strict (gcc 10.1 / msys2/win32) warning/error flags that are getting triggered by your library.

```
-Wall -Werror -Wextra -Wpedantic -Wshadow -Wundef -Wunreachable-code -Wunused -Wignored-qualifiers -Wcast-align -Wdouble-promotion -Wformat-nonliteral -Wformat=2 -Winvalid-pch -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wredundant-decls -Wswitch-default -Wodr
```

My workaround originally was to add these in affected files (factory.hpp for instance):
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wignored-qualifiers" // or whatever the warning might be
...
#pragma GCC diagnostic pop
```

Not sure if that's something you want to look at, or if I should make a separate issue for it, but I'll basically have to finagle around these each time. I'll get back to about the disconnect change once it compiles.

**Comment by skypjack** [comment]
A separate issue would be better, thanks.

**Comment by andrew-r-king** [comment]
Works great! It took a while to debug though, haha. I wanted to effectively print out this to verify:
```
0x4551f20 // class instance at the start of the disconnect call

// in one of the disconnect methods in sigh.hpp
Removed: 0x4551f20
Removed: 0x4551f20
Removed: 0x4551f20
```
(3 events connected, 3 disconnected)

Thanks!
