### ISSUE TITLE
Fixes for GCC warnings & errors

### ISSUE THREAD

**Issue by andrew-r-king** [skypjack/entt#525]
I'm using some pretty strict warning/error flags (gcc 10.1 / msys2/win32) that are getting triggered by your library.

```
-Wall -Werror -Wextra -Wpedantic -Wshadow -Wundef -Wunreachable-code -Wunused -Wignored-qualifiers -Wcast-align -Wdouble-promotion -Wformat-nonliteral -Wformat=2 -Winvalid-pch -Wmissing-declarations -Wmissing-format-attribute -Wmissing-include-dirs -Wredundant-decls -Wswitch-default -Wodr
```

My workaround originally was to add these in affected files (meta/factory.hpp for instance):
```
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wignored-qualifiers" // or whatever the warning might be
...
#pragma GCC diagnostic pop
```

Not sure if it's something you want to look at, but I basically have to finagle around these each time there's an update.

**Comment by skypjack** [comment]
If I add all these flags to the test suite (branch `experimental`), all I get is a couple of warnings from `delegate.cpp`.
Ironically, I agree with these warnings but I can't even change those lines since the static assert would fail otherwise.
Long story short, it checks that the return type of a function-like representation for a data member is the type of the data member itself and since the original type is `const int` we get the function type `const int()`.
`-Werror, -Wignored-qualifiers` are the only flags that trigger something though and I'm not going to change it.
Can you provide an example code that triggers something different from your project? I don't know how to help you here.

**Comment by andrew-r-king** [comment]
Here's what I added the ignore pragma for:
```
(project)/lib/entt/meta/factory.hpp: In member function 'auto entt::meta_factory<Type>::data(entt::id_type)':
(project)/lib/entt/meta/factory.hpp:585:25: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  585 |                 []() -> decltype(internal::meta_data_node::set) {
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(project)/lib/entt/meta/factory.hpp: In member function 'auto entt::meta_factory<Type>::data(entt::id_type)':
(project)/lib/entt/meta/factory.hpp:637:21: error: type qualifiers ignored on function return type [-Werror=ignored-qualifiers]
  637 |             []() -> decltype(internal::meta_data_node::set) {
      |                     ^~~~~~~~~~~~~~~~~~~~~
```

using ent::dispatcher (sink/connect)
```
(project)/lib/entt/signal/delegate.hpp:109:24: error: variable 'arguments' set but not used [-Werror=unused-but-set-variable]
  109 |             const auto arguments = std::forward_as_tuple(std::forward<Args>(args)...);
      |   
```
Workaround for that was to add this (basic UNUSED macro) between the declaration & return. It wouldn't take 
```
static_cast<void>(arguments);
```

That might be it for now actually.

**Comment by skypjack** [comment]
Ok, these are probably suppressed on branch `experimental`. Could you make a try?
Unfortunately, I can't reproduce them easily, I'm sorry. Thank you.

**Comment by andrew-r-king** [comment]
Hmmm, still a variation of the same error in meta/factory.hpp
```
lib/entt/meta/factory.hpp: In lambda function:
lib/entt/meta/factory.hpp:584:32: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  584 |                         return static_cast<decltype(internal::meta_data_node::set)>(nullptr);
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
lib/entt/meta/factory.hpp: In lambda function:
lib/entt/meta/factory.hpp:636:28: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
  636 |                     return static_cast<decltype(internal::meta_data_node::set)>(nullptr);
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The delegate one is fixed though.

**Comment by skypjack** [comment]
This is a big WTF! :smile: 
I force-pushed on `experimental`, let's see if explicitly removing the `const` qualifier from the type of the data member satisfies your compiler! :joy:

**Comment by andrew-r-king** [comment]
That did the trick! Figured it was something const-related. Thanks!
