### ISSUE TITLE
Meta: create a meta any from a void * + meta type pair

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#529]
Unfortunately, we can't construct a meta any from a `void *` + meta type pair since it would be impossible to generate for example container wrappers.
On the other hand, the pair above is usually what is passed back and forth across scripting boundaries. Therefore, it would be great if we could create a meta any from these objects.

A possible approach is:
```
auto any = type.wrap(ptr);
```
Any other suggestion is appreciated.

**Comment by skypjack** [comment]
This is tricky to do in code for many reasons. I won't go in details here.
On the other hand, it's pretty easy to do it from the user side. [Here](https://godbolt.org/z/7zEsYG) is an example.
So, we can _safely_ close the issue.

**Comment by Lawrencemm** [comment]
I see. Yeah this is fine, I do a lot of stuff through meta functions already.

**Comment by skypjack** [comment]
The main problem is that we **can** add a constructor for meta any that accepts a `void *` and a meta type **but** it cannot generate what is needed for container and pointer-like support. So imho it doesn't worth it.

**Comment by Innokentiy-Alaytsev** [comment]
Aren't those things generated for meta-type itself? So that when the user wants to create a `meta_any` object from `meta_type` and `void*` they already have a fully defined `meta_type` that has all the necessary functions generated.

**Comment by skypjack** [comment]
> Aren't those things generated for meta-type itself?

No. At least, not this one. The problem is pretty easy: circular dependency. In fact, we **can** also break it. However, it complicates a little the codebase and the result isn't as satisfying as it could be.
On the other hand, we can already do this _in code_, so there isn't an impelling reason to pre-generate the function for all users and classes that don't need it. It add a cost in terms of compilation time and memory occupancy. For example I don't want this class or function generated for `int`, `char` and all other primitive types.
So, all in all, I think this conservative approach is better overall for many reasons. Any counterargument? :)
