### ISSUE TITLE
[Question] Is there any way to map entt::tags to strings such that I can read them from JSON?

### ISSUE THREAD

**Issue by sniggyfigbat** [skypjack/entt#533]
EnTT Tags are neat, and really useful.

Data-driven architecture is also really neat and useful. My engine's architecture uses JSON for both level data and prefabs.

Unfortunately, I cannot find a way to join the two, due to the templated nature of `entt::tag`. My initial solution was just to have a map of strings to hashed-strings and call translate when reading them from JSON, but unfortunately that's a no-go because tags have to be given constant expressions. Similarly, I can't map strings directly to tags.

My latest (deeply ugly) attempt to solve the problem is to map a templated function to each tag, which takes an entity and assigns the tag to it:

```
// In a central factory class:

// Map of tag hStrings to application functions.
static std::unordered_map<entt::hashed_string::hash_type, std::function<void(entt::registry& registry, entt::entity entity)>> s_tagAppliers;

// Templated application function
template <entt::id_type S>
static void applyTag(entt::registry& registry, entt::entity entity) {
	registry.assign<entt::tag<S>>(entity);
}

// Tag setup function, called in application setup.
template <entt::id_type S>
static void addTag(const std::string& tagStr, entt::hashed_string::hash_type tagHStr) {
	if (s_tagNames.find(tagStr) != s_tagNames.end()) {
		T_WARN("Tag type overwrite detected!");
	}
	s_tagNames[tagStr] = tagHStr;
	s_tagNamesR[tagHStr] = tagStr;
	s_tagAppliers[tagHStr] = std::bind(&ResourceManager::applyTag<S>, std::placeholders::_1, std::placeholders::_2);
}

// In initial setup:
T_RM::addTag<"camera"_hs>("reads_input", "reads_input"_hs); // Doesn't work.
T_RM::addTag<entt::tag<"camera"_hs>>("camera", "camera"_hs); // Also doesn't work. Obviously, I take the tag out of applyTag().

```

Unfortunately, this approach doesn't work either - I suspect my template parameters are wrong.

Is there a recommended way to parse tags from strings? Because I can't find *any* way of doing it, and it rather limits their worth if they're entirely incompatible with data-driven design. Hopefully I've just missed something; help would be greatly appreciated.

**Comment by sniggyfigbat** [comment]
Aha! As is always the way, five minutes after I'd submitted the issue I worked out how to resolve it. The issues were a) entt::tag is just a templated class and can be treated as such, and b) assign doesn't seem to work.

```
// In a central factory class:

// Map of tag hStrings to application functions.
static std::unordered_map<entt::hashed_string::hash_type, std::function<void(entt::registry& registry, entt::entity entity)>> s_tagAppliers;

// Templated application function
template <typename S>
static void applyTag(entt::registry& registry, entt::entity entity) {
	registry.emplace<S>(entity); // DIFFERENT
}

// Tag setup function, called in application setup.
template <typename S>
static void addTag(const std::string& tagStr, entt::hashed_string::hash_type tagHStr) {
	if (s_tagNames.find(tagStr) != s_tagNames.end()) {
		T_WARN("Tag type overwrite detected!");
	}
	s_tagNames[tagStr] = tagHStr;
	s_tagNamesR[tagHStr] = tagStr;
	s_tagAppliers[tagHStr] = std::bind(&ResourceManager::applyTag<S>, std::placeholders::_1, std::placeholders::_2);
}

// In initial setup:
T_RM::addTag<entt::tag<"reads_input"_hs>>("reads_input", "reads_input"_hs);
T_RM::addTag<entt::tag<"camera"_hs>>("camera", "camera"_hs);

```

The typename issue is obvious. Why `assign()` doesn't seem to work is unclear to me.

However, this solution is still pretty ugly. If there's a better one I'd be delighted to know of it.

**Comment by skypjack** [comment]
`assign` is used for batch insertions and not for a single element. It accepts a few pointers while you passed it only an entity.
That being said, I use the meta module to do what you mention. That is, to _load_ components from json. Not sure this is something you are willing to consider, so let me know before going into further details.

**Comment by sniggyfigbat** [comment]
> assign is used for batch insertions and not for a single element. It accepts a few pointers while you passed it only an entity.

That makes perfect sense, and fits with what the docs say. Does that mean that the line [here](https://github.com/skypjack/entt/wiki/Crash-Course:-core-functionalities#tag) is wrong, though? That's what I was working from, which is why I was rather confused.

> I use the meta module to do what you mention. That is, to load components from json. Not sure this is something you are willing to consider, so let me know before going into further details.

To be honest, I'm quite happy building my own, if only because it's helping me understand EnTT better the more I work with it. For example, it was only because I did this that I grasped that tags are literally just empty components.

Thank you for the offer, however.

**Comment by skypjack** [comment]
Oh, yes! That line is wrong. Can I ask you to open an issue for that? Thanks.

**Comment by sniggyfigbat** [comment]
will do.

**Comment by skypjack** [comment]
Thank you very much. Sorry, I'm in a hurry today. Really appreciated.
