### ISSUE TITLE
Is it possible to customize name of the key in JSON?

### ISSUE THREAD

**Issue by lpc0503** [skypjack/entt#539]
Hi, I know EnTT is able to serialize the entites by `entt::snapshot`.

```
cereal::JSONOutputArchive ar(std::cout);
entt::snapshot {registry}.component<TestComponent>(ar);
```

And here's the result:

```
{
    "value0": 2,
    "value1": 0,
    "value2": {
        "x_data": 1,
        "y_data": 2
    },
    "value3": 1,
    "value4": {
        "x_data": 2,
        "y_data": 3
    }
}
```

But I wonder that is it possible to customize name of the key in JSON.

```
{
    "numOfEntity": 2,
    "a_id": 0,
    "a_data": {
        "x_data": 1,
        "y_data": 2
    },
    "b_id": 1,
    "b_data": {
        "x_data": 2,
        "y_data": 3
    }
}
```

[Source code Link](https://ideone.com/Qupoeg)

**Comment by skypjack** [comment]
Doesn't the name depend on the archive and therefore on the user code? EnTT doesn't even know what you're storing aside and how.

**Comment by skypjack** [comment]
I close this for inactivity. Feel free to reopen it if necessary.
