### ISSUE TITLE
Call for comments: spaces

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#54]
I've been fascinated for a while by the [idea of having spaces](https://gamedevelopment.tutsplus.com/tutorials/spaces-useful-game-object-containers--gamedev-14091) implemented directly within `EnTT`.  
Actually, more than once I found myself saying - _uff, if only I had spaces here, it would be easier to do this_.  

However I postponed the implementation because:
* I didn't want them to be part of the registry, because not all users want them and find them useful - in other terms, I don't want to introduce spaces and thus to affect performance of the registry in any case.
* I didn't want them to not be part of the registry, because I wasn't able to find a way to _make it work_ properly (mainly to keep spaces in sync with a registry isn't for free).

Finally, perhaps I found a way to implement spaces and give them a minimal API that _just works_.  
The goal is to not add a duplicated set of functions from the registry, only to add boilerplate all around the codebase.

Not exactly the same, but here is an example of what it will look like probably:
```
template<typename Entity>
struct Space {
   Space(Registry<Entity> &registry);

    // iterate all the entities, false positive (invalid entities) are possible
    iterator_type begin() const noexcept;
    iterator_type end() const noexcept;

    // create an entity and assign it directly to the space
    entity_type create();

    // assign an entitiy to the registry
    void assign(entity_type entity);

    // iterate entities using a standard view internally, invoke the function for each entity
    // invalid entities are filtered out an never returned through func (lazy clean of a space)
    template<typename... Component, typename Func>
    void view(Func func);

    // iterate entities using a persistent view internally, invoke the function for each entity
    // invalid entities are filtered out an never returned through func (lazy clean of a space)
    template<typename... Component, typename Func>
    void persistent(Func func);

    operator const registry_type & () const noexcept;
    operator registry_type & () noexcept;
};
```
Minimal, clean, does the job. Users cannot do _everything_ with the sole space, they must work together with the registry. On the other side, spaces won't affect the performance of a registry in case one doesn't use them.  
Moreover, spaces won't have dedicated views. They offer only two `each`-like functions under the names `view` and `persistent`.  
Finally, users can create how many spaces they want at runtime this way. They don't have a name or  an identity. Consider a space as a partition of a registry.

---

Any feedback or suggestion is really appreciated. Questions are good as well.  
I still have some doubts, but I prefer not to influence you.  :-)

**Comment by ArnCarveris** [comment]
How you'll keep in sync with registry?

**Comment by skypjack** [comment]
@ArnCarveris

I won't. You cannot do that easily if it's an external tool. At least, without affecting the registry.  
A space will clean up itself during iterations and return only valid entities. We can call it a _lazy cleaning_.

In other terms, you pay an extra in terms of performance (not that much probably, but it depends on your software) and get back a fully separated tool to use _when you can do it_.

**Comment by ArnCarveris** [comment]
@skypjack If all entities are valid, what penalty of performance will be?

**Comment by skypjack** [comment]
Consider using a standard multi component view. Take a component _Ci_ from the set of components _C0, C1, ..., Cn_, where _Ci_ is the component that pulls in fewer candidates. In that case, for each entity in _Ci_ you have to pay for a `has` on all the other pools (that's why there exist persistent views, they avoid all the checks and are incredibly fast mainly because of that).  
Spaces work similarly. They add approximately the cost of two `has` for each entity (plus the cost of the view, thus the total differs in case you are using a persistent view instead of a standard multi component view under the hood).

**Comment by skypjack** [comment]
@ArnCarveris 

Anyway, at a first glance and if I think at how I would use spaces, the (yet ridiculous) price of a space is paid only when you iterate entities through the space itself and it won't happen at each loop if you arrange properly the codebase.  
Therefore I wouldn't concentrate the discussion on the cost of a space. Instead I would like to talk about features and API so as to provide a tool that is both easy to use and worth it because of the problems it solves.

**Comment by ArnCarveris** [comment]
@skypjack 

>  Consider a space as a partition of a registry.
- Nope spaces cannot be treated as tool because in most cases this is core engine functionality.
- Space are isolated container, that should be managed by some kind of manager.
- But having partial registry tool might be useful for some use cases. 

There is some rude/experimental implementation of [spaces](https://github.com/ArnCarveris/entt/tree/space).

**Comment by skypjack** [comment]
@ArnCarveris 

> Nope spaces cannot be treated as tool because in most cases this is core engine functionality.

Having spaces as an external tool instead of part of the registry doesn't mean they are not treated as a core functionality. The other way around would be to put spaces in a map managed by a registry and slow down the `destroy` member function to keep each and every space in sync (even when you don't need and don't want to do that).  
I prefer much more a lazy clean done during iterations. It doesn't add much, the most of the cost is due to the test that combines a space and a view and you have it in both cases. The clean step is a call to the `destroy` member function of a sparse set, nothing more.

> Space are isolated container, that should be managed by some kind of manager.

Uhm. Honestly, it depends by the specific application. However, create a manager is straightforward when it's needed. If you can create spaces at runtime, you can give them a label or a numeric identifier using the `Family` class and create a _manager_ (whatever it means, I don't like much the idea of having _managers_) in a few minutes.

> But having partial registry tool might be useful for some use cases.

To sum up the design of `EnTT` we can say that - _if a class needs to access the internals of a registry, it's a good candidate to be part of it. Otherwise we can design it as an external tool with an eye to the performance._  
That's all. So far it proved to be a good choice, so I don't see any reason to change my mind.

> There is some rude/experimental implementation of spaces.

This implementation creates a kind of _set of registries_ where each space has its dedicated container to which to refer.  
I prefer to create logical partitions of a registry instead of using more than one registry. It solves a lot of problems nicely (as an example, keep the same entity in two or more spaces) and memory usage is easier to keep under control.  
Why do you think that using multiple registries is a better solution? I don't see any advantage in this but probably I'm missing something...

**Comment by skypjack** [comment]
> There is some rude/experimental implementation of spaces.

As a side note, in this implementation the design of `EnTT` changed entirely only to be able to add spaces in the form of _multiple instances of a registry_, thus forcing users to rely on spaces instead of registries. I don't think it's worth it. Space becomes a kind of core class in this model, while the registry should be considered the corner stone instead.  
It betrays a bit the philosophy of `EnTT` in order to add a feature that isn't a _desiderata_ for all the users.  
Moreover, please note that I'm still not considering performance and memory usage of this approach. I'm not that sure it's on the right path to improve things. My two cents.

**Comment by ArnCarveris** [comment]
@skypjack 
> thus forcing users to rely on spaces instead of registries.
- The registry API should be same, in addition of space management.

>the other way around would be to put spaces in a map managed by a registry and slow down the destroy member function to keep each and every space in sync (even when you don't need and don't want to do that).
- but I think is way better to create separate tool for space management and don't touch registry at all.

**Comment by skypjack** [comment]
> but I think is way better to create separate tool for space management and don't touch registry at all.

You didn't do it, right? Spaces on the experimental version you linked aren't an external tool. Instead, we can sum up it as _each space is a registry_ (set aside the fact that you changed its name to container):
```
class Space : public SpaceAccessor<Entity, Hash>::container_type;
```

It doesn't even require to add a `Space` class to do that. One can create a map string/registry and obtain more or less the same result without touching `EnTT`.

---

As a side note,hopefully I'll be able to push soon a first draft of the `Space` class as described in the issue.

**Comment by ArnCarveris** [comment]
@skypjack 
>(set aside the fact that you changed its name to container):
- I needed to take control of tag/component/view family types.
- Now is kind of ugly how I did this, but works for me now.

> It doesn't even require to add a Space class to do that.
- Idea is that you cant create space without accessor, later I'll implement manager for it.
- Space must have accessor.

> As a side note,hopefully I'll be able to push soon a first draft of the Space class as described in the issue.
- Ok, notify me.

**Comment by skypjack** [comment]
> I needed to take control of tag/component/view family types.

I see. Be aware that components will have different identifiers in different spaces. You won' be able anymore to easily add serialization/deserialization utilities this way. Consider it.  
Moreover, `EnTT` won't follow this model any time soon. It could complicate merging new features in your fork.

That being said, from my point of view you need to take control of those types because you are creating spaces out of registries. As long as each space is a registry (or container, as you named it), I can understand that taking control of types will reduce a bit the memory usage.  
However, I'd suggest you to consider if it's lower than implementing partition over a single registry. Probably (almost surely) no because of how sparse sets work.

On the other side, keep in mind also that this approach will complicate infinitely things like putting an entity in two spaces or moving entities from one space to another one.  
This way you can't do it, that's all. Both this tasks (as well as many others) will rely on copy and creation/destruction of entities/components on different registries. In addition, they pull in glue code to keep in sync entities in different registries.  
All this problems disappear if you create spaces as partitions of a registry. Did you consider it?

I don't understand why you think that using more than one registry (that is exactly what you are proposing to do) should be better than creating partitions over a single registry.  
Can you elaborate more about this point?  
As far as I can see, multiple registries (as used in the example) introduce several problems (a couple are listed above), increase memory usage, add nothing in terms of performance and make difficult if not even impossible to introduce other features like serialization/deserialization. I don't even want to talk about API, it changes drastically and becomes a bit ugly actually, but it's a WIP, so let it be at this point.  
What are the advantages? Why do you prefer so much this approach? Am I missing something?

> Now is kind of ugly how I did this, but works for me now.

I'm pretty sure it works for you. :-)  
However, general purpose libraries like `EnTT` should work for all the users.

> * Idea is that you cant create space without accessor, later I'll implement manager for it.
> * Space must have accessor.

I don't see the use case for _accessors_ honestly. Can you give me more details of what problem they solve exactly?

**Comment by ArnCarveris** [comment]
@skypjack 
> I see. Be aware that components will have different identifiers in different spaces. You won' be able anymore to easily add serialization/deserialization utilities this way. Consider it.
- This was intended.
- Space is isolated container.

> Probably (almost surely) no because of how sparse sets work.
- I haven't worked with sparse set yet.

> creating partitions over a single registry.
- I have no knowledge how to do it. 

> On the other side, keep in mind also that this approach will complicate infinitely things like putting an entity in two spaces or moving entities from one space to another one.
- I'll try to solve entity migration between containers later.
- Use case will be rare.

> What are the advantages? Why do you prefer so much this approach? Am I missing something?
- Processing whole space by need of context.
- Prefab(snapshot from content) support out of box.
- Out of box support for features like [in this unity asset](https://assetstore.unity.com/packages/tools/utilities/sectr-complete-15356)

Use case: 
- Having big world with ocean & archipelago of islands. driving huge ship that have interiors where can be walked & interacted with various dynamic objects and I don't care about processing not needed components of submarine underneath.
- Async un/loading by need.
- Loaded less than 10% of total count of entities from content.
- Using in runtime less that 25% of loaded entities due culling or VisArea(term from CryEngine).

For me handling those cases with single container, could be problematic for this scale. 

 > I don't see the use case for accessors honestly. Can you give me more details of what problem they solve exactly?
- Use accessor as component, or part of it.
- Process space by accessor, no need to make glue code for it.
- Manage instance life time via accessor.
- I'll make more tests later.

> I'm pretty sure it works for you. :-)
- I'll try to make it look less uglier, I haven't worked with ECS at all.

> However, general purpose libraries like EnTT should work for all the users.
- Totally agree with you.

**Comment by skypjack** [comment]
You probably know it, you can get most of the features for free with a single registry actually.  
I'm not that convinced that multiple registries are the way to go to have the features you are looking for at the end of the day. On the other side, I'm pretty convinced about all the problems we can find with this approach, most of the which are pretty obvious.  
However I'll think twice to it later. Perhaps I'm missing something important at the moment.

That being said, it won't be the approach used in `EnTT` probably, I'm sorry.  
Feel free to modify the code the way you want and that works better for you (it's MIT, right?), but do not expect support on implementing or integrating mainstream features in future.  
I'm already short in time to be able to work on `EnTT`, so I cannot support forks actively in any case.

**Comment by ArnCarveris** [comment]
@skypjack 

> That being said, it won't be the approach used in EnTT probably, I'm sorry.
No problem, I need better work on that, following WIP was done within couple hours, because of that this brutally rude.

> However I'll think twice to it later. Perhaps I'm missing something important at the moment.
Later when you implement partial registry I'll compare with my approach with real test case, meantime I'll wait your implementation & improve own approach.

> but do not expect support on implementing or integrating mainstream features in future.
 Ok, I'll not do any PR in near future related with spaces.

**Comment by skypjack** [comment]
> Ok, I'll not do any PR in near future related with spaces.

Yeah, thanks, I couldn't accept it anyway at the moment, mainly because the line here is to keep intact the registry and its API. Moreover, your changes would break completely the stuff on the `snapshot` branch and it's not acceptable for me. I prefer spaces implemented as an external tool as long as performance are acceptable, because it makes easier to implement serialization/deserialization utilities and a lot of other features I've in the TODO list. A multi-registry approach with no global numeric identifiers for types pulls in some problems that I prefer to keep off the way if possible.

Ping me in any case when you're done. Who knows if you find the best way to implement spaces in `EnTT`? ;-)

> Later when you implement partial registry I'll compare with my approach with real test case, meantime I'll wait your implementation & improve own approach.

Good. Results are something in which I could be interested. However, they must be considered along with features allowed/forbidden by the different approaches.

**Comment by ArnCarveris** [comment]
@skypjack 
> A multi-registry approach with no global numeric identifiers for types pulls in some problems that I prefer to keep off the way if possible.
- Totally agree with that.
- Only space manager is allowed to manage instances(like view instance creation restriction).
- Space instance reference can be getted only from manager via space accessor class.
- Multiple space manager instances will be not allowed.

**Comment by skypjack** [comment]
It doesn't change the fact that a given type `T` will have different numeric identifiers within different spaces, at least the way you implemented them. No matter if you hide everything behind a _manager_ (whatever it means) and if you forbid creation of multiple managers. It will break things like serialization/deserialization, merge between spaces and so on in any case, but keep in mind that the list is much longer than this.  
Type erasure based on static casts that are possible because of known unique identifiers for types won't work anymore and thus you must find another technique to work around the limitation. Do you get it?

**Comment by skypjack** [comment]
[Here](https://github.com/skypjack/entt/tree/space) it is.

The same branch contains also some optimizations and a few other changes. Not everything is related to spaces. Probably a better name for it would have been `experimental`, anyway...  
I'm almost ready to merge it on `master`. I need to update the README file (so that @Djuego won't blame me :-)) and I'm done.

Feedback are highly appreciated.

**Comment by skypjack** [comment]
Upstream. Time to close the issue. Thank you all for your help.

**Comment by UnoYakshi** [comment]
Maybe, it's too late, but Spaces sounds like something like a complicated version of **tagging**.
Pseudo-code:

    object_1->tags = ["ai"];
    object_2->tags = ["vfx", "art"];
    object_3->tags = ["physics", "art"];
    
    auto spaceslike_object = find_by_tags(["vfx", "ai"]);  // Returns the first two objects...`

**Comment by skypjack** [comment]
Yep. At the end of the day, you can also create spaces using a component. Assign the component to all those entities you want to put in the given space, then create views that use *also* that component. Done.  
The goal was/is only to provide users with a more user-friendly tool that uses even less memory if possible.

So far, I haven't been able to find a solutions that is satisfying, so... Well, we'll see. I can live without them, at least for a while. :-)
