### ISSUE TITLE
warning: declaration of 'exclude' hides global declaration

### ISSUE THREAD

**Issue by cholmquist** [skypjack/entt#540]
`
entt\src\entt\entity\runtime_view.hpp(66): warning C4459: declaration of 'exclude' hides global declaration
`
`
entt\src\entt\entity\utility.hpp(24): note: see declaration of 'entt::exclude'
`

Issue encountered with MSVC 2017.

**Comment by skypjack** [comment]
Thanks for pointing this out. 👍
