### ISSUE TITLE
Commit be936438084ee1533c808e2c17eec34b3d769ac4 crashes clang under Emscripten 😯

### ISSUE THREAD

**Issue by nikki93** [skypjack/entt#541]
That change (be936438084ee1533c808e2c17eec34b3d769ac4) (found using `git bisect`) crashes clang (!) under Emscripten for me with the following:

```
FAILED: CMakeFiles/sdl-test.dir/cmake_pch.hxx.pch
C:\Users\nikki\Development\emsdk\upstream\emscripten\em++.bat   -I../../vendor/stb -I../..
/vendor/entt/src -I../../vendor/Chipmunk2D/include -I../../vendor/rapidjson/include -I../.
./vendor/fmt/include -DNDEBUG -O2   -fcolor-diagnostics -pedantic-errors -Wall -Wextra -Wn
o-missing-braces -s USE_SDL=2 -std=c++17 -Xclang -emit-pch -Xclang -include -Xclang C:/Use
rs/nikki/Development/sdl-test/build/web-release/CMakeFiles/sdl-test.dir/cmake_pch.hxx -MD
-MT CMakeFiles/sdl-test.dir/cmake_pch.hxx.pch -MF CMakeFiles\sdl-test.dir\cmake_pch.hxx.pc
h.d -o CMakeFiles/sdl-test.dir/cmake_pch.hxx.pch -c CMakeFiles/sdl-test.dir/cmake_pch.hxx.
cxx
Assertion failed: isa<X>(Val) && "cast<Ty>() argument of incompatible type!", file C:\b\s\
w\ir\cache\builder\emscripten-releases\llvm-project\llvm\include\llvm/Support/Casting.h, l
ine 263
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, prep
rocessed source, and associated run script.
Stack dump:
0.      Program arguments: C:/Users/nikki/Development/emsdk/upstream/bin\clang++.exe -targ
et wasm32-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=39 -D__EMSCRI
PTEN_tiny__=16 -D_LIBCPP_ABI_VERSION=2 -Dunix -D__unix -D__unix__ -Werror=implicit-functio
n-declaration -Xclang -nostdsysteminc -Xclang -isystemC:\Users\nikki\Development\emsdk\ups
tream\emscripten\system\include\libcxx -Xclang -isystemC:\Users\nikki\Development\emsdk\up
stream\emscripten\system\lib\libcxxabi\include -Xclang -isystemC:\Users\nikki\Development\
emsdk\upstream\emscripten\system\lib\libunwind\include -Xclang -isystemC:\Users\nikki\Deve
lopment\emsdk\upstream\emscripten\system\include\compat -Xclang -isystemC:\Users\nikki\Dev
elopment\emsdk\upstream\emscripten\system\include -Xclang -isystemC:\Users\nikki\Developme
nt\emsdk\upstream\emscripten\system\include\libc -Xclang -isystemC:\Users\nikki\Developmen
t\emsdk\upstream\emscripten\system\lib\libc\musl\arch\emscripten -Xclang -isystemC:\Users\
nikki\Development\emsdk\upstream\emscripten\system\local\include -Xclang -isystemC:\Users\
nikki\Development\emsdk\upstream\emscripten\cache\wasm\include -DEMSCRIPTEN -fignore-excep
tions -I../../vendor/stb -I../../vendor/entt/src -I../../vendor/Chipmunk2D/include -I../..
/vendor/rapidjson/include -I../../vendor/fmt/include -DNDEBUG -O2 -fcolor-diagnostics -ped
antic-errors -Wall -Wextra -Wno-missing-braces -std=c++17 -Xclang -emit-pch -Xclang -inclu
de -Xclang C:/Users/nikki/Development/sdl-test/build/web-release/CMakeFiles/sdl-test.dir/c
make_pch.hxx -MD -MT CMakeFiles/sdl-test.dir/cmake_pch.hxx.pch -MF CMakeFiles\sdl-test.dir
\cmake_pch.hxx.pch.d -c CMakeFiles/sdl-test.dir/cmake_pch.hxx.cxx -Xclang -isystemC:\Users
\nikki\Development\emsdk\upstream\emscripten\cache\wasm\include\SDL2 -c -o CMakeFiles/sdl-
test.dir/cmake_pch.hxx.pch -mllvm -combiner-global-alias-analysis=false -mllvm -enable-ems
cripten-sjlj -mllvm -disable-lsr
1.      ../../vendor/entt/src\entt/entity/view.hpp:163:24: current parser token '...'
2.      ../../vendor/entt/src\entt/entity/view.hpp:20:1: parsing namespace 'entt'
3.      ../../vendor/entt/src\entt/entity/view.hpp:67:1: parsing struct/union/class body '
entt::basic_view<Entity, exclude_t<Exclude...>, Component...>'
 #0 0x00007ff60ec41fc6 (C:\Users\nikki\Development\emsdk\upstream\bin\clang++.exe+0x1041fc
6) 
```

The only somewhat related thing I can find online is: https://github.com/emscripten-core/emscripten/issues/8731

I don't think this is entt's fault, but maybe we could do a workaround? I don't think I understand the bug completely but it's definitely due to that particular commit. I'll also check if I can change compiler flags or something and it happens, and will also try on native (not Emscripten) clang on macOS soon. Latest version of entt builds fine for me under MSVC though.

edit: Yeah it compiles fine on native clang 10 (macOS), so just seems to be an issue with the clang version that Emscripten is using.

**Comment by skypjack** [comment]
Wow, impressive. Crashing clang isn't that easy.
Did you find something more on this? I've some problems to reproduce the error unfortunately.
Is the _unpack-as_ utility that makes it crash?

**Comment by skypjack** [comment]
Hi, any news on this?

**Comment by nikki93** [comment]
Hey! Will try this again today and report back. :)

**Comment by nikki93** [comment]
So I've tried a bunch of different ways of expanding `epool` and they are all leading to the same crash. What finally worked was indeed just not using the `unpack_as_t` utility at all:
```
    template<typename ... Es>
    basic_view(pool_type<Component> &... component, Es &&... epool) ENTT_NOEXCEPT
```
but this removes the type safety of the existing constructor, so not meaning this to be the 'real' fix but just to see if that gets it to compile. Again this only happens on emscripten's version of clang and not native clang.

Maybe there is a different way to implement `unpack_as_t` that does compile? I'll try some other ones out.

**Comment by skypjack** [comment]
Is it possible to provide a compilable example with which I can reproduce the error?
This would make it easier to experiment and we can also add it among the other examples in the repo, so that I can guarantee backward compatibility in future.

**Comment by nikki93** [comment]
Sure, I'll set up an example soon! The example would need setting up the emscripten toolchain to compile, but hopefully that doesn't involve too many steps / I'll try to put some clear instructions in.

**Comment by nikki93** [comment]
Haven't had a chance on this yet, will try to get to it this weekend. :)

**Comment by nikki93** [comment]
entt master works with latest emscripten (just tried to update today) so this is now fixed. :)
