### ISSUE TITLE
Documentation unclear as to which functions trigger which "on_..." signals

### ISSUE THREAD

**Issue by cschreib** [skypjack/entt#543]
For EnTT 3.4.0. The registry has three signals that are triggered when components are modified:
 - on_construct()
 - on_update()
 - on_destroy()

The functions to modify the components are:
 - emplace()
 - emplace_or_replace()
 - get_or_emplace()
 - insert()
 - patch()
 - replace()
 - remove()
 - ...

My point is, the link between the signals and these functions isn't immediately obvious, because the names don't match at all. For example, does ``replace()`` trigger ``on_destroy()`` then ``on_construct()`` (since it destroys the old component and constructs a new one), or ``on_update()`` (since it modifies an existing component)? Or all of them? The documentation doesn't specify which signals are triggered, which would be helpful.

Somewhat related, I was wondering if the registry had signals to monitor updates of the context variables? That would be useful.

(I've been using EnTT for a new pet project; I've never used an entity-component system before and I'm liking the change :) Great library, thank you.)

**Comment by skypjack** [comment]
So, do you suggest to integrate the documentation?
Probably this is a call for a FAQ. Does it sound good?

**Comment by cschreib** [comment]
I guess it depends on what EnTT does. If the logic can be fully explained in generic terms, for example:
 - on_created() is called when a component is first added (not modified or replaced) to an entity
 - on_update() is called whenever an existing component is modified or replaced
 - on_destroyed() is called when a component is explicitly removed from an entity (plus when the owning entity is destroyed I guess?)
... then the FAQ is probably the most efficient, although I must admit this is not the place I'd go looking for information in the first place; I always go to the docs first.

But if the logic is a bit more complicated and specific to each function, for example if ``replace()`` calls both ``on_destroyed()`` then ``on_created()``, then the docs are definitely the place to add this information.
