### ISSUE TITLE
Add a registry function to notify that a component has been modified in place?

### ISSUE THREAD

**Issue by cschreib** [skypjack/entt#544]
The registry has the ``patch()`` function, which is good for modifying a component in place. However this isn't optimal when the same component needs to be updated multiple times (i.e., in a loop), as ``patch()`` needs to lookup the entity in the registry each time (and it does it twice internally, afaik). In such cases, it would be more performant and more convenient to first take a reference to the component, and update it as many times as required. However, because this only causes an "implicit" change, it will not trigger the ``on_update()`` signal.

As far as I know, there are two ways to go around this currently (``r``: registry, ``e``: entity, ``C``: component type, ``c``: component instance that we just modified):
 - Call ``r.patch<C>(e, [](auto&){});``. That's not too bad, but the syntax is cumbersome and the meaning is not immediately obvious.
 - Call ``r.replace<C>(e, c);`` with the reference to the modified component. Syntax and meaning are OK, but we're paying for an extra copy. EnTT could check for self-assignment and short-circuit the copy, but it doesn't at the moment.

It seems to me a natural solution would be to add a new function, let's call it ``r.update<C>(e)``, which only takes the entity as argument, and whose sole purpose would be to trigger the ``on_update<C>()`` signal.

**Comment by skypjack** [comment]
You can already do this. Something along this line should work:
```
auto &component = registry.get<T>(e);
// edit the component
registry.patch<T>(e);
```
I wouldn't add a dedicate function to do the same to be honest. It seems overkilling to me.

**Comment by cschreib** [comment]
Ah!! I didn't realize you could call ``patch()`` without a second argument :) My mistake. Thanks!

**Comment by skypjack** [comment]
You're welcome. 👍
