### ISSUE TITLE
Question: use member template function as a on_construct callback?

### ISSUE THREAD

**Issue by GavinNL** [skypjack/entt#545]
Hello

Is there any way do do something like this? I'm trying to use a templated member function as a callback, but it doesn't seem to work with templates. Gcc says it is unable to deduce auto

```
struct Project
{
    entt::registry m_registry;

    template<Comp>
    void onDestroy(registry &r, entity e);

    Project()
    {
        m_registry.on_destroy<MyComp>().connect< &Project::onDestroy<MyComp>  >(*this);
        m_registry.on_destroy<MyComp2>().connect< &Project::onDestroy<MyComp2>  >(*this);
    }
    
};

template<>
inline void Project::onDestroy<MyComp>(entt::registry & r, entity e )
{
    ...
}

template<>
inline void Project::onDestroy<MyComp2>(entt::registry & r, entity e )
{
    ...
}

```

**Comment by skypjack** [comment]
Afaik it should work. Can you provide a minimal example (you can use the online tool, see the README) and the error returned by GCC? Thanks.

**Comment by GavinNL** [comment]
Hmmm... you know what I think this is more of a C++ level problem I'm having.  I think i'm trying to do something that's not C++ complaint.

I will close this.
