### ISSUE TITLE
I made simple 2.5D space shooter game using entt

### ISSUE THREAD

**Issue by kwarkGorny** [skypjack/entt#546]
Hey,
I made basic 2.5D space shooter using entt and opengl in 2 weeks as home assignment and I would be very happy if it can be added to "EnTT in Action" wiki section of course if it is good enough.
link: https://github.com/kwarkGorny/3DGame

**Comment by skypjack** [comment]
Great, you've also used the forward headers! Finally someone noticed them.
You deserve a mention. Thanks for sharing. 😉

**Comment by skypjack** [comment]
Updated the wiki.
