### ISSUE TITLE
Feature request: Early iteration canceling

### ISSUE THREAD

**Issue by Dakror** [skypjack/entt#547]
A nice but small addition to view iteration would be the ability to bailout early.

This is already possible using the classic foreach loop, but when using the each() function, it is not.

A common solution to this would be a version accepting a function returning bool to break the loop early.

**Comment by skypjack** [comment]
On `master there is a new iterator for views:
```
for(auto [pos, vel]: registry.view<position, velocity>().proxy()) {
    // ...
}
```
It works literally as the `::each` member function internally and it makes it easy to break it.
Imho we don't need an _extended_ `each`, this is more than enough for the purpose. Am I wrong?
