### ISSUE TITLE
Instantiate a registry in another registry

### ISSUE THREAD

**Issue by OverShifted** [skypjack/entt#554]
Hello and thanks for the awesome library.

Is there any way for Instantiating entities or registries in another registry? (like prefabs in Unity)
Or I should implement my way of doing this?

#### My incomplete way of doing this:
All of my components are derived from the `Component` struct

```c++
class ScenePrefab
{
    ...

    std::unordered_map<uint32_t, std::vector<Component>> m_EntitiesComponentsList; // Like entt::registry
    ...
};
```
```c++
class EntityPrefab
{

    ...

    uint32_t m_Id; // Like entt::entity
    ScenePrefab* m_ScenePrefab;
    ...
};
```

of course this is not runtime optimized

**Comment by skypjack** [comment]
Hi, thank you for using the library.
There is no built-in way to do this. I usually use a separate registry with a completely different type for identifiers, then I use `visit` and the meta system to copy full _concepts_ from one side to the other.
Among the other things, I'm working to make this part easier to implement and to use but it's not high priority, so I can't really give an ETA at the moment. I'm sorry.

**Comment by OverShifted** [comment]
why you said `I usually use a separate registry with a completely different type for identifiers` ?
why `completely different type for identifiers` ?

**Comment by skypjack** [comment]
1. I want to minimize the risk of using an identifier from one registry with a different registry, that's all. This isn't strictly necessary, just useful.
2. No, sorry, it's not `std::visit`, it's `registry::visit`. My fault. 🙂

**Comment by OverShifted** [comment]
OK. Thank you very much.
I didn't know about `registry::visit`

**Comment by skypjack** [comment]
You're welcome. :+1:
Ping me if you need help or join us on gitter or discord if you like, for a more direct discussion. :wink:
