### ISSUE TITLE
Cannot create meta_any from pointer to const registry

### ISSUE THREAD

**Issue by Lawrencemm** [skypjack/entt#556]
The instantiation of the dereference operator in meta_any seems to be doing a copy inside it when the pointed-to type is const, which is failing because the registry is not copyable.

It would be good if we can keep const pointers to registry in the meta_any objects, so that we don't need to remove const from the registry in places where meta anys are being created, such as invoking meta functions that take a const registry pointer.

**Comment by skypjack** [comment]
As discussed on discord, I need to check if a pointer-like type is also copyable other than non-const. In all other cases, an empty `meta_any` is returned.

**Comment by Lawrencemm** [comment]
Should probably be an assert in there if you dereference a pointer to const meta any because otherwise getting an empty result might be really hard to debug if you don't realise what's going on.

**Comment by skypjack** [comment]
Fair enough. What if the type isn't a pointer-like one though? Still an assert as if it was but it's const and non-copyble?
Note that for const bit copyable types, derefencing a meta any triggers a copy of the dereferenced type. In all other cases you receive an aliased object instead.
