### ISSUE TITLE
[Request] Please make wiki documentation of hashed strings very slightly more explicit.

### ISSUE THREAD

**Issue by sniggyfigbat** [skypjack/entt#559]
The hashed-string functionality is great, and very useful. However, the way it is explained and demonstrated [in the wiki](https://github.com/skypjack/entt/wiki/Crash-Course:-core-functionalities#hashed-strings) led me to the incorrect conclusion that hashed strings *only* worked as const expressions, and couldn't be hashed at runtime. I laboured under this misapprehension until I discovered issue #34 essentially at random. This was entirely user error, but I suspect I may not be the only one to get the wrong idea from the given examples. 

A simple change in the example would make this misunderstanding impossible:
```
void doSomething(const std::string& str) {
    entt::hashed_string hStr{str.c_str()};
    // ...
}
```

I don't know whether you think this a worthwhile amendment, but it would have saved me a lot of wasted time.

**Comment by skypjack** [comment]
I have no doubt that the documentation can be improved, don't worry! 🙂 
Do you want to open a PR for that or do you trust me? 😄

**Comment by sniggyfigbat** [comment]
I'm entirely happy to let you take care of it!

Out of interest, is there any way to do a similar runtime-definition of tags? I assume not, since they're templated, right?

**Comment by skypjack** [comment]
Exactly, they are a compile-time thing. I'm sorry.
