### ISSUE TITLE
Question regarding raw() and size<Component>

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#560]
Hello!

I hope your well. I got tripped up today when working with the [raw()](https://github.com/skypjack/entt/blob/91e63d0f1953522e3a4d81dcfd257c29001ea50d/src/entt/entity/registry.hpp#L309) function of the registry. The [documentation ](https://github.com/skypjack/entt/blob/91e63d0f1953522e3a4d81dcfd257c29001ea50d/src/entt/entity/registry.hpp#L295)uses [] to indicate a range, traditionally [] are used to indicate a [closed range](https://en.wikipedia.org/wiki/Interval_(mathematics)#Terminology). Without knowing your opinion, my sense is replacing the closing "]" with a ")" is more correct. What do you think?

https://godbolt.org/z/fKrqo4

**Comment by skypjack** [comment]
Ah, good point.

**Comment by bjadamson** [comment]
Looks like there's more than one place: 

1. https://github.com/skypjack/entt/blob/91e63d0f1953522e3a4d81dcfd257c29001ea50d/src/entt/entity/view.hpp#L393
1. https://github.com/skypjack/entt/blob/91e63d0f1953522e3a4d81dcfd257c29001ea50d/src/entt/entity/group.hpp#L236
1. https://github.com/skypjack/entt/blob/91e63d0f1953522e3a4d81dcfd257c29001ea50d/src/entt/entity/storage.hpp#L197

Probably some more I don't know about

**Comment by bjadamson** [comment]
Also the data() functions seems to have the same verbiage.
