### ISSUE TITLE
Is it possible to create a view from begin/end iterators?

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#563]
I have a vector of entities that are a subset of all entities within my registry. These entities contain `>=1` component I am interested in viewing. Is this code possible?

```C++
std::vector<entt::entity> ids;
...
auto begin = std::begin(ids);
auto end   = std::end(ids);

// Does something like this exist? (constructing a view from a pair of iterators)
auto view = registry.view<ComponentA, ComponentB>(begin, end);
```

I know it's possible to do this manually like so: 
```C++
for (auto const id : ids)
{
    auto const& ca = registry.get<ComponentA>(id);
    auto const& cb = registry.get<ComponentB>(id);
    ...
}
```

However this feels like I'm programming at a lower level, instead of programming what I want to do, it feels like I'm programming how to do it. I'm sorry again if I missed a way to do this that's spelled out in the wiki / inline documentation, if it's there I haven't been able to find it.

Thanks :)

**Comment by skypjack** [comment]
Hit there,

It's not possible actually.
I think the main problem is that the view cannot be sure that those entities really have the components.

Why don't you just iterate the vector and get the components from the view instead? Something like:
```
auto view = registry.view<Component A, ComponentB>();

for(auto id: ids) {
    auto [ca, cb] = view.get(id);
    // ...
}
```

**Comment by bjadamson** [comment]
I hadn't considered creating the view with no arguments before, this should work perfectly. Thank you :)

**Comment by skypjack** [comment]
You're welcome. :+1:
