### ISSUE TITLE
size() of multi component view seems wrong?

### ISSUE THREAD

**Issue by s9w** [skypjack/entt#567]
```c++
#include <entt/entt.hpp>

struct A {};
struct B {};
struct C {};

int main() {
   entt::registry registry;

   {
      auto A_and_B = registry.create();
      registry.emplace<A>(A_and_B);
      registry.emplace<B>(A_and_B);
   }
   {
      auto A_and_C = registry.create();
      registry.emplace<A>(A_and_C);
      registry.emplace<C>(A_and_C);
   }

   const auto before = registry.view<A, B>().size(); // 1
   {
      auto only_B = registry.create();
      registry.emplace<B>(only_B);
   }
   const auto after = registry.view<A, B>().size(); // 2

   return 0;
}
```
As I understand it, multi component views mean entities that contain *all* the components. Quoting from `view.hpp`: "Multi component views iterate over those entities that have at least all the given components in their bags". So why is the view size two when there was no second entity added with both A and B? I'm probably understanding something wrong.

**Comment by skypjack** [comment]
In fact, it's a _size hint_ and it has already been renamed to `size_hint` for the next version, to avoid errors.
The view estimates only the maximum amount of entities that can be returned during an iteration.

**Comment by s9w** [comment]
I see, so is there a way to get the actual number of such entities other than iterating?

**Comment by skypjack** [comment]
Groups know the exact number of multi-type sets. Views do not, unless ofc you iterate them.

**Comment by s9w** [comment]
Got it. Thanks a lot!

**Comment by skypjack** [comment]
You're welcome. I also invite you to join the gitter channel or the discord server if you've any other question like this one. You may get a response much faster from whoever is there! 😉
