### ISSUE TITLE
add/remove entity from registry temporarily?

### ISSUE THREAD

**Issue by bjadamson** [skypjack/entt#568]
Is it possible to add/remove an entity from a registry??

I have a "disabled" component that currently tracks whether a component is "disabled", meaning the game engine should completely ignore it (however the level editor should not). The engine currently excludes entities with this component, and the level editor does not when "show disabled entities" is enabled.

This is troublesome for code maintenance. I need to remember to add `exclude<Disabled>` to all my views within the engine, and it is also not ideal for performance. Basically all my views need the `exclude<DisabledTAG>` passed to it's constructor, which I believe has worse performance than if no components are excluded.

My hope is that I could manage these entities externally from the registry by adding or removing them from the registry. Essentially storing disabled entities in a `std::vector<entt::entity>`.

My initial idea is to register functions during initialization that would automatically add/remove the entity from the registry whenever the `DisabledTAG` component is added to a registry. This allows my engine to add/remove the `DisabledTAG` just like any other component, which seems nice. Does this seem like a good strategy?

The code demonstrating my idea is as follows:

```c++
using DisabledTAG = entt::tag<"DisabledTAG"_hs>;

void
on_tag_disabled_added(entt::registry& es, EID const id)
{
  es.remove(id); // No component type here, I want to remove the entity `id` from the registry.
}

void main()
{
  ....

  entt::registry es;
  es.on_construct<DisabledTAG>().connect<&on_tag_disabled_added>();

 // somewhere else in my code bases
 for (auto const id : disabled_entities)
 {
   es.add(id); // Add the entity back to the registry
 }
 ...
}
```

**Comment by bjadamson** [comment]
It occurred to me I could instead maintain a second registry, a 'disabled' registry, and move entities between the registries. I'm going to see if it's possible to easily moving an entity from one registry to another.

**Comment by bjadamson** [comment]
Feel free to not bother responding here, I changed my design once I re-evaluated what my design goals were. It helps knowing more about **entt**'s internals, which I'm slowly getting a better grasp over time.

Anyway the rest of this thread is intended for anyone who finds this thread in the future while trying to do something similar. My goal was to improve iteration time, and the tradeoff I came up with is to pay more to "disable" or "enable" things by just moving the component that's being disabled to a secondary registry.. Using your instructions from [here](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#stamping-an-entity) I was able to get something basic working.

I'll post something once I get more time to test it works exactly how I want it too.

**Comment by skypjack** [comment]
Sorry for being late. I had some personal problems over the weekend and didn't even have time to spend on GH.
I see you solved it though. In order to add more information for future readers, I'm about to push some changes for an improved support to custom pools. One of the examples I'll add to the `test` directory is that of an enabled/disabled component. This could be another way of solving your issue. 👍 
Though, yeah, for full entities, I'd rather use a secondary registry. I've in the TODO list to re-add the copy functionality, so that moving entities across registries will be easier and you won't have to to what I mentioned in the link. 😉

**Comment by bjadamson** [comment]
Bruh don't apologize, I don't know you but I do hope your personal problems get resolved soon. :)

That's exciting news about the custom pools, will you be writing a blog post about them? I do enjoy reading your blog, it has helped me tremendously. Especially your blog post about using entt to manage entity hierarchy's.

Anyways, here's the specific solution I'm using in my game engine if it helps anyone in the future before custom pool support comes about. It's missing template parameters for the Entity type, as I use the EID typedef everywhere, and noexcept because I'm still not exactly sure where I can use it w/regard to entt yet. Hopefully this can be cleaned up some more in the future, but it works for now.

```c++
using EID = entt::registry::entity_type;

enum class EnabledState : bool
{
  DISABLED = 0,
  ENABLED,
};

namespace disabled::detail
{
template<typename Type>
void
stamp(entt::registry const& from, entt::entity const src, entt::registry &to, entt::entity const dst)
{
  to.emplace_or_replace<Type>(dst, from.get<Type>(src));
}

} // namespace disabled::detail

template <typename Component>
struct ComponentSourceId final
{
  EID const id;
};

class DisabledSystem final
{
  entt::registry disabled_;
  entt::entity&  es_;

  using stamp_fn_type = void(entt::registry const&, entt::entity, entt::registry&, entt::entity);

private:
  template <typename Component>
  void
  move_between(EID const src, entt::registry& from, entt::registry& to)
  {
    auto const dst = to.valid(src)
        ? src
        : to.create(src);
    assert(dst == src);
    from.visit(src, [&](auto)
    {
      disabled::detail::stamp<Component>(from, src, to, dst);
    });
    from.remove<Component>(src);
  }

public:
  NO_MOVE_OR_COPY(DisabledSystem);
  DisabledSystem(entt::entity& es)
    : es_{es}
  {}

public:
  template <typename Component>
  auto status(EID const id) const
  {
    auto const has_component = [id](auto& registry)
    {
      return registry.valid(id)
        ? registry.has<Component>(id)
        : false;
    };
    assert(has_component(es_) != has_component(disabled_));
    return es_.has<Component>(id)
      ? EnabledState::ENABLED
      : EnabledState::DISABLED;
  }

  template <typename Component>
  void
  disable(EID const src)
  {
    auto& from = es_;
    auto& to   = disabled_;
    move_between<Component>(src, from, to);
  }

  template <typename Component>
  void
  enable(EID const src)
  {
    auto& from = disabled_;
    auto& to   = es_;
    move_between<Component>(src, from, to);
  }

  template <typename Component>
  void
  toggle(EID const id)
  {
    switch (auto const st = status<Component>(id); st)
    {
    case EnabledState::DISABLED:
      enable<Component>(id);
      break;

    case EnabledState::ENABLED:
      disable<Component>(id);
      break;
    }
  }
};
```

**Comment by skypjack** [comment]
> That's exciting news about the custom pools, will you be writing a blog post about them?

Definitely, more than one probably. I want to show how we can use custom pools to solve many different problems. 👍
