### ISSUE TITLE
[Question/Request] Is there any way to publish a signal while explicitly excluding certain sinks?

### ISSUE THREAD

**Issue by sniggyfigbat** [skypjack/entt#570]
I've been using signals for inter-component communication, specifically informing components when things happen to the transform component. This works alright, provided I build in a somewhat ugly and inefficient signal-forwarder at a static address - it's one of those solutions I'd probably do differently were I to do it again, but it works.

However, I have a slight problem wherein I get feedback loops with my physics components. I use the physics component to update the transform to where the physics object is, which then chains back into updating my physics component to tell it that the transform has been moved. I need the functionality in both directions in case some other game logic effects the transform or whatever. My current solution is to simply set a bool in the physics component, telling it to ignore the next incoming update from the transform component, but this is awful and fragile and incredibly bad practise in many ways.

Is there any way to specifically exclude a list of sinks by address when using `publish()`? If not, might this not be a useful functionality? Or is my architecture just irredeemably flawed and this sort of feedback loop only a problem when doing something fundamentally stupid?

**Comment by skypjack** [comment]
🤔 
There isn't at the moment a way to _exclude_ a listener. If it's attached to a signal, there is a reason usually.
You can remove then reassign it. Or we can make the signal object _iterable_ and let the user invoke the delegates. In this case, you can filter out a delegate if the object associated with it has a specific address (it's returned as `const void *` but still).

**Comment by sniggyfigbat** [comment]
Making it possible to iterate through delegates manually sounds like it might be quite useful, if that makes sense with the internals and wouldn't take too much work. Tangentially, is there any way to order the call priority of delegates?

**Comment by skypjack** [comment]
> if that makes sense with the internals

The first question is if it makes sense at all. You're use case is pretty odd and probably quite unique to be honest.

> Tangentially, is there any way to order the call priority of delegates?

No, mainly because to me this kind of things smells a little. 🙂 But you can have it wit ha bouncing signal if you like.

**Comment by sniggyfigbat** [comment]
All things considered, I think I'm probably just using the signalling functionality wrong. Will close the issue, as this is an architectural issue within my code rather than a missing feature in EnTT.
