### ISSUE TITLE
Test: an upstream regression in googletest causes the CI to fail repeatedly

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#571]
Get around it and rollback the changes when the problem is fixed in the dependency library.

**Comment by Innokentiy-Alaytsev** [comment]
TBH, I'd rather use a fixed version then `master` in any case.

**Comment by skypjack** [comment]
Yeah, I didn't realize they cut a release on March. The previous one was from 2018 and definitely unusable. This is the reason for which I was using `master`. 🙂

**Comment by skypjack** [comment]
I'm closing this. It makes sense to use the last tag now that it's not from 2018 anymore. 👍
