### ISSUE TITLE
[Question] How do I go about binding member functions of components?

### ISSUE THREAD

**Issue by sniggyfigbat** [skypjack/entt#572]
This is a functionality that would be useful generally, but I'm specifically encountering it while trying to build an inter-component / inter-object messaging system. I simply cannot work out how to build a clean solution that does not involve function-binding. With static objects, that's straightforward: use `std::bind` and give it the component instance. However, with EnTT the components are not static (as I understand it?), and thus `std::bind` will break whenever EnTT's memory manager moves things (again, as I understand it - I may be completely wrong, in which case this is a non-problem).

How can I store an `entt::entity` value, possibly some sort of indicator of component class, and some kind of function pointer to a component member function, and then later get the right type of component attached to the entity and call the appropriate member function? Is there some solution built into EnTT that I've missed? Otherwise, how have other people solved this problem cleanly and efficiently?

**Comment by skypjack** [comment]
I'm not sure I get what you're trying to do. Probably, you should describe the problem you are facing rather than the solution you're implementing (and don't like).

Inter-component communication is reduced to that between entities in this kind of models.
So, for example, if you want a 1-to-1 message, you can attach a component to the entity that triggers the event and let it store the id of the target entity. Otherwise, if you want a 1-to-many communication, you can attach components to the entities that are interested in that type of message and visit them when you trigger the even, by putting eventually the id of the sender in their components.
I'm also more oriented to multiple types for multiple events, but afaik you want something more _generic_, right? Well, with the solutions above, you can use a delegate on the message type that stores all what is needed to perform an action, whatever it is.
And so on. There are plenty of solutions but I can't figure out exactly what the right one is for you, since I've no clue on what you're trying to do to be honest.

**Comment by sniggyfigbat** [comment]
Hi Michele! Sorry if I'm being a pain with these questions; I just hope it's of some minor use to you in demonstrating pain-points for new EnTT users.

Let us assume that I have the following classes to be used as components:

```
class Type1 : public Component {
private:
    std::map<entt::hashed_string::value_type, std::vector<std::function<void(void*)>> m_callbacks; // The _hs is the message, which, when triggered, will call all associated callback functions.
public:
    void addCallbackFunc(entt::hashed_string::value_type message, std::function<void(void*)>& func) {
        if (!m_callbacks.contains(message)) { m_callbacks[message] = {}; }
        m_callbacks[message].push_back(func);
    }
    void triggerEvent(entt::hashed_string::value_type message, void * data = nullptr, bool cleanupData = false) {
        if (m_callbacks.contains(message)) {
            for (auto& func : m_callbacks[message]) { func(data); }
        }
        if (cleanupData && data != nullptr) { delete data; }
    }

    void thingHappens() {
        /* ... */
        triggerEvent("thing_type2_cares_about"_hs);
        /* ... */
    }
};

class Type2 : public Component {
private:
public:
    void callbackFunc(void * data) { /* ... */ }

    void initialise() {
        Type1 * t1 = getType1ComponentInSomeWay();
        t1->addCallbackFunc("thing_type2_cares_about"_hs, std::bind(&Type2::callbackFunc, this, std::placeholders::_1);
    }
};
```

This is an unsophisticated example, but hopefully it gets the point across. Type2 cares about certain things that Type1 does. Were I rolling my own simple entity-component system, I'd create and destroy these components with `new` and `delete`, and this would work fine because their memory addresses would never move.

However, my understanding is that EnTT will move component instances around in memory to keep memory contiguous and well-optimised. As such, the example given above will not work, because the std::bind instances will presumably fail catastrophically when the instance they're pointing to is moved - again, an assumption on my part.

The obvious solution to this is to replace `initialise()` with this:

```
    void Type1::initialise() {
        Type1 * t1 = getType1ComponentInSomeWay();
        entt::entity myEntity = getMyEntityInSomeWay();
        entt::registry& myRegistry = getMyRegistryInSomeWay();
        t1->addCallbackFunc("thing_type2_cares_about"_hs, [myEntity, &myRegistry](void * data){
            Type2* t2 = myRegistry.try_get<Type2>(myEntity);
            if (t2 != nullptr) { t2->callbackFunc(data); }
        });
    }
```

However, this is awful and I strongly dislike it. It involves creating vast numbers of identical lambdas, each slightly different, in code all over the codebase. It's incredibly inefficient, highly coupled, and a pain to maintain.

Is there a good way, with EnTT, to implement this functionality? How do I store and call a member function of an EnTT-stored component in a way that's clean and efficient?

**Comment by sniggyfigbat** [comment]
Right. After quite a bit of searching, asking on [StackOverflow](https://stackoverflow.com/questions/64391313/how-can-i-bind-a-member-function-of-an-instance-whose-address-may-change/), etc, I've come to the conclusion that using a lambda to redirect calls to the correct function of the correct entity is the only viable option. Hopefully there's some way to build a templated lambda to do that, with C++20.

Will close the issue.
