### ISSUE TITLE
`entt::meta_sequence_container` insert documentation is incorrect

### ISSUE THREAD

**Issue by xissburg** [skypjack/entt#578]
At https://github.com/skypjack/entt/blame/master/docs/md/meta.md#L514
`handle` is private in `meta_sequence_container::meta_iterator`, so I assume the correct form would be simply `view.insert(view.end(), 42);`.

**Comment by skypjack** [comment]
It's `view.insert(last, 42)`. 👍 
Thanks for pointing this out. Upstream on `experimental`.
