### ISSUE TITLE
Question: About posibility of using Entt with runtime (script defined) components.

### ISSUE THREAD

**Issue by heretique** [skypjack/entt#581]
Hi, I'm working on a hobby game engine in my spare time and I have a use case that I believe should be pretty common. 
I would like to define new components in scripts but I want them to be defined in a way that makes use of the ECSs pros, keeping the components as only data and tightly packed in the memory and I wouldn't want to reinvent the wheel and implement an ECS just for this.
What I want to be able to do is to dynamically define components/structs by creating some sort of `DynamicComponentDefinition` class that takes a list of fields and types and "reinterprets" a given buffer like it would be a normal structure where I can access the fields by name. 
I've already implemented something like that with proper alignment and packing and it works pretty well on it's own. (Keep in mind this just reinterprets a buffer as a buffer of "dynamic structs" but it does not own it).
This seems at odds with Entt where the registry needs to know at compile time the structure and size of a component in order to create the associated component storage.
Even if my `DynamicComponentDefinition` definition would own the buffer I cannot know at compile time it's size and allocating the buffer for each component separately having a `uint8_t *buffer` member (instead of `uint8_t buffer[N]`) defeats the purpose of dense component storage that is cache friendly, each component only storing a pointer to the actual data which could be scattered in memory.
I hope this make sense for anyone reading this.
Is there a way to have this kind of runtime defined components with Entt?

**Comment by skypjack** [comment]
Correct me if I'm wrong, but if you don't know the size of the buffer at compile-time, all you can do is either dynamically allocat it or prepare pools for different sized buffers to use when needed (like, a pool for objects up to 50b, one for objects up to 100b, and so on). I don't see how you could that otherwise, so feel free to point me towards the solution you would use instead if I'm missing it.

**Comment by heretique** [comment]
The way I was considering implementing something like this is to have some sort of freelist allocator or in this case a packed freelist allocator, for the sake of simplicity something like this:
```
template <typename Entity>
struct ComponentStorage
{
    ComponentStorage(u32 typeSize, bool trivialConstruct, bool trivialCopyConstruct, bool trivialDestruct);

    bool hasComponent(Entity entity);
    u8* getComponentBuffer(Entity entity);

    std::vector<Entity> sparse;
    std::vector<Entity> dense;
    std::vector<u8> buffer;

    u32  typeSize : 29;
    bool construct : 1;
    bool copyConstruct : 1;
    bool destruct : 1;
};
```
and for each type of "dynamic" component I will have one of these `ComponentStorage` associated with it via a type id or some sort of hash.

Then I'd implement a "dynamic component definition" something like this:
```
class FieldDefinition
{
public:
    template <typename T>
    void get(u8* buffer, T& value) const;
    template <typename T>
    void set(u8* buffer, const T& value) const;

private:
    FieldDefinition(size_t offset, size_t alignment, size_t size);

    size_t offset;
    size_t alignment;
    size_t size;

    friend class DynamicComponentDefinition;
};

class DynamicComponentDefinition
{
public:
    DynamicComponentDefinition() {};

    template <typename T>
    void addField(FieldHash fieldHash);
    size_t pack();
    size_t size() const noexcept;
    size_t alignment() const noexcept;

    std::optional<FieldDefinition> getField(FieldHash fieldHash);

    template <typename T>
    void get(u8* buffer, FieldHash hash, T& value) const
    template <typename T>
    void set(u8* buffer, FieldHash hash, const T& value) const;
    u8* next(u8* buffer) const noexcept;

private:
    std::unordered_map<FieldHash, FieldDefinition> fields_;
    size_t size_{ 0 };
    size_t alignment_{ 0 };
};
```
And this will be used to "reinterpret" the buffer in the `ComponentStorage` as my "dynamic" component, that provides a way to retrieve fields based on their hash or name.
I could go as far as implement the whole ECS based on `ComponentStorage` and have the rest of the "native" components just be a [thin wrapper template](https://en.wikibooks.org/wiki/More_C%2B%2B_Idioms/Thin_Template) over it.
Now, I wouldn't want to implement this from scratch as Entt is already way better than I could ever make but given it's compile time nature, I'm not sure if it is possible to integrate this kind of feature/behavior.

**Comment by skypjack** [comment]
Got it. So, all you need is in fact a way to create multiple pools of the same type and to combine them in a view or view-like object, right?

**Comment by heretique** [comment]
Yes, I guess so, I think that might be enough, if I can create pools of the same type `ComponentStorage`, each of these holding buffers for different `DynamicComponentDefinition` "dynamic" components and a way to create views of combinations of them or combinations of native compile time components and "dynamic" ones, than I could easily use Entt with scripting languages and define my own components inside the scripting language and these will be cache friendly, more or less, same as the native ones.

**Comment by skypjack** [comment]
I assume you're using the last stable tag. In this case, all pools are associated with compile-time type. So, all you can do is to create a _bucket_ for runtime types and us it from your scripting env.
With the upcoming release instead, things should change quite a lot. It's not a problem for itself to create pool and to associate them to _runtime identifiers_. Though, the problem so far was  that of combining them with _standard views_. The `::view` function cannot really accept also these idenfiers and there was no way to _combine_ views.
This should be solved with something like this in the next release(s):
```
auto v1 = registry.view<foo, bar>();
auto v2 = registry.view(runtime_identifier);
for(auto entity: v1 | v2) { ... }
```
Could it work? OFc you don't have it upstram yet, so probably this doesn't answer the question. However, you've a use case, so probably you're a good candidate for asking a feedback. 🙂

**Comment by skypjack** [comment]
The ability to create your own storage, manage it externally, then use it to build a view to combine with other views in a pack is now on `master`.
I'm closing this issue because you should have everything you need to do what you ask. Feel free to continue the discussion here or reopen the issue if needed.

Thanks!

**Comment by heretique** [comment]
Sorry for late reply, somehow I missed the last two notifications on this issue. Thanks for adding this to the library , I'll check it out.

**Comment by xharris** [comment]
> ```
> auto v1 = registry.view<foo, bar>();
> auto v2 = registry.view(runtime_identifier);
> for(auto entity: v1 | v2) { ... }
> ```

I'm confused how this works. How is `runtime_identifier` created?

**Comment by skypjack** [comment]
It's up to the user in this case @xharris name hashing or any other generator.
