### ISSUE TITLE
Warning about converting an unsigned int to entt::entity

### ISSUE THREAD

**Issue by Grant12311** [skypjack/entt#582]
Hey. I just recently updated my entt submodule to the latest commit. Upon doing so, I was presented with the following new error. It seems to me as if my registry is now using unsigned short as its entity type? Please forgive me if I do anything wrong, this is my first time submitting an issue to any repository.

```
vendor/entt/src/entt/entity/registry.hpp|507|warning: conversion from ‘unsigned int’ to ‘entt::basic_registry<entt::entity>::version_type’ {aka ‘short unsigned int’} may change value [-Wconversion]|
```

My registry is declared like this
```cpp
entt::registry registry;
```

The error from the registry::destroy call is in the destructor of my Entity class. Here is a shortened version of the class.

hpp file
```cpp
class Entity
{
public:
    Entity(GJGO::Application* const a_appPtr);
    ~Entity();
    // Member functions here
private:
    entt::registry* m_registryPtr;
    entt::entity m_entity;
};
```
cpp file
```cpp
Entity::Entity(GJGO::Application* const a_appPtr) :
m_registryPtr(&a_appPtr->registry), m_entity(m_registryPtr->create()) {}

Entity::~Entity()
{
    this->m_registryPtr->destroy(this->m_entity);
}
```

**Comment by skypjack** [comment]
Hi, no worries and thank you for your (first) issue. 🙂 
I can't reproduce it though. Can I ask you the hash of the commit to start with?

**Comment by Grant12311** [comment]
Here is the submodule info

f3fc32660bfba47012f24bfbdcb034adae7e0b69 vendor/entt (v3.5.2-139-gf3fc3266)

**Comment by Grant12311** [comment]
My entire project is actually hosted on GitHub, so I can share the full source code with you. It builds using Premake5. The warning appears in both my IDE and make. Please forgive the lack of documentation, I wasn't intending for it to be public yet. The relevant code is in the Entity source and header files in the src and include directories respectively. examples/Game is my test application.

[https://github.com/Grant12311/GJGO-Engine](url)

**Comment by skypjack** [comment]
Sorry if I'm late. `version_type` is actually defined as `std::uint16_t` for the default entity type (that is `std::uint32_t`).
So, it's not an _unsigned short_ in all cases, because it's implementation defined. Probably you're hitting something I don't reproduce locally, because of _<reasons>_.

Is this the function that gives you the warning?
```
void destroy(const entity_type entity) {
    destroy(entity, version(entity) + 1u);
}
```
In this case, may I ask you to test this instead?
```
auto curr = version(entity);
destroy(entity, ++curr);
```
It should solve your problem, but it would be great if you could give me a feedback on this.

**Comment by Grant12311** [comment]
That fixed the problem, that you very much! I'd really appreciate it, though, if you could please explain to be in more detail why this fixes the issue, as I don't understand it at all.

**Comment by codylico** [comment]
_Outsider comment; feel free to ignore._

My guess is that adding `1u` to the `version(entity)` value activates an integer promotion from `std::uint16_t` (a.k.a. `unsigned short` in your case) to `unsigned int` (= uint32_t). This integral promotion would result from unsigned short being too "small" for the built-in `+` operator. The destroy function called here
```c++
    destroy(entity, version(entity) + 1u);
```
probably expects a 16 bit value. However, after the integer promotion, the `...+1u` value is now too "wide".

The `auto`-based code likely creates a `std::uint16_t`,as if by the following:
```c++
std::uint16_t curr = version(entity);
```
Pre-incrementing a `std::uint16_t` would return a reference to the now-modified `std::uint16_t` value, and so would stay 16 bits.

For more information, see the section on integral promotions in [Implicit conversions on cppreference.com](https://en.cppreference.com/w/cpp/language/implicit_conversion).

**Comment by skypjack** [comment]
@Grant12311 the last comment by @codylico answers your question pretty well. :+1:

**Comment by Grant12311** [comment]
Thank you both for your help :)

**Comment by Grant12311** [comment]
Thank you both for your help :)
