### ISSUE TITLE
Trim type name used for hashing and returned from entt::type_info<T>::name()

### ISSUE THREAD

**Issue by sunnlok** [skypjack/entt#586]
Right now the type name used for type hashing still contains some remnants from pretty function that could be trimmed of.

Example:

`struct Components::MyComponent`

becomes

`struct Components::MyComponent>(void) noexcept`

the noexcept bit is not necessary for the type name.

**Comment by skypjack** [comment]
I'm closing this as we discovered from a chat on Discord that the error was somewhere else and the `noexcept` token is already stripped out as expected. 👍 
Thanks for helping to investigate it down.
