### ISSUE TITLE
The managed type must be at least move constructible and assignable

### ISSUE THREAD

**Issue by sukoy** [skypjack/entt#594]
Hi,

The following code, cause the error "The managed type must be at least move constructible and assignable"

```
struct noncopyable {
         noncopyable() = default;
         noncopyable(noncopyable &&) = default;
         noncopyable(const noncopyable &) = delete;
         noncopyable & operator=(const noncopyable &) = delete;
         noncopyable & operator=(noncopyable &&) = default;
 
         const std::vector<std::unique_ptr<int>>& actions;
};
```

Maybe is it related to the same problem? https://github.com/skypjack/entt/issues/331#issuecomment-539924267

I'm on master @14e051f9

Thanks

**Comment by codylico** [comment]
```c++
const std::vector<std::unique_ptr<int>>& actions;
```
That may be your problem. If i remember correctly, references as class members don't assign well.

**Comment by skypjack** [comment]
A reference to a const vector of unique pointers. You did all what is possible to make a type non-moveable. 🙂 
Adding defaulted move ctor/operator doesn't help here. You can't really move an instance of your class into another instance, so this type doesn't satisfy the requirements.

As a side note, note that `EnTT` uses the `std::is_move_constructible_v` and `std::is_move_assignable_v` traits internally and triggers the error you reported if they return false.
You can easily make the same test on your types if in doubts. 👍

**Comment by sukoy** [comment]
> A reference to a const vector of unique pointers. You did all what is possible to make a type non-moveable. 🙂
Yes it was my intent :)

> 
> As a side note, note that `EnTT` uses the `std::is_move_constructible_v` and `std::is_move_assignable_v` traits internally and triggers the error you reported if they return false.
> You can easily make the same test on your types if in doubts. 👍

Yes I know they return both false, I did the test, but I'm quite sure this thread will help a lot of people :)

However @skypjack I want to say Thanks for this amazing library, bravo!

**Comment by skypjack** [comment]
As a side note, the constraints on the types are mentioned in the [documentation](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#vademecum):

> Components (the C of an ECS) must be both move constructible and move assignable.

I know that reading the documentation isn't always the first thing we do as developers, but here we enter the field of _RTM for the details_. 🙂 

> However @skypjack I want to say Thanks for this amazing library, bravo!

Thank you. More is coming too, there are a lot of new exciting feature that are about to enter `EnTT`.
In this sense, I've to thank the company I work with at the moment, which allows me to make public the changes to `EnTT` developed over time.

Do you think I can close the issue? I don't see any action to be taken for that at the moment, but I may be wrong.

**Comment by sukoy** [comment]
Yes is true sometime the documentation is boring :P, and sometime a small guideline, with few good practices and warnings is more efficient. However I'm quite sure google will rank this page and a lot of people will benefit of it.

Yes close, and I apologise If I wasted your time.

Thanks

Thanks

**Comment by skypjack** [comment]
There is never a waste of time exchanging ideas and feedback. Thank you for discussing it. 😉
