### ISSUE TITLE
feature request: emplace_or_patch

### ISSUE THREAD

**Issue by ywwg** [skypjack/entt#595]
I find myself often wanting to do an emplate_or_patch operation -- if an entity has the component, patch it as normal.  But if it doesn't exist, create one with initial values and then patch it with the function. "Initial values" could be defined as brace-or-equal initializers for structs:

`struct myComponent {
  int thingy = 10;
};`

Or a default constructor for classes.

**Comment by skypjack** [comment]
Hi, sorry for being late.
`get_or_emplace` was introduced for this kind of patterns. Wouldn't it work as well in your case?

**Comment by ywwg** [comment]
I often want to update a value in a component that may not exist, so I need to do a multi-step process:

`
int old_val = 0;
if (reg.has<Component>(ent)) {
  old_val = reg.get<Component>(ent);
}
reg.emplace_or_replace<Component>(ent, old_val + change_val);
`

it looks like I can use get_or_emplace I think?  I didn't see that before.

`
int old_val = reg.get_or_emplace<Component>(ent, 0);
reg.replace<Component>(ent, old_val + change);
`

If you think that's performant that would fulfill my use-case.

**Comment by skypjack** [comment]
That's definitely the way to go. Yeah.
It's also far easier to work with and to maintain than a `get_or_patch` from my point of view.

**Comment by skypjack** [comment]
I close this one as I suspect that the answer was satisfactory. 🙂 
Feel free to continue the discussion here if you've any other doubt. 👍
