### ISSUE TITLE
Error in Code Example

### ISSUE THREAD

**Issue by misnor** [skypjack/entt#6]
Hi!

I wanted to bring your attention to a potential issue in the Code Example in the README.

I am trying out entt and noticed I was getting a compilation error on the following loop:

```
for(auto entity: ecs.view<Position>().exclude<Velocity>()) 
{
    std::cout << (registry.has<Position>(entity)) << "/" << (registry.has<Velocity>(entity)) << std::endl;
}
```

Specifically, 'registry': undeclared indentifier.

Switching registry to ecs seems to make the example work as expected:

```
for (auto entity : ecs.view<Position>().exclude<Velocity>())
{
    std::cout << (ecs.has<Position>(entity)) << "/" << (ecs.has<Velocity>(entity)) << std::endl;
}
```

I only dabble in C++ so I didn't want to submit a PR for this fix in case I am missing something obvious.

**Comment by skypjack** [comment]
You are right, absolutely. That's a typo.
I use to call it `registry` in my code. I suspect I missed it while copying over to the README.
I'll fix it in a couple of hours (I'm not in front of my PC right now).

Thank you very much.

**Comment by skypjack** [comment]
Fixed. Thank you very much.
