### ISSUE TITLE
Emplace doesn't work properly on visual studio

### ISSUE THREAD

**Issue by Redman3global** [skypjack/entt#600]
I have a simple test code as follows:

    #include <iostream>
    #include "entt.hpp"

    struct Position {
	   float x;
	   float y;
    };

    int main() {

	    entt::registry world;

	    entt::entity entity = world.create();

	    world.emplace<Position>(entity, 0 ,0);

	    world.view<Position>().each([](Position& pos) {
		
		    std::cout << pos.x << " " << pos.y << std::endl;

	    });

	    std::cin.get();

	    return 0;
    }

"entt.hpp" is a single header. When i try to compile it using MinGW everything works fine (except millions of warnings). However when I try to compile the same file using visual studio it screams at me that "conversation from _Ty to float requires a narrowing conversation" and starts working only if I replace "world.emplace<Position>(entity, 0 ,0)" with "world.emplace<Position>(entity, Position(0 ,0))".
Am I doing something wrong, or is it a bug that needs a fix?

Sorry if this isn't how I'm supposed to report these kind of things, it is my first time doing it.

**Comment by Innokentiy-Alaytsev** [comment]
MSVC is for some reason stricter in this case. Use `world.emplace<Position>(entity, 0.0f ,0.0f);` syntax instead. Or any other syntax that has the correct type that is `float`.

**Comment by skypjack** [comment]
Indeed. `EnTT` constructs your instances internally as `T{args...}`. For some reasons, you get an error from MSVC because it considers this a narrow conversion, that isn't therefore accepted as expected. Though, the real issue is that you should use arguments of the _right_ types when constructing objects. The registry API is the last chance you have to pass in correct values and detect errors otherwise, so it prevents you from doing errors if possible.

**Comment by Redman3global** [comment]
> MSVC is for some reason stricter in this case. Use `world.emplace<Position>(entity, 0.0f ,0.0f);` syntax instead. Or any other syntax that has the correct type that is `float`.

My bad, I totally forgot that there's a difference between 0 and 0.0f. Should I take down the issue?

**Comment by skypjack** [comment]
Well, yeah, this is indeed invalid and we can close the issue.
There is nothing to do in `EnTT` to _make it work_ because it works as expected already. 🙂
