### ISSUE TITLE
No way to disable testing when built as CMake subproject via FetchContent

### ISSUE THREAD

**Issue by globberwops** [skypjack/entt#603]
### Issue
Build system is CMake.
EnTT is added as a subproject to a parent project using _FetchContent_.
The parent project has set `BUILD_TESTING=ON`.
There is now **no way to disable testing** in EnTT.

### Solution
Only add testing (and docs) when EnTT is not a subproject:
* by checking `if (CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)` after the call to `project()` or
* by checking `if (NOT DEFINED PROJECT_NAME)` before the call to `project()`

**Comment by Innokentiy-Alaytsev** [comment]
You have `ENTT_BUILD_TESTING` option for controlling building tests of EnTT. Set it before adding EnTT subdirectory.

**Comment by globberwops** [comment]
@Innokentiy-Alaytsev I see this was added since the last release, my bad. Thank you for pointing that out!

**Comment by Innokentiy-Alaytsev** [comment]
You're welcome)
