### ISSUE TITLE
Including CTest in the top-level CMakeLists.txt sets BUILD_TESTING=ON for parent projects

### ISSUE THREAD

**Issue by globberwops** [skypjack/entt#609]
#### What is the issue you have?
`BUILD_TESTING` is unset in the main project.
skypjack_entt is included in a main project using FetchContent.
`ENTT_BUILD_TESTING=OFF` is set in the main project.
skypjack_entt's top-level CMakeLists.txt includes CTest regardless.
`BUILD_TESTING=ON` is now set in the main project.

#### Please describe the steps to reproduce the issue.
```
message(STATUS "before BUILD_TESTING := ${BUILD_TESTING}") # prints ""
include(FetchContent)
FetchContent_Declare(
  skypjack_entt
  GIT_REPOSITORY https://github.com/skypjack/entt.git
  GIT_TAG master)
set(ENTT_BUILD_TESTING OFF)
FetchContent_MakeAvailable(skypjack_entt)
message(STATUS "after BUILD_TESTING := ${BUILD_TESTING}") # prints ON
```

#### What is the expected behavior?
CTest should only be included if skypjack_entt is the main project.

#### And what is the actual behavior instead?
CTest is included although skypjack_entt is added as subproject.

**Comment by skypjack** [comment]
Upstream. 👍 Thanks for pointing this out.

**Comment by globberwops** [comment]
@skypjack Thank you 👍🏻
