### ISSUE TITLE
Search by Component

### ISSUE THREAD

**Issue by Nostritius** [skypjack/entt#614]
I'm reimplementing a certain game, and try to map its logical system to entt. In this system, most objects (but not all) have a certain ID, which is used for example for accessing them through scripts. I realized this ID through an additional component, and now my question is what is the "standard" way of searching an entity by a component?

**Comment by Green-Sky** [comment]
This sounds very inefficient...
I would create a separate data-structure for GAME_ID -> ENTT_ID lookup, like a unordered_map.

**Comment by skypjack** [comment]
Searching an entity by a component or by a value of a data member in a component?
Because in the first case you can just use a `view`.

**Comment by Nostritius** [comment]
I'm searching for an component by value. View seems to work fine, thanks. Just out of interest, since I found entt::to_entity, which works on the component by reference, why is there no method like this which works by value?

**Comment by skypjack** [comment]
`to_entity` relies on pointer arithmetic, it dosen't iterate a view. You can't do the same if searching by value. That's all. 🙂

**Comment by skypjack** [comment]
I'm closing this issue because I assume it was answered.
Feel free to continue the discussion here if this isn't the case and eventually reopen the issue.
Thanks. 🙂
