### ISSUE TITLE
error C2332: 'struct': missing tag name

### ISSUE THREAD

**Issue by alexgeek** [skypjack/entt#615]
If include windows.h before any entt headers then I get:

```
C:\[...]\src\entt\poly\poly.hpp(180): error C2332: 'struct': missing tag name
  C:\[...]\src\entt\entity\../poly/poly.hpp(327): note: see reference to class template instantiation 'entt::poly<Concept>' being compiled
C:\[...]\src\entt\poly\poly.hpp(180): error C2059: syntax error: '='
C:\[...]\src\entt\poly\poly.hpp(292): error C2332: 'struct': missing tag name
C:\[...]\src\entt\poly\poly.hpp(297): error C2332: 'struct': missing tag name
```

If I add the following macro definitions before including windows then it resolves:

```
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#ifndef NOMINMAX
#define NOMINMAX
#endif
```

But adding any of the following headers causes it to break again:

```
#include <d3d12.h>
#include <dxgi1_4.h>
#include <D3DCompiler.h>
```

Anyone know what the conflict is? I can fix it at the moment by reordering headers but I thinking it will cause headaches down the line and the error messages I get aren't particularly helpful.

**Comment by codylico** [comment]
maybe there is an `interface` macro/keyword hiding in one of the Windows headers?

**Comment by skypjack** [comment]
Unfortunately it's due to some idiosyncrasies of the Windows headers. Defining `NOMINMAX` is a good approach for suppressing their macros.
Actually, `min` and `max` had been appropriately wrapped and they shouldn't be a problem.
I don't know what problems the other headers might introduce. Do they also conflict with `windows.h` rather than `EnTT`?

**Comment by alexgeek** [comment]
> maybe there is an `interface` macro/keyword hiding in one of the Windows headers?

Ah that's the ticket. combaseapi.h:169:

```
#define __STRUCT__ struct
#define interface __STRUCT__
```

The interface macro is used extensively (pretty much every D3D type):

```
typedef interface ID3D12Device ID3D12Device;
```

Not sure the cleanest approach to solving it though.

**Comment by skypjack** [comment]
Renaming `struct` is **REALLY** devilish.
No idea of what the cleanest approach is actually.

**Comment by alexgeek** [comment]
Renaming `interface` to `interface_type` or something similar would solve it but not sure if that's something you want to do.

```
    using interface = typename Concept::template type<poly_base<poly<Concept>>>;
```

```
    using interface_type = typename Concept::template type<poly_base<poly<Concept>>>;
```

COM is at fault here not EnTT but without that change using COM with EnTT will be difficult.

**Comment by skypjack** [comment]
Wait. Is this all that is needed? I've absolutely no problems at renaming `interface` if it's the only problem.
`poly` hasn't even entered any release yet, so really not an issue at all. In this case, I would rename it to `type` actually.
Can I ask you to test the change and confirm that everything just works as expected? Thanks.

**Comment by alexgeek** [comment]
`type` would conflict with the member function `type()`:

```
    [[nodiscard]] type_info type() const ENTT_NOEXCEPT {
        return storage.type();
    }
```

Renaming to `interface_type` works, just tested.

**Comment by skypjack** [comment]
Yeah, well, I honestly think it was a mistake to call that function `type`, since `type` is usually reserved for using declarations.
Since `poly` hasn't reached a release yet, I'll probably change both. The important thing is to know that just remove `interface` is enough to solve.
Thanks so much for your help and confirmation!

**Comment by Innokentiy-Alaytsev** [comment]
`interface` -> `facade`?

**Comment by skypjack** [comment]
`interface` -> `concept_type`, since the template parameter is called `Concept`. 🤷‍♂️
