### ISSUE TITLE
entt/3.5.2 error: constexpr variable 'value' must be initialized by a constant expression

### ISSUE THREAD

**Issue by blockspacer** [skypjack/entt#618]
entt/3.5.2

```cpp
entt/entity/../signal/../core/type_info.hpp:125:24: error: constexpr variable 'value' must be initialized by a constant expression
        constexpr auto value = internal::type_name<Type>();
```

```bash
/usr/bin/clang++ -v
clang version 6.0.1-svn334776-1~exp1~20190309042730.123 (branches/release_60)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.5.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
```

Binary used `set_property(TARGET ${target} PROPERTY CXX_STANDARD 17)` i.e. `-std=gnu++17`

```bash
/usr/bin/clang++  -isystem ~/.conan/data/entt/3.5.2/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/include -m64 -stdlib=libstdc++ -g -fPIC -std=gnu++17 -c main.cc
```

clang version 10.0.1 compiled same code without issues.

Ubuntu 18.04.2 LTS provides clang 6 by default.

Looks like widely used clang version (clang-6) do not support `constexpr auto value = internal::type_name<Type>();` syntax  https://clang.llvm.org/cxx_status.html. Can it be solved somehow (probably by rewriting that line of code in other way)?

**Comment by skypjack** [comment]
Have you tried it with current `master`? Something similar has already popped out a while ago as far as I remember.

**Comment by skypjack** [comment]
I've tested EnTT with clang 6.0.0 for _<reasons>_ and found only an issue with `std::launder` that isn't supported (fixed upstream on `experimental`, soon on `master`.
I assume the error you reported is solved and therefore I'm closing the issue. Feel free to reopen it if this isn't the case. Thanks.

**Comment by blockspacer** [comment]
I solved issue by using clang 10, because clang++-6.0 with -stdlib=libstdc++ had some other bugs ( https://stackoverflow.com/questions/46506387/getstring-for-variants-fail-under-clang-but-not-g )
