### ISSUE TITLE
registry::remove(ent) can accept 0 components which leads to 

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#623]
see 
```
 template<typename... Component>
    void remove(const entity_type entity) {
        ENTT_ASSERT(valid(entity));
        (assure<Component>()->remove(*this, entity), ...);
    }
```
I'd recomend a static assert that the Component type list is > 0
i noticed this when accidentally callig registry.remove(id) which resulted in nothing... when i meant to do registry.destory(id)

**Comment by skypjack** [comment]
Makes sense. Thanks for pointing this out.
