### ISSUE TITLE
Rename "ensure" to "assure"

### ISSUE THREAD

**Issue by mhaemmerle** [skypjack/entt#63]
I'm creating a new issue to track for the renaming of ensure/assure mentioned in #61 

> The last two things are related to Unreal Engine 4 in combination with EnTT:
> UE4 defines a macro named ensure and uses it in various places deep in the engine code, making it practically impossible to not have it included in some place of the user code (resulting in compiler errors). Do you see any chance of renaming ensure to something else? :)

> Put them in the TODO list. Is assure fine for UE4? Any other suggestion?

That sounds fine to me and I've also assured that there's also no macro defined with that name.

**Comment by skypjack** [comment]
`grant`, `guarantee`, `provide` are probably good candidates as well. What about? :-)

**Comment by UnoYakshi** [comment]
@skypjack, `grant` and `assure` take less time to type among others.

**Comment by mhaemmerle** [comment]
Yes, those are the macros.

Personally I think `assure` is closest in meaning of all of your examples. See dict [here](https://www.dict.cc/?s=assure).

**Comment by skypjack** [comment]
I like to use _laziness_ as a main reason!! @UnoYakshi :-D
`assure` seems to be the best choice then. I'll go for it. ;-)

**Comment by UnoYakshi** [comment]
It's about user-oriented mostly::).

**Comment by skypjack** [comment]
Upstream. See 472064b.
