### ISSUE TITLE
Performance when accessing component via view.get vs registry.get

### ISSUE THREAD

**Issue by Aardvarklord** [skypjack/entt#631]
If I know that always when an entity has component A it also has component B, is there any difference from a perfomance point of view between
```
auto view = registry.view<A, B>();
for (auto entity : view) {
	auto& A = view.get<A>(entity);
        auto& B = view.get<B>(entity);
        ...
}
```
vs
```
auto view = registry.view<A>();
for (auto entity : view) {
	auto& A = view.get<A>(entity);
        auto& B = registry.get<B>(entity);
        ...
}
```
Cheers

**Comment by skypjack** [comment]
This is such a common use case that I planned a dedicate custom pool for the next iteration (it's in the TODO list).

Until it's done, probably this is your best bet:
```
auto view = registry.view<A, B>();
for (auto [entity, a, b]: view.each()) {
    ...
}
```
Otherwise, you can use the `.each(F)` function:
```
view.each([](auto entity, auto &a, auto &b) { ... }
```

**Comment by Aardvarklord** [comment]
Ok, thanks!

The second alternative works fine, but for the first alternative Microsoft Visual Studio 2019 (compiling with C++17) gives these errors:

```
error C2672: 'entt::basic_view<Entity,entt::exclude_t<>,A,B>::each': no matching overloaded function found
error C2780: 'void entt::basic_view<Entity,entt::exclude_t<>,A,B>::each(Func) const': expects 1 arguments - 0 provided
```

**Comment by skypjack** [comment]
Mmm... because I missed a closing `)`? 🙂

**Comment by Aardvarklord** [comment]
I meant this gives the compilation errors:
 ```
auto view = registry.view<A, B>();    
for (auto [entity, a, b] : view.each()) {
        
}

```
Seems the compiler thinks the each method expects a Func object. I'm probably missing something trivial... not quite up to speed on the modern c++ language constructs :relaxed:

**Comment by skypjack** [comment]
Aha, that's because it's called `proxy` in v3.5.2, sorry.
