### ISSUE TITLE
change division to shifting

### ISSUE THREAD

**Issue by BossOfTheGym** [skypjack/entt#639]
https://github.com/skypjack/entt/blob/47ada87ba2fab08c70fdd61fa2835a27fb9ce8a7/src/entt/entity/sparse_set.hpp#L153

It seems that division can be changed to bit shifting. Page size is pow of 2 so...

return size_type{(to_integral(entt) & traits_type::entity_mask) / entt_per_page};
return size_type{(to_integral(entt) & traits_type::entity_mask) >> entt_per_page_log2};

**Comment by BossOfTheGym** [comment]
Oh sorry to disturb, most compilers seem to optimize it themselves :\

**Comment by skypjack** [comment]
Yeah, since `entt_per_page` is a compile-time value, I guess most compilers can do the right thing here. 🙂
