### ISSUE TITLE
[Docs] little error? in inline documentation in registry.hpp

### ISSUE THREAD

**Issue by Green-Sky** [skypjack/entt#640]
This sentience talks about it self as if it talks about another function:
```
     * @brief Assigns entities to an empty registry.
     *
     * This function is intended for use in conjunction with `raw` and
     * `assign`.<br/>
```
https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L457

**Comment by skypjack** [comment]
It feels important. 😄 Thanks for pointing this out.
