### ISSUE TITLE
Getting C2039 Error on compile 

### ISSUE THREAD

**Issue by roeeh111** [skypjack/entt#642]
I'm trying to compile the code snippet given in the main entt readme. But I keep having this error show up in multiple places.
I cant seem to find the root of the error as it looks like value is defined.
Currently running Visual Studio 2019 with c++17.

Here's the error: 

entt\entt.hpp(910,68): error C2039: 'value': is not a member of 'entt::type_seq<remove_cv<remove_reference<Type>::type>::type,void>'
1>        with
1>        [
1>            Type=Type::value_type
1>        ]

**Comment by skypjack** [comment]
Hi, the example from the README [works fine](https://godbolt.org/z/xG8Pbe) with the latest single include file, MSVC v19.
So, it must be something in your environment or in your snippet, but it's hard to tell you what.
Can you reproduce the error with the online tool? I can look into it in case and try to help.

**Comment by Innokentiy-Alaytsev** [comment]
Was the single include header updated?

**Comment by skypjack** [comment]
> Was the single include header updated?

[Yes, it is](https://github.com/skypjack/entt/commit/7a949dd32849e8230b15a5ff8ad1104c7f748c2a). 👍

**Comment by Innokentiy-Alaytsev** [comment]
Ok, It looks like the error comes from the single include header so I double checked)

**Comment by roeeh111** [comment]
The online tool does not reproduce the error, so it does seem like its an issue with my environment.

**Comment by Nigelev77** [comment]
This occurs not through the single include but using the src/entt.hpp file. That's probably what you were including

**Comment by roeeh111** [comment]
Error was on my side, Visual Studio was having issues. Its fixed and can build now.

**Comment by skypjack** [comment]
Nice to know. Thanks for reporting. :+1:

**Comment by MohammadMDSA** [comment]
@roeeh111 What was the issue? I have the same problem.

**Comment by roeeh111** [comment]
@MohammadMDSA I don't know exactly, but uninstalling and reinstalling visual studio fixed the problem.
