### ISSUE TITLE
What is the best way to deal with transforms in entity hierarchies?

### ISSUE THREAD

**Issue by RaskiTech** [skypjack/entt#643]
Hi,

I have been struggling with entity hierarchies recently. I made a relation component like you described in [this](https://skypjack.github.io/2019-06-25-ecs-baf-part-4/) post but now I don't know how to handle positions, rotations and scales with it.

What I want to do is find a good way get and set a world position for an entity, and have every objects 0 0 point be at the parents position. So basically just like how ecs usually handles this.

I have tried two things different approaches, but neither of them seem ideal.
You said in some comment that the transform component should store only the relative positions. This is good, but then when you need the world position, so at least every time it gets rendered, you need a recursive function like this:
```
void GetWorldPosition() {
    entt::entity parent = mRegistary.get<TransformComponent>(thisEntity);
    if (parent != entt::null)
        return mRegistary.get<TransformComponent>(parent).GetWorldPosition() + localPosition;
    else
        return localPosition;
}
```
There aren't usually too many children on top of each other, but this function doesn't still seem ideal.

I also tried to store the world position in the transform component, but the same problem occurs as you need to always update the children when you move the parent. This, however, needs to only happen when the position is updated.

Is there good solution to this or do I need to choose the best out of bad ones?

**Comment by Green-Sky** [comment]
You could take a look at [Unity3D and how they handle this problem](https://docs.unity3d.com/Packages/com.unity.entities@0.11/manual/transform_system.html).

while doing a quick google search i came across this breakdown https://gist.github.com/AThilenius/528b981accc2cc62de3deb49f5fff3ed

**Comment by skypjack** [comment]
Well, if you only store relative positions, probably you want to use a local/global pair of transform components for each entity and a dirty flag to reduce the amount of work when you update something.
What you suggest is similar, though without the _global_ part of the pair. 🙂 So, you literally calculate the same information over and over again from many different places. Right?

**Comment by RaskiTech** [comment]
Yea I think that sounds like the best answer. Thanks for the reply! :)

**Comment by skypjack** [comment]
You're welcome. 🙂 Let me know if you come up with something different too. I think other users may be interested. Thanks.

**Comment by RaskiTech** [comment]
For possible future readers, here is some of the code I came up. I modified it a little bit to make it less specific to my engine. 
Of course if anyone has any improvements to some parts of this code feel free to comment, since this is a very essential part when thinking about performance. :)

```
void TransformComponent::SetLocalPosition(const glm::vec3& position) {
    localPosition = position;
    SetWorldPosFlagsFalse(mRegistry.get<Relation>(thisEntity));
}
```
```
// Private function
void TransformComponent::SetWorldPosFlagsFalse(Relation& thisRel) {
    entt::entity child = thisRel.firstChild;
    worldPosRight = false;
    while (child != entt::null) {
        Relation& childRel = mRegistry.get<Relation>(child);
        TransformComponent& tr = mRegistry.get<TransformComponent>(child);
        tr.worldPosRight = false;
        tr.SetWorldPosFalse(childRel);
        child = childRel.nextSibling;
    }
}
```
```
const glm::vec3& TransformComponent::GetPosition() {
    if (worldPosRight)
        return worldPosition;

    entt::entity parent = mRegistry.get<Relation>(thisEntity).parent;
    worldPosRight = true;
    if (parent != entt::null)
        worldPosition = mRegistry.get<TransformComponent>(parent).GetPosition() + localPosition;
    else
        worldPosition = localPosition;

    return worldPosition;
}
```
```
void TransformComponent::SetPosition(const glm::vec3& position) {
    entt::entity parent = mRegistry.get<Relation>().parent;
    if (parent != entt::null) {
        const glm::vec3& parentWorldPosition = mRegistry.get<TransformComponent>(parent).GetPosition();
        localPosition = position - parentWorldPosition;
    }
    else localPosition = position;

    worldPosition = position;
    worldPosRight = true;
}
```

**Comment by RaskiTech** [comment]
I noticed some problem with this approach, as it doesn't handle rotation or scale very well.
For example, if you have a child above a parent and you tilt the parent 90° clockwise, you would expect the child to move to left of the parent. Now however they both just rotate around their centers.

I looked the links that @Green-Sky posted, and they seemed to solve the issue. Thanks for them! :) You probably also could solve this problem by just taking into account the rotation and scale of the parent when getting the world pos, but I assume it would be slower.

**Comment by skypjack** [comment]
How do they handle it without querying the parent?

**Comment by RaskiTech** [comment]
It seemed quite complex and I didn't look at it too much, as I just wanted to get it working today. Also my appologies, as I relized that I hinted that Unity wouldn't query the parent when i'm not entirely sure. However they seem to store some kind of 4x4 'localToParent' and 'localToWorld' matixies
