### ISSUE TITLE
Component using aligned type like Eigen::Matrix3d

### ISSUE THREAD

**Issue by pwm1234-sri** [skypjack/entt#645]
Hello! I am looking into using entt and want to know about storing an aligned type, like an Eigen::Matrix3d, as a component type in an entt::registry. I have seen multiple mentions that the only requirement for a component is that the type is movable. But eigen alignment issues have been a pain for me (outside of entt) for a while, so I just wanted to check and see about the consequences of using an aligned type as a component.

Thanks for making entt available!

**Comment by sunnlok** [comment]
AFAIK the master branch of eigen as well as the next version of it should support cpp17s aligned new which should solve this problem in general with containers.
Otherwise you would need to write a custom pool implementation for your eigen types.

**Comment by skypjack** [comment]
Indeed. The rule of thumb is: if it works in an `std::vector`, it works with the default pool of `EnTT`.
Otherwise, `EnTT` offers the possibility to design your own pool for all types or on a per-type and per-traits basis.
So, one way or the other, you should be able to get it work.

**Comment by pwm1234-sri** [comment]
Thank you - I appreciate your help!

**Comment by skypjack** [comment]
You're welcome. Let us know if you find anything interesting about this topic. It may help future users in case. Thanks. 🙂
