### ISSUE TITLE
Call for comments: single instance components (aka tags)

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#65]
So far, tags and components have no requirements and a type can be used both as a component and as a tag. 
This is also the reason for which their APIs are slightly different. As an example, to `assign` a tag we must use `attach` and to `replace` it we have to use `set`.
This approach could be error-prone, mainly because it happens that users use a tag as if it's a component or viceversa and the bugs that arise from this are quite subtle.

A possible solution would be to completely separate the two APIs. Sort of `assign` vs `assignTag`, `replace` vs `replaceTag` and so on.
However, this is still error-prone and internally it's hard to say sometimes if a type is a tag or a component for the registry. Something similar is true also for the clients.
Consider the following line:
```
auto type = registry.component<MyTag>();
```
It works and that's all. Put errors like this one all around a codebase and pretty annoying bugs are for free.

A more (let me say) _type-safe_ approach would be to force users to define tags as derived classes like this:
```
struct MyTag: SingleInstanceComponent<MyTag> {
    // ...
};
```
This way tags and components can share exactly the same API (`replace`, `assign` and so on, no exceptions). Sfinae will do the rest.
Moreover, the registry would know at all times what kind of object it is working with. It means compile-time errors if an user uses a tag as if it's a component or viceversa. It means more chances for optimizations. And so on.
Drawbacks? The _base class_ from which to inherit. I tried to avoid it so far for I'm not a fan of forcing users to do something. Anyway, single instance components probably is worth it.

Any comment? Could it be a viable solution?

**Comment by ArnCarveris** [comment]
@skypjack 
> The base class from which to inherit
Is possible to hide inheritance behind API?

**Comment by skypjack** [comment]
@ArnCarveris 

>Is possible to hide inheritance behind API?
Do you mean, sort of factory method or what?

**Comment by ArnCarveris** [comment]
@skypjack 
```
template <typename Tag> struct InternalTag: SingleInstanceComponent<Tag> {
    // ...
};
```

**Comment by ArnCarveris** [comment]
@skypjack 
> This way we cannot merge the two APIs anymore. Moreover, subtle bugs like registry.component<MyTag>() are still possible. Did I miss something?

So there is no way to avoid to `subclassing` `SingleInstanceComponent` at client side.

**Comment by skypjack** [comment]
Another way to _solve_ it that is half way between the two approaches comes directly from the standard library: tag dispatching.
We could add a dedicated tag type like this:
```
struct tag_type final {};
```
Then use it as a first parameter on `assign` and `replace` whenever a single instance component is involved.

This way we would have a common API and there is no need of inheritance.
Still partially error-prone, at least more than the solution based on inheritance.

What about?

**Comment by skypjack** [comment]
I'm tempted to introduce a class type to disambiguate overloads when required, as mentioned above.
I made some experiments and it seems a good compromise, even if a bit verbose. @morbo84 ? :-)

**Comment by skypjack** [comment]
That's it. Tag dispatching.
Let's close this issue.
