### ISSUE TITLE
A way to avoid any/meta_any aliasing.

### ISSUE THREAD

**Issue by alexander-v** [skypjack/entt#652]
Example:
```
int a = 0;
entt::any any(std::ref(a));
entt::any any_copy = any;
```
In this example, both `any` and `any_copy` hold a reference to `int`. But there are cases when a real copy is needed.
It would be great to have an explicit method to avoid aliasing.

**Comment by skypjack** [comment]
Maybe a copy operation should just trigger a copy, even in case of references? This would be the cleanest solution.
There is no actual reason to do otherwise and the current behavior also is semantically wrong probably.

**Comment by alexander-v** [comment]
I totally agree with you. I spent probably an hour debugging because I expected a copy to contain an actual copy.

**Comment by skypjack** [comment]
Available on `experimental`, about to merge it into `master`.
