### ISSUE TITLE
Remove all components, except...

### ISSUE THREAD

**Issue by GavinNL** [skypjack/entt#653]
Hi 

Is there currently a way to remove all components from an entity except for the ones listed? If not, is it possible to get this feature?

I need a way to ensure that one of my components is always the last one to be removed when I call my custom destroy function. 

Something like this:
```cpp
registry.remove_all_except<Comp1>(e); // removes all components except Comp1

registry.destroy(e); // Comp1 is destroyed here since its the only one left
```

**Comment by codylico** [comment]
_outsider comment; feel free to ignore_

A potential idea, is to use two-phase destruction.
- Phase 1: destroy all components except...; then set a "last to destroy" tag.
- Phase 2: destroy the except, with the "last to destroy" tag.

**Comment by skypjack** [comment]
There isn't an explicit way to do that, even though you can achieve the same result with other functionalities. Out of my mind, something like this should work (not tested, probably it contains some errors, but still):
```
rgistry.visit([&](auto storage) {
    if(storage.type() != entt::type_id<T>()) {
        storage.remove(registry, entity);
    }
}, entity);

registry.destroy(entity);
```
Can I ask you why do you have this requirement? Maybe there exists another way for you to solve your problem that doesn't require to delay the destruction of a component.

**Comment by GavinNL** [comment]
I have a component that handles hierarchy information such as parents/children as well as a few other things. So I always want that to be removed last since other components might want to query parents/children when they get destroyed. 

I couldn't get your example code working, this is what I have so far. 

```cpp
    R.visit(e, [&](auto idt)
    {
        if( idt == entt::type_id<CHeader>())
        {
            // do nothing
        }
        else
        {
            // how do I get T ?? No way to delete based on id_type ??
            // R.remove<T>(e);
        }
    });
```

Is there a way to remove a component based on its type_id rather than by template parameter? Perhaps something like this?
```
R.remove(e, entt::id_type<Comp>() );
```

**Comment by skypjack** [comment]
It more like [this](https://godbolt.org/z/xWKdE5). I'm actually polishing the API of the poly storage, mainly to remove the registry argument, but still.
The method is used to delete one or more entities, so it expects an array of them (a couple of iterators actually).

**Comment by GavinNL** [comment]
Thanks! The code you gave works for what I need. You can close this issue if you like :)


I'm using the hierarchy of entities to create a compound collision shape based on the collision shapes of all the entities in the tree.
Each child entity has a collision shape (eg sphere), and when the `CCollisionShape` gets destroyed for a child shape, it needs to indicate to the parent that the shape has changed so it's parent rebuild the compound shape, but if the `CHeader` component is destroyed first, the on_destroy( ) callback for `CCollisionShape` will be unable to determine who the parent is.

Here's the stripped down code of of what i'm doing. 
```cpp
void PhysicsSystem::on_destroyCollisionShape(registry & r, entity e)
{
    auto parentEntity = r.get<CHeader>(e).parent;
   if( parentEntity != entt::null)
   {   
     scheduleRebuildCollisionShape(parentEntity);
   }

}
```

I'm sure there's probably a better way of designing this, but I don't want to get into a huge discussion about engine design :P

Thanks for the assist!

**Comment by skypjack** [comment]
> I'm sure there's probably a better way of designing this, but I don't want to get into a huge discussion about engine design

Oh, no, don't worry, just curious. Thanks for explaining. 👍 🙂
