### ISSUE TITLE
Call for comments: "singleton mode" for tags

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#66]
Well, ok, I didn't find a better name than _singleton mode_.
All the details are in [the last comment](https://github.com/skypjack/entt/issues/62#issuecomment-379847327) of #62. I'm creating this issue to _discuss them_ and to try to understand if it's one of the _most wanted_ feature.
I'm also adding a note in the TODO list, mainly because I'm working on some other features at the moment.

Let's try to find the best way to define it in the meantime.

**Comment by ArnCarveris** [comment]
@skypjack sounds like [subsystem](https://github.com/urho3d/Urho3D/blob/21b1c48da0f3144110b3451a0a10bc5467e9d307/Source/Urho3D/Core/Context.h#L273)

**Comment by skypjack** [comment]
@ArnCarveris 

I must admit that I don't know what's a subsystem in Urho3D.  
Can you elaborate a bit further on them, please? Thank you.

**Comment by ArnCarveris** [comment]
@skypjack well subsystem same as system in ECS there some subsystems usages in [ Urho3D](https://github.com/urho3d/Urho3D/blob/030877647efdc1788f04e06d1e898b458ba60793/Source/Samples/03_Sprites/Sprites.cpp#L64) and [gentlemanly_engine](https://github.com/gentlemans/gentlemanly_engine/blob/6993d143b905c7758531af929e3210b4e66df372/samples/tutorial01/main.cpp#L13)

**Comment by skypjack** [comment]
Time to close this issue. It seems not a much desired feature.
I put a note in the TODO list so as to work on this sooner or later.
Thank you all for participating.
