### ISSUE TITLE
Requesting an update in the Wiki page: EnTT in Action

### ISSUE THREAD

**Issue by FahimFuad** [skypjack/entt#669]
I am developing [Spike](https://github.com/FahimFuad/Spike), which is a game engine which can run on a toaster. It uses EnTT for ECS. Can I get the engine in *Engines and the like* list on the *EnTT in Action* wiki page? 😊
If yes, here is the mark-down ⬇️ 
[Spike](https://github.com/FahimFuad/Spike): A powerful game engine which can run on a toaster

**Comment by skypjack** [comment]
Updated. Thanks. 🙂
