### ISSUE TITLE
check storage alignment for entt::any

### ISSUE THREAD

**Issue by Bigpet** [skypjack/entt#676]
There's currently an issue with storing over-aligned types in_situ with std::any.
The practical example was `glm::vec3` with intrinsics enabled. It has `alignof(glm::vec3) == 16` and its copy-constructor generated with optimizations in gcc was a single `movqda`.

Regardless of changes to add an optional alignment requirements to the std::any storage, the in-situ check should take alignment into consideration.

i.e. something like 
```C++
static constexpr bool in_situ = Len && alignof(Type) <=  alignof(storage_type) && sizeof(Type) <= sizeof(storage_type) && std::is_nothrow_move_constructible_v<Type>;
```

instead of just
https://github.com/skypjack/entt/blob/6d3857f33700b1ed8bd34e254bd567f86a10171a/src/entt/core/any.hpp#L31

That should be enough for power-of-two alignments. I don't know if npot alignments are a thing, but I think I'd rather throw a static assert in that case instead of supporting that.

**Comment by skypjack** [comment]
> the in-situ check should take alignment into consideration.

Wouldn't this force dynamic allocations in though? This way we get proper alignment but we cannot rely on the in-situ storage, that is instead a nice-to-have feature for optimizations.

**Comment by Bigpet** [comment]
Yes it would. But I just thought I'd primarily address correctness concerns in the issue.

When I typed "Regardless of changes to add an optional alignment requirements to the std::any storage" I meant what you said in the gitter chat. Adding an additional `align` non-type template parameter to `basic_any` would allow users to store over-aligned types in `entt::any` if they configure it properly. (at the expense of additional memory required to keep alignment)

**Comment by skypjack** [comment]
I think that (but I'm open to feedback, since I'm not that used to this kind of things) the latter is probably the right thing to do. That is, to mimic `std::aligned_storage` rather than to try to _intercept_ over-aligned types.
As for getting around the in-situ storage, you can already do this: `using over_aligned_any = entt::basic_any<0u>`. It forces dynamic allocations in all cases.

**Comment by Innokentiy-Alaytsev** [comment]
Another (uglier) option is making SBO aligned at 16. With the default size, it will work quite nicely.

**Comment by Bigpet** [comment]
> Another (uglier) option is making SBO aligned at 16. With the default size, it will work quite nicely.

Yes that's what I did to hot-fix it locally. But not the best general solution.

> the latter is probably the right thing to do

Both is the only reasonable answer in my opinion. The first thing (consider alignment with in_situ check) addresses correctness concerns. 

The second one (let users control default alignment) allows users to trade off memory to store over-aligned types in situ as well.

Just doing the second one will still allow people to run into bugs.

**Comment by skypjack** [comment]
Is it possible to have a small reproducible test that doesn't require to include `glm`?
I'd like to include it to the testsuite in order to avoid regressions in future.

**Comment by Bigpet** [comment]
Or I guess it's better to just check successive elements. 
So it doesn't fail the static assert on working implementations, but does fail on broken implementations 100% of the time

```C++
#include <type_traits>
#include <cassert>

#include <entt/entt.hpp>

constexpr size_t overalignment = 64;

using any_type = entt::basic_any<overalignment>;

struct alignas(overalignment) overAligned {
    overAligned(){assert((uintptr_t)this%overalignment == 0);}
    overAligned(const overAligned& ) noexcept {assert((uintptr_t)this%overalignment == 0);}
    overAligned(overAligned&& ) noexcept {assert((uintptr_t)this%overalignment == 0);}
};

int main(int argc, char** argv) {
    any_type target[2];
    target[0] = overAligned{};
    target[1] = overAligned{};
    return 0;
}
```

**Comment by skypjack** [comment]
Isn't this enough too to reproduce the error?
```
struct alignas(64u) over_aligned {};
entt::basic_any<alignof(over_aligned)> instance{over_aligned{}};
ASSERT_TRUE((reinterpret_cast<std::uintptr_t>(entt::any_cast<over_aligned>(&instance)) % 64u) == 0u);
```

**Comment by Bigpet** [comment]
> Isn't this enough too to reproduce the error?
> 

In most cases it probably is. The issue is just when there's a single allocation then it might just by chance (or with different compile flags) fall on the right alignment. So testing 2 contiguously stored objects should make it fail more reliably than just one instance.

**Comment by Bigpet** [comment]
@skypjack  as for the implementation of the alignment. Wouldn't something like 

```
// std::min(Len,alignof(double[2])) might not be constexpr in all implementations
template<std::size_t Len, std::size_t Align = (Len<=alignof(double[2])?Len : alignof(double[2]))>
class basic_any {

```
be preferable to the version. Because it makes the default value more explicit and makes it clear that is is only one value
```
template<std::size_t Len, std::size_t... Align>
class basic_any {
```

**Comment by skypjack** [comment]
Mmm... you're not wrong, though I'm _scared_ (or _tempted_, it depends on the point of view) by the implementation-defined nature of the `Align` parameter of `std::aligned_storage` that may also support extended alignment and the like. I'd prefer to keep the built-in value when an user defined one isn't available.

**Comment by Bigpet** [comment]
@skypjack  that's a valid concern, maybe `template<std::size_t Len, std::size_t Align = alignof(aligned_storage<Len + !Len>::type)>` would be a possibility

**Comment by skypjack** [comment]
🤔 this makes sense actually.
