### ISSUE TITLE
component added event

### ISSUE THREAD

**Issue by BPopcorn** [skypjack/entt#68]
Hi, thanks for this great library. It is exactly what I was looking for! I have a small problem right now. I don't know if this is the right place to ask questions but I was wondering if there's a way to detect when a specific component is added to an entity. I would like to use z-ordering, but only sort the components when a new component was added. Is there an internal event I can subscribe to?

**Comment by skypjack** [comment]
Hi @BPopcorn 

I'm glad you like `EnTT` and you plan to use it. Really appreciated.
In this case, do not forget to star the project. It helps to spread it more and more.

Events on creation/destruction for components and tags is an upcoming feature. It's already available on branch `experimental`.  
The stuff on that branch should be considered under development and I cannot guarantee it remains the same until it is merged on `master`. That being said, feel free to use it. Actually I'm already using the same branch in a project of mine. Moreover, early adopters can give me useful feedbacks before to create a stable release!!

Let me know if it works fine for you.

**Comment by BPopcorn** [comment]
Thanks for the fast reply. Great to hear that such a feature is being worked on. I'll have a look at the experimental branch when I get more fluent with the library.

**Comment by skypjack** [comment]
Sure. Do not hesitate to ping me if you need help! ;-)

**Comment by ArnCarveris** [comment]
@skypjack Hi, can you add signal on component pool creation `void(Registry<Entity> &, std::size_t/*pool_idx*/)`?

**Comment by skypjack** [comment]
@ArnCarveris Actually the idea is to make `EnTT` allocator-aware. If your intention is to keep track of memory usage, it's easier to use a dedicated allocator designed for debug purposes.

**Comment by ArnCarveris** [comment]
@skypjack 
> Actually the idea is to make EnTT allocator-aware. If your intention is to keep track of memory usage, it's easier to use a dedicated allocator designed for debug purposes.

I'm trying solve other problem, I need catch moment right after pool was [created at once](https://github.com/skypjack/entt/blob/8ef4cdc9c3196396460dfe42c4d2c85c6ecdd0fa/src/entt/entity/registry.hpp#L96)
afterwards I'll associate some component template function with component pool index, it should help implement some kind of component-auto-factory, inspectors and other external user defined tools.

**Comment by ArnCarveris** [comment]
@skypjack 
> Just attach your listener before to start the loop.

Can I safely remove listener inside attached listener during invocation? Events trigger only once.

**Comment by ArnCarveris** [comment]
@skypjack 
>Theoretically it's possible. Instead of a for_each we can use an indexed for that uses operator[] on the internal vector of listeners.

Error-prone, better create different signal for it,
