### ISSUE TITLE
Convenience API for working with singleton components

### ISSUE THREAD

**Issue by albin-johansson** [skypjack/entt#682]
I've been using EnTT for some time, and I've thoroughly enjoyed it! I can honestly say this is one of the best libraries I've ever used. However, during this time I noticed some room for a simple convenience function for obtaining "singleton" components, so I thought I'd propose the idea here and see what you think. 

## Rationale

When working in an ECS environment, it's relatively common pattern to have "singleton" components, i.e. components that there only exists a single instance of in a registry. For example, this could be a `settings` or `binds` component, or some other "blob" component that lives in the registry, because we want as much data as possible in our registries. However, there is currently no terse way of obtaining these kinds of components from a `registry` instance.

## Proposal 

Extend the API of `basic_registry` with a new `singleton` function, that returns a reference to the only component of the specified type. In debug builds, assert that there really only exists one instance of the component, and let the function result in undefined behaviour if it has zero or more than one instances of said component.

```C++
// Current syntax
void foo(entt::registry& registry)
{
  const auto view = registry.view<bar>();
  assert(view.size() == 1);
  auto& bar = view.front();

  // Use bar...
}

// Proposed syntax
void foo(entt::registry& registry) 
{
  auto& bar = registry.singleton<bar>();

   // Use bar...
}
```

## Possible implementation

The implementation is not very complicated and requires no new logic, since it is only a convenience function. The idea is to add the following functions to `basic_registry`.

```C++
template <typename Component>
[[nodiscard]] decltype(auto) singleton()
{
  const auto v = view<Component>();
  ENTT_ASSERT(v.size() == 1);
  return v.front();
}

template <typename Component>
[[nodiscard]] decltype(auto) singleton() const
{
  const auto v = view<Component>();
  ENTT_ASSERT(v.size() == 1);
  return v.front();
}
```

**Comment by Innokentiy-Alaytsev** [comment]
How is it better than context variables?

**Comment by albin-johansson** [comment]
To be honest, I missed context variable interface, but they do indeed seem very similar to this. If their use case is the same as this, then this is of course not needed.

**Comment by skypjack** [comment]
The upcoming version also _extends_ the support to context variables with a (imho) nice-to-have feature.
Briefly, you can attach to a registry a variable that is a reference to something that you manage externaly and you can also make it read-only.
Imagine for example a time object that is created, updated and destroyed within your loop and that you want to make available to user as a read-only variable, to avoid them to update it by mistake.
