### ISSUE TITLE
SHA mismatch error when installing entt via homebrew

### ISSUE THREAD

**Issue by ChristianIvicevic** [skypjack/entt#683]
I just tried installing entt via homebrew and got this error message:
```
==> Installing entt from skypjack/entt
==> Downloading https://github.com/skypjack/entt/archive/refs/tags/v3.6.0.tar.gz
==> Downloading from https://codeload.github.com/skypjack/entt/tar.gz/refs/tags/v3.6.0
##=#=-#
Error: SHA256 mismatch
Expected: 02890a14d40b117d4854620c9bb6c95e530828449dcb66299f31082e9ff8fa96
  Actual: 94b7dc874acd0961cfc28cf6b0342eeb0b7c58250ddde8bdc6c101e84b74c190
    File: /Users/near/Library/Caches/Homebrew/downloads/739fd35ea11af408129df3826997c6d107746cecadbd7e2470f3231db0d2ea65--entt-3.6.0.tar.gz
```
In the meantime I will try to setup the installation via cmake FetchContent.

**Comment by skypjack** [comment]
Honestly, I don't use homebrew and I've literally no idea of why it may be broken. 🙂
At a first glance, the repo seems correctly updated. Maybe @Kerndog73 ?

**Comment by Kerndog73** [comment]
I seem to have v3.6.0 installed already so I guess I haven't run into this. I tried manually downloading and hashing the archive and I got `94b7dc87`. There should have been an error but wasn't. I tried reinstalling entt and got the same SHA256 mismatch error. It seems like the hash in the `entt.rb` file is wrong. Maybe the GitHub actions script is running too soon after the release is created? The script doesn't check the exit code of `curl`. Although if there was an error, the `archive.tar.gz` might not be created so `openssl` would fail.

I went back a few versions and checked the hashes. All the hashes that GitHub actions has calculated are wrong. v3.3.2 is correct but all subsequent versions are wrong. What's really shocking is that Homebrew doesn't seem to check the hashes when upgrading, only when installing. That's probably what caused this to go under the radar.

Maybe all that's required is `sleep`ing for a few minutes? If that's not it then I'm not sure.

**Comment by skypjack** [comment]
I strongly suspect that the problem may be that I was creating release drafts that were published automatically with the tag.
I'm not doing it anymore (I'm using discussions to keep everybody up-to-date with all changes). So, let's see what happens with the next release before doing anything else. 👍

**Comment by skypjack** [comment]
I've just cut a new release. Can I ask you guys to check if this time homebrew was correctly updated?

**Comment by Kerndog73** [comment]
Whatever you did seems to have fixed it. Nice!

**Comment by skypjack** [comment]
Great. Thanks for checking!! ❤️ 🙂
