### ISSUE TITLE
Aggregate initialization for `entt::basic_any`

### ISSUE THREAD

**Issue by TerensTare** [skypjack/entt#687]
`entt::basic_any` cannot correctly initialize aggregates, as discussed on https://discord.com/channels/707607951396962417/707607952592470058/828189412486807582
A simple and working fix is adding `if constexpr` check for aggregates as follows so that those are initialized correctly. 
```cpp
    template<typename Type, typename... Args>
    explicit basic_any(std::in_place_type_t<Type>, [[maybe_unused]] Args &&... args)
        : instance{},
          vtable{&basic_vtable<Type>}
    {
        if constexpr(!std::is_void_v<Type>) {
            if constexpr(std::is_lvalue_reference_v<Type>) {
                static_assert(sizeof...(Args) == 1u && (std::is_lvalue_reference_v<Args> && ...), "Invalid arguments");
                instance = (std::addressof(args), ...);
            } else if constexpr(in_situ<Type>) {
                if constexpr (std::is_aggregate_v<Type>) // notice the check here
                    new (&storage) Type{std::forward<Args>(args)...};
                else
                    new (&storage) Type(std::forward<Args>(args)...);
            } else {
                if constexpr (std::is_aggregate_v<Type>) // and here
                    instance = new Type{std::forward<Args>(args)...};
                else
                    instance = new Type(std::forward<Args>(args)...);
            }
        }
    }
```

**Comment by hls333555** [comment]
Thank you for your fix!
However, I have come across another issue after applying this fix:
`error C2440: 'initializing': cannot convert from 'const char [10]' to 'char'`
Here's the error code line:
```cpp
.prop(PropertyType::Name, "TestEnum1"); // PropertyType::Name is a enum, I have omitted the type registration code
```

**Comment by TerensTare** [comment]
Apparently `std::is_aggregate<T>` applies `std::remove_all_extents<T>` before checking. I don't want to complicate things, but can you please check if this fix works? Thank you
```cpp
    template<typename Type, typename... Args>
    explicit basic_any(std::in_place_type_t<Type>, [[maybe_unused]] Args &&... args)
        : instance{},
          vtable{&basic_vtable<Type>}
    {
        if constexpr(!std::is_void_v<Type>) {
            using raw_type = std::remove_pointer_t<std::remove_extent_t<Type>>;
            if constexpr(std::is_lvalue_reference_v<Type>) {
                static_assert(sizeof...(Args) == 1u && (std::is_lvalue_reference_v<Args> && ...), "Invalid arguments");
                instance = (std::addressof(args), ...);
            } else if constexpr(in_situ<Type>) {
                if constexpr (std::is_aggregate_v<Type> && !std::is_fundamental_v<raw_type>) // notice the second check here
                    new (&storage) Type{std::forward<Args>(args)...};
                else
                    new (&storage) Type(std::forward<Args>(args)...);
            } else {
                if constexpr (std::is_aggregate_v<Type> && !std::is_fundamental_v<raw_type>) // and here
                    instance = new Type{std::forward<Args>(args)...};
                else
                    instance = new Type(std::forward<Args>(args)...);
            }
        }
    }
```

**Comment by hls333555** [comment]
> Apparently `std::is_aggregate<T>` applies `std::remove_all_extents<T>` before checking. I don't want to complicate things, but can you please check if this fix works? Thank you
> 
> ```c++
>     template<typename Type, typename... Args>
>     explicit basic_any(std::in_place_type_t<Type>, [[maybe_unused]] Args &&... args)
>         : instance{},
>           vtable{&basic_vtable<Type>}
>     {
>         if constexpr(!std::is_void_v<Type>) {
>             using raw_type = std::remove_pointer_t<std::remove_extent_t<Type>>;
>             if constexpr(std::is_lvalue_reference_v<Type>) {
>                 static_assert(sizeof...(Args) == 1u && (std::is_lvalue_reference_v<Args> && ...), "Invalid arguments");
>                 instance = (std::addressof(args), ...);
>             } else if constexpr(in_situ<Type>) {
>                 if constexpr (std::is_aggregate_v<Type> && !std::is_fundamental_v<raw_type>) // notice the second check here
>                     new (&storage) Type{std::forward<Args>(args)...};
>                 else
>                     new (&storage) Type(std::forward<Args>(args)...);
>             } else {
>                 if constexpr (std::is_aggregate_v<Type> && !std::is_fundamental_v<raw_type>) // and here
>                     instance = new Type{std::forward<Args>(args)...};
>                 else
>                     instance = new Type(std::forward<Args>(args)...);
>             }
>         }
>     }
> ```

Sadly, with this second check, the old error occurs again: `an array cannot be initialized with a parenthesized initializer`.

**Comment by TerensTare** [comment]
I tried to reproduce an example on [godbolt](https://godbolt.org/z/cd9TEEGhf), and I think I made it work now😅. Can you confirm it? If not, can you please modify the example to a more complete example and share it here? Thank you once again.

**Comment by hls333555** [comment]
> I tried to reproduce an example on [godbolt](https://godbolt.org/z/cd9TEEGhf), and I think I made it work now😅. Can you confirm it? If not, can you please modify the example to a more complete example and share it here? Thank you once again.

You can reproduce it using this code:
`entt::meta<int>().type().prop("tooltip"_hs, "message");`

**Comment by TerensTare** [comment]
The error happens to me on the latest (non preview) MSVC even with the non-modified EnTT. I'm not a `entt::meta` expert, but aren't you supposed to write `"message"_hs`?

**Comment by hls333555** [comment]
> The error happens to me on the latest (non preview) MSVC even with the non-modified EnTT. I'm not a `entt::meta` expert, but aren't you supposed to write `"message"_hs`?

No, I just want const char*...
At least, the documentation says it is supported
https://github.com/skypjack/entt/wiki/Crash-Course:-runtime-reflection-system#properties-and-meta-objects

**Comment by skypjack** [comment]
@hls333555 is it possible to have a minimal, reproducible example to speed up the investigation? If you've already something that works (well, that doesn't actually), probably it's easy for you to setup something?
The online compiler is fine for that, I don't need a full project ofc!

**Comment by hls333555** [comment]
> @hls333555 is it possible to have a minimal, reproducible example to speed up the investigation? If you've something that works already (well, that doesn't actually), probably it's easy for you to setup a repro?
> The online compiler is fine for that, I don't need a full project ofc!

https://godbolt.org/z/nMhM8Gov3

**Comment by skypjack** [comment]
Oh... Dunno why but I was convinced it was a little more complex than this!
Thanks.

**Comment by hls333555** [comment]
> Oh... Dunno why but I was convinced it was a little more complex than this!
> I'm from mobile and didn't realize the problem is reducible with a call to `prop`, sorry.
> Thanks.

Thanks for the fix!
Could you please merge this fix into single_include file?

**Comment by skypjack** [comment]
I will do as soon as it gets ready. 👍 I'm still modifying the class for some refinements.
