### ISSUE TITLE
What happened to entt::registry.has?

### ISSUE THREAD

**Issue by hazeled** [skypjack/entt#691]
I used to be able to use registry.has, and it is still present in the single include. However, in the most updated version of entt, no such function exists. I can't seem to find an alternative, does anyone know what it is?

**Comment by Green-Sky** [comment]
It has been renamed to `all_of`.

@skypjack I told you to deprecate it first! :'D

**Comment by hazeled** [comment]
Ah, thank you! I searched first but totally missed that, whoops. Appreciate the help!

**Comment by skypjack** [comment]
> @skypjack I told you to deprecate it first! :'D

So true @Green-Sky thanks for answering!
