### ISSUE TITLE
Clang: C++ requires a type specifier for all declarations

### ISSUE THREAD

**Issue by devsammi3** [skypjack/entt#692]
On line 155 of entt.hpp, clang throws the error: C++ requires a type specifier for all declarations. This is to do with the template defined as:

template<class... Func>
overloaded(Func...) -> overloaded<Func...>;

I'm using clangd which is the clang lsp server that comes with llvm.

**Comment by skypjack** [comment]
It's a delegation guide. This is perfectly C++17 code. Are you compiling with the right flags?

**Comment by devsammi3** [comment]
I have -std=c++17 set up, is there anything else I need to check for clang?

**Comment by skypjack** [comment]
Actually no, this is enough. You can take a look at the testsuite. It runs on CI with clang too, that is why I'm pretty sure it runs smoothly.
What version of clang are you using?

**Comment by devsammi3** [comment]
It was my fault. My build scripts for clang had a typo where -std=c+17 (I think you can see the issue). Thank you!
