### ISSUE TITLE
Entity copy

### ISSUE THREAD

**Issue by andrew-r-king** [skypjack/entt#694]
I'm trying to figure out how to copy an entity and its components, and came across this snippet in the docs:

```cpp
registry.visit(entity, [&](const auto info) {
    auto storage = registry.storage(info);
    storage->emplace(registry, other, storage->get(entity));
});
```

It seems this is broken right now. I tried v3.7.1, master, and experimental. In master/experimental, emplace is a member of storage, but doesn't exist at all in 3.7.1. `storage->get(entity)` doesn't exist in all three. Hopefully I'm just misunderstanding something though.

```cpp
registry.visit(entity, [&](const auto info) {
    entt::poly<entt::Storage<entt::entity>>& storage = registry.storage(info);
    storage.emplace(registry, other, storage->get(entity));
});
```

As a nice to have, I was thinking a simple copy/clone abstraction method would be better anyway. Something like so:
```cpp
entt::registry registry;
entt::registry otherRegistry;

entt::entity entity = registry.create();
// numerous components are added to entity 

entt::entity other = registry.copy(entity);
// or from one registry to another
entt::entity other = otherRegistry.copy(entity, registry);
```

**Comment by skypjack** [comment]
Probably you're interested in [this](https://github.com/skypjack/entt/discussions/684#discussion-3299774) discussion (it also contains a link to a working example).
The `copy` function isn't something that I feel like I want to add to the registry. You can easily define your utility like:
```
my_namespace::my_copy_function(entt::registry &registry, entt::entity from, entt::entity to);
```
As for the why there isn't a built-in mechanism, it's quickly explained. Consider two types, `T` and `U`. What should `copy` do for them? Emplace the source into the destination? Replace it? Emplace or replace? What if one of them is such that a copy boils down to a custom behavior like porting only some data members? What if you want to copy `T` but ignore `U` when you copy an entity? And so on.
This happened more often than not in the past and a one-fits-all solution that works for all users doesn't exist apparently.
The poly storage is there exactly for this purpose. You can look at it as an empty class that you can extend for all types or on a per-type or per-traits basis so as to customize the copy functionality (as well as any other functionality) the way you like. Moreover, there is also the nice-to-have side effect that I won't pay the cost of instantiating erased functions to copy all types if I don't need to.

**Comment by andrew-r-king** [comment]
Thanks! That discussion link was enough (I'll remember to check the discussions tab next time). You can close this issue if you want.

To answer this question:

> As for the why there isn't a built-in mechanism, it's quickly explained. Consider two types, `T` and `U`. What should `copy` do for them? Emplace the source into the destination? Replace it? Emplace or replace? What if one of them is such that a copy boils down to a custom behavior like porting only some data members? What if you want to copy `T` but ignore `U` when you copy an entity? And so on.

I can see why it gets complicated. Ultimately, in this use case, I want "other" to have the same data as "entity" in the end, just like I'm copying a class/struct. But I guess that logic would be: If the component type T or U exists on "other", replace, otherwise emplace, and if there are other components in "other" that don't exist on "entity", remove them. Maybe that boils down to naming: clone_entity or something. "copy" might be slightly more ambiguous.
