### ISSUE TITLE
Add connection pool

### ISSUE THREAD

**Issue by warxander** [skypjack/entt#695]
Connection pool can be used to store multiple connections to manage their lifetime in more easy way.

```cpp
entt::connection_pool connections; // scoped_connection container

connections += sink.connect<&mylistener::foo>(l);
// or
connections.add(sink.connect<&mylistener::bar>(l));

connections.release_all(); // or store it as class member to breaks automatically in destructor
```

Implementation example: https://github.com/warxander/entt/commit/8f661d5ad2b3b2e1e26205952fc1799ad57a6e62

**Comment by skypjack** [comment]
It doesn't seem to me like something that should be part of the library.
The implementation is just a thin wrapper around an `std::list` that could have been an `std::set` probably or anything else.
Am I missing something? What makes you feel like this should be offered out of the box?

**Comment by warxander** [comment]
Well, simple implementation is not bad, isn't it? :)

Although I understand that it's a 'matter of taste' if it should be included as a part of library.
I'm using this for my own project and used this kind of interface before, so it looks "standard enough" for me.

Thank you for review, great library!

**Comment by skypjack** [comment]
I don't dislike the idea actually, my only concern is that it adds a dependency to `<list>` in the header and I'd rather avoid it if possible. Also, not sure why you decided to use a list instead of a vector or a set. Any particular reason?
