### ISSUE TITLE
Compilation issue with Clang 9.0.1

### ISSUE THREAD

**Issue by aganea** [skypjack/entt#700]
Hello,
We're seeing the following compilation issue when using Clang:
```
1>..\..\..\..\tmp\native_pkg\entt.3.7.1-ubisoft.1\build\native\src\src\entt/meta/meta.hpp(1560,37): error : 'y_combinator' may not intend to support class template argument deduction [-Werror,-Wctad-maybe-unsupported]
1>        const auto unregister_all = y_combinator{
1>                                    ^
1>..\..\..\..\tmp\native_pkg\entt.3.7.1-ubisoft.1\build\native\src\src\entt/meta/../core/utility.hpp(72,8): note: add a deduction guide to suppress this warning
1>struct y_combinator {
1>       ^
```
Is this something that could be fixed in a future release?
Thanks!

**Comment by skypjack** [comment]
Well, if _fixing it_ means to not use the `y_combinator`, it seems pretty easy actually.
What's odd is that [the CI uses the same compiler](https://github.com/skypjack/entt/runs/2519263895?check_suite_focus=true#step:6:7) (that is, clang 9.0.1) and doesn't return any problem.
Do you have a small repro for this error? It would help a lot.

**Comment by aganea** [comment]
It actually occurs on PS4 clang, perhaps they have extra patches applied that could trigger this. I'll try to reduce the repro and will get back.

**Comment by skypjack** [comment]
I've also pushed some changes to the `any` branch if you want to give it a try.
It's going to be merged with `experimental` and therefore with `master`.

It also contains some deprecated functions aimed at removing the `<functional>` dependency and a whole bunch of commit to drastically reduce the number and size of symbols generated by both `any` and `meta_any`.

**Comment by skypjack** [comment]
Also, I'm using meta on PS4, latest sdk. Can I ask you what compiler version is in use in your case?

**Comment by aganea** [comment]
Currently using SDK 7.50.0.331

**Comment by aganea** [comment]
https://github.com/skypjack/entt/commit/ecc4f8bd83f318cb03a235a3a1177d2af72e6738 fixes the issue, thanks! :)

**Comment by skypjack** [comment]
Nice to know, it was an easy fix then. Thanks for testing it. 👍
