### ISSUE TITLE
Compile error when using entt::sink inside templated class from templated function

### ISSUE THREAD

**Issue by tmahring** [skypjack/entt#703]
Hi
I'm having some trouble getting my code to compile, when i try to use an entt::sink, thats held by an templated class, which is again used by another templated class or function.
Here is an example:
```c++
#include "entt/entt.hpp"
#include <iostream>

void handler() {
  std::cout << "handler\n";
}

template<class T>
struct TestClassT {
  entt::sigh<void()> signal;
  entt::sink<void()> sink;
  TestClassT() : sink(signal) {}
};

template<class T>
void use() {
  TestClassT<T> test;
  test.sink.connect<&handler>();
}

int main() {
  use<int>();
}
```

That code failes to compile with the following error:

```shell
test.cpp: In function 'void use()':
test.cpp:18:31: error: expected primary-expression before ')' token
   18 |   test.sink.connect<&handler>();
      |                               ^
test.cpp: In instantiation of 'void use() [with T = int]':
test.cpp:22:12:   required from here
test.cpp:18:20: error: invalid operands of types '<unresolved overloaded function type>' and 'void (*)()' to binary 'operator<'
   18 |   test.sink.connect<&handler>();
      |   ~~~~~~~~~~~~~~~~~^~~~~~~~~
```

When i move the sink and signal in a non-templated base class, the whole think becomes even stranger, now it depends on wether i cast the pointer or not if it compiles:

```cpp
struct BaseClass {
  entt::sigh<void()> signal;
  entt::sink<void()> sink;
  BaseClass() : sink(signal) {}
};

template<class T>
struct TestClassT : public BaseClass {};

template<class T>
void use(TestClassT<T>* test) {
  test->sink.connect<&handler>();     // does not compile
  static_cast<BaseClass*>(test)->sink.connect<&handler>();  // compiles
}

int main() {
  TestClassT<int> test;
  use<int>(&test);
}
```

I have to admit, that I have no clue if this a bug, or just an error on my side / misunderstanding of some c++ template magic.
It would be awesome if you could have a quick look.

**Comment by skypjack** [comment]
You only need a couple of `template` keywords in the right place. See [here](https://godbolt.org/z/5PvE6jdjr) for further details.

**Comment by tmahring** [comment]
Thank you very much!

**Comment by skypjack** [comment]
I guess we can close this one. Feel free to reopen the issue if this isn't the case. Thanks.
