### ISSUE TITLE
Questions about resource_handle

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#706]
1. Is there a way I can clear the reference of resource_handle just like std::shared_ptr::reset?
2. There seems no == operator overloading, how can I compare two resource_handles?
Thanks!

**Comment by skypjack** [comment]
1. `handle = {}`?
2. Do you want to compare the contained objects or their addresses?
    ```cpp
    bool obj = *h1 == *h2;
    bool addr = std::addressof(*h1) == std::addressof(*h2);
    ```

**Comment by hls333555** [comment]
> 1. `handle = {}`?
> 2. Do you want to compare the contained objects or their addresses?
>    ```c++
>    bool obj = *h1 == *h2;
>    bool addr = std::addressof(*h1) == std::addressof(*h2);
>    ```

Thanks! I'll have a try!

**Comment by skypjack** [comment]
You're welcome. I'm closing the issue but feel free to reopen it in case of problems. 👍

**Comment by hls333555** [comment]
I want to fully simulate what std::shared_ptr does so I choose to compare their addresses. Here's what I write:
```
template<typename T>
bool operator==(const entt::resource_handle<T>& lhs, const entt::resource_handle<T>& rhs)
{
    return std::addressof(*lhs) == std::addressof(*rhs);
}
```
But this will cause an assertion if any of them has null resource assigned. Any ideas? Thanks!

**Comment by skypjack** [comment]
Handles convert to bool. You can check if both are valid before getting the elements.

**Comment by hls333555** [comment]
> Handles convert to bool. You can check if both are valid before getting the elements.

So I just modify like this
···
template<typename T>
bool operator==(const Asset<T>& lhs, const Asset<T>& rhs)
{
    if (lhs && rhs) return std::addressof(*lhs) == std::addressof(*rhs);
    if (!lhs && !rhs) return true;
    return false;
}
···

**Comment by skypjack** [comment]
Yeah, exactly, something like:
```cpp
return (!lhs && !rhs) || (lhs && rhs && std::addressof(*lhs) == std::addressof(*rhs));
```

**Comment by hls333555** [comment]
Hey~
Is there a way I can assign `entt::resource_handle<Derived>` to `entt::resource_handle<Base>`?

I have an abstract asset class called IAsset, and a derived class called SceneAsset. I want to implement a getter somewhere to get the appropriate asset with a virtual function like below:
```C++
virtual entt::resource_handle<IAsset> GetAsset() = 0;
```
But I cannot get the following to work (it says "no suitable conversion exists"):
```C++
virtual entt::resource_handle<IAsset> GetAsset() override { return m_SceneAsset; /* Its type is entt::resource_handle<SceneAsset> */ }
```

Thanks!

**Comment by skypjack** [comment]
There is no built-in method to do that with the default implementation of a handle.
However, it looks like a good addition. I invite you to create a new issue for that. 🙂 

That said, in the meantime you can get around it by specializing the handle class.
It's more cumbersome than a built-in solution but it can get the job done if you can't wait.

**Comment by hls333555** [comment]
> There is no built-in method to do that with the default implementation of a handle.
> However, it looks like a good addition. I invite you to create a new issue for that. 🙂
> 
> That said, in the meantime you can get around it by specializing the handle class.
> It's more cumbersome than a built-in solution but it can get the job done if you can't wait.

Sure, I'll wait for that!

**Comment by skypjack** [comment]
Lets' reopen the issue to not forget about it. 👍

**Comment by skypjack** [comment]
Can you tell me if the conversion function available on branch `wip` work as expected? Thanks.

**Comment by hls333555** [comment]
> Can you tell me if the conversion functions available on branch `wip` work as expected? Thanks.

I'm using single-include file in my engine, could you please update that so that I can easily test it? Thanks!

**Comment by GavinNL** [comment]
Hi @skypjack , is it possible to add a function to resource_handle to return the shared_ptr's `use_count()`?

**Comment by skypjack** [comment]
@GavinNL it makes sense actually but could you open another issue for that?
I want to keep track of all requests and I risk to miss them if they are in a comment of a different issue.
Thanks!

**Comment by GavinNL** [comment]
Sure! I'll do that.

**Comment by hls333555** [comment]
> Can you tell me if the conversion functions available on branch `wip` work as expected? Thanks.


> Hey~
> Is there a way I can assign `entt::resource_handle<Derived>` to `entt::resource_handle<Base>`?
> 
> I have an abstract asset class called IAsset, and a derived class called SceneAsset. I want to implement a getter somewhere to get the appropriate asset with a virtual function like below:
> 
> ```c++
> virtual entt::resource_handle<IAsset> GetAsset() = 0;
> ```
> 
> But I cannot get the following to work (it says "no suitable conversion exists"):
> 
> ```c++
> virtual entt::resource_handle<IAsset> GetAsset() override { return m_SceneAsset; /* Its type is entt::resource_handle<SceneAsset> */ }
> ```
> 
> Thanks!

I have tested this conversion. It works pretty well in 3.8.0_single_include file! Thanks!
Could you please add another conversion function like std::dynamic_pointer_cast<> as down_cast is also important to me. Thanks a lot!

**Comment by skypjack** [comment]
I strongly suggest to open a dedicated issue for this @hls333555 I can't promise I won't forget about it otherwise. 😅
