### ISSUE TITLE
What is the correct to add new components during iteration?

### ISSUE THREAD

**Issue by FishHawk** [skypjack/entt#708]
Hi.

I know that after adding new components duration iteration, the reference will be invalid. But I don't know what is the correct way to do it. Here is an example.

```c++
auto view = registry.view<const Com>();
for (auto [parent, c] : view.each()) {
    for (auto i = 0u; i < c.repeat; ++i) {
        const auto child = registry.create();
        const auto new_c = Com(c.value);
        registry.emplace<Com>(child, new_c);
    }
}
```

Should I generate all `new_c` before emplacing like this?

```c++
auto view = registry.view<const Com>();
for (auto [parent, c] : view.each()) {
    std::vector<Com> vec;
    for (auto i = 0u; i < c.repeat; ++i) {
        vec.push_back(Com(c.value)); 
    }
    for (auto i = 0u; i < c.repeat; ++i) {
        const auto child = registry.create();
        registry.emplace<Com>(child, vec[i]);
    }
}
```

Thank you.

**Comment by skypjack** [comment]
Only the currently iterated reference is invalidated. If you don't plan to use it (and you're not from what I see), you don't have to worry about it.
Also, as a side note, the next release will have pointer stability when emplacing. You can already try it on branch `experimental`.

**Comment by FishHawk** [comment]
Thanks! That's awesome!
