### ISSUE TITLE
 ENTT_API_IMPORT and  ENTT_API_EXPORT

### ISSUE THREAD

**Issue by MicroSDA** [skypjack/entt#714]
Seems like latest version has issue with ENTT_API_IMPORT and  ENTT_API_EXPORT.
When those both flags are present (ENTT_API_EXPORT in source dll and ENTT_API_IMPORT in client app) - i have unresolved external symbol. I can remove them and i will get undefined behaviour instead. For example - entity has component even if it actually  doesn't.

Version 3.5.2 works correctly with  ENTT_API_IMPORT and  ENTT_API_EXPORT.

**Comment by skypjack** [comment]
Actually, nothing changed in that regard with the last version. However, you shouldn't have both export and import flag enabled on the same side. They are meant to be used on different sides of a boundary, that is you export from one side and you import from the other one.
Version 3.5.2 used a different approach that was reverted to the old one as an intermediary step for a different solution based on component names. This will be part of a future release. Soon, but I can't give a date yet.
Probably you need something like [this](https://github.com/skypjack/entt/blob/master/test/lib/registry_plugin/type_context.h) in the meantime, so as to create a common bucket for identifiers that is accessed from both sides of a boundary.

**Comment by MicroSDA** [comment]
I'm using import in application and export in dll. Thanks, i will check your example.

**Comment by skypjack** [comment]
I close this issue and assume you solved your problem given the inactivity.
Feel free to continue the discussion here or to join the gitter channel/discord server if you need help.
Thanks. 👋 🙂
