### ISSUE TITLE
A function for creating views with implicitly const components?

### ISSUE THREAD

**Issue by albin-johansson** [skypjack/entt#715]
Hi!

When working on a project I noticed that a relatively common pattern when working with `const entt::registry&` registries, is the creation of views with only `const` components. The following is a real line of code that highlights the verbosity (it causes a line break with a column limit of 90, which is relatively generous). This is also a bit annoying since the components *must* be `const` if the registry is passed as reference-to-`const`.
```C++
const auto view =
      registry.view<const ui_button, const ui_label, const ui_position, const in_menu>();
```
Now, the requirement to explicitly state `const` components with `view()` is something that I enjoy when some of the components are non-`const`. However, do you think it would be beneficial or desirable to add a convenience for explicitly creating views with implicitly `const` components? For example, adding a function such as `const_view()` that would allow us to write the previous line of code as follows?
```C++
const auto view = registry.const_view<ui_button, ui_label, ui_position, in_menu>();
```

This isn't really a major issue for me or anything, but the API's are otherwise quite terse so I was curious to see what you guys think. 😄

**Comment by skypjack** [comment]
Actually, functions like `get` or `try_get` works already with non-const types and return const references/pointers in any case.
We could do the same for the const overload of `view`, `std::add_const_t` should be enough for that. Would it work?

**Comment by albin-johansson** [comment]
Yeah, unifying the behaviour of the functions seems like a good idea. As you say, it should basically just come down to applying `std::add_const_t` to the type parameters. However, we should probably not disallow `const` types in the template parameter lists to avoid breaking existing code though if we change the behaviour of `view()`. Although it's difficult to emit warnings if users use superfluous `const` types, so I guess that we can't deprecate anything really.

**Comment by skypjack** [comment]
I wouldn't deprecate nor disable support for const types honestly.
The const overloads of `try_get` and `get` accept both const and non-const types and turn them to const in any case.

**Comment by skypjack** [comment]
If you want to give it a try, it's available on branch `wip`. 👍

**Comment by albin-johansson** [comment]
It seems to work just fine, thank you! Another related issue that I couldn't help notice when I tried it locally, is that the `const`-overload of `ctx()` also requires that the type parameters are `const`. Now, I don't know if there is a technical limitation or reason for this, but would this requirement be worth dropping for `ctx()` as well? 😄

**Comment by skypjack** [comment]
I think it's easy as well. However, can I ask you to create another issue for that or to update the title of this one?
It helps me to keep track of the work and to figure out what's still pending. Thanks!

**Comment by albin-johansson** [comment]
See #720 for an issue specific to the registry context variable getters. Feel free to close this issue whenever you want, thank you!😄

**Comment by skypjack** [comment]
Thanks!
