### ISSUE TITLE
Using Entt in a engine with multiples DLL

### ISSUE THREAD

**Issue by SirLynix** [skypjack/entt#716]
Hi there,

I'm trying to integrate EnTT as the ECS of my game engine] which is made of several modules (think of SFML) and I run into some issues with component indexing, with indexes of some components not being the same inside and outside of the engine.

To explain, I have a `Core` module, a `Physics` one and a `Graphics` one (every module lies in its own dll). My idea was to have each module expose some components and systems, for example:
- Physics exposes a `RigidBodyComponent` and a `CollisionComponent`.
- Core exposes a `NodeComponent` (transformations)
- Graphics exposes a `GraphicsComponent`

With Physics exposing a system synchronizing the RigidBodyComponent and the NodeComponent, and Graphics exposing a system drawing things where the NodeComponent is, I think you see the picture.

The issue I have is that each module is not aware/linked of other modules, except for the Core, and so every module generates its own type identifier for the modules it knows about, and when an application tries to use the components from the modules, it doesn't go too well.

I took a look at https://github.com/skypjack/entt/wiki/Push-EnTT-across-boundaries and `type_info` documentation, but I'm not sure what would be the best solution here.

I was thinking of using a external generator, using:
```cpp
template<typename Type>
struct entt::type_seq<Type, std::void_d<decltype(Type::index())>> {
    static entt::id_type value() ENTT_NOEXCEPT {
        return Type::index();
    }
};
```

and giving each component a unique id manually. However there can be a problem if someone using the engine tries to mix their own components with components from my engine, as I think the internal type_seq counter will start at zero, which would force the engine users to provide a `index()` function to manually set their ID, which doesn't seem right.

I also tried to have the core define `ENTT_API_EXPORT` with every other module (and app) using `ENTT_API_IMPORT` but since the core doesn't make use of their modules I couldn't make it work (plus, wouldn't it prevent the user app to make its own components?)

What would be the best course of action?

I was thinking of maybe having a header in the `Core` module which would forward declare every component and instantiate all type_seq templates in a fixed order, maybe with an inline function that the user would have to call in their code?

Thank you for your help

**Comment by skypjack** [comment]
Yeah, I tried a bunch of different solutions over time to keep the direct index intact but it still requires some machinery with DLLs.
Soon I'll turn the whole thing to a name-based model and this should get rid of the direct index and make working across boundaries transparent. On the other side, it's also slightly less efficient, so I want to do it _the right way_.
This means that in the long run you'll be able to remove all the glue code. In the meantime, is the type context [here](https://github.com/skypjack/entt/tree/master/test/lib/registry_plugin) what you're looking for?

**Comment by SirLynix** [comment]
I think it would work yes, in the meantime I implemented a solution based on a [inline function](https://github.com/DigitalPulseSoftware/NazaraEngine/blob/2dfb6dce5fa3266dc3ceb79d5b6889199ed46187/include/Nazara/Core/ECS.inl#L22) (based in the Core module) that the user should call when initializing the engine, which will instantiate and check `entt::type_seq` value in a specific order.

Every module in the engine also calls this function on initialization to make sure components ID are the same.

Since this function is inline (it's not exported to make sure it's not part of the DLL), it should execute as part of the user application, initializing entt registry in the user application space, I hope.

I've only tested it on MSVC for now but it seems to work.

**Comment by skypjack** [comment]
Sounds good. You can just drop it when the rework is in place. 👍

**Comment by SirLynix** [comment]
Thank you for your hard work on EnTT. I'm closing this since I'm got a working solution and you're working on a even better one. 😄 

I just hope there won't be too much overhead from having name-based indices

**Comment by skypjack** [comment]
> I just hope there won't be too much overhead from having name-based indices

Yeah, that's what I'm working on. The idea is either to make it optional or to provide a way to avoid indexing as much as possible.

**Comment by RamilGauss** [comment]
How about this:

``` cpp
template<typename...>
class DllExport TRunTimeTypeIndex
{
public:
    using TypeCounter = unsigned int;
    using AtomicTypeCounter = 
#ifdef USE_MULTITHREAD
        std::atomic<TypeCounter>;
#else
        TypeCounter;
#endif
private:
    AtomicTypeCounter mCounter;

    struct MultiType
    {
        std::set<std::type_index> types;

        bool operator <(const MultiType& rhs) const
        {
            return types < rhs.types;
        }
    };

    std::map<MultiType, TypeCounter> mTypeCounters;

    template <typename T>
    void Fill(MultiType& multiType)
    {
        multiType.types.insert(std::type_index(typeid(T)));
    }

    template <typename T0, typename T1, typename ... Args>
    void Fill(MultiType& multiType)
    {
        Fill<T0>(multiType);
        Fill<T1, Args...>(multiType);
    }
public:
    template <typename T, typename ... Args>
    TypeCounter Type()
    {
        static TypeCounter innerCounter = -1;
        if (innerCounter == -1) {
            MultiType multiType;
            Fill<T, Args...>(multiType);

            auto fit = mTypeCounters.find(multiType);
            if (mTypeCounters.end() == fit) {
                mTypeCounters[multiType] = mCounter++;
            }
            innerCounter = mTypeCounters[multiType];

        }
        return innerCounter;
    }
};
```

**Comment by skypjack** [comment]
The issue is actually solved on `master` at the moment @RamilGauss 🙂

**Comment by RamilGauss** [comment]
Not quite fixed. If you call from one DLL:
```cpp
     auto strId = entt :: type_id <std :: string> (). seq (); // -> 0
     auto intId = entt :: type_id <int> () .seq ();// -> 1
```
and call from another Dll (or *.exe):
```cpp
     auto intId = entt :: type_id <int> () .seq ();// -> 0
     auto strId = entt :: type_id <std :: string> (). seq ();// -> 1
```
The point is where the call to the template method comes from. 

The TRunTimeTypeIndex::Type<x> can be called from different libraries and and the result will be the same.

**Comment by skypjack** [comment]
Indeed but the registry no longer uses the sequence generator. Therefore the registry doesn't suffer from this problem anymore.

**Comment by RamilGauss** [comment]
If the order of adding will be different in different libraries. 

```cpp
int main()
{
    entt::registry reg;
    auto eid = reg.create();
    X x;// goes first
    reg.emplace<X>(eid, x);
    Y y;// second!
    reg.emplace<Y>(eid, y);
    Caller caller;
    caller.Set(&reg);
    caller.Func();
}
```

Another dll.
```cpp
void Caller::Func()
{
    auto eid = pReg->create();
    Y y;// now it goes first
    pReg->emplace<Y>(eid, y);
    X x;
    pReg->emplace<X>(eid, x);
    pReg->each([this](auto ent)
    {
        auto yy = pReg->get<Y>(ent);// it crashes on second entity !!!!!!
        auto xx = pReg->get<X>(ent);
    });
}
```

Sorry for my persistence. :)

**Comment by skypjack** [comment]
Yeah, sure, this would break it if the registry still used the sequence generator **but** it does not.
It now stores pools in a (custom dense hash) map internally. No static variables. The order doesn't matter anymore.

**Comment by RamilGauss** [comment]
At 3.8.2?

**Comment by skypjack** [comment]
Version 3.8.2 doesn't exist. These changes are part of `master` and therefore of v3.9 at the moment.
