### ISSUE TITLE
Allow non-const types in const overloads of registry context variable getters

### ISSUE THREAD

**Issue by albin-johansson** [skypjack/entt#720]
Note: This issue is closely related to #715, which proposes the same thing for `view()`/`group()`.

In order to unify the behaviour of functions like `get()`, `try_get()`, `view()`, `group()` with `ctx()` and `try_ctx()`, allow non-`const` types in the `const` overloads of `basic_registry::ctx()` and `basic_registry::try_ctx()`. 

```C++
void some_system(const entt::registry& registry)
{
   // Current: The type parameters must be const-qualified, which is redundant due to the reference-to-const registry
  auto& ref = registry.ctx<const foobar>(); 
  auto* ptr = registry.try_ctx<const foobar>();

  // Proposed: The registry is already const-qualified, so we know that the context variables must be const
  auto& ref = registry.ctx<foobar>();      // decltype(ref) == const foobar&
  auto* ptr = registry.try_ctx<foobar>();  // decltype(ptr) == const foobar*
}
```

**Comment by ElDesalmado** [comment]
I feel that this would be confusing and inconsistent. In case of non-const `registry` you will still have to write `ctx<const foobar>` in order to get const-qualified reference to `foobar`

**Comment by albin-johansson** [comment]
> I feel that this would be confusing and inconsistent.

Currently, functions like `get()`, `try_get()` (and `view()` and `group()` on the `wip` branch) have this behaviour for their `const` overloads. So the current behaviour is more inconsistent in that regard.

> In case of non-const `registry` you will still have to write `ctx<const foobar>` in order to get const-qualified reference to `foobar`

That is a good thing, in my opinion. The default when working with a non-`const` registry shouldn't be `const`. The point is that the context variables will be `const` no matter what when you're working with a `const` registry. You won't be able to mistakenly use non-`const` context variables with a `const` registry.
