### ISSUE TITLE
Does entt have owning entt::handle ?

### ISSUE THREAD

**Issue by Eren121** [skypjack/entt#721]
I figured out, that I need often only one entity. It allow to add components to an object.

```c++
class GameObject {
     entt::registry reg;
     entt::entity_type entity;
};
```

My qestions are :
1) Is there anything to facilitate that in `entt` ? I know there is `handle`, but I believe `handle` is non-owning. Basically, a `owning_handle` would be perfect.
2) Is a `registry` a lightweight object, that can be created multiple thousand of times ?

Thanks you!

**Comment by skypjack** [comment]
Do you mean a registry with a single entity? It seems a waste to me. Why would you use it like this?

> Is a registry a lightweight object, that can be created multiple thousand of times ?

Yeah, it's cheap to create, I often use multiple registries.

**Comment by Eren121** [comment]
The fact is, when using `registry`, you need to pass a reference of the registry around all of your code. With a `owning_handle`, you can integrate `entt` with only adding a single field to your class.

**Comment by skypjack** [comment]
Though, if you want to create a view and iterate all entities that have components `A` and `B`, the entities managed by your handles **must** be put in the registry. Right? Otherwise, what you're looking for is just an OOP-like approach that has nothing wrong but is not what EnTT tries to achieve.

**Comment by Eren121** [comment]
I was learning about ECS... And entt is more ECSR ;)

Yes, it's less powerful. Hm you're probably right, in fact I was using mostly `entt` like a "map anything to any object".

**Comment by skypjack** [comment]
Yeah, what you describe is mostly similar to the old EC model of engines like Unity, where the entity/game object owns its components. EnTT flips the whole thing on its head and uses the entity as an index to lookup components from pools.

**Comment by skypjack** [comment]
I close the issue because it seems to me that the question has been answered.
Feel free to continue the discussion here if this isn't the case. Thank you.
