### ISSUE TITLE
The view is not getting any entities when the filters contain all the components of an entity

### ISSUE THREAD

**Issue by SeleDreams** [skypjack/entt#726]
Hi, I noticed a really strange behaviour while working on a system.

I basically created an entity that has
- a TransformComponent
- a MeshComponent
- a ShaderComponent

I tried to iterate through entities of this type by doing

auto view = registry.view<TransformComponent,MeshComponent,ShaderComponent>();

but this didn't give me any results, which I found weird.
I then tried to remove some components from the request, for instance ShaderComponent
auto view = registry.view<TransformComponent,MeshComponent>();

there it started getting results, I started thinking that maybe i forgot to add ShaderComponent to my entities
but in fact if I try something else, by removing MeshComponent instead

auto view = registry.view<TransformComponent,ShaderComponent>();

this also gets results

so this makes me think that either a bug or an intended behaviour I don't know of, prevents me from finding entities where all the components match

**Comment by SeleDreams** [comment]
as a note, using RuntimeView allows to work around this problem
doing this
`  entt::id_type types[] = { entt::type_hash<TransformComponent>::value(), entt::type_hash<MeshComponent>::value(),entt::type_hash<ShaderComponent>::value()  };
    auto view = registry.runtime_view(std::cbegin(types), std::cend(types));`
works, entities correctly get retrieved

**Comment by SeleDreams** [comment]
![image](https://user-images.githubusercontent.com/16335601/124043078-94729f00-da0a-11eb-9cfd-23e32188bb5a.png)
In fact in any case it was having issues even as a runtimeview to get the transform, and through debugging i noticed something interesting

it seems like the transformcomponent is getting deleted as soon as it gets added to the entity, it doesn't happen to any of the other components

**Comment by SeleDreams** [comment]
so, here's a minimal case

![image](https://user-images.githubusercontent.com/16335601/124044774-760ea280-da0e-11eb-848e-cc9dbd6fb9e4.png)

entity 1 gets created succesfully, entity 2 has the destructor of TransformComponent getting called as soon as it's added

**Comment by SeleDreams** [comment]
![image](https://user-images.githubusercontent.com/16335601/124044881-b8d07a80-da0e-11eb-8bb5-473078e7230f.png)
so here's a minimal example

entity 1 gets created succesfully, the destructor of the TransformComponent gets called immediately for the second entity which isn't normal

**Comment by SeleDreams** [comment]
Ok, so I found a fix, however this is REALLY weird

the fix was... changing the compilation from shared to static, it seems like having the game engine as a shared library broke the entity system

**Comment by SeleDreams** [comment]
I wonder if it is something like the types not getting properly exported to the shared library

**Comment by skypjack** [comment]
Things are about to change soon in the registry, more or less to solve this exact _issue_.
However, you can make it work also with the current implementation as described [here](https://github.com/skypjack/entt/wiki/Push-EnTT-across-boundaries#the-entt-way) and as shown in the `lib` dir.

**Comment by skypjack** [comment]
I close the issue since I assume that your question/doubt has been answered.
Feel free to continue the discussion here if it's not. Thanks.
