### ISSUE TITLE
Clang format?

### ISSUE THREAD

**Issue by ElDesalmado** [skypjack/entt#733]
Do you intend to include a clang format file for autoformatting? Or maybe some other tools for autoformatting are used already?

**Comment by skypjack** [comment]
There are no tools in use at the moment actually.
I plan to add one? Dunno, not really but it's not a big problem either.

**Comment by ElDesalmado** [comment]
For one thing, it is rather convenient to autoformat a document when you make a PR, rather to do it by hand. It *is* not a big deal, until you get used to autoformatting and are tired of people's PRs that don't meet the style for some reason.

**Comment by Innokentiy-Alaytsev** [comment]
The thing is that `clang-format` can't reproduce the current formatting which is there for _reasons_.
