### ISSUE TITLE
Invalid component type

### ISSUE THREAD

**Issue by hero2002** [skypjack/entt#734]
I am trying to create entity with position component with this code 
`const auto player2 = registry.create();
registry.emplace<position>(player2, 10, 5);
`
with the position as
`struct position {
    float x;
    float y;
};`
which genrate the following eror
` error: static assertion failed: Invalid component type
             static_assert(std::is_same_v<Comp..., Component>, "Invalid component type");
                           ^~~`

**Comment by skypjack** [comment]
As it stands, there are not enough information to help.
Can you provide at least the version of EnTT in use and the line/file where the assert is triggered?
Thanks.

**Comment by hero2002** [comment]
I used EnTT v3.7.1 and even tried the latest master brench 
edit: something awkward happened after I retried with same code now it worked
sorry for inconvenience
if you don't mind me I have a couple function
1- how can I attach some function to component so when iterate on the component I can just call it's function
2-how can I get a pointer to a component and not copy so I don't waste memory
I tried this 
`auto pos = registry.get<position>(player2);` but it generate a copy of that component 
note : I tried reading the docs

**Comment by skypjack** [comment]
@hero2002 

1. Components are class types. They can have member functions. Isn't it enough to _attach_ a function to a component? Otherwise you can use a function pointer or the like. This doesn't really depend on/matter to EnTT.

2. `get` returns a reference. Try `auto &` instead of `auto`.
