### ISSUE TITLE
Undesired fallthrough from previous case

### ISSUE THREAD

**Issue by morbo84** [skypjack/entt#736]
There's an undesirable fallthrough from the previous case (`operation::DEREF`) to `operation::SEQ`.

https://github.com/skypjack/entt/blob/9460e04ea547e7f4f3923c5458b187781c604220/src/entt/meta/meta.hpp#L174-L185

**Comment by skypjack** [comment]
Fortunately I can't imagine a case in which we pass both `if constexpr` bit this is definitely something to fix to avoid future errors.
Thanks for pointing this out!!
