### ISSUE TITLE
`entt_traits::construct` causes UB for 64-bit types

### ISSUE THREAD

**Issue by glebov-andrey** [skypjack/entt#745]
Hi!

Release 3.8.0 is broken for 64-bit ID types (and probably 32-bit ones too).
`entt_traits::version_type` is `std::uint32_t` but `entt_traits::construct` shifts it left by `32`:
https://github.com/skypjack/entt/blob/89aece7c28124b00f457aaf31829e0ef04fe6256/src/entt/entity/entity.hpp#L128-L130
As MSVC notes this is UB: `entity.hpp(129): warning C4293: '<<': shift count negative or too big, undefined behavior`.
Trivial code like the following triggers assertion failures:
```c++
enum class entity_t : std::uint64_t {};
struct my_component {};

int main() {
    auto registry = entt::basic_registry<entity_t>{};
    const auto id = registry.create();
    registry.emplace<my_component>(id);
}
// Assertion failed: entt != tombstone && entt != null, file <...>\entt\entity\sparse_set.hpp, line 518
//                        ^ this is false
```

Presumably `entt_traits::construct` should first cast `version` to `entt_traits::entity_type` and then shift it. Also there could be other places in the codebase with similar issues.

The only reason this works with 32-bit types is because `entt_traits::version_type`(`std::uint16_t`) is usually `unsigned short` and the shift operator first promotes it to `int`. If I'm not mistaken this also causes undefined behavior if the resulting value is larger than `INT_MAX` (e.g. `version_mask << entity_shift` is `0xfff << 20u` which overflows a 32-bit `int`). Oddly enough both MSVC and Clang allow this in constant expressions.

On a related note, the tests don't seem to cover 64-bit IDs. I tried to compile the tests with `ENTT_ID_TYPE=std::uint64_t` and that failed because the described UB was triggered in constant expressions. It might be a good idea to add a CMake option to test with `ENTT_ID_TYPE=std::uint64_t` and/or add some tests for 64-bit IDs.

Thank you for your work on this library!

**Comment by skypjack** [comment]
Ouch. Good catch. Thanks for reporting!
I think you're right. It's time to also run the 64b version in the CI.

> Also there could be other places in the codebase with similar issues.

Hopefully not. I centralized the entity bit manipulation exactly to avoid subtle bugs due to copy-paste errors upon changes.
In any case, the CI will tell us if this is the case.

**Comment by skypjack** [comment]
Branch `v3.8.x` contains all the changes required to get around your issue and an updated workflow to tests 64b identifiers on the CI.
I'm literally ready to cut a minor release with a bunch of QoL improvements and this fix. Could you confirm that your issue is solved before proceeding? It would be **really** appreciated!! 🙂 
Thanks.

**Comment by glebov-andrey** [comment]
Tested with branch `3.8.x` and 64-bit IDs. Everything seems to be working correctly now :)
Thanks for the quick fix!

**Comment by skypjack** [comment]
Oh, well, thank you for reporting this and for convincing me to set up the CI for 64b identifiers too! 🙂 
For your interest, I'll cut a minor release (v3.8.1) soon, most likely today or tomorrow.
