### ISSUE TITLE
Is there a way to set data member from meta_any?

### ISSUE THREAD

**Issue by SoftwareEngIsArt** [skypjack/entt#750]
I am wondering if there is a way or a workaround to set type data members from `meta_any` instead of using a compile-time type.

My original idea was that certain types would specify a serializer as a property of their type, with the serializer returning a `meta_any` instance of that type. In case a type does not specify a serializer, a generic one would be used that would iterate over all reflected data members of the type, deserialize them individually and then set them for the type's instance. 

The `meta_data` class however does not seem to support setting data members from `meta_any`, however it's `get` method does return a `meta_any` instance.

Is there a way to implement a workaround for it? I am using the entt 3.8.0 version (latest available through conan).

**Comment by skypjack** [comment]
Do I get it correctly that you want to pass a `meta_any` to the `set` function of a `meta_data` object?
In this case, you can just pass it as an argument and use `.as_ref()` if you want to avoid copies.
Otherwise, can you provide more details about what you're trying to achieve?

**Comment by SoftwareEngIsArt** [comment]
Yes, you are correct, thank you for the example. The documentation did not say that a `meta_any` object can be used for the `set` function, or i just missed it, so i was confused. Thank you again for the explanation.

**Comment by skypjack** [comment]
You're welcome.
It's likely that the lack is in the documentation. You were right to ask. :)
