### ISSUE TITLE
How to Sort Entities

### ISSUE THREAD

**Issue by SimonMaracine** [skypjack/entt#752]
I'm using EnTT for my game and I'm trying to render some objects in a particular order, specifically by their distance to the camera. I need to create a view in which the entities are in a specific order. I read  the docs and I wrote this:

```
void systems::piece_render(entt::registry& registry, entt::entity hovered_entity, entt::entity camera_entity) {
    auto& camera_transform = registry.get<TransformComponent>(camera_entity);

    auto func = [&camera_transform](const TransformComponent& lhs, const TransformComponent& rhs) {
        float distance1 = glm::length(camera_transform.position - lhs.position);
        float distance2 = glm::length(camera_transform.position - rhs.position);
        return distance1 < distance2;
    };

    registry.sort<TransformComponent>(func);

    auto view = registry.view<TransformComponent, MeshComponent,
                              MaterialComponent, TextureComponent,
                              OutlineComponent, PieceComponent>();

    for (entt::entity entity : view) {
        auto [transform, mesh, material, textures, outline, piece] = view.get(entity);
        // Render code here
    }
}
```

But it doesn't seem to do what I want. Looks like the objects are still rendered like before. I think I'm using `sort` wrongly. **The docs aren't clear to me for some reason**. My question is: How can I achieve what I want?

**Comment by skypjack** [comment]
You probably want to add a `view.use<TransformComponent>()` before iterating the view. It guarantees that the order of your `TransformComponent` is respected.

**Comment by SimonMaracine** [comment]
> You probably want to add a `view.use<TransformComponent>()` before iterating the view. It guarantees that the order of your `TransformComponent` is respected.

Ok. I'll try when I will be back home. Thank you.

**Comment by SimonMaracine** [comment]
Wow! I tried what you said and it works now. It renders the objects back to front.

I didn't know the `use` method before.

**Comment by skypjack** [comment]
You're welcome.

**Comment by OverShifted** [comment]
@skypjack Who fast (or slow) `registry.sort` is? Since it is called every frame.

**Comment by skypjack** [comment]
It sorts a sparse set. Slower than sorting a vector because it also has to update the sparse array. The packed array is a single packed array that is sorted using `std::sort` or any other function you pass to it instead (it's configurable, probably an insertion sort is faster in many cases but this really depends on the application).
Everything happens in-place. No allocations nor anything else. I also wrote an extensive post on the blog about this topic.

I use it in real world applications, the reason for which it's there 
This doesn't make it blazing fast automatically but at least confirms that it's not there just because. :)

**Comment by OverShifted** [comment]
When I want to render my objects; I use a vector to save vertex buffer data before rendering them using a batch renderer.
Is sorting that vector is faster than sorting entities?

**Comment by skypjack** [comment]
Well, sorting a pool literally sorts a vector (similar cost) and updates the sparse array associated to it (additional cost).
It doesn't matter how small the second cost is, its existence is already the answer you're looking for.

**Comment by OverShifted** [comment]
Got it

**Comment by sourabh-gupta-dev** [comment]
I have a similar use case of sorting entities. But I am not able to use the view.use<Comp>() function.
It keeps giving me error
```
No member named 'use' in 'entt::basic_view<entt::entity, entt::get_t<Shutter::SortComponent>, entt::exclude_t<>>'
```

I am using v3.9.0 and below is my usage.
```
m_Registry.sort<SortComponent>([](const auto &lhs, const auto &rhs) {
            return lhs.sortOrder > rhs.sortOrder;
        }, entt::insertion_sort());
        auto view = m_Registry.view<SortComponent>();
        view.use<SortComponent>();
```
Please help me with this issue.

**Comment by skypjack** [comment]
@sourabh-gupta-dev `view::use` is only available for multi-type views. It tells to the view what pool to use to drive the iteration.
It wouldn't make much sense for a single type view actually since you don't really have a choice there. 😅

**Comment by sourabh-gupta-dev** [comment]
Got it. Thanks for the quick reply.
