### ISSUE TITLE
Storing pointers in components

### ISSUE THREAD

**Issue by OverShifted** [skypjack/entt#754]
I have a component that contains information needed to render a sprite:
```c++
struct SpriteRendererComponent
{
    std::shared_ptr<Texture> sprite;
}
```

And a system that renders the sprite:
```c++
// Iterates over TransformCompoennt and SpriteRendererComponent
Renderer::Render(transform.GetMatrix(), spriteRenderer.sprite->GetOpenGLID());
```

The whole point of ECS is to make use of the CPU cache by tightly packing components.
But here; For each `SpriteRendererComponent`; I am fetching the memory that `spriteRenderer.sprite` points to; To retrieve the OpenGL id of the texture.

Will this ruin optimizations behind ECS (Because data in the cache will become useless after fetching `spriteRenderer.sprite`)?
If yes; Is there any solution to it?

**Comment by skypjack** [comment]
In theory, you can customize your pool and store (and rearrange) entities and components by sprite. This isn't much different from what groups do already.
However, I would rather go with your approach, measure and change it **only** in case of problems, ie if it shows up as a bottleneck while measuring.
What you're doing here is trading some perf for some memory. This approach is very close to the flyweight pattern and I wouldn't turn it off nor add extra code to maintain for a premature optimization.

**Comment by OverShifted** [comment]
Do you mean content in the cache is still useful after fetching `spriteRenderer.sprite` which is far far away from `spriteRenderer`?
What about `transform`?
`TransformCompoenent`s are probably stored far away from ‍`SpriteRenderer`s (not sure how EnTT handles it). So when I fetch `transform`; content in the cache will point to `transform` and maybe a few other `TransformCompoenents` after that. So it won't help with `SpriteRenderers`.

Am I wrong? If yes; please tell :)

**Comment by skypjack** [comment]
> Do you mean content in the cache is still useful after fetching spriteRenderer.sprite which is far far away from spriteRenderer?
What about transform?

What I mean is that you can try to elaborate all objects with a same sprite together to improve locality and avoid some jumps. You can move around things in parallel in both pools if you want them to have the same order. Though, the real question is: does it worth it in your case?
Keep in mind that using an ecs arch doesn't mean that you won't have any cache misses in your software! Also, the more the context you need to fully elaborate an entity, the greater the likelihood of something being ripped off.
Moreover:

> TransformCompoenents are probably stored far away from ‍SpriteRenderers (not sure how EnTT handles it). So when I fetch transform; content in the cache will point to transform and maybe a few other TransformCompoenents after that. So it won't help with SpriteRenderers.

Cache... I mean... it doesn't work like that. It's also hard to predict what the cpu will do. All you can do is to _help_ it and provide it with data that are easy to prefetch and elaborate in a meaningful way.
As a side note, this is somewhat wrong too, something some companies shouldn't sell as an idea just to make two extra pennies:

> The whole point of ECS is to make use of the CPU cache by tightly packing components.

This is **not** the whole point (fortunately). Don't get obsessed by this kind of things. It's (very very very) likely that the current implementation with a pointer to an object that is shared by many entities is already good enough for 99% of uses.
Just measure before trying to replace a solution that is easy to reason about with something that is way more complex to get correct and to maintain.

**Comment by OverShifted** [comment]
@skypjack Thank you for your reply. The cache can be smarter than what I thought.
