### ISSUE TITLE
Is there any way to invoke member function using meta?

### ISSUE THREAD

**Issue by BarbedCrow** [skypjack/entt#755]
Hello! So I have a basic setup like this:
```cpp
template<typename Type>
   Type& get(entt::registry& registry, entt::entity entity) {
      return registry.template get<Type>(entity);
   }

class A
{
   void Print() { printf("print"); }
   void static StaticPrint() { printf("static print"); }
};
```
And main function like this:
```cpp
int main()
{
   auto registry = entt::registry;
   entt::meta<A>().type()
      .func<&A::Print>("Print"_hs)
      .func<&A::StaticPrint>("StaticPrint"_hs)
      .func<&get<A>, entt::as_ref_t>("get"_hs);
   const auto entity = registry->create();
      registry->emplace<A>(entity);
      registry->visit(entity, [&](const auto info) {
         const auto type = entt::resolve(info);
         const auto any = type.func("get"_hs).invoke({}, std::ref(registry), entity);
         if (auto func = type.func("Print"_hs); func)
         {
            func.invoke(any);
         }
			
         if (auto staticFunc = type.func("StaticPrint"_hs))
         {
            staticFunc.invoke(any);
         }
      });
}
```

This code works perfectly for static function, but when I try and call **Print** function I just get nothing. I tried to invoke it with({}) instead of (any), and it doesn't work too. 
Sorry if it's a dumb question. I am pretty new with this library and don't know all of the details, but I will really appreciate your help

**Comment by skypjack** [comment]
You're trying to invoke a non-const method (`void Print() { ... }`) from a const object (`const auto any = ...`).
This doesn't work in C++ as well as for meta types. Just add a `const` here or remove a `const` there to [make it work](https://godbolt.org/z/zxf7T3Yb5).

**Comment by BarbedCrow** [comment]
Thanks a lot for your quick response! I really just missed that I was using const object

**Comment by skypjack** [comment]
You're welcome.
