### ISSUE TITLE
snapshot entity list size incorrect

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#757]
Unlike the component-list sizes, the snapshot entity-list size doesn't include the destroyed entity at the end, so the size has to be adjusted by the archive function.

```
struct ArchiveSave {
  bool writing_entities{};

  void operator()(std::underlying_type_t<entt::entity> size) {
    if(writing_entities) ++size;
    init_output_buffer(size);
  }
};

struct ArchiveLoad {
  bool writing_entities{};

  void operator()(std::underlying_type_t<entt::entity>& size) {
    size = get_input_size();
    if(writing_entities) --size;
  }
};
```

**Comment by skypjack** [comment]
Can I ask you to provide a little more details about this? For example, can you tell me what calls cause your problems?
It would help a lot. Not sure I get exactly what you're trying to do and why it's wrong, sorry.

**Comment by huwpascoe** [comment]
This line here
https://github.com/skypjack/entt/blob/0754f108c99ed2adce12b8d1bdf370169d103614/src/entt/entity/snapshot.hpp#L96

Let's say I create one entity and snapshot it. The resulting list contains the one entity plus another tail(?) entity. entities.size() == 2. But when the operator is called, it only shows the underlying_type<> size to be 1.

**Comment by skypjack** [comment]
Oh, I guess this is the line that causes you troubles?
```cpp
archive(reg->released());
```
Is it? That's the head of the list of destroyed entities.

**Comment by huwpascoe** [comment]
Thanks!
