### ISSUE TITLE
Proposal: Refcounted Double Linked Lists for version objects

### ISSUE THREAD

**Issue by CharlesJQuarra** [skypjack/entt#759]
This might not be useful for everyone, but I thought to write it down in case it might have interesting applications

The problem with incremental counters for versions in `Entity` identifiers is that for long-running programs (like, if Entt/ECS is used to implement an online game server), they might wrap around and result in false alive tests.

The optimization opportunity is that many version numbers might have no entities pointing to them, and that all the functionality provided by versioning can presumably exist with a reduced set of Version identifiers. The only important invariants for versions is that:

1) they are well-ordered
2) that they remain alive as long as all past Entity references that point to it

These can be easily achieved by implementing the Version objects as DL lists with a refcount of Entity references. Whenever it is detected that no one holds an Entity reference point to a given Version object, the object is removed.

If one is confident the number of alive versions in a program will remain limited, one might replace a pointer to a version object as the version identifier, with an index in the actual array of pointers

Any feedback on the above is welcome.

**Comment by codylico** [comment]
Two thoughts come to mind:
- *Worst-case: one entity per version, all versions used up:* Is there a way to handle version identifier selection in this case?
- *New version selection:* How does this scheme select new version identifiers, given that a version object, once removed, "takes" its identifier with it? Do the pointers to object (for example, `Version* ptr;`) become the de-facto version identifier?

Forgive me if I'm missing something obvious.
