### ISSUE TITLE
How to create a new entity with custom identifier

### ISSUE THREAD

**Issue by 1TrueNova1** [skypjack/entt#763]
Hello! Excuse me if the question I am going to ask has already been elaborated in the documentation, I was trying to find it there but failed.
I am almost a newbie and currently learning C++ by trying to implement a simple game engine. I added a little networking part to it, and my problem is that I need to have server and client entities synchronized (meaning entt::entity of objects on server and client must be the same no matter what), and the only one solution I could have come up with is transmitting entities of all objects created on server to clients. After receiving them, clients must set these new entities to their registries. However, I could not have found any function that can perform adding entities with custom identifiers to registry. I have found only create() function that simpy adds new entity with id that is being incremented every time. But I would like to have control over what identifiers are being added to entities vector.
Thank you in advance!

**Comment by 1TrueNova1** [comment]
Is create() method overload that takes in const entity_type hint as parameter the thing I was asking? Oopsie if so...

**Comment by skypjack** [comment]
Yeah, more or less. The `create` overload that also accepts a hint does its best to return the requested identifier. However, it fails if the identifier is already in use. So, it's up to you to guarantee the consistency between client and server.
In general, you don't replicate identifiers exactly in these cases. Instead, you should use a local-remote map to decouple them. It also has the advantage of working offline if required/needed.

**Comment by 1TrueNova1** [comment]
Oh, hm, I've never thought about it. I think it is actually the right way to solve the problem. Thank you very much!
