### ISSUE TITLE
EnTT Library always Errors

### ISSUE THREAD

**Issue by Dynimics** [skypjack/entt#769]
I'm working on a small game engine backend for a project and I'm trying to use EnTT for an Entity Component System. Everytime I try to include EnTT into my project, I get lots of errors. About 4 or 5 pages full of errors. I'm not sure what I'm doing wrong

**Comment by skypjack** [comment]
It's hard to say without looking at the errors.
However, my guess is that you didn't set C++17 as the default.

**Comment by Dynimics** [comment]
My CXX standard is set in the make file as C++20

**Comment by skypjack** [comment]
Ok. Can you show at least one error? It's a little hard to figure it out otherwise.

**Comment by Dynimics** [comment]
The first error I get is:
'argument list for class template "entt::overloaded" is missing'
The second error I get, on 'Func...' parameter of overloaded:
'expected a ')''

**Comment by skypjack** [comment]
Yeah, that's exactly the kind of error returned when you use C++11/14 with EnTT. The specific message depends on the compiler. Which one are you using?
I strongly suggest to review your cmake config and eventually regenerate the cache from scratch. EnTT is guaranteed to work with C++17 and C++20 at the moment. 👍

**Comment by Dynimics** [comment]
I apologise for this. Turns out it was my CMake configuration being wrong. Thank you for trying anyways :)
