### ISSUE TITLE
Call for comments: getting rid of the raw view

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#77]
Recently I worked a lot on improving standard views for single components and they finally got rid of all the indirections, thus being faster than ever.  
Because of this, it doesn't make much sense for me to continue supporting raw views:

* Performance are more or less the same of a standard view created for the same component, even though entities aren't accessed.

* There are few to no cases where it makes sense to use a raw view - I have never used them so far actually!!

* Supporting something that smells of _dead code_ is annoying.

From my point of view, I can get rid of them unless someone has a good reason to continue supporting raw views.  
As a compromise for the really few cases in which they can be useful (if any), I could add a couple of member functions to the standard views for single components in order to return _raw begin/end iterators_. We won't be able anymore to _go raw_ in a range-for loop, but we can get away with it using a `while` after all.

What about? Someone knows of use cases from a real world project where raw views are a must-have in terms of performance?

---

Lighting issue before to decide. I'll close it in 24h .  
Thank you all for participating.

**Comment by skypjack** [comment]
@vblanco20-1 I'm glad to know someone found useful raw views, it's a point in favor of keeping them on board. Views for single components has a `size` member function that returns the exact number of entities they contain, sure.

How is it going your project? Still satisfied of `EnTT`? Feel free to contact me for any request.

**Comment by ArnCarveris** [comment]
@skypjack Need instances data getter, for raw direct access.

**Comment by skypjack** [comment]
@ArnCarveris Views already contains `get` member functions. What else? Maybe I didn't get your request.

**Comment by ArnCarveris** [comment]
@skypjack I mean [this](https://github.com/skypjack/entt/blob/871bda6198c640ccbb023c43ae09d0c400b63f6e/src/entt/entity/view.hpp#L975), don't remove it.

**Comment by skypjack** [comment]
@ArnCarveris Sure, no plan to remove it.

**Comment by skypjack** [comment]
Time to close this issue. Thank you for participating.
