### ISSUE TITLE
Entt View iteration failing if all entities destroyed on first step?

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#772]
I feel as though this should be valid code but it appears to fail when iterating  at assert(testReg.valid(ent))
```
  {
    Registry testReg;
    auto ent = testReg.create();
    auto ent2 = testReg.create();
    testReg.emplace<std::pair<EntityType, EntityType>>(ent, std::pair<EntityType, EntityType>{ent,ent2});
    testReg.emplace<std::pair<EntityType, EntityType>>(ent2, std::pair<EntityType, EntityType>{ent,ent2});
    auto view = testReg.view<std::pair<EntityType,EntityType>>();
    for (auto [ent, pair] : view.each()) {
      assert(testReg.valid(ent));
      assert(testReg.valid(pair.first));
      testReg.destroy(pair.first);
      assert(testReg.valid(pair.second));
      testReg.destroy(pair.second);
      assert(view.size() == 0);
      auto sizeReg = testReg.size<std::pair<EntityType,EntityType>>();
      assert(sizeReg == 0);
    }
  }
```

**Comment by pgruenbacher** [comment]
oh this only fails on single-component views by the way... the issue does not appear when using multi-component view.
This definitely seems like a bug to me...

**Comment by skypjack** [comment]
As from the documentation:
> Deleting the current entity or removing its components is allowed during iterations but it could invalidate references. For all the other entities, destroying them or removing their components isn't allowed and can result in undefined behavior.

When you do this:
```cpp
testReg.destroy(pair.first);
testReg.destroy(pair.second);
```
You're literally deleting the entity currently returned by the view **and** a random entity somewhere else within the view itself.
It works for multi type views, you're right, though it isn't guaranteed to work for single type views, thus the warning in the doc. 🙂

**Comment by pgruenbacher** [comment]
Hm yea but I don't think its a reference invalidation issue in this case... cause even if I copy the pair of ids it still fails

```
  {
    Registry testReg;
    auto ent = testReg.create();
    auto ent2 = testReg.create();
    testReg.emplace<std::pair<EntityType, EntityType>>(ent, std::pair<EntityType, EntityType>{ent,ent2});
    testReg.emplace<std::pair<EntityType, EntityType>>(ent2, std::pair<EntityType, EntityType>{ent,ent2});
    auto view = testReg.view<std::pair<EntityType,EntityType>>();
    for (auto [ent, _pair] : view.each()) {
      // copy the pair so that it's not a reference
      auto pair = _pair;
      assert(testReg.valid(ent));
      assert(testReg.valid(pair.first));
      testReg.destroy(pair.first);
      assert(testReg.valid(pair.second));
      testReg.destroy(pair.second);
      assert(view.size() == 0);
      auto sizeReg = testReg.size<std::pair<EntityType,EntityType>>();
      assert(sizeReg == 0);
    }
  }
```

**Comment by skypjack** [comment]
It's not a reference invalidation, indeed. It's an iterator invalidation. Imagine this:
```
last -> [entity-0|entity-1] <- first
```
I don't know if my great graphic skills pay off here 😅 however, `first` points to `entity-1` and iterate backwards while `last` points past `entity-0`.
During the first loop, you delete both the entities because of:
```
testReg.destroy(pair.first);
testReg.destroy(pair.second);
```
So, not only the one currently returned by the iterator but also another one.
Then you advance `first` that points now to an invalid element (that is, `entity-0`). This is the _undefined behavior_ part of:
> Deleting the **current** entity [...] is allowed during iterations [...]. For all the other entities, destroying them [...] can result in undefined behavior.

It works for the currently iterated element because advancing the iterator skips over it. However, randomly deleting entities risks to invalidate iterators.
Multi type views don't suffer from the same problem for _<reasons>_ that have nothing to do with this failure anyway.

**Comment by pgruenbacher** [comment]
Ok so only the **current** id. 
Makes sense thanks for the explanation... its code smell to do it this way anyways... i just suspected it was a bug only because it worked for multi-component views so i assumed same for single-component views.

**Comment by skypjack** [comment]
No worries at all. If you think that the documentation can be improved, feel free to drop a line!
