### ISSUE TITLE
Type qualifiers ignored on cast result type with g++ 10.3

### ISSUE THREAD

**Issue by Evangel63** [skypjack/entt#785]
Getting a warning from inside of `meta_node`'s `static auto *meta_default_constructor` with the `-Wignored-qualifiers` warning flag.

```
In file included from ../co/entt/src/entt/meta/meta.hpp:17,
                 from ../co/entt/src/entt/meta/container.hpp:11,
                 from ../co/entt/src/entt/entt.hpp:33,
                 from ./entt_test.cpp:2:
../co/entt/src/entt/meta/node.hpp: In static member function ‘static auto* entt::internal::meta_node<Type>::meta_default_constructor()’:
../co/entt/src/entt/meta/node.hpp:133:20: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
  133 |             return static_cast<decltype(meta_type_node::default_constructor)>(nullptr);
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

To test, just include `entt/entt.hpp` in a file with an empty main. Doesn't affect performance or functionality, but using the CMake target `EnTT` means they're not treated as system include headers that I normally ignore warnings from.

Happens on both `wip` branch at commit `04b2e1152cb18691207def8d3f8c1c41252f3063` and `master` branch at commit `4b3bd265a67c050884d4a98ec141ed27ce642c67`

**Comment by skypjack** [comment]
Hi, thanks for the heads-up, good catch. Can I ask you to test branch `wip`?
I've added an `std::decay_t` that should suppress the warning. Thanks!

**Comment by Evangel63** [comment]
Confirmed, has been solved.
