### ISSUE TITLE
Question regarding creating a registry wrapper class

### ISSUE THREAD

**Issue by grimaldini** [skypjack/entt#789]
I am currently working on creating a wrapper class to basic_registry, the reason is to reduce access to certain functions and simplify some flows.
One of my attempts is the following, a function to hook on_construct and connect to the signal at the same time:

```
    using F = std::function<void(registrywrapper &, entity)>;
    template <typename Component>
    auto on_create(F f) {
        return _registry.on_construct<Component>().connect([](F &ptr, entt::registry &r, entity e) {
            ptr(r.ctx<registrywrapper>(), e);
        }, &f);
    }
```

However, the problem seems to be that registry creates the signal expecting (entt::registry &, const entt::entity). How can I expand upon this signature and/or pass in a parameter that can be later used (because connect won't allow capturing lambdas). I know I can potentially set some ctx variables in the registry and then access them like I'm doing with ctx<registrywrapper> but I don't think that's a scalable solution for this scenario.

Thanks!

**Comment by skypjack** [comment]
Hi, do you mind if I convert this issue in a _discussion_? I think it's better suited. As for your question:
> How can I expand upon this signature and/or pass in a parameter that can be later used

Signal support is nothing more than a [mixin](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L895). You can just define your own and replace it by specializing the [`storage_traits`](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L1055) class (which is a sfinae-friendly one). The registry is fully transparent to the type returned by `on_construct` and similar, so you don't have to touch it in any way.
Roughly speaking, you can define and set up your mixin that also accepts capturing lambdas and make it return the derived registry to the callbacks. If you want to stick with the current behavior, you can just copy what the `sigh_storage_mixin` does already and only replace the parts of interest (i.e. the [`sigh`](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L1044) type with a list of `std::function`s or similar).

**Comment by skypjack** [comment]
You're welcome. 👍

**Comment by hls333555** [comment]
> Hi, do you mind if I convert this issue in a _discussion_? I think it's better suited. As for your question:
> 
> > How can I expand upon this signature and/or pass in a parameter that can be later used
> 
> Signal support is nothing more than a [mixin](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L895). You can just define your own and replace it by specializing the [`storage_traits`](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L1055) class (which is a sfinae-friendly one). The registry is fully transparent to the type returned by `on_construct` and similar, so you don't have to touch it in any way. Roughly speaking, you can define and set up your mixin that also accepts capturing lambdas and make it return the derived registry to the callbacks. If you want to stick with the current behavior, you can just copy what the `sigh_storage_mixin` does already and only replace the parts of interest (i.e. the [`sigh`](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L1044) type with a list of `std::function`s or similar).

Hi, I have the same issue here, but I am not quite understand how to implement this. In my case, I have an Entity class which encapsulates registry and entity both and I want the callback to my Entity class as the argument... Is it possible? Thanks a lot!

**Comment by skypjack** [comment]
> I want the callback to my Entity class as the argument

Is it the same entity that you store in the registry/pools? Otherwise, how does a pool know about it when it's time to send a signal? 🤔

**Comment by hls333555** [comment]
> > I want the callback to my Entity class as the argument
> 
> Is it the same entity that you store in the registry/pools? Otherwise, how does a pool know about it when it's time to send a signal? 🤔

In fact, what I mean is to change callback signature from (registry&, entity) to entity, and that's enough, as I can outside create  my Entity out of that passed in entity argument.

**Comment by skypjack** [comment]
The question remains the same: it's possible but where the storage is supposed to find a link to the scene?
Cuz from what I get you're still using `entt::entity` under the hood. So, this is what the storage has. It know nothing about th scene itself. How can it construct an `Entity` then? I think I'm missing a piece of your idea here.

**Comment by hls333555** [comment]
> The question remains the same: it's possible but where the storage is supposed to find a link to the scene? Cuz from what I get you're still using `entt::entity` under the hood. So, this is what the storage has. It know nothing about th scene itself. How can it construct an `Entity` then? I think I'm missing a piece of your idea here.

In my situation, I have a System class holding a reference to my Scene. So that I will only register callback in my System and construct my Entity through that Scene reference. As a result, entt::registry is not needed in this case.

**Comment by hls333555** [comment]
> The question remains the same: it's possible but where the storage is supposed to find a link to the scene? Cuz from what I get you're still using `entt::entity` under the hood. So, this is what the storage has. It know nothing about th scene itself. How can it construct an `Entity` then? I think I'm missing a piece of your idea here.

In my situation, I have a System class holding a reference to my Scene. So that I will only register callback in my System and construct my Entity through that Scene reference. As a result, entt::registry is not needed in this case.

**Comment by hls333555** [comment]
> Hi, do you mind if I convert this issue in a _discussion_? I think it's better suited. As for your question:
> 
> > How can I expand upon this signature and/or pass in a parameter that can be later used
> 
> Signal support is nothing more than a [mixin](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L895). You can just define your own and replace it by specializing the [`storage_traits`](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L1055) class (which is a sfinae-friendly one). The registry is fully transparent to the type returned by `on_construct` and similar, so you don't have to touch it in any way. Roughly speaking, you can define and set up your mixin that also accepts capturing lambdas and make it return the derived registry to the callbacks. If you want to stick with the current behavior, you can just copy what the `sigh_storage_mixin` does already and only replace the parts of interest (i.e. the [`sigh`](https://github.com/skypjack/entt/blob/master/src/entt/entity/storage.hpp#L1044) type with a list of `std::function`s or similar).

Is there a step by step way to achieve this? I have a class derived from entt::registry and I do not know how to pass my class around instead of entt::registry as callback argument. Thanks a lot!

**Comment by skypjack** [comment]
Oh, I see. Yeah, there is defniitely a way.
You must define a mixin mostly similar to the `sigh_storage_mixin`. The only difference is that it works with your class rather than the registry class.
Then, you can specialize the `storage_traits` template to use your mixin as a default rather than the `sigh_storage_mixin`. If I remember it correctly, the documentation contains enough details about this. If this isn't the case, feel free to drop a line here and I can help further. 👍

**Comment by hls333555** [comment]
> Oh, I see. Yeah, there is defniitely a way. You must define a mixin mostly similar to the `sigh_storage_mixin`. The only difference is that it works with your class rather than the registry class. Then, you can specialize the `storage_traits` template to use your mixin as a default rather than the `sigh_storage_mixin`. If I remember it correctly, the documentation contains enough details about this. If this isn't the case, feel free to drop a line here and I can help further. 👍

I have tested but I come across a null pointer during bind() call in mixin class:
```C++
class Reg : public entt::registry
{
	
};

namespace entt {
    /**
        * @brief Mixin type used to add signal support to storage types.
        *
        * The function type of a listener is equivalent to:
        *
        * @code{.cpp}
        * void(basic_registry<entity_type> &, entity_type);
        * @endcode
        *
        * This applies to all signals made available.
        *
        * @tparam Type The type of the underlying storage.
        */
    template<typename Type>
    class my_sigh_storage_mixin final : public Type {
        using basic_iterator = typename Type::basic_iterator;

        template<typename Func>
        void notify_destruction(basic_iterator first, basic_iterator last, Func func) {
            ENTT_ASSERT(owner != nullptr, "Invalid pointer to registry");

            for (; first != last; ++first) {
                const auto entt = *first;
                destruction.publish(*owner, entt);
                const auto it = Type::find(entt);
                func(it, it + 1u);
            }
        }

        void swap_and_pop(basic_iterator first, basic_iterator last) final {
            notify_destruction(std::move(first), std::move(last), [this](auto... args) { Type::swap_and_pop(args...); });
        }

        void in_place_pop(basic_iterator first, basic_iterator last) final {
            notify_destruction(std::move(first), std::move(last), [this](auto... args) { Type::in_place_pop(args...); });
        }

        basic_iterator try_emplace(const typename Type::entity_type entt, const bool force_back, const void* value) final {
            ENTT_ASSERT(owner != nullptr, "Invalid pointer to registry");
            Type::try_emplace(entt, force_back, value);
            construction.publish(*owner, entt);
            return Type::find(entt);
        }

    public:
        /*! @brief Underlying entity identifier. */
        using entity_type = typename Type::entity_type;

        /*! @brief Inherited constructors. */
        using Type::Type;

        /**
         * @brief Returns a sink object.
         *
         * The sink returned by this function can be used to receive notifications
         * whenever a new instance is created and assigned to an entity.<br/>
         * Listeners are invoked after the object has been assigned to the entity.
         *
         * @sa sink
         *
         * @return A temporary sink object.
         */
        [[nodiscard]] auto on_construct() ENTT_NOEXCEPT {
            return sink{ construction };
        }

        /**
         * @brief Returns a sink object.
         *
         * The sink returned by this function can be used to receive notifications
         * whenever an instance is explicitly updated.<br/>
         * Listeners are invoked after the object has been updated.
         *
         * @sa sink
         *
         * @return A temporary sink object.
         */
        [[nodiscard]] auto on_update() ENTT_NOEXCEPT {
            return sink{ update };
        }

        /**
         * @brief Returns a sink object.
         *
         * The sink returned by this function can be used to receive notifications
         * whenever an instance is removed from an entity and thus destroyed.<br/>
         * Listeners are invoked before the object has been removed from the entity.
         *
         * @sa sink
         *
         * @return A temporary sink object.
         */
        [[nodiscard]] auto on_destroy() ENTT_NOEXCEPT {
            return sink{ destruction };
        }

        /**
         * @brief Assigns entities to a storage.
         * @tparam Args Types of arguments to use to construct the object.
         * @param entt A valid identifier.
         * @param args Parameters to use to initialize the object.
         * @return A reference to the newly created object.
         */
        template<typename... Args>
        decltype(auto) emplace(const entity_type entt, Args &&...args) {
            ENTT_ASSERT(owner != nullptr, "Invalid pointer to registry");
            Type::emplace(entt, std::forward<Args>(args)...);
            construction.publish(*owner, entt);
            return this->get(entt);
        }

        /**
         * @brief Patches the given instance for an entity.
         * @tparam Func Types of the function objects to invoke.
         * @param entt A valid identifier.
         * @param func Valid function objects.
         * @return A reference to the patched instance.
         */
        template<typename... Func>
        decltype(auto) patch(const entity_type entt, Func &&...func) {
            ENTT_ASSERT(owner != nullptr, "Invalid pointer to registry");
            Type::patch(entt, std::forward<Func>(func)...);
            update.publish(*owner, entt);
            return this->get(entt);
        }

        /**
         * @brief Assigns entities to a storage.
         * @tparam It Type of input iterator.
         * @tparam Args Types of arguments to use to construct the objects assigned
         * to the entities.
         * @param first An iterator to the first element of the range of entities.
         * @param last An iterator past the last element of the range of entities.
         * @param args Parameters to use to initialize the objects assigned to the
         * entities.
         */
        template<typename It, typename... Args>
        void insert(It first, It last, Args &&...args) {
            ENTT_ASSERT(owner != nullptr, "Invalid pointer to registry");
            Type::insert(first, last, std::forward<Args>(args)...);

            for (auto it = construction.empty() ? last : first; it != last; ++it) {
                construction.publish(*owner, *it);
            }
        }

        /**
         * @brief Forwards variables to mixins, if any.
         * @param value A variable wrapped in an opaque container.
         */
        void bind(any value) ENTT_NOEXCEPT final {
            auto* reg = any_cast<Reg>(&value); ////////////////////////////////////////////// Here the returned reg is NULL
            owner = reg ? reg : owner;
            Type::bind(std::move(value));
        }

    private:
        sigh<void(Reg&, const entity_type)> construction{};
        sigh<void(Reg&, const entity_type)> destruction{};
        sigh<void(Reg&, const entity_type)> update{};
        Reg* owner{};
    };

    template<typename Type>
    struct storage_traits<entity, Type> {
        /*! @brief Resulting type after component-to-storage conversion. */
        using storage_type = my_sigh_storage_mixin<basic_storage<entity, Type>>;
    };
}

struct TestComponent {};

static void TestOnConstruct(Reg& reg, entt::entity e)
{	
}

int main()
{
    Reg reg;
    auto entity = reg.create();
    reg.on_construct<TestComponent>().connect<&TestOnConstruct>();
    auto& testComp = reg.emplace<TestComponent>(entity); //////////////////////////////// CRASH here
}
```

**Comment by skypjack** [comment]
I guess this is due to the fact that the registry forwards itself and therefore the type to extract is still `entt::registry`. Then you can static cast it to the derived type.

**Comment by skypjack** [comment]
Although you made me think, I can just make the registry class a template parameter for the `sigh_storage_mixin`. This would get rid of your implementation and make these cases easier to address. 🤔

**Comment by hls333555** [comment]
> I guess this is due to the fact that the registry forwards itself and therefore the type to extract is still `entt::registry`. Then you can static cast it to the derived type.

So I just replace
```C++
auto* reg = any_cast<Reg>(&value);
```
with
```C++
auto* reg = static_cast<Reg*>(value.data());
```
Is that proper way?

**Comment by skypjack** [comment]
No, I mean more something along this line:
```cpp
auto* reg = 
    static_cast<Reg *>( // <-- static cast to your registry type
        any_cast<entt::registry>(&value)) // << any_cast to the entt registry type
    ;
```

**Comment by hls333555** [comment]
> No, I mean more something along this line:
> 
> ```c++
> auto* reg = 
>     static_cast<Reg *>( // <-- static cast to your registry type
>         any_cast<entt::registry>(&value)) // << any_cast to the entt registry type
>     ;
> ```

Thansk!
But I'm wondering if it is possible to change (on_construct, on_update, on_destroy) these signatures from (entt::registry&, entt::entity) to just (entt::entity)?

**Comment by skypjack** [comment]
Oh, yeah, same stuff. Just swap the mixin with one you like and that fits your needs.
You can really customize everything with `EnTT`. [This](https://godbolt.org/z/6oz96Wv6n) is a quick example I packed for you.
There is no way to say _change the signature of the `sigh` mixin for me_ but you can still replace it with your own if you like.

**Comment by hls333555** [comment]
> Oh, yeah, same stuff. Just swap the mixin with one you like and that fits your needs. You can really customize everything with `EnTT`. [This](https://godbolt.org/z/6oz96Wv6n) is a quick example I packed for you. There is no way to say _change the signature of the `sigh` mixin for me_ but you can still replace it with your own if you like.

Thanks. I have tried that already, but my code does not compile when I call registry.group(), maybe something conflict with that?

**Comment by skypjack** [comment]
Oh, yeah, definitely. Groups use signals and **do** require the registry.

**Comment by hls333555** [comment]
> Oh, yeah, definitely. Groups use signals and **do** require the registry.

So in this situation, is it possible to make registry an optional parameter for signal?

**Comment by skypjack** [comment]
No, I'm sorry, it is not. Definitely. It would be possible if it were the last one but I can't make it work since it's the first one here.
