### ISSUE TITLE
internal compiler error when make with gcc version 5.4.0/ubuntu-16.04.9

### ISSUE THREAD

**Issue by seamast** [skypjack/entt#79]
Scanning dependencies of target view
[ 78%] Building CXX object test/CMakeFiles/view.dir/entt/entity/view.cpp.o
/home/user/Repo/entt/test/entt/entity/view.cpp: In instantiation of ‘View_MultipleComponentEachWithHoles_Test::TestBody()::<lambda(auto:31, const char&, const int&)> [with auto:31 = unsigned int]’:
/home/user/Repo/entt/src/entt/entity/view.hpp:895:17:   required from ‘entt::View<Entity, Component>::each(Func)::<lambda(entt::View<Entity, Component>::entity_type, const Component& ...)> [with Func = View_MultipleComponentEachWithHoles_Test::TestBody()::<lambda(auto:31, const char&, const int&)>; Entity = unsigned int; Component = {char, int}; entt::View<Entity, Component>::entity_type = unsigned int]’
/home/user/Repo/entt/src/entt/entity/view.hpp:894:48:   required from ‘struct entt::View<Entity, Component>::each(Func) [with Func = View_MultipleComponentEachWithHoles_Test::TestBody()::<lambda(auto:31, const char&, const int&)>; Entity = unsigned int; Component = {char, int}]::<lambda(using entity_type = using entity_type = unsigned int, const char&, const int&)>’
/home/user/Repo/entt/src/entt/entity/view.hpp:894:9:   required from ‘void entt::View<Entity, Component>::each(Func) [with Func = View_MultipleComponentEachWithHoles_Test::TestBody()::<lambda(auto:31, const char&, const int&)>; Entity = unsigned int; Component = {char, int}]’
/home/user/Repo/entt/test/entt/entity/view.cpp:284:6:   required from here
/home/user/Repo/entt/test/entt/entity/view.cpp:278:19: internal compiler error: Segmentation fault
         if(entity == e0) {
                   ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
test/CMakeFiles/view.dir/build.make:62: recipe for target 'test/CMakeFiles/view.dir/entt/entity/view.cpp.o' failed
make[2]: *** [test/CMakeFiles/view.dir/entt/entity/view.cpp.o] Error 1
CMakeFiles/Makefile2:909: recipe for target 'test/CMakeFiles/view.dir/all' failed
make[1]: *** [test/CMakeFiles/view.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gale93** [comment]
A minimal example to reproduce the crash would help :)

**Comment by skypjack** [comment]
@gale93 Don't worry. I've already fixed it.  
I'm not pushing yet because here the wireless is down right now. :-)

**Comment by skypjack** [comment]
Fixed upstream. Tested with GCC 5.5 that suffers from the same ICE.  
It wasn't an issue of `EnTT` actually. Instead it was an ICE of a quite old compiler.

**Comment by seamast** [comment]
Thanks, it works now.
