### ISSUE TITLE
Issues with some pools and ids across boundries

### ISSUE THREAD

**Issue by Soarex** [skypjack/entt#795]
Hello,
I'm developing a simple game engine with a visual editor using Entt as it's ecs. The idea is to have the user create and register custom components and systems in a separate project, compile it as dll and then dynamically load it in the editor so that the user can add custom components to the entities and test the systems.

I've already read "Push EnTT across boundaries" and implemented the systems to share the meta context and id creation between main code and dll (the last one taken directly from the test suite "registry_plugin") but I've come across some issues.
I've noticed that the custom type_seq generator doesn't get called for two types of components, IdComponent and NameComponent, causing a conflict when I try to add another one(for example, every time a new entity gets created I add an IdComponent, NameComponent and TransformComponent, causing a conflict because the first two call the default generator getting ids 0 and 1 and the last one calls the custom generator getting id 0). At first I fixed it with a quick hack, adding +2 to every id created by the custom generator, but then I noticed a bigger problem.

Essentially, everything is fine from the editor side, but when I try to get IdComponents or NameComponents from the dll (for example with a view) it acts as if the respective pools are empty.
I've tried to understand what's going on, but I wasn't able to come up with anything.

**Comment by skypjack** [comment]
Any updates? Have you tried the `dll` branch?

**Comment by Soarex** [comment]
Hi,
sorry for the lack of feedback, I've been pretty busy this week.
I've tried the dll branch and it worked flawlessly out of the box just as you sad.

**Comment by skypjack** [comment]
No worries at all. I was just curious to know if it worked since I'm about to merge it with master. Thanks for the feedback!
