### ISSUE TITLE
[question] using entt as DLL and custom generator

### ISSUE THREAD

**Issue by xubury** [skypjack/entt#801]
I tried to compile my project as shared library(DLL),  
I wrap entt in a  `ecs.dll`  , the main application and some other dll are link to `ecs.dll`.
But when my main app use those moudles,  entt is not working correctly.
I search for solution and see this on wiki:
https://github.com/skypjack/entt/wiki/Push-EnTT-across-boundaries

So apparently, I have to do something like this in [test/lib/registry_plugin](https://github.com/skypjack/entt/tree/master/test/lib/registry_plugin). 
But I have hard time understanding those code..

Here's what I do to try to follow the example,  which unfortunately is still not working.
Can you tell me where I did wrong? Thanks in advance!
in `main.cpp`
```
#include "type_context.h"

template<typename Type>
struct entt::type_index<Type> {
    [[nodiscard]] static id_type value() ENTT_NOEXCEPT {
        static const entt::id_type value = type_context::instance()->value(entt::type_hash<Type>::value());
        return value;
    }
};

void main() {
  SetContext(type_context::instance());
 // Some operation that call functions in ecs.dll (emplace add remove etc.) 
 // and function in other dll which also use function in ecs.dll
....
}
```
in `ecs.hpp`
```
#if defined(SD_ECS_EXPORT)
#define SD_ECS_API __declspec(dllexport)
#define ENTT_API_EXPORT
#elif defined(SD_ECS_IMPORT)
#define SD_ECS_API __declspec(dllimport)
#define ENTT_API_EXPORT
#else
#define SD_ECS_API
#endif

void SD_ECS_API SetContext(type_context *context);
```

in `ecs.cpp`
```
#include "type_context.h"

struct ctx {
    inline static type_context *ref;
};

template<typename Type>
struct entt::type_index<Type> {
    [[nodiscard]] static id_type value() ENTT_NOEXCEPT {
        static const entt::id_type value = ctx::ref->value(entt::type_hash<Type>::value());
        return value;
    }
};

void SetContext(type_context *context) {
    ctx::ref = context;
}
```

**Comment by skypjack** [comment]
Given that we're very close to the next release, my suggestion is to refer to the `experimental` branch. It contains the changes necessary to make EnTT work transparently across boundaries.
This branch _may_change but it's mostly stable when we're about to cut a new release. This way you won't have to struggle now and change it in a month. My two cents. 🙂

**Comment by xubury** [comment]
Yes, thanks! `exprimental` branch works. I guess I can settle for static linking for now.

**Comment by skypjack** [comment]
Dunno about your deadlines but yeah, the next release should be available soon.
