### ISSUE TITLE
Looping each entity component

### ISSUE THREAD

**Issue by marvkey** [skypjack/entt#802]
In my project I want to be able to loop through the current entity and each of its components, it would really be a good feature if the team or someone out there is able to implement it.

**Comment by skypjack** [comment]
Hi, the upcoming version has a visit function that returns you the storage for all components owned by an entity.
Keep in mind that types are erased within the registry. Therefore, what you get is a reference to the storage base class.
You have a `type_info` and you can get a `void *` to a component from it. Dunno exactly what your expectation is.

**Comment by marvkey** [comment]
Thank you so much I think that should be enough for me can not wait for the new version.

**Comment by skypjack** [comment]
Well, technically speaking, you can already find what you're looking for on branch `experimental`.

**Comment by marvkey** [comment]
Oh I will check that out, and when will the new version be released on the main branch.
