### ISSUE TITLE
Changing ID Type

### ISSUE THREAD

**Issue by marvkey** [skypjack/entt#803]
I am making a project and I want my ID type of my entities to be uint64_t not uint32_t. I changed the entity default ID type to uint64_t and it seems to break the whole library, memory leaks and the valid function never returns true even though the ID does not exist. I have also tried crating my own alias of the entity registry but that does not work I still get the same problem.

**Comment by skypjack** [comment]
What version are you using? `master` is currently tested with 64b identifiers and also runs under a sanitizer, therefore I'm pretty confident about it. However, I remember there was an issue a while ago, so maybe you got it on an older version?

**Comment by marvkey** [comment]
I am using the single include entt file on the master branch

**Comment by marvkey** [comment]
I changed to src/entt and I was able to use a normal uint64_t as an ID everything is working fine but when I try to use view on a component I get this error 
![image](https://user-images.githubusercontent.com/67913666/144949826-4a443da0-23f1-4297-8280-2da5b79aa7cb.png)

**Comment by marvkey** [comment]
I think the bug came with this piece of code in the view.hpp file, I commented it and my project seems to be working fine.
![image](https://user-images.githubusercontent.com/67913666/145058820-82ea57ec-c089-49fc-a67c-cca4b83a1bb0.png)

**Comment by codylico** [comment]
It seems like the entity type (`uint64_t`) and the size type are clashing. So either the entity-based lookup or the index-based lookup can work in 64-bit, but not both.

https://github.com/skypjack/entt/blob/0ec763131043647d4c64fb1f6274da12c898b0ca/src/entt/entity/view.hpp#L828

**Comment by skypjack** [comment]
That's odd though. Entity type isn't `std::uint64_t`. Instead, it's an enum class type the underlying type of which is `std::uint64_t`. Unless... how did you change the entity type? Maybe that is the culprit here?
