### ISSUE TITLE
Sink fails to compile with 3.9.0 single_include file 

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#814]
```
entt::sigh<void(int)> sigh;
entt::sink sink{sigh};
```
This code won't compile with the following error on vs 2022:
Argument list for class template entt::sink is missing.
Please help. Thank you!

**Comment by skypjack** [comment]
Mmm this seems an issue of VS2022. This code is perfectly valid from what I see.
I don't have a working copy of VS2022 at the moment but maybe this fixes the error?
```cpp
entt::sigh<void(int)> sigh;
entt::sink<entt::sigh<void(int)>> sink{sigh};
```

**Comment by hls333555** [comment]
> Mmm this seems an issue of VS2022. This code is perfectly valid from what I see. I don't have a working copy of VS2022 at the moment but maybe this fixes the error?
> 
> ```c++
> entt::sigh<void(int)> sigh;
> entt::sink<entt::sigh<void(int)>> sink{sigh};
> ```

Thanks! That works!
