### ISSUE TITLE
Conditional triggering updates when using `patch`

### ISSUE THREAD

**Issue by Naios** [skypjack/entt#817]
Thank you for your awesome library!

I stubled across the use case, that I want to debounce updates to the storage such that `on_update` is not fired if the component is not updated through `patch`, or a specified condition is not satisfied.

This has the benefit over `get` (and update) followed by an eventual patch that we dont have to double look-up the storage and entity. Something like the following snippet where we return true or false from the callback that updates the component to indicate a change:

```cpp
registry.patch<MyComponent>(id, [](MyComponent& comp) {
  return true; // Or false if the component was not updated, then the on_update event should not be fired.
});
```

A more expensive workaround implementation of the behaviour described above would be something like this:

```cpp
template <typename Component, typename Callback>
void maybe_patch(entt::registry& reg, entt::entity id, Callback&& callback) {
  Component& comp = reg.get<Component>(id);

  if (std::forward<Callback>(callback)(comp)) {
    reg.patch<Component>(id, [](Component&) {});
  }
}
```

Sadly it is not possible to implement the optimized solution because `sigh_storage_mixin<basic_storage<Entity, Type>>` only exposes the `sigh` as an attachable sink without making it possible to trigger the signal manually (the signal itself is private).
Making it possible to trigger the `on_update` signal would be advantageous for other use-cases as well where we inform the registry through an update made via mutable `view` or `group` iteration.

Do you know of any other possibility to implement this behaviour in a straight forward way?

**Comment by Green-Sky** [comment]
I my experience using an empty patch `reg.patch(e)` is sufficiently performant, because the callback should get optimized away...
If you want to know about more optimized data structures of tracking change, I suggest you read https://ourmachinery.com/post/syncing-a-data-oriented-ecs/ , it has some examples.

**Comment by Naios** [comment]
Thank you for your quick response, calling `patch` with no callback is probably the intended way of solving my issue.
The article seems really interesting and I will definitly get deeper into it.
