### ISSUE TITLE
[bug] Calling registry.view<...>() after the registry has been moved causes  is_power_of_two(mod) failure.

### ISSUE THREAD

**Issue by GavinNL** [skypjack/entt#819]
If you std::move the contents of registry from A to B, Calling `A.view< >()`  will fail instead of returning an empty view. 

Looks to be an issue with dense_hashmap, bucket_count() is returning 0.

Here's a demonstration of the problem on version 3.9 vs 3.6. It works on 3.6
https://godbolt.org/z/Eah4nxGGr

**Comment by skypjack** [comment]
A dense hash map and thus a registry are put in a valid but unspecified state when moved from.
Roughly speaking, you're guaranteed that the destruction won't cause problems but there is no guarantee on their use.

This is a simplified version of your snippet:
```cpp
entt::registry R1;
entt::registry R2 = std::move(R1);
(void)R1.view<comp>(); // fails. R1 should technically be empty
```
Despite the expectation, `R1` should not be _technically empty_. It should be (and actually is) in a valid but unspecified state.
Therefore, what you're doing is technically UB and so it was even before. Like any other UB, the fact that it used to work as expected (v3.6) and now it no longer does (v3.9) is completely irrelevant.

**Comment by GavinNL** [comment]
Okay, sounds good! Feel free to close this issue
