### ISSUE TITLE
Hotreloading of dlls

### ISSUE THREAD

**Issue by firesgc** [skypjack/entt#828]
Hello!

In my game engine I use entt along with dll plugins that I can hotreload. The game engine keeps the entt::registry, but the plugins are able to add custom components to it. The state of the plugins is stored in components and added to entt::registry so that I can keep the current game state when I hot reload a plugin.

For this reason I have problems with static variables as in type_info.hpp ln 258: 
`static type_info instance{std::in_place_type<std::remove_cv_t<std::remove_reference_t<Type>>};`.
In this function a reference to a static variable is returned and basic_any stores a pointer to it.

When a dll is unloaded, all static variables of that dll are removed and the pointers to the type_info are dangling. I changed the code and instead of saving a pointer to the static variable, I always make a copy, which seems to solve my problem (in any.hpp ln 392, the type_info is no longer a pointer).

I know my use case is a little bit special, but is there a better way to handle this problem?

Thank you very much!
Cheers

ps:
I am aware that any change to a component (e.g. adding/removing an element) will result in undefined behavior when I reload the plugins, but that's fine. Many tasks don't need to touch the data structures.

**Comment by skypjack** [comment]
Hi @firesgc I must admit that the built-in rtti system is designed to stay close to the standard one. In this case, `typeid` returns a reference to an object with static storage duration and here we are. 🤷‍♂️🙂 
There is also another advantage actually. The `type_info` object is much larger than a pointer and it may grow in future. Therefore, returning a const reference and storing aside pointers gives some guarantees. Your change makes all `any`s and all types that rely on a `type_info` bigger at once instead.

> I know my use case is a little bit special, but is there a better way to handle this problem?

Is it? I may have overlooked this case but we could make it feasible. I'm not saying even _user-friendly_ 😅 but at least not impossible to get without changes to the library.
If you had a way to specialize the rtti system, you could do it in plugins and have them ask or register `type_info` objects on the main executable. At the end of the day, a `type_info` object is a triplet of values. If you could explicitly register it, then specialize `type_id` to _ask others_, would that work?

**Comment by firesgc** [comment]
I did further testing and the `vtable` in `basic_any` (in any.hpp) references a local function that is also unloaded with the DLL. The `vtable` is also used in meta.hpp and I'm a little afraid that there are many more places I would need to change to get hot reloading to a working state :/

About the problem with `basic_any` (info and vtable point to code/data that has been unloaded):
Maybe it would be an option to add a "(re)-register" function to the registry that is called by the plugin and updates the `type_info` and the `vtable` of basic_any? The hash should be the same, so I can probably find the appropriate entries.

I don't see how I can fix the vtable problem, without registration and updated function.

What do you you think about this?

**Comment by skypjack** [comment]
> I did further testing and the vtable in basic_any (in any.hpp) references a local function that is also unloaded with the DLL. The vtable is also used in meta.hpp and I'm a little afraid that there are many more places I would need to change to get hot reloading to a working state :/

I suspect that a non-static vtable wouldn't really change anything here. You still have a pointer to member into a dynamic object. Am I wrong?

> About the problem with basic_any (info and vtable point to code/data that has been unloaded):
Maybe it would be an option to add a "(re)-register" function to the registry that is called by the plugin and updates the type_info and the vtable of basic_any?

What version of EnTT are we talking about? The latter uses `any` only for context variables. Is it? I'm still trying to figure out what's causing you the problem.

> I don't see how I can fix the vtable problem, without registration and updated function.

Hot reloading works well with data, ie component definitions but a little less with logic, especially if you _push_ that logic through a boundary and expect to use it on the other side, no matter what.
I'd like to help you because I find the problem interesting but I need more details about what you're doing and where it causes problems. I must admit that I don't have a full picture yet, I'm sorry.

**Comment by firesgc** [comment]
I have done small testcase, so it is easier to talk about the issue.
(I use Windows, I don't know if shared libraries behave completely differently on other platforms.)

[tstcase.zip](https://github.com/skypjack/entt/files/7935024/tstcase.zip)

**Comment by skypjack** [comment]
Yeah, thanks. I see what you mean now. Makes sense.
Imho there exists a solution to have the cake and eat it but it requires some changes to the codebase.
That is, I don't want to copy the whole `type_info` object all the times, it's a waste for 90% of applications. On the other hand, I'd like to make it possible for when you need it.
This would solve the problem with `any`, `meta_any` and the storage. However, keep in mind that meta is all about static stuff currently (see [here](https://github.com/skypjack/entt/blob/master/src/entt/meta/factory.hpp#L550) for example). Therefore, you can use it across boundaries but you'll have bad times if you want to hotreload without destroying `meta_any`s and `meta_type`s created from the dll.

**Comment by firesgc** [comment]
Currently I'm thinking of a "hacky" solution to my problem and don't call FreeLibrary() so the old code and memory are still there, but bind the API to the newly loaded dll. This will cause memory leaks and might cause some confusion, but is probably more stable.... 

It's a really specific problem and probably 99% of all entt users will never have a problem with it, so no point spending much time on it!

Thank you for your thoughts on this!

**Comment by skypjack** [comment]
Well, hot reloading is quite common in fact. So, why not? 🙂
I'll give my idea a try and let you know. In the worst case, I'll fail miserably and nothing will change. 😅

**Comment by firesgc** [comment]
Another task for the backlog :)
Please let me know if you did something to solve the problem.
