### ISSUE TITLE
Is there a way to deduce the unupdated (the opposite of entt::observer)?

### ISSUE THREAD

**Issue by Sonolil** [skypjack/entt#835]
So far I'm digging the observer design but there's a case where I also need to iterate the unupdated. Is there a way to know if an entity has been updated or not while iterating the entire view?

I know this seems really strange in hindsight but I just don't want to populate my classes with unnecessary variables and sometimes I only want to iterate the unupdated.

**Comment by skypjack** [comment]
There is not actually. If you don't update it, nothing happens. How can one track that _nothing has happened_? 🤔 
Though, you can maybe use the `is_updated` tag as a filter in a view and therefore get the non-updated entities this way.

**Comment by Sonolil** [comment]
You're right, I'm content with the tag method. Thank you

**Comment by Sonolil** [comment]
Hi, sorry again but this is a related question. Is there a remove_if algorithm equivalent for entt? A passage in the sorting section implies I can create a custom sort function object so there must be a way to use this to send all deletable elements to the back?

**Comment by skypjack** [comment]
Mmm it sounds to me like an XY-problem. Can I ask you what you're trying to achieve? Maybe there is a more EnTT-y way of doing it.

**Comment by Sonolil** [comment]
Not much really, I actually just got it done. I am reloading certain components based on whether my file is modified or not. I serialize a registry and a map of entities, with relative path to my root folder as its key, and use that to compare file write time and data. I deserialize the registry and map, iterate through the root folder and update entitiy states with existing keys in my map, then reiterate the file data view to remove the none-existing ones. 

I couldn't find reference for the is_updated tag so I just attached a filedata component which also contains the write time and other info. This was all fine except I needed to detect erased files as well and destroy entities with invalid filepath. I was just hoping I could do ranged destruction on the eraseables as if with std::removed_if algorithm. I just found out I can destroy while iterating through my views so this isn't urgent but I still wonder if this is possible.

**Comment by skypjack** [comment]
Oh, no, sorry, the `is_updated` component doesn't exist, it was just a hint on a possible solution. 😅 
I see what you want now. `remove_if` just iterates the container and _moves_ things to the end, then you've to use `erase`. With a view, you combine the two as you did. That's perfectly fine.

**Comment by Sonolil** [comment]
Oh, I didn't realize that was possible, thank you! I was thinking of using the algorithm on the pool itself rather than the view entities. Does the ranged destroy optimize itself in this regard? I've never used it before

**Comment by skypjack** [comment]
Yeah, range functionalities perform better in general, especially if you use iterators from storage classes or single type views (because of an internal machinery that helps to further optimize this case).

**Comment by Sonolil** [comment]
That settles all concerns. I've been enjoying entt very much, it pretty much dominates every part of my source code. Thank you for making ECS in c++ easier for us.

**Comment by skypjack** [comment]
I'm glad to know that you're enjoying the library. 🙂 
Let me know if you've any other questions. Otherwise, I'll close the issue soon. Thanks. 👍
