### ISSUE TITLE
How can I lock components so they can be used between threads ?

### ISSUE THREAD

**Issue by vertexpotato** [skypjack/entt#836]
I have a multiplayer open world game that has  2 threads, a render thread and a world thread. Both threads access the same entt:registry

The render thread iterates transform components and sprite components each frame and getting data from them.

The world thread on the other hand, handles the world streaming, whenever a new chunk arrives from the server the world thread handles the packet and creates the entities inside that chunk.

Now with this approach, the game crashes because while the world thread is creating entities and accessing component pools, the render thread is trying to access the same pool at the same time so a crash occurs inside entt telling me that a view doesn't contain entity.

any idea on how can I lock components until after the world thread is done with them ?

**Comment by skypjack** [comment]
EnTT doesn't offer a built-in mechanism for locking a component, mainly because you can easily implement it on top of what it offers and also achieve better results.
As for you specific case, I'd consider a few options probably:

* Create a cold copy of the components for the renderer. If it's only about two component types, it may worth it rather than using mutexes or the like everywhere to control accesses. Remember that EnTT offers named and runtime pools, thye look like a good option for this.

* Add a mutex to the registry context and make your systems use it. Otherwise, inherit from the registry itself and do something similar.

* Add a mixin to the transform and sprite pools and make it use a local mutex to control all accesses.

Can any of these work for you? The former is imho the simplest and I dare to say likely the most effective. Though, it's probably a matter of tastes, so let me know what are your thoughts. 👍

**Comment by vertexpotato** [comment]
> EnTT doesn't offer a built-in mechanism for locking a component, mainly because you can easily implement it on top of what it offers and also achieve better results. As for you specific case, I'd consider a few options probably:
> 
>     * Create a cold copy of the components for the renderer. If it's only about two component types, it may worth it rather than using mutexes or the like everywhere to control accesses. Remember that EnTT offers named and runtime pools, thye look like a good option for this.
> 
>     * Add a mutex to the registry context and make your systems use it. Otherwise, inherit from the registry itself and do something similar.
> 
>     * Add a mixin to the transform and sprite pools and make it use a local mutex to control all accesses.
> 
> 
> Can any of these work for you? The former is imho the simplest and I dare to say likely the most effective. Though, it's probably a matter of tastes, so let me know what your thoughts are. 👍

Hi, thanks for your response and your work on this amazing ECS :)

using mixins and mutexes would require me to do a lot of refactoring for my engine, same goes with inheriting from the registry so it would just complicate things, and, as you said it might not be the most effective way.

as for creating cold copies it sounds good  because my components are small. but I don't really know how to implement it, because the only way I used EnTT so far is by just creating views and iterating them each frame. can you please point me to the right docs or provide code example ?

**Comment by skypjack** [comment]
There are a few ways to do it. Something along this line maybe?
```cpp
auto &view = registry.view<transform>();
auto &copy = registry.storage<transform>("tcopy"_hs);

copy.clear();
copy.insert(view.begin(), view.end(), view.storage().begin());
```
Then you can use the copy in your rendering system as:
```cpp
entt::basic_view view{registry.storage<transform>("tcopy"_hs)};
for(auto [entt, transform]: view) { ... }
```

**Comment by chengts95** [comment]
I think the better way is to use something similar to a command buffer in unity ECS.  That is to say, instead of locking whole data, locking certain synchronous operations is better. And it depends on how the task is allocated to multiple threads.

**Comment by vertexpotato** [comment]
> There are a few ways to do it. Something along this line maybe?
> ```cpp
> auto &view = registry.view<transform>();
> auto &copy = registry.storage<transform>("tcopy"_hs);
> 
> copy.clear();
> copy.insert(view.begin(), view.end(), view.storage().begin());
> ```
> Then you can use the copy in your rendering system as:
> ```cpp
> entt::basic_view view{registry.storage<transform>("tcopy"_hs)};
> for(auto [entt, transform]: view) { ... }
> ```
> Let me know if you've any doubts. 👍 

When using ```copy.insert()``` how would I make sure that the component being inserted isn't being accessed by the other thread ?

**Comment by skypjack** [comment]
That's the only sync point in the whole process. That is for example:
* generate new transforms
* sync
* generate copy
* spawn multiple threads

Then it's up to you to use all things correctly as you would to with any other data structure.
Your question isn't different from asking _how do I know that a second thread won't access the `std::vector` that I'm modifying on the main thread?_

**Comment by vertexpotato** [comment]
> That's the only sync point in the whole process. That is for example:
> 
>     * generate new transforms
> 
>     * sync
> 
>     * generate copy
> 
>     * spawn multiple threads
> 
> 
> Then it's up to you to use all things correctly as you would to with any other data structure. Your question isn't different from asking _how do I know that a second thread won't access the `std::vector` that I'm modifying on the main thread?_

I have fixed the problem by using a condition variable to lock the world thread when the render thread tries to access the pools, therefore I could create my copies, thank you for your advice it was really helpful 😃
