### ISSUE TITLE
Entt dispatcher

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#84]
Hello

I was looking @EnTT few weeks ago and i was thinking of using Bus/BusEvent etc, those files are not here anymore, and i was trying to use the entt::Dispatcher so, unfortunately he doesn't compile since you need to take template argument and in your examples you didn't

Best Regards.

error C2955 on MSVC  with an `entt::Dispatcher dispatcher_`

edit: i use entt::ManagerDispatcher now and it's work, but have to update your documentation, because it's not evident.

**Comment by Milerius** [comment]
https://github.com/skypjack/entt/blob/master/test/entt/signal/dispatcher.cpp use entt::Dispatcher without template

**Comment by skypjack** [comment]
It looks correct indeed. Are you using v2.5.0? In this case, you should refer to the [online documentation](https://skypjack.github.io/entt/) for the latest stable release or the inline documentation, *not* to the README file shown on GitHub. The latter is picked up from `master` and `Dispatcher` doesn't take template arguments anymore on `master` actually.

**Comment by Milerius** [comment]
yeah i use vcpkg with your project so 2.5.0, that's why i'm confuse, because i want to use Bus, but it's not here anymore so i dont know for the next release

**Comment by skypjack** [comment]
Got it. Well, for v2.5.0, please, refer to the online documentation, **not** to the README file on `master`.  
`Bus` won't be anymore part of `EnTT` as well as `Signal`. I would discourage using the `Bus` class, it wasn't as safe as I would it to be and honestly there are some other tools in `EnTT` that are much better.

**Comment by skypjack** [comment]
I'm closing this issue because it's invalid. You are using a tagged version while referring to the documentation from `master`.  
Feel free to continue the discussion here anyway if you have any question.
