### ISSUE TITLE
Entity already has component error when creating more than ~1m entities

### ISSUE THREAD

**Issue by GeorgeAzma** [skypjack/entt#841]
I have a this setup in "Entity" class:
```
template<typename T, typename... Args>
	T& addComponent(Args&&... args)
	{
		ASSERT(!hasComponent<T>(), "Entity already has specified component");
		return scene->registry.emplace<T>(entity, std::forward<Args>(args)...);
	}
```
But assertion fails when I have ~1m+ entities, I have no clue why, here are some details:

I add to each entity ~4 components
Entities are stored like so: `std::vector<std::shared_ptr<Entity>> entities;`
I resize entities vector to 2m, iterate over all the entities, where I create them and assign them some components like this:
```
entities.resize(2000000);
for (size_t i = 0; i < entities.size(); ++i)
{
    entities[i] = scene->createEntity();
    entities[i]->addComponent<TransformComponent>(mat4(1));
    entities[i]->addComponent<SpriteComponent>(0);
    entities[i]->addComponent<ColorComponent>(vec4(1));
    entities[i]->addComponent<MeshComponent>(rectangle);
}
```
scene->createEntity() just creates entity shared ptr using registry.create(), not much else
It fails on 1048576th (2^20) entity
"Entity" contains entt::entity handle and Scene* (Scene is just entt::registry), so not much can go wrong here
Am not destroying/adding any more entities this is all that's happening (am updating entities, but nothing fails there it just calls registry.patch())
Here is hasComponent():
```
template<typename T>
	bool hasComponent() const
	{
		return scene->registry.any_of<T>(entity);
	}
```

Thats all the relevant info I think

**Comment by GeorgeAzma** [comment]
I think someone fixed it by using uint64_t as entt::entity type instead of uint32_t in the old version, but I can't see why uint32_t only supports 2^20 entities.

**Comment by skypjack** [comment]
> assertion fails when I have ~1m+ entities, I have no clue why

The id type is `std::uint32_t` by default and it only reserves 20b for the entity (in fact, you've `(2^20 - 1)` entities because `0xF...F` is also reserved), while 12b are used for the version.
If you want more than 1M entities, you've two options:
* The simplest one: use `std::uint64_t` instead (as described [here](https://github.com/skypjack/entt/wiki/Crash-Course:-configuration#entt_id_type))
* The slighlty more complex one: define your own entity type that inherits from `std::uint32_t` and specialize the `entt_traits` class to use more than 20b for the entity

**Comment by GeorgeAzma** [comment]
Thanks for quick reply am not sure about those 12b usage, but that solves my problem, thanks, I will try define my own entity type

**Comment by skypjack** [comment]
That's pretty simple. Imagine to create an entity and to store it's identifier aside. Then you delete it and create a new one. The id is recycled but with a different version. So, technically speaking, you've the same _entity_ but different versions and therefore you've different identifiers.
If you want to know more about why recycling entities is important, [this](https://skypjack.github.io/2019-05-06-ecs-baf-part-3/) blog post can help. 🙂

**Comment by GeorgeAzma** [comment]
Thanks for your activity that explains it, I'd sponsor if I had money, maybe later someday, do you have any reference where they create custom entity?

**Comment by GeorgeAzma** [comment]
But that would require changing entt internal code?

**Comment by GeorgeAzma** [comment]
I use cmake so I sometimes delete vendor folder (where entt lays) for testing porpuses, so that's not a good solution for me
