### ISSUE TITLE
New entity IDs increasing rapidly when deleted from registry. Is this expected?

### ISSUE THREAD

**Issue by omgitsaheadcrab** [skypjack/entt#843]
I added some debugging to a game I'm writing and stumbled upon some strange behavior with entity IDs.

No destroys:
```  
entt::registry registry;

for (auto _ = 10; _--;) {
  auto entity = registry.create();
  std::cout << static_cast<int>(entity) << "\n";
}
```
``` 
0
1
2
3
4
5
6
7
8
9
```

Destroy each entity:
```  
entt::registry registry;

for (auto _ = 10; _--;) {
  auto entity = registry.create();
  std::cout << static_cast<int>(entity) << "\n";
  registry.destroy(entity);
}
```
``` 
0
1048576
2097152
3145728
4194304
5242880
6291456
7340032
8388608
9437184
```

Destroy every other entity:
```  
entt::registry registry;

for (auto i = 10; i--;) {
  auto entity = registry.create();
  std::cout << static_cast<int>(entity) << "\n";
  if (i % 2) {
    registry.destroy(entity);
  }
}
```
``` 
0
1048576
1
1048577
2
1048578
3
1048579
4
1048580
```

This makes me think it's burning through entities very quickly when destroy is called, presumably up to `uint_32`.

**Comment by skypjack** [comment]
That's due to the version which is increased when you destroy an identifier. If you look at its entity part (using `entt::to_entity(identifier)`), you can see that entities are recycled and otherwise generated in order.

**Comment by skypjack** [comment]
You can find some details [here](https://skypjack.github.io/2019-05-06-ecs-baf-part-3/) if you're interested. 👍

**Comment by omgitsaheadcrab** [comment]
Aha, cool! Didn't know about the blog either, will definitely keep an eye on that
