### ISSUE TITLE
Context variables assertion failure in fast_mod on macOS

### ISSUE THREAD

**Issue by dolphineye** [skypjack/entt#846]
Hi,

We have recently migrated EnTT from the v3.8.1 to the v3.9.0 and we are now having an issue with the context variables on `macOS Big Sur 11.6.2 (20G314)` and `Xcode 13.0.0` in the `fast_mod` function where it claims that `value` is non power of two. We have also tested with the HEAD revision, with no avail.

```cpp
[[nodiscard]] inline constexpr std::size_t fast_mod(const std::size_t value, const std::size_t mod) ENTT_NOEXCEPT {
    ENTT_ASSERT(is_power_of_two(mod), "Value must be a power of two");
    return value & (mod - 1u);
}
```

Here is our context variable's structure if that helps (I have renamed the variables for project secrecy reasons):

```cpp
struct Context {
    TypeA *ptrA;
    TypeB *ptrB;
    TypeC *ptrC;
    TypeD *ptrD;
    TypeE *ptrE;
    TypeF *ptrF;
    TypeG *ptrG;
    TypeH *ptrH;
    TypeI *ptrI;
    TypeJ *ptrJ;
};
```

Also you'll find bellow part of our callstack (I cannot disclose it fully at this point for project secrecy reasons):

![image](https://user-images.githubusercontent.com/31071122/154523813-fb2a865a-5e31-4ccc-8080-d779046f879c.png)

After further investigation, it looks like this problem is affecting other types of context variables. There might be a chance this is actually affecting all of them. 

Are we doing something wrong?

Thanks for your help and let me know if you need any additional information regarding this issue!

**Comment by skypjack** [comment]
It's actually super hard to track it down without a repro **but** I'll try if you promise to ping me again when the time to disclose arrives. :)

My guess is that you're adding your context variables to a moved from registry.
This is more or less what I would expect from it.

**Comment by skypjack** [comment]
🤔 Interesting. Then yes, a repro would help. I've no idea how you get it, so I don't know how to help you. I'm sorry.

**Comment by dolphineye** [comment]
@skypjack Since I was unable to reproduce in a self contained macOS application, I assumed something was somewhat wrong in our project. I was also not able to reproduce the issue on our CI's test machines either.

_As for the breaking news, it appears that doing a clean build after upgrading EnTT just solved the issue._

I'm going to close this issue, and will eventually reopen it if the issue appears again ;)

Thank you for helping!
