### ISSUE TITLE
Check whether a type is free for use in a group

### ISSUE THREAD

**Issue by samaursa** [skypjack/entt#847]
This is useful to avoid an `assert` and a crash if someone adds a component to a group that is already in another group. It's useful in all cases, but especially so in large codebases where it is not obvious who 'started' a group.

**Comment by skypjack** [comment]
Correct me if I'm wrong but what you want isn't a way to know if a group exists. Instead, you need a way to know if a type is _free_ to use for another group. Am I wrong?

**Comment by samaursa** [comment]
Yes, you're right.

**Comment by skypjack** [comment]
Then `registry::sortable` returns exactly this information. I agree that the naming doesn't really help. 😅

**Comment by samaursa** [comment]
Thanks! I see why it's named that way.

**Comment by skypjack** [comment]
I'm open to suggestions to change its name. 🙂

**Comment by samaursa** [comment]
`registry::sortable` makes sense as well, especially if you want to make it more general (perhaps in the future some other feature can make a component unsortable and not just because it's in a group)

maybe an alias `registry::groupable` would be useful

**Comment by skypjack** [comment]
I think it's more about the _state_ of the storage rather than the functions that it offers. That is, I'd probably change it to something like `::owned<T>`. Does it make sense?

**Comment by samaursa** [comment]
sorry, I didn't reply - yes, that makes sense ty!
