### ISSUE TITLE
Question: How deterministic is EnTT (ECS side)?

### ISSUE THREAD

**Issue by DragonJawad** [skypjack/entt#856]
Context: This is a probing question to see how much effort I need to put into a sync system between a server and clients (or in other network models)

Hope everything's going well @skypjack! Have a broad but hopefully not too broad question on EnTT:

How deterministic is the ECS aspect of the library exactly? Specifically...
- If `entt::registry` is provided with the exact same inputs on the same architecture, will it result in identical state? (Such as entity ids and entity + component order)
  - Assuming there's no `<random>` usage or other sources of noise as well
- Would the order when looping via `registry::view` ever differ, assuming groups and sorts are either completely unused or identically used in the same way (ie, same order of calls and relevant inputs on the same machine)?
- Cross-platform determinism: To the best of your knowledge, would any of the above differ across various architectures? Eg, if a simulation on two very different architectures are using EnTT in "equivalent" fashion (at least in order of calls and otherwise identical inputs to `entt::registry`), would they always result in the same order of execution for views + identical entity ids and internal component order + otherwise roughly the same (observable) state?

I've seen a few interesting mentions in other question issues - eg, #24 and #161 - but from a quick skim, they don't seem to answer the above question. Thus I'm interested in learning more about EnTT's determinism before I over- or under-engineer some relevant mechanisms =)

**Comment by skypjack** [comment]
Interesting question. In general:

* If `entt::registry` is provided with the exact same inputs on the same architecture, it results in identical state.
* Would the order when looping via `registry::view` ever differ [...]? No but this derives from the previous question actually.
* Cross-platform determinism: To the best of your knowledge, would any of the above differ across various architectures? Yes.

As for the third question, you can make it fully deterministic if you like but it may differ out of the box.
Briefly, EnTT uses `PRETTY_FUNCTION` and `FUNC_SIG` to _create_ an identifier for a given type and the major compilers return different values sometimes.
This could affect for example the order of iteration of the pools when destroying an entity. It never affects the order of iteration of the entities when iterating a view though.

Like everything else in EnTT, you have control over this part too. In fact, everything in the type info system is customizable. 👍

**Comment by DragonJawad** [comment]
Interesting, this almost certainly means I have less work ahead of me than I thought and multiple options to knowingly modify the relevant parts of EnTT here as needed.

Thank you for the detailed response! This'll definitely come in handy ^_^
