### ISSUE TITLE
poly and inherited noncopyable struct issue

### ISSUE THREAD

**Issue by skaman** [skypjack/entt#863]
Hi,
I stumbled in a problem with entt::poly when i tried to inherit a non copyable class for disable copy.

In the example below there are 2 structs. One that inherit NonCopyable (`struct ItNotWork`) and another one that delete the copy constructor without inherit anything (`struct ItWork`).

The code compile fine in both cases, but in runtime the ItNotWork struct fail when try to run the test() method. To me, with my limited knowledge, it look like there is some wrong value into the vtable.

Tested with compiler MSVC 19.31.31105.0

```c++
#include <entt/entt.hpp>

struct NonCopyable {
  NonCopyable() = default;
  NonCopyable(const NonCopyable &) = delete;
  NonCopyable &operator=(const NonCopyable &) = delete;
};

struct TestI : entt::type_list<> {
  template <typename Base> struct type : Base {
    void test() { this->template invoke<0>(*this); }
  };

  template <typename Type> using impl = entt::value_list<&Type::test>;
};

struct ItNotWork : TestI, NonCopyable {
  auto test() -> void { std::cout << "It doesn't work" << std::endl; }
};

struct ItWork : TestI {
  ItWork() = default;
  ItWork(const ItWork &) = delete;
  ItWork &operator=(const ItWork &) = delete;

  auto test() -> void { std::cout << "It work" << std::endl; }
};

auto main() -> int {
  entt::poly<TestI> test{};

  test.emplace<ItNotWork>();
  test->test();   // fail here

  return EXIT_SUCCESS;
}
```

**Comment by skypjack** [comment]
This is interesting actually. From a quick test, it only happens with MSVC. Clang as well as gcc and clang-cl work just fine instead.
As it stands, it looks like an MSVC bug rather than an EnTT issue. Not sure what we can do about it or if we should do anything. Especially if there is an alternative solution already.

**Comment by skaman** [comment]
I agree, I don't think it's a real problem. The problem happen only with a non copyable empty struct, I tried to add a member variable into the NonCopyable struct (just for test) and it compile correctly even with MSVC. Example:

```c++
struct NonCopyable {
  NonCopyable() = default;
  NonCopyable(const NonCopyable &) = delete;
  NonCopyable &operator=(const NonCopyable &) = delete;

  int justSomeValue;
};
```

The problem is just limited in this edge case (an empty class/struct used to delete the copy constructor).
If the user need to inherit from a class/struct that delete the copy constructor, in the real world, I suppose it also have at least some member variables.

I don't know if you want to keep the issue opened (maybe you want think more about that). But for me I think it can be closed.

Thanks
