### ISSUE TITLE
Binding resource_cache to arbitrary loader function

### ISSUE THREAD

**Issue by xubury** [skypjack/entt#868]
Before commit b8bb509d5c1683aaed318cfb2c2da3b6e6a2c89e,  the  loaders are required to inherit from `resource_loader` and  implement `load` function .
If I understand the code correctly,  the new `resource_cache` now just require loader to overwrite `operator()`.
Would it be a good idea to pass function pointer to template parameters, so I can bind arbitrary function from a loader?
Here's the code snippet I came up with when trying to achieve that, kind of messy. 
I would like to know about your opinion. :)
```
template <typename Resource, typename Loader, typename LoaderFunc,
          LoaderFunc func>
class resource_cache {
   public:
    template <typename... Args>
    [[nodiscard]] resource_handle<Resource> load(const id_type rid,
                                                Args &&...args)
    {
        if (auto it = m_resources.find(rid); it == m_resources.cend()) {
            if (auto handle = temp(std::forward<Args>(args)...); handle) {
                return m_resources[rid] = std::move(handle);
            }
        }
        else {
            return it->second;
        }

        return {};
    }

    template <typename... Args>
    [[nodiscard]] resource_handle<Resource> temp(Args &&...args)
    {
        return (m_loader.*func)(std::forward<Args>(args)...);
    }
   private:
    Loader m_loader;
    std::unordered_map<id_type, resource_handle<Resource>> m_resources;
}
```
So if I have a `TextureLoader` class, I can do something like this:
```
class  TextureLoader {
   public:
    std::shared_ptr<Texture> Load(const std::string &path);
};
 using TextureCache =
        ResourceCache<Texture, TextureLoader, decltype(&TextureLoader::Load),
                      &TextureLoader::Load>;
```

**Comment by skypjack** [comment]
My two cents: that's somewhat contrived since we can achieve exactly the same result with a lambda already or a custom adaptor like:
```cpp
template<typename Type>
struct Loader: Type {
    using result_type = std::shared_ptr<typename Type::value_type>;

    template<typename... Args>
    result_type operator()(Args &&...args) {
        return Type::Load(std::forward<Args>(args)...);
    }
};

using TextureCache = entt::resource_cache<Texture, Loader<TextureLoader>>;
```

**Comment by xubury** [comment]
Oh, that'will do too, I didn't think of that earlier. 
The problem initially for me is that I have different loader implementations with different name.
For example, I have to write different adaptors like below.
Perhaps it's better to rename them with the same name?
```
template <typename Loader>
struct LoadFromFileAdp : Loader {
    template <typename... Args>
    auto operator()(Args &&...args)
    {
        return Loader::LoadFromFile(std::forward<Args>(args)...);
    }
};

template <typename Loader>
struct LoadFromMemoryAdp : Loader {
    template <typename... Args>
    auto operator()(Args &&...args)
    {
        return Loader::LoadFromMemory(std::forward<Args>(args)...);
    }
};

using TextureCache = ResourceCache<Texture, LoadFromFileAdp<TextureLoader>>;
using TextureCacheFromMemory = ResourceCache<Texture, LoadFromMemoryAdp<TextureLoader>>;
```

**Comment by skypjack** [comment]
The whole cache and loader machinery is meant to support tag dispatching. So, you actually need a single class probably:
```cpp
struct load_from_memory {};
struct load_from_file {};

struct MyLoader : Loader {
    template <typename... Args>
    auto operator()(load_from_memory, Args &&...args) {
        return LoaderFromMemory::LoadFromMemory(std::forward<Args>(args)...);
    }

    template <typename... Args>
    auto operator()(load_from_file, Args &&...args) {
        return LoaderFromFile::LoadFromFile(std::forward<Args>(args)...);
    }
};
```
Or something similar. This should give you a grasp of what I mean. From outside, you can have a single cache for both resource, it doesn't really matter if they were loaded from memory or from file. As long as you can attach to them the right destructor, the cache won't make any difference.
Let me know if it's unclear.

**Comment by xubury** [comment]
Oh, I see.  That's an interesting usage of struct. Anyway, thanks for your answer ! I am closing this issue.
