### ISSUE TITLE
Can't dereference out of range vector issue in entt 3.10.0

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#872]
Something might go wrong with meta_sequence_container in entt 3.10.0 **single_include_file**, here's the code to reproduce this issue:
```
std::vector<int> a;
entt::meta_any any = entt::forward_as_meta(a);
auto view = any.as_sequence_container();
auto it = view.insert(view.end(), 1);
auto v = *it;
auto it2 = view.insert(view.end(), 2);
auto v2 = *it2; // Here is the crash!
```
Please help, thanks!

**Comment by skypjack** [comment]
Mmm have you tried using the headers from the project? Because [it works fine](https://godbolt.org/z/86f9MG9zb) in this case from what I can tell.
Otherwise, can I ask you what compiler are you using? I can't reproduce the issue yet.

**Comment by hls333555** [comment]
> Mmm have you tried using the headers from the project? Because [it works fine](https://godbolt.org/z/86f9MG9zb) in this case from what I can tell. Otherwise, can I ask you what compiler are you using? I can't reproduce the issue yet.

I have tested in vs2019 and vs2022. Both of them have this issue. And I just add that code to main() and run, the crash occurs both in debug and release. Maybe this issue is related to MSVC compiler only...

**Comment by skypjack** [comment]
I see. I'll give it a try but you have to wait a little for that since Monday is a national holiday in Italy and I'll be out for a few days. 🙂

**Comment by skypjack** [comment]
Nvm, I've found the time to give it a try and damn: you're right!!
This is a bug, an error of mine and a corner case not covered by a test (yet).
Good catch. Really a good catch. Thanks for pointing this out. 👍

**Comment by skypjack** [comment]
Is there any chance that you can test the commit above? It would be great if you could confirm that it fixes the problem. Thanks.

**Comment by hls333555** [comment]
> Is there any chance that you can test the commit above? It would be great if you could confirm that it fixes the problem. Thanks.

Thanks for the fix! However, it's not easy for me to test that in my project. Could you please update the single include file so that I can test it quickly.

**Comment by hls333555** [comment]
> ` [103f935](/skypjack/entt/commit/103f935d615d4b7c3ad3e1552f83f7ddabd7d133)`

Thanks! But which arguments do I need?
Enter like this seems incorrect:
`python amalgamate.py -c`

**Comment by skypjack** [comment]
Fair enough, it's:
```cpp
python3 scripts/amalgamate.py -c scripts/config.json -s .
```

**Comment by hls333555** [comment]
> Fair enough, it's:
> 
> ```c++
> python3 scripts/amalgamate.py -c scripts/config.json -s .
> ```
> 
> From the root dir of the project.

That works! Thanks for the fix! Hope it can be merged to main and released soon!
