### ISSUE TITLE
[Question] destroying multiple entities via registry.destroy()

### ISSUE THREAD

**Issue by moonburnt** [skypjack/entt#877]
I'm trying to befriend box2d with entt. This task consists of two parts:
- Tying entity with collision.
- Deleting entity on collision with some specific thing (and because that thing is a mouse pointer - Im using box2d's QueryAABB).

In order to achieve first, Im trying to store entity ID inside collision component:

```cpp
entt::entity ball = registry.create();

registry.emplace<BallComponent>(
    ball, &world, ball, pos, size, BLUE,
    b2Vec2{direction.x*speed, -direction.y*speed});
```
And then, inside component's constructor - attach pointer to that component to fixture:

```cpp
class BallComponent {
public:
    entt:entity entity_id;
    Color color;

    BallComponent(
        b2World* world,
        entt::entity eid,
        Vector2 pos,
        float _radius,
        Color _color,
        b2Vec2 velocity) : entity_id(eid), color(_color) {
        // Some code omitted
        b2FixtureDef fixture_def;
        // Some code omitted
        fixture_def.userData.pointer = uintptr_t(this);
        // Some code omitted
    }
};
```

So it will be possible to access it on collision and retrieve its public data (including id) via collision handler.
Thus far, things work.
I update my collision tree, then try to query collisions that occurred. And thats where things start getting weird

```cpp
// Everything works, until commented out part

void Level::process_mouse_collisions(b2AABB rect) {
    CollisionQuerryCallback* querry = new CollisionQuerryCallback;
    world.QueryAABB(querry, rect);

    if (querry->collisions.size() > 0) {
        for (auto collision : querry->collisions) {
            const entt::entity entity_id = collision->entity_id;
            spdlog::info(
                "Rect collides with with {}",
                static_cast<uint32_t>(entity_id));

            auto ball = registry.try_get<BallComponent>(entity_id);

            if (ball) {
                spdlog::info("destroying");

                // However stuff commented there has semi-undefined behavior.
                // E.g most of the time it works, but sometimes it either refuses
                // to delete things completely, or delete the wrong entities.
                // Not sure what exactly causes it - entt's documentation specify
                // destruction before the end of update cycle as a fine thing.
                // Unless I've misunderstood something or its only fine in a view?

                // collision->body->DestroyFixture(collision->body->GetFixtureList());
                // world.DestroyBody(collision->body);
                // // b2Fixture* fixtures = collision->body->GetFixtureList();
                // registry.destroy(entity_id);
            }
        }
    }

    delete querry;
}
```

So yeah - as comment indicates, everything before deletion part seems to work. I think (I've debugged this thing by changing colors of specific components and this seem to always apply to right components).
But if I try to destroy entity the commented way - sometimes nothing happens, sometimes wrong entity's components get destroyed. What could possibly go wrong? 
I thought entt::entity are entity ids which don't get changed even if other things in registry are getting destroyed. Or am I wrong and there should be some other approach to perform entity destruction?

**Comment by skypjack** [comment]
> And then, inside component's constructor - attach pointer to that component to fixture

Unless you enabled pointer stability for `BallComponent`, I bet this is your issue. 🙂 
Pointers to components aren't stable by default in `EnTT`. That is, components are moved if necessary to keep all pools tightly packed. Pointer stability flips the problem on its head and uses tombstones to achieve the same.
Roughly speaking, it's literally meant for these cases. You can find more details in the documentation. Feel free to drop a line if you've any problems with it though. 👍

**Comment by skypjack** [comment]
Please, let me know if that was the problem and close the issue eventually. Thanks.

**Comment by skypjack** [comment]
I assume that was the problem and therefore we can close the issue. Feel free to drop a line if this isn't the case.

**Comment by moonburnt** [comment]
actually just solved this, was about to close the issue. No, entt's default behavior was not the cause of problem - actual culprit was box2d. Still, thanks for bothering - tombstones may come useful later
