### ISSUE TITLE
Getting all components on an entity

### ISSUE THREAD

**Issue by JSandusky** [skypjack/entt#88]
I might just be having an idiot moment but ...

I don't see a way to get all components on an entity for inspection/tool purposes?

Is there something I'm missing or a recommended way of doing that. Even just a bitset or vector<bool> by some sort of index would be useful.

**Comment by Kerndog73** [comment]
I'm not completely sure what you mean but you can check if an entity `has` one or more components.

```C++
entt::DefaultRegistry reg;
reg.has<Position>(entity); // true if the entity has a Position component
reg.has<Position, Velocity, Goblin>(entity); // true if entity has Position and Velocity and Goblin
```

You might be able to take a typelist and create a bitset of the components an entity has by calling `reg.has` for each type in the list. [EnTT is a bitset-free ECS](https://github.com/skypjack/entt#a-bitset-free-entity-component-system) so you can't just grab a bitset from the internals because there isn't one!

```C++
template <typename... Comps>
std::bitset<sizeof...(Comps)> getBitset(
  entt::DefaultRegistry &reg,
  const uint32_t entity
) {
  using List = Utils::TypeList<Comps...>;
  std::bitset<sizeof...(Comps)> bitset = 0;
  size_t index = 0;
  Utils::forEach<List>([&bitset, &index, &reg, entity] (auto type) {
    using Component = UTILS_TYPE(type);
    bitset[index] = reg.has<Component>(entity);
    ++index;
  });
  return bitset;
}
```

You'll have to replace `Utils::TypeList` and `Utils::forEach` with your own type list library of course. @skypjack might be aware of a way to do this more effeciently than calling `reg.has` for each component.

---

You can get a list of components all at once.

```C++
reg.get<Position, Velocity, Goblin>(entity); // returns a std::tuple containing the three components
```

**Comment by skypjack** [comment]
In case the suggestions from @Kerndog73 don't solve your problem, it would help if you can give more details and an example of use of what you are looking for.  
Thank you.

**Comment by JSandusky** [comment]
@Kerndog73 yeah I think so. Even if it doesn't that's close enough that I get it. 

Though it just dawned on me that the serialization stuff could probably be used assuming I can serialize/deserialize 1 specific entity, even if I can't ATM that's probably not going to be a tough tweak.

@skypjack exact purpose in my case is that I'm embedding a small HTTP server into the program for introspection/editing purposes. For that I need to get a list of every component on an entity ideally as close to typeless as I can for as long as I can - though in some cases that isn't necessary, not needed in a trivial inspector but is needed for a coalesced data-table view of entities.

TL/DR: user-interface needs.

**Comment by skypjack** [comment]
>For that I need to get a list of every component on an entity ideally as close to typeless as I can for as long as I can

So, a sort of range of `component_type`s (aka `std::size_t`) would work for you?  
This put your side the burden of _deducing_ what's the actual type of the i-th item in the range.

**Comment by ArnCarveris** [comment]
Hmm sounds like visitor pattern, [this example may help](https://github.com/acki-m/rttr/blob/feature-add-visitor-mechanism/src/examples/scripting/chaiscript_visitor.h)

**Comment by skypjack** [comment]
So, @JSandusky nothing to do for this issue? Not sure serialization is the best tool for this purpose, but it's fine for me if it works for you. :-)

**Comment by JSandusky** [comment]
Yeah, nothing to do. Going along the lines of what @Kerndog73 posted will work plenty well. The Snapshot interface involves too much hard writing to be usable for this (usable, but really unpleasant).

**Comment by skypjack** [comment]
>The Snapshot interface involves too much hard writing to be usable for this (usable, but really unpleasant).

Feel free to contribute with a suggestion to improve the snapshot stuff. This library is mostly made by its users, their requests and suggestions.  
Also, do not forget to star the project. This helps to make it known and to attract even more users, so more contributions and suggestions.

**Comment by JSandusky** [comment]
> Also, do not forget to star the project. This helps to make it known and to attract even more users, so more contributions and suggestions.

No. Ended up going with a late 90's style Bungie style ECS instead. Can't actually recommend Entt enough to star it. Need concrete identification of things in order to write tools, Entt makes that template hell.

**Comment by skypjack** [comment]
I love this _C-ish_ stuff that pops out from late 90's.  
However, if you need help with modern C++, modern techniques and therefore with `EnTT`, feel free to ask in future.  
There exist already tools like the one you're writing that use `EnTT` under the hood, fortunately. It's only a matter of approach and design sometimes.

**Comment by namandixit** [comment]
@JSandusky Sorry for the necro-post, but can you please refer to some documentation as to what you meant by "late 90's Bungie style ECS"? I am also hitting the same complexity barriers, and would like to study simpler alternatives. The only thing my research yielded was [Halo 2's "tag" system](http://nikon.bungie.org/misc/gdc2005_mnoguchi/), but I am not sure if this is what you were referring to (and how to use this to build a full entity-management system to top of this)?

**Comment by Kerndog73** [comment]
Getting all components of an entity as an opaque identifier has since become possible with [`visit`](https://github.com/skypjack/entt/blob/47ada87ba2fab08c70fdd61fa2835a27fb9ce8a7/src/entt/entity/registry.hpp#L1492). That will give you a [`type_info`](https://github.com/skypjack/entt/blob/47ada87ba2fab08c70fdd61fa2835a27fb9ce8a7/src/entt/core/type_info.hpp#L141) object. What you can do with this [is growing](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#meet-the-runtime). You can create a table of function pointers or use the other facilities available.

**Comment by henrywalters** [comment]
@Kerndog73 Thanks A LOT for mentioning this. This is exactly what I needed for my project. I notice this is not in the [crash course](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system). Would a PR for that be welcomed?

Thanks all for working on this great library

**Comment by skypjack** [comment]
Actually, things are about to change.
The basic idea is that pools will be publicly available (as in `registry.storage<T>() -> storage<T>` and `registry.storage(name) -> basic_sparse_set`) and are fully safe to use from the base (as in you can remove elements or create defautl constructible ones from the base if you like). Because of that, the base will also offer an `user_data` field where you can literally store a vtable through a mixin.
So, way more convenient. @henrywalters let me know if you've any questions about this. 👍

**Comment by Eren121** [comment]
Digging up this topic, but I think this solution works (based on the [wiki](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system)) :

````
void print_all_components_ids(entt::registry& reg, entt::entity entity)
{
    for(auto&& curr : reg.storage())
    {
        entt::id_type id = curr.first;

        if(auto& storage = curr.second; storage.contains(entity))
        {
            std::cout << "Entity has component id = " << id << std::endl;
            // Or do watever you will with the component ID
        }
    }
}
```

**Comment by skypjack** [comment]
Or the reflection system @Eren121 you can use the type info returned by the storage to lookup the meta type, then...

**Comment by ChilledCosmonaut** [comment]
I'm sorry to revive this thread again but I do not quite understand all the approaches explained here.

My current goal is to cycle through all components of n entity (note that all components inherit from a templated common base class) and call one specific function. Is there a way to simply call one function to flag each component for deletion?

The common base class will have a flagForDeletion function something along the lines of this:
```
template <typename ComponentType>
void FlagForDeletion(entt::entity entityId){
     registry.emplace_or_replace<Destroy<ComponentType>>(entity);
}
```

The Component Destroy<ComponentType> is then used for identification in a later function call to handle the destruction properly.

**Comment by Eren121** [comment]
Here a complete example to iterates all components.
However, you **have** to register every `Destroy<A>`, `Destroy<B>`, etc first. Even if your component class is a template. Two instances of the same template class are still different classes, you have to generate compiled code for them.

```
#include <entt/entt.hpp>
#include <entt/entity/registry.hpp>

#include <iostream>

using std::cout;
using std::endl;

struct A
{
    A() { cout << "A()" << endl; }
    ~A() { cout << "~A()" << endl; }
    A(const A&) { cout << "A(const A&)" << endl; }

    A& operator=(const A&) { cout << "operator=(const A&)" << endl; return *this; }

    int my;
};

std::map<entt::id_type, std::string> map;

struct B {};

void print_all_components_ids(entt::registry& reg, entt::entity entity)
{
    for(auto&& curr : reg.storage())
    {
        entt::id_type id = curr.first;

        if(auto& storage = curr.second; storage.contains(entity))
        {
            std::cout << "Entity has component " << map[id] << std::endl;
        }
    }
}

int main()
{
    entt::registry reg;
    auto e1 = reg.create();
    auto e2 = reg.create();

    map[entt::type_id<A>().hash()] = "A";
    map[entt::type_id<B>().hash()] = "B";


    reg.emplace<A>(e1);
    reg.emplace<B>(e1);
    reg.emplace<B>(e2);

    print_all_components_ids(reg, e1);
    print_all_components_ids(reg, e2);
}
```

**Comment by skypjack** [comment]
@ChilledCosmonaut I don't even get the purpose of the `FlagForDeletion` function to be honest.
You want to iterate over the components of an entity to invoke a function that attaches yet another component to the same entity.
Just do it as you iterate, why not? I'm pretty sure I'm missing a bit of context here.

**Comment by ChilledCosmonaut** [comment]
@Eren121 Thank you. It was exactly what I was searching for!
@skypjack Yeah you are right. I wrote this just as I was going to bed (so it was typed out pretty badly) and later it came to me that it would be easier to have another single component that all components would recognize, that it is a destruction flag (an entity destruction flag, instead of a component destruction flag).
Thank you both though for the fast reply!

**Comment by kafkaphoenix** [comment]
@skypjack 
`void print_all_components_ids(entt::registry& reg, entt::entity entity)
{
    for(auto&& curr : reg.storage())
    {
        entt::id_type id = curr.first;

        if(auto& storage = curr.second; storage.contains(entity))
        {
            std::cout << "Entity has component id = " << id << std::endl;
            // Or do watever you will with the component ID
        }
    }
}`
do you mean that with reflection we could know the component name without mapping it? would you mind to show how it would be? I failed to find the answer myself

**Comment by skypjack** [comment]
Yup, that's a way. The other one is by using meta (if you want to also generate a proper meta type) and use the type info object that comes with it. Same stuff though. 👍

**Comment by DamirHalilovic** [comment]
Hello,

Apologies for the necro-post, but I've been trying to use this for a while now without much progress. What I'm trying to do is similar to what is done in the cereal test: https://github.com/skypjack/entt/blob/master/test/snapshot/snapshot.cpp

The only difference is that I want to do this without explicitly listing all the components one by one. I just want to do

`    entt::snapshot_loader{destination, input}
`
...and deserialize everything. Any way to do this?

**Comment by skypjack** [comment]
@DamirHalilovic you can use a reflection system for that, ie the meta module of EnTT.
If you registered a reflect-me function to meta types, you could iterate all pools in a registry, use their type info objects to resolve the meta type, then pass them to the above mentioned function to get the job done.
Another option is to create your own set of erased reflection functions indexed by type id. Similar approach, same result.

**Comment by DamirHalilovic** [comment]
> @DamirHalilovic you can use a reflection system for that, ie the meta module of EnTT.
> If you registered a reflect-me function to meta types, you could iterate all pools in a registry, use their type info objects to resolve the meta type, then pass them to the above mentioned function to get the job done.
> Another option is to create your own set of erased reflection functions indexed by type id. Similar approach, same result.

Thank you for the help. If it's not too much to ask could you point me to an example code snippet of using the meta module? I have barely scratched the surface and it's quite a handful.

**Comment by DamirHalilovic** [comment]
> @DamirHalilovic you can use a reflection system for that, ie the meta module of EnTT. If you registered a reflect-me function to meta types, you could iterate all pools in a registry, use their type info objects to resolve the meta type, then pass them to the above mentioned function to get the job done. Another option is to create your own set of erased reflection functions indexed by type id. Similar approach, same result.

I found some time to look some more into this and this is what I got for the save function:

```
	template<class Archive>
	void save(Archive& archive, entt::registry const& reg)
	{
		entt::snapshot ss = entt::snapshot{ reg };
		for (auto&& curr : reg.storage())
		{
			auto& storage = curr.second;
			archive(storage.free_list());

			for (auto first = storage.data(), last = first + storage.size(); first != last; ++first) 
			{					
				archive(*first);
			}
		}
	}

```

This seems to work fine and it's pretty much the exact content of the built-in get function, but just with the type checks removed (since the type I'm iterating over is obviously the correct type for the storage). However I am stuck with the load function as the get function from the basic_snapshot_loader does not translate as it requires the type info at compile time, and I am unable to get it to infer it from the meta info. Any help or examples would be greatly appreciated, and apologies for the trouble.

**Comment by skypjack** [comment]
Oh, sorry, I was on vacation and forgot to reply when I got back to work.
What I mean is that you can register a meta function as in:
```cpp
entt::meta_factory<Type>().func<&serialize<Type>>("serialize"_hs);
```
Where `serialize` is defined like the following:
```cpp
template<typename Type>
void serialize(NonGenericArchiveType &archive, const entt::sparse_set &set) {
    const auto &storage = static_cast<const entt::storage<Type> &(set);
    // do whatever you want here, you've the set and the archive now... :)
}
```
Then you can invoke the function for all storage types as in:
```cpp
for(auto &&storage: registry.storage()) {
    auto type = entt::resolve(storage.info());
    type.invoke("serialize"_hs, {}, entt::forward_as_meta(archive), , entt::forward_as_meta(storage));
}
```
I didn't test it. Everything is out of my mind as I write this post. However, it should give a grasp of what I mean with my previous message.
Let me know if you want more details and sorry again for the late reply. 🙏

**Comment by DamirHalilovic** [comment]
> Oh, sorry, I was on vacation and forgot to reply when I got back to work. What I mean is that you can register a meta function as in:
> 
> ```c++
> entt::meta_factory<Type>().func<&serialize<Type>>("serialize"_hs);
> ```
> 
> Where `serialize` is defined like the following:
> 
> ```c++
> template<typename Type>
> void serialize(NonGenericArchiveType &archive, const entt::sparse_set &set) {
>     const auto &storage = static_cast<const entt::storage<Type> &(set);
>     // do whatever you want here, you've the set and the archive now... :)
> }
> ```
> 
> Then you can invoke the function for all storage types as in:
> 
> ```c++
> for(auto &&storage: registry.storage()) {
>     auto type = entt::resolve(storage.info());
>     type.invoke("serialize"_hs, {}, entt::forward_as_meta(archive), , entt::forward_as_meta(storage));
> }
> ```
> 
> I didn't test it. Everything is out of my mind as I write this post. However, it should give a grasp of what I mean with my previous message. Let me know if you want more details and sorry again for the late reply. 🙏

Thank you, I see now, and I managed to replicate this. However, I have a crash when running meta_factory with any type. For testing purposes I just do:

![image](https://github.com/user-attachments/assets/ebbb0888-29ac-4f1f-a1c1-41807c37dcbf)

This crashed in the `meta_factory(meta_ctx &area)` ctor, who creates a new ctx, then passes it to `internal::owner(*ctx, *info);` who looks into the newly initialized ctx and searches for the passed-in type, which isn't there obviously because the ctx was just created and has 8 default values. Am I missing something for the meta factory?

**Comment by skypjack** [comment]
> EDIT: It seems I was using an outdated entt version (3.13.1)

Does it mean that you solved the issue or that I should consider it on an older version?

**Comment by DamirHalilovic** [comment]
> > EDIT: It seems I was using an outdated entt version (3.13.1)
> 
> Does it mean that you solved the issue or that I should consider it on an older version?

My bad, yes, I have resolved the issue. I'm posting the solution for anyone who may come across the thread:

```
template<typename Type>
void enttSave(cereal::JSONOutputArchive& archive, entt::registry const& reg)
{
	entt::snapshot{ reg }.template get<Type>(archive);
}

template<typename Type>
void enttLoad(cereal::JSONInputArchive& archive, entt::registry& reg)
{
	entt::snapshot_loader{ reg }.template get<Type>(archive);
}

template<typename Type>
void enttSaveBin(cereal::BinaryOutputArchive& archive, entt::registry const& reg)
{
	entt::snapshot{ reg }.template get<Type>(archive);
}

template<typename Type>
void enttLoadBin(cereal::BinaryInputArchive& archive, entt::registry& reg)
{
	entt::snapshot_loader{ reg }.template get<Type>(archive);
}

// Base template for component registration
template<typename T>
struct ComponentRegistrar {
	ComponentRegistrar() {
		using namespace entt::literals; // For "_hs" literal

		entt::meta<T>()
			.type("name"_hs)
			.template func<&:enttSave<T>>("enttSave"_hs)
			.template func<&enttLoad<T>>("enttLoad"_hs)
			.template func<&enttSaveBin<T>>("enttSaveBin"_hs)
			.template func<&enttLoadBin<T>>("enttLoadBin"_hs);
	}
};
```

```
template<class Archive>
void save(Archive& archive, entt::registry const& reg)
{
	using namespace entt;
	for (auto&& storage : reg.storage()) {
		auto type = entt::resolve(storage.first);
		type.invoke("enttSave"_hs, {}, entt::forward_as_meta(archive), entt::forward_as_meta(reg));
	}
}

template<class Archive>
void load(Archive& archive, entt::registry& reg)
{
	using namespace entt;
	for (auto&& storage : reg.storage()) {
		auto type = entt::resolve(storage.first);
		type.invoke("enttLoad"_hs, {}, entt::forward_as_meta(archive), entt::forward_as_meta(reg));
	}
}
```

It's just missing the differentiation to switch between binary and json archives, but that seems much more straightforward now.

Thanks a ton for the help!

**Comment by skypjack** [comment]
You can make the archive type a template parameter and have a single load/save implementation probably. 👍
