### ISSUE TITLE
entity: registry with non constexpr custom entity fails to compile

### ISSUE THREAD

**Issue by Alzathar** [skypjack/entt#882]
EnTT version: v3.10.1
OS: Windows 10 (x64)
Compiler: Visual Studio Build Tools 2022 - amd64

The following code compiled with EnTT v3.9.0 but failed with EnTT 3.10.1. The issue is related to the usage of a `constexpr` variable in `sparse_set::contains`: https://github.com/skypjack/entt/blob/master/src/entt/entity/sparse_set.hpp#L578. If you remove the `constexpr` keyword, the code compiles as expected.

```c++
struct my_entity {
  using entity_type = std::uint32_t;
  static constexpr auto null = entt::null;

  my_entity(entity_type value = entt::null):
      _Eid(value), _Dynamic() {
  }

  my_entity(const my_entity &other) ENTT_NOEXCEPT : _Eid(other._Eid), _Dynamic(other._Dynamic) {}

  const a_dynamic_type &dynamic() const noexcept {
    return _Dynamic;
  }

  constexpr operator entity_type() const noexcept {
    return _Eid;
  }

private:
  entity_type _Eid;
  a_dynamic_type _Dynamic; // Dynamic structure, for example std::string
};

void main() {
    entt::basic_registry<my_entity> registry{}; // Fail to compile
}
```

**Comment by skypjack** [comment]
As far as I can tell, v3.9 has exactly [the same line of code](https://github.com/skypjack/entt/blob/v3.9.0/src/entt/entity/sparse_set.hpp#L584)? That being said, yeah, EnTT requires that entity types are also constexpr since a couple of versions ago.
The right place for the data are usually the components. Can I ask you what you're trying to do and why your entity type isn't constexpr instead? Maybe this is an XY-problem.

**Comment by skypjack** [comment]
> I did not pay attention to the code in v3.9

Yeah, what I mean is that I strongly suspect you're not using v3.9 since it also fails with it. 🙂 

> Would you advise against this kind of customization for the entity_type?

Rather than this, I wonder whether the registry is the right tool for it. Why not an `entt::dense_map` for example? It seems more appropriate to be honest. Am I missing something?

**Comment by Alzathar** [comment]
Please find the output of godbolt when I compile a custom entity with a dynamic object using EnTT 3.9.0 and EnTT 3.10.1. As mentionned in my previous messages, the code compiles with EnTT 3.9.0 but fails with EnTT 3.10.1

 - EnTT 3.9.0: https://godbolt.org/z/qEPc1jdM8
 - EnTT 3.10.1: https://godbolt.org/z/M31o65Evr

What can explain this?

**Comment by skypjack** [comment]
The fact that the entity class was already required to be constexpr and now you also hit a line of code where this is enforced by chance.
I'm more than willing to help you to get around this but I need more info on what you're trying to achieve and why, so that I can make a meaningful proposal. 🙂
