### ISSUE TITLE
entt::meta_type missing is_signed

### ISSUE THREAD

**Issue by Opity69** [skypjack/entt#884]
meta_type   missing is_signed trait

**Comment by skypjack** [comment]
It isn't available on purpose to reduce the number of generated symbols.
However, you can easily simulate it with a custom function in user space.

**Comment by Opity69** [comment]
thx  though it might be the case

**Comment by skypjack** [comment]
I've decided to add both `is_integral` and `is_signed`. The others can be derived from these ones. 👍
