### ISSUE TITLE
Question about entt::resource

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#889]
Is there a way I can cast entt::resource to std::shared_ptr?
Here's the situation:
```cpp
class Bindable {};
class Asset {};

class Texture2D : public Bindable, public Asset {};
class Depth : public Bindable {};

class Manager
{
std::vector<std::shared_ptr<Bindable>> m_Bindables;
};
```
Here, Texture2D is an asset so it is loaded by the resource_cache as an entt::resource, but I want to store it also in the m_Bindables. I do not want to make std::shared_ptr<Bindable> to entt::resource<Bindable> as other bindables such as Depth is not an asset.
Thanks for any help!

**Comment by skypjack** [comment]
Mmm actually, we could just remove functions like `use_count` and offer access to the underlying handle instead.
It won't be necessarily available in case of specializations but that's kinda expected and therefore it doesn't matter. 🤔

**Comment by hls333555** [comment]
So, would you please add that to entt::resource class in the future? Thanks a lot!
