### ISSUE TITLE
Call for comments: bind prototypes to a registry

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#89]
Currently, `Prototype` manages internally its components. I'd like to pass a registry to the constructor instead and therefore to use the registry as its (let me say) _underlying storage_.  
The prototype will create an entity to which to bind the components assigned to it and will destroy the entity in the destructor. All its member functions will have two overloads: one that uses the underlying registry and one that copies the prototype over to a different registry. Something like this:
```
// creates an entity in the underlying registry and assigns it all the components of the prototype
const auto e0 = prototype();
// creates an entity in another registry (not the underlying one) and assigns it all the components of the prototype (by cross-copying them between the two registries)
const auto e1 = prototype(registry);
```

This is by far easier to maintain and make much sense for me.  
To avoid _collisions_ with the actual types of the components, the prototype will _wrap_ those types in custom ones. As an example:
```
template<typename Component>
struct Wrapper {
    Component component;
};
```

This way, prototypes won't interfere in any case with systems that are interested in `Component`, even when prototypes share the registry with the rest of the application.

Unless someone comes with a good reason not to do it, the change will be part of the next release.

**Comment by ArnCarveris** [comment]
@skypjack So prototype will have inside instance of registry?

**Comment by skypjack** [comment]
@ArnCarveris A reference to a registry, yep - `Registry<Entity> &`

**Comment by ArnCarveris** [comment]
@skypjack What prototype will hold inside?

**Comment by skypjack** [comment]
@ArnCarveris `Prototype` will have two data members: a reference to a registry and an entity identifier, the one of the entity to which the prototype attaches its components through the registry.

**Comment by Kerndog73** [comment]
Should probably store a pointer to the registry rather than a reference so that prototypes can be moved.

**Comment by skypjack** [comment]
@Kerndog73 A reference to a registry should not prevent you from moving a prototype. I didn't get your comment but, well, it makes sense in terms: a prototype should be moveable, I agree. :-)

**Comment by ArnCarveris** [comment]
@skypjack Why `Prototype` needs entity identifier? This change will break my use cases mentioned in #56?

**Comment by skypjack** [comment]
Sorry, which post? #56 is pretty long... :-(

**Comment by skypjack** [comment]
@ArnCarveris Sorry, which post? #56 is pretty long, unfortunately...

**Comment by ArnCarveris** [comment]
@skypjack right after [this](https://github.com/skypjack/entt/issues/56#issuecomment-388064719)

**Comment by skypjack** [comment]
@ArnCarveris I don't get how a prototype that internally uses an entity breaks your use case. Components used by the prototype don't interfere with the ones of the application (it wraps them in a dedicated type). Moreover, it is allowed to use two registries: one to store the prototypes and one for the rest of the applications. Prototypes that use a registry can create entities on a second registry. How does this interfere with the use case mentioned in the other issue exactly?

**Comment by ArnCarveris** [comment]
@skypjack If wont break, when aren't any problem with this.

**Comment by Kerndog73** [comment]
Just a nitpick: I'm pretty sure the member functions `create`, `assign`, `accommodate` and `operator()` can be marked `const`.

**Comment by skypjack** [comment]
@Kerndog73 Yep, it's right. Wouldn't it be a bit misleading anyway? Even if `const`, they modify the underlying registry by creating a new entity and some components. Not sure if this is something I want to allow with a const prototype. What about?

**Comment by Kerndog73** [comment]
The prototype does modify the registry but the prototype doesn't "own" the registry. The prototype only refers to the registry. The registry isn't apart of the prototype's "state".

When I pass a `const entt::DefaultPrototype &` to a function, I expect the function to create entities.

When I pass a `entt::DefaultPrototype &` to a function, I expect the function to fill up the prototype with components.

**Comment by skypjack** [comment]
@Kerndog73 It makes sense.

**Comment by Kerndog73** [comment]
I just noticed that Prototype doesn’t have a move constructor. So when you try to move it, you get an assert in registry.destroy.

A “moved from” prototype could store a null entity (just like a “moved from” std::unique_ptr stores a nullptr) so that registry.destroy succeeds (delete nullptr succeeds) but all other operations on the prototype result in asserts in the registry.

**Comment by skypjack** [comment]
Good point. It's a sort of enhancement of the prototype class.  
Could you open a dedicated issue for this? It makes sense.
