### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_INCLUDEDIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [skypjack/entt#890]
As per title: `cmake/in/entt.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_INCLUDEDIR`. This leads to broken .pc files on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach.

**Comment by skypjack** [comment]
@alexshpilkin I've no way to test a fix to be honest. If you know already what to change and can also verify it, can I ask you to open a PR?

**Comment by skypjack** [comment]
Ping. The issue is starving. I cannot reproduce the problem, I need help in case and I don't have any way to test it eventually.
