### ISSUE TITLE
Issue emplacing component to entity

### ISSUE THREAD

**Issue by grimaldini** [skypjack/entt#891]
Hi,

I am getting the following error:
`Assertion failed: (entity_traits::to_version(elem) == entity_traits::to_version(tombstone)), function assure_at_least, file sparse_set.hpp, line 210.`

when I emplace a component to an entity that I know is alive (because I have printed out all the entities that have been "destroyed" by calling the method destroy and I didn't see that one on the list). The emplace happens within a view each and the entity that I am emplacing the component to is the current entity.

I basically only call destroy from one single place in the codebase. I am assuming that this error message refers to a emplacing a component to an invalid/tombstoned entity, is that right? if so or not, what could be another situation when this message is shown?
P.S. I am not using the in-place delete functionality.

Thanks

**Comment by skypjack** [comment]
Can I ask you what version of EnTT is it? I can't find this line of code anymore. 😅 
Anyway, at a first glance, this is what replaced it:
```cpp
ENTT_ASSERT(elem == null, "Slot not available");
```
It states that the set already contains the component. So, roughly speaking, you're adding a component to an entity that has an instance of the same type already.
You can try to assert before invoking `emplace` to confirm it.

**Comment by grimaldini** [comment]
I am based off commit a03b88e0eb679ca0fbb79d9c54293e772b4f4a93 "dense_hash_[map/set]: suppress super annoying warnings".

> So, roughly speaking, you're adding a component to an entity that has an instance of the same type already.

So, you are saying that the entity already has the same component added to it?

**Comment by skypjack** [comment]
It looks so from the error, yeah. Hard to confirm 100% without a repro though.

**Comment by grimaldini** [comment]
Ok, that makes sense, I was able to find the issue with your explanation, thanks. Quick question, do you normally use `emplace_or_replace`. I feel that it's hard to keep track of all system dependencies and the components that each add, especially with a large set of systems.

**Comment by skypjack** [comment]
Actually, I don't. The last version of EnTT offers the possibility of getting the storage from a view and this makes passing the registry around pointless. Moreover, the whole library is moving towards a model where you can have storage classes and views but no registry at all if you like.

**Comment by grimaldini** [comment]
Interesting, do you have a post or doc with more details of the model where EnTT is headed to?

**Comment by skypjack** [comment]
I should but there is not actually. If you have any questions, feel free to drop them here and I'll be glad to answer them.
