### ISSUE TITLE
enttRegistry->view performance issue ... 

### ISSUE THREAD

**Issue by wenfangliao0223** [skypjack/entt#892]
i build an ecs gameobject update pipeline with entt v390.
in the game world, there are 150 entities, each of them has about 30 types of components.
the size of these component is about 40 bytes to 1k bytes.
and my update pipeline comes up with 30 systems, each of them will access 4 to 6 components.
the problem is, the 30 systems access their components using: view = enttReg->view<...>() operation.
and the cost of 30 times of enttReg->view<...>() call is about 0.3ms per frame in a i7-10700 cpu.
i believe the performance is heavy ...  is there a cheap way to get all of these views during a frame tick?
i wanna cache them, but some memory issues will make it a bad idea ... 
also, for now, all the 150*30 componets stored in 1 enttReg, maybe i can separate them into 2 or 3 enttRegistry ? as each cost of enttReg->view mybe reduce? im not sure...
so whats the best solution? 
thx...

**Comment by skypjack** [comment]
The numbers you're reporting aren't even close to what can cause problems to the library (actually, they are pretty far away).
Are you compiling in debug or release mode with symbols? This smells of a debug build (even though it's still pretty odd).
In any case, you don't have to do this or something similar all the times:
```cpp
reg.view<T>().get(entity);
```
As it results from your comment:
> and the cost of 30 times of enttReg->view<...>() call is about 0.3ms per frame in a i7-10700 cpu.

The documentation contains enough details about how to iterate entities and components. 👍

**Comment by skypjack** [comment]
Closing as invalid and due to starvation/no answers.
