### ISSUE TITLE
Question : Is it possible to add components (of the same type) while iterating a view?

### ISSUE THREAD

**Issue by Oolalalalala** [skypjack/entt#893]
Currently, I've created a component (named [ScriptingComponent] ) to contain all user-defined scripts attached to an entity. However, when I was iterating through all of the OnUpdate() functions in scripts with a view, user might need to create entities. During the creation process, [ScriptingComponent] is attached to an entity as default, because one might need to add scripts right afterward. Due to the reason, delay wouldn't be optimal.

So, is it possible to add components (of the same type) while iterating a view? Or, are there any other alternatives that I could take?

(Below is a simplified version of what I'm doing)
```
auto view = registry.view<ScriptingComponent>();
for (auto e : view)
{
    auto& scriptingComponent = view.get<ScriptingComponent>(e);
    for (Script* script : scriptingComponent.Scripts)
    {
        script->OnUpdate();
    }
}
``` 
```
void SomeScript::OnUpdate()
{
    // Create an additional entity
    auto entity = registry.create();
    // Adding a component while the view is still alive
    registry.emplace<ScriptingComponent>(entity);
}
```

**Comment by skypjack** [comment]
Yes, it is. Even more, references to already existing components aren't invalidated if you add new instances.
The documentation should contain all the details already. Let me know if something is unclear.

**Comment by Oolalalalala** [comment]
That's what I thought in the first place, too. But there's a bug in my code and I can't quite find it. However, I have reproduced the same error with the following code.

```
#include <iostream>
#include <unordered_map>
#include "entt.hpp"

entt::registry reg;
class Script;

struct ScriptingComponent
{
	std::unordered_map<int, Script*> Scripts;
};

class Script
{
public:
	void OnUpdate()
	{
		counter++;
		if (counter % 20 == 0) // Add a new entity per 20 updates
		{
			entt::entity e = reg.create();
			reg.emplace<ScriptingComponent>(e);
		}
		std::cout << "Counter = " << counter << "\n";
	}
private:
	int counter = 0;
};

int main()
{
	entt::entity et = reg.create();
	auto& scriptingComponent = reg.emplace<ScriptingComponent>(et);
	scriptingComponent.Scripts.emplace(1, new Script());

	while (1)
	{
		auto view = reg.view<ScriptingComponent>();
		for (auto e : view)
		{
			auto& scripts = view.get<ScriptingComponent>(e).Scripts;
			for (auto [idx, script] : scripts)
			{
				script->OnUpdate();
			}
		}
	}
}
```

It seems to work fine if I store the scripts with std::vector, but with std::unordered_map, the program throws an **Access Violation Error**. The unordered_map seems to become invalid when I add [ ScriptingComponent ] to an entity. Am I doing something incorrect or misunderstanding anything?

**Comment by Innokentiy-Alaytsev** [comment]
Wouldn't the reference be invalidated due to component pool reallocation during growth? Does this behaviour somehow depend on whether pointer stability is enabled or not?

**Comment by skypjack** [comment]
Newest releases don't invalidate in this case.
@Oolalalalala what version of EnTT are you using? This will help to figure it out.

**Comment by skypjack** [comment]
Oh, yeah, transparent pointer stability on creation was added with a later version.
I'm from mobile and I can't check right away but it's likely v3.7 or v3.8?

**Comment by Oolalalalala** [comment]
Thanks a lot, @skypjack.
The issue seems to have been gone in test when I switch to the latest version.
I will later make changes to my project and hope everything work fine.
