### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by jakehffn** [skypjack/entt#896]
On [this](https://github.com/skypjack/entt/blob/master/docs/md/meta.md) page of the docs there's, what I assume is, a typo:

> There exits also an overload of the resolve function to use to iterate all the reflected types at once. It returns an iterable object that can be used in a range-for loop:

Should be:
>  There **_exists_** also an overload of the resolve function to use to iterate all the reflected types at once. It returns an iterable object that can be used in a range-for loop:

**Comment by skypjack** [comment]
Oh, wow, good catch. Thanks!

**Comment by jakehffn** [comment]
Not sure how granular people usually try to get with grammar in documentation, but I think that, because it probably could be considered [non-essential](https://owl.purdue.edu/owl/general_writing/punctuation/commas/extended_rules_for_commas.html#:~:text=Use%20commas%20after%20introductory%20a,cat%20scratched%20at%20the%20door.) to the meaning of the sentence, you need commas around 'also'. Like:

> There exists, also, an overload of the resolve function to use to iterate all the reflected types at once. It returns an iterable object that can be used in a range-for loop:

I could be wrong about this though.

**Comment by jakehffn** [comment]
Sorry for not putting that in the original issue though. I didn't notice until looking again.
