### ISSUE TITLE
Single component basic_view::get returning tuple

### ISSUE THREAD

**Issue by james4k** [skypjack/entt#897]
Is it intended that you can no longer call `registry.view<T>().get(id)` without specifying a component type or index?

**Comment by skypjack** [comment]
Yes, it is. The API of the views (multi and single type) were unified a while ago.
On the other hand, you've an `operator[]` on the single type view that also takes an entity and returns its component:
```cpp
auto &&value = view[entity];
```

**Comment by james4k** [comment]
Ah, the operator is probably what I want. I feel like I'm too adverse to multi views, too. Thanks!

**Comment by skypjack** [comment]
You're welcome. 🙂
