### ISSUE TITLE
[3.9.0] swap_and_pop component removal for sorted components

### ISSUE THREAD

**Issue by cmartel** [skypjack/entt#899]
I'm trying to troubleshoot some unexpected behaviour with a sorted component pool when destroying entities. Essentially, these entities have a Distance component which is kept sorted. When beyond a certain distance threshold, the entity is marked for destruction and a system later destroys these entities.

Because marked entities are only ever destroyed **when at the end of the sorted list** (and I've added some logging to confirm this is the case), the swap_and_pop destruction should theoretically just remove Distance components from the end of the pool, preserving the order of the other components. But it looks like the order gets clobbered by entity destruction.

Specifying in_place_delete is not a viable option because it (understandably) disables the single component view specialization, even if I were to explicitly keep the component pool compacted at all times.

We currently opted for the nuclear option of re-sorting the component pool after a destruction, but as this pool can get quite large, I'd rather avoid an extra sort.

Am I misunderstanding something about the component swap_and_pop here?

**Comment by skypjack** [comment]
> Am I misunderstanding something about the component swap_and_pop here?

I wouldn't say so. The swap-and-pop takes the last element, moves it onto the one you want to remove and gets rid of the latter.
In case you're removing the last element, this is literally a plain pop from behind. It's hard to say what's happening to you without a reproducible example.

**Comment by cmartel** [comment]
Hmm, sure. I didn't expect it to be this simple to reproduce but a simple case using godbolt: https://godbolt.org/z/Ehz43jah9

I did not expect the pre-sort to be in decreasing order. It almost looks like the view is iterating backwards? If you flip the Backwards constant in that test case, the order does get preserved when sorting, which makes it seem like the order in which the entities are created is more important than the order of the single component view being used for iteration.

**Comment by skypjack** [comment]
It iterates backward so that you can add and remove elements during iterations. Nothing special, just a trick.
The fact is that `<0> 0` isn't position 0 into the sparse set, it's actually the last slot. Similarly, `<7> 7` is the first one. Therefore, when you delete it, it actually swaps before popping.

That being said, you can do the following to achieve what you want:
* Use reverse iterators to visit the storage/view/whatever
* When you sort, negate the result (and use insertion sort, it's probably way faster in your case)

With your premises, there shouldn't be any swap-and-pop if you do this.

**Comment by skypjack** [comment]
I assume this was answered. I'll close the issue in a couple of days if there are no other comments/doubts. 👍

**Comment by cmartel** [comment]
I couldn't get around to implementing this until recently and then went on vacation but yes, using reverse iteration yields the expected behaviour. Thank you for clarifying this!

I've also further confirmed that even with properly preserved sorting, the processors I'm trying to prioritize based on this sorted component pool would probably be better off served with tags outright restricting the number of iterations, instead of cutting them short early. But that'd require a significant rework which I suppose will have to wait again...

On the subject of iteration, can I borrow this comment thread for one tangential question? 

Over the course of profiling and optimizing, I've pretty much found that the best iteration optimization is to not iterate at all, hence multi component views picking the smallest component pool as the component to drive iteration. `entt::exclude` filters work by subtraction by skipping those components while iterating, which means that with a large component pool and comparably large exclusion set, we end up iterating a lot just to skip entities.

As far as I can tell, groups are the only way to avoid this since they will actively manage a list of which entities match both inclusion and exclusion criteria. What I'm not clear on is whether partial owning groups also get this benefit? I _think_ they do, and the main distinction with fully owned groups is that their dense set will not have their components ordered in lockstep for perfect SoA iteration.

**Comment by skypjack** [comment]
Yeah, exactly, that's the point.
Actually, recent reworks are unlocking a bunch of new possibilities for the storage such as `storage<void>` and `storage<T, U, ...>`. I am working on several things in parallel, so I can't really give you an ETA but this ☝️ will probably allow you to reach your goal even more easily?

**Comment by cmartel** [comment]
I couldn't say without a better picture of what that storage implies. It sounds like `storage<T, U, ...>` would allow for multiple component types to be allocated and stored together? If so, I could see a couple of cases where we would benefit from this, but the main problem I'm trying to solve is of a different nature altogether.

The tl;dr is that we have a set of entities that will have multiple successive operations performed on them, things like reading saved state, performing some data conversion, applying modifiers, etc. There are too many of these entities to just run everything every frame and hold it in memory, so it gets done in a time sliced, priority (hence my persistent interest in ordering/sorting) fashion. In general, the presence of a component indicates that the corresponding system has been run, so the natural instinct is to use a view that excludes that component. 

But because exclusion doesn't actually skip iteration, the overhead of filtering grows with each system and we're reaching large enough entity counts that iteration itself is as much overhead as the processing it does. Thus, switching to use inclusive tags instead of exclusion is one way to handle that, but this confirms that non-owning groups could be an alternate way of doing it.

There's lots more context and experimentation I'm glossing over, not least of which is the matter that using sorted component pools for priority directly cancels the performance benefits of inclusion or exclusion tags. Unless I were to also sort the tag components using the priority component, but then sorting itself would quickly become a new bottle neck. Anyway, my point is there's already lots of tools to experiment with in EnTT's toolbox and knowing this detail about non-owning groups lets me know there's still a couple of things there we can try as needed. 👍

**Comment by skypjack** [comment]
You can also use a plain storage class as in `storage<void> my_set;`, fill it with your entities, then iterate it either alone or in a view if you need to combine it with other sets from the registry:
```cpp
for(auto entt: my_set | registry.view<T, U, V>()) {
    // ...
}
```
This isn't that far from what a non-owning group does but you've finer control on the set of entities probably (and you can also sort your storage if you like).
