### ISSUE TITLE
Systems?

### ISSUE THREAD

**Issue by tomsharratt** [skypjack/entt#9]
Hi,

I was wondering if it would be possible to implement systems based on views. I'm not very familiar with templates to understand how everything in this library works, so I was hoping to get an answer here.

I imagine something like this would be useful:

    template<class ECS, typename... Components>
	class System<ECS, Components...>
	{
	public:

		using pool_type = typename ECS::pool_type;
		using entity_type = typename ECS::entity_type;

		System(ECS ecs) : m_ecs(ecs) {};
		virtual ~System() {};

		void run() {
			for (entity_type entity : m_ecs.view<Components...>())
			{
				process(entity);
			}
		}

		virtual inline void process(entity_type entity) = 0;

	private:

		ECS m_ecs;

	};

Then this would be used for each system like:

`class MovementSystem : public System<ECS, Position, Velocity> ...`

then in the game loop you'd just loop though all the systems and call `run()` or something like that.

Code above obviously doesn't work, just trying to give an example.

**Comment by skypjack** [comment]
>I was wondering if it would be possible to implement systems based on views.

Yeah, definetely yes. You can do that.
I'd suggest you to pass the registry by reference to the systems (registries aren't copyable and you don't want to move it, I'm pretty sure, for the goal is usually to share it between all the systems).
Also, for it's a dependent name, probably you'll have to do something like this to use the `view` member function:

    m_ecs.template view<Components...>()

If you need a working example, let me know and I'll try to prepare one for you as soon as possible.

Thank you for using `EnTT`. Hope it works fine for you.

**Comment by tomsharratt** [comment]
A working example would be ideal, I'm really not very familiar with templates.

Thank you.

**Comment by skypjack** [comment]
Something along this line should work:

```
using registry_type = entt::DefaultRegistry<Position, Velocity>;

template<class ECS, typename... Components>
struct System {
        using entity_type = typename ECS::entity_type;

        System(ECS &ecs) : ecs(ecs) {};
        virtual ~System() {};

        void run() {
            for(entity_type entity: ecs.template view<Components...>()) {
                process(entity);
            }
        }

        virtual void process(entity_type entity) = 0;

private:
        ECS &ecs;
};

struct MySystem: System<registry_type, Position> {
    using entity_type = typename System<MySystem, Position>::entity_type;
    MySystem(registry_type &reg): System<registry_type, Position>{reg} {}
    void process(entity_type entity) { /* ... */ }
};

// ...

registry_type registry;
MySystem sys{registry};
sys.run();
```

Let me know if you need more help.

**Comment by tomsharratt** [comment]
Fantastic, thank you for this.
