### ISSUE TITLE
Undo/Redo

### ISSUE THREAD

**Issue by Daivuk** [skypjack/entt#903]
Hi, this is more of a question than an Issue (The right place to ask?)

I wonder how to implement undo/redo in my editor using EnTT. I have done this numerous times using conventional OOP, and it is simply a matter of capturing the `shared_ptr` into the lambdas. So it just automatically worked.

But using EnTT it's a different story. If I delete entities, then Undo the action, I need to make sure all previous Undos in the history get their `entt::entity` reference updated with the newly "re-created" one.

Currently, I am simply re-recreating the entity using the same ID. But I feel like this will blow in my face at some point. Or would it? If we have to go through all possible IDs first, then i'm fine.

```
// Re-create the entity using the same ID
auto newEntity = reg.create(entity);
if (newEntity != entity) ASSERT("Cannot recreate entity with the same old ID");
```

**Comment by skypjack** [comment]
> this is more of a question than an Issue (The right place to ask?)

I think this is better suited for a discussion. Do you mind if I convert it?

> Currently, I am simply re-recreating the entity using the same ID. But I feel like this will blow in my face at some point.

Well, there are many ways and this one isn't that bad to be honest.
Let's put it this way: if you reach the point where you restore entity E, it means that you've eventually reverted the command that recycled the identifier after destruction. Therefore, the entity is available for use in all cases by construction.

**Comment by Daivuk** [comment]
Oh yea I guess that's perfectly fine then. Unless I have millions of objects I modify over a long history.. might never be the case. And if it is, I could always switch to 64 bits Entities. Thanks for confirming that my solution would work!

**Comment by skypjack** [comment]
You're welcome. 🙂
