### ISSUE TITLE
Improve registry.storage interface

### ISSUE THREAD

**Issue by huwpascoe** [skypjack/entt#908]
The current method of using custom named storage pools is clunky and some interfaces like emplace_or_replace are unavailable.

```
// nice
reg.emplace<int>(e, 123);
reg.view<int>();

// wat
reg.storage<int>("myint"_hs).emplace(e, 123);
entt::basic_view{ reg.storage<int>("myint"_hs) };
```

Some kind of storage pool identifier that could be used by the registry like any other type would be **so much better**:

```
using myint = entt::storage_id<int, "myint"_hs>;

// nice
reg.emplace<myint>(e, 123);
reg.view<myint>();
```

**Comment by huwpascoe** [comment]
I've made an example, and it works as you'd expect:
```
template<typename T, entt::id_type ID = entt::type_hash<T>::value()>
struct storage_id{
	using type = T;
	static auto constexpr id{ ID };
};

template<typename T, typename... Args>
void emplace(entt::registry& reg, entt::entity e, Args&&... args) {
	reg.storage<typename T::type>(T::id).emplace(e, std::forward<Args>(args)...);
}

static void BM_emplace_myint(benchmark::State& state) {
	using myint = storage_id<int, "ok"_hs>;

	entt::registry reg;
	for (auto _ : state) {
		emplace<myint>(reg, reg.create(), 0);
	}
}
```

And it performs identically to `reg.emplace<T>()`, is it really invalid?
```
-------------------------------------------------------------------------
Benchmark                               Time             CPU   Iterations
-------------------------------------------------------------------------
BM_emplace_int                       23.3 ns         23.0 ns     29866667
BM_emplace_int_storage               17.9 ns         18.0 ns     37333333
BM_emplace_int_storage_with_id       17.9 ns         18.0 ns     37333333
BM_emplace_myint                     23.3 ns         23.0 ns     29866667
```

**Comment by skypjack** [comment]
> is it really invalid?

I mean, this doesn't work with runtime identifiers. Therefore, it would only solve the problem in a specific case. 🤷‍♂️

**Comment by kariem2k** [comment]
Because your solution will only work on compile time ids,  which renders the string ids of the storages to be less useful, so maybe just cut the middle man (the registry) and just store variables to the storages. IMHO this is safer and more compile time friendly.

entt:storage<int> myint;
entt:storage<float> myfloat;

auto e = reg.create();
myint.emplace(e, 1);
myfloat.emplace(e, 1.0f);

entt::basic_view{ myint,  myfloat};

**Comment by skypjack** [comment]
This is already possible in fact. The long term goal is exactly to support a registry-less model.
As for your last comment, what do you mean with _your solution will only work on compile time ids_?
Currently, the registry make you use runtime ids if you like/need, that is exactly at the opposite. 🤔

**Comment by skypjack** [comment]
I think we can close this one as invalid. Feel free to reopen it if you feel I didn't get the point. Thanks. 👍
