### ISSUE TITLE
Implicit converting constructor of `entt::meta_any`

### ISSUE THREAD

**Issue by Naios** [skypjack/entt#917]
As discussed on discord, `entt::meta_any` is currently implicitly constructible which might break unrelated code due to (operator overloading) ambiguities:

```
range-v3\include\meta/meta.hpp(3404,60): error C2593: 'operator !=' is ambiguous
entt\include\entt\meta\meta.hpp(559,27): message : could be 'bool entt::operator !=(const entt::meta_any &,const entt::meta_any &) noexcept'
range-v3\include\meta/meta.hpp(3406,1): message : or       'built-in C++ operator!=(unsigned __int64, unsigned __int64)'
```

An easy fix is to change the constructor to explicit:

```patch
diff --git a/src/entt/meta/meta.hpp b/src/entt/meta/meta.hpp
index c53a40ce..f231e878 100644
--- a/src/entt/meta/meta.hpp
+++ b/src/entt/meta/meta.hpp
@@ -216,7 +216,7 @@ public:
      * @param value An instance of an object to use to initialize the wrapper.
      */
     template<typename Type, typename = std::enable_if_t<!std::is_same_v<std::decay_t<Type>, meta_any>>>
-    meta_any(Type &&value)
+    explicit meta_any(Type &&value)
         : meta_any{std::in_place_type<std::remove_cv_t<std::remove_reference_t<Type>>>, std::forward<Type>(value)} {}
 
     /**
@@ -1780,7 +1780,7 @@ inline bool meta_associative_container::clear() {
  * @param value The value of the element to insert.
  * @return A bool denoting whether the insertion took place.
  */
-inline bool meta_associative_container::insert(meta_any key, meta_any value = std::in_place_type<void>) {
+inline bool meta_associative_container::insert(meta_any key, meta_any value = meta_any(std::in_place_type<void>)) {
     return (insert_or_erase_fn(storage, key, value) != 0u);
 }
```

Sadly this breaks a lot of code relying on the implicit conversion (every function that accepts a plain entt::meta_any) -> +60 errors in unit tests.
Probably it is the best solution to add a templated overload to all functions accepting entt::meta_any in order to keep the API intact and usable e.g. to shift the implicit conversion from the constructor to the accepting method by introducing methods like `template<typename T> meta_prop::prop(T&& value)`.

**Comment by skypjack** [comment]
Do you have a repro for the issue with C++20 ranges? It would be great if we could reproduce it easily on godbolt or at least one of the major compilers.

**Comment by Naios** [comment]
https://godbolt.org/z/nW317o73E

```cpp
#include <https://raw.githubusercontent.com/skypjack/entt/master/single_include/entt/entt.hpp>
#include <range/v3/view/filter.hpp>
#include <range/v3/view/iota.hpp>
#include <range/v3/view/transform.hpp>
#include <range/v3/view/zip.hpp>

using namespace entt;

void test() {
  auto const st = static_cast<std::size_t>(0);

  ranges::zip_view(ranges::views::iota(st, st), ranges::views::iota(st, st))
    | ranges::views::filter([=](auto&& element) { return true; });
}

```

I now noticed while reproducing the issue that `using namespace entt` is the main issue here.

**Comment by skypjack** [comment]
Uhm, that's interesting. I can't see the reason though. Any idea?

**Comment by Naios** [comment]
I have no idea. Actually I expected the issue to occur without `using namespace entt` too.

**Comment by skypjack** [comment]
Not sure I want to do _something_ then, I'm of the party that discourages importing namespaces as a whole. 🙂  
Any good reason for which we should try to address an issue that is the result of a bad habit?

**Comment by Naios** [comment]
Thank you for taking a look at this again. I see your point, however importing namespaces can be perfectly valid especially for compilation units (not headers).
It is probably difficult to justify the changes needed to fix the implicit constructor, and also the API breakage that comes with it.

It might be possible that the issue occurs without importing the namespace (also with different effects), however I'm not entirely sure about it. The constructor should have never been implicit in the first place, especially because it accepts all inputs.

I'll leave it to you, how you want to proceeed with this. This issue can be easily avoided by either
1) not including `entt/meta/meta.hpp` or `entt/entt.hpp`
2) not importing the namespace `entt` e.g. `using namespace entt;`

**Comment by skypjack** [comment]
> The constructor should have never been implicit in the first place, especially because it accepts all inputs.

I'm not 100% sold on this though. `std::any` also has a catch-all constructor that isn't implicit. It seems a pretty common design after all and I somehow trust the design of the standard library (mainly because many people smarter than me decided for the best before I did 😅).
In any case, I'll try to address this in a way or the other. You mentioned that turning `operator!=` in a class method also solves the problem for some reasons, am I wrong?

**Comment by Naios** [comment]
As I remind, the in-class `operator!=` also fixed the issue for me. A catch-all constructor is always fine as long as it is marked as `explicit`. I was saying that an implicit constructor that accepts all inputs without limiting the possible set of inputs through SFINAE should not exist.

**Comment by skypjack** [comment]
Sorry. Mistyped. `std::any` ctor is implicit and therefore not explicit afaik. Mostly similar to `entt::any` and `entt::meta_any`.

**Comment by Naios** [comment]
It seems like `std::any` does not implement any binary operator (maybe to avoid such issues?).

**Comment by skypjack** [comment]
Do you mean `operator==`/`!=`? `std::any` offers way less feature then `entt::any` (for a good reason too, that's a design choice). However, I won't drop the two operators because it would mean to break a good amount of code of mine. 😅

**Comment by Naios** [comment]
Yes I was referring to `operator==` and `operator!=` let's first try to make those in-class.

**Comment by skypjack** [comment]
> I have no idea. Actually I expected the issue to occur without `using namespace entt` too.

Ahaaaaa. I finally had the time to look into this one and I can see now why the `using namespace` directive breaks it and why an in-class definition solves the issue.
That's pretty simple actually, this is our beloved language at its best. As tricky as it can get sometimes. 😅
