### ISSUE TITLE
Compile error of `gtest` since Visual Studio 2017 v15.7.3

### ISSUE THREAD

**Issue by ArnCarveris** [skypjack/entt#92]
After upgrading visual studio, while compiling any test emits following error:
```
\entt\deps\googletest\src\googletest\include\gtest\internal\gtest-port.h(996): error C2220: warning treated as error - no 'object' file generated
\entt\deps\googletest\src\googletest\include\gtest\internal\gtest-port.h(996): warning C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and will be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this warning.
```
That issue is know: [google/googletest#1373](https://github.com/google/googletest/issues/1373)

**Comment by skypjack** [comment]
Yep. Can you help me to solve it?  
Find the file `googletest.in` (path `cmake/in`) and change the value of `GIT_TAG` to `master`, then try to compile.  
It should solve the problem. In this case, either open a PR or leave a message here and I'll update the project.  
Thank you.

**Comment by skypjack** [comment]
Nevermind. Can you try branch `experimental`? Let me know if it works for you. Thanks.

**Comment by ArnCarveris** [comment]
@skypjack fixed

**Comment by skypjack** [comment]
Upstream.
