### ISSUE TITLE
Cannot use `registry.ctx().get<>` function.

### ISSUE THREAD

**Issue by ShenCiao** [skypjack/entt#923]
Environment: Windows 11, MSVC, C++20 standard
Version: Newest installed from vcpkg (3.10.1#1)

I'm trying out the `context` example from wiki page. I found that I cannot use `registry.ctx().get<>` function. And cannot use hash string functionality. Are they deprecated? Or I forget to include some header files?

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/24319509/185458999-b2d56cd4-cf71-4e47-a6d5-ed170d164f6d.png">

**Comment by ShenCiao** [comment]
Well, I do find the `registry.ctx().get` function inside the file `entt/entity/registry.hpp`
https://github.com/skypjack/entt/blob/85ca2f356234de3c945667d12857dea2a26c214d/src/entt/entity/registry.hpp#L206
But I cannot find it inside `single_include/entt/entt.hpp`.
https://github.com/skypjack/entt/blob/85ca2f356234de3c945667d12857dea2a26c214d/single_include/entt/entt.hpp

Perheps we got some issues about release system?

**Comment by skypjack** [comment]
The single include file is updated after every release. The new context stuff is part of the upcoming release. So, well 🤷‍♂️ it works as expected. 🙂

**Comment by skypjack** [comment]
As for the hashed string functionalities, `EnTT` follows the same approach of the standard. That is, you've to add an `using namespace entt::literals` somewhere to import the literals and use them (that is, `_hs`).

**Comment by ShenCiao** [comment]
Thanks for guidance on C++. I'm not that experienced. And I don't know the wiki page is updated before the released🙈. I would use the function `find` for now and change it later.

**Comment by skypjack** [comment]
Oh, yeah, the wiki is up-to-date with `master`.
