### ISSUE TITLE
Entt Snapshot produces Json output  litered with "Value" tags

### ISSUE THREAD

**Issue by Impulse21** [skypjack/entt#926]
Not sure this is the best place to ask this, but I have been trying to serialize out my registry with entt::snapshot and cereal::JSONOutputArchive. The produced Json File seems to be unreadable as it contains a bunch of "value" tags. 

Not sure if this is a question for the Cereal repo, or here, but is there a proper way to produce a more readable Json Document for the registry?

Code Example  for snapshot:
`
cereal::JSONOutputArchive output{ os };
            entt::snapshot{ scene.GetRegistry() }.entities(output).component<New::NameComponent, New::TransformComponent, DirectX::XMFLOAT3>(output);
`
Serialize implementation
`namespace PhxEngine::Scene::New
{

    template<typename Archive>
    void serialize(Archive& archive, PhxEngine::Scene::New::NameComponent& name)
    {
        archive("NameComponent", CEREAL_NVP(name.Name));
    }

    template<typename Archive>
    void serialize(Archive& archive, PhxEngine::Scene::New::TransformComponent& transform)
    {
        archive(CEREAL_NVP(transform.LocalTranslation));
    }
}

namespace DirectX
{
    template<typename Archive>
    void serialize(Archive& archive, DirectX::XMFLOAT3& v)
    {
        std::vector<float> float3 = { v.x , v.y , v.z };
        archive(CEREAL_NVP(float3));
    }
}`

Example Output:
` .... "value0": 3,
    "value1": 4294967295,
    "value2": 0,
    "value3": 1,
    "value4": 2,
    "value5": 0,
    "value6": {
        "value0": {
            "value0": 78,
            "value1": 97,
            "value2": 109,
            "value3": 101,
            "value4": 67,
            "value5": 111,
            "value6": 109,
            "value7": 112,
            "value8": 111,
            "value9": 110,
            "value10": 101,
            "value11": 110,
            "value12": 116,
            "value13": 0
        },
        "name.Name": "Hello"
    },....`

**Comment by skypjack** [comment]
> is there a proper way to produce a more readable Json Document for the registry?

I think defining _what we want_ is the first step in getting a proper answer. 🙂 
You've access to all pools and components nowadays. The snapshot class is way older than all this.
You can probably do better by getting the pools and storing the data the way you like. Not sure what Cereal can do for you in this specific case (I don't use it since 🤔 some years ago) but still.

**Comment by Impulse21** [comment]
Ah okay, I just wanted more descriptive key's in JSON document rather then "Value#" tags everywhere. I can look at just accessing the pools and components directly and write the data the way I see fit. Thanks for the quick response! 

Closing out Cheers,

**Comment by Impulse21** [comment]
Not sure if this is the most optimal way to do this, but seems to get the job done. Leaving these here in case any future people have a similar question:

**Example Format**
![JSON](https://user-images.githubusercontent.com/9197147/187084804-12bbc31e-5eaa-4f93-8ef1-5531134bdd6c.png)
 **Code:**
```
            cereal::JSONOutputArchive archive{ os };
            std::vector<Entity> entities;
            entities.reserve(scene.GetRegistry().size());
            scene.GetRegistry().each([&](auto entityID)
                {
                    Entity entity = { entityID, &scene };
                    if (entity)
                    {
                        entities.push_back(entity);
                    }
                });

            archive(CEREAL_NVP(entities));
```
 **Serialize Methods (Note: Entity is just a wrapper of the entt::entity, and a pointer to registry)**
```
    template<typename Archive>
    void serialize(Archive& archive, PhxEngine::Scene::Entity& entity)
    {
        assert(entity.HasComponent<New::IDComponent>());
        assert(entity.HasComponent<New::NameComponent>());
        archive(
            cereal::make_nvp("UUID", (uint64_t)entity.GetUUID()));
        archive(
            cereal::make_nvp("Name", entity.GetName()));

        if (entity.HasComponent<New::TransformComponent>())
        {
            archive(
                cereal::make_nvp("Transform Component", entity.GetComponent<New::TransformComponent>()));
        }
    }

    namespace New
    {
        template<typename Archive>
        void serialize(Archive& archive, PhxEngine::Scene::New::NameComponent& name)
        {
            archive(cereal::make_nvp("Name", name.Name));
        }

        template<typename Archive>
        void serialize(Archive& archive, PhxEngine::Scene::New::TransformComponent& transform)
        {
            archive(
                cereal::make_nvp("Translation", transform.LocalTranslation));
            archive(
                cereal::make_nvp("Rotation", transform.LocalRotation));
            archive(
                cereal::make_nvp("Scale", transform.LocalScale));
        }
    }
```

**Comment by skypjack** [comment]
> I just wanted more descriptive key's in JSON document rather then "Value#" tags everywhere

Yeah, I get your point. I think `Value` is the way of Cereal though.
The snapshot stuff was developed for a company a few years ago when `EnTT` didn't offer direct access to the storage classes. Nowadays, my advice is to save the data out the way you like since everything is available. 🙂

**Comment by Impulse21** [comment]
yeah, I realized that it was the way of Cereal through my Journey. 

I appreciate the help/feedback!

P.S I have been really enjoying working with entt thus far!
