### ISSUE TITLE
View on all entities except some with specific component

### ISSUE THREAD

**Issue by christopheseyler** [skypjack/entt#929]
Hi, It there a way to grap all entities that do not have some component like:

registry.view(exclude<someComponent>) ?

**Comment by skypjack** [comment]
At the moment, you can only iterate all entities (`registry::each`) and `if` them explicitly.
However, what you're asking for is on the roadmap. This is the final interface fyi:
```cpp
auto view = registry.view<void>(entt::exclude<T, U>);
```

**Comment by christopheseyler** [comment]
Great to know. From a performance perspective,  is it more efficient to create a BaseComponent to all entity and query it with my exclude, or the each + if on any_of ?

**Comment by skypjack** [comment]
If you create a base component and exlude it, it doesn't mean that all derived classes are also excluded as a consequence. I guess this answers your question.

**Comment by christopheseyler** [comment]
I meaned a struct BaseComponent that ensure that every entities have one (each time i create an entiti, I add this BaseComponent to it)

then, I can:

```code
auto view = Registry.view<BaseComponent>(exclude<ComponentToExclue>); 
```
I would use this BaseComponent as a workaround to get a view to all my entities

**Comment by skypjack** [comment]
Oh, sorry, didn't get it. Then I would go with the `BaseComponent` since it will be easier to update later on (just replace `BaseComponent` with `void` and you're done).

**Comment by christopheseyler** [comment]
Great. BTW, that lead to a feature request : is there any way to get a signal on a new entity creation (and destruction) as we have with components instance

**Comment by skypjack** [comment]
Available upstream on the `wip` branch. The way it works is:
```cpp
for(auto entt: registry.view<entt::entity>(entt::exclude<T>)) { ... }
```
Signals on entity construction/deletion are also available as in:
```cpp
registry.on_construct<entt::entity>().connect<&my_func>();
```

**Comment by skypjack** [comment]
Available on `master`. :+1:

**Comment by christopheseyler** [comment]
I've just noticed that the size() of this kind of view is not available:

auto myview = registry.view<entt::entity>();

myview.size() returns the total number of entities

auto myview = registry.view<entt::entity>(entt::exclude<MyComponent>);

myview.size() -> ERROR : size() not a member of ...

Is there any workaround ?

**Comment by skypjack** [comment]
`size_hint` @christopheseyler it tells you the maximum number of elements returned by the view.
It's not guaranteed to return exactly N elements but it never returns more than them.
