### ISSUE TITLE
Questionable usage of constexpr in type_info.hpp

### ISSUE THREAD

**Issue by JuanDiegoMontoya** [skypjack/entt#931]
Several member functions in type_info.hpp are marked `constexpr` despite relying on functions or values that are themselves not `constexpr`. For example, `type_info` has a `constexpr` constructor which calls `type_index::value()`, `type_hash::value()`, and `type_name::value()`:
```cpp
    template<typename Type>
    constexpr type_info(std::in_place_type_t<Type>) noexcept
        : seq{type_index<std::remove_cv_t<std::remove_reference_t<Type>>>::value()},
          identifier{type_hash<std::remove_cv_t<std::remove_reference_t<Type>>>::value()},
          alias{type_name<std::remove_cv_t<std::remove_reference_t<Type>>>::value()} {}
```

 Of these three calls, only `type_name::value()` is `static constexpr`, while the others are `static` only. For brevity, I will only show the definition of `type_index`:
```cpp
template<typename Type, typename = void>
struct ENTT_API type_index final {
    [[nodiscard]] static id_type value() noexcept {
        static const id_type value = internal::type_index::next();
        return value;
    }

    [[nodiscard]] constexpr operator id_type() const noexcept {
        return value();
    }
};
```

Trying to initialize a `constexpr` variable with these constexpr functions does not compile and may confuse users (as these functions are clearly marked `constexpr`). This can be demonstrated easily: https://godbolt.org/z/WoxzaMMvs

I suggest removing `constexpr` from these functions where it offers no benefit.

I ran into this issue while researching ways to make a `constexpr` counter for type IDs. While EnTT may not need it, I was shown a possible solution to the problem (which, admittedly, has questionable legality): https://mc-deltat.github.io/articles/stateful-metaprogramming-cpp20

**Comment by skypjack** [comment]
That's questionable either way actually.
The fact is that all `type_*` tools are fully customizable and nothing prevents you from defining a constexpr version of them.
If it happened, it could be an issue not to have i.e. the `type_info` constructor as `constexpr`.
So, let's say, among the choices to make, I made the most flexible one in case of customizations and not the most correct one given the default version. 🤷‍♂️ 

That said, both `hash` and `name` are `constexpr`. The only one left out is `index` at the moment. Am I missing something?

**Comment by skypjack** [comment]
Closing as starving as well as invalid/won't fix.
