### ISSUE TITLE
Question: Given an entity, how to efficiently traverse all types of components and convert them to the corresponding C + + structure type ?

### ISSUE THREAD

**Issue by harukumo** [skypjack/entt#932]
Recently, I am working on implementing the inspector UI using entt:: meta (similar to that in UE4). 

![image](https://user-images.githubusercontent.com/81619976/188175630-fdfd2f12-db5b-499a-beb6-f98fe70a3804.png)

First, I have registered all components in the meta system. The following is an example of TransformComponent:

```
struct TransformComponent
{
    Vector3 position;
    Vector3 rotation;
    Vector3 scale;
    TransformComponent()
        : position(0.0, 0.0, 0.0)
	, rotation(0.0, 0.0, 0.0)
	, scale(1.0, 1.0, 1.0)
    {
	using namespace entt; 
	auto factory = entt::meta<TransformComponent>();
	factory.data<&TransformComponent::scale, entt::as_ref_t>("Scale"_hs)
		.prop("Name"_hs, std::string("Scale"));
	factory.data<&TransformComponent::rotation, entt::as_ref_t>("Rotation"_hs)
		.prop("Name"_hs, std::string("Rotation"));
	factory.data<&TransformComponent::position, entt::as_ref_t>("Position"_hs)
		.prop("Name"_hs, std::string("Position"));
    }
};
```
Then, when drawing the UI, I enumerate all component types and perform explicit type conversion, which requires a lot of tedious work and is not conducive to scalability.
```
if (auto* component = activeScene->GetEntityManager()->TryGetComponent<TransformComponent>(selectedEntity))
{
    DrawComponentUI<TransformComponent>("Transform", *component);
}
if (auto* component = activeScene->GetEntityManager()->TryGetComponent<DirectionalLightComponent>(selectedEntity))
{
    DrawComponentUI<DirectionalLightComponent>("Directional Light", *component);
}
if (auto* component = activeScene->GetEntityManager()->TryGetComponent<SkyLightComponent>(selectedEntity))
{
    DrawComponentUI<SkyLightComponent>("Sky Light", *component);
}
if (auto* component = activeScene->GetEntityManager()->TryGetComponent<CameraComponent>(selectedEntity))
{
    DrawComponentUI<CameraComponent>("Camera Light", *component);
}
if (auto* component = activeScene->GetEntityManager()->TryGetComponent<StaticMeshComponent>(selectedEntity))
{
    DrawComponentUI<StaticMeshComponent>("Static Mesh", *component);
}

more tedious work...
```
So, I am looking for an elegant implementation, like the following pseudocode:
```
foreach ComponentType in selectedEntity
    auto& component = activeScene->GetEntityManager()->GetComponent<need some magic here>(selectedEntity));
    DrawComponentUI<need some magic here>("component_name", component);
```
Is this possible? Or do I have to choose to use the parser to generate code automatically to free my hands?

Thank you in advance, if you can give me some inspiration.

**Comment by codylico** [comment]
_outsider comment; feel free to ignore:_
One thing I did recently for a library was to use a [list-initializater technique](https://en.cppreference.com/w/cpp/language/parameter_pack) from C++11 to "iterate" over different types, similar to this:
```cpp
template <typename ...Types>
class UseTheTypes {
public:
  bool get_results(entity* my_entity) {
    bool results[sizeof...(Types)] =
            { UseOneType<Types>::do_something(my_entity) ... };
    for (int i = 0; i < sizeof...(Types); ++i) {
      /* do something with the results */
    }
  }
}
```
where the functor would do something with the "entity":
```cpp
template <typename T>
class UseOneType {
public:
  static bool do_something(entity* my_entity) {
    /* type specific code here */
  };
};
```
Since you are probably working with C++17, you may be able to use [fold expressions](https://en.cppreference.com/w/cpp/language/fold) to get a similar effect with cleaner syntax.

**Comment by xissburg** [comment]
Considering you have a list of types of components these entities can have, you could put them in a tuple and create a supporting component that stores the indices of the components in that tuple that the entity has, or a bit set. Then you use `std::apply` to invoke a function only for the component types the entity has such as:

```cpp
struct comp_bits {
  std::bitset set;
};

auto &bits = registry.get<comp_bits>(entity);
std::apply([&](auto ... c) {
  int i = 0;
  ((bits.set[i++] ? DrawComponentUI<decltype(c)>(entity) : void(0)), ...);
), components_tuple);
```

**Comment by skypjack** [comment]
You can't really convert an opaque pointer to an actual C++ type _automagically_, I'm sorry. 🙂 
However, you can attach a free function to your meta type and use it. For example:
```cpp
entt::meta<CameraComponent>().func<&DrawComponentUI<CameraComponent>>("draw"_hs);
```
Then you can iterate all storage in a registry (see the doc and the `::storage` function of a registry), get a `void *` to the component using the entity, finally pass it to `meta_type::from_void` (where you resolved the meta type _by name_ this time, using the type info from the storage) to construct a `meta_any` that you can use to invoke `draw`.

**Comment by skypjack** [comment]
I assume this has been answered. I close it as inactive. Feel free to continue the discussion here if you need. Thanks.
