### ISSUE TITLE
Addition to EnTT in Action requested

### ISSUE THREAD

**Issue by hexerei** [skypjack/entt#933]
I have created a simple SDL2 C++ project, as template or starting point for other developers to dive into development with EnTT and keeping it simple to make it easier to use for own implementations, without complex structures.

https://github.com/hexerei/entt-confetti

In fact, only two classes are provided, the Game class to encapsulate all SDL2 functionality and the Scene class, which uses EnTT registry to create entities (here 1000 of them), add components to them, and then update and render them on screen using views.

The code is well documented, absolutely free to use, and I hope useful for others starting their journey on EnTT.

Although it is only leveraging the most basic implementation, it has the advantage of making it easier to continue the journey on exploring EnTT. As a benefit, it comes with a very flexible platform independent makefile, supporting release and debug targets, and with VSCode templates for running and debugging straight out of VSCode.

The EnTT Library is included as submodule, to keep the latest EnTT version available.

The actual implementation, is just some simple colourful confetti snow, that the user can play around with using the keyboard, but showcasing very well the performance on updating 1000 entities all at once.

Feedback to the code is very welcome :) and I hope it will find it's way in the the EnTT in Action list.

Best Regards,
Daniel

**Comment by skypjack** [comment]
> I have created a simple SDL2 C++ project, as template or starting point for other developers to dive into development with EnTT and keeping it simple to make it easier to use for own implementations, without complex structures.

😍

> Feedback to the code is very welcome :) and I hope it will find it's way in the the EnTT in Action list.

Thank you very much for sharing!! I'm more than willing to add it to the list! 👍 
As for a review, I'll look into it and let you know as soon as possible. How do you want me to drop a comment, if any? Is a GH issue good for you?

**Comment by hexerei** [comment]
Completely fine. Thanks!
