### ISSUE TITLE
About setting value to entt::meta_data

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#936]
I have a generic buffer(void*) storing an arbitrary value, I just want to set this buffer back to meta_data using memcpy instead of using the strong type setter(`entt::meta_data.set(instance, value)`), I can get the raw data by `entt::meta_data.get(instance).data()`, but copying memory data seems not work. Is there any way to achieve this? Thanks!

**Comment by skypjack** [comment]
Well, if you **do** want to use `memcpy` (and I'm tempted to discourage this), you've the `void *` for the source and the destination already while the meta type also returns you the _size_ of the underlying type. That is, you've all you need for a `memcpy`.
What's exactly the problem? I don't fully get it to be honest. Sorry. My advice is still to use a _setter_ after a call to `meta_type::from_void` if you want to stay in the erased field without incurring the risks of a `memcpy`.

**Comment by hls333555** [comment]
> Well, if you **do** want to use `memcpy` (and I'm tempted to discourage this), you've the `void *` for the source and the destination already while the meta type also returns you the _size_ of the underlying type. That is, you've all you need for a `memcpy`. What's exactly the problem? I don't fully get it to be honest. Sorry. My advice is still to use a _setter_ after a call to `meta_type::from_void` if you want to stay in the erased field without incurring the risks of a `memcpy`.

Thanks for the reply!
In fact, I'm not stick to use `memcpy`, all I want is to set value to data directly using my buffer (void* pointer). However, I cannot find from_void() and I don't know how to call this. Please help. Thanks a lot!

**Comment by skypjack** [comment]
`meta_type::from_void` is available on `master` but it isn't part of a release yet.
As for the pointer stability, the address of the underlying element doesn't change unless you move the containing object (in this case, it only changes if the element is embedded, otherwise it's still stable).

**Comment by hls333555** [comment]
> `meta_type::from_void` is available on `master` but it isn't part of a release yet. As for the pointer stability, the address of the underlying element doesn't change unless you move the containing object (in this case, it only changes if the element is embedded, otherwise it's still stable).

Thanks! But it seems that I do not explicitly move the TestComponent above, and it still does not work. Could you please help me fix the above code? Thanks!

**Comment by skypjack** [comment]
You're not telling to meta to return your data member by reference. Therefore, it's returned by copy.
What you want is likely `.data<&TestComponent::FloatVar, entt::as_ref_t>("FloatVar"_hs)`.

**Comment by hls333555** [comment]
> ```c++
> , entt::as_ref_t
> ```

Thanks for explanation! However, I have another question, if my float variable uses getter and setter like this:
```C++
float GetValue() const { return FloatVar; }
void SetValue(float value) { FloatVar = value; }
```
In this case, I cannot register the data using `entt::as_ref_t`, so that I am not able to use `memcpy` to properly copy my buffer to the data right? Is there a way to solve it in this situation? Thanks!

**Comment by skypjack** [comment]
Well, the policy is **always** available and you can pass `entt::as_ref_t` also when using a setter and getter pair.
As you correctly pointed out, the problem is your getter that returns the element by copy. Meta cannot really work around it.
In this case, you're literally saying (as an user): _I'll never ever return this data member by reference and my getter prevents it_.
So, no, there is not an easy way to get around the will of the final user in general. 🙂

**Comment by hls333555** [comment]
> Well, the policy is **always** available and you can pass `entt::as_ref_t` also when using a setter and getter pair. As you correctly pointed out, the problem is your getter that returns the element by copy. Meta cannot really work around it. In this case, you're literally saying (as an user): _I'll never ever return this data member by reference and my getter prevents it_. So, no, there is not an easy way to get around the will of the final user in general. 🙂

Thanks for your help! I am sure what I should do now!

**Comment by skypjack** [comment]
You're welcome. 👍 🙂
