### ISSUE TITLE
Collector for construct and destruct?

### ISSUE THREAD

**Issue by ShenCiao** [skypjack/entt#937]
When using class `entt::observer`, only collector for update signal `entt::collector.update` is available. But we do have three kinds of signals associated with component. Perhaps for some reasons Entt cannot add them?

It's not a feature request. Just for curiosity. Maybe don't be worried about adding them.

**Comment by skypjack** [comment]
Poorly named, but that's `.group<T>`. 👍 
Otherwise, you can just use an `entt::storage<void>` and connect it to the registry signals. Then you can construct a view with it as in `entt::basic_view view{storage}` and combine it with other views from the registry as in `view | registry.view<U, V>()`.

**Comment by ShenCiao** [comment]
My stupidness definitely gonna kill myself. I've read the document about `.group<T>`  four or five times but never realize it can do that😵. I will have a try on it.

**Comment by skypjack** [comment]
No worries at all. It's definitely not your fault. 👍
