### ISSUE TITLE
About setting shared_ptr value to meta_data using data.set(instance, value)

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#938]
I have registered a by-reference shared_ptr getter, but I cannot set value using `data.set(instance, value)`, the following code shows what I mean:
```C++
class TestClass
{
public:
	std::shared_ptr<int32_t> IntPtr;
};

struct TestComponent
{
	std::shared_ptr<TestClass> TestPtr;
	TestComponent() = default;
	TestComponent(const TestComponent&) = default;

        std::shared_ptr<int32_t>& GetIntPtr() const { return TestPtr->IntPtr; } // Here I return the non const reference
};

int main()
{
        using namespace entt::literals;
	entt::meta<TestComponent>().type().data<nullptr, &TestComponent::GetIntPtr, entt::as_ref_t>("TestPtr"_hs); // Here I register the data by ref

	entt::registry reg;
	auto entity = reg.create();
	auto& testComp = reg.emplace<TestComponent>(entity);
	testComp.TestPtr = std::make_shared<TestClass>();
	entt::meta_any compInstance{ entt::forward_as_meta(testComp) };
	const auto compType = compInstance.type();
	for (const auto data : compType.data())
	{
		data.set(compInstance, std::make_shared<int32_t>()); // After this, the IntPtr of TestPtr is still nullptr
	}
}
```
Is there anything I am missing? Please help, thanks!

**Comment by skypjack** [comment]
I mean, by doing this:
```cpp
.data<nullptr, &TestComponent::GetIntPtr, entt::as_ref_t>
```
You're literally creating a read-only property (no setter). If you check the return type of `set`, it likely converts to false.  
You don't even need the `GetIntPtr` for the getter by the way. The following should work (take this with a grain of salt, I'm from mobile):
```cpp
.data<&TestComponent::TestPtr, entt::as_ref_t>
```
If you've still problems, let me know but also get prepared to wait until Monday since I'm out of home.

**Comment by skypjack** [comment]
I assume this is answered. Let me know if this isn't the case. Otherwise I'll close the issue in a few days. 👍
