### ISSUE TITLE
Getting pointers to all components attached to an entity

### ISSUE THREAD

**Issue by eugen-bondarev** [skypjack/entt#939]
Let's say I have following components:
```
struct Transform : ComponentBase {
  void DrawSettings(EditorContext&) override { /* */ }
};
```
```
struct Mesh : ComponentBase {
  void DrawSettings(EditorContext&) override { /* */ }
};
```
```
struct Material : ComponentBase {
  void DrawSettings(EditorContext&) override { /* */ }
};
```
With this base class:
```
struct ComponentBase {
  virtual void DrawSettings(EditorContext&) {}
};
```

Let's assume those 3 components are attached to the same enity (`entt::entity player`).

Now my question:
is there any way I can iterate over all the components attached to `player` that inherit from `ComponentBase` and call their `DrawSettings` method?

I tried to derive a working approach from this docs page https://entt.docsforge.com/master/poly/#deduced-interface, but unfortunately without any success. Perhaps, you could provide a short snippet implementing this idea?

Thank you very much for your work! :)

**Comment by skypjack** [comment]
If all your components derive from `ComponentBase`, then that's trivial.
Otherwise, there it [this PR](https://github.com/skypjack/entt/pull/871) that tries to address the problem as well as an example of mine (link in the discussion) that should work with the current version of EnTT (less flexible then the proposed solution but you don't have to wait at least).
That being said, if your problem is that you want to use polymorphism when working with an ECS architecture, imho you're not on the right path. When you want to _draw_ something, just add a `draw_me` component to the entity and iterate over it. It's way more ECS-ish than what you're trying to achieve. My two cents.

**Comment by eugen-bondarev** [comment]
Thanks for your reply :slightly_smiling_face: 
What I am trying to achieve here is just basic drawing of component settings, so I would implement the `DrawSettings` function something like this:

```
void Mesh::DrawSettings(EditorContext&) {
  ImGui::Text(&meshPath);
}
```

```
void Transform::DrawSettings(EditorContext&) {
  ImGui::DragFloat3(&position);
  ImGui::DragFloat3(&rotation);
  ImGui::DragFloat3(&scale);
}
```

```
void Material::DrawSettings(EditorContext&) {
  ImGui::Text(&diffuseTexturePath);
}
```

That's why I need different *implementations* of `DrawSettings` per class. And because of this, creating a `draw_me` component is probably inappropriate in this case, or am I missing something? Also, can you please specify a bit more concrete what example in [this PR](https://github.com/skypjack/entt/pull/871) you mean? Thank you very much!

**Comment by skypjack** [comment]
Hey, sorry for the late reply. I'm having a bad time recently. 🙏 
In general, polymorphism and components are orthogonal concepts. The typical approach in this case is to split your hierarchy into different components that you assign to entity and elaborate with different systems. Trying to stuff polymorphic types into an ECS model can quickly lead to headaches.
That said, yes, while I don't highly recommend it, it's still possible with EnTT. The PR offers a refined and somewhat complete solution that is probably overkilling for your case (dunno actually, I've only scratched the surface of your issue so far).
As for the example, [here](https://godbolt.org/z/W4f8zfsGz) it is the one I meant (fixed to make it work with the last version of EnTT). 👍

**Comment by eugen-bondarev** [comment]
Thank you very much for this example, this should do the trick!
I apologize for my delayed reply, too 🙂
