### ISSUE TITLE
how to pass a component as function argument?

### ISSUE THREAD

**Issue by peeterdog** [skypjack/entt#941]
Modern c++ is very difficult for me and the level here is high. please i want to do something like this:

```cpp
//comp.hpp

struct _t1_tag {};
struct _t2_tag {};
struct _t3_tag {};

using id = entt::identifier<_t1_tag, _t2_tag, _t3_tag>;
 

constexpr auto ty_t1_tag = id::type<_t1_tag>;
constexpr auto ty_t2_tag = id::type<_t2_tag>;
constexpr auto ty_t3_tag = id::type<_t3_tag>;



//other.cpp
#include "comp.hpp"
void Game::setComp(entt::entity e, const entt::id_type??? p_comp)
	{
			m_registry.emplace<p_comp>(e);
	}
```

sorry for the english

**Comment by skypjack** [comment]
You can't use a runtime parameter as a template argument.
I mean, you can't do that in C++ and therefore you can't do that with EnTT. 🤷‍♂️ 
However, you can use the _opaque `emplace`_ to achieve the same result maybe?
```cpp
void Game::setComp(entt::entity e, const entt::id_type p_comp) {
    m_registry.storage(p_comp).emplace(e);
}
```

**Comment by peeterdog** [comment]
Finally i decided to use a template solution. For nested function calls i modified some other stuff make them templates too.. ... 


		void setComp(const entt::entity e)
			{
                       m_registry.emplace<T>(e);
			}


For now this simple aproach works super fast in main loop.. im still searching for a param solution...

**Comment by peeterdog** [comment]
Im really sorry for the mess my browser is very old and my conection is about 10 KB/s and all stuff with asycronous load like actions menu in the posts wont load so i cant edit or delete posts...  i forgot to put  template stuff

		template <typename T>
		void setComp(const entt::entity e)
			{
                       m_registry.emplace<T>(e);
			}

:)

**Comment by skypjack** [comment]
No worries at all. I'm glad you solved. Closing the issue then. 👍
