### ISSUE TITLE
Using multiple registry.group<>() calls gives ENTT_ASSERT "Conflicting groups"

### ISSUE THREAD

**Issue by TQwan** [skypjack/entt#942]
I read your blog and I am trying to use multiple owning groups, since your blog described that it was the fastest way to iterate.

I keep getting conflicts when I try to use multiple 'owning groups'.
When I change the group to a view it works fine.

In the entt.hpp file it says:
     * Groups are created on the fly and share with the registry its internal
     * data structures. Feel free to discard them after the use.
     * Creating and destroying a group is an incredibly cheap operation. As a
     * rule of thumb, storing a group should never be an option.

My Assumption: I think the group variables are not destroyed after the method call ended.

Are groups only unique by the first type that is provided and is this causing conflicts?

Also: I don't need any sort functionality, just iterate and update / read variables of components mostly.

Anyway the simplified code looks something like this:
```
main() {
    init();
    loop();
}

// called once on startup
init() {
	// Fill the entt registry with a bunch of entities with components.
	// Example: A single entity now has components:
	// - TransformComponent
	// - Component3D
	loadComponents();
	
	// Do some other stuff...
	
	// Determine which entities are visible and add a RenderableComponent to those.
	auto all3DComponents = registry.group<Component3D, TransformComponent>();
	for(auto entity: all3DComponents) {
		registry.emplace<RenderableComponent>(entity);
	}
	
	// Example: A single entity now has components:
	// - TransformComponent
	// - Component3D
	// - RenderableComponent
	
	initRenderSpecific();
	
	// Example: A single entity now has components:
	// - TransformComponent
	// - Component3D
	// - RenderableComponent
	// - Renderer3DVulkanComponent
}

// called by init
initRenderSpecific() {
	// Determine renderer (opengl / vulkan / etc...)
	
	// Create specific render object for the render type.
	// So iterate all renderable components.
	// >>>>>>>>>>>>>>>>>>>>>>>>>>>> THE METHOD BELOW sometimes HAS A CONFLICT <<<<<<<<<<<<<<<<<
	auto allRenderableComponents = registry.group<TransformComponent, RenderableComponent>();
	// <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
	
	for(auto entity: allRenderableComponents) {
		registry.emplace<Renderer3DVulkanComponent>(entity);
		
	}
}

// called by main.
loop() {
    while(true) {
        update();
        render();
    }
}

// called allot by loop
update() {
	>>>>>>>>>>>>>>>>>>>>>>>>>>>> THE METHOD BELOW HAS A CONFLICT <<<<<<<<<<<<<<<<<
	auto group = registry.group<TransformComponent, Renderer3DVulkanComponent>();
	//... loop group and update values of Renderer3DVulkanComponent based on camera matrix * TransformComponent
	<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
}

// called allot by loop
render() {
	// Apparently a group can't have a single component, so can't iterate fast, so should I use a view or use group with an additional component that we just don't use?
	auto view = registry.view<Renderer3DOpenGLComponent>();
       // or
	auto group = registry.view<Renderer3DOpenGLComponent, RenderableComponent >();
	
        // .. loop view/group and for each Renderer3DOpenGLComponent call renderComponent().
       
        // Note: RenderableComponent is just a component with bool visible, which in this case is always true, it is thus not actually used.
        // Renderer3DOpenGLComponent are only added for components that have a RenderableComponent with visible true)
}

```

Blog I'm referring to: https://skypjack.github.io/2019-03-21-ecs-baf-part-2-insights/

*note: all for loops are actually parallel, an example looks like this:
```
std::for_each(std::execution::par, std::begin(group), std::end(group), [&group, &currentLocation, &moveVector, this](auto &entity) {
	// *** loop code here ***
};
```
** To get this working for all platforms I had to compiled my own version of clang, libc, pstl and tbb, since windows and android do not have parallel support out of the box when compiling with clang. **

**Comment by skypjack** [comment]
> My Assumption: I think the group variables are not destroyed after the method call ended.

They are not. Groups have an initialization step that you don't want to pay all the times. Therefore, you undergo this cost once (when the pools are likely empty or almost empty) and that's it.
The error about conflicting groups is due to:
```cpp
registry.group<TransformComponent, RenderableComponent>();
```
Versus:
```cpp
registry.group<TransformComponent, Renderer3DVulkanComponent>();
```
Where `TransformComponent` can be an owned type only for a group.
That being said, I suggest you to work with views until you've a perf problem, then optimize hot paths (switching to groups) if this ever happens.

**Comment by skypjack** [comment]
Closing as solved/starving issue. Feel free to continue the discussion here if this isn't the case.
