### ISSUE TITLE
Entity component serialization

### ISSUE THREAD

**Issue by jaredhan** [skypjack/entt#945]
Hello！
 I would like to ask a question.
if there are more components and you don't have to specify which specific component types to serialize, is there a way to serialize all the components

**Comment by skypjack** [comment]
There is a way to iterate all storage classes in a registry. They also return their type id on request.
Therefore, if you're using a reflection system or just stored aside serialization functions, you can lookup the right call.

**Comment by skypjack** [comment]
Closing as solved/starving issue. Feel free to continue the discussion here if this isn't the case.
