### ISSUE TITLE
Questions about registry destruction

### ISSUE THREAD

**Issue by hls333555** [skypjack/entt#947]
When a registry is destructed, will all components' on_destroy being called? And do I need to disconnect all components' on_XXX callbacks? Thanks!

**Comment by skypjack** [comment]
You don't need to disconnect signals as they are discarded upon destruction anyway.
As for the signals, they aren't invoked by default but you can _force_ it by calling `clear` before destroying the registry.
We can match the tastes of all users this way, you know. 🙂
