### ISSUE TITLE
Parallel std::for_each execution for multi-component view is not working as expected

### ISSUE THREAD

**Issue by Casqade** [skypjack/entt#949]
Given this code example:

```
auto view = registry.view <const Component1, const Component2> ();

std::for_each(std::execution::par, view.begin(), view.end() [&] (auto entity) {
  // ...
});
```
The lambda here is executed sequentially. Debugging shows that the view does not meet a requirement of a random access iterator and `std::foreach` implementation chooses a sequential candidate function to iterate the view. 

Manually simulating the requirement from STL implementation gives assertion failure:

```
constexpr bool is_rai = std::is_same_v <typename std::iterator_traits<decltype(view.begin())>::iterator_category, std::random_access_iterator_tag>;
static_assert(is_rai); // <-- static assertion failed
```

But for single-component view the assertion is successful. What can I do in this situation to force parallel code execution? Using `tbb::parallel_for_each` instead of `std::for_each` produces desired results but I wonder whether it is possible to stick with STL. 

By the way, does the [wiki example](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#iterators) really run in parallel? Contrary to my case, that example uses `parallel_unsequenced_policy`, but I suspect random access iterator requirement should also be unsatisfied there...

**Comment by skypjack** [comment]
Indeed, single type views return random access iterators while multi type views return input iterators. Since the beginning.
A possible solution to stick with the stl is to get the leading storage from `view::handle`, split it on multiple threads, then invoke `view::contains` before elaborating the entity.

**Comment by skypjack** [comment]
No, wait, I'm wrong. View iterators are at least in the forward iterator category, which is also the same required by `std::for_each`. What version of `EnTT` are you using?

**Comment by Casqade** [comment]
> Indeed, single type views return random access iterators while multi type views return input iterators

Ok, but the corresponding [wiki section](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#iterators) seems to be somewhat vague on that detail (especially the sentence _"Most of the time they meet the requirements of random access iterators"_). Which is confusing... 

> A possible solution to stick with the stl is to get the leading storage from `view::handle`, split it on multiple threads, then invoke `view::contains` before elaborating the entity.

Actually, following your advice and passing the `view::handle` iterators into `std::for_each` turned out to be enough to satisfy STL requirements for parallel execution :) The code snippet looks like this:
```
auto view = registry.view <Component1, Component2> (); // <-- const entt::registry&
auto& handle = view.handle();

std::for_each( std::execution::par, handle.begin(), handle.end(),
[&] ( const auto entity )
{
  auto [comp1, comp2] = view.get <const Component1, const Component2> ();
  // ...
});
```
I'm not sure if I interpreted your advice correctly (since I don't invoke `view::contains`), but the snippet compiles and runs successfully. To my surprise, it even manages to consistently outperform the `tbb::parallel_for_each` version. 



> ~Oh, yeah, the example wants a forward iterator.~

Wait, I was trying to point out that[ `std::for_each`](https://github.com/gcc-mirror/gcc/blob/32a06ce38a38bf37db468f0e6c83520fcc221534/libstdc%2B%2B-v3/include/pstl/glue_algorithm_impl.h#L62) called with `std::execution::par` policy [resolves ](https://github.com/gcc-mirror/gcc/blob/32a06ce38a38bf37db468f0e6c83520fcc221534/libstdc%2B%2B-v3/include/pstl/algorithm_impl.h#L109)into a sequential loop if the passed iterator is not a [random access iterator](https://github.com/gcc-mirror/gcc/blob/32a06ce38a38bf37db468f0e6c83520fcc221534/libstdc%2B%2B-v3/include/pstl/execution_impl.h#L139). And debugging confirms that, so I believe in the context of parallel `std::for_each` a random access iterator is mandatory. Though, the `view::handle` solution is probably a good enough alternative (thank you very much!)

> What version of `EnTT` are you using?

Oops, my bad - forgot to mention the most important bits! 
I'm compiling the latest release tag [v3.10.3](https://github.com/skypjack/entt/tree/v3.10.3) with **GCC 12.2.0** on both Windows (_MSYS2_ environment) & Arch Linux.

**Comment by skypjack** [comment]
> I'm not sure if I interpreted your advice correctly

It's more like this:

```cpp
auto view = registry.view <Component1, Component2> (); // <-- const entt::registry&
auto& handle = view.handle();

std::for_each( std::execution::par, handle.begin(), handle.end(), [&] ( const auto entity ) {
  if(view.contains(entity)) {
    auto [comp1, comp2] = view.get <const Component1, const Component2> ();
    // ...
  }
});
```

The handle might return more entities than those with all the components. That is, the handle is just one of the storage classes of the view, roughly speaking the smallest. You aren't guaranteed that all the returned entities also have all the components.

> Wait, I was trying to point out that[ std::for_each](https://github.com/gcc-mirror/gcc/blob/32a06ce38a38bf37db468f0e6c83520fcc221534/libstdc%2B%2B-v3/include/pstl/glue_algorithm_impl.h#L62) called with std::execution::par policy [resolves ](https://github.com/gcc-mirror/gcc/blob/32a06ce38a38bf37db468f0e6c83520fcc221534/libstdc%2B%2B-v3/include/pstl/algorithm_impl.h#L109)into a sequential loop if the passed iterator is not a [random access iterator](https://github.com/gcc-mirror/gcc/blob/32a06ce38a38bf37db468f0e6c83520fcc221534/libstdc%2B%2B-v3/include/pstl/execution_impl.h#L139).

Isn't this an implementation detail of the specific compiler? As far as I remember, `for_each` wants a forward iterator and does its best to split the execution over multiple threads.
I wonder what other vendors do here. It's odd that it let's say _doesn't work as expected_ even if we satisfy the requirements as dictated by the standard. 🤔

**Comment by Casqade** [comment]
> You aren't guaranteed that all the returned entities also have all the components

Oh, I got it now, thanks for the correction! 

> Isn't this an implementation detail of the specific compiler?
> I wonder what other vendors do here

Well, looks like you're right. Some digging revealed that Microsoft' STL [implementation](https://github.com/microsoft/STL/blob/ff83542af4b683fb2f2dea1423fd6c50fe3e13b0/stl/inc/execution#L1202) actually wants [forward iterators](https://github.com/microsoft/STL/blob/ff83542af4b683fb2f2dea1423fd6c50fe3e13b0/stl/inc/xutility#L1456). Similar to GCC, LLVM/Clang relies on _pstl_ for parallelisation and requires a [random access iterator](https://github.com/llvm/llvm-project/blob/d9c52c31a0fee22414bb4024ee5b203fe86ef5bb/pstl/include/pstl/internal/algorithm_impl.h#L118). Probably that requirement [comes from their optional dependence on TBB](https://www.cppstories.com/2018/11/pstl/#about-intel-parallel-stl:~:text=Intel%E2%80%99s%20library%20needs%20stronger%20condition%3A%20Random%20Access%20Iterators). Thus, I don't know whether this specific standard violation should be considered as a compiler bug or just as an implementation peculiarity. 

Anyway, the solution you proposed ensures compiler-independent `for_each` behaviour, and there are no problems on _EnTT_ side, so I'm closing the issue. Also, I think it's worth mentioning this inconsistency in the corresponding wiki section and providing your last code snippet as the example. 

So... that's it. Thanks a lot for both your help and your _magnificent_ library, love it 🥇

**Comment by skypjack** [comment]
You're welcome. Thanks for using it (and for the interesting discussion!!). 👋
