### ISSUE TITLE
EnTT and C++17

### ISSUE THREAD

**Issue by skypjack** [skypjack/entt#95]
Modern C ++ has reached revision 17 for quite a while now.  
`EnTT` is stuck in the revision 14 currently because of several reasons: laziness, willingness to support a widely used revision, requests from users, laziness again, and so on.  

However, I'd like to port the library to the latest revision mainly because:
* I like C++17 and it contains a lot of things I'd like to use in `EnTT`
* Resulting code would be cleaner. As an example:

      signal.sink().connect<&Listener::member>(&listener);

  Instead of:

      signal.sink().connect<Listener, &Listener::member>(&listener);

  But also `entt::Prototype` instead of `entt::DefaultPrototype` as an alias for `entt::Prototype<entt::DefaultRegistry::entity_type>` and so on.

* We can rely on things like `std::execution::par` (see #94) and work on multi threading
* We can rely on `pmr::` namespace (see #80 and some other issues that talk about making `EnTT` allocator-aware)
* ... AOB

The idea is to maintain a branch `cpp14` until the end of the year, then interrupt the support and leave the revision 14 behind if nobody comes up that either wants to maintain it or is willing to support me to maintain the port.  
New features or at least the biggest ones won't be available on that branch. As an example, multi threading support could be developed only on `master` and therefore it will be available only to users that can use C++17.

Comments and/or feedback on this are highly appreciated.

**Comment by danielytics** [comment]
I already compile all of my code as C++17, so in principal, I'm all for this. However, I do notice that at least my OS X Apple Clang compiler does *not* have full C++17 support yet (some fancy things like structured binding declarations work, but some simple stuff like `std::optional` still lives in `<experimental/optional>` and I had trouble getting it to work). I haven't tested other compilers.

So, for me personally, its still too new too soon, although, as I said, I do compile as C++17 regardless. Maybe by end of year support will be good enough to move completely to 17.

**Comment by skypjack** [comment]
@danielytics Yeah, you got the idea. Supporting C++14 until end of the year so as to give enough time to C++17 to spread through our life. In the meantime, branch `cpp14` will receive support and all the features that can be easily ported to C++14. Major changes that require stuff from C++17 won't be available for obvious reasons and that's all.  
Also, do not forget that `EnTT` is tested on travis and appveyor, so your os x apple clang compiler will be definitely one of those that **must** work with the _C++17 version_ of `EnTT`. I'll do my best to make the library work on the platforms currently supported, don't worry about this.  

After all, `EnTT` is already good enough for most of the applications. Multi threading, allocators and all these fancy things are a plus that users can have with the _C++17 version_. In all the other cases, the current implementation, that is the _C++14 version_ is there for all those interested in it.

Sounds good?

**Comment by danielytics** [comment]
Yep, that sounds good. I'm hoping that compilers will have caught up enough anyway because I want to be able to use C++17 features too, when it makes sense to do so.

Just for the record, my compiler is `Apple LLVM version 9.1.0 (clang-902.0.39.2)`. I wasn't able to find a newer version and Apple's annoying versioning makes it hard to determine what version of LLVM/Clang this really is since Apple don't seem to publish the upstream version number anymore :(

**Comment by Milerius** [comment]
It is absolutely necessary to pass on c++ 17, in addition to the comment above, is not really true because I am on OSX, and my c++ 17 works perfectly well, same on MSVC & on GCC 7.2 minimum, it is enough for osx to have clang 6.0

**Comment by Kerndog73** [comment]
I think C++17 language features are mostly supported across the major compilers. But C++17 standard library support is a bit patchy. So as long as we're careful with standard library usage, we should be good.

**Comment by danielytics** [comment]
I’ll doublecheck my version of Apple libc++, but `std::optional` is in `experimental` for me (I have to include `<experimental/optional>` and link with `-lc++experimental`, but that wasn’t enough as I couldn’t figure out what namespace optional was in so I gave up).

But yes, the language features seem to work — it’s the standard library that isn’t fully there yet, at least for me.

**Comment by Milerius** [comment]
I think that OSX should warn users that it would be better to use an external version of clang / libc ++ like LLVM 6.0, for my part that's what I did and I have all the features of 17 full c ++ at my disposal, I will soon go on LLVM 7.0

**Comment by skypjack** [comment]
Ok, let's move towards C++17 and see what happens.  
If you're willing to help me, I'll push sooner or later a branch called `cpp17` that contains a first review along this way. Before to merge it on `master` and in case travis and appveyor both like it, it would help if you can review it as well and post your suggestions.  
I'll keep it there for a few days because of this, then I'll merge everything on `master` and bye bye C++14. :-)

**Comment by danielytics** [comment]
I’ll happily test it on my compiler and let you know if it works.

It sounds like this Apple compiler may be the lowest common denominator with c++17 standard library support so if that works, then the other popular compilers are probably going to work too.

**Comment by dbacchet** [comment]
sorry for being late in the thread.
Please keep a branch active with c++14 support (freeze it to today's version, if you like) for hot fixes; if somebody is using EnTT in production environment, changing compiler is not something that can be done easily. For example I'm stuck with gcc5.4 for at least another couple of years...
Also some embedded targets don't support anything more than c++11, but that's already out of the window.

**Comment by skypjack** [comment]
@dbacchet Sure, it makes sense.  
Actually I plan to port on the C++14 branch improvements as long as possible.  
Also, if you need a C++11 version of `EnTT`, I don't think it's a big amount of work. At least for the ECS part, not sure about the rest of the library. Is it a requirement for you?

**Comment by skypjack** [comment]
As a side note, I just realized that the signalling stuff becomes much more flexible with C++17. As an example, to a signal that accepts `void(int)`, it will be possible to attach functions with a definition like `void(const int &)`, more or less as it works for `std::function`. As long as return value and parameters are convertible, everything should work just fine and also the dispatcher will benefit from this!! Nice to know.

**Comment by skypjack** [comment]
Ok, when #99 is closed, I can start working to port everything to C++17.  
I've also decided what will be the next feature and I'm pretty sure most of you will appreciate it! :-)  
Stay tuned.

**Comment by skypjack** [comment]
Of course, I'll support C++14 as long as possible and I'll try to integrate new features as well.  
Still to decide what the `master` branch will contain and what I'll put on its dedicated branch.  
@dbacchet If you need a C++11 port, do not hesitate to contact me.

**Comment by skypjack** [comment]
It look like both VS and clang on MacOS don't like much my first attempt.  
I love those compilers that reject valid code... :rage:

**Comment by Milerius** [comment]
@skypjack 

On OSX you should use clang 6.0, XCode doesn"t support fold expression and the c++17 library is not full

**Comment by skypjack** [comment]
Interesting. I've not a Mac with me, so this kind of comments are really precious!! Thank you.

**Comment by skypjack** [comment]
@Milerius Something along this line would work?
```
before_install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update && brew install llvm && export clang-6.0; fi
```
If you've ever tried it with travis, otherwise I'll push and we'll see... :-)

**Comment by skypjack** [comment]
Uhm... wai, it doesn't make much sense. I already know that it works fine with clang 6 because I'm testing it with the same build.  
Probably it's worth it disabling the check on osx until xcode fully supports C++17.

**Comment by skypjack** [comment]
It looks like `std::is_aggregate[_v]` [isn't supported yet](https://developercommunity.visualstudio.com/content/problem/243668/stdis-aggregate-stdis-aggregate-v-are-missing.html) by VS.  
I strongly suspect that the times are not that ready for a portable version of `EnTT` in C++17, unless I decide to fill the library with a bunch of `ifdef` or kind of all around.

**Comment by ArnCarveris** [comment]
@skypjack keep it more portable.

**Comment by skypjack** [comment]
@ArnCarveris `master` is still developed with C++14. `cpp17.something` branches will be a work in progress to keep up-to-date a version of `EnTT` that will replace `master` probably at the end of the year. Until that moment, I don't care if it doesn't compile with VS because VS doesn't fully support C++17 yet, it's not something for which I can do much after all.
