### ISSUE TITLE
Sort a registry/view

### ISSUE THREAD

**Issue by Squeemos** [skypjack/entt#952]
So I'm trying to sort my list of objects by the transforms so I can draw them according to their z_order, but when I do so I get some problems.

```c++
registry.sort<Transform>(Transform::compare);

inline static bool compare(const Transform& left, const Transform& right) { return left.z_order < right.z_order; }
```

When I do this, things now draw properly (hurray!) but I get problems with entities owning the correct components now. Essentially what I want is to order the objects by their z order in increasing order for drawing, but keep each entitiy's ownership correct.

Is there a better way I should be sorting? Currently the render just iterates through this view
```c++
current_scene->registry.view<const Transform, const Material>();
```

and then draws in order.

**Comment by skypjack** [comment]
🤔 
This is what I do literally everywhere actually. Do you have a repro for your issue?
There might be something more here but it's hard to say without looking at the code.

**Comment by Squeemos** [comment]
I do! Yeah it seemed like I might be doing something wrong which is why I'm confused.
https://github.com/Squeemos/VideoJames

Inside source/systems/SceneManager.cpp is where I would sort the registry (each registry is hosted per scene). Then a view from the registry is passed to the renderer to render. As a current hot patch to get the render order to work (at least for now) I create a multimap to iterate through. This is at the top of source/systems/Renderer.cpp.

If I move the render code from renderer into the loop at the bottom
```c++
//for (const auto& [e, transform, material] : renderables.each())
//{
//	// render everything the same way I currently do
//}
```
I get the following error:
``` Assertion failed: !owned<Type>(), ```

**Comment by Squeemos** [comment]
To add on because I forgot, inside scenes/Sandbox is where I add the entities to the registry in case I'm doing something incorrect there. Same for the "movement controller" which allows me to change the z_order of the entity.

**Comment by skypjack** [comment]
A whole project isn't exactly _a repro_. 😅 
Anyway, the error makes me think that you're trying to sort the pool of a type that is owned by a group.
This isn't allowed and it's UB. It would also explain the other errors around. I suggest to turn your groups into views and test it again before doing anything else.

**Comment by Squeemos** [comment]
Oh no I can't read 😅 okay so when I swap to using a view it worked perfectly! I guess I'm a bit fuzzy on what you mean by it is owned by a group. Do the pools of groups act differently than the pools of views?

**Comment by skypjack** [comment]
Yeah. You can imagine a view as a tiny pointer to an otherwise const pool that isn't affected in any way by the view itself. On the other hand, when a group _owns_ a pool, it also sorts the elements in the pool to maximixe the performance. Therefore, you can't just sort them the way you like, it would conflict with the group otherwise.
