### ISSUE TITLE
Raw iteration over owned group

### ISSUE THREAD

**Issue by LeifHenriksen** [skypjack/entt#955]
Hi,

I would like to know if it is possible to iterate over an owned group using raw pointers like showed [here](https://skypjack.github.io/2019-04-12-entt-tips-and-tricks-part-1/), the group `raw` method was removed here https://github.com/skypjack/entt/commit/8e6439c3d1408b7eed214d61ad044322ce85fea0 and from what I understood from this https://github.com/skypjack/entt/issues/818#issuecomment-1002650357 answer trivial iteration is no longer possible because group storage is now paged and no longer a contiguous array.

I am trying to do something like this. 
```c++
auto group = reg.group<component::position, component::physics>();
auto pos   = *group.storage<component::position>().raw();
auto physx = *group.storage<component::physics>().raw();
for(size_t i = 0; i < group.size(); i++)
    (physx + i)->integrate(*(pos + i), delta);
```

All my entities and components are created during an initialization step and the registry is not modified after, so I dont need pointer stability. Eventually I would like to send raw component arrays to the **GPU** and if they are not contiguous this is not going to work.

So is there any way to disable paging and get the old SoA behavior back?

Thanks.

**Comment by skypjack** [comment]
> So is there any way to disable paging and get the old SoA behavior back?

It's actually something I'd like to allow, although right now it's only possible by specializing the storage class.
Pagination isn't only abouth pointer stability though, it's also about avoiding large (re)allocations that can cause spikes.

That being said, you can get where you want actually, with or without using multiple pages to get the job done.
The `raw` method is still there, just not in the group interface:

```cpp
auto group = registry.group<T, U>();
auto &storage_for_t = group.storage<T>();
T **all_ts = storage_for_t.raw();
```

`all_ts` is a pointer to the pages for `T` and the size of these pages is known:

```cpp
constexpr std::size_t page_size_for_t = entt::component_traits<T>::page_size;
```

So, here you've already all you need to pass the component arrays to your gpu, `page_size` at a time for both `T` and `U`.
Then, if you want to avoid multiple calls, you can cheat on the page size and `EnTT` won't complain:

```cpp
struct T {
    static constexpr std::size_t page_size = 1024u*1024u;
    // other data
};

struct U {
    static constexpr std::size_t page_size = 1024u*1024u;
    // other data
};
```

The type returned by `.raw()` is still a `T **` (or `U **`, it depends on the storage). However, the page size is such that a single call is all you need.
Of course, don't use `1024u*1024u` directly in a production code 😅 you want to refine this number a little probably, in order to hit a reasonable maximum number.

**Comment by LeifHenriksen** [comment]
Ok, I didn't know you could set the page size per component type, I thought the only option available was 
the `ENTT_PACKED_PAGE` macro.

So I tested this solution with entt 3.10.1 and I was getting consistent segmentation faults while iterating a group, I then upgraded to 3.11.0 and the crashes are gone. Is this normal behavior? Are there any rules to respect when changing the page size per component?

Bug aside, I think that being able to set the page size per component solves my problem.

Thanks

**Comment by skypjack** [comment]
> I tested this solution with entt 3.10.1 and I was getting consistent segmentation faults while iterating a group

That's interesting, this shouldn't be the case. 🤔 
I'd be curious to know why but I'm glad it's fixed in v3.11.
Let me know if you have any problems with the last version. I'm more than glad to look into them eventually.
Thank you very much!

> Is this normal behavior?

I wouldn't say so. 😅 

> Are there any rules to respect when changing the page size per component?

It **MUST** be a power of two. Otherwise it should assert at runtime (or even fail at compile-time, I don't remember the details but I bet on the first one).

> Bug aside, I think that being able to set the page size per component solves my problem.

👍 🥳

**Comment by LeifHenriksen** [comment]
The following code will reproduce the bug, compiled with `g++ -std=c++17 -g main.cpp`, entt version `3.10.1`, g++ `gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) `.

In my true code my bug appears in the second group iteration, but here it appears earlier.

```cpp
#include "entt.hpp"

struct vec2 {
	float x;
	float y;
};

struct position {
        // This causes the bug, if removed the programs finishes correctly 
	static constexpr std::size_t page_size = 1024u*1024u;
	vec2 vec;
};

struct physics {
	vec2 vel;
	vec2 acc;
	float forces;
};

struct health {
	int hp;
};

int main()
{
	entt::registry registry;
	for(auto i = 0u; i < 200000u; ++i) {
		const auto entity = registry.create();
		registry.emplace<position>(entity, i * 1.f, i * 1.f);
		registry.emplace<physics>(entity, i * 1.f, i * 1.f, i * 1.f, i * 1.f, i);
		registry.emplace<health>(entity, i + 100);
	}

	{
		auto group = registry.group<position, health, physics>();
		for(auto [entity, pos, health, physx] : group.each())
		{
                        // Random stuff
			if(health.hp <= 0) continue;
			pos.vec.x += physx.vel.x * 0.016f;
			pos.vec.y += physx.vel.y * 0.016f;
		}
	}

	{
		int dead = 0;
		auto group = registry.group<position, health>();
		for(auto [entity, pos, health] : group.each())
		{
                        // Do something
			if(health.hp <= 0)
				dead++;
		}

		printf("dead %d\n", dead);
	}

	return 0;
}
```

```sh
$ gdb ./a.out 
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./a.out...
(gdb) r
Starting program: /home/leif/projects/entt-bug/a.out 

Program received signal SIGSEGV, Segmentation fault.
0x000055555555664a in main () at main.cpp:38
38				pos.vec.x += physx.vel.x * 0.016f;
(gdb) bt
#0  0x000055555555664a in main () at main.cpp:38
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /home/leif/projects/entt-bug/a.out 

Program received signal SIGSEGV, Segmentation fault.
0x000055555555664a in main () at main.cpp:38
38				pos.vec.x += physx.vel.x * 0.016f;
(gdb) bt
#0  0x000055555555664a in main () at main.cpp:38
(gdb) q
A debugging session is active.

	Inferior 1 [process 45558] will be killed.

Quit anyway? (y or n) y
```

**Comment by skypjack** [comment]
Ah, probably it's not due to groups. You're likely hitting [this](https://github.com/skypjack/entt/pull/924) issue? A cherry-pick of the commit can get the job (or test 😅) done then.

**Comment by LeifHenriksen** [comment]
I tried with the callback and it works so I think it is indeed the same issue.
I already upgraded to the latest version so no reason to go back, just happy that we found the problem.

**Comment by skypjack** [comment]
Yup, thank you very much for helping here! Really appreciated.
