### ISSUE TITLE
Opaque structures no longer supported by locator API

### ISSUE THREAD

**Issue by sbhutch** [skypjack/entt#956]
Recent changes to the locator API prevent the locator from being initialised with an existing service. Now, the service may only be initialised via in-place construction. Overall, the changes to the locator API are great for encapsulation and simplicity, but has made it difficult (or impossible) to register an opaque structure as a service.

Consider the following example from the previous API, in which a shared_ptr pairs the creation and destruction of an SDL_Window (an opaque C-struct) via create/destroy functions. The shared_ptr is then assigned to the locator and the user can rest assured that the underlying type will be destroyed appropriately when the service is reset.

```cpp
std::shared_ptr<SDL_Window> window {
    SDL_CreateWindow(
        window_title,
        SDL_WINDOWPOS_CENTERED,
        SDL_WINDOWPOS_CENTERED,
        window_size.x,
        window_size.y,
        0),
    &SDL_DestroyWindow,
};

entt::service_locator<SDL_Window>::set(window);
```

I don't believe that the new locator API can support using an opaque structure as a service type anymore, as there is no way to attach the custom create/destroy functions, unless this can be achieved in a relatively simple way via a custom allocator?

I could create a wrapper class for the opaque type that will invoke the create/destroy functions, and register this as a service instead, but this feels more cumbersome and adds another layer of indirection. 

Do you have any thoughts on this?

**Comment by skypjack** [comment]
> Recent change

Define _recent_ 😅 do you mean the changes from February? 🙂 

> Do you have any thoughts on this?

I think you're right actually. It's likely a matter of making the `service_handle` public and using `reset` to inject it.

**Comment by skypjack** [comment]
Looking into this. What about a `construct` function that forwards its arguments directly to the `shared_ptr` constructor?
I kinda prefer this version rather than exposing the `shared_ptr` directly, mainly because we can still change the implementation details in future without having to also affect the API.

**Comment by sbhutch** [comment]
I agree that it would be best not to expose the underlying storage type in case you wish to change it in the future, but what do you imagine the signature of a `construct` function to be?

If it simply took variadic arguments and passed them to the `shared_ptr` constructor, then the user would need to understand what the underlying storage type is, and any changes to this type would need to be communicated.

```cpp
template <class... Args>
void construct(Args&&... args); // It is unclear exactly what needs to be provided here.
```

If the function explicitly took a raw pointer and deleter function, then the user would not need to know how it is stored internally, only that the locator becomes the owner of the pointer and it will be deleted appropriately.

```cpp
template <class Deleter = std::default_delete<T>>
void construct(T* service, Deleter deleter);
```

But, this would have a side-effect of restricting what underlying storage type you can use, i.e. you would not be able to use a `unique_ptr` because the deleter is part of the template signature.

**Comment by skypjack** [comment]
Fair enough. I feel that not exposing the `shared_ptr` isn't an option. 🤔 
The _loader_ model has the same problem after all. You still have to return a `shared_ptr` and therefore to know about the implementation details.
Any other idea or suggestion?

**Comment by sbhutch** [comment]
At least with the loader model you have the explicit `result_type` alias, so the user can't mistakenly assume that the internal type is anything else. I personally don't mind any of these solutions, I just like to play devils advocate. I also think it is fair enough if you would prefer not to support opaque structures directly as you would typically expect a C++ user to create raii wrappers for C library constructs anyway.
