### ISSUE TITLE
entt::flow::graph() causes crash if resources are set without binding a task

### ISSUE THREAD

**Issue by jdswebb** [skypjack/entt#957]
Example:

```
entt::flow f;
f.ro("test"_hs);
f.rw("test"_hs);
auto g = f.graph();
```

Stack:

```
>	sample_hierarchy.exe!std::exchange<unsigned __int64,unsigned int>(unsigned __int64 & _Val, unsigned int && _New_val) Line 725	C++
 	sample_hierarchy.exe!entt::adjacency_matrix<entt::directed_tag,std::allocator<unsigned __int64>>::insert(const unsigned __int64 lhs, const unsigned __int64 rhs) Line 308	C++
 	sample_hierarchy.exe!entt::basic_flow<std::allocator<unsigned int>>::graph() Line 279	C++
```

It would be better if this was caught and asserted rather than the current crash in `std::exchange`.

**Comment by skypjack** [comment]
To be done: also mention in the wiki that _if you re-use an id you just end up appending to the resources on that vertex rather than creating a new one_. 🙂

**Comment by jdswebb** [comment]
This was my fault for having disabled asserts and forgotten about it. I'll not close this in case you wanted the reminder for the second comment.

**Comment by skypjack** [comment]
Yeah. I'm adding some tests to avoid regressions and also a note in the documentation. 👍
