### ISSUE TITLE
EnTT really work on windows ? 

### ISSUE THREAD

**Issue by Milerius** [skypjack/entt#96]
Hey using vcpkg + entt 2.6.1

```cpp
  entity_registry_.each([this](auto entity) {
                this->entity_registry_.destroy(entity);
            });
````

this snippet doesn't compile with the following error
  ecs-test.cpp

c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(567): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(625): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(633): warning C4003: not enough actual parameters for macro 'max' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(756): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(552): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
  c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(901): note: see reference to class template instantiation 'entt::View<Entity,Component...>' being compiled
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(567): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(625): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(633): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(756): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]

**Comment by Milerius** [comment]
https://ci.appveyor.com/project/Milerius/shiva

**Comment by Milerius** [comment]
I found the problem I'm compiling with flags / permissive- https://docs.microsoft.com/en-us/cpp/build/reference/permissive-standards-conformance
on windows, it's a very important flag. (It seems that EnTT does not compile with / permissive- we could look at this. problem together if you want and try to solve it via another issue?

permissive-: 
Use this option to help you identify and fix conformance issues in your code, to make it both more correct and more portable.)

**Comment by skypjack** [comment]
So, Windows has a flag that makes our code more portable by rejecting valid code? :-D
Love it, really.

**Comment by Milerius** [comment]
i dont know but may be we can look together if you want, or report an error to MSVC team

**Comment by skypjack** [comment]
I was already looking at the error, but I don't know how to solve it.  
It looks like it considers malformed expressions like this one:

    return std::min({ pool<Component>().size()... });

Not sure about a workaround that doesn't affect everything.  
Any idea?

**Comment by Milerius** [comment]
If i reminder, std::min on windows is a macro, may be it's the problem, we can try to do our own min function and try with /permissive- to compile entt

**Comment by skypjack** [comment]
A macro? Why that? The language is mandatory about `std::min`, it's defined as a function template.  
I've used `std::min` all around in the codebase, this will break things a bit actually.  

Btw, if it's a macro, why it doesn't complain without permissive flag?

**Comment by Milerius** [comment]
It's does with /W4 msvc flags
`c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(567): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]`

**Comment by skypjack** [comment]
It seems [you can solve the problem](https://stackoverflow.com/questions/6884093/warning-c4003-not-enough-actual-parameters-for-macro-max-visual-studio-2010) your side by defining a macro that disable those macros (it makes me cry).  
Probably, if it solves, it's worth adding the macro in the configuration file for `EnTT`.  
Can you try it?

**Comment by skypjack** [comment]
This:

    #ifndef NOMINMAX
    #define NOMINMAX
    #endif

Should be put *before* any other `include`.  
I don't think it will work as expected if set by the configuration file of `EnTT`.

**Comment by Milerius** [comment]
yeah, it's totaly my fault i use a boost library in my project that include windows.h, and doesn't define NOMINMAX... it's not your fault i think..

**Comment by skypjack** [comment]
Don't worry, it's not a problem of my fault or your fault.  
I want to help you to solve your issue somehow. ;-)

**Comment by Milerius** [comment]
thanks ! i close the issue !
