### ISSUE TITLE
One entity with multiple 'same' type components

### ISSUE THREAD

**Issue by immerhart** [skypjack/entt#961]
I know that it is not possible to attach the same component multiple times to an entity.
I was wondering if it would possible through some C++ magic or whatever, though.

I tried it with:
```cpp
    struct struct1
    {
        int val = 0;
    };

    typedef struct1 struct2;
    using struct3 = struct1;

    auto entity = reg.create();
    reg.emplace<struct1>(entity);
    reg.emplace<struct3>(entity);
```
But it is still causing a runtime assert...
Is there another option I'm not aware of? I would like to avoid smth like:

```cpp
    struct struct1
    {
        int val = 0;
    };
    
    struct struct2
    {
        int val = 0;
    };
```

Thanks in advance!

**Comment by immerhart** [comment]
Came up with the following 
```cpp
    struct one {};
    struct two {};
    
    template<typename T>
    struct MultiComponent
    {
        int val;
    };

    auto entity = reg.create();
    reg.emplace<MultiComponent<one>>(entity);
    reg.emplace<MultiComponent<two>>(entity);
```

**Comment by immerhart** [comment]
> Came up with the following
> 
> ```c++
>     struct one {};
>     struct two {};
>     
>     template<typename T>
>     struct MultiComponent
>     {
>         int val;
>     };
> 
>     auto entity = reg.create();
>     reg.emplace<MultiComponent<one>>(entity);
>     reg.emplace<MultiComponent<two>>(entity);
> ```
Guess that is better, would be nice if the `MultiComponent` could be somehow iterated:
```cpp
        template<std::size_t N = 0>
        struct MultiComponent
        {
            int val;
        };
    
        auto entity = reg.create();
        reg.emplace<MultiComponent<>>(entity, 12);
        reg.emplace<MultiComponent<1>>(entity, 2);
        reg.emplace<MultiComponent<2>>(entity, 312);
        
        auto view = reg.view<MultiComponent<1>>();
        for(auto entity: view)
        {
            auto& comp = view.get<MultiComponent<1>>(entity);
            debug("{} has id: {}", comp.val, entity);
        }
```

**Comment by skypjack** [comment]
`using` declarations don't introduce new types (as in C++ types). That is why it doesn't work.
Your solution gets the job done instead. Another approach is to spawn multiple storage for the same type but with different _names_ as in:
```cpp
using namespace entt::literals;
auto &&storage1 = registry.storage<my_struct>("my_struct_1");
auto &&storage2 = registry.storage<my_struct>("my_struct_2");
```
Storage classes have roughly the same API of the registry:
```cpp
storage1.emplace(entity, arg1, arg2);
storage2.erase(entity);
```
And you can use them to construct views directly if you like:
```cpp
entt::view view{storage1, storage2};
```
Then you can also combine this view with others from the registry, as in:
```cpp
for(auto [entity, position, elem1, elem2]: registry.view<position>() | view) {
    // ...
}
```
The doc contains all the details btw. This should give you a grasp of the whole picture though. 👍

**Comment by immerhart** [comment]
> `using` declarations don't introduce new types (as in C++ types). That is why it doesn't work. Your solution gets the job done instead. Another approach is to spawn multiple storage for the same type but with different _names_ as in:
> 
> ```c++
> using namespace entt::literals;
> auto &&storage1 = registry.storage<my_struct>("my_struct_1");
> auto &&storage2 = registry.storage<my_struct>("my_struct_2");
> ```
> 
> Storage classes have roughly the same API of the registry:
> 
> ```c++
> storage1.emplace(entity, arg1, arg2);
> storage2.erase(entity);
> ```
> 
> And you can use them to construct views directly if you like:
> 
> ```c++
> entt::view view{storage1, storage2};
> ```
> 
> Then you can also combine this view with others from the registry, as in:
> 
> ```c++
> for(auto [entity, position, elem1, elem2]: registry.view<position>() | view) {
>     // ...
> }
> ```
> 
> The doc contains all the details btw. This should give you a grasp of the whole picture though. +1

Thanks for the answer (and the ECS :D)!
Do you refer to the Beam me up section (I think I skipped that)?

Does it produce overhead to use  N different storages, not sure what `Since the storage are also self-contained, the registry doesn't duplicate its own API for them` means.
Any idea on iterating over it (for creating and viewing), like in an array with unknown size?

**Comment by skypjack** [comment]
> Does it produce overhead to use N different storages

I mean, that is exactly what you're doing when you use `MultiComponent<1>` and `MultiComponent<2>`, isn't it? 🤷‍♂️ 

> Any idea on iterating over it (for creating and viewing), like in an array with unknown size?

Can you elaborate? Not sure I get what you mean. As mentioned above, you can construct views from the storage and iterate them as you would do with any other view.

**Comment by immerhart** [comment]
`MultiComponent<1>` and `MultiComponent<2>` will only add new components, I thought.
Creating N new stores sounds like overhead to me (are those stores not "big"?), if there are many same components on an entity (+ different entities which might have multiple same components again), but I don't know the internals...

I meant something like (which obviously does not work with templates and I didn't understand how to do it with the store approach):

```cpp
        template<std::size_t N = 0>
        struct MultiComponent
        {
            int val;
        };
    
        auto entity = reg.create();
        int size = 100;
        for(int i = 0; i < size;  i++)
            reg.emplace<MultiComponent<i>>(entity, randomInt());
        
        auto view = reg.view<const MultiComponent<GET_ALL_SOMEHOW>>();
        for(auto entity: view)
        {
            for(int i = 0; i < size; i++)
            {
                auto& comp = view.get<const MultiComponent<i>>(entity);
                debug("Entity {} has val: {}", entity, comp.val,);
            }
        }
```

I'm trying to represent a 2d-grid with multiple layers (should be used for building stuff, comparable to sim city, where you can build on ground and under it etc.).
And my idea was to have some kind of grid entity which holds many cell components, but maybe I shouldn't do it in the ECS, not sure...
What would you suggest? :)

**Comment by skypjack** [comment]
> `MultiComponent<1>` and `MultiComponent<2>` will only add new components, I thought.
> Creating N new stores sounds like overhead to me (are those stores not "big"?)

There is no difference. `MultiComponent<1>` and `MultiComponent<2>` are different types in C++. Same as let's say `position` and `velocity`. The fact that they _share_ part of the name doesn't really mean anything.

**Comment by skypjack** [comment]
> How would you iterate over the view and access each components data?

It's something along this line (for a non-empty `Name` type):
```cpp
auto join = reg.view<Name>() | entt::basic_view{ reg.storage<Name>(1), reg.storage<Name>(2) };

for(auto [e, n1, n2, n3] : join) { ... }
```

> How would this whole mechanic be used for dynamic size

Not sure I get what you mean. Let me know if I'm not on the right track.
You can iterate over all storage instances using `registry.storage()`, check their type info using `.type()` and test it against `entt::type_id<Name>()`. When you find a match, you've the storage, the id, all the entities and their components.
