### ISSUE TITLE
Get TypeName and not TypeSignature from type_info

### ISSUE THREAD

**Issue by MohitSethi99** [skypjack/entt#963]
`entt::type_id<ArcEngine::TransformComponent>().name().data();` results in `"struct ArcEngine::TransformComponent>(void) noexcept"`

Which is the signature I think, is there any way to get a compile time name which in this case should be: `"ArcEngine::TransformComponent"` or `"struct ArcEngine::TransformComponent"`

**Comment by skypjack** [comment]
`.name()` returns an `std::string_view`. You should use both `.data()` **AND** `.size()` to get the right portion of the original string.
If I get it correctly, this isn't what you did. Am I wrong?

**Comment by MohitSethi99** [comment]
My bad, using `std::string_view.data()` and `std::string_view.size()` or `static_cast<std::string>(std::string_view)` works. Thanks for the help, closing the issue.
