### ISSUE TITLE
registry.group() accepting entt::exclude as first argument

### ISSUE THREAD

**Issue by Net5F** [skypjack/entt#964]
Hello! I was having a random issue with groups returning the wrong entities, and I eventually tracked it down to my forgetting the first argument when instantiating a related group elsewhere:

```
// Correct
auto group = registry.group<position, velocity>({}, entt::exclude<renderable>);

// What I was doing (missing first argument)
auto group = registry.group<position, velocity>(entt::exclude<renderable>);
```

My problem is all fixed now, I just figured I would mention this in case there's a potential improvement to be made. Could attempting to use entt::exclude as a first argument fail at compile time instead?

**Comment by skypjack** [comment]
Since both `get_t` and `exclude_t` are [type aliases](https://github.com/skypjack/entt/blob/master/src/entt/entity/fwd.hpp#L99), it's not **that** easy to make it fail as you said. 😅
I'm sorry for that.

**Comment by Net5F** [comment]
Ah, makes sense, thanks! It won't be a problem for me now that I know, but I'm going to have users that might get tripped up by it. I'll just put a big note in my project's docs 😄
