### ISSUE TITLE
entt::basic_registry<uint64_t> causing bugs

### ISSUE THREAD

**Issue by hebohang** [skypjack/entt#972]
Hi, I want to use entt::basic_registry<uint64_t>, and then I can use the id to serialize in my file, and deserialize to the Entity. (I think uint32_t is not enough for the UUID, so I want to use uint64_t and pass straightly to entt like `mRegistry.create(uuid)`)

But it causes some bugs in here:
```
  /**
   * @brief Returns the identifier that occupies the given position.
   * @param pos Position of the element to return.
   * @return The identifier that occupies the given position.
   */
  [[nodiscard]] entity_type operator[](const size_type pos) const {
      return begin()[pos];
  }

  /**
   * @brief Returns the component assigned to the given entity.
   * @param entt A valid identifier.
   * @return The component assigned to the given entity.
   */
  [[nodiscard]] decltype(auto) operator[](const entity_type entt) const {
      return get<Component>(entt);
  }
```

bug: `error : functions that differ only in their return type cannot be overloaded`

As you can see, because the size_type (std::size_t) is same with the entity_type, which is the template argument of basic_registry.

My computer is Windows10 64bit environment.

How can I fix these and still use entt::basic_registry<uint64_t>? Hope for your help!

**Comment by hebohang** [comment]
It worked! Really appreciate your help!

**Comment by skypjack** [comment]
Well, this one was easy. 🙂 
I'm glad it worked.
