### ISSUE TITLE
How can I add a component instance directly to the entity?

### ISSUE THREAD

**Issue by hebohang** [skypjack/entt#973]
Hi, I have a new question that bothered me for a long time.

I construct a component, and want to connect to the entity like this:
```
entt::entity mEntityHandle = mRegistry.create();
ComponentA compA{ 1, 2, 3 };
mRegistry.add_component(mEntityHandle, compA);
```

But entt::registry doesn't have this method.

What I have tried:
```
template<typename T>
T& AddComponent(const T& component)
{
    T& comp = mRegistry.emplace_or_replace<T>(mEntityHandle);
    comp = component;
    return comp;
}
```

But it seems a little ugly and the component type must have default constructor function.

What can I do? Hope for your help.

**Comment by skypjack** [comment]
It's easier than this actually:
```cpp
entt::entity mEntityHandle = mRegistry.create();
mRegistry.emplace<ComponentA>(mEntityHandle, 1, 2, 3);
```
That is, tell to the registry what component it is and what arguments you want to forward to the constructor.

**Comment by hebohang** [comment]
> 

Thanks for your help. I know I can do this way, but since my component is deserialized from a json file, like this:
```
Comp comp;
Serializer::Deserialize(MyJsonFile, comp);
```
and I want to pass that comp to the entity in registry, and since the Comp is a template argument, I can't know its truly member.

**Comment by skypjack** [comment]
I mean, here you know the component type, is it?
```cpp
Comp comp;
Serializer::Deserialize(MyJsonFile, comp);
```
If this is the case, then you can still pass it to `emplace` as: `registry.emplace<Comp>(entity, comp)`.
Otherwise, a full picture of the problem would help a lot. 🙂

**Comment by hebohang** [comment]
Thanks for your help!

Here is my code:
![image](https://user-images.githubusercontent.com/60227429/212137998-6617309d-fe08-4dd5-9932-74dbffcb2707.png)

What have tried (it worked but seems a little ugly):
![image](https://user-images.githubusercontent.com/60227429/212138461-e7992df8-3789-43d7-b091-1c4e2be82b7a.png)

mEntityHandle is a member of Entity, and its type is entt::entity

And when I change my function like this:
![image](https://user-images.githubusercontent.com/60227429/212138265-ba123187-ad3e-4081-8521-5788d8a92884.png)

It will raise an error:
![image](https://user-images.githubusercontent.com/60227429/212138391-1e3afcac-edc4-46af-95e3-40401b635855.png)

At this time the T (component type) is TransformComponent:
![image](https://user-images.githubusercontent.com/60227429/212139629-ca75f32a-32a6-4fba-94bc-5bc28fa57de8.png)

**Comment by skypjack** [comment]
Maybe the entity already has the component? You can still use `emplace_or_replace` with the single line version if this is the case.

**Comment by hebohang** [comment]
Really appreciate your help! Its my mistake and I fixed it today. Your work is really excellent. Thank you again!
