### ISSUE TITLE
Error: ‘entt::registry’ {aka ‘entt::basic_registry<>’} is not a template

### ISSUE THREAD

**Issue by gvalderramos** [skypjack/entt#974]
Hey there!

I'm trying to use the entt::registry<uint64> like was solved in this another ticket:
https://github.com/skypjack/entt/issues/197

But it saying that entt::registry is not a template. How to solve it?

Thanks

**Comment by skypjack** [comment]
It's `entt::basic_registry`. If the goal is to use a custom entity type, it's:
```cpp
using my_registry_type = entt::basic_registry<my_entity_type>;
```

**Comment by skypjack** [comment]
After almost a week of inactivity, I guess this one is solved. Feel free to comment or reopen the issue if this isn't the case.
