### ISSUE TITLE
question about copying components from one entity to another

### ISSUE THREAD

**Issue by appletastesgood** [skypjack/entt#976]
Hi, I'm currently using release v3.11.1.
I've tried to copy components from one entity to another as below:

```c++
// source entity
entt::entity entity_camera_prototype = registry.create();
registry.emplace<component::Position>(e1, 0.0f, 0.0f, 0.0f);
registry.emplace<component::Camera>(e1, "HelloCamera");

// target entity
entt::entity entity_camera = registry.create();

// TODO: copy all components from the source entity to the target entity
my_utility::copy_components(registry, entity_camera_prototype, entity_camera);

...
```
I've read entt documentation but I still can't find good solution for this. The issue https://github.com/skypjack/entt/discussions/684 pretty fits in my use case but has a compile error in the recent release. (maybe because of the deprecation of `poly_storage` stuff) So is there a best way to implement the `my_utility::copy_components(...)`? It would be grateful if anyone could share their wisdom about this.

**Comment by skypjack** [comment]
Have you already seen [this](https://github.com/skypjack/entt/blob/master/test/example/entity_copy.cpp)?

**Comment by appletastesgood** [comment]
I didn't know there was a unit test code. That's the thing I was looking for, thanks!

**Comment by appletastesgood** [comment]
Ok, so I've checked out the test code, but there seems to have a problem. 
```c++
...
for(auto [id, storage]: registry.storage()) {
      if(id != "custom"_hs && storage.contains(src)) {
          storage.push(dst, storage.value(src));       // error : No member named 'push' in 'entt::basic_sparse_set<>'
      }
  }
...
```
do you have any clue for this?

**Comment by skypjack** [comment]
It's `emplace` in v3.11.x, I renamed it upstream to avoid name clashing.
The example is for `master`. You should check the same under the v3.11.x tag.

**Comment by appletastesgood** [comment]
OK, I've just updated the entt sources from `master` branch and it works great. Thanks!
