### ISSUE TITLE
any way chance to improve compile-time?

### ISSUE THREAD

**Issue by VictorQueiroz** [skypjack/entt#978]
I am using this library in my game and I have a huge compile-time. is there any way to improve that?

**Comment by skypjack** [comment]
Well, this boils down to good practices in C++ and it's hard to say how you can improve without looking at your code.
Just to throw a couple of ideas at you, you can avoid to use `entt.hpp` everywhere and start to use the forward files instead. 🤷‍♂️

**Comment by skypjack** [comment]
I'm closing the issue due to inactivity. Feel free to continue the discussion here anyway if you want/need.
