### ISSUE TITLE
Observer limited to 1048575 instances

### ISSUE THREAD

**Issue by CrankFlash** [skypjack/entt#979]
Hello,
I'm using EnTT 3.10.0 and I've come across a problem using an observer.
First, I'm creating something between 4 to 6 million entities with two components each, a std::map iterator (model), and a matrix (transform) :

```cpp
for (float z = -25.f; z < 5000.f && timer.total_time() < 1.f; z += .2f) {
    for (float x = -25.f; x < 25.2f; x += .2f) {
        entt::entity id = m_registry->create();
        m_registry->emplace<components::model>(id, model_cache_entry);
	m_registry->emplace<components::transform>(id, {x, 0.f, z});
	++m_instance_count;
        }
```

I also have an observer (models_observer) connected to this registry as follows :
```cpp
models_observer.connect(*m_registry,
                entt::collector
		    .group<model, transform>()
		    .update<model>()
		    .update<transform>());
```
When I query the observer after having emplaced all those instances :
```cpp
models_observer.size() == 1048575; //is true
//But I'm expecting ~4million
```

I iterate this observer after having created the 4 million instances in the first step, so my expectations are that the observer will contain the same number of entries, ~4 millions.
But that's not the case. There's a ceiling of precisely 1048757 instances maximum returned by the observer. Anything beyond that isn't recorded by the observer.

Am I using it wrong ?

**Comment by skypjack** [comment]
I see this:

> I'm creating something between 4 to 6 million entities

Then I see this:

> entt::entity id = m_registry->create();

If you consider that the default entity type is meant to support up to 1M entities (actually, 1M - 1 identifiers), I'm not surprised that you're experiencing UB everywhere.
If you want to spawn more than 1M elements, you must use a different entity type. There are a bunch of ways to customize it, among which a macro to make it use `std::uint64_t` or the possibility of using a custom entity class.
The documentation contains many details about it. Let me know if you've other problems. As it stands, the issue looks invalid otherwise.

**Comment by CrankFlash** [comment]
Thanks for the prompt response.

That's what I was thinking, but I couldn't find anything in the documentation. Besides, this particular example was a test bed to see how far it can be pushed. In actual real conditions, I only get to something like 200k-300k instances.
It's good to know there's an option to increase this limit though !

And thanks for EnTT !

**Comment by skypjack** [comment]
> It's good to know there's an option to increase this limit though !

You've at least three options actually. 😅 
* You can redefine `ENTT_ID_TYPE` to make it use `std:.uint64_t`.
* You can define your own entity type as an enum, then use it directly as:
  ```cpp
  enum class my_entity: std::uint64_t {};
  using my_registry = entt::basic_registry<my_entity>();
  ```
* Same as above but [with a class type](https://github.com/skypjack/entt/blob/master/test/example/custom_identifier.cpp#L6) to which you can also add more functionalities if you like.

All this just to scratch the surface of the possibilities that you've when it comes to customizing the identifiers. 🙂
