### ISSUE TITLE
Is there any way to insert an entity that has inheritance?

### ISSUE THREAD

**Issue by Tonyx97** [skypjack/entt#983]
I don't think the "poly" section is what I need, I just need to insert entities into a registry that have basic inheritance, for example, 2 components Position and Velocity:

```
struct test { bool valid = true; };

struct Position : test
{
	float x, y, z;
};
```

Can "poly" solve this? Thanks.

**Comment by skypjack** [comment]
Inserting isn't a problem, you can just use `emplace`. I guess what you want is to iterate both `T` and `U` through their commong base class `V` as in `for(auto entt: registry.view<V>()) { }` or similar? Otherwise I don't really get the meaning of this issue, sorry.

**Comment by Tonyx97** [comment]
I was wondering if you do that iteration but no that's not what I want, emplacing Position won't work when there it has a base class. It gives me the following error: '<function-style-cast>': cannot convert from 'initializer list' to 'Type'.
![image](https://user-images.githubusercontent.com/12673334/218548723-d8e5545f-a758-4840-a678-d6f370473c12.png)
the highlighted line is the one the error leads to. Also, since I'm here I want to ask, is there any way to pass a component instance with its on_create/on_destroy callback? When using those callbacks I want to know get the component instance and I can't register the callback with the instance parameter because it'd have been created and the callback would not be called at all.

**Comment by skypjack** [comment]
It looks like [the same](https://godbolt.org/z/4dcYdWhvb) idiosyncrasy (almost) why an `emplace_back` in an `std::vector` doesn't work either.
In this case, a constructor would get around the issue. However, I can't confirm it since [I can't reproduce](https://godbolt.org/z/ocbTbdxYh) your issue.
Can you provide a repro? Otherwise I can only guess what the problem is.

**Comment by Tonyx97** [comment]
Ah, didn't know emplace had the same idiosyncrasy, yeah a constructor fixed the issue. The reason why you couldn't reproduce the issue is probably because I have some wrapper in between that also uses templating and it might've messed with it but it's fixed now, thanks!
