### ISSUE TITLE
Is there any specific component in my entity?

### ISSUE THREAD

**Issue by 0LGL0** [skypjack/entt#987]
Hello, I would like to know how I can find out if there is a certain component in my entity. I know there used to be a "has" function, but now I can't find it. Thank you in advance for your answer

**Comment by Green-Sky** [comment]
yes, they are now called `.all_of<Component>(e)` and `.any_of<Component>(e)`

**Comment by 0LGL0** [comment]
@Green-Sky, thank you so much for your help
