### ISSUE TITLE
Organizer always returning a simple linear graph

### ISSUE THREAD

**Issue by RicardRC** [skypjack/entt#990]
I have three functions:
```
void processMessagesStatic(entt::view<entt::get_t<universe>>);
void queryGalaxies(entt::view<entt::get_t<const star>>, entt::view<entt::get_t<galaxy>>);
void updateCelestialOrbits(const entt::registry&, entt::view<entt::get_t<const orbit, position, const child_of>>);
```
registered with:
```
	organizer.emplace<&processMessagesStatic, galaxy>("processMessages");
	organizer.emplace<&queryGalaxies>("queryGalaxies");
	organizer.emplace<&updateCelestialOrbits, const pixiel::mass, const pixiel::tick>("updateCelestialOrbits");
```
And I get this graph:
![image](https://user-images.githubusercontent.com/35220750/223570643-b8fd5eca-7e4d-4cf5-ade6-8bc6ed3ac814.png)
I expected to have the node [0] with nodes [1] and [2] as reachable (so they run in parallel)

I have even tried to change the signature of queryGalaxies to:
`void queryGalaxies();`
And the result was still the same linear execution graph. (here I'd expect to have two root nodes with that empty signature).
Am I doing anything wrong, or maybe I'm missing something?

Thank you for the library!

**Comment by Green-Sky** [comment]
`organizer.emplace<&processMessagesStatic, galaxy>("processMessages");`
specifies `galaxy` as RW via overrides
and `void queryGalaxies(entt::view<entt::get_t<const star>>, entt::view<entt::get_t<galaxy>>);`
RW too. so they can't execute simultaniously. and then `const entt::registry&` in the 3rd, which is equivalent to everything RO. so it cant execute with any of the previous 2.

but i am more amazed by the fact, that you can have 2 views in the same system :O , i never realized that was possible!!

**Comment by RicardRC** [comment]
But query galaxies only has write on galaxy while not touching position, while updateCelestialOrbits only has RW on position while not writing anything else. This should be parallelizable, two different RW on components that the other system does not open in RO should be parallel, I  think. And const registry, should not be a problem. It's not called explicitly on the other systems, so by doc, this should be RO on all three systems, and thus, parallelizable. I might be wron, but I still don't see it, sorry :S

**Comment by Green-Sky** [comment]
you access `const entt::registry&` in updateCelestialOrbits -> EVERYTHING is now RO, and everything includes `galaxy`. 

so you access `galaxy` from all three, and two of those accesses are RW.

**Comment by RicardRC** [comment]
I don't know, you must be right, but I don't think it makes much sense if you do. If I need a non-const registry is because I'll do operations that might impact everything, like creating new entities or groups. But in any other case, I might want a const registry to check read only stuff, while modifying a component of type X in the same query, while other query modifies components Y or Z. From the docs on organizer, it does not stem anywhere that the registry is an special resource that locks everything else in the same mode. The only special think about the registry as an organizer resource that I see in the docs is that it's always present, in RO when implicit or defined, or RW when explicitly requested as non const. I don't see there any mention of any special status on that resource that overrides everything. And on multithreading using entt, everything I've seen written points to there being no problem in creating, modifying or destroying DIFFERENT types of component concurrently (and If I got it right, even modifying the same type of component concurrently, as long as the user makes sure to not edit the SAME component instance and not delete or insert new components). I'll wait for confirmation, if it's right what you say, I'll have to revert back to entt::flow, which is an order of magnitude more cumbersome to use and prone to user error.

**Comment by skypjack** [comment]
Hi, sorry for the late reply. I was out for a short vacation last week and also managed to get a flu in the meantime! 😅😭
I'm trying to keep up with all things today but this one requires a little more work. I'll look into it as soon as possible. 👍

**Comment by RicardRC** [comment]
I'm, also on the second week of "just a flu", and the baby has also caught it now, so I've been unable to be more helpful. When I get a chance, I'll try to cut the example to the minimum repro and switch function and variable names to something akin to your tests.

**Comment by Green-Sky** [comment]
D: guys, please get better soon

**Comment by skypjack** [comment]
> so you access galaxy from all three, and two of those accesses are RW.

That's correct. From what I see, `processMessagesStatic` requires galaxy as non-const and therfore blocks `queryGalaxies` which also requires the same type as non-const. Finally, `updateCelestialOrbits` gets a registry and thus it has access to all resources. This means also `queryGalaxies`, which forces a reschedule of the process after `queryGalaxies`.

> If I need a non-const registry is because I'll do operations that might impact everything, like creating new entities or groups

The upcoming version of EnTT puts entities in their own storage. That is, you can require a view for `entt::entity` rather than the whole registry, then use it to create or destroy entities as you like.
This should solve your problem I guess, since all other components are already accessible like this. Am I wrong?

**Comment by RicardRC** [comment]
Oh! I needed the registry only to constRegistry.ctx().get<pixiel::tick> (as const). Could that be accessed somehow else without requiring asking for the registy?
And also, having the entities in their own storage, if it allows creating and deleting them without asking for the registry as a resource, would certainly allow parallelizing a whole lot more, and is even better news than getting this particulat ctx parallelized or not.

Thanks skypjack and sorry Green-Sky for doubting you! Maybe the fact that asking for the registry counts as asking for everything should be added in the docs somewhere?

**Comment by RicardRC** [comment]
This still does not work as I expect. I've added three simple functions, without arguments or resources specified as additional emplace<> template types. They just to a "wait 50 ms".

I'm still getting a simple linear graph:
![image](https://user-images.githubusercontent.com/35220750/226198817-0ba59bc2-bdb1-4cdf-9cd1-1b0582e448d7.png)

Confirmed during execution with Tracy.

Maybe I'm doing something wrong? I take that the dependency is: from an edge on the graph, the function children returns all nodes that can run after the current one.
Anyways, this should have three roots, as there are no dependencies between anyone.

**Comment by Green-Sky** [comment]
>  sorry Green-Sky for doubting you!

don't worry, I'm used to that <.<

> Oh! I needed the registry only to constRegistry.ctx().getpixiel::tick (as const). Could that be accessed somehow else without requiring asking for the registy?

Yes, just put them into the system's function signature. [Example where I used it](https://github.com/Green-Sky/miniTD/blob/7869d318e8536a3ab63bacb7589c2347ae290342/src/systems/progress_enemies.hpp#L15)

**Comment by RicardRC** [comment]
> don't worry, I'm used to that <.<
Not ok! And I'm really sorry about contributing to that feeling.

> Yes, just put them into the system's function signature. [Example where I used it](https://github.com/Green-Sky/miniTD/blob/7869d318e8536a3ab63bacb7589c2347ae290342/src/systems/progress_enemies.hpp#L15)

You just put the component type there and that's it? It's magic! Thank you! I guess it's actually not as magical as the same happening with views, but it never crossed my mind to try. Do you know of a way of accessing named components this way? I'll probably just end up using a single one per component type, but I lose nothing by asking!

**Comment by Green-Sky** [comment]
> Do you know of a way of accessing named components this way? I'll probably just end up using a single one per component type, but I lose nothing by asking!

None that I am aware of. I don't think the `organizer` supports this right now.

**Comment by skypjack** [comment]
> Maybe the fact that asking for the registry counts as asking for everything should be added in the docs somewhere?

Fair enough. I was almost sure there was actually. 🤔 

> Do you know of a way of accessing named components this way?

Green-Sky is right. I'm slowly introducing support to named components all around. If you look at the commits on the `wip` branch, I'm decoupling groups from the registry now in order to also support multiple storage of the same type (that is what named components offer after all). So, yeah, it's just a matter of time and it will also reach the organizer. 🙂

**Comment by skypjack** [comment]
Ahaha, I guess this is my fault. Sorry. 😅 
I still have to look into the code but it seems to me that _empty functions_ (as in `void()` or similar) aren't fully tested nor correctly handled.
See [here](https://godbolt.org/z/jrzjE7zrK) for a (working) example based on the same code.
Today or tomorrow I'll try to run it locally and figure out why they're treated as sync points. It's probably a corner case without a proper test, at least this is my bet. 🙂

**Comment by skypjack** [comment]
I was wrong actually. I simply didn't remember an undocumented feature that seems to have been implemented on purpose.
The culprit is [this line](https://github.com/skypjack/entt/blob/master/src/entt/entity/organizer.hpp#L159) within the `organizer.hpp` file:
```cpp
builder.set(type_hash<Registry>::value(), requires_registry || (sizeof...(RO) + sizeof...(RW) == 0u));
```
The second parameter is also known as `is_rw`. An _empty function_, that is, a function that doesn't have dependencies is considered a sync point. I think the basic idea is: _if you don't want anything, it means you already have everything but I can't know what that everything is_. So, when in doubt, it's considered a sync point, that is the safest approach.

**Comment by RicardRC** [comment]
All makes sense now! Tested and looks beuatiful! 
![image](https://user-images.githubusercontent.com/35220750/226729661-8f74461f-37c7-49d4-babc-784e12f78d50.png)

Thank you both for your time and patience!
