### ISSUE TITLE
[[nodiscard]] warning on group

### ISSUE THREAD

**Issue by cschreib** [skypjack/entt#991]
Hello. I understand from the documentation that it is most efficient to create groups upfront, before any entity is added to the registry. I guess this means adding a dummy call to `registry::group` like so
```c++
// initialise registry and other stuf...

r.group<A,B,C>();

// add entities, create world, etc...

// later:
for (auto e : r.group<A,B,C>()) {
    // do stuff
}
```

Is that right? If so, currently `registry::group` is marked as `[[nodiscard]]`, which means the first line generates a warning. My understanding of `[[nodiscard]]` is that it should only be used if there is no good reason to ignore the return value (i.e., functions with no side effects) or when it is dangerous (i.e., likely to cause leaks etc.). But I don't think this is applicable in this case, because `registry::group` does have a side-effect (creating the group), hence it makes sense to call it and ignore the return value if we're only interested in the side-effect.

**Comment by skypjack** [comment]
Fair enough. 🙂👍
