### ISSUE TITLE
Invalid identifier appears when I try to delete an entity，I just call the destory method after creating the entity

### ISSUE THREAD

**Issue by Playerrrrrr** [skypjack/entt#993]
version_type release(const entity_type entt, const version_type version) {
			ENTT_ASSERT(valid(entt), "Invalid identifier");
			ENTT_ASSERT(std::all_of(pools.cbegin(), pools.cend(), [entt](auto &&curr) { return (curr.second->current(entt) == entity_traits::to_version(tombstone)); }), "Non-orphan entity");
			return release_entity(entt, version);
		}

**Comment by Green-Sky** [comment]
can you please share your code / your api usage ? as far as i can tell, the entt code seems good.

**Comment by Playerrrrrr** [comment]
entt::enttity m_Handle = m_Register.create();
///////
Just save and add components and call components
//////
m_Register.destory(m_Handle)
...and wrong

**Comment by Green-Sky** [comment]
hm, looks correct.
are you sure you dont modify the value of m_Handle?
are you sure you dont call .destroy() inbetween?

**Comment by Playerrrrrr** [comment]
If you say that, there must be a solution. I'm relieved,

**Comment by Playerrrrrr** [comment]
Thank you. Let me check my code again

**Comment by Playerrrrrr** [comment]
I know what the problem is. I tried to delete the submitted enttity at the end of the frame, but I did not delete the destory enttity in the queue, resulting in repeated deletion

**Comment by skypjack** [comment]
This is very likely the case then. The identifier is recycled when you destroy it the first time. Therefore, the second time you get the _invalid identifier_ error as it ought to be. 👍
