### ISSUE TITLE
Get name by meta id_type

### ISSUE THREAD

**Issue by MohammadMDSA** [skypjack/entt#996]
Hi,
I have a type which itself and its properties are registered as meta type. I can iterate over its properties (data), however, I don't have any access to property names. While I do have access to each property id_type, I wanted to ask if it is possible to convert id_type ("foo"_hs) to an actual string (to "foo")?

**Comment by skypjack** [comment]
`EnTT` doesn't store aside names for your meta objects automatically. You can use meta properties for that though:
```cpp
entt::meta<T>()
    .data<T::x>("x"_hs).prop("name"_hs, "x")
    .data<T::y>("y"_hs).prop("name"_hs, "y");
```
As for the type info, that's the declaration type of the data member. That is, for `int x` it would be `int` and not `x`. So, converting it doesn't really help.
