### ISSUE TITLE
``exclude_t``, ``get_t`` and ``owned_t`` should be strong types

### ISSUE THREAD

**Issue by DNKpp** [skypjack/entt#998]
Hey,
as already pointed out on the discord, the mentioned types should be strong types instead of simple aliases.

During my upgrade from ``v3.10.3`` to ``v3.11.1`` I detected a regression in one of my systems. It took me some time to get to the root cause, but its simply due to the conversion of these types from dedicated structs to aliases.

Here is a very minimal example, how this affects the desired behaviour of ``entt::registry::group``: https://godbolt.org/z/sYoaePvoj

**Comment by skypjack** [comment]
It's not that smooth unfortunately because views use `type_list_transform` under the hood to convert component lists to storage lists.
